### ISSUE TITLE
Reverse geocoding fails to provide municipality in Norway

### ISSUE THREAD

**Issue by kvolden** [osm-search/Nominatim#1017]
Previously, when doing reverse geocoding in Norway, the municipality was given with the "county" key, and the county was given with the "state" key. Just like it currently is in Sweden and Denmark. But recently, the tag place=county was added to all Norwegian counties, and place=municipality was added to all Norwegian municipalities. It looks like the right thing to do for many reasons, but this seems to have broken reverse geocoding in that area.

After the change, the county is given with the "county" key, and the municipality is not given at all. I would expect the municipality to be given with a "municipality" key. The municipality is actually in the "display_name" string, but it does not appear in the "address" object.

**Comment by lonvia** [comment]
A concrete example would be helpful.

**Comment by kvolden** [comment]
Sure thing. Pretty random position coming up.

URL: https://nominatim.openstreetmap.org/reverse?format=json&addressdetails=1&accept-language=nb,no&lat=62.5942286&lon=9.6707428

Response:
`{"place_id":"42573356","licence":"Data © OpenStreetMap contributors, ODbL 1.0. https:\/\/osm.org\/copyright","osm_type":"node","osm_id":"3112427889","lat":"62.5938917","lon":"9.6708134","display_name":"3B, Soleivegen, Kåsa, Mjøa-grenda, Oppdal, Trøndelag, 7340, Norge","address":{"house_number":"3B","road":"Soleivegen","neighbourhood":"Kåsa","hamlet":"Mjøa-grenda","county":"Trøndelag","postcode":"7340","country":"Norge","country_code":"no"},"boundingbox":["62.5937917","62.5939917","9.6707134","9.6709134"]}`

As you can see, all the elements in `display_name` are broken down with their own keys in `address` except for the municipality Oppdal.

If you look up the county, Trøndelag, (or any Norwegian county) in nominatim, you will see that its rank translates to "state", but it has a place=county tag. And if you look up the municipality, Oppdal, (or any Norwegian municipality) you will see that its rank translates to "county", but it has a place=municipality tag. URLs below:

https://nominatim.openstreetmap.org/details.php?place_id=179333864
https://nominatim.openstreetmap.org/details.php?place_id=177839342

**Comment by lonvia** [comment]
See #1080. Closing here.
