### ISSUE TITLE
Place with postalcode=... not found

### ISSUE THREAD

**Issue by foodev** [osm-search/Nominatim#1028]
When I search for a place with `postalcode=16356&city=Werneuchen` I won't get any results:

https://nominatim.openstreetmap.org/search.php?format=json&countrycodes=de&postalcode=16356&city=Werneuchen

```json
[]
```

But when I remove the `postalcode` parameter, I get the correct result (among others):

https://nominatim.openstreetmap.org/search.php?format=html&countrycodes=de&city=Werneuchen

```json
[{"place_id":"179025849","licence":"Data © OpenStreetMap contributors, ODbL 1.0. https:\/\/osm.org\/copyright","osm_type":"relation","osm_id":"1318353","boundingbox":["52.5784223","52.7136828","13.6374307","13.8587715"],"lat":"52.6334769","lon":"13.7340939","display_name":"Werneuchen, Landkreis Barnim, Brandenburg, Deutschland","class":"boundary","type":"administrative","importance":0.21723658035362,"icon":"https:\/\/nominatim.openstreetmap.org\/images\/mapicons\/poi_boundary_administrative.p.20.png"}]
```

Though the corresponding node has the postcode:

https://nominatim.openstreetmap.org/details.php?place_id=157634

**Comment by JLuc** [comment]
I confirm same issues for french area cf https://github.com/openstreetmap/Nominatim/issues/1239 : 

In some cases, nominatim **fails when being provided both city and postalcode** : 
https://nominatim.openstreetmap.org/search?postalcode=40430&city=Argelouse&format=json&limit=1&countrycode=fr

But it succeeds and finds the right place when provided **only with city name** :
https://nominatim.openstreetmap.org/search?city=Argelouse&format=json&limit=1&countrycode=fr

```
[{ "place_id": "199026058", 
"licence": "Data © OpenStreetMap contributors, ODbL 1.0. https://osm.org/copyright",
"osm_type": "relation", "osm_id": "2114363",
"boundingbox": [ "44.345529", "44.4001763", "-0.672487", "-0.599563" ],
"lat": "44.3671374", "lon": "-0.6449692",
"display_name": "Argelouse, Mont-de-Marsan, Landes, Nouvelle-Aquitaine, France métropolitaine, 40430, France",
"class": "boundary", "type": "administrative", 
"importance": 0.637409167502591,
"icon": "https://nominatim.openstreetmap.org/images/mapicons/poi_boundary_administrative.p.20.png" }]
```

As shown in the result, **the found postalcode (that appear in the display_name) is the right one**, so it is known and correct. 

Why did the first exact and fully detailed request fail ? 

IMO it should succeed.

Same with CP=10000 and city=Troyes, allthough this is quite important a city (prefecture du département).
https://nominatim.openstreetmap.org/search?postalcode=10000&city=TROYES&format=json&limit=1&countrycode=fr

**Comment by JLuc** [comment]
@lonvia i dont understand your comment. Can it helps with my issue ? As for now i test with postal code and city, and when it fails, i test again without postal code... :-/

**Comment by JLuc** [comment]
I have more examples of this issues in France.

In some cases, there is a way to fix it : state the departement number as 'state'

- CP + town = :-1: no result : https://nominatim.openstreetmap.org/?city=Voussac&limit=1&countrycodes=FR&format=json&accept-language=fr&postalcode=03140

- CP + town + state = :+1: found  with https://nominatim.openstreetmap.org/?city=Voussac&limit=1&countrycodes=FR&format=json&accept-language=fr&postalcode=03140&state=03

Stating 'state=40' also succeeds with previous Argelouse issue :+1:  = https://nominatim.openstreetmap.org/search?postalcode=40430&city=Argelouse&format=json&limit=1&countrycode=fr&state=40

But stating 'state=10' does NOT help with previous Troyes example :-1:  with
https://nominatim.openstreetmap.org/search?postalcode=10000&city=TROYES&format=json&limit=1&countrycode=fr&state=10

I could not find documentation on using departement number as state.

**Comment by promosrene** [comment]
Recently, the search with postcode and city does not return any results with postcode or returns incorrect results. Searching only with postcode, on the other hand, returns a correct result with city and postcode. 

correct:
[https://nominatim.openstreetmap.org/search.php?format=xml&addressdetails=1&limit=10&postalcode=90429&country=DE](https://nominatim.openstreetmap.org/search.php?format=xml&addressdetails=1&limit=10&postalcode=90429&country=DE)

Result without postcode when searching with city:
[https://nominatim.openstreetmap.org/search.php?format=xml&addressdetails=1&limit=10&postalcode=90429&country=DE&city=N%C3%BCrnberg](https://nominatim.openstreetmap.org/search.php?format=xml&addressdetails=1&limit=10&postalcode=90429&country=DE&city=N%C3%BCrnberg)

result with wrong postcode - search for 10179 - recieve result with 10177:
[https://nominatim.openstreetmap.org/search.php?format=xml&addressdetails=1&limit=10&postalcode=10179&country=DE&city=berlin](https://nominatim.openstreetmap.org/search.php?format=xml&addressdetails=1&limit=10&postalcode=10179&country=DE&city=berlin)

but search without city, works:
[https://nominatim.openstreetmap.org/search.php?format=xml&addressdetails=1&limit=10&postalcode=10179&country=DE](https://nominatim.openstreetmap.org/search.php?format=xml&addressdetails=1&limit=10&postalcode=10179&country=DE)

**Comment by lonvia** [comment]
Looks to be working these days.
