### ISSUE TITLE
house numbers in one street are only found if city is omitted or "Gemeinde" (municipality) is added to the city name

### ISSUE THREAD

**Issue by Luzandro** [osm-search/Nominatim#1037]
When searching for "Velmerstraße 6, Münchendorf" (or any other house number in this street), the house number cannot be found and you only get a small segment of the street as result

https://nominatim.openstreetmap.org/details.php?place_id=107817971

https://nominatim.openstreetmap.org/search.php?q=Velmerstraße+6%2C+Münchendorf&polygon_geojson=1&viewbox=

If you change the query to "Velmerstraße 6, Gemeinde Münchendorf" or omit the city completely and only search for "Velmerstraße 6" the house number is found

As far as I've seen, this issue doesn't apply to other streets

**Comment by lonvia** [comment]
Partial search now works better.
