### ISSUE TITLE
addressdetails is practically useless

### ISSUE THREAD

**Issue by lonvia** [osm-search/Nominatim#1080]
There is no standardized way in OSM to make a connection between admin_level and place type. Nominatim uses a one-size-fits-all solution that works in some countries but not all. As address details require a correct identification of the kind of place for boundaries, the details are often confusing in this case.

Solving this issue involves completely redesigning how address ranks are handled as well as localized handling of objects (see #213).

**Comment by InI4** [comment]
@lonvia, for our purpose we could actually use the <result> element. Well, nearly. Splitting a string by commas always has a smell and we have come across regions (in Greece I think) where the region name contains a comma, which would break such an effort.

So if Nominatim could just pump out the `<result>` as machine readable, machine separated list, i.e. `<resultList><part1>..</part1><part2>..</part2></resultList>`, this would relieve a lot of our pain here, as we could figure the address ourselves in many cases! As a new section, it should also not break existing client code.

**Comment by kvolden** [comment]
Is there work being done on this? I had a more specific issue, #1017, that seems like a straight up bug more than some deeper inconsistency issue (but I could be mistaken). Summarized, the `display_name` string in the response contains an element that does not show up as an element in the `address` object. More specifically, it's the municipality. All other elements of `display_name` are always also in the `address` object as far as I can tell. And as luck would have it, it is the municipality I need. More details are in the now closed ticket.

Can i just forget about this being fixed within a reasonable amount of time? I'm wondering if I need to switch to Google's unfree services for this, or if I just need to wait it out a little bit.

**Comment by lonvia** [comment]
It gets fixed when it gets fixed. The only way to get it fixed faster is to invest into development yourself. That's what Open Source means, it doesn't mean that you get all you need for free.

That said have a look at the new [geocodejson format](http://nominatim.org/release-docs/develop/api/Output/) and there at `admin` in particular. It might help with your particular use case.

**Comment by kvolden** [comment]
> It gets fixed when it gets fixed. The only way to get it fixed faster is to invest into development yourself. That's what Open Source means, it doesn't mean that you get all you need for free.

And I would if I could. I simply asked if this is being worked on, I didn't demand an immediate fix. No need for an attitude, quite frankly.

> That said have a look at the new geocodejson format and there at admin in particular. It might help with your particular use case.

Thank you. I'll have a look.

**Comment by lonvia** [comment]
Sorry, I shouldn't have snapped but frankly I'm getting a bit wary on the different variations of 'fix this or I switch to Google' theme.

So to answer your question: yes, it is being worked on but it's a rather difficult topic and currently in a very early design stage. I couldn't say when it will be fixed but we are certainly talking months, if not years.

**Comment by kvolden** [comment]
> Sorry, I shouldn't have snapped but frankly I'm getting a bit wary on the different variations of 'fix this or I switch to Google' theme.

I totally get that. In my case, it is simply a neutral explanation of my situation. It is not a threat. I do not feel entitled. It simply _is the case_ that I need this functionality, and that it is a blocker. Hence my wondering if I should (reluctantly) do the work of switching to Google and switch back later, or wait until this works. Now, maybe some others feel entitled and use the possibility of switching to Google as a threat, but I suspect most situations are sort of like mine, and that you shouldn't assume ill will. :)

Happily and luckily, the geocodejson format looks like it solves my problems. Thanks for pointing me to it.

**Comment by lonvia** [comment]
Should be better now, especially for the geocodejson format. Probably still needs minor adjustments for specific countries.
