### ISSUE TITLE
Search for housenumber in a range

### ISSUE THREAD

**Issue by richardbrinkman** [osm-search/Nominatim#111]
When a building is tagged with, say, addr:housenumber=20-40, nominatim can only find the building if you search for the housenumber 20 or 40, whereas it should be possible to find the building for any housenumber in the range (while taking addr:interpolation into account, ofcourse).

**Comment by cwmke** [comment]
Users (myself included) have been using a range for the addr:housenumber and then adding the addr:interpolation tag to demonstrate it is a range. Is this an acceptable alternative? For tagging it is much simpler and faster but currently it does not provide results when searching between the range.
