### ISSUE TITLE
strange error with Nominatim/module/nominatim.so

### ISSUE THREAD

**Issue by SoulRaven** [osm-search/Nominatim#116]
i get this errors, and i don't have the slightest ideea,

COPY_END for place failed: ERROR:  incompatible library "/opt/Nominatim/module/nominatim.so": version mismatch
DETAIL:  Server is version 9.3, library is version 9.1.
CONTEXT:  PL/pgSQL function make_standard_name(text) line 5 at assignment

i am running postgresql 9.3

**Comment by yeahframeoff** [comment]
@lonvia I am facing the same issue a.t.m. as the author was, but in the following saying it is unclear, should I either recompile `postgres` or `nominatim`:
> Make sure you remove the server development libraries (`postgresql-server-dev-9.1` on Ubuntu) and recompile (`./configure && make`).
