### ISSUE TITLE
details endpoint returns wrong distance in linked places

### ISSUE THREAD

**Issue by mtmail** [osm-search/Nominatim#1174]
Unterisling https://nominatim.openstreetmap.org/details.php?osmtype=N&osmid=774475247
and
Piesenkofen https://nominatim.openstreetmap.org/details.php?osmtype=N&osmid=46828474
are places near Regensburg, about 3km apart.

![image](https://user-images.githubusercontent.com/3727288/45392164-70116200-b626-11e8-818e-d247cb905ec9.png)

The "Address" (`$aAddressLines`) section on the Unterisling details page shows a distance of 0 (rounded for readability in `details-html.php`). The JSON output https://nominatim.openstreetmap.org/details.php?osmtype=N&osmid=774475247&format=json&addressdetails=1 shows the raw 0.03749
```json
{
  "localname": "Piesenkofen",
  "place_id": 225941,
  "osm_id": 46828474,
  "osm_type": "N",
  "class": "place",
  "type": "village",
  "admin_level": 15,
  "rank_address": 16,
  "distance": 0.0374950127950353
},
```

`website/details.php` uses `Nominatim\AddressDetails->getAddressDetails(true)` which itself uses `get_addressdata` from `functions.sql`. I haven't found the exact line, but I believe `ST_Distance` https://postgis.net/docs/manual-2.4/ST_Distance.html is used without the `use_spheroid` set to true. 

It's unexpected because for the linked place on the details page we use `ST_DistanceSpheroid` https://postgis.net/docs/manual-2.4/ST_Distance_Spheroid.html which returns a distance in meters. It's also not human readable and that's the main purpose of the details page output.

@lonvia Can you suggest where the distance should be recalculates? `details.php`, `AddressDetails` or even change to `functions.sql` ?

```SQL
SELECT
    -- name1, ST_X(geometry1), ST_Y(geometry1),
    -- name2, ST_X(geometry2), ST_Y(geometry2),
    ST_Distance(
        geometry1,
        geometry2
    ) as distance,
    ST_DistanceSpheroid(
        geometry1,
        geometry2,
        'SPHEROID["WGS 84",6378137,298.257223563, AUTHORITY["EPSG","7030"]]'
    ) as distance_meters
FROM
    (SELECT name->'name' AS name1, geometry AS geometry2
        FROM placex
        WHERE osm_type='N' AND osm_id=774475247
    ) AS one,
    (SELECT name->'name' AS name2, geometry AS geometry1
        FROM placex
        WHERE osm_type='N' AND osm_id=46828474
    ) AS two;

      distance      | distance_meters
--------------------+------------------
 0.0374950127950353 | 3200.67719094061
```

**Comment by lonvia** [comment]
We can't fix this in `functions.sql` directly. Address details are requested with almost every `reverse` request and there must not be anything in that part of the code that makes it slow. So, the distance should be computed somewhere in the details code. A custom Haversine function would be an option but requires the centroids which we don't export either in the address details at the moment. So I'd say have another DB query in details, which just gets the spheroid distances.

Or just remove the distances completely from the address table, they don't add a lot of information.

**Comment by lonvia** [comment]
To add to that: if you do an extra query: only do this for place nodes. If the address part is an area, then the given point must always be inside, so the distance is always 0.

**Comment by lonvia** [comment]
I've looked into this issue again because I needed the distance when debugging #2674. `distance` returns the corresponding of place_addressline column. This is the correct behaviour. The details endpoint is meant as a debugging tool to show the contents of the database. 

So I'm closing this as 'works as expected'.  We need to fix the extensive rounding in nominatim-ui because distances are usually small and probably should just present the raw value without any units attached.
