### ISSUE TITLE
Direct lookup of existing node returns empty metadata

### ISSUE THREAD

**Issue by tlongers** [osm-search/Nominatim#1222]
Thanks for crafting this tool everyone. First time reporting a problem with it, so thanks in advance for your attention. I was [redirected here from OSM Help](https://help.openstreetmap.org/questions/66613/node-exists-on-osm-but-nominatim-lookup-returns-empty).

Here's the issue:

If a node exists on OSM, I would expect to be able to retrieve its metadata through a lookup on Nominatim. I'm confused by why it doesn't work in this case:

1. Node exists: https://www.openstreetmap.org/node/1984103891
2. Node metadata exists: https://www.openstreetmap.org/api/0.6/node/1984103891
3. Node is linked to Place in Nominatim: https://nominatim.openstreetmap.org/details.php?place_id=20053249
4. BUT nothing returned from a node lookup Nominatim: https://nominatim.openstreetmap.org/lookup?osm_ids=N1984103891

If this is expected behaviour, can someone explain the logic to me?

Thanks again.

**Comment by lonvia** [comment]
The node is a linked node, meaning that it is linked to an area which serves as the main object.

For search and reverse we simply return the area object in such a case. This doesn't really work here because information about the node was specifically requested. So this needs some on-the-fly merging of data. Use the base information from the node and any derived information (address at least, possibly other) from the linked area.

**Comment by tlongers** [comment]
Thanks @lonvia. Why not also cover the case where there is a direct lookup of the node, replicating the data derived from the linkage so it attaches to the node also?

**Comment by simonm3** [comment]
Is there some reason for the distinction between an area and a linked node? I am looking at a cluster of villages in Nigeria. They are clearly distinct settlements as can be seen from the buildings and roads; and they are labelled correctly in OSM. However the reverse geocode lookup labels the whole area together - about 15km by 10km.

**Comment by mtmail** [comment]
@simonm3 Please open a new issue with specific example. https://github.com/openstreetmap/Nominatim/blob/master/CONTRIBUTING.md#when-reporting-bad-search-results
