### ISSUE TITLE
City name not appearing in search

### ISSUE THREAD

**Issue by raulperez** [osm-search/Nominatim#1262]
Hi 

I have a problem with city names not appearing in the json when searching for an address.

It happens with many addresses, but here it is an example. The right city name is Virum, and I get Sorgenfri. If I use debug=1 param I can see Virum in the addresses tags list, but not in the json.

https://nominatim.openstreetmap.org/search?q=kongevejen+135a+2830+virum&format=jsonv2&addressdetails=1

When I call the link below to get the node info I can see addr:city = Virum as HTML.

https://www.openstreetmap.org/node/340718525

But If I make a lookup like the link below, I cannot:

view-source:https://nominatim.openstreetmap.org/lookup?format=xml&osm_ids=N340718525&namedetails=1&extratags=1&addressdetails=1&dedupe=0&debug=0

I can just see the city if I call this kind of link:

https://www.openstreetmap.org/api/0.6/node/340718525

Is there a way of getting the city name in the search query?

Thanks in advance.

Raúl Pérez

**Comment by raulperez** [comment]
From the link https://nominatim.openstreetmap.org/details.php?osmtype=N&osmid=340718525&class=place I can see in the Address Tags Virum (city) is there a way of accessing that tag from the json?

**Comment by mtmail** [comment]
You can add `&format=json` to the URL.

**Comment by lonvia** [comment]
I agree, basically a problem of missing exact boundaries. #148 might help. So closing in favour of that.

**Comment by lonvia** [comment]
The fix for #148 only works when areas are involved. So reopening this as a reminder to also find a solution for place nodes.
