### ISSUE TITLE
Display address is inconsistent when crossing boundaries

### ISSUE THREAD

**Issue by kobi-wan** [osm-search/Nominatim#1400]
I found two points in Germany, where nomination delivers a wrong state attribute.
First one is:
https://nominatim.openstreetmap.org/reverse?format=json&lat=53.02828&lon=8.933256&accept-language=en&addressdetails=1

Which returns:
{"place_id":179125997,"licence":"Data © OpenStreetMap contributors, ODbL 1.0. https://osm.org/copyright","osm_type":"way","osm_id":478793738,"lat":"53.0283197060677","lon":"8.9332646642824","display_name":"A 1, Mahndorf, Hemelingen, Stadtbezirk Bremen-Ost, Achim, Bremen, Lower Saxony, 28307, Germany","address":{"road":"A 1","neighbourhood":"Mahndorf","suburb":"Hemelingen","city_district":"Stadtbezirk Bremen-Ost","town":"Achim","city":"Bremen","state":"**Lower Saxony**","postcode":"28307","country":"Germany","country_code":"de"},"boundingbox":["53.0272783","53.0292419","8.9302322","8.9568636"]}

=> state should be the same as the city "Bremen".

---
The second one is:
https://nominatim.openstreetmap.org/reverse?format=json&lat=49.633598&lon=9.273487&accept-language=en&addressdetails=1

Which returns:
{"place_id":89635259,"licence":"Data © OpenStreetMap contributors, ODbL 1.0. https://osm.org/copyright","osm_type":"way","osm_id":53840747,"lat":"49.6340219521602","lon":"9.27383738299715","display_name":"B 47, Schneeberg, Verwaltungsverband Hardheim-Walldürn, Landkreis Miltenberg, Lower Franconia, Baden-Württemberg, 63936, Germany","address":{"road":"B 47","suburb":"Schneeberg","village":"Schneeberg","county":"Verwaltungsverband Hardheim-Walldürn","state_district":"Lower Franconia","state":"**Baden-Württemberg**","postcode":"63936","country":"Germany","country_code":"de"},"boundingbox":["49.6254243","49.6408555","9.2615423","9.2889123"]}

=> "Schneeberg (Unterfranken)" belongs to state "Bayern", although the point is located in state "Baden-Württemberg".

kobi

**Comment by mtmail** [comment]
A road (OSM way) is only assigned one hierarchical parent (city, whose parent is a county, then state etc) in Nominatim. It depends roughly on where the middle point of the length of the road (way) is location. When it crosses an administrative boundary it is not split into two database records. During search we don't want to check every road if it crosses various boundaries.

Of course in OSM data you can split the way into two. I've done that before when houses were assigned a wrong country. But with states and no houses nearby I wonder if that's really needed.

To query only the state you can set the zoom parameter. http://nominatim.org/release-docs/latest/api/Reverse/#parameters has a table of possible values. https://nominatim.openstreetmap.org/reverse?format=json&lat=53.02828&lon=8.933256&accept-language=en&addressdetails=1&zoom=8 or zoom=5 will show the state of Bremen.

**Comment by lonvia** [comment]
To add to what @mtmail says, Nominatim does notice that the road goes through two Bundesländer and two Kreise. This can be seen in the [details view](https://nominatim.openstreetmap.org/details.php?osmtype=W&osmid=478793738&class=highway). When displaying the address it needs to choose one of the two. The problem here is that it does not choose very consistently and mixes the city of Bremen with the state of Lower Saxony. I think we could do better here. The information is there.

I've adapted the title to reflect the underlying problem.

**Comment by kobi-wan** [comment]
Here is another location:
https://nominatim.openstreetmap.org/reverse?format=json&lat=48.4571&lon=10.18964

{"place_id":142884796,"licence":"Data © OpenStreetMap contributors, ODbL 1.0. https://osm.org/copyright","osm_type":"way","osm_id":289838393,"lat":"48.4570991473227","lon":"10.1896398022366","display_name":"A 8, Leipheim, GVV Langenau, Landkreis Günzburg, Schwaben, Baden-Württemberg, 89340, Deutschland","address":{"road":"A 8","town":"Leipheim","county":"GVV Langenau","state_district":"Schwaben","state":"Baden-Württemberg","postcode":"89340","country":"Deutschland","country_code":"de"},"boundingbox":["48.4534877","48.4594773","10.1700603","10.1987858"]}

=> Leipheim / Schwaben is located in Bayern
