### ISSUE TITLE
Thai transliteration is bogus

### ISSUE THREAD

**Issue by nachanon** [osm-search/Nominatim#1406]
I have recently made [an edit](https://www.openstreetmap.org/changeset/71470236) on OpenStreetMap that added Thai initials (abbreviation) for _[Thailand Creative and Design Center (TCDC)](https://www.openstreetmap.org/node/4840964126)_ via its [`alt_name:th`](https://wiki.openstreetmap.org/wiki/Key:alt_name) key to improve its searchability. This initials is (officially) not separated by space or dots.

After waiting several minutes for Nominatim instance on OpenStreetMap.org to update its index, I conducted a test search on said initials <q>`ศสบ`</q> verbatim on both main OpenStreetMap.org and nominatim.openstreetmap.org debug interface. As the search term is relatively obscure, I expected that <q>_TCDC_</q> would come up as a sole result (or one of the few results) as it is supposed to be an exact match.

However, the result came up with a huge list of foreign POIs which are not remotely related to what I intended to find...

- [OpenStreetMap.org main interface](https://www.openstreetmap.org/search?commit=Go&query=%E0%B8%A8%E0%B8%AA%E0%B8%9A):
	
	![](https://u.cubeupload.com/xwindows/nvR6TN.png)
	
- [nominatim.openstreetmap.org debug entry](https://nominatim.openstreetmap.org/search.php?q=%E0%B8%A8%E0%B8%AA%E0%B8%9A):
	
	![](https://u.cubeupload.com/xwindows/yjOQMi.png)

After spending many minutes alternating between reading and clicking through the results, I found the entry I was looking for&mdash; buried in page 13 of the search result (from both [normal](https://u.cubeupload.com/xwindows/hoDIrQ.png) and [debug](https://u.cubeupload.com/xwindows/45OpAv.png) search).

But the problem is why a large number unrelated POIs made their way into the search result **without having anything remotely resembling "ศสบ" in any of their name fields?**

Please investigate; fixing this problem should improve the relevancy of results that Nominatim returns.

Nominatim: [nominatim.openstreetmap.org](https://nominatim.openstreetmap.org/)  
Browser: Pale Moon 25.8.1 (GNU/Linux 32-bit)

-----

### Notes ###

* There are few other exact-match initials search terms for this POI, like English <q>`TCDC`</q> <sup>([OSM](https://www.openstreetmap.org/search?commit=Go&query=TCDC), [Nominatim](https://nominatim.openstreetmap.org/search.php?q=TCDC))</sup> or a Thai-transliterated <q>`ทีซีดีซี`</q> <sup>([OSM](https://www.openstreetmap.org/search?commit=Go&query=%E0%B8%97%E0%B8%B5%E0%B8%8B%E0%B8%B5%E0%B8%94%E0%B8%B5%E0%B8%8B%E0%B8%B5), [Nominatim](https://nominatim.openstreetmap.org/search.php?q=%E0%B8%97%E0%B8%B5%E0%B8%8B%E0%B8%B5%E0%B8%94%E0%B8%B5%E0%B8%8B%E0%B8%B5))</sup>; but these are not affected by the problem.
* The 3-character length of <q>`ศสบ`</q> query is not likely to be the sole cause of this problem; since a similarly-constructed search for another POI <q>`ปปง`</q> <sup>([OSM](https://www.openstreetmap.org/search?commit=Go&query=%E0%B8%9B%E0%B8%9B%E0%B8%87), [Nominatim](https://nominatim.openstreetmap.org/search.php?q=%E0%B8%9B%E0%B8%9B%E0%B8%87))</sup> returned [the exact item I was looking for](https://www.openstreetmap.org/way/333177964) as its _sole_ result.

**Comment by lonvia** [comment]
ศสบ transliterates to NPC and that just happens to be a very frequent term. The results you get are entirely expected because the search index works on transliterated terms only. If there are a lot of matches, there is currently no way to prioritize the item to force it into the initial result set. It is also not something that can be easily changed without sacrificing a lot of performance.

Work around: search for "ศสบ, Bangkok" or "ศสบ, Thailand".

**Comment by nachanon** [comment]
@lonvia,

>> there is currently no way to prioritize the item to force it into the initial result set

I already knew for some time now that Nominatim has no result ranking (although it should have). So, that's not what I intend to discuss here.

>> ศสบ transliterates to NPC

While the <q>`NPC`</q> part seems to explain those unwanted results, the real problem is **why <q>`ศสบ`</q> got transliterated into <q>`NPC`</q>?**

As far as I understand, three characters `ศ`, `ส`, and `บ` in the query are [Thai alphabets](https://en.wikipedia.org/wiki/Thai_script), and are not used in any other languages. The readings are <q>**s**or</q>, <q>**s**or</q>, and <q>**b**or</q> respectively. There's no vowel in the phrase, so each character are read one-by-one.

If the phrase was going to be transliterated (phonetically romanized) from Thai into English, then we should have got <q>`SSB`</q> for the query. The fact Nominatim got it as <q>`NPC`</q> does not make sense.

Which language the transliteration in question takes place anyway? Can it be checked?

-----

Full disclosure: I'm a native Thai user, but I'm not a linguist; so I'm not fully aware if any nearby languages could cause this mis-romanization.

**Comment by lonvia** [comment]
Ah, so you are reporting that the Thai transliteration is wrong. Sorry, I didn't get that from the initial report. I've changed the title to that effect.

Likely to be fixed only with #1279.

**Comment by lonvia** [comment]
This is fixed with the new ICU tokenizer added in #2312. ศสบ now transliterates indeed to 'ssb'.

Note that it will still be a while before the new tokenizer goes into production on osm.org.
