### ISSUE TITLE
Initial data import: Create and drop indexes with CONCURRENTLY

### ISSUE THREAD

**Issue by JostBaron** [osm-search/Nominatim#1507]
When doing a full planet import, it got stuck for me multiple times because autovacuuming locked the tables, leading to queries like `DROP INDEX IF EXISTS place_id_idx;` taking > 12 hours. Using `DROP INDEX CONCURRENTLY IF EXISTS place_id_idx;` should help in such cases.

**Comment by lonvia** [comment]
Had to revert the change as `CONCURRENTLY` is buggy.

**Comment by anayrat** [comment]
> When doing a full planet import, it got stuck for me multiple times because autovacuuming locked the tables, leading to queries like `DROP INDEX IF EXISTS place_id_idx;` taking > 12 hours.

Hello,
I think the issue is elsewhere, autovacuum do not lock tables or if it happen it stops itself:
https://www.postgresql.org/docs/current/routine-vacuuming.html

> Autovacuum workers generally don't block other commands. If a process attempts to acquire a lock that conflicts with the SHARE UPDATE EXCLUSIVE lock held by autovacuum, lock acquisition will interrupt the autovacuum. 

Do you have logs when it happened?

**Comment by lonvia** [comment]
The problem is with the second part in the paragraph you quoted:

> However, if the autovacuum is running to prevent transaction ID wraparound (i.e., the autovacuum query name in the pg_stat_activity view ends with (to prevent wraparound)), the autovacuum is not automatically interrupted.

That is the kind of vacuum that blocks the process.

We update the entire placex table which is a couple of million lines all in autocommit mode. So I'm not surprised that we run out of transaction IDs. We could insert a vacuum here and there but so far this does not seem to have solved the problem. A full 'vacuum analyse' takes too long. Increasing the limits for wraparound just defers the problem to a later point in time as the OSM database is constantly growing.

We might have to change the strategy and run several UPDATEs per transaction. I think there was a problem that we run into deadlocks doing that because of interdependencies between the updates.

**Comment by anayrat** [comment]
> The problem is with the second part in the paragraph you quoted:
> 
> > However, if the autovacuum is running to prevent transaction ID wraparound (i.e., the autovacuum query name in the pg_stat_activity view ends with (to prevent wraparound)), the autovacuum is not automatically interrupted.
> 
> That is the kind of vacuum that blocks the process.

That's why I ask for log. anti wraparound  are rare. They happen each 200 millions transaction if I am right (autovacuum_freeze_max_age).

> 
> We update the entire placex table which is a couple of million lines all in autocommit mode. So I'm not surprised that we run out of transaction IDs. 

You update line by line with a new transaction for each line?

> We could insert a vacuum here and there but so far this does not seem to have solved the problem. A full 'vacuum analyse' takes too long. Increasing the limits for wraparound just defers the problem to a later point in time as the OSM database is constantly growing.

A `vacuum analyze` wont help you, only `vacuum freeze`.

> We might have to change the strategy and run several UPDATEs per transaction. I think there was a problem that we run into deadlocks doing that because of interdependencies between the updates.

I could be a good idea, just take care of deadlock or taking locks for too long.

Maybe the issue is around autovacuum settings. Default values are really conservative and sometimes need to be increased. Unless an autovacuum freeze can take several day to complete.

**Comment by mtmail** [comment]
As optimization the install instruction already include to set `fsync=off`, `full_page_writes=off`, at least for the initial import. Could we set `autovacuum_freeze_max_age` to a much higher number to avoid the wraparound?

I have output from an index state:

```
135306 postgres 98.9 34:45.15 postgres: 12/main: nominatim nominatim [local] CREATE INDEX waiting
131517 postgres  3.3  5:32.82 postgres: 12/main: autovacuum worker   nominatim
131501 postgres  2.6  4:52.60 postgres: 12/main: autovacuum worker   nominatim
131525 postgres  2.6  5:24.56 postgres: 12/main: autovacuum worker   nominatim
130773 ubuntu    1.3  1:50.14 htop
```

```sql
nominatim=# SELECT pid,
nominatim-#        usename,
nominatim-#        pg_blocking_pids(pid) AS blocked_by,
nominatim-#        query AS blocked_query
nominatim-# FROM pg_stat_activity;
  pid   |  usename  | blocked_by |                                      blocked_query
--------+-----------+------------+-----------------------------------------------------------------------------------------
  76780 |           | {}         |
  76782 | postgres  | {}         |
  78051 | nominatim | {}         | DEALLOCATE pdo_stmt_00000013
 135306 | nominatim | {}         | CREATE INDEX idx_placex_geometry_reverse_lookupPoint                                   +
        |           |            |   ON placex USING gist (geometry)                                                      +
        |           |            |   WHERE (name is not null or housenumber is not null or rank_address between 26 and 27)+
        |           |            |     AND class not in ('railway','tunnel','bridge','man_made')                          +
        |           |            |     AND rank_address >= 26 AND indexed_status = 0 AND linked_place_id is null;
 135701 | nominatim | {}         | SELECT pid,                                                                            +
        |           |            |        usename,                                                                        +
        |           |            |        pg_blocking_pids(pid) AS blocked_by,                                            +
        |           |            |        query AS blocked_query                                                          +
        |           |            | FROM pg_stat_activity;
 131501 |           | {}         | autovacuum: VACUUM public.planet_osm_ways (to prevent wraparound)
 131517 |           | {}         | autovacuum: VACUUM public.location_road_2 (to prevent wraparound)
 131525 |           | {}         | autovacuum: VACUUM public.place (to prevent wraparound)
  76778 |           | {}         |
  76777 |           | {}         |
  76779 |           | {}         |
(11 rows)
```

**Comment by lonvia** [comment]
> That's why I ask for log. anti wraparound are rare. They happen each 200 millions transaction if I am right (autovacuum_freeze_max_age).

That sounds about right. `placex`, the table in question, is now at 250 million lines and growing.

> You update line by line with a new transaction for each line?

Yes. A bit of background: Nominatim processes the data in two steps. First we load the raw OSM data for each place in the world into a table (the `placex` table). Then we go through the table and set the value in a special column (`indexed_status`) which triggers the computation of the address and search terms of that place. This is a rather complex trigger written in plpgsql that in turn fills other tables with address and search information. The whole thing is called the _indexing step_ (not to be confused with creating postgresql indexes, that's different). The indexing is done multithreaded externally, i.e. we create multiple connections to the database and have each of them index a part of the placex table. And that's where the trouble with transactions is. If we run those per-thread indexing in a transaction, the threads immediately run into a deadlock with each other. I've never really invested what deadlocks with what but the indexing also occasionally changes entries in the placex table itself, which naturally is a bit of an issue in that setup. We also have a sequence which needs to be shared between the threads. I don't know if that is an issue, too.

The whole process was invented in times of Postgresql 8.4 and when we had a lot less OSM data, so there are historical reasons why it is the way it is. And so far it did it's job, so no need to touch it. With Postgresql 11+ we probably should get rid of the client side threading and just have postgresql take care of parallel processing. It's finally time to look into improving the process. 

Independent of that I still don't quite understand why Postgresql doesn't manage to freeze the tables during the indexing process. There are no long running transactions that would be in the way of freezing.

> A vacuum analyze wont help you, only vacuum freeze.

Ah, that is good to know. I'll give it a try.

**Comment by anayrat** [comment]
> As optimization the install instruction already include to set `fsync=off`, `full_page_writes=off`, at least for the initial import. 

Yes, these options are right. If it is possible you can put wal_level to minimal (need restart and is not compatible with replication), increase maintenance_work_mem to 1GB for example, checkpoint_completion_target to 0.9, max_wal_size to 10GB and checkpoint_timeout to 30min (this will reduce the amount of WAL generated).

Could we set `autovacuum_freeze_max_age` to a much higher number to avoid the wraparound?
> 
> I have output from an index state:
> 
> ```
> 135306 postgres 98.9 34:45.15 postgres: 12/main: nominatim nominatim [local] CREATE INDEX waiting
> 131517 postgres  3.3  5:32.82 postgres: 12/main: autovacuum worker   nominatim
> 131501 postgres  2.6  4:52.60 postgres: 12/main: autovacuum worker   nominatim
> 131525 postgres  2.6  5:24.56 postgres: 12/main: autovacuum worker   nominatim
> 130773 ubuntu    1.3  1:50.14 htop
> ```
> 
> ```sql
> nominatim=# SELECT pid,
> nominatim-#        usename,
> nominatim-#        pg_blocking_pids(pid) AS blocked_by,
> nominatim-#        query AS blocked_query
> nominatim-# FROM pg_stat_activity;
>   pid   |  usename  | blocked_by |                                      blocked_query
> --------+-----------+------------+-----------------------------------------------------------------------------------------
>   76780 |           | {}         |
>   76782 | postgres  | {}         |
>   78051 | nominatim | {}         | DEALLOCATE pdo_stmt_00000013
>  135306 | nominatim | {}         | CREATE INDEX idx_placex_geometry_reverse_lookupPoint                                   +
>         |           |            |   ON placex USING gist (geometry)                                                      +
>         |           |            |   WHERE (name is not null or housenumber is not null or rank_address between 26 and 27)+
>         |           |            |     AND class not in ('railway','tunnel','bridge','man_made')                          +
>         |           |            |     AND rank_address >= 26 AND indexed_status = 0 AND linked_place_id is null;
>  135701 | nominatim | {}         | SELECT pid,                                                                            +
>         |           |            |        usename,                                                                        +
>         |           |            |        pg_blocking_pids(pid) AS blocked_by,                                            +
>         |           |            |        query AS blocked_query                                                          +
>         |           |            | FROM pg_stat_activity;
>  131501 |           | {}         | autovacuum: VACUUM public.planet_osm_ways (to prevent wraparound)
>  131517 |           | {}         | autovacuum: VACUUM public.location_road_2 (to prevent wraparound)
>  131525 |           | {}         | autovacuum: VACUUM public.place (to prevent wraparound)
>   76778 |           | {}         |
>   76777 |           | {}         |
>   76779 |           | {}         |
> (11 rows)
> ```

Thanks for providing  this! Indeed it is an anti wraparound autovacuum.
Do you know if just the initial import generate more than 200 millions transactions? It seems really huge. I think we can expect improvement by perform operations in batch.
However, we can increase `autovacuum_freeze_max_age` just during the import and perform a `VACUUM FREEZE ANALYZE` at the end. This will be faster than autovacuum, and also update statistics. Note, it won't block SELECT or UPDATE/DELETE statements.

**Comment by anayrat** [comment]
> > That's why I ask for log. anti wraparound are rare. They happen each 200 millions transaction if I am right (autovacuum_freeze_max_age).
> 
> That sounds about right. `placex`, the table in question, is now at 250 million lines and growing.
> 
> > You update line by line with a new transaction for each line?
> 
> Yes. A bit of background: Nominatim processes the data in two steps. First we load the raw OSM data for each place in the world into a table (the `placex` table). Then we go through the table and set the value in a special column (`indexed_status`) which triggers the computation of the address and search terms of that place. This is a rather complex trigger written in plpgsql that in turn fills other tables with address and search information. The whole thing is called the _indexing step_ (not to be confused with creating postgresql indexes, that's different). The indexing is done multithreaded externally, i.e. we create multiple connections to the database and have each of them index a part of the placex table. And that's where the trouble with transactions is. If we run those per-thread indexing in a transaction, the threads immediately run into a deadlock with each other. I've never really invested what deadlocks with what but the indexing also occasionally changes entries in the placex table itself, which naturally is a bit of an issue in that setup. We also have a sequence which needs to be shared between the threads. I don't know if that is an issue, too.
> 
> The whole process was invented in times of Postgresql 8.4 and when we had a lot less OSM data, so there are historical reasons why it is the way it is. And so far it did it's job, so no need to touch it. With Postgresql 11+ we probably should get rid of the client side threading and just have postgresql take care of parallel processing. It's finally time to look into improving the process.

Thanks for this explanation. Indeed there is historical stuff. I should look how "indexing" works.

> 
> Independent of that I still don't quite understand why Postgresql doesn't manage to freeze the tables during the indexing process. There are no long running transactions that would be in the way of freezing.
> 

I didn't look into Postgres code but it seems freezing take at least SHARE UPDATE EXCLUSIVE lock which conflict even with CREATE INDEX CONCURRENTLY. It is quite complicated but we can't have vacuum during CREATE INDEX:https://www.postgresql.org/docs/current/explicit-locking.html#TABLE-LOCK-COMPATIBILITY

VACUUM must open indexes to perform some kind of cleanup (https://www.postgresql.org/docs/current/progress-reporting.html#VACUUM-PHASES). Thus it can't do this in the same time index is created.

**Comment by lonvia** [comment]
The "indexing" happens in three stages. In each stage a portion of the placex table is updated. In between the stages we close all conntections to the database and run an `analyse`. I'd expect that at this point postgresql would be able to freeze the tables. The batches are significantly smaller than 200 million lines, so having a freeze at these points should help getting through the entire process without a forced autovacuum. But obviously nothing happens there. Maybe there is not enough time to trigger the freezing before the next batch of UPDATEs starts. I'll try to replace the `analyse` with a `vacuum freeze` and see if that improves anything.

**Comment by lonvia** [comment]
#1901 now implements indexing with a lot less transactions which should resolve the issue that was underlying the request.
