### ISSUE TITLE
Initial data import: CREATE INDEX CONCURRENTLY now uses only 1 core and takes more time

### ISSUE THREAD

**Issue by arvindkartik** [osm-search/Nominatim#1549]
While creating index, it just uses 1 core (when there are 15 more available) and takes 24 hours more to the usual import process. 

While checking on `pg_stat_activity`, I found the below SQL to be active for ~ 15 to 20 hours
`CREATE INDEX CONCURRENTLY idx_search_name_nameaddress_vector ON search_name USING GIN (nameaddress_vector) WITH (fastupdate = off) ;`

**Comment by lonvia** [comment]
Please complete your report with the following information:
* hardware configuration: RAM size, CPUs, kind and size of disks
* Operating system (also mention if you are running on a cloud service)
* Postgres and Postgis version
* list of settings you changed in your Postgres configuration
* file being imported (planet, country etc.)

Also please add the full `pg_stat_activity` output line and check if vacuum is running as well. If yes, supply that lien too.

**Comment by arvindkartik** [comment]
Here's the details you asked:

- hardware configuration: RAM size, CPUs, kind and size of disks
    -> 2x E5-2630v3 - 16 cores, 32 threads
- Operating system (also mention if you are running on a cloud service)
    -> Ubuntu 16.04 LTS, dedicated server
- Postgres and Postgis version
    -> PostgreSQL: 9.5.10
    -> POSTGIS: 2.3.3
- list of settings you changed in your Postgres configuration
    ```shared_buffers = 8GB
    maintenance_work_mem = 10GB
    work_mem = 50MB
    effective_cache_size = 24GB
    synchronous_commit = off
    checkpoint_timeout = 10min
    checkpoint_completion_target = 0.9
    autovacuum = on
    fsync = off
    full_page_writes = off
    autovacuum_vacuum_cost_delay = 10ms 
    autovacuum_vacuum_cost_limit = 1000
- file being imported (planet, country etc.)
    -> planet
- Also please add the full pg_stat_activity output line and check if vacuum is running as well. If yes, supply that lien too.
     ->  I specifically checked if vaccum was running, but it wasn't.            
     ->  Here's the full output of pg_stat_activity:
```-[ RECORD 1 ]----+-------------------------------------------------------------------------------------------------------------------------------------
datid            | 36763
datname          | nominatim
pid              | 5239
usesysid         | 16384
usename          | nominatim
application_name | 
client_addr      | 
client_hostname  | 
client_port      | -1
backend_start    | 2019-10-31 22:37:19.245011+05:30
xact_start       | 
query_start      | 2019-11-02 15:44:46.779125+05:30
state_change     | 2019-11-02 15:44:46.779148+05:30
waiting          | f
state            | idle
backend_xid      | 
backend_xmin     | 
query            | DEALLOCATE pdo_stmt_0000000e
-[ RECORD 2 ]----+-------------------------------------------------------------------------------------------------------------------------------------
datid            | 36763
datname          | nominatim
pid              | 17160
usesysid         | 16384
usename          | nominatim
application_name | psql
client_addr      | 
client_hostname  | 
client_port      | -1
backend_start    | 2019-11-02 15:44:09.847971+05:30
xact_start       | 2019-11-03 09:34:42.439683+05:30
query_start      | 2019-11-03 09:34:42.439683+05:30
state_change     | 2019-11-03 09:34:42.439687+05:30
waiting          | f
state            | active
backend_xid      | 
backend_xmin     | 231183475
query            | select * from pg_stat_activity;
-[ RECORD 3 ]----+-------------------------------------------------------------------------------------------------------------------------------------
datid            | 36763
datname          | nominatim
pid              | 17176
usesysid         | 16384
usename          | nominatim
application_name | psql
client_addr      | 
client_hostname  | 
client_port      | -1
backend_start    | 2019-11-02 15:44:46.861774+05:30
xact_start       | 2019-11-02 19:21:33.705312+05:30
query_start      | 2019-11-02 19:21:33.705312+05:30
state_change     | 2019-11-02 19:21:33.705314+05:30
waiting          | f
state            | active
backend_xid      | 
backend_xmin     | 231183475
query            | CREATE INDEX CONCURRENTLY idx_search_name_nameaddress_vector ON search_name USING GIN (nameaddress_vector) WITH (fastupdate = off) ;
```

Prior to this PR, #1526 , it would take about a day lesser and postgres would always use multiple cores

**Comment by lonvia** [comment]
Thank you. Looks like this is a issue specifically on Postgres < 9.6, possibly even < 10.

**Comment by otbutz** [comment]
I don't think that GIN indexes can be built in parallel:

Postgres 12 documentation:

> Currently, the only parallel utility command that supports the use of parallel workers is CREATE INDEX, and only when building a B-tree index.

https://www.postgresql.org/docs/current/runtime-config-resource.html#GUC-MAX-PARALLEL-WORKERS-MAINTENANCE
