### ISSUE TITLE
empty zoom parameter value on /reverse endpoint should be ignored

### ISSUE THREAD

**Issue by mtmail** [osm-search/Nominatim#1599]
https://nominatim.openstreetmap.org/reverse.php?format=html&lat=13.862500&lon=5.558333&zoom=

returns "` Integer number expected for parameter 'zoom' `".

I think it makes sense that empty value should be ignored since the parameter is optional. The query works when the parameter is not present
https://nominatim.openstreetmap.org/reverse.php?format=html&lat=13.862500&lon=5.558333

**Comment by lonvia** [comment]
It is still badly formatted. I'd rather see that we fix the website and do not send the empty parameter anymore. Same for viewbox.

**Comment by lonvia** [comment]
This has been fixed on the UI side.
