### ISSUE TITLE
Geocoding fails when searching for both name and house number

### ISSUE THREAD

**Issue by scaidermern** [osm-search/Nominatim#164]
As reported via [help.openstreetmap.org](https://help.openstreetmap.org/questions/35073/ensuring-buildings-can-be-found-by-nominatim) the search yields no result when searching for both the name and the house number. Example:
- [Searching for the name](https://www.openstreetmap.org/search?query=Tower%20B%2C%20Legget%20Dr%2C%20Ottawa) succeeds
- [Searching for the house number](https://www.openstreetmap.org/search?query=555%20Legget%20Dr%2C%20Ottawa) succeeds
- [Searching for both the name and the house number](https://www.openstreetmap.org/search?query=Tower%20B%2C%20555%20Legget%20Dr%2C%20Ottawa) fails

**Comment by hohl** [comment]
May be related to my bug: When searching for a full address (like "Sample Street 123") it always finds "Sample Street" but not the exact house. (But the exact house number is noted correctly in OSM) Seems to be related with how long the street is too.

**Comment by arvindkartik** [comment]
I came across a similar issue. Searching for "Upper Camden Street, Saint Kevin's, Dublin 2" would work, but adding a house number to the query would not give any results.

[Search query up to street level](https://nominatim.openstreetmap.org/search.php?q=Upper+Camden+Street%2C+Saint+Kevin%27s%2C+Dublin+2&polygon_geojson=1&viewbox=) succeeds

[Search query with house number](https://nominatim.openstreetmap.org/search.php?q=10+Upper+Camden+Street%2C+Saint+Kevin%27s%2C+Dublin+2&polygon_geojson=1&viewbox=) fails

**Comment by joy-yyd** [comment]
Hello, 
Regarding the problem mentioned in  #1821, we've modified the tag to addr:place=place_name and load the data in local Nominatim, it seems still not able to find the place with House number. Is it possible to add more tags to the parent node?
Thanks a lot for your help!

**Comment by joy-yyd** [comment]
We were testing our data of Austria (downloaded from https://www.geofabrik.de/) with the new release 3.5.1, however, we found many issues with the house number, e.g.
1) We found: https://nominatim.openstreetmap.org/search.php?q=Universit%C3%A4tsklinikum+St.+P%C3%B6lten%2C+Sankt+P%C3%B6lten%2C+3100&polygon_geojson=1&viewbox=
Not found with house number: https://nominatim.openstreetmap.org/search.php?q=Universit%C3%A4tsklinikum+St.+P%C3%B6lten%2C+1%2C+Sankt+P%C3%B6lten%2C+3100&polygon_geojson=1&viewbox=
 2) Found https://nominatim.openstreetmap.org/search.php?q=Universit%C3%A4tsklinikum+Tulln%2CAlter+Ziegelweg%2CTulln%2C3430&polygon_geojson=1&viewbox=
Not found: https://nominatim.openstreetmap.org/search.php?q=Universit%C3%A4tsklinikum+Tulln%2C10%2CAlter+Ziegelweg%2CTulln%2C3430&polygon_geojson=1&viewbox=
3) Found: https://nominatim.openstreetmap.org/search.php?q=Krankenhaus+Theresienhof%2C+Frohnleiten%2C+8130&polygon_geojson=1&viewbox=
Not found: https://nominatim.openstreetmap.org/search.php?q=Krankenhaus+Theresienhof+%2C3-5%2CFrohnleiten%2C+8130&polygon_geojson=1&viewbox=
We have modified/added the place tags to the data and imported to the database, but not able to fix the issues. 
Is there a plan to fix this bug in the new release? Thanks a lot for your advice!

**Comment by lonvia** [comment]
There are no immediate plans for a fix. It's not exactly trivial.

**Comment by joy-yyd** [comment]
Hello Sarah, I modified the _address_rank_ as `$aTerms[] = 'address_rank between 16 and 30'; ` in https://github.com/osm-search/Nominatim/blob/master/lib/SearchDescription.php#L660. Wit this change, it seems to have found the places by name with house number for the examples above in Austria. Then, I tested some addresses for the house number with the street and no house number search, the results are the same as the original code. I am wondering if there is a downside of this fix? Or I can ask for a pull request for the change. Many thanks!

**Comment by lonvia** [comment]
This might work. I don't think there is too much overlap with streets and POI names here. Feel free to do a PR.

**Comment by lonvia** [comment]
Fixed by #1874.

**Comment by joy-yyd** [comment]
Hello Sarah, 
As we are testing the Release 3.5.1, we found that the code seems not changed, though the pull request has been merged, as the following: 
https://github.com/osm-search/Nominatim/blob/168c2e222ee3792e5c2e9261e2196e182523bce6/lib/SearchDescription.php#L660
Could you help us to merge it again if the code is reverted?
Thanks a lot!
Joy

**Comment by lonvia** [comment]
#1874 is not in the 3.5.1 release as it was merged later.

**Comment by joy-yyd** [comment]
ok, thank you Sarah!

**Comment by juanpelegrina** [comment]
> #1874 is not in the 3.5.1 release as it was merged later.

any idea on when the next release is planned?

**Comment by lonvia** [comment]
Tomorrow. However, this particular feature will only be included when we do the 3.6 release which is still a couple of months away.
