### ISSUE TITLE
Nominatim breaks Badger game

### ISSUE THREAD

**Issue by lonvia** [osm-search/Nominatim#1643]
#### Größkühnau

https://nominatim.openstreetmap.org/reverse?format=geocodejson&lat=51.855291&lon=12.176971&zoom=42&accept-language=en&addressdetails=1

The actual village Größkühnau is reflected in label and admin level 9, but is not contained in the city, state, country geocoding.

The label introduces Brambach, which can be found nowhere else

#### Chester County

https://nominatim.openstreetmap.org/reverse?format=geocodejson&lat=39.877073&lon=-75.669708&zoom=42&accept-language=en&addressdetails=1 there is an admin 6 level "Chester County", which is reflected in the  label, but is lacking from the geocoding (i.e. between state and city).

#### Frankfurt am Main

Querying a place in Frankfurt am Main via
https://nominatim.openstreetmap.org/reverse?format=geocodejson&lat=50.119698&lon=8.639374&zoom=42&accept-language=en&addressdetails=1
there is a now new intermediate layer "geocoding:city: Frankfurt" between Frankfurt am Main and Bockenheim. Wasn't there a few weeks ago.

#### Zahna-Elster

Seems that change thrown out whole communities (gemeinden) and Cities out of the address ranking.
Example:
https://nominatim.openstreetmap.org/reverse?format=geocodejson&lat=51.934952&lon=12.819672&zoom=42&accept-language=en&addressdetails=1 (Here the City Zahna-Elster is missing and only the "suburb" Zahna is delivered

@InI4 @Megachip

**Comment by InI4** [comment]
Thank you for at least collecting things. I must confess this is more than I hoped for an I do not hope for much more. Or the other way round, I am not sure, if we are a relevant use case for Nominatim.

**Comment by Megachip** [comment]
@lonvia Subject confuses a bit, I would call it Nominatim Changes breaks address resolving... So not sure if this fits here:
https://nominatim.openstreetmap.org/reverse?format=geocodejson&lat=51.84002&lon=12.242889&zoom=42&accept-language=en&addressdetails=1

Here the result lacks of the City "Dessau", which was there before.

**Comment by InI4** [comment]
In other words, the point might be, that some points which break Badge(r)s, actually break more usecases. (Yes, I understand, that some changes are deliberate, but break Badgers, just do not ignore the other ones).

**Comment by Megachip** [comment]
https://nominatim.openstreetmap.org/reverse?format=json&lat=53.521533&lon=10.125275&zoom=42&accept-language=en&addressdetails=1 Wrong village "Havighorst"

**Comment by lonvia** [comment]
Grosskühau: this comes out as mapped, as part of the city Dessau-Roslau. Nothing I can see wrong there. There has been no city 'Desslau' since 2007 according to Wikipedia. If it has been there before then it was wrong before. Same for comment from Feb 1st.

Chester County: Mapping error. Somebody put a place=hamlet with role 'label into the county relation.

Frankfurt will be fixed by #1702. Hamburg probably too but that needs some amended tagging as well.

**Comment by lonvia** [comment]
Zahna is now fixed as well. That's a tricky one because Zahna is tagged as an independent village inside a municipality. The OSM tagging is very inconsistent for this situation. The result is that sometimes the municipality shows up in the 'city' field, sometimes the village. Not much Nominatim can do about this until tagging in OSM improves.

Hamburg did come out correctly after some retagging as well.

All the cases should be fixed now from the software side, so I'm closing this. Note that there is still quite a bit of bad tagging in OSM that needs fixing. And the database hasn't been globally reindexed after the software changes. That means that you will see the occasional odd outcome still.

**Comment by Megachip** [comment]
We've more than 90 Corrections per day :( But strange thing, when I'm checking via HTML, it is fine. The Levels seems only missing via json/gecodejson.

**Comment by Megachip** [comment]
https://nominatim.openstreetmap.org/reverse?format=geocodejson&lat=52.408284&lon=12.970734&zoom=42&accept-language=en&addressdetails=1 

Just one more example (of the 90 per day ;) ... City Potsdam is missing in result. (Beside that Potsdam Nord isn't a suburb of Golm ;) It#s vice versa ;)

**Comment by lonvia** [comment]
As I said, the database needs to slowly catch up with the software changes.

If you really want to help out, you could collect all the test cases you have as a PR for this table: https://github.com/lonvia/geocoder-tester/blob/nominatim/geocoder_tester/world/germany/test_reverse.csv
The reverse geocoding needs to be done at `zoom=16` (corresponding to `street` in the detail column). The tests run against the geocodejson format. The `expected_*` columns are the expected output corresponding to the fields of the geocodejson answer. The comment column can be left free.

**Comment by lonvia** [comment]
I should add that the current convention for kreisfreie Städt like Potsdam is that they only show up as `city=Potsdam`, they don't have a `county` field, so the `expected_county` column needs to remain empty.

**Comment by InI4** [comment]
Anyway, most of the changes I see arriving in Badge(r)s database are no Nominatim bugs or issues, only the announced changes of Nominatim address delivery.

**Comment by Megachip** [comment]
> As I said, the database needs to slowly catch up with the software changes.
> 
> If you really want to help out, you could collect all the test cases you have as a PR for this table: https://github.com/lonvia/geocoder-tester/blob/nominatim/geocoder_tester/world/germany/test_reverse.csv
> The reverse geocoding needs to be done at `zoom=16` (corresponding to `street` in the detail column). The tests run against the geocodejson format. The `expected_*` columns are the expected output corresponding to the fields of the geocodejson answer. The comment column can be left free.

It's fine now on both levels (16 and 42), so I'll guess it makes no sense to add it to the csv?

**Comment by lonvia** [comment]
Well, the whole point of this file is to create a large set of regression tests. So if you have a list of all the cases you found to be wrong before, then it would still be helpful to have them in above mentioned CSV format so that I can run them against the new algorithm and see if they all pass.

**Comment by InI4** [comment]
@lonvia  This looks interesting to us:
https://nominatim.openstreetmap.org/reverse?format=json&lat=52.448477&lon=13.605194&zoom=42&accept-language=en&addressdetails=1
This is lacking Berlin.

**Comment by InI4** [comment]
Ah, we are supposed to do Pull Requests now. Means I need to create my own Nominatim clone. Not anytime soon.

**Comment by lonvia** [comment]
No, you were supposed to create _test cases_.

**Comment by InI4** [comment]
Creating test cases by pull requests. I now have forked the geocode-tester project, but I fail to fully grasp your csv format, especially as it I also have mistakes in countries you haven't created in that project. Look at this request:

https://nominatim.openstreetmap.org/reverse?format=json&lat=50.082701&lon=14.280853&zoom=16&accept-language=en&addressdetails=1

It is in Czechia and it contains the completely pointless line 
  state: Prague

I'd expect no state in this and things would be fine.

**Comment by lonvia** [comment]
Don't worry too much about sorting or putting tests in the right place. This can easily be cleaned up at a later time. It's the test cases themselves that are very valuable to us. I would suggest that you create a single file `geocoder_tester/world/test_badger.csv` and open a PR about the new file. You can then just keep adding test cases by adding new lines to the file and committing and pushing the changes. Feel free to mix tests from all over the world in that single file. 

Ideally we'd have a website where you can just fill in a form with your test cases. But that's future tense. For the moment the CSV is the best way of reporting we have. :(

**Comment by InI4** [comment]
Just as an Update, I did a selection over Badge(r)s database on (once) corrected deviations between Nominatim and what we expect. I get beyond 1000 cases (already skipping cases with low numbers of samples). 

I currently have two problem: 

1. No time to hand review them all. 
2. No means to exactly provide the format you suggest for test cases (for example as we often lack placetypes in our database).
