### ISSUE TITLE
Improve details page for non-OSM objects

### ISSUE THREAD

**Issue by lonvia** [osm-search/Nominatim#1671]
Nominatim sometimes presents results that are not directly related to an OSM object. These are:

* postcode (country + postcode + a parent OSM object)
* interpolations (OSM way + a housenumber)
* Tiger house numbers (OSM way + Tiger interpolations + housenumber)
* auxillary data (Currently unused)
* countries/country codes (osm_country_name table + location_country table for geometry)

These objects don't have good details pages at the moment. They usually simply redirect to their OSM parent object. This can be confusing at times. It would be nice if the available data for these objects is also presented in the details page.

Todo:
- [x] document auxiliary data and how it is returned to the user
- [ ] extend parameters of details page, so that auxiliary data can be uniquely linked (see also #1651)
- [ ] extend details API output
- [ ] nominatim-ui: extend linking to details of special objects
- [ ] nominatim-ui: extend details page to show additional information about the auxiliary object

**Comment by amanbora** [comment]
Hi, I would like to work on this issue, I'm new to Nominatim so i might need some guidance.

**Comment by lonvia** [comment]
Welcome @amanbora. To get started, I recommend focusing on one of the object types on the list. Postcodes is a very good one.

The first step is always to set up your own small installation of Nominatim. Follow the [installation instructions](http://nominatim.org/release-docs/develop/admin/Installation/) to get it running for a small country. I recommend [Liechtenstein](http://download.geofabrik.de/europe/liechtenstein.html). Once you have this running, have a look at the `location_postcode` table. This is the table that contains the artificial postcodes. Try to understand what it contains. `sql/update-postcodes.sql` contains the code that creates this table, so you should look at this, too. Ideally you should document your findings in the [Developer's documentation](https://github.com/openstreetmap/Nominatim/tree/master/docs/develop).

After this, have a look at the code for the [details endpoint](https://github.com/openstreetmap/Nominatim/blob/master/website/details.php) and extend it to query the postcodes table.

If you have questions about the installation or the code, the [geocoding mailinglist](https://lists.openstreetmap.org/listinfo/geocoding) is a good place for discussions.

**Comment by amanbora** [comment]
@lonvia I'll get to it 👍

**Comment by amanbora** [comment]
@lonvia while building I'm getting the following error.
<img width="697" alt="Screenshot 2020-02-25 at 9 04 38 AM" src="https://user-images.githubusercontent.com/33185170/75212748-ddc73480-57ad-11ea-828e-d98485a0742d.png">

**Comment by mtmail** [comment]
Among other places it looks at the output of ‘pg_config’. Make sure that’s in your $PATH That solved it for me on centos8 when I encountered the issue.

**Comment by lonvia** [comment]
This is **not** the right place to ask installation questions. I did mention the mailing list above, please use that. Also, you will have to include a more extensive problem description. This involves describing: what you have been doing, what went wrong (do not send screen shots) and what you have been trying to resolve the problem. I assume you are interested in participating in GSoC. The last part about "trying to resolve the problem yourself" is particular important in this case.

**Comment by amanbora** [comment]
I'm working on a MacOS system. I'm unable to find documentation related to `building on a mac`, can you pls guide.
