### ISSUE TITLE
Update script for running updates on a database with multiple countries

### ISSUE THREAD

**Issue by lonvia** [osm-search/Nominatim#1683]
Issue #60 describes a way to keep multiple countries up-to-date using osmosis. This does not work properly anymore with the latest Nominatim. The script should be updated to use pyosmium-get-changes.

**Comment by Muhammadreda264** [comment]
Hi, I would like to work on this issue, I'm new to Nominatim so i might need some guidance.Can you please share a link to the orginal script.

**Comment by mmd-osm** [comment]
@Muhammadreda264 : you need to submit a PR to this project **even before** your application will be considered. Please refer to https://wiki.openstreetmap.org/wiki/User:Lonvia/GSoC_2020_Nominatim_Projects

**Comment by lonvia** [comment]
Fixed in #1758.
