### ISSUE TITLE
Different licence and copyright infomation for different data providers

### ISSUE THREAD

**Issue by joy-yyd** [osm-search/Nominatim#1699]
Hello, 
As we need to use data from different sources, we would like to link the corresponding licence and copyright information with the place in the database. Meanwhile, we will keep the original openstreetmap licence for the original data as default. We are implementing this feature now. I am wondering if we can ask for a 'Pull request'  regarding this customization? 

Thanks a lot for your help!
Joy

**Comment by lonvia** [comment]
I'm not entirely sure how you imagine this works license-wise. OSM data is under ODbL and as a share-alike license, it would 'contaminate' any additional data when they are imported together in Nominatim. So the license of the database is ODbL globally (including the obligation to make your mixed database available publicly). If your extra data is not ODbL-compatible then you're better off keeping it in a separate database and mixing results from the two Nominatim instances in the webserver.

I could see a use-case where you need to add additional attribution information.

There are placeholder in Nomiantim for external house number data (the currently empty `*aux*` tables and the `*tiger*` table. I could imagine defining custom attributions for those on a table granularity.

If you convert your external data into OSM format and import that, then you could add additional attribution information simply as a tag to each object. Import with the `import-extratags.style` and hack the output templates to include the information. Note that the result will not be exactly correct. Each result that is returned by Nominatim is a mixup of the object itself and of each object that makes up the address. You'd have to combine the attributions for all these objects to get it completely right.

If it's done in a configurable and well-documented way, I might accept a pull request.

**Comment by joy-yyd** [comment]
Thank you so much! We will discuss and define the usage of the customized data and licence according to your advice,  and then submit our change.

**Comment by joy-yyd** [comment]
Dear Sarah,  
We have customized our data via GeoKettle ETL scripts, and then imported the data to a separate database for its Nominatim instance.  And we will add the “data_licence” and “data_copyright” tags to our data for testing the change.
 
Regarding the Nominatim change, I would like to ask your opinion on the following steps: 

1. Import  "data_licence” and “data_copyrihgt” as tags from each element in OSM file via the _import-extratags.style_.

2. Modify the _PlaceLookup.php_ to request these values from the _extratags_ column in _placex_ table.

3. Modify output templates in _Nominatim/lib/template/_ to display the licence and copyright under each place found. If not found, it will display the OSM licence as default.

We will guarantee to keep the default configuration of the original Nominatim source and will always respect current OSM licence structure for the OSM data. 

Thanks a lot for your correction and advice in advance!
Joy

**Comment by juanpelegrina** [comment]
Dear @lonvia, 
have you had the chance to review the changes propose from Joy? we think is a good solution for having more information about the data. 
if you agree with the last modification we will request for a PR according to the changes you proposed.
Thanks
Juan

**Comment by lonvia** [comment]
This can now be done using customized API output as per #3515.
