### ISSUE TITLE
Nominatim database update 

### ISSUE THREAD

**Issue by bidabil** [osm-search/Nominatim#1709]
Hi, 
We want to make an application used by a lot of people who update our local Nominatim database. 
by searching on the internet, we found two methods: 

1. Having direct access to the database (we need the database architecture and developing the whole update program). 
2. Update by a third-party project (like the openstreetmap ID project).

Our question is: 
If using the second option is not possible, how do we update using the first?

**Comment by mtmail** [comment]
duplicate https://github.com/openstreetmap/iD/issues/7417

You'd need to create OSM change files, direct access to the database will just cause trouble. I don't know if ID can output those.

Changefiles is already out of scope for Nominatim (https://github.com/openstreetmap/Nominatim/issues/1329#issuecomment-472063275), it's possible but we don't want to end up debugging custom data. Again ID might be able to produce valid OSM change files. I don't think anybody has tried that yet.

Direct changing data in the database is definitely out of scope for support requests.

Our main concern is growing the overall OpenStreetMap project, making data free for everybody under the ODbL license.

Note you'd likely mix data of different licenses, triggering a ODbL share-a-like https://github.com/openstreetmap/Nominatim/issues/1699
