### ISSUE TITLE
Option to get polygon encoded

### ISSUE THREAD

**Issue by MKergall** [osm-search/Nominatim#171]
As Nominatim now proposes a lot of possible formats for polygon... it would be great to add still another "polygon_" parameter, to get polygon outline in the now classical Google-encoded form (https://developers.google.com/maps/documentation/utilities/polylinealgorithm). 
Pros: 
- bandwidth reduction
- on Android, parsing an encoded polygon is incredibly faster than parsing its XML or Json equivalent. 

There is a lot of open source encoders (and decoders) available, in many languages - including PHP.

**Comment by lonvia** [comment]
More polygon formats are certainly possible. An external contribution for this feature would be welcome.

**Comment by MKergall** [comment]
I suggest the following approach: 

Include a PHP polyline encoder, like this one: 
https://github.com/dyaaj/polyline-encoder/blob/master/PolylineEncoder.php


In https://github.com/twain47/Nominatim/blob/master/lib/Geocode.php, once $aPolyPoints is built, 
encode it: 


if ($this->bIncludePolygonAsEncoded && isset($aPolyPoints))
{
	$polylineEncoder = new PolylineEncoder();
	foreach($aPolyPoints as $aPoint)
	{
		$polylineEncoder->addPoint($aPoint[1], $aPoint[2]);
	}
	$aResult['aPolyPoints'] = $polylineEncoder->encodedString();
}

**Comment by lonvia** [comment]
I'm closing this as not planned. There doesn't seem to be much interest and it's not clear that the format can even encode polygons.
