### ISSUE TITLE
Capital of Paraguay, Asunción, relation and node not linked

### ISSUE THREAD

**Issue by jesulo** [osm-search/Nominatim#1713]
Hello, the state trying to obtain the geometey coordinates of the Asunción polygon, Paraguay, but in Nominatim are not yet available, because it is in open street, yes it shows in map this (Relationship: Capital District of Paraguay (3654543)).
He tried to access with this link, which I see does not have geometry type: polygon, just say point coordinates.
https://nominatim.openstreetmap.org/details.php?polygon_geojson=1&format=json&place_id=685798

There is a new link or need update info?

Regards
Jesús

**Comment by mtmail** [comment]
Nobody has added a polygon (relation) to the OpenStreetMap data for the city of Asunción yet.

> There is a new link or need update info?

Somebody needs to add the polygon. That could be you. https://www.openstreetmap.org/fixthemap

**Comment by jesulo** [comment]
Hi,

OpenStreetMap does contain polygones for cities, it draws me correctly, but not in Nominatim, apparently it is missing to migrate those data, I have a json file with the coordinates, how can I add it to this link so that can be complete

**Comment by mtmail** [comment]
Sorry, I think I understand now.

https://www.openstreetmap.org/node/249854726 and https://www.openstreetmap.org/relation/3654543 are the same place (Asunción), one is the boundary/polygon, the other the center point? They have a different name but the same wikidata and wikipedia id.

I see there is already a link. The https://www.openstreetmap.org/relation/3654543 has "Node Asuncion (249854726) as admin_centre" (displayed below the table on the left side). We'll need to check what Nominatim did there.

**Comment by jesulo** [comment]
yes.
,"wikidata":"Q2933","wikipedia":"es:Asunción"},"calculated_wikipedia":"es:Asunción","icon":"https://nominatim.openstreetmap.org/images/mapicons/poi_place_city.n.32.png","rank_address":16,"rank_search":15,"isarea":false,"centroid":{"type":"Point","coordinates":[-57.6343814,-25.2800459]},"geometry":{"type":"Point","coordinates":[-57.6343814,-25.2800459]}}

this is a fragment of polygon_geojson, where it says gometry it should be Polygon type but this say point. maybe it be that at some time there was no polygon and there was only the city point, then only some updating is needed? otherwise I have the coordinates of the polygon in a file if they need it but it is the same as openstreet maps

regards

**Comment by mtmail** [comment]
When two places (relation, node) are the same then Nominatim will merge them into a single one. That doesn't always work. As you say the data is in OpenStreetMap already, now it's Nominatim's logic (the linking) that we need to look at.

**Comment by lonvia** [comment]
The node has a wrong admin_level. Asuncion is not a country.

That said, the boundary relation is on county level while the node is tagged with place=city. They need to be marked as belonging together. Either by adding a place tag to the relation or by adding the node with role 'label' (not 'admin_centre'). See also #774.

As a side node: do not use the details endpoint to automatically download geometries. There is a good chance that you get blocked.
