### ISSUE TITLE
Nomination API returns single point instead of polygons

### ISSUE THREAD

**Issue by VaclavRut** [osm-search/Nominatim#1719]
We found these cases for country Mexico:
- Monterrey
`https://nominatim.openstreetmap.org/search.php?q=monterrey%2C+mexico&polygon_geojson=1&viewbox=`
- Santa Fe
`https://nominatim.openstreetmap.org/search.php?q=santa%20fe%2C+mexico&polygon_geojson=1&viewbox=`

**Comment by lonvia** [comment]
I can't find the administrative boundaries for these places in OpenStreetMap. Can you provide a link?

**Comment by lonvia** [comment]
Actually, there is https://www.openstreetmap.org/relation/5606060 for Monterrey. Is this the administrative area of the city? Then you need to indicate that they are linked to the [place node](https://www.openstreetmap.org/node/4145210488) in the OSM data. Either add the node to the relation with a role 'label' or add a tag place=city to the relation.
