### ISSUE TITLE
Database server failed to load /srv/nominatim/Nominatim/build/module/nominatim.so module

### ISSUE THREAD

**Issue by mantesat** [osm-search/Nominatim#1724]
D #1458

Same thing occurred on a fresh Fedora 31 installation. DB is Postrgresql 9.6

**Comment by lonvia** [comment]
Please read https://github.com/osm-search/Nominatim/blob/master/CONTRIBUTING.md#reporting-bugs and the first paragraph in https://github.com/osm-search/Nominatim#installation. Thank you.

**Comment by mantesat** [comment]
ΟΚ, sorry about that, I opened this issue coming from #1458. Anyway, found my way out. Closing it.
