### ISSUE TITLE
Ambiguous countrycodes field definition in  search documentation

### ISSUE THREAD

**Issue by bernsteining** [osm-search/Nominatim#1727]
Hi, 

According to https://nominatim.org/release-docs/develop/api/Search/#result-limitation, the value of the key countrycodes=<countrycode> has to be an  ISO_3166-1_alpha-2 country code.

``` 
countrycodes=<countrycode>[,<countrycode>][,<countrycode>]...
Limit search results to one or more countries. <countrycode> must be the ISO 3166-1alpha2 code, e.g. gb for the United Kingdom, de for Germany.
```

However, a few ISO_3166-1_alpha-2 codes such as "[PF](https://en.wikipedia.org/wiki/ISO_3166-1_alpha-2#PF)" aren't considered as a valid one by Nominatim, because Nominatim identifies French Polynesia with the "FR"  ISO_3166-1_alpha-2 countrycode.

You can give it a try yourself : 

The following request returns nothing:
https://nominatim.openstreetmap.org/search.php?city=Papeete&countrycodes=PF

While this one does:
https://nominatim.openstreetmap.org/search.php?city=Papeete&countrycodes=FR

Even though French Polynesia is a part of France, it has its own countrycode, and therefore must be identified by its ISO_3166-1_alpha-2 code in my opinion. 

Otherwise, the documentation should be more precise about which ISO_3166-1_alpha-2 codes are considered as valid by Nominatim or not.

Peace

**Comment by lonvia** [comment]
Ccountry is defined as anything with admin_level=2, so I'd consider this a data issue.

**Comment by bernsteining** [comment]
Alright, then a list of all the regions defined as admin_level=3 (eg. French Polynesia), which are incorrectly identified by an admin_level=2 (eg. France)  ISO_3166-1_alpha-2 code, would be pretty useful. 

Maybe it's possible to get such a list using overpass? https://overpass-turbo.eu/

I'm not familiar with overpass at the moment tho.

**Comment by mtmail** [comment]
Overpass questions are better on https://help.openstreetmap.org/ or a specific overpass mailing list. We only have capacity for Nominatim related issues.

**Comment by bernsteining** [comment]
It looks like such a request wouldn't be possible on overpass anyway.

I guess the documentation should be more explicit about which ISO3166-1:alpha2 codes are valid as a value for the key "coutrycodes" in a request.
