### ISSUE TITLE
how to make data import faster?

### ISSUE THREAD

**Issue by mtnskb** [osm-search/Nominatim#1728]
Hello,

Some way to optimize the data importation?

I'm importing only Spain map and ./utils/setup.php is taking more than 6 hours. 

I'm doing the installation in a virtual machine with vmWare (two threads and 8 GB).

thanks!

**Comment by mtmail** [comment]
More hardware (more threads), more RAM, faster hard drives help. Spain can take over 24h, the world weeks when using 2 threads.
