### ISSUE TITLE
Search API output with addressdetails is missing postcode

### ISSUE THREAD

**Issue by traynor** [osm-search/Nominatim#1730]
Hello,

when searching API using `addressdetails` parameter, the response's `address` is missing `postcode` property.

Best to use the very examples from API docs:

- click on examples from API docs page, notice how they're missing `postcode` in actual results, that is noted in the example output on the page:

https://nominatim.org/release-docs/develop/api/Search/#examples

Although some results do include `postcode`, most don't, and that goes for other queries, like this one:

https://nominatim.openstreetmap.org/search?q=SW1A+2DX&format=json&addressdetails=1

Any ideas how to get `postcode`?

Edit:
just noticed these, that's probably it, since it started today:

https://github.com/osm-search/Nominatim/commit/4930f776fe5b14879697a02323c5cf1621735dad
#1723

**Comment by lonvia** [comment]
Your guess was right. This was a typo in 4930f77. We obviously need more tests on that front. Thanks for the report.

**Comment by traynor** [comment]
It's back, works great!
Thanks for the fix!
