### ISSUE TITLE
nominatim search api - airports does not include parking in polygon

### ISSUE THREAD

**Issue by roimor** [osm-search/Nominatim#1735]
Hi,

I'm using /search api in order to form geojson files from nominatim. 
One use-case that my customers needs is a airports polygons. So for example, my customer will provide the airport name, then the application will query nominatim and get the geojson data.

The problem is that airports' polygons do not include the airport parking/taxi pickup and dropoff areas. (cars)

Is there any workaround or is there any other modification I can perform on my query? 

for example: Los Angeles International Airport (where you can see in the attached pic, that the polygon is very tight and does not include any part of parking or entry roads within the airport(world way str. for example))

![image](https://user-images.githubusercontent.com/43300666/78514234-fb2dec00-77b8-11ea-9290-d9c337d1e9bf.png)

**Comment by mtmail** [comment]
Not really. Nominatim returns what's in OpenStreetMap data. If that polygon doesn't include certain areas then one would need to edit the data (https://www.openstreetmap.org/way/649268639). https://www.openstreetmap.org/fixthemap This requires coordination with OSM mappers in the area (the area of each airport). For example the current polygon might precisely match the borders/gates/official records of the airport and be technically be correct even if the user expectation differs.
