### ISSUE TITLE
Nominatim without internet connection

### ISSUE THREAD

**Issue by mariusdobre94** [osm-search/Nominatim#1744]
I have installed Nominate on Ubuntu 18, I have completed all the steps to install Nominatim and download a map, more precisely the map of Romania. I imported into the database. everything works fine until there is no internet connection on the browser accessing ubuntu. what would be the problem?
I followed the instructions on http://nominatim.org/release-docs/latest/appendix/Install-on-Ubuntu-18/

**Comment by lonvia** [comment]
Duplicate from the mailing list, which was the right place for the question. Follow-up will be there. Closing here.
