### ISSUE TITLE
Missing link between Island and City

### ISSUE THREAD

**Issue by kbsali** [osm-search/Nominatim#1746]
Hi,
we are trying to implement a search engine based on location of items and we are storing the corresponding `osm_id`s of those items to better locate them.
However we have realised that when an item is located in a city which itself is on an island, we are unable to make the relation between the 2.
Here is an example : 
The town "Saint-Martin-de-Ré" https://nominatim.openstreetmap.org/details.php?osmtype=R&osmid=112857&class=boundary is located in the island of Ré https://nominatim.openstreetmap.org/details.php?osmtype=R&osmid=3066508&class=place in France.
Looking at the details you will see that Saint-Martin-de-Ré is totally unrelated to the island it is in.
Any reason for that? And ultimately, any work around that issue? :)

Thanks in advance for your help & ideas.

**Comment by lonvia** [comment]
The address parts only include administrative parts. Islands will only show if they are an administrative entity themselves. That conveniently solves the problem of figuring out where in the address the island should go.

You can change the behaviour in your own installation by modifying [address-levels.json](https://github.com/osm-search/Nominatim/blob/master/settings/address-levels.json#L12). Currently the line for island puts it at `(17, 0)`. the second number is the important one here. It tells where the type of object should show up in the address hierarchy. `0` means that it should not show up at all. If you want to it to show up on the same level as counties, you'd change this to  `(17, 12)`. You probably have to experiment a bit with the right value to avoid clashes with the administrative boundaries. The full documentation for address-levels.json can be found in the [developer's manual](https://nominatim.org/release-docs/develop/develop/Ranking/#place-ranking-in-nominatim).

**Comment by kbsali** [comment]
Thanks a lot @lonvia for your prompt and clear answer.
We are going to test this ASAP, I'll make sure to let you know if it works or not! :)

**Comment by lonvia** [comment]
Given that this is not something we plan to change in the default address levels, I'm going to close this issue.

@kbsali You are still welcome to comment if the custom levels worked for you. It might be something that is also interesting for others with their own installation.

**Comment by kbsali** [comment]
Jo @lonvia , sorry for not getting back to you on this.
We have transferred the info to our Nominatim provider who is trying to work on this (we are their only clients, and for obvious reasons, they do not want this change to affect any other integration).
Thanks again for your clear answer!
