### ISSUE TITLE
Full planet data import stuck in create search indices phase

### ISSUE THREAD

**Issue by misbahulhoque** [osm-search/Nominatim#1748]
It is been a long time since my full planet data import stuck in the create search indices phase. I am using Ubuntu 16.04, postgresql 9.5 and Nominatim 3.4.1. I have tried restarting the process again using,
./utils/setup.php --index --create-search-indices
Alarmingly the process is not using CPU and memory at all. 
For your information, my server has a higher configuration than expected to import the full planet data.
Thanks in advance for your kind help.

**Comment by misbahulhoque** [comment]
running the following command,
select * from pg_stat_activity;
I found nominatim is idle as the following,
 25099780 | nominatim | 19907 |    16384 | nominatim |                  |             |                 |          -1 | 2020-04-10 21:40:01.661128-05 |                               | 2020-04-10 21:40:01.665681-05 | 2020-04-10 21:40:01.668053-05 | f       | idle   |             |              | CREATE FUNCTION nominatim_test_import_func(text) RETURNS text AS '/home/nominatim/Nominatim/build/module/nominatim.so', 'transliteration' LANGUAGE c IMMUTABLE STRICT;DROP FUNCTION nominatim_test_import_func(text);

**Comment by mtmail** [comment]
What are the last lines of output of `setup.php`? Does the `placex` table contain millions of records? (end of the import steup) Any errors in the postgresql log? Without an error message it's hard to assess what might be going on. The `CREATE FUNCTION nominatim_test_import_func` is run multiple times during a setup, as early as right after the databas creation so I think that can't be the issue.

Possibly related https://github.com/osm-search/Nominatim/issues/1549 though I'd expect a `CREATE INDEX` query to be running

Possibly related https://github.com/osm-search/Nominatim/issues/1476 though I'd expect a vaccum to be running

**Comment by misbahulhoque** [comment]
Thanks. The process has completed after all these days. I think it was running slowly and took all these days. Amid, I have to use the following,
./utils/setup.php --index --create-search-indices --create-country-names --index-noanalyse --ignore-errors

Thank you guys for your relentless help.
