### ISSUE TITLE
Code error 400, select a place_id

### ISSUE THREAD

**Issue by geidsonc** [osm-search/Nominatim#1757]
I am get the success result to `https://nominatim.openstreetmap.org/details.php?osmtype=R&osmid=10218022&format=json`, but response is:

```
{"error":{"code":400,"message":"Please select a place id"}}
```

The relation can to be see in https://www.openstreetmap.org/relation/10218022#map=15/-7.9855/-34.8534.

**Comment by mtmail** [comment]
I think we need to change the error message and code. It searches by osmtype and osmid but finds no results. Maybe code=404.

Nominatim merges nodes and relations into one object when they represent the same place. One https://nominatim.openstreetmap.org/search.php?q=Fragoso%2C+brazil&polygon_geojson=1 the result is the node instead of the relation. There's no guarantee that all relations have a details page.

Do you have local knowledge? Do you know why https://www.openstreetmap.org/relation/10218022 and https://www.openstreetmap.org/way/774620733 are both suburbs with the same name in the same city (no overlap)?

**Comment by geidsonc** [comment]
@mtmail, the suburbs  https://www.openstreetmap.org/relation/10218022 and https://www.openstreetmap.org/way/774620733 are of different cities (Olinda, Pernambuco, Brasil) and (Paulista, Pernambuco, Brasil).

I need the coverage geometry polygon that detail the relation 10218022.

The node https://nominatim.openstreetmap.org/search.php?q=Fragoso%2C+brazil&polygon_geojson=1, it's part of relation 10218022. This can to be see in https://www.openstreetmap.org/node/6052806112. 

Do you know why the nominatim don't have this merge or this is a problem in the edition in the OSM?

In other example, https://www.openstreetmap.org/relation/10216613, have the same situation, but I can to find using the nominatim https://nominatim.openstreetmap.org/details.php?osmtype=R&osmid=10216613&class=boundary.

**Comment by mtmail** [comment]
Seems similar to https://github.com/osm-search/Nominatim/issues/1719 Can you try adding `place=suburb` to the relation?

**Comment by geidsonc** [comment]
I will try this. Any news I put here.

**Comment by geidsonc** [comment]
I added the `place=suburb` and I still can't do it. Still the same answer error`code: 400`.

I still not understand the reason.

I don't see different in the structure between two examples of these relations.
1 - https://www.openstreetmap.org/api/0.6/relation/10218022
2 - https://www.openstreetmap.org/api/0.6/relation/10216613

In the second example there is no problem with api https://nominatim.openstreetmap.org/details.php?osmtype=R&osmid=10216613&class=boundary

There is another thing, the relation does not appear as a parent of `administrative` in https://nominatim.openstreetmap.org/details?place_id=236235999.

**Comment by geidsonc** [comment]
I finally to solve it, after updating the relationship between the node and the relation in OSM. I still don't know why, but I just upgraded to the same relation. Thanks!

**Comment by lonvia** [comment]
You must not use the details endpoint for any automatic downloading. It will get you blocked, see our [usage policy](https://operations.osmfoundation.org/policies/nominatim/). If you just want geometries of OSM objects, then you should use [Overpass](https://overpass-turbo.eu/). If you also need addresses, please have a look at the [lookup endpoint](https://nominatim.org/release-docs/develop/api/Lookup/).
