### ISSUE TITLE
unable to find UK town "Bury St Edmunds"

### ISSUE THREAD

**Issue by freyfogle** [osm-search/Nominatim#1761]
In the UK there is a town named "Bury St Edmunds" with a population of over 40,000 people. 
https://en.wikipedia.org/wiki/Bury_St_Edmunds

This town is well mapped in OSM, see screenshot. 

Nominatim is unable to find it though, I suspect because the "Bury St" portion of the name is converted into "Bury Street"

I think some sort of exception is needed for this specific, and admittedly bizarre, placename

<img width="804" alt="Screenshot 2020-04-19 at 12 14 19" src="https://user-images.githubusercontent.com/351074/79685230-58a14e80-8237-11ea-89fa-9397f915e249.png">

**Comment by lonvia** [comment]
Works for me. https://nominatim.openstreetmap.org/search.php?q=Bury+St+Edmunds&polygon_geojson=1 results in: https://nominatim.openstreetmap.org/details.php?osmtype=N&osmid=21409982&class=place

I suspect that you've run into a viewbox issue here. Can you post the exact query you used when you didn't find it?

**Comment by freyfogle** [comment]
thanks for the fast follow up. I am an idiot. I was searching for "Bury St Edmonds" (with o not u). sorry for the noise.
