### ISSUE TITLE
SyntaxWarning: assertion is always true, perhaps remove parentheses

### ISSUE THREAD

**Issue by shugydw** [osm-search/Nominatim#1762]
Hi.

I am importing Luxembourg and this syntax warning keeps popping up.
It happened for Index ranks `0 - 4`, `5 - 25` and `26-30`

```bash
2020-04-19 11:40:17 == Index ranks 26 - 30
/app/Nominatim/nominatim/nominatim.py:307: SyntaxWarning: assertion is always true, perhaps remove parentheses?
  assert(False, "Unreachable code")
WARNING: Starting indexing rank (26 to 30) using 10 threads
WARNING: Starting rank 26
```

I am using Ubuntu 18.04 with Python3, PHP 7.4, Postgres 11, Postgis 2.5. If you need any additional info, please let me know.

Danke!

**Comment by lonvia** [comment]
Good catch, I'll fix that immediately. Oddly enough I never see that warning. So I wonder: if you do as it says and remove the parentheses, does the assertion trigger for you?

**Comment by mtmail** [comment]
I see it in the Vagrant ubuntu18 setup and in the travis-ci output https://travis-ci.org/github/osm-search/Nominatim/jobs/676730670

**Comment by lonvia** [comment]
Then it is probably something about the python that ships with Ubuntu. Anyway, fixed now.
