### ISSUE TITLE
unusual attribute address:construction for a certain address in nominatim

### ISSUE THREAD

**Issue by struberg** [osm-search/Nominatim#1763]
I am looking up a house address in nominatim:
https://nominatim.openstreetmap.org/search?country=AT&city=Wien&street=Schweidlgasse%2027&accept-language=de&format=json&addressdetails=1

Returns the street name `Schweidlgasse` as address:construction instead of address:street attribute. But it seems like it's correctly entered as 'street' in OSM itself (checked with both ID and JOSM). Did I do anything wrong when editing the building or is it a glitch in nominatim? Or is it even valid? In which case an explanation would be appreciated - txs!

**Comment by mtmail** [comment]
The detail page of the buliding result https://nominatim.openstreetmap.org/details.php?osmtype=W&osmid=740454178&class=building shows the OSM way the building is linked to.
https://www.openstreetmap.org/way/228960357 is still tagged as `highway=contruction`

**Comment by lonvia** [comment]
We should translate `highway=construction` to `Road` as we do for all other road types. I'm looking into it.

**Comment by struberg** [comment]
Thanks for looking into it!
What surprises me is that an attribute of the linked highway kind of 'erases' the addr:street attribute of the building itself.
