### ISSUE TITLE
wrong results for 55429

### ISSUE THREAD

**Issue by joshuaabel** [osm-search/Nominatim#1765]
what it returns:
https://nominatim.openstreetmap.org/details.php?place_id=237738116

shows up as "Crystal, Pembina County, North Dakota, 55429, United States of America" via api

https://nominatim.openstreetmap.org/search?q=Crystal,%20Pembina%20County&format=jsonv2&addressdetails=1&limit=1

what it should be:
https://nominatim.openstreetmap.org/details.php?osmtype=R&osmid=136672&class=boundary

**Comment by mtmail** [comment]
Based on OSM data, which places got tagged with postal codes (zip codes), I can't tell if Brooklyn Center is a better result than Crystal.

Nominatim looks at the calculated center of the postal codes and that just happens to be in Crystal. http://nominatim.org/release-docs/latest/develop/Postcodes/

https://overpass-turbo.eu/s/T9C
![image](https://user-images.githubusercontent.com/3727288/79918247-4f2d0780-842c-11ea-845a-3e724179388e.png)

**Comment by joshuaabel** [comment]
Zipmap.net shows the majority of 55429 to be Brooklyn Center. https://www.zipmap.net/Minnesota/Hennepin_County/Brooklyn_Center.htm

Also USPS lists the following:
You entered:
55429
RECOMMENDED CITY NAME

MINNEAPOLIS MN
OTHER CITY NAMES RECOGNIZED FOR ADDRESSES IN THIS ZIP CODE™

BROOKLYN CENTER MN
BROOKLYN CTR MN
BROOKLYN PARK MN
CRYSTAL MN


However at the end of it all, I think we can agree it’s not in North Dakota as it currently returns.

**Comment by lonvia** [comment]
> However at the end of it all, I think we can agree it’s not in North Dakota as it currently returns. 

Aha. That's the important piece of information here. Didn't see that originally. That's just a fallout from a data error in the OpenStreetMap data that has been long fixed. I've given the database a nudge to update itself.

**Comment by mtmail** [comment]
https://www.zipmap.net/zip-instructions.htm links to good article on zip codes https://www.coryat.org/2019/03/zip-code-boundary-maps.html

"Users of [zipmap.net] might find differences between our depictions and other depictions and that is absolutely normal and correct. Who is right? The answer is simple. Nobody has the perfect or official Zip Code boundary map. Not even the United States Postal Service."

**Comment by joshuaabel** [comment]
I’m getting the correct(ish) results now, thanks!
