### ISSUE TITLE
China-Bhutan border problem.

### ISSUE THREAD

**Issue by sun-jiao** [osm-search/Nominatim#1767]
China and Bhutan have disputed areas, China assigns some of them to Xiayadong. However, there is no territorial dispute in most areas of Xiayadong, and the whole Xiayadong is assigned to Bhutan in Nominatim results (even the areas controlled by China).

![image](https://user-images.githubusercontent.com/14086980/80101379-e6689b00-85a3-11ea-8b68-e909b359d24d.png)

"下亚东乡, Paro Dzongkhag, 不丹" means "Xiayadong, Paro Dzongkhag, Bhutan".

**Comment by mtmail** [comment]
Nominatim software only returns the data in OpenStreetMap.

**Comment by sun-jiao** [comment]
> Nominatim software only returns the data in OpenStreetMap.

OSM data is right.

**Comment by sun-jiao** [comment]
> Nominatim software only returns the data in OpenStreetMap.

Nominatim return different countries in different zoom level, it's not a data issue.

[zoom = 8, country = China](https://nominatim.openstreetmap.org/reverse?format=xml&lat=27.4269&lon=88.9231&zoom=10&addressdetails=1&accept-language=en)
[zoom = 10, country = Bhutan](https://nominatim.openstreetmap.org/reverse?format=xml&lat=27.4269&lon=88.9231&zoom=10&addressdetails=1&accept-language=en)
[zoom = 18, country = China](https://nominatim.openstreetmap.org/reverse?format=xml&lat=27.4269&lon=88.9231&zoom=10&addressdetails=1&accept-language=en)

**Comment by mtmail** [comment]
The Butan border was broken which can cause issues as fixing it doesn't always guarantee all child places are updated. https://www.openstreetmap.org/changeset/84086218 I looked at the various zoom levels and it seems consistent now. Can you check again if the result match the expectations?

**Comment by sun-jiao** [comment]
> The Butan border was broken which can cause issues as fixing it doesn't always guarantee all child places are updated. Got fixed in https://www.openstreetmap.org/changeset/84086218 and https://www.openstreetmap.org/relation/4052259 I looked at the various zoom levels and it seems consistent now. Can you check again if the result match the expectations?

Oh, OK. So this is still a data issue. Thanks so much.
