### ISSUE TITLE
Town + English powiat name returns nothing

### ISSUE THREAD

**Issue by BenPortner** [osm-search/Nominatim#1771]
Hi guys,

I don't know if this is a bug or if I'm too impatient: 9 days ago, I submitted an update to OSM that added English names to most of the Polish Counties (powiats). Using nominatim, it is now possible to search for the powiats themselves by their English names. However, it is still not possible to search for a village/town in a powiat using village/town name + English county name. 

Example: 
`powiat białogardzki` and `białogard county` both yield the same correct result. However, `tychowo białogard county` returns nothing. Instead, one has to search for `tychowo powiat białogardzki` to get the correct result. Why is that? Is it because the search index was not (completely) updated yet or is this a bug?

Cheers
Ben

**Comment by mtmail** [comment]
I'm adding links to the query and expected result:

https://nominatim.openstreetmap.org/search.php?q=tychowo%2C+białogard+county
should return
https://nominatim.openstreetmap.org/details.php?osmtype=R&osmid=3008996&class=boundary&keywords=1

**Comment by lonvia** [comment]
Areas as large as that county don't trigger complete updates over the entire area for efficiency reasons. I've given Tychowo a kick and you can see that it now can be found under Bialograd County. The rest of the county will sort itself out with time.

**Comment by BenPortner** [comment]
I don't want to be pushy here. But could you give me a rough idea what "will sort itself out with time" means? A month? A year? I'm waiting for these changes to transpire so that I can parse several addresses in Poland that were given to me in English language. If the update takes much longer (it's been two weeks now) then I might consider writing my own solution.

**Comment by lonvia** [comment]
It depends on how often stuff is changed in OSM. In some rural areas of Poland it might take indeed years. I could give it a kick but I have to admit that I have strong reservations about the changes. The names you added are not the English names but just some translation of 'powiat'  which might or might not be correct. You did not even bother to handle `ł` which is not a letter in English. I'm aware that these kind of 'translations' are not uncommon in OSM but that does not mean that they are universally accepted. Neither is [Wikidata/Wikipedia as a source](https://wiki.openstreetmap.org/wiki/Wikidata#Importing_data) by the way.

Anyway, the new name:en don't add enough information to warrant a full reindexing of all of Poland, which would be seriously expensive. You can set up your own Nominatim instance with fresh data and you will get an updated search index.

**Comment by BenPortner** [comment]
@lonvia thanks for your quick answer. I'm sorry to hear that you don't approve my changes. If you provide me a source of "universally accepted" translations for the Polish powiats that you would be willing to push to Nominatim I would be more than willing to implement them.
