### ISSUE TITLE
undefined constant CONST_BasePath

### ISSUE THREAD

**Issue by RailsGuy** [osm-search/Nominatim#1774]
Can you help? I have a Problem after a basic install on ubuntu 18.04 following https://www.nominatim.org/release-docs/3.4.1/appendix/Install-on-Ubuntu-18/

`Apache error log
[php7:warn] PHP Warning:  Use of undefined constant CONST_BasePath - assumed 'CONST_BasePath' (this will throw an Error in a future version of PHP) in /srv/nominatim/Nominatim-3.4.1/website/search.php on line 3
[php7:warn] PHP Warning:  require_once(CONST_BasePath/lib/init-website.php): failed to open stream: No such file or directory in /srv/nominatim/Nominatim-3.4.1/website/search.php on line 3
[pid 7337] PHP Fatal error:  require_once(): Failed opening required 'CONST_BasePath/lib/init-website.php' (include_path='.:/usr/share/php') in /srv/nominatim/Nominatim-3.4.1/website/search.php on line 3
`

I can see CONST_BasePath should be set by /srv/nominatim/build/settings/settings.php

`
 /etc/apache2/conf-available/nominatim.conf
<Directory "/srv/nominatim/Nominatim-3.4.1/website">
  Options FollowSymLinks MultiViews
  AddType text/html   .php
  DirectoryIndex search.php
  Require all granted
</Directory>

Alias /nominatim /srv/nominatim/Nominatim-3.4.1/website

`

**Comment by mtmail** [comment]
This could similar to https://github.com/osm-search/nominatim-org-site/issues/5

Try setting the Apache configuration to the build directory, e.g.

```
<Directory "/srv/nominatim/build/website">
  Options FollowSymLinks MultiViews
  AddType text/html .php
  DirectoryIndex search.php
  Require all granted
  Alias /nominatim /srv/nominatim/build/website
```

**Comment by RailsGuy** [comment]
That was it thank you
