### ISSUE TITLE
Incorrect coordinates output when geocoding using Colombian addresses

### ISSUE THREAD

**Issue by aleangel** [osm-search/Nominatim#1777]
Colombian addresses have this format:
Examples: 
Calle 114A # 21-74, Bogota
Calle 121 # 48-60, Bogota
My code:
`import pandas`
`from geopy.geocoders import Nominatim`
`gc = Nominatim(user_agent="fintu-blog-geocoding-python")`
`gc.geocode("Calle 121 # 48-60, Bogotá")`

 The output coordinates given is incorrect:
`Location(Calle 121, Bella Suiza, Usaquén, Distrito Capital, Bogotá, 110111, Colombia, (4.7000065, -74.0384207, 0.0))`
The correct coordinates for this location are: 4.703244, -74.058373

The same bug happens with all Colombian addresses. Please let me know how to get the correct ones. Thanks in advance

**Comment by lonvia** [comment]
That's a case of missing data in OpenStreetMap. That particular house number [does not exist yet](https://nominatim.openstreetmap.org/reverse.php?format=html&lat=4.703244&lon=-74.058373&zoom=18).

If the housenumber is mapped the search works fine. Example: [Calle 122 # 21-43, Bogotá](https://nominatim.openstreetmap.org/search.php?q=Calle+122+%23+21-43%2C+Bogotá).

**Comment by aleangel** [comment]
Sorry to insist but that is the only address that works correctly. I tried almost 200 others and the location provided is incorrect. How do I Know which part of the city is mapped? and which part is not ? Actually the next house right after that correct address you provide is: 
Calle 122 # 21 31 and when you geocode it:
`gc.geocode("Calle 122 #21-31, Bogotá")`
The output:
`Location(Calle 122, La Alhambra, Distrito Capital, Bogotá, 11211, Colombia, (4.7032773, -74.0567681, 0.0))`
It is totally incorrect. So once again. It does not work for Colombian addresses. You can verify it on google maps: [example](https://www.google.com/maps/dir/Cl.+122+%2321-43,+Bogot%C3%A1/Cl.+122+%2321-31,+Bogot%C3%A1/@4.702157,-74.0543615,17z/data=!3m1!4b1!4m13!4m12!1m5!1m1!1s0x8e3f9ab5eb28999f:0xeb61dbb0cdc96103!2m2!1d-74.0522327!2d4.7020937!1m5!1m1!1s0x8e3f9ab5eb28999f:0x5ffeb7e09df6f526!2m2!1d-74.0521361!2d4.7020783)

**Comment by lonvia** [comment]
Data for Nominatim comes from the OpenStreetMap project. It finds the addresses that are mapped there, nothing more. You can check out which house numbers are already in the data by browsing the map at https://openstreetmap.org.
