### ISSUE TITLE
install nominatim

### ISSUE THREAD

**Issue by ederantonio** [osm-search/Nominatim#1778]
hello I have a question in this step: construction and configuration

Get the source code of the version and unzip it

cd $ USERHOME
wget https://nominatim.org/release/Nominatim-3.4.1.tar.bz2
tar xf Nominatim-3.4.1.tar.bz2

in the terminal this marks me, what's going on?

ubuntuserver@ubuntuserver-VirtualBox:/srv/nominatim$ wget https://nominatim.org/release/Nominatim-3.4.1.tar.bz2
--2020-05-05 11:44:25-- https://nominatim.org/release/Nominatim-3.4.1.tar.bz2
Resolviendo nominatim.org (nominatim.org)... 138.201.190.130
Conectando con nominatim.org (nominatim.org)[138.201.190.130]:443... conectado.
Petición HTTP enviada, esperando respuesta... 200 OK
Longitud: 48539993 (46M) [application/x-bzip2]
Nominatim-3.4.1.tar.bz2: Permiso denegado

No se puede escribir a “Nominatim-3.4.1.tar.bz2” (Conseguido).

**Comment by mtmail** [comment]
I think you forgot to type „tar xz“. That seems like a problem related to unzipping a file or file permissions, not Nominatim.

**Comment by lonvia** [comment]
Also: please use the Nominatim 3.4.2 release. This was not up-to-date in the instructions. I've fixed that now.

**Comment by ederantonio** [comment]
hello, if I see thanks, now what happens to me is that when importing the file it marks this error but I don't know why

ubuntuserver@ubuntuserver-VirtualBox:/srv/nominatim/build$ sudo ./utils/setup.php --osm-file /home/ubuntuserver/mexico-latest.osm.pbf --all 2>&1 | tee setup.log
tee: setup.log: Permiso denegado
2020-05-05 13:19:23 == module path: /srv/nominatim/build/module
2020-05-05 13:19:23 == Create DB
createdb: could not connect to database template1: FATAL:  role "root" does not exist
ERROR: Error executing external command: createdb -E UTF-8 -p 5432 nominatim
string(69) "Error executing external command: createdb -E UTF-8 -p 5432 nominatim"
