### ISSUE TITLE
initial import of the data problem

### ISSUE THREAD

**Issue by ederantonio** [osm-search/Nominatim#1779]
hello, if I see thanks, now what happens to me is that when importing the file it marks this error but I don't know why

ubuntuserver@ubuntuserver-VirtualBox:/srv/nominatim/build$ sudo ./utils/setup.php --osm-file /home/ubuntuserver/mexico-latest.osm.pbf --all 2>&1 | tee setup.log
tee: setup.log: Permiso denegado
2020-05-05 13:19:23 == module path: /srv/nominatim/build/module
2020-05-05 13:19:23 == Create DB
createdb: could not connect to database template1: FATAL: role "root" does not exist
ERROR: Error executing external command: createdb -E UTF-8 -p 5432 nominatim
string(69) "Error executing external command: createdb -E UTF-8 -p 5432 nominatim"

**Comment by mtmail** [comment]
Don't use "sudo".

**Comment by ederantonio** [comment]
Thank you

**Comment by ederantonio** [comment]
once installed nominatim which step is the next one?

**Comment by mtmail** [comment]
Open a new issue if you run into specific installation problems.

**Comment by ederantonio** [comment]
Thank you

**Comment by jonsonasMafjiozas** [comment]
@ederantonio I'm running into the same issue, were you able to get this issue resolved? I'm not using sudo but the error is the same

**Comment by mtmail** [comment]
@jonsonasMafjiozas Make sure you're user 'nominatim' (unix command 'whoami').

Please use https://help.openstreetmap.org/tags/nominatim/ for follow-up questions. We were able to help ederantonio there.
