### ISSUE TITLE
PHPUnit tests fail with PHPUnit 8

### ISSUE THREAD

**Issue by Simon-Will** [osm-search/Nominatim#1781]
With PHP version 7.4 and PHPUnit version 8.5, when I’m in the directory `tests/php/` and execute `phpunit ./`, the following error comes up:

```
PHP Fatal error:  Declaration of Nominatim\AddressDetailsTest::setUp() must be compatible with PHPUnit\Framework\TestCase::setUp(): void in /home/vagrant/Nominatim/test/php/Nominatim/AddressDetailsTest.php on line 12
```

This is because apparently the signature of the `setUp` method changed to include an explicitly declared result type `void`. This also concerns other methods, but they are not used in Nominatim’s tests.

Update the tests so that they work with PHPUnit 8.

**Comment by lonvia** [comment]
Fixed in #1782.
