### ISSUE TITLE
doubt after the nominatim installation 

### ISSUE THREAD

**Issue by ederantonio** [osm-search/Nominatim#1783]
doubt after the nominatim installation what happens next, if I want to work with the reverse option?

**Comment by mtmail** [comment]
After you ran `./utils/setup.php ...` (https://nominatim.org/release-docs/develop/admin/Import-and-Update/) you can run `./utils/check_import_finished.php` to make sure all tables got created and filled with data.

Configuring the updates (http://nominatim.org/release-docs/develop/admin/Import-and-Update/#updates) is optional, you can skip it if you want.

You've already set up Apache (https://nominatim.org/release-docs/develop/admin/Installation/#configure-for-use-with-apache) so you can now open http://<your server name or ip address>/nominatim/search.php in the browser. If there are errors look at the Apache error logs (e.g. `/var/log/apache2/`)

For reverse use http://<your server name or ip address>/nominatim/reverse.php?format=html&lat=21.88&lon=-102.29 (or `format=jsonv2`). See https://nominatim.org/release-docs/develop/api/Reverse/

**Comment by ederantonio** [comment]
Thanks for your patience and help, only I was missing the part of the updates but when I do it it sends the following error:
sudo ./utils/update.php --init-updates
PHP fatal error: Nominatim not detected \ Database error: [500]: Error establishing the database connection: SQLSTATE [08006] [7] FATAL: the role "root" does not exist

released at /srv/nominatim/Nominatim-3.4.1/lib/DB.php on line 36


I don't know if I should go on a new topic

**Comment by mtmail** [comment]
Remove the „sudo“, then it should work.

**Comment by ederantonio** [comment]
I already remove it but it shows me the following:

:/srv/nominatim/build$ ./utils/update.php --init-updates
PHP Fatal error:  Uncaught Nominatim\DatabaseError: [500]: Failed to establish database connection:SQLSTATE[08006] [7] FATAL:  role "ubuntuserver" does not exist

  thrown in /srv/nominatim/Nominatim-3.4.1/lib/DB.php on line 36

**Comment by mtmail** [comment]
Both setup.php and update.php read build/settings/local.php for the database connection string. If the setup.php was able to connect to the database then update.php should have no problem.

I think you're the wrong user. Running `whoami` will tell you which user you are. Try the command as user 'nominatim' (`sudo su nominatim`).

**Comment by ederantonio** [comment]
Thank you very much for your help and patience.
