### ISSUE TITLE
Upgrade Travis-CI from Ubuntu 16 to Ubuntu 18

### ISSUE THREAD

**Issue by mtmail** [osm-search/Nominatim#1787]
In `.travis.yml` we currently test agaist `xenial`, we should use `bionic` going forward. https://docs.travis-ci.com/user/reference/overview/

**Comment by mmd-osm** [comment]
Changing .travis.yml to bionic still passes unit tests. I guess there must be some other reason why this issue is labeled as "help wanted".

https://travis-ci.org/github/mmd-osm/Nominatim/jobs/687177142

**Comment by mtmail** [comment]
We changed several things last week related to Ubuntu 16 (and Ubuntu 20) and that was a left-over. I actually didn't expect it would just pass. Feel free to submit a pull-request if you have a branch open. Otherwise I'll take care in a couple of hours. Thanks a lot!
