### ISSUE TITLE
slow place_id rank 26 

### ISSUE THREAD

**Issue by ederantonio** [osm-search/Nominatim#1788]
hello how are you, the following happens to me when importing from a virtual machine is this correct or what can I do about it?
Done 1570487 in 11225 @ 139.909760 per second - Rank 26 ETA (seconds): 6398.996094
  Done 1570864 in 11227 @ 139.918411 per second - Rank 26 ETA (seconds): 6395.905762
  Done 1571177 in 11228 @ 139.933823 per second - Rank 26 ETA (seconds): 6392.964844
  Done 1571449 in 11230 @ 139.933121 per second - Rank 26 ETA (seconds): 6391.053223
  Done 1571763 in 11232 @ 139.936157 per second - Rank 26 ETA (seconds): 6388.670410
  Done 1571788 in 11234 @ 139.913483 per second - Rank 26 ETA (seconds): 6389.527344
  Slow place_id 2026249
  Slow place_id 2026247
  Done 1571798 in 11236 @ 139.889465 per second - Rank 26 ETA (seconds): 6390.552734
  Slow place_id 2026234
  Done 1571966 in 11238 @ 139.879517 per second - Rank 26 ETA (seconds): 6389.806152
  Done 1572500 in 11239 @ 139.914581 per second - Rank 26 ETA (seconds): 6384.388184
  Done 1572922 in 11241 @ 139.927231 per second - Rank 26 ETA (seconds): 6380.79541

**Comment by lonvia** [comment]
This is an issue tracker, not a general help forum. Please use the mailing list or help.osm.org for generic installation questions.
