### ISSUE TITLE
website apache nominatim 

### ISSUE THREAD

**Issue by ederantonio** [osm-search/Nominatim#1789]
Hello, I pass the following I have apache configured:
<Directory "/srv/nominatim/build/website">
Options FollowSymLinks MultiViews
AddType text/html       .php
DirectoryIndex     search.php
Require all granted
</Directory>
Alias /nominatim /srv/nominatim/build/website

and I have in settings >> local.php:
@define('CONST_Website_BaseURL','http://10.0.2.15/nominatim/');

and navegador :
http://10.0.2.15/nominatim

but when you enter, only two directories appear, one that says main directory and the other .txt, when I click on parent directory it only shows me the apache portal, which is missing if I followed the steps in the nominatim instructions?

**Comment by mtmail** [comment]
Have you tried „ After making changes in the apache config you need to restart apache.“?

**Comment by lonvia** [comment]
@ederantonio you seem to have not read my last comment: This is an issue tracker, not a general help forum. Please use the mailing list or help.osm.org for generic installation questions. Please stop wasting volunteer time. Thank you.

**Comment by ederantonio** [comment]
Hello, what if I have read it, only that the instructions that come are not exact, one has to be supplemented from here and there, I turn to you who are the ones who know and only in this way I can move forward I do not do it to bother, believe me that if I knew I would not be in this problem tracker, also I see that other users ask the same type of questions as I do and it seems that they do not say the same thing to them.
