### ISSUE TITLE
Wrong result for "рафиева 29к2"

### ISSUE THREAD

**Issue by Komzpa** [osm-search/Nominatim#1791]
"рафиева 29к2"

https://www.openstreetmap.org/search?query=%D1%80%D0%B0%D1%84%D0%B8%D0%B5%D0%B2%D0%B0%2029%D0%BA2

Expected: https://www.openstreetmap.org/way/25438365 (house 29 корпус 2 on street улица Рафиева)
Actual: https://www.openstreetmap.org/way/33972622 (street segment)

"рафиева 29 корпус 2"
https://www.openstreetmap.org/search?query=%D1%80%D0%B0%D1%84%D0%B8%D0%B5%D0%B2%D0%B0%2029%20%D0%BA%D0%BE%D1%80%D0%BF%D1%83%D1%81%202

Expected: https://www.openstreetmap.org/way/25438365 (house 29 корпус 2 on street улица Рафиева)
Actual: not found

"рафиева 29/2"
https://www.openstreetmap.org/search?query=%D1%80%D0%B0%D1%84%D0%B8%D0%B5%D0%B2%D0%B0%2029%2F2

Expected: https://www.openstreetmap.org/way/25438365 (house 29 корпус 2 on street улица Рафиева)
Actual: https://www.openstreetmap.org/way/33972622 (street segment)

"рафиева 29 к2" finds right house because of exact match on spelling of house number.

**Comment by lonvia** [comment]
We'd need to know about specific house number formats of different countries and do a country-specific normalisation. It's certainly something that would be nice to have. But to be realistic, it's also still quite a long way from being implemented. We need to implement a complete infrastructure for object-specific normalisation first.

I'll close this issue in favour of #177, which is a good place to start collecting these particularities in house numbering.
