### ISSUE TITLE
PostgreSQL 12 compatibility (lack of consrc)

### ISSUE THREAD

**Issue by huepf** [osm-search/Nominatim#1794]
PostgreSQL 12 removes the `pg_constraint.consrc` column which causes `pg_upgradecluster` to fail:

```
pg_restore: error: could not execute query: ERROR:  column s.consrc does not exist
LINE 28:             "replace"("split_part"("s"."consrc", ''''::"text...
                                            ^
HINT:  Perhaps you meant to reference the column "s.conkey" or the column "s.conbin".
Command was: 
-- For binary upgrade, must preserve pg_type oid
SELECT pg_catalog.binary_upgrade_set_next_pg_type_oid('2424041'::pg_catalog.oid);
```

Documentation:  
The docs for 11 still include consrc, but recommend to use pg_get_constraintdef
[PostgreSQL 12](https://www.postgresql.org/docs/12/catalog-pg-constraint.html)
[PostgreSQL 11](https://www.postgresql.org/docs/11/catalog-pg-constraint.html)

**Comment by mtmail** [comment]
In which part of the Nominatim installation or operation do you see this error? I see other projects have made changes (e.g. https://github.com/typeorm/typeorm/commit/ce7cb167cf788ca6eb91dfcd74bb9f07c651eb9d) but can't find `consrc` anywhere in Nominatim source code.

**Comment by huepf** [comment]
I tried to upgrade an older installation (nominatim 3.0.1)

**Comment by lonvia** [comment]
We don't support upgrading the Postgres version for an existing database. You are on your own here, I'm afraid. In any case, nominatim 3.0.1 is seriously old. If you upgrade, you should upgrade Nominatim as well to the latest version and do a reimport.
