### ISSUE TITLE
[Bad Search Result] City name in Post Code 

### ISSUE THREAD

**Issue by Adrjanjan** [osm-search/Nominatim#1795]
URL of the query that produces the bad result:
https://nominatim.openstreetmap.org/reverse.php?format=html&lat=50.30454857635719&lon=18.659484386444092&zoom=18

The result I'm getting:
"Drogowa Trasa Średnicowa, Osiedle Powstańców Śląskich, Szobiszowice, **Gliwice**, Górnośląsko-Zagłębiowska Metropolia, województwo śląskie, **44-100 GLIWICE**, Polska (Primary)"

Should be: 
"Drogowa Trasa Średnicowa, Osiedle Powstańców Śląskich, Szobiszowice, **Gliwice**, Górnośląsko-Zagłębiowska Metropolia, województwo śląskie, **44-100**, Polska (Primary)"

As seen here city name is contained also in post code. 
I did not find any similar cases in my app, so I suppose it was an error while saving this post code.

**Comment by mtmail** [comment]
Yes, looks like it. We have a short guide http://nominatim.org/release-docs/latest/develop/Postcodes/ (the Overpass query near the end) on how to find such places. I see the uppercasing and possibly normalization make it harder to debug. I'll see if I can find and fix it.

**Comment by mtmail** [comment]
Fixed in https://www.openstreetmap.org/changeset/85095951 Postcodes in Nominatim are recalculated once per night so it will take 24h to be reflected in search results.
