### ISSUE TITLE
 website search.php is not displayed

### ISSUE THREAD

**Issue by ciellink** [osm-search/Nominatim#1798]
Hi,
I am having trouble viewing the nominations directory, I have the settings at https://nominatim.org/release-docs/latest/appendix/Install-on-Ubuntu-18/

contained in   / srv / nominatim / build / settings local.php

@define ('CONST_Website_BaseUrl', 'http: // localhost / nominatim /');

contained in   / etc / apache2 / conf-available

<Directory "/ srv / nominatim / build / website">
FollowSymLinks MultiViews options
AddType text / html .php
Require all awarded
</Directory>
Alias ​​/ nominatim / srv / nominatim / build / website

contained in  000-default.conf
ServerAdmin webmaster @ localhost
DocumentRoot / srv / nominatim

<Directory "/ srv / nominatim / build / website">
Options FollowSymLinks MultiViews
AddType text / html .php
DirectoryIndex search.php
Require all granted
</Directory>
Alias ​​/ nominatim / srv / nominatim / build / website
</virtualhost>

is not displayed in the browser
http: //localhost/nominatim/search.php as if not entering nominatim

**Comment by lonvia** [comment]
None of these configs looks semantically correct. Please read the instructions again and make sure you have followed all the steps.

Also note that  this is an issue tracker not a general help forum. If you have questions about the installation process. please use the mailing list or help.openstreetmap.org.
