### ISSUE TITLE
Searching for russian street with transliterated version fails to find it

### ISSUE THREAD

**Issue by oniongarlic** [osm-search/Nominatim#1803]
Kurskaya Ulitsa 28,Sankt-Peterburg
-> No results

Курская улица 28,Sankt-Peterburg
-> Finds the right location (but top result is a bus stop, not the building)

**Comment by mtmail** [comment]
Thanks. Looks like "Курская улица" it gets normalized to "kurskaia ul" https://nominatim.openstreetmap.org/details.php?osmtype=W&osmid=117329146&class=highway&keywords=1

**Comment by lonvia** [comment]
I'm not sure there is a lot we can do here. There is no one valid transliteration for Russian around. Nominatim transliterates `Курская` to `kurskaia`. You prefer `Kurskaya`. translit.cc recommends `Kurskaja`. The only way to catch that would be to handle them as misspellings and be more lenient with those. This is still a long way away, I'm afraid.
