### ISSUE TITLE
Missing values at country level for details.php?addressdetails=1

### ISSUE THREAD

**Issue by jtheiner** [osm-search/Nominatim#1806]
When requesting details (addressdetails=1) e.g. [details.php?osmtype=W&osmid=518071791&class=tourism&format=json&addressdetails=1](https://nominatim.openstreetmap.org/details.php?osmtype=W&osmid=518071791&class=tourism&format=json&addressdetails=1) values like "place_id" and "osm_id" are missing at country level:
 `"address": [..., {"localname":"Germany","place_id":null,"osm_id":null,"osm_type":null,"place_type":null,"class":"place","type":"country","admin_level":null,"rank_address":4,"distance":0,"isaddress":true}]`

Is there a reason this is missing or it is a bug?
Limiting a reverse query to country level returns the correct data anyway.

**Comment by mtmail** [comment]
That's an optimization. In the Nominatim data schema each place is assigned a country (those outside any countries like oil platforms or ship wrecks have a catch-all country assigned). Thus during search a name is looked up but nothing else, for example it's not double-checked again if the place is really inside the boundaries of the country. When searching for the country directly everything is looked up of course.

The /details endpoint is meant for debugging. http://nominatim.org/release-docs/latest/api/Details/ Were you just wondering or are the ids needed?

**Comment by jtheiner** [comment]
Thanks for reply.
I was just interested since I don't use the details endpoint for debugging purpose only. Based on your answer, there's no need to fix it and thus this issue can be closed. I'll probably implement this locally.

**Comment by mtmail** [comment]
The lookup logic of parent address lines happens in `sql/functions/address_lookup.sql`.

But you can probably make a change in `__construct` in `lib/AddressDetails.php`, inspect what the database returns and run a second query to fetch missing data.
