### ISSUE TITLE
Issues with Berlin

### ISSUE THREAD

**Issue by Megachip** [osm-search/Nominatim#1807]
Seems the City is lost on most reverse requests:
Moabit: http://nominatim.openstreetmap.org/reverse?format=json&lat=52.52207&lon=13.352509&zoom=16&accept-language=en&addressdetails=1 http://nominatim.openstreetmap.org/reverse?format=geocodejson&lat=52.52207&lon=13.352509&zoom=16&accept-language=en&addressdetails=1
2. Moabit: http://nominatim.openstreetmap.org/reverse?format=json&lat=52.525413&lon=13.366241&zoom=16&accept-language=en&addressdetails=1 http://nominatim.openstreetmap.org/reverse?format=geocodejson&lat=52.525413&lon=13.366241&zoom=16&accept-language=en&addressdetails=1

https://nominatim.openstreetmap.org/reverse?format=json&lat=52.525&lon=13.366&zoom=16&accept-language=en&addressdetails=1

**Comment by lonvia** [comment]
Looks like a data issue that happened when Berlin got changed into a cycling route. Given that this already happened in March and we were on an older version of Nominatim then it is impossible now to figure out what exactly happened. Reindexed the affected parts now.

There is still a glitch in the address typing which I'd like to fix before closing this issue.
