### ISSUE TITLE
New/renamed fields within address in json

### ISSUE THREAD

**Issue by Megachip** [osm-search/Nominatim#1808]
Looks like we getting a lot of new fields within the `address` instead of the old known ones: `Country, State, State_District, County, City, Town, Village, City_district, Suburb`
Now we getting names like

- borough
- district
- territory
- municipality

Is there anywhere a document which describes the new names or how they map/fit to the old ones?

**Comment by mtmail** [comment]
I haven't seen territory yet. The others are listed in https://github.com/osm-search/Nominatim/blob/master/settings/address-levels.json Municipality is "bigger" than a city, smaller than a county (German: Kreis). District larger, usually a set of, boroughs/neighborhood (German: Bezirk, e.g. https://de.wikipedia.org/wiki/Bezirk_Wandsbek)

**Comment by lonvia** [comment]
`address-level.json` is indeed the best source. I need to see if we can auto-generate a list that can be added to the documentation.

**Comment by Megachip** [comment]
> I haven't seen territory yet. The others are listed in https://github.com/osm-search/Nominatim/blob/master/settings/address-levels.json Municipality is "bigger" than a city, smaller than a county (German: Kreis). District larger, usually a set of, boroughs/neighborhood (German: Bezirk, e.g. https://de.wikipedia.org/wiki/Bezirk_Wandsbek)

It seems names just taken from the `place=` value. So find territory in Australia. So very uncommon: https://taginfo.openstreetmap.org/tags/?key=place&value=territory But not easy to parse a json, which is not defined :(
