### ISSUE TITLE
Question on geocoding

### ISSUE THREAD

**Issue by srinathsrk76** [osm-search/Nominatim#1810]
Can someone please help me understand the location that Nominatim returns when I pass address as city, state, country? Is it city centroid coordinates or what's the definition here?

**Comment by mtmail** [comment]
Centroid. When a relation has a node member (role=label) then that is used as centroid. Many large cities, states, country have a definition what their center is, e.g. the central marketplace, a statue or historic building. Also useful when a relation is very large. 

Example: Tokyo state is very large with many islands https://www.openstreetmap.org/relation/1543125 Below the table on the left you see  "Node Tokyo (265018692) as label". Thus the center point Nominatim returns is https://www.openstreetmap.org/node/265018692

Same for Hamburg https://www.openstreetmap.org/relation/62782

**Comment by srinathsrk76** [comment]
Very helpful, thanks!
