### ISSUE TITLE
Ways processing very slow 

### ISSUE THREAD

**Issue by jonsonasMafjiozas** [osm-search/Nominatim#1816]
Hello, I'm importing full planet, but processing the ways is taking to long started at 0.36k/s and after 2 days reached 2.30k/s and still running, is this normal?

Processing: Node(6023704k 4644.3k/s) Way(487766k 3.03k/s) Relation(0 0.00/s)

**Real memory:** 20.63 GiB used / 29.48 GiB cached / 58.97 GiB total
**Virtual memory:** 173.25 MiB used / 1.99 GiB total
**Local disk space:** 381.06 GiB used / 1.16 TiB free / 1.53 TiB total

<img width="929" alt="Screen Shot 2020-05-30 at 10 43 32 AM" src="https://user-images.githubusercontent.com/15992747/83335549-72847700-a262-11ea-87d5-b7f25b09149b.png">

Update: after 3 and a half days:
Relation stats: total(7825274), max(11111523) in 92933s
Stopping table: planet_osm_nodes
Stopped table: planet_osm_nodes in 0s
Stopping table: planet_osm_ways
Stopped table: planet_osm_ways in 0s
Stopping table: planet_osm_rels
Building index on table: planet_osm_rels
Stopped table: planet_osm_rels in 612s

Osm2pgsql took 287084s overall
node cache: stored: 2264544947(37.59%), storage efficiency: 92.21% (dense blocks: 273760, sparse nodes: 106561537), hit rate: 32.80%
2020-06-01 06:19:59 == Create Functions
2020-06-01 06:20:04 == Create Tables
2020-06-01 06:20:06 == Create Functions
2020-06-01 06:20:06 == Create Partition Tables
2020-06-01 06:20:08 == Create Partition Functions
2020-06-01 06:20:09 == WARNING: wikipedia article dump file not found - places will have default importance
2020-06-01 06:20:09 == WARNING: wikipedia redirect dump file not found - some place importance values may be missing
2020-06-01 06:20:09 == Drop old Data
......................................................................................................................................................................................................................................................................
2020-06-01 06:20:11 == Loading word list

Now stuck on **Loading word list** for about 12 hours

**Comment by mtmail** [comment]
It looks looks slow indeed. Several days of import time is expected but usually not days in the osm2pgsql step, that's only 10-20% of the total import.

Is this a "real" server or inside a virtual machine? Is postgresql installed locally or on a network-connected storage. Does the postgresql log file give any clues? Did you set postgresql tuning settings like http://nominatim.org/release-docs/latest/admin/Installation/#postgresql-tuning ?

**Comment by jonsonasMafjiozas** [comment]
Thanks for the reply, 
The server is inside a virtual machine (VPS), I did set the postgresql config as recommended for the 64GB RAM 
I've canceled the last import and started all over again after increasing the max_wal_size to 8GB, but it seems like it's going with the same slow rate. 
**Processing: Node(6023704k 1305.0k/s) Way(577k 0.17k/s) Relation(0 0.00/s)**
Please let me know if there are any helpful information i can provide?
Appreciate your help!

**Comment by mtmail** [comment]
Try checking the storage setup. You write 1.5TB available, but in some VM setups that means it starts low and then auto-increases until it hits the maximum. And each increase will slow down execution of the client operating system.
The Postgresql tuning parameter help. But if applied and you still see such slow import it's more likely hardware or operating system related. From software and configuration there aren't more tricks I'm aware of.

**Comment by jonsonasMafjiozas** [comment]
Thanks you so much!!
