### ISSUE TITLE
bogus search results for "Germany, Hamburg, Hamburg"

### ISSUE THREAD

**Issue by ukleinek** [osm-search/Nominatim#1817]
https://nominatim.openstreetmap.org/search.php?q=Germany%2CHamburg%2C+Hamburg&polygon_geojson=1&viewbox= lists a small village first in its search results (https://nominatim.openstreetmap.org/details.php?osmtype=R&osmid=3549480&class=boundary) even though the spelling is different from the searched term.

I would have expected that https://nominatim.openstreetmap.org/details.php?osmtype=N&osmid=565666208&class=place is listed first. IMHO having "Hamburg" twice in the search term is fine as Hamburg is both the state and the city. For "Bremen"  the same works fine (i.e. searching for "Germany, Bremen, Bremen); for "Berlin" the same results in a first hit at least in Berlin.

**Comment by lonvia** [comment]
I'm afraid this is not fixable. Hamburg may be a city _and_ a state but it is not a city _in_ a state. OpenStreetMap has exactly one boundary for it and we'd have to artificially duplicate it in the search terms to achieve the effect. Same goes for Berlin. Bremen is actually slightly different as it is a state consisting of Bremen and Bremerhaven.

**Comment by ukleinek** [comment]
Ah, so location A is only "in" location B if A ⊂ B but not if the borders match and A is conceptually in B (because A is a city and B a state)? I wonder if this is a shortcoming of the data model that affects more locations than the city states in Germany.

Also looking at the details of Hamburg, the city seems to include an island in the west of the city which isn't included in the state. I don't know the details but I wonder if this is right.

**Comment by lonvia** [comment]
The problem actually only occurs with computers not with humans. No human would ever search for 'hamburg, hamburg' because for a human it's a 'city state' not a 'city and state'. I suspect that you are trying to geocode from some kind of form that always has a city and a state entry. I challenge that the wrong assumption is in the form as it assumes that state and city are always distinct entities.

**Comment by ukleinek** [comment]
Actually I try to parse https://wiki.debian.org/Keysigning/Offers where for Berlin, Bremen and Hamburg the city state's name is repeated. The motivation why the people added the name twice is unknown to me, but at least it was not forced by some form check :-) The obvious workaround is of course to drop this duplication.

Thanks for your feedback.
