### ISSUE TITLE
New GB postcode February 2020-05 file

### ISSUE THREAD

**Issue by mtmail** [osm-search/Nominatim#1819]
A new file got released on http://www.ordnancesurvey.co.uk/opendatadownload/products.html#CODEPO. I converted it according to http://nominatim.org/release-docs/develop/data-sources/GB-Postcodes/ and placed it on https://downloads.opencagedata.com/public/gb_postcode_data.202005.sql.gz (35MB)

**Comment by lonvia** [comment]
Now available on nominatim.org.
