### ISSUE TITLE
Possible improvement for searching with house number 

### ISSUE THREAD

**Issue by joy-yyd** [osm-search/Nominatim#1821]
Hello, 
we have many issues of getting no result when search the address with the house number in Austria, 
For example: 
1) https://nominatim.openstreetmap.org/search.php?q=Kreuzberg%2C+310%2C++Gro%C3%9F+Gerungs%2C+3920&polygon_geojson=1&viewbox=
(However it found result when there is no housenumber:
https://nominatim.openstreetmap.org/search.php?q=Kreuzberg%2C++Gro%C3%9F+Gerungs%2C+3920&polygon_geojson=1&viewbox=)
2) https://nominatim.openstreetmap.org/search.php?q=Johannes+von+Gott-Platz%2C+1+%2C+7000+&polygon_geojson=1&viewbox=
(Found: https://nominatim.openstreetmap.org/search.php?q=Johannes+von+Gott-Platz%2C+7000+&polygon_geojson=1&viewbox=)

We've downloaded the Austria data to test locally, in the table _placex_, we can find the housenumber value with the matching name. 
And in the source code of Geocode.php (https://github.com/osm-search/Nominatim/blob/master/lib/Geocode.php#L799), we found the search process passes rank limit first, and then interpolates housenumbers for rank_address = 30

I am wondering, if the parent placeId with rank_address 30 had been dropped before reached the code for interpolating housenumbers? Is it possible to assign a higher 'houenumber' weight or modify the process for passing rank limits?

Thanks a lot for your advice!
Joy

**Comment by lonvia** [comment]
There is a long-standing bug #164 that you can't search for a named object and a housenumber at the same time.

That said, the two examples you give look rather badly mapped to me.

The address of the Kreuzberg restaurant come from [this node](https://www.openstreetmap.org/way/49272732) which has `addr:street=Kreuzberg` as a tag but there is no street `Kreuzberg`. So Nominatim assumes that this is a mapping error and ignores it. Add a landuse with name=Kreuzberg and change the tagging to `addr:place=Kreuzberg` and all will be well.

The second example has a similar issue. There is no `Johannes von Gott-Platz` mapped anywhere, so nothing to attach the address to.
