### ISSUE TITLE
New South Wales (state) missing in Australian address results

### ISSUE THREAD

**Issue by Megachip** [osm-search/Nominatim#1823]
Looks some entities (state etc) in new south wales:
![image](https://user-images.githubusercontent.com/487352/84203890-802fcd00-aaaa-11ea-90bd-0a1af3cce038.png)
![image](https://user-images.githubusercontent.com/487352/84203987-aa818a80-aaaa-11ea-92e4-d4b8a88906e8.png)

https://www.openstreetmap.org/relation/6079484
https://www.openstreetmap.org/relation/6079550
https://nominatim.openstreetmap.org/reverse?format=json&lat=-35.836742&lon=150.178986&zoom=42&accept-language=en&addressdetails=1

**Comment by mtmail** [comment]
The report requires guessing. Do you mean the address returned doesn't contain the Australian state (admin_level=4)?

**Comment by Megachip** [comment]
> The report requires guessing. Do you mean the address returned doesn't contain the Australian state (admin_level=4)?

Oh, yes. Sorry.

**Comment by mtmail** [comment]
Ok, thanks. Could potentially be solved by reindexing the area (I personally don't have access to the server).

Rephrasing:
Broulee (`admin_level=10`, `place=locality`, https://nominatim.openstreetmap.org/details.php?osmtype=R&osmid=6079484) and its linked node (`place=hamlet`, https://nominatim.openstreetmap.org/details.php?osmtype=N&osmid=113259464&class=place) have no state in their address lines. The state (https://www.openstreetmap.org/relation/2316593/) is mapped fine in OSM and I can't see any recent boundary issues or changes.

**Comment by Megachip** [comment]
> Rephrasing:
> Broulee (`admin_level=10`, `place=locality`, https://nominatim.openstreetmap.org/details.php?osmtype=R&osmid=6079484) and its linked node (`place=hamlet`, https://nominatim.openstreetmap.org/details.php?osmtype=N&osmid=113259464&class=place) have no state in their address lines. The state (https://www.openstreetmap.org/relation/2316593/) is mapped fine in OSM and I can't see any recent boundary issues or changes.

Not sure, if it is just Broulee. As you see, I've the same issue with Mossy Point and also Eurobodalla.
![image](https://user-images.githubusercontent.com/487352/84207436-aa38bd80-aab1-11ea-989d-46f17b2b84c6.png)
But Shire itself is resolved correct.

**Comment by lonvia** [comment]
data issue

**Comment by Megachip** [comment]
> data issue

Means issue is on OSM side and not nominatim?
