### ISSUE TITLE
PHP Fatal error:  Uncaught Nominatim\DatabaseError: [500]: Database server failed to load /build/module/nominatim.so module

### ISSUE THREAD

**Issue by chhaunkar96** [osm-search/Nominatim#1824]
Hello,
I'm getting the following error.

```
kaushal@kaushal-pc:~/Desktop/OSM/Nominatim$ ./build/utils/setup.php --osm-file ~/nominatimdata/bhutan.osm.pbf --all
2020-06-10 14:15:45 == module path: /home/kaushal/Desktop/OSM/Nominatim/build/module
2020-06-10 14:15:45 == Create DB
2020-06-10 14:15:45 == Setup DB
Postgres version found: 11
Postgis version found: 3
PHP Fatal error:  Uncaught Nominatim\DatabaseError: [500]: Database server failed to load /home/kaushal/Desktop/OSM/Nominatim/build/module/nominatim.so module

  thrown in /home/kaushal/Desktop/OSM/Nominatim/lib/DB.php on line 62
```

Permissions:
![image](https://user-images.githubusercontent.com/29665934/84247450-c118f780-ab25-11ea-8eba-c7cb070cf891.png)

![image](https://user-images.githubusercontent.com/29665934/84247543-e443a700-ab25-11ea-9098-83983dd8a88e.png)

**Comment by chhaunkar96** [comment]
Thanks for your reply.
I create build again using these instructions 
https://nominatim.org/release-docs/latest/appendix/Install-on-Ubuntu-18/

I added permission 777 for every user but no luck.

Current permissions:
![image](https://user-images.githubusercontent.com/29665934/84347813-1bbb5d80-abd1-11ea-8a7f-694a8567ba2c.png)

![image](https://user-images.githubusercontent.com/29665934/84347850-35f53b80-abd1-11ea-995b-bb5581336736.png)

![image](https://user-images.githubusercontent.com/29665934/84347897-532a0a00-abd1-11ea-8b53-6b2f8761cdcd.png)

> I advise not to install Nominatim in your home directory. From the screenshot every file is read+write+executable and you will run a webserver which accesses the build directory and potentially opens ports to the outside network. A separate user account and directory (/src/nominatim) as described in the installation instructions is safer.
I'll change after once if it works. Just I'm trying to run it anyhow.

**Comment by mtmail** [comment]
I wasn’t clear enough. For security the database won’t load a module that every user can change (write) to. 777 permissions are not required. The link I posted shows the permissions needed.

> I'll change after once if it works. Just I'm trying to run it anyhow.

I wasn’t clear enough. I meant: do it. Follow the instructions line by line, any deviation costs support time.

**Comment by mtmail** [comment]
I think you’re close to get it running. I’ll update the instructions to make it more clear what the permissions should be.

**Comment by chhaunkar96** [comment]
I have changed again all permission but still the same problem.

![image](https://user-images.githubusercontent.com/29665934/84354137-fda82a00-abdd-11ea-85fb-ac5b24b079f7.png)


![image](https://user-images.githubusercontent.com/29665934/84354229-24fef700-abde-11ea-9226-39ddac5a0100.png)

**Comment by chhaunkar96** [comment]
I tried the following permissions also but no luck.

![image](https://user-images.githubusercontent.com/29665934/84355207-d18da880-abdf-11ea-8cd3-60a06c6138d4.png)
![image](https://user-images.githubusercontent.com/29665934/84355261-eec27700-abdf-11ea-921f-5362b366fc76.png)

**Comment by mtmail** [comment]
We just had a similar issue on a server. The same error message is printed when`nominim.so` when the operating system changed, postgresql got upgraded or libraries got moved. Try:

```
cd build
rm -r module/
cmake ../Nominatim
make
```

**Comment by chhaunkar96** [comment]
It's fixed by making build using nomimatim user.
I made build agian using following command. It worked for me.
`sudo -u nominatim make`

**Comment by mtmail** [comment]
Awesome. I'll check how we can improve the error message and FAQ entry.
