### ISSUE TITLE
issue proj52-epsg

### ISSUE THREAD

**Issue by netluca1** [osm-search/Nominatim#1825]
hi I wanted to expose the problem I'm having.
I am attempting to install nominatim 3.5.0 I have performed a clean installation of Centos8 and following your guide I have run aground on a couple of points.
First of all the guide you have documented (https://nominatim.org/release-docs/latest/appendix/Install-on-Centos-8/) talks about Postgres 10, while it is said (https://nominatim.org/release -docs / develop / admin / Installation /) which also supports version 11 with postgis 2.5 well I wanted a confirmation.
After installing and updating centos8, I will install the necessary programs x Nominatim.
I run:
sudo dnf --enablerepo = PowerTools install -y postgresql11-server postgresql11-contrib postgresql11-devel
sudo dnf --enablerepo = PowerTools install -y postgis25_11 postgis25_11-utils
sudo dnf --enablerepo = PowerTools install -y wget git cmake make gcc gcc-c ++ libtool policycoreutils-python-utils
sudo dnf --enablerepo = PowerTools install -y llvm-toolset ccache clang-tools-extra
sudo dnf --enablerepo = PowerTools install -y php-pgsql php php-intl php-json libpq-devel
sudo dnf --enablerepo = PowerTools install -y proj52-epsg bzip2-devel proj-devel boost-devel
sudo dnf --enablerepo = PowerTools install -y python3-pip python3-setuptools python3-devel expat-devel zlib-devel

Error: Could not find a match: proj52-epsg.
how do i solve?
can you help me?

**Comment by mtmail** [comment]
Nominatim will work with postgresql 10/11/12 and postgis 2.5/3.0 and possibly more combinations. 

I remember having trouble with `proj` on centos 8, that's why the centos 7 instructions use postgresql11 but the centos 8 instructions use the lower postgresql 10.

**Comment by lonvia** [comment]
Do we even still need proj? osm2pgsql can be compiled without it these days and we use all data unprojected.

**Comment by netluca1** [comment]
so I can exclude proj52 and go on or do you recommend leaving postgres 10.
@mtmail if i need help can we feel email us?

**Comment by mtmail** [comment]
I tested the centos8 vagrant install script without proj52 and it imported a country fine. I'll create a PR.

**Comment by mtmail** [comment]
Also tested postgresql 11, postgis 2.5 combination now. That works.

@netluca1 try removing the 'proj52-epsg' from the `sudo dnf` line.

**Comment by netluca1** [comment]
@mtmail I noticed that in the installation there is no more postgis25_11-utils but only postgis25_11.
It's not necessary any more
