### ISSUE TITLE
Error while running search indices

### ISSUE THREAD

**Issue by jonsonasMafjiozas** [osm-search/Nominatim#1833]
2020-06-15 02:44:42 == Create Search indices
ERROR:  invalid page in block 166877 of relation base/19232/12950811
ERROR: pgsql returned with error code (3)
string(34) "pgsql returned with error code (3)"

 
 nominatim@vmi394996:~/build$./utils/check_import_finished.php                                      Checking database got created ... OK
Checking nominatim.so module installed ... OK
Checking place table ... OK
Checking indexing status ... OK
Search index creation
Checking index idx_word_word_id ... OK
Checking index idx_place_addressline_address_place_id ... OK
Checking index idx_placex_rank_search ... OK
Checking index idx_placex_rank_address ... OK
Checking index idx_placex_pendingsector ... Failed
        Hints:
        * Rerun the setup.php --create-search-indices step
nominatim@vmi394996:~/build$ setup.php --create-search-indices step
setup.php: command not found
nominatim@vmi394996:~/build$ ./utils/setup.php --create-search-indices
2020-06-15 04:16:13 == module path: /srv/nominatim/build/module
2020-06-15 04:16:13 == Create Search indices
ERROR:  relation "idx_word_word_id" already exists
ERROR: pgsql returned with error code (3)
string(34) "pgsql returned with error code (3)"
<img width="650" alt="Screen Shot 2020-06-14 at 7 20 45 PM" src="https://user-images.githubusercontent.com/15992747/84612001-28abab80-ae74-11ea-9370-4103c188e5e0.png">

**Comment by mtmail** [comment]
The `invalid page in block 166877 of relation base/19232/12950811` points to a serious database issue, possibly not all data was written to disk or other hardware issue. You'd need to check the Postgresql documentation/issue tracker what exactly to do. Also check the Postgresql logfile for hints. If you want to be on the safe side delete the database and start the setup from the beginning.

`./utils/setup.php --create-search-indices` runs the SQL commands in https://github.com/osm-search/Nominatim/blob/master/sql/indices.src.sql and https://github.com/osm-search/Nominatim/blob/master/sql/indices_search.src.sql You can delete any existing index. The index names are highlighted in purple color in the github page. So:

```sql
DROP INDEX IF EXISTS idx_word_word_id;
DROP INDEX IF EXISTS idx_place_addressline_address_place_id;
```
etc. From your screenshot it's not clear at which point the database crashed. You'll need to do some testing how many indices need to be deleted first.

**Comment by jonsonasMafjiozas** [comment]
I deleted the 2 suggested indices and re ran ./utils/setup.php --create-search-indices
It didn't through an error, hopefully it will threw me the error: "ERROR: invalid page in block 166877 of relation base/19232/12950811"
if it did you think it will be best to drop the DB and start over again, correct?

**Comment by lonvia** [comment]
`./utils/setup.php --create-search-indices --ignore-errors` should also do the trick. We should improve the output for check_import_finished.php.

If the error appears again, google for `postgresql invalid page in block` to find a couple of hints how to find and fix the broken part. If it's an index you might be in luck, otherwise you have to start over again.

**Comment by jonsonasMafjiozas** [comment]
Thank you so much!

**Comment by jonsonasMafjiozas** [comment]
@lonvia just wanna confirm that your recommendation did the trick and both reverse and search are running very smooth! Appreciate all the help :)
