### ISSUE TITLE
./utils/update.php --init-updates (output is an older date)

### ISSUE THREAD

**Issue by jonsonasMafjiozas** [osm-search/Nominatim#1835]
nominatim@vmi394996:~/build$ ./utils/update.php --init-updates
2020-06-17 02:09:48 == module path: /srv/nominatim/build/module
2020-06-17 02:09:48 == Create Functions
Done. Database updates will start at sequence 4048029 (2020-06-02T15:28:16Z)

**Comment by mtmail** [comment]
That’s expected. You initialized the updates now, you didn’t run any updates yet.
