### ISSUE TITLE
Strange results for search "Dieburg"

### ISSUE THREAD

**Issue by lytenyn** [osm-search/Nominatim#1837]
I hope this is the correct place for this report.

If I search for "Dieburg" (a town in Germany) on https://nominatim.openstreetmap.org/, like this:

https://nominatim.openstreetmap.org/search.php?q=Dieburg&polygon_geojson=1&viewbox=

-> the first result is the country "Bulgaria".

Even if I restrict the search and look for a city of the name like this:

https://nominatim.openstreetmap.org/search.php?street=&city=Dieburg&county=&state=&country=&postalcode=&polygon_geojson=1&viewbox=

-> the first result is "Bergamo".

This may be related to the fact that "die" is a German article, but in this case, it is part of the name itself. Searching for other German cities that start with "Die" does not show this behaviour (Diepholz, Diemelstadt).

I believe that the first search result should be the exact match.

**Comment by mtmail** [comment]
Dasburg (https://en.wikipedia.org/wiki/Dasburg) is also affected.

Add &debug=1 to see that Nominatim is doing internally.

Looks like Nominatim searches for 'bg' only. With fewer result candidates Dieburg would probably be ranked higher if not first, but 'bg' as abbreviation for Burg (German: castle) and Berg (German: mountain) is part of too many matching names.

**Comment by lonvia** [comment]
That's been a long-standing issue. "Die" in France is similarly unsearchable, see #1078 

Unfortunately, we need to reimplement abbreviation handling to fix that. This is currently tracked in #1208. Closing this ticket as duplicate.
