### ISSUE TITLE
Wrong place linkings in geocoding results in Nominatim 3.5

### ISSUE THREAD

**Issue by geoneutrino** [osm-search/Nominatim#1844]
Seems to be an issue with the 3.5 update - many results now return addresses with a wrong information of place=isolated_dwelling in addressdetails
e.g.
https://nominatim.openstreetmap.org/search.php?q=71723+Gro%C3%9Fbottwar+Wacholderstra%C3%9Fe+27&polygon_geojson=1&viewbox=
returns place=isolated_dwelling Benzenmühle (a single house several hundred meters away of the street)
https://nominatim.openstreetmap.org/details.php?osmtype=W&osmid=477346469&class=building

other example
https://nominatim.openstreetmap.org/search.php?q=Kastanienweg+16%2C+67256+Weisenheim+am+Sand&polygon_geojson=1&viewbox=
contains tag place=isolated_dwelling Eyersheimer Hof (2 kilometers outside the city)
https://nominatim.openstreetmap.org/details.php?osmtype=W&osmid=334155360&class=building

Maybe it is linked to 
https://github.com/osm-search/Nominatim/issues/575
but in the update this effect seems to be caused very often (and a house found directly as result shouldn't be linked to another place ?)

**Comment by mtmail** [comment]
I checked the addresses against the test setup of this PR https://github.com/osm-search/Nominatim/pull/1836 and the addresses look better. Note that test setup doesn't have house number imported.

http://kilda.lonvia.de/places/search.php?q=71723+Gro%C3%9Fbottwar+Wacholderstra%C3%9Fe&polygon_geojson=1
Wacholderstraße, Großbottwar, Landkreis Ludwigsburg, Baden-Württemberg, Germany 

http://kilda.lonvia.de/places/search.php?q=Kastanienweg%2C+67256+Weisenheim+am+Sand&polygon_geojson=1
Kastanienweg, Weisenheim am Sand, Freinsheim, Landkreis Bad Dürkheim, Rhineland-Palatinate, Germany

**Comment by geoneutrino** [comment]
Thanks. seems to be better with the test setup

As a generic improvement: in this cases we found exact buildings, both containing all addr:* tags. Is it useful to "enhance" the result with isolated_dwelling nearby (as per wiki definition isolated_dwelling itself are only 1 or 2 houses)

**Comment by mtmail** [comment]
The tags on the building https://www.openstreetmap.org/way/117637178 for example look alright. House addresses belonging to a hamlets and isolated_dwellings only need `addr:place` and `addr:house_number`. In Germany those don't have streets with names. It's a common misconception and I've made the mistake myself to mapped a couple thinking "there has to be a street by the same as the hamlet". `addr:postcode` is helpful, but in Germany we have postcode boundary objects already, in other countries it's more helpful. 'addr:county`, `addr:state`, `addr:country` are not required, it's implied if the hamlet is inside a county boundaries it belongs to the county.

**Comment by lonvia** [comment]
Fixed by #1836. Note that we haven't reimported the database. That means that a) hamlets and isolated dwellings will only disappear gradually as data in OSM is updated and b) there might be some odd artefacts as we change from old to new computation for small places. There will be a reimport eventually to get to a clean state but at the moment I'd like to see if the change breaks other stuff.
