### ISSUE TITLE
Absent countries after the DB importing

### ISSUE THREAD

**Issue by Weeappy** [osm-search/Nominatim#1846]
Hi everybody,

We want to import all countries with his polygons (without streets and addresses) to use this in our B'n'B web platform.
So, to do this, we have imported the "admin" style into our PostgreSQL database (200+ GB size).
But, after content checking I discovered that many countries are missing in the database, for example : 

- France: all it's OK
- Spain: for this country, we have a definition name in the database, but not his polygons (geometry cell is missing)
- Mexico and other Latin America countries: are completely missing in the database (not event his definition name)

Can you tell me what the problem is? Do I have to upload anything else apart from the table/style "admin"?
Many thanks

**Comment by mtmail** [comment]
New to me, nobody has reported the issue yet.

Input file is a planet.pdf I assume. Can you list which Nominatim, postgresql, postgis version you use? How you run queries, just searching for "France" like `../search.php?q=france&polygon_geojson=1` or via command-line, export.php or direct database access?

**Comment by Weeappy** [comment]
Hi,

Thank you for your reply.

We run queries like this :

France it's OK : http://nominatim.lvpdirect.fr/nominatim/search.php?q=france&polygon_geojson=1&viewbox=
Spain : http://nominatim.lvpdirect.fr/nominatim/search.php?q=spain&polygon_geojson=1&viewbox=
Mexico : http://nominatim.lvpdirect.fr/nominatim/search.php?q=mexique&polygon_geojson=1&viewbox=

_PostgreSQL ver 12.3
Nominatim last update from 2020/06/07_

When you say that input file is **planet.pbf**, I do not understand why, but we only need countries without streets information. Should we really import this very large file planet.pbf ?

We have uploaded only "admin" style section https://prnt.sc/t75fk9 and flatnode.file into database (161 GB)

Thanks

**Comment by mtmail** [comment]
planet.pbf: Just wanted to double-check if you did any processing of the file, e.g. osmconvert, osmfilter, outside Nominatim. You're right with the style set Nominatim (or rather osm2pgsql which Nominatim uses) will filter out non-relevant objects.

**Comment by Weeappy** [comment]
Non, any another processing we use except Nomitaim coordinates.

So do we need to import another PBF file in addition to **"admin"** style to lookup all the countries ?

**Comment by mtmail** [comment]
Ok. You're doing everything right, it should work. Must be something wrong on the Nominatim import side.

**Comment by lonvia** [comment]
I still don't understand what the style has to do with the data file you want to import. Setting the admin style is just a step in configuring your setup. Once this is done you have to [import a file](https://nominatim.org/release-docs/latest/admin/Import-and-Update/#initial-import-of-the-data). @mtmail's question was: what file did you import. Please report the exact command line that you used.

**Comment by mtmail** [comment]
Nominatim 3.5 stable, Postgresql 12, PostGIS 3, osm2pgsql 1.2.0. planet-latest.osm.pbf is https://planet.openstreetmap.org/pbf/planet-200615.osm.pbf (52 GB)


In my `settings/local.php` I added
```
  @define('CONST_Import_Style', '/srv/nominatim/Nominatim/settings/import-admin.style');
```

and ran a full import
```
utils/setup.php --osm-file /tmp/planet-latest.osm.pbf --all --osm2pgsql-cache 32000 --threads 16
```

Number of imported places:
```sql
nominatim3=# select count(*) from placex;
 6770884
```

Running queries the results look alright:
```
./utils/query.php --search mexique --limit 1 | jq -c '.[0] | [.osm_type, .osm_id, .admin_level, .name, .label]'
["R",114686,2,"México","Country"]
./utils/query.php --search spain --limit 1 | jq -c '.[0] | [.osm_type, .osm_id, .admin_level, .name, .label]'
["R",1311341,2,"España","Country"]
./utils/query.php --search france --limit 1 | jq -c '.[0] | [.osm_type, .osm_id, .admin_level, .name, .label]'
["R",2202162,2,"France","Country"]
./utils/query.php --search guatemala --limit 1 | jq -c '.[0] | [.osm_type, .osm_id, .admin_level, .name, .label]'
["R",1521463,2,"Guatemala","Country"
./utils/query.php --search nicaragua --limit 1 | jq -c '.[0] | [.osm_type, .osm_id, .admin_level, .name, .label]'
["R",287666,2,"Nicaragua","Country"]
./utils/query.php --search ecuador --limit 1 | jq -c '.[0] | [.osm_type, .osm_id, .admin_level, .name, .label]'
["R",108089,2,"Ecuador","Country"]
```

(`jq` is https://stedolan.github.io/jq/)

**Comment by mtmail** [comment]
Doing some searches on your website I think you imported Europe only.

**Comment by lonvia** [comment]
No further information provided by reporter. Closing.
