### ISSUE TITLE
Test suite: run one daily update

### ISSUE THREAD

**Issue by mtmail** [osm-search/Nominatim#1853]
https://github.com/osm-search/Nominatim/pull/1852/files added initializing update and look for an update, but since we import http://download.geofabrik.de/europe/monaco-latest.osm.pbf file there'll never be a data update to apply.

Instead we should import an older file than ...-latest.osm.pbf. http://download.geofabrik.de/europe/monaco.html lists older files. It probably needs parsing the HTML for the URL.

**Comment by lonvia** [comment]
The updates run against the global minutely diffs, not against the monaco diffs from geofabrik. If you look at [the travis output](https://travis-ci.org/github/osm-search/Nominatim/jobs/702961720), you'll see that a couple of nodes, ways and relations get imported. Few of them are likely in Monaco but that's fine as the test is more to check that the update scripts itself still runs, not about changing data in the database.

**Comment by mtmail** [comment]
Very nice. Closing.
