### ISSUE TITLE
Wrong post code for Solan Himachal Pradesh, India

### ISSUE THREAD

**Issue by Tom9944** [osm-search/Nominatim#1859]
Listed as 17229, should be 173212

**Comment by mtmail** [comment]
Most 173212 postcodes are indeed near https://nominatim.openstreetmap.org/details.php?osmtype=N&osmid=2360610107&class=place

But some are 25+ kilometers away https://overpass-turbo.eu/s/VDP Nominatim then calculated the center of the postcode somewhere in the middle. Somebody (could be you) would need to check if the postcodes far away are correct. 

OpenStreetMap doesn't have a single list of places to fix, you can leave a note to a local mapper, see https://www.openstreetmap.org/fixthemap
