### ISSUE TITLE
Update stuck on a batch

### ISSUE THREAD

**Issue by RailsGuy** [osm-search/Nominatim#1861]
Hi there I've run into a problem updating (update.php --import-osmosis) which seems to be stuck on a batch. Its been running for 36 hours and previous batches completed in less then an hour. There is an active "COPY place FROM STDIN" but I can't see any blocked pids in postgres. Any ideas whats happened?

This in v3.4.1, postgres 10.12 on ubuntu 18.04

datid |  datname  |  pid  | usesysid |  usename  | application_name | client_addr | client_hostname | client_port |         backend_start         |          xact_start           |          query_start          |state_change                   | wait_event_type |     wait_event      | state  | backend_xid | backend_xmin |  query
 
 16387 | nominatim | 10045 |    16386 | workbooks | osm2pgsql        |             |                 |          -1 | 2020-06-29 21:07:45.041876+00 |                               | 2020-06-29 21:07:56.306444+00 | 2020-06-29 21:07:59.352764+00 | Client          | ClientRead          | idle   |             |              | COPY planet_osm_ways FROM STDIN                                                                                                                                                                   | client backend
 16387 | nominatim | 10046 |    16386 | workbooks | osm2pgsql        |             |                 |          -1 | 2020-06-29 21:07:45.043419+00 |                               | 2020-06-29 21:08:19.161171+00 | 2020-06-29 21:08:19.161218+00 | Client          | ClientRead          | idle   |             |              | PREPARE mark_ways_by_node(int8) AS select id from planet_osm_ways WHERE nodes && ARRAY[$1];                                                                                                      +| client backend
       |           |       |          |           |                  |             |                 |             |                               |                               |                               |                               |                 |                     |        |             |              | PREPARE mark_ways_by_rel(int8) AS select id from planet_osm_ways WHERE id IN (SELECT unnest(parts[way_off+1:rel_off]) FROM planet_osm_rels WHERE id = $1);                                       +|
       |           |       |          |           |                  |             |                 |             |                               |                               |                               |                               |                 |                     |        |             |              |                                                                                                                                                                                                   |
 16387 | nominatim | 10047 |    16386 | workbooks | osm2pgsql        |             |                 |          -1 | 2020-06-29 21:07:45.052873+00 |                               | 2020-06-29 21:08:19.161879+00 | 2020-06-29 21:08:19.163982+00 | Client          | ClientRead          | idle   |             |              | PREPARE get_way (int8) AS SELECT nodes, tags, array_upper(nodes,1) FROM planet_osm_ways WHERE id = $1;                                                                                           +| client backend
       |           |       |          |           |                  |             |                 |             |                               |                               |                               |                               |                 |                     |        |             |              | PREPARE get_way_list (int8[]) AS SELECT id, nodes, tags, array_upper(nodes,1) FROM planet_osm_ways WHERE id = ANY($1::int8[]);                                                                   +|
       |           |       |          |           |                  |             |                 |             |                               |                               |                               |                               |                 |                     |        |             |              |                                                                                                                                                                                                   |
 16387 | nominatim | 10049 |    16386 | workbooks | osm2pgsql        |             |                 |          -1 | 2020-06-29 21:07:45.061677+00 | 2020-06-29 21:07:54.708555+00 | 2020-06-29 21:07:54.708555+00 | 2020-06-29 21:07:54.70857+00  | Client          | ClientRead          | active |             |    352261615 | COPY place FROM STDIN                                                                                                                                                                             | client backend
       |           | 24074 |          |           |                  |             |                 |             | 2020-06-29 18:58:03.545351+00 |                               |                               |                               | Activity        | BgWriterHibernate   |        |             |              |                                                                                                                                                                                                   | background writer
       |           | 24073 |          |           |                  |             |                 |             | 2020-06-29 18:58:03.544877+00 |                               |                               |                               | Activity        | CheckpointerMain    |        |             |              |                                                                                                                                                                                                   | checkpointer
       |           | 24075 |          |           |                  |             |                 |             | 2020-06-29 18:58:03.545958+00 |                               |                               |                               | Activity        | WalWriterMain       |        |             |              |                                                                                                                                                                                                   | walwriter

Currently at sequence 4082776 (26/06/2020 18:54:02) - 1 indexed
/home/workbooks/.local/bin/pyosmium-get-changes --server https://planet.openstreetmap.org/replication/minute -o /srv/nominatim/build/osmosischange.osc -s 30 -I 4082776
/srv/nominatim/build/osm2pgsql/osm2pgsql -klas --number-processes 1 -C 2000 -O gazetteer -S /srv/nominatim/Nominatim-3.4.1/settings/import-full.style -d nominatim -P 5432 --flat-nodes /var/lib/postgresql/Nominatim/flatnode.file /srv/nominatim/build/osmosischange.osc
osm2pgsql version 1.2.0 (64 bit id space)

Allocating memory for dense node cache
Allocating dense node cache in one big chunk
Allocating memory for sparse node cache
Sharing dense sparse
Node-cache: cache=2000MB, maxblocks=32000*65536, allocation method=11
Mid: loading persistent node cache from /var/lib/postgresql/Nominatim/flatnode.file
Mid: pgsql, cache=2000
Parsing gazetteer style file '/srv/nominatim/Nominatim-3.4.1/settings/import-full.style'.
Using projection SRS 4326 (Latlong)

Reading in file: /srv/nominatim/build/osmosischange.osc
Using XML parser.
^MProcessing: Node(130k 130.0k/s) Way(0k 0.00k/s) Relation(0 0.00/s)^MProcessing: Node(253k 253.8k/s) Way(1k 1.00k/s) Relation(0 0.00/s)^MProcessing: Node(253k 253.8k/s) Way(5k 2.50k/s) Relation(0 0.00/s)^MProcessing: Node(253k 253.8k/s) Way(10k 3.33k/s) Relation(0 0.00/s)^MProcessing: Node(253k 253.8k/s) Way(15k 3.75k/s) Relation(0 0.00/s)^MProcessing: Node(253k 253.8k/s) Way(22k 4.40k/s) Relation(0 0.00/s)^MProcessing: Node(253k 253.8k/s) Way(27k 4.50k/s) Relation(0 0.00/s)^MProcessing: Node(253k 253.8k/s) Way(33k 4.71k/s) Relation(0 0.00/s)^MProcessing: Node(253k 253.8k/s) Way(37k 4.62k/s) Relation(0 0.00/s)^MProcessing: Node(253k 253.8k/s) Way(40k 3.13k/s) Relation(10 10.00/s)^MProcessing: Node(253k 253.8k/s) Way(40k 3.13k/s) Relation(50 50.00/s)^MProcessing: Node(253k 253.8k/s) Way(40k 3.13k/s) Relation(190 95.00/s)^MProcessing: Node(253k 253.8k/s) Way(40k 3.13k/s) Relation(310 15.50/s)

  PID USER      PR  NI    VIRT    RES    SHR S  %CPU %MEM     TIME+ COMMAND
10043 workboo+  20   0 59.933g 915204 764768 R  99.7  0.8   2345:49 osm2pgsql

**Comment by mtmail** [comment]
There was a huge complex OSM data object that tools couldn't handle. osm2pgsql 1.2.2 fixes this

https://lists.openstreetmap.org/pipermail/dev/2020-June/030956.html

**Comment by lonvia** [comment]
The newest 3.5.1 release solves this problem. We don't provide bug fix releases for older versions of Nominatim. However, if updating to the latest Nominatim 3.5.1 is not an option, you can patch your version manually:

Download and unpack [latest libosmium](https://github.com/osmcode/libosmium/releases/tag/v2.15.6). Then change into your Nominatim build directory and run:

```
cmake -DEXTERNAL_LIBOSMIUM=ON -DOSMIUM_INCLUDE_DIR=<path to libosmium 2.15.6>/include <Nominatim source directory>
make
```

**Comment by RailsGuy** [comment]
I updated to osm2pgsql 1.2.2 and all is good thank you.
