### ISSUE TITLE
mentioning city causes Nominatim to ignore housenumber and geolocate bus stop instead of address (in simple search where queried street name is shortened)

### ISSUE THREAD

**Issue by matkoniecz** [osm-search/Nominatim#1871]
`Stachiewicza 33` with Kraków specified as city using structured search works https://nominatim.openstreetmap.org/search.php?street=Stachiewicza+33&city=Krak%C3%B3w&county=&state=&country=&postalcode=&polygon_geojson=1&viewbox=

`Stachiewicza 33, Kraków` fails https://nominatim.openstreetmap.org/search.php?q=Stachiewicza+33%2C+Krak%C3%B3w&polygon_geojson=1&viewbox=

------

`Bema 66, Toruń` fails https://nominatim.openstreetmap.org/search.php?q=Bema+66%2C+Toru%C5%84&polygon_geojson=1&viewbox=

`Bema 66` `Toruń` works https://nominatim.openstreetmap.org/search.php?street=Bema+66&city=Toru%C5%84&county=&state=&country=&postalcode=&polygon_geojson=1&viewbox=

**Comment by lonvia** [comment]
This is now working. I suspect that #2369 did the trick.
