### ISSUE TITLE
"Maison Folie de Lambersart" doesn't return "Maison Folie de Lambersart : Le Colysée"

### ISSUE THREAD

**Issue by napnapnapnap** [osm-search/Nominatim#1875]
Searching for "Maison Folie de Lambersart" returns [no results](https://nominatim.openstreetmap.org/search.php?q=Maison+Folie+de+Lambersart&polygon_geojson=1&viewbox=).

Searching "Maison Folie de Lambersart : Le Colysée" returns [the correct object](https://nominatim.openstreetmap.org/search.php?q=Maison+Folie+de+Lambersart+%3A+Le+Colys%C3%A9e&polygon_geojson=1&viewbox=).

See https://github.com/osm-search/Nominatim/issues/94 .

**Comment by mtmail** [comment]
Yes, it's the same issue as https://github.com/osm-search/Nominatim/issues/94 Still open.

For this place specifically you could add an `alt_name` or `short_name` tag since I think an average user would refer to the place in the short form, not long form.
