### ISSUE TITLE
perfectly fine address not found at all

### ISSUE THREAD

**Issue by matkoniecz** [osm-search/Nominatim#1876]
https://www.openstreetmap.org/way/184611515 

`addr:housenumber = 7` `addr:street=Osiedle Wysokie`

Searching Osiedle Wysokie 7 finds something else - see https://nominatim.openstreetmap.org/search.php?q=Osiedle+Wysokie+7%2C+31-819+Krak%C3%B3w&polygon_geojson=1&viewbox=20.00916%2C50.08963%2C20.01678%2C50.08791 https://nominatim.openstreetmap.org/search.php?q=Osiedle+Wysokie+7%2C+Krak%C3%B3w&polygon_geojson=1&viewbox= ( https://nominatim.openstreetmap.org/details.php?osmtype=W&osmid=54965759&class=landuse )

I asked PL community: https://www.openstreetmap.org/note/2260611 https://forum.openstreetmap.org/viewtopic.php?pid=794068#p794068

**Comment by lonvia** [comment]
`Osiedle Wysokie` is not a street. Use `addr:place=Osiedle Wysokie` on the building way instead.

**Comment by matkoniecz** [comment]
Thank you for diagnosing this data issue! It makes perfect sense.
