### ISSUE TITLE
not found address

### ISSUE THREAD

**Issue by Rathch** [osm-search/Nominatim#1878]
50923 Köln
is not found but it's the address of the university of Cologne.

**Comment by mtmail** [comment]
I'm familiar with the city, it sees easy to add the missing data.

University buildings stretch part of the city and I think some buildings have 50931, but you're right the main website and all faculty websites have 50923. I added that to the OpenStreetMap data and it should be found in 24-48 hours.

**Comment by lonvia** [comment]
This would be a company postcode (Grossempfängerpostleitzahl), I presume? I'm not sure if those should be mapped at all given that they have no geographic relation and if so, 'contact:*' would be more appropriate.

Relevant discussion: https://forum.openstreetmap.org/viewtopic.php?id=60421&p=2
