### ISSUE TITLE
Postcode calculated wrong / different on 2 nearby objects

### ISSUE THREAD

**Issue by geoneutrino** [osm-search/Nominatim#1879]
Searching
https://nominatim.openstreetmap.org/search.php?q=Memprechtshofen+Maierhof&polygon_geojson=1&viewbox=
gives a street and a place node directly beside the street, both with name "Maierhof"

While the street has the correct zip code 77866 the place has the wrong code 77839 of the neighbor area
The zip code area of 77866 itself is correctly mapped and covers the place location
https://nominatim.openstreetmap.org/details.php?osmtype=R&osmid=3358135&class=place
(neighbor postcode area is also mapped correctly and doesn't overlap the place)

Thanks

**Comment by lonvia** [comment]
ZIP codes for place nodes are tricky because it is never clear if the code really covers the entire place or just a part. We probably should simply not be showing them at all.

**Comment by lonvia** [comment]
Got fixed as part of #1982.
