### ISSUE TITLE
Copying data from server to server

### ISSUE THREAD

**Issue by snoopy72** [osm-search/Nominatim#1880]
Hello,

i am using my server in the basement for converting the pdf into the database; more power, more ram etc.

but finally the service should run on my own webserver.
the converting process will not run on the webserver - and should not run there, because its performace is used by webusers.

how can i copy the data from the basement server onto my webserver ?

OS ist exactly the same.

Thanks !

**Comment by lonvia** [comment]
The most easy way to do this is to dump the database with `pg_dump` and restore it on the other machine with `pg_restore`. You don't need to dump the entire database but only the tables that are really needed for the API. If you don't plan to run updates on your import machine, then you can simply run `./utils/setup.php --drop` and Nominatim will delete all unnecessary tables. You can then dump the entire database. If you want to run updates on the database and just dump the current state to your production machine from time to time, you need to select the relevant tables using the `-t` option of pg_dump. Have a look at the list of [tables that drop keeps](https://github.com/osm-search/Nominatim/blob/master/lib/setup/SetupClass.php#L658). This gives you a good idea what needs to be copied over.

**Comment by snoopy72** [comment]
Thank you very much for this helpful answer.
I'll try it as soon as the setup script has finished.
