### ISSUE TITLE
Running Ranking process in parallel

### ISSUE THREAD

**Issue by ajinra020307** [osm-search/Nominatim#1881]
We had run nominatim with planet pbf with a 64 gb ram debian system. It has been running more than 4 days. It seems to be the ranking process is taking a lot of time going forward. Is there any way we can run the ranking process in multiple cpus parallely. If Yes how can we do it

Thank You

**Comment by lonvia** [comment]
You can force parallel processing with the `--threads` parameter although normally Nominatim should automatically choose one that is good for your system (available CPUs - 1).
