### ISSUE TITLE
Explain how to import for remote server

### ISSUE THREAD

**Issue by tuananh1998hust** [osm-search/Nominatim#1882]
when i try import data to remote server, i have a response error "CREATE FUNCTION nominatim_test_import_func(text) RETURNS text AS '/app/src/build/module/nominatim.so', 'transliteration' LANGUAGE c IMMUTABLE STRICT;DROP FUNCTION nominatim_test_import_func(text);PHP Fatal error:  Uncaught Nominatim\DatabaseError: [500]: Database server failed to load /app/src/build/module/nominatim.so module"

**Comment by lonvia** [comment]
You need to copy `build/module/nominatim.so` to the remote server. Then add `@define('CONST_Database_Module_Path', '<path on the remote server where nominatim.so is located>');` to your `settings/local.php`.

I thought we had documented this by now but apparently not.
