### ISSUE TITLE
Some islands in Sapodilla Cayes listed in wrong country

### ISSUE THREAD

**Issue by kaldari** [osm-search/Nominatim#1883]
The Sapodilla Cayes are an atoll that is part of Toledo District, Belize, and if you search OpenStreetMap for "Sapodilla Cayes", it correctly reports it as "Sapodilla Cayes, Toledo District, Toledo, Belize". Strangely, though, if you search for the member islands of the Sapodilla Cayes, some are reported as being in Guatemala instead of Belize:
- Lime/Low Caye, Puerto Barrios, Guatemala
- Ragged Caye, Puerto Barrios, Guatemala
- Hunting Caye, Guatemala
- Nicholas Caye, Guatemala
- Frank's Caye, Toledo District, Belize
- Northeast Sapodilla Caye, Toledo District, Belize
- Tom Owen's Caye, Toledo District, Belize
- Seal Caye, Toledo District, Belize

**Comment by lonvia** [comment]
The archipelago is currently not mapped as part of [Toledo](https://www.openstreetmap.org/relation/962358). In fact, it is not mapped as being part of any country as far as I can see. Consequently, Nominatim's choice of country parenting is a bit random.

You should extend the boundary relations of Belize and Toledo to include the archipelago and things will sort themselves out automatically with Nominatim.

**Comment by kaldari** [comment]
@lonvia - Thanks! I'll try that!
