### ISSUE TITLE
Recompute Importance using Wikidata

### ISSUE THREAD

**Issue by srik506** [osm-search/Nominatim#1885]
While searching for places like 'Boston', 'Cleveland' etc the top results were not too satisfactory. So I followed along the below section i.e. Importing Section from Administration Guide:

**Downloading additional data**
Wikipedia/Wikidata rankings:
_./utils/setup.php --import-wikipedia-articles
./utils/update.php --recompute-importance_

**After these steps, when I checked the DB, I do see the updates:**
select count(*) from wikipedia_article

9936394

But when I try to query for the same places, there is no change in the Importance values:

0.55	Cleveland County, Arkansas, United States of America
0.45999999999999996	Cleveland, Russell County, Virginia, United States of America
0.45999999999999996	Cleveland, Manitowoc County, Wisconsin, United States of America
0.45999999999999996	Cleveland, Bradley County, Tennessee, United States of America
0.45999999999999996	Cleveland, Emery County, Utah, United States of America

I am missing some step?

**Comment by lonvia** [comment]
The steps look about right.

Is it possible that you have the wikidata information missing in the extratags? Please check out the details page on your server, e.g. `/details.php?osmtype=R&osmid=1822199&class=boundary` for Cleveland County. In the extratags row you should have `wikidata` or `wikipedia` just as on the [OSM server details page](https://nominatim.openstreetmap.org/details.php?osmtype=R&osmid=1822199&class=boundary). If you have neither, then the essential information for matching up the importance values is missing.

**Comment by srik506** [comment]
Hmm yes I am not able to see the wikidata and wikipedia in the details page. Would that be because I added the Wiki part post Import?

**Comment by lonvia** [comment]
No, it depends on the import style you are using. I see that the simpler styles `import-address.style`, `import-admin.style`, `import-street.style` all skip over the wiki* tags. That's an unfortunate oversight. I will fix the styles immediately. For you it means unfortunately that you have to reimport the database. There is no way to add these tags to an existing database.

**Comment by lonvia** [comment]
As per PR #1890, you can simply add the missing lines:

```
{   "keys" : ["wikipedia", "wikipedia:*", "wikidata"],
    "values" : {
        "" : "extra"
    }
},
```

to the style that you are using and then reimport the database.
