### ISSUE TITLE
delete the name of a province in Iran in the address - recently

### ISSUE THREAD

**Issue by AminZare** [osm-search/Nominatim#1887]
Hello.
Recently, the name of a province was removed from the output. Is there a specific reason?
The capital of Iran is located in this province, is it possible that its type has changed from province to something else?
Sample link:
https://nominatim.openstreetmap.org/lookup?format=json&osm_ids=N2326794015
In the address section, there should be a province with the name of Tehran.

```
address |  
town | "دماوند"
municipality | "تاررود"
district | "بخش مرکزی شهرستان دماوند"
county | "شهرستان دماوند"
country | "ایران"
country_code | "ir"
```

**Comment by AminZare** [comment]
I checked that the province relation exists in osm but not in nominatim.
https://nominatim.openstreetmap.org/lookup?format=json&osm_ids=R537701
https://www.openstreetmap.org/relation/537701

**Comment by mtmail** [comment]
Thanks for the links. So an admin_level=2 (address rank 4) is missing in the address hierarchy https://nominatim.openstreetmap.org/details.php?osmtype=N&osmid=2326794015

It could be related to https://www.openstreetmap.org/changeset/87781892 and probably requires nominatim.openstreetmap.org to reindex the region.

**Comment by lonvia** [comment]
The geometry of the relation is clearly broken in multiple places. Please fix the relation and things should sort themselves out automatically with Nominatim.

**Comment by mtmail** [comment]
Might be related to https://www.openstreetmap.org/changeset/88207285 (comment translated: "help to improve the map") which deleted several admin_level=6 and 7 boundary sections (ways). I still see them rendered in zoom level 11, but when I zoom in closer. It's a data issue, from the Nominatim search engine logic we can't do much.
