### ISSUE TITLE
States are missing in the address section

### ISSUE THREAD

**Issue by rcarroll0452** [osm-search/Nominatim#1888]
A fewer searches on Nominatim for cities that also act as a state returns no state element in the address section of the response:

1. [Ho Chi Minh](https://nominatim.openstreetmap.org/search.php?q=Ho%20Chi%20Minh&format=json&addressdetails=1)
2. [Tehran](https://nominatim.openstreetmap.org/search.php?q=Tehran&format=json&addressdetails=1) (This maybe related to #1887)
3. [Kuala Lumpur](https://nominatim.openstreetmap.org/search.php?q=Kuala%20Lumpur&format=json&addressdetails=1)
4. Searching for [Brunei-Muara District](https://nominatim.openstreetmap.org/search.php?format=json&q=Brunei-Muara%20District,%20BE1318,%20Brunei%20Darussalam&addressdetails=1) gives it as state, while searching for a PoI data like [this](https://nominatim.openstreetmap.org/search.php?format=json&q=Cengkih,%20Simpang%20181,%20Kiarong,%20Mukim%20Gadong%20B,%20Brunei-Muara%20District,%20BE1318,%20Brunei%20Darussalam&accept-language=en&addressdetails=1) within that district returns `Brunei-Muara District` as district in the address section of the response

**Comment by lonvia** [comment]
That's intentional. There is no 'state' for these cities. OSM reflects that by mapping exactly one boundary relation. And as a consequence Nominatim returns exactly one administrative entity. I really don't like the idea of adding phantom address parts just so all boxes in the address field are filled.

**Comment by rocainunwired** [comment]
The earlier versions of the API returned it and now it doesn't and I just wondered why.
Thank you for the clarification

**Comment by lonvia** [comment]
Closing as 'won't fix'.
