### ISSUE TITLE
Hierarchy in Mexico City wrong

### ISSUE THREAD

**Issue by rcarroll0452** [osm-search/Nominatim#1889]
Searching for [Mexico City](https://nominatim.openstreetmap.org/search.php?q=Mexico%20City&format=json&addressdetails=1) with `addressdetails=1` returns `city` at first position and `neighbourhood` at the 2nd position in the address section of the response. 

Position might not matter, but opening an issue to see if this effect is due to some other bug/feature

**Comment by lonvia** [comment]
That's because the neighbourhood has been mapped as `admin_level=6` which is usually county level and thus creates a bit of a mess. I need to check out how the rest of Mexico is mapped before that can be fixed.

**Comment by lonvia** [comment]
Turns out that Mexico City was just missing the link between its place node and the administrative boundary. A simple update in the database fixed it.
