### ISSUE TITLE
Expand standard shortcuts in Polish

### ISSUE THREAD

**Issue by matkoniecz** [osm-search/Nominatim#1896]
Currently Nominatim fails for `rotm. Witolda Pileckiego, Bydgoszcz` while its obvious expansion `rotmistrza Witolda Pileckiego, Bydgoszcz` works

https://nominatim.openstreetmap.org/search.php?q=rotm.+Witolda+Pileckiego%2C+Bydgoszcz&polygon_geojson=1&viewbox=
https://nominatim.openstreetmap.org/search.php?q=rotmistrza+Witolda+Pileckiego%2C+Bydgoszcz&polygon_geojson=1&viewbox=

I am right now working on geocoding project and as side effect I would be able to provide decent coverage of such expansions for Polish street names.

Sadly, I am unable to promise that I can implement shortcut expansion, but if it is implemented I would gladly make PR with better config files for Polish names.

**Comment by egils-consulting** [comment]
I would gladly contribute config files for Danish and Swedish.

**Comment by matkoniecz** [comment]
I found https://wiki.openstreetmap.org/wiki/Name_finder:Abbreviations

Not sure is it collecting what Nominatim actually needs, but I added there what I encountered so far in my data processing.

**Comment by lonvia** [comment]
Yes, this is the right place for collecting abbreviations. I have no ETA yet when they will get integrated because #1208 needs to be solved first. When it gets tackled then the wiki table surely will be used as a base. So your work on that wiki page is much appreciated.

Closing here in favour of @1208.

**Comment by matkoniecz** [comment]
> Yes, this is the right place for collecting abbreviations.

Thanks for info, I was a bit confused about purpose and status of that page. I edited wiki to mention this in  https://wiki.openstreetmap.org/w/index.php?title=Name_finder:Abbreviations&diff=2026053&oldid=2025315

**Comment by Reynal01051991** [comment]
> > Yes, this is the right place for collecting abbreviations.
> 
> Thanks for info, I was a bit confused about purpose and status of that page. I edited wiki to mention this in  https://wiki.openstreetmap.org/w/index.php?title=Name_finder:Abbreviations&diff=2026053&oldid=2025315


[]()[]()
