### ISSUE TITLE
How to Handle Building on private areas without "properly" named streets

### ISSUE THREAD

**Issue by Simon0Harms** [osm-search/Nominatim#1897]
On some private areas, the streets aren't important and only the names of the buildings are used.
It would be great if you could "tell" this nominatin and it would use
building name, private area name, ...

For example:
https://www.openstreetmap.org/search?query=Fahrbereitschaft%20ptb#map=19/52.29484/10.46515
`Fahrbereitschaft, Parkstreifen vor Hertz-Bau, Kanzlerfeld, Lehndorf-Watenbüttel, Braunschweig, Niedersachsen, 38116, Germany`
In my opinion better would be:
`Fahrbereitschaft, PTB, Kanzlerfeld, Lehndorf-Watenbüttel, Braunschweig, Niedersachsen, 38116, Germany`
This was discussed here (german):
https://forum.openstreetmap.org/viewtopic.php?id=70107

Another example:
https://www.openstreetmap.org/search?query=Audi%20Wolfsburg#map=19/52.43311/10.79258
`Audi, Parkstraße, Wolfsburg, Niedersachsen, 38440, Germany`
In my opinion better would be:
`Audi, Autostadt, Wolfsburg, Niedersachsen, 38440, Germany`

**Comment by lonvia** [comment]
Nominatim does handle named landuse=residential/commercial/industrial/retail as address parts. That means you can use them in connection with 'addr:place'. So add a landuse tag to the PTB and Autostadt and they will show up in the address.
