### ISSUE TITLE
When looking up address parents of long road, skip nodes only touching a border

### ISSUE THREAD

**Issue by mtmail** [osm-search/Nominatim#1900]
Battle Creek Road (https://nominatim.openstreetmap.org/details.php?osmtype=W&osmid=10729997) is in Pennsylvania.

The most northern node touches the state border of New York (north) and Pennsylvania (south). During address parent lookups that node is used and `state=New York` (also admin_level 7=Nicols Town, county=Tiago County) is chosen.

It would be better if we can recognize the node only touches the border and re-check on which side of the border the address should be.

For the city (`city=Rome`) though the southern most node is used and that is correctly in Pennsylvania. Address for Rome itself also looks good https://nominatim.openstreetmap.org/details.php?osmtype=R&osmid=188544&class=boundary

**Comment by lonvia** [comment]
I can confirm that #1902 fixes the example on the OSM servers.

**Comment by mtmail** [comment]
Thank you very much. https://en.wikipedia.org/wiki/DE-9IM gives me headaches, but will study more closely.
