### ISSUE TITLE
Missing city in address hierarchy for places in Indonesia

### ISSUE THREAD

**Issue by arvindkartik** [osm-search/Nominatim#1904]
Hello,

I recently completed a full planet importing using v3.5.1 and I found that few addresses in Indonesia are missing out on the city info in the address details.
For example:
**Kalijudan, Indonesia**

The response I got in my local import: ```"display_name": "Kalijudan, East Java, Indonesia"```
On checking for the address ranks:
Address Rank of Kalijudan: 20
Address Rank of Mulyorejo: 18
Address Rank of Surabaya : 16
Address Rank of East Java:  8

However, nominatim.openstreetmap.org seems to give the correct response which is: ```"display_name": "Kalijudan, Mulyorejo, Surabaya, East Java, 60114, Indonesia"```
https://nominatim.openstreetmap.org/search.php?q=Kalijudan,%20Indonesia&format=json&addressdetails=1
On checking for the address ranks:
Address Rank of Kalijudan: 14
Address Rank of Mulyorejo: 12
Address Rank of Surabaya : 10
Address Rank of East Java:  8

Another example:
**Keputih, Indonesia**
The response I got in my local import: ```"display_name": "Keputih, Sukolilo, East Java, 60111, Indonesia"```
On checking for the address ranks:
Address Rank of Keputih	: 14
Address Rank of Sukolilo: 12 
Address Rank of Surabaya : 16 (maybe this is why it is not considered as an element in the address hierarchy?)
Address Rank of East Java:  8

While nominatim.openstreetmap.org seems to give the correct response which is: ```"display_name": "Keputih, Sukolilo, Surabaya, East Java, 60111, Indonesia"```
https://nominatim.openstreetmap.org/search.php?q=Keputih,%20Indonesia&format=json&addressdetails=1
On checking for the address ranks:
Address Rank of Kalijudan: 14
Address Rank of Mulyorejo: 12
Address Rank of Surabaya : 10
Address Rank of East Java:  8

I was hoping PR #1894 should fix it, so I did a reimport again with master branch. But the issue still exists

**Comment by lonvia** [comment]
It looks like all the admin_levels in Indonesia are shifted, so we need localized levels. I need to look through the data how to do that in detail.

**Comment by lonvia** [comment]
#1919 fixes the issue of the disappearing admin levels. The default rank assignments are still not ideal for Indonesia. Leaving this issue open for a bit because of that.

**Comment by lonvia** [comment]
The fix in #1982 mostly works without a reimport. Just reloading the SQL with `./utils/setup.php --create-functions --enable-diff-updates --create-partition-functions` will do.
