### ISSUE TITLE
Wrong result for Decatur, Georgia

### ISSUE THREAD

**Issue by zampetti** [osm-search/Nominatim#1906]
Submitting the following query yields a city in Alabama
https://nominatim.openstreetmap.org/ui/search.html?city=Decatur&format=geojson&polygon_geojson=1&state=Georgia

The second result is correct, but there is no way that I can see to distinguish the two.

**Comment by lonvia** [comment]
The administrative boundary got for some reason linked against the wrong place node and then took over the address of that node. The linking is really odd and I suspect the fallout of a bug fixed long ago. Reindexing has removed the glitch and it looks like it never appeared on the second server. So closing as strange outlier.
