### ISSUE TITLE
Getting `column "diamaeter" does not exist` when importing

### ISSUE THREAD

**Issue by nspaeth** [osm-search/Nominatim#1907]
While attempting to import a region into a fresh database I am getting this error:

```
WARNING: Starting rank 11
DEBUG: Total number of rows: 0
WARNING: Done 0/0 in 0 @ 0.000 per second - FINISHED rank 11

WARNING: Starting rank 12
DEBUG: Total number of rows: 6
DEBUG: Processing places: [101742]
DEBUG: Processing places: [101878]
DEBUG: Processing places: [159073]
DEBUG: Processing places: [177528]
DEBUG: Processing places: [101885]
DEBUG: Processing places: [140540]
Traceback (most recent call last):
  File "/app/src/nominatim/nominatim.py", line 326, in <module>
    Indexer(options).run()
  File "/app/src/nominatim/nominatim.py", line 201, in run
    self.index(RankRunner(rank))
  File "/app/src/nominatim/nominatim.py", line 235, in index
    thread = next(next_thread)
  File "/app/src/nominatim/nominatim.py", line 256, in find_free_thread
    if thread.is_done():
  File "/app/src/nominatim/nominatim.py", line 169, in is_done
    if self.conn.poll() == psycopg2.extensions.POLL_OK:
psycopg2.errors.UndefinedColumn: column "diameter" does not exist
LINE 1: SELECT diameter
               ^
QUERY:  SELECT diameter
CONTEXT:  PL/pgSQL function add_location(bigint,character varying,integer,integer[],integer,integer,text,geometry) line 26 at RAISE
PL/pgSQL function placex_update() line 341 at assignment

ERROR: error status 1 running nominatim!
string(33) "error status 1 running nominatim!"

real	48m37.901s
user	0m1.167s
sys	0m0.657s
```

After searching through the sources and sql, I am not sure where the `diameter` column is supposed to be created, only updated. If someone can point me to where that should happen I might be able to investigate further on my own.

I am using this command to import:
```
./src/build/utils/setup.php \
		-v \
		--osm2pgsql-cache 512 \
		 --osm-file $OSMFILE \
		 --threads $THREADS \
		 --setup-db \
		 --import-data \
		 --create-functions \
		 --create-tables \
		 --create-partition-tables \
		 --create-partition-functions \
		 --no-partitions \
		 --enable-debug-statements \
		 --import-wikipedia-articles \
		 --load-data \
		 --index \
		 --create-search-indices \
		 --calculate-postcodes \
		 --osmosis-init \
     --enable-diff-updates \
		 --create-country-names \
&& ./src/build/utils/check_import_finished.php
```

I specifically am not using `all` because the database is pre-created and setup fails when trying to create it.

Other possibly useful info:
I'm not sure if these are important or not, but while running I get numerous warnings that look like: `NOTICE:  table "placex" does not exist, skipping` for various tables, but when I look at the database afterward those tables do end up existing.

I also get:
`NOTICE:  PostGIS: Unable to compute statistics for "placex.centroid": No non-null/empty features` more than once.

This is being run on the current master branch.
`PostgreSQL 12.2 (Debian 12.2-2.pgdg100+1) on x86_64-pc-linux-gnu, compiled by gcc (Debian 8.3.0-6) 8.3.0, 64-bit`
`"POSTGIS="3.0.0 r17983" [EXTENSION] PGSQL="120" GEOS="3.7.1-CAPI-1.11.1 27a5e771" PROJ="Rel. 5.2.0, September 15th, 2018" GDAL="GDAL 2.4.0, released 2018/12/14" LIBXML="2.9.4" LIBJSON="0.12.1" LIBPROTOBUF="1.3.1" WAGYU="0.4.3 (Internal)" TOPOLOGY RASTER"`

**Comment by lonvia** [comment]
There is an outdated debug statement in the code. Run without `--enable-debug-statements` and you'll be fine. Further: you must run the initial import without `--enable-diff-updates` and should run it in without `-no-partitions`.

Please have a look at `utils/setup.php` and check there which commands are usually run when using `--all`.

**Comment by nspaeth** [comment]
Thank you, this helped.
I thought I had read that using `--no-partitions` would improve the speed of importing smaller regions, but I can't find that documentation now, so I may have made it up.
