### ISSUE TITLE
Question about 'class' column and the need for (osm_id, osm_type, class) for uniqueness

### ISSUE THREAD

**Issue by nspaeth** [osm-search/Nominatim#1908]
Knowing that there is no permanent id for places, I was looking to have a relatively stable identifier to reference in my own database.

Before realizing that 'class' is required for uniquness I considered adding something like:
```
ADD COLUMN placeid text GENERATED ALWAYS AS ((osm_type||osm_id::varchar(15))) STORED UNIQUE;
CREATE INDEX generatedPlaceId ON placex USING placeid;
```
In order to generate a column that looks like 'N12343643'.

It seems like I'll need to figure out a different solution, but I am interested in knowing why 'class' is needed in the first place. 

For example, could `class->type` have been stored in a `JSONB` or `hstore` column, eliminating the need for duplicated rows? I don't know what the performance implications would be of this alternative, but I also am not sure how these duplicated rows affect performance, database size, or import time. 

My uninformed hope: maybe the performance tradeoffs would balance out while removing the 'class' column from the uniqueness criteria?

Any enlightenment would be helpful!

**Comment by lonvia** [comment]
The class type has an influence on other properties of the place, most notably `rank_search` and `rank_address`. These properties in turn have an influence on search prominence and how addresses of related objects are formed. 

It would probably be possible to compute "merged ranks". It just creates a lot of corner cases that are easily overlooked. Having different classes in different rows makes handling a lot easier.

You can just add class into your id string and then you do have a unique ID. The number of values that `class` can have is very limited (defined in your `CONST_Import_Style` style file). So you could even shorten it. In the end it all depends what you need the ID for.

**Comment by nspaeth** [comment]
Thanks for the info.

Is there any documentation on how all of the ranking and indexing steps are meant to work? I know the sources are available, but that can be difficult to interpret when trying to filter out implementation details.

**Comment by lonvia** [comment]
Only what you can find in the developer's section in the documentation.
