### ISSUE TITLE
Wrong parsing of Wikidata fields

### ISSUE THREAD

**Issue by summer-son** [osm-search/Nominatim#1911]
In Munich city districts are tagged to Wikidata.
In Wikidata, the name fields are correct. There is an [official number of town quarter](https://www.wikidata.org/wiki/Property:P5901) field that is, for some reason, added in front of the district name. This shouldn't be done.

Example:
Query https://nominatim.openstreetmap.org/reverse?format=xml&lat=48.1617&lon=11.5535&zoom=18&addressdetails=1
Returns `<city_district>Stadtbezirk 04 Schwabing-West</city_district>`
The district data was pulled from https://www.wikidata.org/wiki/Q252910
and had to include only name _Schwabing-West_ and not the _Stadtbezirk 04_ before the name.

**Comment by lonvia** [comment]
The data for Nominatim comes from OpenStreetMap, not Wikidata. The relation for the Stadtbezirk has indeed the name you see: https://www.openstreetmap.org/relation/56389 This needs to be fixed in OpenStreetMap.

**Comment by lonvia** [comment]
Asked the locals about the tagging in https://forum.openstreetmap.org/viewtopic.php?pid=797475
