### ISSUE TITLE
Does Nominatim not yet support the right-click context menu seen at openstreetmap.org?

### ISSUE THREAD

**Issue by jwest75674** [osm-search/Nominatim#1915]
I am new to Nominatim, and Open Street Maps, but have my first instance running!

I noticed that some functionality, like the right click context menu, and the right side floating menu are missing in Nominatim when comparing to https://www.openstreetmap.org/.

I am currently unsure if this is a bug on my end, or if it's functionality which just doesn't exist in Nominatim at this time. If not, it may be within my skill set to try to tackle, but I am keen to understand the current situation first!

**Comment by lonvia** [comment]
openstreetmap.org is a different website. It is only natural that it has a completely different set of functionalities. The web frontend for Nominatim is for debugging purposes only, it is not meant to be a fully featured end-user website. I don't really see the need for right-click context menus in that context.

**Comment by jwest75674** [comment]
Fair enough! I don't disagree, the API is the truly important functionality. Thank you
