### ISSUE TITLE
PHP Parse error:  syntax error, unexpected '?' in /srv/nominatim/Nominatim-3.5.1/lib/DB.php on line 410

### ISSUE THREAD

**Issue by faqihgithub** [osm-search/Nominatim#1925]

**Comment by mtmail** [comment]
Please post the relevant lines of the files you have on your disk. Which version of PHP are you running?

**Comment by faqihgithub** [comment]
PHP 5.4.16 (cli) (built: Apr  1 2020 04:07:17)
Copyright (c) 1997-2013 The PHP Group
Zend Engine v2.4.0, Copyright (c) 1998-2013 Zend Technologies

using default .db file from Nominatim-3.5.1

**Comment by mtmail** [comment]
Nominatim 3.5.1 requires at least PHP 7 http://nominatim.org/release-docs/3.5.1/admin/Installation/#software

I think we might be able to add a check during the build (make) step of the installation. But to solve the PHP syntax error you need to upgrade PHP to at least version 7.
