### ISSUE TITLE
Getting different result for same coordinate

### ISSUE THREAD

**Issue by umerfaruque** [osm-search/Nominatim#1927]
https://nominatim.openstreetmap.org/reverse?format=geojson&lat=28.30788&lon=76.88272666666666&zoom=18&addressdetails=1    
Result - "Bilaspur Khurd, Gurugram, Manesar, Haryana, 122413, India"

http://localhost/nominatim/reverse?format=geojson&lat=28.30788&lon=76.88272666666666&zoom=18&addressdetails=1
Result - "Gurugram, Manesar, Haryana, 122413, India"

What is the issue??

**Comment by mtmail** [comment]
The red dot is the search coordinates, the blue dot in the response. I would say "Bilaspur Khurd" is not very relevant to the query and fine if it's missing. Most likely your database index is newer and nominatim.openstreetmap.org would have the same result if it reimported/reindexed that area.

![image](https://user-images.githubusercontent.com/3727288/90805145-8993ac00-e31b-11ea-9538-92f43e6fe25c.png)

**Comment by lonvia** [comment]
@mtmail  is right. This is a result of reducing the influence of place nodes. The result from the local installation is considered more correct these days.
