### ISSUE TITLE
Rebuild pincodes/postal codes in database

### ISSUE THREAD

**Issue by ajaybhargav** [osm-search/Nominatim#1929]
My nominatim installation is giving wrong postal codes. On my server I am getting address as:

> I B Patel Road, Yashodham, P/S Ward, Zone 4, Mumbai, Mumbai Suburban, Maharashtra, 400093, India

where as https://nominatim.openstreetmap.org gives:

> I B Patel Road, Yashodham, P/S Ward, Zone 4, Mumbai, Mumbai Suburban, Maharashtra, 400062, India

This is true for many tests that I have done. is there a way to dump and rebuild postal code database again? Please suggest.
Thanks in advance.

**Comment by lonvia** [comment]
Two disclaimers:

1) Please do not expect your own database to give you exactly the same results as the instance on nominatim.openstreetmap.org. It has OSM data from a different point in time and created with a different version of your software. Even if you rebuild your database, you will get different results.

2) Do not expect postcode data to be correct. The postcode coverage in OSM is patchy at best and the assignment of postcodes is fuzzy and error prone.

That said, you can rebuild the postcode tables with `./utils/update.php --calculate-postcodes`. However, this will not change the postcode assignments in the placex table, i.e. you still get the same results until an entry is updated. Simply put: a full postcode update is only possible via a full reimport.

**Comment by ajaybhargav** [comment]
I guessed that ah..! 😄 Thanks for response.
I don't know why but looks like my server got banned by geofabrik server. I am getting connection refused while download pbf file.
I am running updates using supervisorctl using following command

> command=/home/nominatim/Nominatim/build/utils/update.php --import-osmosis-all

Do you think that's the problem?
PS: You can close the thread if you feel its off-topic. Thanks! 🙏

**Comment by mtmail** [comment]
@ajaybhargav Several geofabrik employees are active on https://help.openstreetmap.org/tags/geofabrik/ Afaik it's an automatic block (HTTP 429?) that resolves after a couple of hours

**Comment by lonvia** [comment]
Make sure you set the replication interval to a day as explained in [the installation instructions](https://nominatim.org/release-docs/latest/admin/Import-and-Update/#setting-up-the-update-process). Otherwise it is indeed likely that you get banned from the Geofabrik servers for a bit.
