### ISSUE TITLE
County no longer appearing in address details

### ISSUE THREAD

**Issue by mchuttani18** [osm-search/Nominatim#1933]
Hi, 

Yesterday, almost all US search queries included a"county" field under "address_details" in the jsonv2 response. Today very few searches include the county.

For example, yesterday when I searched "UCLA", Nominatim included {  "county": "Los Angeles County"  } in address details. Today, the response includes the city and state but not the county.

[UCLA example search URL](https://nominatim.openstreetmap.org/search?format=jsonv2&q=ucla&countrycodes=us&addressdetails=1)

The county field does not appear in address details even when searching a county name explicitly, like "orange county, california." [This query](https://nominatim.openstreetmap.org/search?format=jsonv2&q=orange%20county,%20california&countrycodes=us&addressdetails=1) returns an abandoned railroad (OSM ID 327344057) and Orange County is not listed in address details.

Could you please look into why the county field was removed, and add the field back to address_details?

Thanks!

**Comment by lonvia** [comment]
These kind of  error usually mean that somebody broke the county boundary in OpenStreetMap. And indeed, there is a whole in LA County and Orange County: https://www.openstreetmap.org/relation/396479#map=16/33.9451/-117.9113

**Comment by lonvia** [comment]
I've fixed both counties now.
