### ISSUE TITLE
correct address not found

### ISSUE THREAD

**Issue by fx99-D** [osm-search/Nominatim#1935]
Aspenhaustraße 25, 72770 Reutlingen is not found in the osm search
https://www.openstreetmap.org/search?query=Aspenhaustra%C3%9Fe%2025%2C%2072770%20Reutlingen#map=11/48.5607/9.0833 , 
though correctly mapped: https://www.openstreetmap.org/way/34943641
"Result":
```
Ergebnisse von OpenStreetMap Nominatim

    Keine Ergebnisse gefunden
```

This is probably due to the fact that the building is not on Reutlingen territory but in Kusterdingen.

**Comment by lonvia** [comment]
Nominatim is taking the address from the boundaries not the addr:* tags. There is already issue #148 about that. So closing here as duplicate.
