### ISSUE TITLE
Missing parameter 'featuretype'?

### ISSUE THREAD

**Issue by NicoHood** [osm-search/Nominatim#1938]
I've read multiple times, that there is a parameter called `featuretype` which is not documented. Is that true?
https://help.openstreetmap.org/questions/31629/restricting-nominatim-search-results-to-a-certain-adminstrative-level
https://help.openstreetmap.org/questions/27915/how-to-narrow-the-result-from-nominatim-with-only-cities-and-countries-no-additional-areas

**Comment by mtmail** [comment]
The parameter got removed years ago and there's no other parameter to restrict by type/class/category. Reverse lookup has zoom parameter (https://nominatim.org/release-docs/latest/api/Reverse/) that makes it easy to exclude street-level results, you can test it here https://nominatim.openstreetmap.org/ui/reverse.html?format=html&lat=51&lon=7
