### ISSUE TITLE
Can't search for Kings or Queens counties in New York City

### ISSUE THREAD

**Issue by ab1470** [osm-search/Nominatim#1939]
The five boroughs of NYC are all different counties:

- Manhattan -> New York County
- Brooklyn -> Kings County
- The Bronx -> Bronx County
- Staten Island -> Richmond County
- Queens -> Queens County

(source: [wikipedia](https://en.wikipedia.org/wiki/List_of_counties_in_New_York#:~:text=Five%20boroughs%20of%20New%20York%20City,-Five%20of%20New&text=They%20are%20New%20York%20County,and%20Queens%20County%20(Queens).))

The Nominatim API successfully returns results for New York County, Bronx County, and Richmond County:
[New York County](https://nominatim.openstreetmap.org/ui/search.html?countrycodes=us&state=new%20york&county=new%20york%20county)
[Bronx County](https://nominatim.openstreetmap.org/ui/search.html?countrycodes=us&state=new%20york&county=bronx%20county)
[Richmond County](https://nominatim.openstreetmap.org/ui/search.html?countrycodes=us&state=new%20york&county=richmond%20county)

But it returns zero results for Kings County and Queens County:
[Kings County](https://nominatim.openstreetmap.org/ui/search.html?countrycodes=us&state=new%20york&county=kings%20county)
[Queens County](https://nominatim.openstreetmap.org/ui/search.html?countrycodes=us&state=new%20york&county=queens%20county)

Despite Nominatim's failure to find them, entries for both [Kings County](https://www.openstreetmap.org/relation/369518) and [Queens County](https://www.openstreetmap.org/relation/369519) already exist in OSM.

**Comment by lonvia** [comment]
The relations are broken here: https://www.openstreetmap.org/relation/369518#map=19/40.67906/-73.86265 Once you fix the relations will be searchable again.
