### ISSUE TITLE
Circular relation breaks indexing

### ISSUE THREAD

**Issue by woodpeck** [osm-search/Nominatim#1941]
A `place=locality` relation that contains itself (https://www.openstreetmap.org/relation/8184246, meanwhile fixed) seems to lock up the indexing process:

    update placex set indexed_status=0 where placex.osm_type='R' and placex.osm_id=8184246;
    ERROR:  tuple to be updated was already modified by an operation triggered by the current command

I was able to fix that by manually modifying the `planet_osm_rels` table but ideally self-references should be detected and ignored.

**Comment by woodpeck** [comment]
https://lists.openstreetmap.org/pipermail/dev/2020-September/030986.html for reference

**Comment by mtmail** [comment]
Thanks a lot!

**Comment by mmd-osm** [comment]
I would recommend to also report this as a bug with the iD repo. It’s quite unlikely that the user intentionally created this recursive relation.

**Comment by woodpeck** [comment]
Done https://github.com/openstreetmap/iD/issues/7983

**Comment by lonvia** [comment]
I cannot reproduce this on current master.

In c3dc66ce9c4f5fccaec405c01e7d71130dc19d2b the linking was refactored. As part of this change I restricted valid label members to nodes. Before that, any member type was acceptable. So this might have automatically fixed this issue. The change was part of the 3.5 release. Any version prior to that would still be affected.

Can you please confirm if all of the machines that showed the issue run a Nominatim 3.4 or earlier?

**Comment by mtmail** [comment]
I saw it on Nominatim 3.4 with planet file from 2020/Aug/24. Nominatim 3.5 imported the same fine.

**Comment by lonvia** [comment]
Confirmed that the issue only appeared on older versions of Nominatim, so I consider it fixed. Please comment if you saw the issue on a 3.5 installation.

**Comment by boooch** [comment]
Nominatim 3.5.2 https://github.com/osm-search/Nominatim/issues/2045
