### ISSUE TITLE
Dehradun is a city in India (vs an attraction)

### ISSUE THREAD

**Issue by LeCoupa** [osm-search/Nominatim#1944]
By the way, is there another way to submit mistakes rather than submitting a Github issue?

https://nominatim.openstreetmap.org/search/?q=Dehradun&accept-language=en&addressdetails=1&format=json&limit=1

**Comment by mtmail** [comment]
It's tagged both `place=city` and `tourism=attraction`. I agree with the discussion https://www.openstreetmap.org/changeset/87547846 that the tourism tag is entire redundant if not harmful. Remove the tag and the city should show up again.

> By the way, is there another way to submit mistakes rather than submitting a Github issue?

You can leave a so called map note (https://www.openstreetmap.org/fixthemap), contact local mappers (https://openstreetmap.community/), starts a changeset discussion with the mapper who added a mistake or edit the map. There's no central list of OpenStreetMap data issues.

**Comment by LeCoupa** [comment]
Thank you for your quick answer @mtmail. I read the Nominatim documentation before working with this service but I don't know how to remove the tourism tag. Is it a param to add to the request below?

https://nominatim.openstreetmap.org/search/?q=Dehradun&accept-language=en&addressdetails=1&format=json&limit=1

**Comment by mtmail** [comment]
https://www.openstreetmap.org/node/299531301 Then the 'edit' button

**Comment by LeCoupa** [comment]
Thank you @mtmail! Looks like it is working now 👍

https://nominatim.openstreetmap.org/search/?q=Dehradun&accept-language=en&addressdetails=1&format=json&limit=1
