### ISSUE TITLE
Address not found

### ISSUE THREAD

**Issue by enatalia** [osm-search/Nominatim#1947]
Can not find this address
139 Main St  Brattleboto, VT  EE. UU. 05301

**Comment by mtmail** [comment]
Please add a link to the expected address/building in the OpenStreetMap data, e.g. https://www.openstreetmap.org/way/326049607

**Comment by mtmail** [comment]
Search for "139 Main St Brattleboro, VT 05301" works: https://nominatim.openstreetmap.org/ui/search.html?q=+139+Main+St+Brattleboro%2C+VT+05301

* Nominatim will look for the "EE. UU." part as well and can't find anything in the OpenStreetMap data. 
* the city name is Brattleboro, not Brattleboto. Nominatim doesn't do typo-correction/spellcheck
