### ISSUE TITLE
Editing Node not working

### ISSUE THREAD

**Issue by LeCoupa** [osm-search/Nominatim#1948]
I would like to add the municipality tag as Humacao is a municipality.

> Humacao is a municipality in Puerto Rico located on the eastern coast of the island, north of Yabucoa; south of Naguabo; east of Las Piedras; and west of Vieques Passage. 

But Nothing appears. I do not have the fields to add a tag when I click on the edit button.

https://www.loom.com/share/7b9064903e764eabaa499bfe29edb0eb

**Comment by lonvia** [comment]
Nominatim is a search engine, not an editor. I'm quite sure there is no edit button anywhere. So this is most certainly the wrong issue tracker.

Please read the [OSM wiki](https://wiki.openstreetmap.org/wiki/Beginners%27_guide) for more information about editing OpenStreetMap.

**Comment by LeCoupa** [comment]
Alright @lonvia, it is just because in #1944 I was able to edit the city.
