### ISSUE TITLE
Issue with Melbourne, Australia

### ISSUE THREAD

**Issue by LeCoupa** [osm-search/Nominatim#1949]
(I am sorry for yet another issue opened, but I am trying to understand how to edit nodes (see #1948))

There is an issue with Melbourne. It should link to the Melbourne city in Australia. Instead, it says that it is a county and the next one is in Florida.

https://nominatim.openstreetmap.org/search/?q=Melbourne&accept-language=en&addressdetails=1&format=json&limit=2

**Comment by LeCoupa** [comment]
@lonvia Thank you for dealing with this issue. I am still getting the Melbourne county first. How can we fix this? Do I have to add a tag somewhere on openstreetmap?

**Comment by lonvia** [comment]
The fix is not deployed yet.
