### ISSUE TITLE
Partial or Wildcard searches

### ISSUE THREAD

**Issue by deicidemilan** [osm-search/Nominatim#1950]
Hello,

Is there are any way to force Nominatim doing partial or wildcard searches?
I installed Nominatim on my server, and everyting works perfect except partial or wildcard searches.
When i type zrenjani i got nothingfrom API but zrenjanin i got result :(

[https://nominatim.openstreetmap.org/search.php?q=zrenjani&polygon_geojson=1&format=jsonv2](url)
[https://nominatim.openstreetmap.org/search.php?q=zrenjanin&polygon_geojson=1&format=jsonv2](url)

Or just to install something like this [https://osmnames.org/#q=zrenjan](url).

**Comment by mtmail** [comment]
Also called autocomplete/autosuggest/type-ahead. Nominatim can't do that, but osmnames and https://photon.komoot.de/ can. There has been some work in the last couple of months at https://github.com/osm-search/nominatim-suggest but it's too early to present or use in production.

**Comment by mtmail** [comment]
photon uses a Nominatim dump so it's a good addition, especially if you imported only one country into Nominatim or other import customization.

**Comment by deicidemilan** [comment]
Yes I use only one country, and only need name and coorinate from API.
But I don't like photon. It's have poor documentation. So I maybe try [https://github.com/osmnames/osmnames](url)
But in the end, if osmnames fails I will try photon.

**Comment by mtmail** [comment]
Full list of alternatives at https://wiki.openstreetmap.org/wiki/Search_engines
