### ISSUE TITLE
UPDATE failed since 2020/09/08 : tuple to be updated was already modified by an operation triggered by the current command

### ISSUE THREAD

**Issue by renaudk** [osm-search/Nominatim#1951]
Since september 8th, I got the fllowing error on all my nominatim servers :

```
Starting rank 20
index_placex: UPDATE failed: ERROR:  tuple to be updated was already modified by an operation triggered by the current command
HINT:  Consider using an AFTER trigger instead of a BEFORE trigger to propagate changes to other rows.
Error: 1
```
Nothing has been changed on the servers.
Any idea?

I'm running version 3.4.1 and 3.3.0, both are affected!

Thank you very much for your help.

**Comment by mtmail** [comment]
See closed issue in https://github.com/osm-search/Nominatim/issues/1946

**Comment by mtmail** [comment]
See work-around in https://github.com/osm-search/Nominatim/issues/1941

[sorry, previously I linked to the wrong issue]

**Comment by renaudk** [comment]
That's working, you saved my day, thank a lot!
