### ISSUE TITLE
Update suddenly fail with Nominatim 3.4.2

### ISSUE THREAD

**Issue by eastclintw00d** [osm-search/Nominatim#1954]
Hi,

My updates were automated and used to work for at least the last six months. Something broke it during the last week.

>  ./utils/update.php --import-osmosis-all

This now ends with

> Starting rank 20
> index_placex: UPDATE failed: ERROR:  tuple to be updated was already modified by an operation triggered by the current command
> HINT:  Consider using an AFTER trigger instead of a BEFORE trigger to propagate changes to other rows.
> Error: 1
> 

Any idea what I can do?

Thanks in advance!

**Comment by mtmail** [comment]
Search for closed issues. This is the work-around: https://github.com/osm-search/Nominatim/issues/1941
