### ISSUE TITLE
Importing a planet file on an existing database ?

### ISSUE THREAD

**Issue by UntitleDude** [osm-search/Nominatim#1956]
Hi,

I've used Nominatim to import my country's GPS data, and it's working great. However, I'd like to import the planet file now, but I don't know if it'll break my current database or make the previous import unusable, and the service unreachable, as I need to keep it live while I'm importing planet's data.

Should I import it on another computer ? Otherwise, what steps should I follow to import this big database while keeping my previous import usable ?

**Comment by lonvia** [comment]
If you want to extend to the planet, you should definitely do that into a separate database. It is possible in theory to add data to an existing database but that process is significantly slower than importing into a new database. For a planet it is not feasible.

**Comment by UntitleDude** [comment]
Thanks a lot for your input
And thanks for the great work, it is an awesome piece of software :)
