### ISSUE TITLE
Incorrect city for Moscow

### ISSUE THREAD

**Issue by Heizenergy** [osm-search/Nominatim#1968]
Hi. I try to find coordinates in Moscow but for 3 points I get completely different results. For first I get district instead of city, for second I didn't get an city and for third I get correct result "city" : "Moscow"

```json
{
    "place_id": 93732311,
    "licence": "Data © OpenStreetMap contributors, ODbL 1.0. https://osm.org/copyright",
    "osm_type": "way",
    "osm_id": 29096512,
    "lat": "55.64964195",
    "lon": "37.56608934049156",
    "place_rank": 30,
    "category": "building",
    "type": "apartments",
    "importance": 0,
    "addresstype": "building",
    "name": null,
    "display_name": "56 к1, Балаклавский проспект, Zjuzino, Zyuzino District, South-Western Administrative Okrug, Moscow, Central Federal District, 117246, Russia",
    "address": {
      "house_number": "56 к1",
      "road": "Балаклавский проспект",
      "suburb": "Zjuzino",
      "city": "Zyuzino District",
      "state_district": "South-Western Administrative Okrug",
      "state": "Moscow",
      "region": "Central Federal District",
      "postcode": "117246",
      "country": "Russia",
      "country_code": "ru"
    },
    "boundingbox": [
      "55.6495529",
      "55.6498933",
      "37.5659885",
      "37.5663247"
    ]
  }
```

```json
{
    "place_id": 104452861,
    "licence": "Data © OpenStreetMap contributors, ODbL 1.0. https://osm.org/copyright",
    "osm_type": "way",
    "osm_id": 82798093,
    "lat": "55.59829225",
    "lon": "37.605819707942715",
    "place_rank": 30,
    "category": "building",
    "type": "yes",
    "importance": 0,
    "addresstype": "building",
    "name": null,
    "display_name": "4 к3 с7, Россошанский проезд, Chertanovo Yuzhnoye District, Southern Administrative Okrug, Moscow, Central Federal District, 117535, Russia",
    "address": {
      "house_number": "4 к3 с7",
      "road": "Россошанский проезд",
      "suburb": "Chertanovo Yuzhnoye District",
      "state_district": "Southern Administrative Okrug",
      "state": "Moscow",
      "region": "Central Federal District",
      "postcode": "117535",
      "country": "Russia",
      "country_code": "ru"
    },
    "boundingbox": [
      "55.5982112",
      "55.5983732",
      "37.6056597",
      "37.6059797"
    ]
  }
```

```json
{
    "place_id": 100187040,
    "licence": "Data © OpenStreetMap contributors, ODbL 1.0. https://osm.org/copyright",
    "osm_type": "way",
    "osm_id": 51546920,
    "lat": "55.73077065",
    "lon": "37.578058843821964",
    "place_rank": 30,
    "category": "building",
    "type": "stable",
    "importance": 0,
    "addresstype": "building",
    "name": null,
    "display_name": "1 с2, Usachyova street, Квартал №538, Khamovniki District, Moscow, Central Administrative Okrug, Moscow, Central Federal District, 119048, Russia",
    "address": {
      "house_number": "1 с2",
      "road": "Usachyova street",
      "neighbourhood": "Квартал №538",
      "suburb": "Khamovniki District",
      "city": "Moscow",
      "state_district": "Central Administrative Okrug",
      "state": "Moscow",
      "region": "Central Federal District",
      "postcode": "119048",
      "country": "Russia",
      "country_code": "ru"
    },
    "boundingbox": [
      "55.7306717",
      "55.7308696",
      "37.5778638",
      "37.5782539"
    ]
  }
```

**Comment by Heizenergy** [comment]
![image](https://user-images.githubusercontent.com/37046272/93825120-4b1c4480-fc6d-11ea-8d99-0380cb10a1de.png)
![image](https://user-images.githubusercontent.com/37046272/93825138-553e4300-fc6d-11ea-97c4-30dd3046ea15.png)
![image](https://user-images.githubusercontent.com/37046272/93825158-5f604180-fc6d-11ea-9225-1ea204383063.png)

**Comment by mtmail** [comment]
Please post the full URLs you queried. And for each what you expected to be returned.

**Comment by Heizenergy** [comment]
1. https://nominatim.openstreetmap.org/reverse?format=jsonv2&addressdetails=1&lat=55.64973068237305&lon=37.56659698486328&zoom=18&accept-language=en
2. https://nominatim.openstreetmap.org/reverse?format=jsonv2&addressdetails=1&lat=55.59845733642578&lon=37.60592269897461&zoom=18&accept-language=en
3. https://nominatim.openstreetmap.org/reverse?format=jsonv2&addressdetails=1&lat=55.73076248168945&lon=37.5778923034668&zoom=18&accept-language=en

I choose 3 points in Moscow and expect that I will receive "city":"Moscow" in all 3 requests. But only 1 is correct (last)

**Comment by mtmail** [comment]
(Adding debug URL for each)
1. https://nominatim.openstreetmap.org/ui/details.html?osmtype=W&osmid=29096512&class=building
2. https://nominatim.openstreetmap.org/ui/details.html?osmtype=W&osmid=82798093&class=building
3. https://nominatim.openstreetmap.org/ui/details.html?osmtype=W&osmid=51546920&class=building

**Comment by Heizenergy** [comment]
Do I need to add each debug? And send results to you? Or what? Sorry, I didn't clear understand

**Comment by mtmail** [comment]
You did everything right. Those URLs are just relevant for us (maintainers). They're an alternative view of the last step of the search, where the address hiearchy (street -> city -> country, etc) gets created.

**Comment by lonvia** [comment]
That has already been fixed with the new wikidata item linking. I've forced an update for the District boundaries, so that they come out as suburbs. Moscow is too big to be reindexed in its entirety, so addresses have to sort themselves out over time.
