### ISSUE TITLE
Regressions across commits among the admin elements in the response

### ISSUE THREAD

**Issue by arvindkartik** [osm-search/Nominatim#1969]
Hello, 
I did a full planet reimport once again with the latest master (da72183) and noticed the following regressions with the admin elements in the response, when I compared them with responses across different commits:

Latest import commit:  da72183
Old import commit: 586ff0c

Query1:
| Query | RW 11, Jakarta Special Capital Region, Pasar Manggis, Setiabudi, South Jakarta, Indonesia |
| --- | --- |
| Response from online Nominatim | [RW 11, Jakarta Special Capital Region, Pasar Manggis, Setiabudi, South Jakarta, Indonesia](https://nominatim.openstreetmap.org/search.php?q=RW%2011,%20Jakarta%20Special%20Capital%20Region,%20Pasar%20Manggis,%20Setiabudi,%20South%20Jakarta,%20Indonesia&format=json&addressdetails=1&accept-language=en) |
| Response from old import | RW 11, Pasar Manggis, Setiabudi, South Jakarta, Jakarta Special Capital Region, Indonesia |
| Response from latest import | RW 11, Jakarta Special Capital Region, Indonesia |
| Regression | Few admin elements are missing in the response, maybe related to my earlier issue https://github.com/osm-search/Nominatim/issues/1904  |

<br/>Query2:
| Query | 55, Section 12, Dhaka, Dhaka District, Dhaka Division, Bangladesh |
| --- | --- |
| Response from online Nominatim | [Section 12, Dhaka, Dhaka District, Dhaka Division, Bangladesh](https://nominatim.openstreetmap.org/search.php?q=55,%20Section%2012,%20Dhaka,%20Dhaka%20District,%20Dhaka%20Division,%20Bangladesh&format=json&addressdetails=1&accept-language=en) |
| Response from old import | Section 12, Dhaka, Dhaka District, Dhaka Division, Bangladesh |
| Response from latest import | Section 12, Dhaka District, Dhaka Division, Bangladesh |
| Regression | The city `Dhaka` is missing in the response.  |

<br/>Query3:
| Query | Al Anees Street, Amman, Jordan |
| --- | --- |
| Response from online Nominatim | [Al-Anees Street, الروابي, منطقة تلاع العلي, Amman, 11885, Jordan](https://nominatim.openstreetmap.org/search.php?q=Al%20Anees%20Street,%20Amman,%2011195,%20Jordan&format=json&addressdetails=1&accept-language=en) |
| Response from old import | Al-Anees Street, الروابي, منطقة تلاع العلي, Amman, 11885, Jordan |
| Response from latest import | Al-Anees Street, الروابي, Amman, 11885, Jordan |
| Regression | Both online nominatim & old import returns 2 different admin elements `city` and `state`, both as `Amman`.<br/>However, on the latest import, the `city` is absent while the `state` element in mentioned as `Amman`<br/>If I search just `Amman, Jordan`, then i get both `city` and `state` elements as `Amman` across all the commits |

Also, is the online nominatim running an older version?

**Comment by lonvia** [comment]
Looks like there are really still huge cities in the world which are mapped in OSM with nothing but a tiny place node. Computing addresses for these cities will always be a hit and miss and the only real fix is to add proper areas in OSM. That said, it looks like we need to be a bit more generous for the areas of cities.

nominatim.openstreetmap.org has a mix of versions. It always runs on the code from latest master but the data has been computed with different versions of Nominatim. I.e. the code gets updated but the data is only recomputed as updates come in from OpenStreetMap.

**Comment by arvindkartik** [comment]
Based on [the docs](https://github.com/osm-search/Nominatim/blob/master/docs/develop/Ranking.md#search-rank), the extent specified for `cities, municipalities, islands` is 7.5km for features mapped only as a point.
For following queries the distance is less than 7.5km. Are there cases when the extent is not taken into account?

**Query**: 55, Section 12, Dhaka, Dhaka District, Dhaka Division, Bangladesh
**Coordinates of Response**: [23.82511885, 90.3707484264548](https://nominatim.openstreetmap.org/ui/details.html?osmtype=W&osmid=437400178&class=boundary)
**Coordinates of Dhaka Node**: [23.810651, 90.4126466](https://www.openstreetmap.org/node/3442474911)
**Distance from Dhaka Node to Response**: 4.556km

**Query**: Al Anees Street, Amman, Jordan
**Coordinates of Response**: [31.9692453, 35.8602426](https://nominatim.openstreetmap.org/ui/details.html?osmtype=W&osmid=392727311&class=highway)
**Coordinates of Amman Node**: [31.9515694, 35.9239625](https://www.openstreetmap.org/node/1643504896)
**Distance from Amman Node to Response**: 6.324km
