### ISSUE TITLE
No progress information about rank indexing on update after upgrade to 3.5.1 from 3.4.2

### ISSUE THREAD

**Issue by renaudk** [osm-search/Nominatim#1973]
Hello,

I follow the upgrade process to 3.5.1 (from 3.4.2) but when I restarted incremental updates, there is no more progress info with ETA during indexing step.

Is there a new parameters to pass to update.php or a config setting to change verbosity?

Tried adding `--verbose` but changes nothing.

Current output :
```
WARNING: Starting rank 0
WARNING: Done 0/0 in 0 @ 0.000 per second - FINISHED rank 0

WARNING: Starting rank 1
WARNING: Done 0/0 in 0 @ 0.000 per second - FINISHED rank 1

WARNING: Starting rank 2
WARNING: Done 4/4 in 0 @ 7.761 per second - FINISHED rank 2

WARNING: Starting rank 3
WARNING: Done 0/0 in 0 @ 0.000 per second - FINISHED rank 3

WARNING: Starting rank 4
WARNING: Done 3/3 in 0 @ 3.220 per second - FINISHED rank 4

WARNING: Starting rank 5
WARNING: Done 0/0 in 0 @ 0.000 per second - FINISHED rank 5
```

Thanks for your help

**Comment by lonvia** [comment]
This has already been fixed in  #1895. I would expect that adding ` --verbose` as a parameter also reverts to the previous behaviour.

**Comment by renaudk** [comment]
I tried with 
`utils/update.php --import-osmosis-all --verbose`

Only WARNING level messages are displayed. No change.

**Comment by renaudk** [comment]
It seems the `--verbose` option is working (show INFO messages),
For an unknown reason, indexing process is VERY VERY slow since the upgrade to 3.5.1...

**Comment by lonvia** [comment]
Okay, I'm closing this issue then. Please open a new issue for the slowness and don't forget to add details about your system and software versions.
