### ISSUE TITLE
Unable to reverse geocode certain nodes by id mostly in Romania

### ISSUE THREAD

**Issue by nslxndr** [osm-search/Nominatim#1976]
Certain nodes are exists in database, but they can not be reverse geocoded by node id:

https://nominatim.openstreetmap.org/ui/details.html?osmtype=N&osmid=27418664
https://nominatim.openstreetmap.org/reverse?osm_type=N&osm_id=27418664

https://nominatim.openstreetmap.org/ui/details.html?osmtype=N&osmid=122338839
https://nominatim.openstreetmap.org/reverse?osm_type=N&osm_id=122338839

https://nominatim.openstreetmap.org/ui/details.html?osmtype=N&osmid=129994153
https://nominatim.openstreetmap.org/reverse?osm_type=N&osm_id=129994153

https://nominatim.openstreetmap.org/ui/details.html?osmtype=N&osmid=262786574
https://nominatim.openstreetmap.org/reverse?osm_type=N&osm_id=262786574

https://nominatim.openstreetmap.org/ui/details.html?osmtype=N&osmid=305906875
https://nominatim.openstreetmap.org/reverse?osm_type=N&osm_id=305906875

https://nominatim.openstreetmap.org/ui/details.html?osmtype=N&osmid=454126635
https://nominatim.openstreetmap.org/reverse?osm_type=N&osm_id=454126635

https://nominatim.openstreetmap.org/ui/details.html?osmtype=N&osmid=2026974577
https://nominatim.openstreetmap.org/reverse?osm_type=N&osm_id=2026974577

They are mostly in country called Romania, except the first example is Frankfurt in Germany. Maybe some data error causes this in so many cases? I found a node with very similar tags, but I don't see any substantive difference with the above:
https://nominatim.openstreetmap.org/ui/details.html?osmtype=N&osmid=460160905
https://nominatim.openstreetmap.org/reverse?osm_type=N&osm_id=460160905

**Comment by mtmail** [comment]
Issue is still open and tracked in https://github.com/osm-search/Nominatim/issues/1222

(https://nominatim.org/release-docs/latest/api/Lookup/ works similar to Reverse search when osm type and id are given, lookup can return multiple results if you plan to query a lot of ids).
