### ISSUE TITLE
Why some census tiger road data is missed from nominatim provided "Tiger housenumber data for the US"?

### ISSUE THREAD

**Issue by Johnny-Zhangzhao** [osm-search/Nominatim#1977]
Hi Guys,

I setup a local-based nominatim at my home machine, following the guide at https://nominatim.org/release-docs/latest/admin/Installation/, I'm sure I have installed "Tiger housenumber data for the US" with command below:

```
cd Nominatim/data
wget https://nominatim.org/data/tiger2019-nominatim-preprocessed.tar.gz
tar xf tiger2019-nominatim-preprocessed.tar.gz
```

everything works pretty nice for most cases, but for some, seems like it doesn't. Take "**724 2nd St. NW, Dyersville, IA, 52040**" as example, If search it at "Census official website" with "https://geocoding.geo.census.gov/geocoder/locations/onelineaddress?address=724+2nd+St.+NW%2C+Dyersville%2C+IA%2C+52040&benchmark=4", I can get the result like below:

```
Matched Address: 724 2ND ST NW, DYERSVILLE, IA, 52040
Coordinates:X: -91.125374 Y: 42.491295
Tiger Line Id: 16899641 Side: L
Address Components:

From Address: 600
To Address: 798
PreQualifier:
PreDirection:
PreType:
Street Name: 2ND
SuffixType: ST
SuffixDirection: NW
SuffixQualifier:
City: DYERSVILLE
State: IA
Zip: 52040
```

But query with the imported tiger housenumber database from Nominatim, returns nothing. Did I do something wrong? As far as I know, the Census Tiger data should includes all roads with housenumber range in United States, any help is appreciated!

Thanks,
Johnny

**Comment by mtmail** [comment]
Result on the nominatim.openstreetmap.org server: https://nominatim.openstreetmap.org/ui/search.html?q=724+2nd+St.+NW%2C+Dyersville%2C+IA%2C+52040

Did you run all 4 steps in https://nominatim.org/release-docs/latest/admin/Import-and-Update/#installing-tiger-housenumber-data-for-the-us ?

What does `select count(*) from location_property_tiger;` return? It should be about 33 million rows.

**Comment by Johnny-Zhangzhao** [comment]
Thanks for your reminder, mtmail, I checked all steps again, seems like I missed something,  I will make it closed.

**Comment by Johnny-Zhangzhao** [comment]
Hi mtmail,

After the correction of 4 steps, seems like all my cases works fine now, except "**509 Northern Ave., Earlville, Iowa, 52041**", the road can be searched from OSM data, but not available in "location_property_tiger", unable to get the housenumber range.  

BTW, if I run "`select count(*) from location_property_tiger`" , it retuns "33,598,589".

Thanks,
Johnny

**Comment by lonvia** [comment]
The address does not appear in the Tiger data used on nominatim.openstreetmap.org. it might be available in a newer version or a different Tiger data set (see also https://github.com/osm-search/TIGER-data/issues/1).

On a general note: you can't expect that all address of the Tiger database are searchable. Nominatim requires that the street referenced in the Tiger data does also exist in the OSM dataset. If the street cannot be found (for example, because of a typo in the name or the geometry), then the addresses are dropped.
