### ISSUE TITLE
Stuck with no progress on Update - v3.5.2

### ISSUE THREAD

**Issue by d3mon187** [osm-search/Nominatim#1983]
I'm trying to get a planet import to do an osmosis update, but it appears to freeze after processing nodes, ways, and relations.  Looking at the database, the only active query is - COPY "place" FROM STDIN.  According to my server stats I can see that the query is using tons of disk IO at 200-400MB a second.  Still, I have let it run for over 2 days, and the osmosis import showed no updates on progress.  I tried using the latest osm2pgsql version from master, as well as updating Nominatim from 3.5.1 to 3.5.2. Am I missing something? Thanks!

```
sudo docker exec -it nominatim sudo -u postgres ./src/build/utils/update.php --verbose --import-osmosis --osm2pgsql-cache 22000
Currently at sequence 2928 (17/09/2020 23:58:04) - 1 indexed
'/usr/local/bin/pyosmium-get-changes' --server 'https://planet.openstreetmap.org/replication/day' --outfile '/app/src/build/osmosischange.osc' --size 20 '--start-id' 2928
'/app/src/build/osm2pgsql/osm2pgsql' --hstore --latlong --append --slim '--number-processes' 1 --cache 22000 --output gazetteer --style '/app/src/settings/import-full.style' --database nominatim --port 5432 '/app/src/build/osmosischange.osc'
osm2pgsql version 1.2.0 (v3.5.2)

Allocating memory for dense node cache
Allocating dense node cache in one big chunk
Allocating memory for sparse node cache
Sharing dense sparse
Node-cache: cache=22000MB, maxblocks=352000*65536, allocation method=11
Mid: pgsql, cache=22000
Parsing gazetteer style file '/app/src/settings/import-full.style'.
Using projection SRS 4326 (Latlong)

Reading in file: /app/src/build/osmosischange.osc
Using XML parser.
Processing: Node(3588k 66.4k/s) Way(831k 16.62k/s) Relation(12342 726.0/s)  parse time: 121s
Node stats: total(3588852), max(7921640261) in 54s
Way stats: total(831818), max(849053464) in 50s
Relation stats: total(12342), max(11643024) in 17s
```

**Comment by lonvia** [comment]
Please supply the following information: hardware configuration(CPUs, RAM size, disk type and size), OS type and version, Postgresql and PostGIS version, changes you made to the default Postgresql config.

Have you run `./utils/setup.php --create-functions --enable-diff-updates` after updating to 3.5.2? Please also try without the `--osm2pgsql-cache 22000` parameter.

**Comment by d3mon187** [comment]
It is running on a VM with 12 vcpu, 32gb of ram, 10 disk raid 10 ssd with 3tb.  OS is Ubuntu 20.04 Server.  I'm working out of the  nominatim-docker/3.5 with Postgresql 12 and POSTGIS="3.0.0 r17983" [EXTENSION] GEOS="3.8.0-CAPI-1.13.1 " PROJ="6.3.1" LIBXML="2.9.4" LIBJSON="0.13.1" LIBPROTOBUF="1.3.3" WAGYU="0.4.3 (Internal)".  I have run create and init scripts on 3.5.2, and without cache parameter.  I've tried adjusting postgres config many different ways, but current config changes are:

# Memory Settings
shared_buffers = 2GB
work_mem = '50 MB'
autovacuum_work_mem = 2GB
maintenance_work_mem = 5GB
effective_cache_size = '12 GB'
effective_io_concurrency = 200
# Replication
wal_level = minimal
synchronous_commit = off
# Checkpointing:
checkpoint_timeout  = 30min
checkpoint_completion_target = 0.9
max_wal_size = 1GB
default_statistics_target = 100
# Parallel queries:
max_worker_processes = 12
#postgres12 features
max_parallel_maintenance_workers = 2
# Advanced features
jit_above_cost = -1
max_parallel_workers_per_gather = 0
random_page_cost = 1.5

**Comment by d3mon187** [comment]
I am using a flatnode file since it said it was recommended in the docs for large imports.  Is there a built in way to include the node file for updates?  Only documentation I saw was defining CONST_Osm2pgsql_Flatnode_File in local.php.  

I also just reran the check_import_finished.php and it failed on the indexing status.  Which is odd since I could have sworn it passed after I had run the initial import.  I wasn't sure if Tiger housenumbers were automatically imported on the initial import, so I did import those afterwards.  Would that mess anything up?

I'm trying "--index --create-search-indices --create-country-names --index-noanalyse" right now.

Thanks for the help!

**Comment by mtmail** [comment]
> I am using a flatnode file since it said it was recommended in the docs for large imports. Is there a built in way to include the node file for updates? Only documentation I saw was defining CONST_Osm2pgsql_Flatnode_File in local.php.

The update.php script reads the local.php file and would find the flatnode file. I think lonvia's question was more if the file was moved or deleted after the initial import.

> I also just reran the check_import_finished.php and it failed on the indexing status. Which is odd since I could have sworn it passed after I had run the initial import.
> I'm trying "--index --create-search-indices --create-country-names --index-noanalyse" right now.

Yes, that's the right command. You can also add `--ignore-errors` for/against "[index name] already exists"

> I wasn't sure if Tiger housenumbers were automatically imported on the initial import, so I did import those afterwards. Would that mess anything up?

That's fine. The Tiger script can be run multiple times and writes to different tables than the OSM place scripts.

**Comment by d3mon187** [comment]
Yep, looks like it was an indexing error.  I could have sworn I checked, but after running the reindex command two additional times, check_import_finished finally reported everything was good.  After the first run it was down to 700 or so still needing indexed.  Is that normal for it to miss some and need multiple runs?

THANKS!

**Comment by mtmail** [comment]
I've seen that before, not sure why it happening. In one of my install scripts I have

```
# not sure why, sometimes some places (<500) remained unindexed after first full import + updates
./utils/update.php --index
```

**Comment by lonvia** [comment]
> After the first run it was down to 700 or so still needing indexed. Is that normal for it to miss some and need multiple runs?

This is normal because some objects of higher rank cause objects of lower rank to be invalidated. Nothing to worry about they will be caught in the next round. Also, the master version has switched the indexing order so that this is less likely to happen.

@d3mon187 Please recheck that `CONST_Osm2pgsql_Flatnode_File` is still set in `settings/local.php` when you run the updates. In the original output that you posted, the flatnode file is clearly missing. Note that you will not get any errors in that case. You will just see that more and more data disappears in each update round.

**Comment by d3mon187** [comment]
@lonvia you are totally right.  Oh the joys of dockers and keeping track of file changes.  No idea how I missed that, but looks like I'm going for another import.  Should hopefully go much smoother this time.  Thanks for the help!
