### ISSUE TITLE
Problems with data import

### ISSUE THREAD

**Issue by rolandg** [osm-search/Nominatim#1989]
Hi,

we are having problems to import osm data (DACH area) in our kubernetes cluster. We are using stolon for postgres HA. We are getting `psycopg2.OperationalError: server closed the connection unexpectedly` somewhen during the import. We had this problems earlier and usually 1 or 2 retries and we were able to import the data. Since i updated to the current version I cannot import the data anymore.

I currently have set IMPORT_THREADS to 4. 

Do you have an idea what could be the reason for this?
Are there any other parameters that could improve the situation?
Is there a way to continue importing where it stopped?

**Comment by mtmail** [comment]
Users have reported 'server closed [unexpectetly]' before. We can only point to the postgresql logs, often it's network related. Nominatim can't really do much and doesn't have retry logic (though some steps of the setup.php and update.php can be run multiple times to recover).
