### ISSUE TITLE
Search diference address interpolation

### ISSUE THREAD

**Issue by emejia1980** [osm-search/Nominatim#199]
Install the last version of nominatim clone with the latest source code from Github.

But have difference answer for search in my local server, please note the example:

Incorrect answer:
http://192.168.1.117/nominatim/search?q=cr+10.43765,-83.6435383333333&format=xml&addressdetails=18&limit=0
Display: Finca Altagracia

Correct answer:
http://nominatim.openstreetmap.org/search?q=cr+10.43765,-83.6435383333333&format=xml&addressdetails=18&limit=0
Display: Finca Esterlina

Need run some script or adjust some in my server for identical answer that OpenStreetmap server ?

**Comment by lonvia** [comment]
Need a test case if the order by importance instead of distance from the coordinate has been fixed.
