### ISSUE TITLE
Wrong postcode for the suburb Cronenbourg

### ISSUE THREAD

**Issue by Bischnu** [osm-search/Nominatim#1990]
The postcode returned on Nominatim and OpenStreetMap for the suburb called Cronenbourg (node 1212907470) is wrong. It shows 7200 and should be 67200.
I do not know if the correct way to edit it is on Nominatim (how apart by opening an issue?), add a label postal_code on the OSM node or add a Postal code to the Wikidata element if it is OK with suburbs (Q3003711).

**Comment by mtmail** [comment]
https://nominatim.openstreetmap.org/ui/details.html?osmtype=N&osmid=1212907470

This node https://www.openstreetmap.org/node/6567838974 might be causing the issue in the postcode calculation. The calculation is explained at http://nominatim.org/release-docs/latest/develop/Postcodes/ I think if you fix that node and wait 24h the Cronenbourg node should be fine again.

**Comment by mtmail** [comment]
And https://www.openstreetmap.org/node/3719111196 (the overpass output had the results almost overlap).

**Comment by Bischnu** [comment]
OK thanks for the documentation, I will edit these nodes. I will also look on OSM and Wikidata if it is a good practice to add postcodes of suburbs in each databases.

**Comment by mtmail** [comment]
Ideally we'd have `boundary=postal_code` relations https://overpass-turbo.eu/s/YCM but those are often not available, it's something you can't observe, they usually have to be imported from an ODbL compatible data source. Suburbs can have multiple postcodes, even streets can have multiple (left side vs right side of the road) so mappers have to use lists (comma or semicolon separated, we've seen : separated, too) or ranges. Nominatim can't handle those lists and ranges well yet.

![image](https://user-images.githubusercontent.com/3727288/94923991-08543b00-04bd-11eb-9af4-4e6e5b86e523.png)

**Comment by Bischnu** [comment]
I changed the two nodes Friday but the suburb still appears as 7200.
Also, I found that Strasbourg city releases a lot of data on an open-data hub, and there is one set describing the postal codes of the metropolis: https://data.strasbourg.eu/explore/dataset/secteurs-postaux/table/?location=10,48.56813,7.71705&basemap=8b5b47
There is an API which could help to automate the edits on OSM, but I do not really know how to manipulate it.

**Comment by lonvia** [comment]
Postcodes only get updated when the object itself gets updated. Postcodes on larger areas like suburbs, neighbourhood are only informative anyway.
