### ISSUE TITLE
Update script should check if flatfile is missing

### ISSUE THREAD

**Issue by mtmail** [osm-search/Nominatim#1991]
As follow-up to https://github.com/osm-search/Nominatim/issues/1983 the `update.php` should check if the configuration value for flatfile (`CONST_Osm2pgsql_Flatnode_File`) was set and check the file still exists.

**Comment by mtmail** [comment]
Should check_import_finished.sh should add a warning, too?

**Comment by lonvia** [comment]
It's a bit more complicated. `CONST_Osm2pgsql_Flatnode_File` must have the same value during import and update. If it wasn't set on import then that's perfectly fine.

I think this is rather something for osm2pgsql. It can use the presence/absence of planet_osm_node to check if a flatnode file is needed and abort if the update is missing the parameter. See https://github.com/openstreetmap/osm2pgsql/issues/39 for details.

**Comment by lonvia** [comment]
I'm closing this in favour of the osm2pgsql ticket.
