### ISSUE TITLE
More descriptive type for protected areas

### ISSUE THREAD

**Issue by ZeLonewolf** [osm-search/Nominatim#1997]
This is a suggestion to improve search results for certain protected areas.

boundary=protected_area combined with protect_class=* for values 1a, 1b, 2, 3, 4, 5, and 6 have specific meaning, as the derive from IUCN conservation categories.

For example, Little Desert National Park comes up with the type "Protected Area" rather than "National Park"
https://www.openstreetmap.org/search?query=Little%20Desert%20National%20Park

There are currently two ways to tag a national park in OSM.  A mapper can use boundary=national_park, or the newer boundary=protected_area + protect_class=2.  Ideally, either usage should show up as a "National Park" in Nominatim search results.

I suggest that the following type names could be used instead of Protected Are for these class values:

1a: Nature Reserve
1b: Wilderness Area
2: National Park
3: Natural Monument
4, 5, 6: Conservation Area

**Comment by lonvia** [comment]
The descriptive names on the OpenStreetMap website are set by the website itself. So this is the wrong repository to ask for this feature request.

That said, the names are currently derived from the main tag only (`boundary=protected_area`) and there is no mechanism to take secondary tags into account. We need an entirely new algorithm, which unfortunately is not going to happen any time soon.
