### ISSUE TITLE
Slow indexing on update with ranks 1-25 since upgrade from 3.4.2 to 3.5.2

### ISSUE THREAD

**Issue by renaudk** [osm-search/Nominatim#1998]
Hello,

I've just upgraded from 3.4.2 to 3.5.2.

Since the upgrade, indexation process during incremental update is very slow for ranks < 26.
For example, indexing day of 09/30/20 took :
- about 20 min for downloading/importing data
- about 16 hours for ranks 1-25
- about 30 min for ranks 26-30

Machine is :
- Intel(R) Xeon(R) E-2136 CPU @ 3.30GHz 6c/12t
- 32 GB RAM
- SSD NVMe RAID-Z (2x 440 Go)
- ZFS recordsize=16k, atime=off, compression=lz4
- Ubuntu 18.04 LTS with PostgreSQL 10

Notes:
- Updating wikidata took about 48 hours.
- I've let finished autovacuum before restarting updates.
- I've tried to defragment the whole ZFS pool via a full recreation of the pool (with zfs send/recv datasets on another machine)
- I use 8 threads for update command (also tried less but changes nothing)
- Same behavior with Nominatim 3.5.1

I've no more idea to solve this issue, if anyone can help me...

Below is Zabbix graph, the CPU is about 80-90% idle while indexing ranks 1 to 25...

![nominatim-3 5 2-updates](https://user-images.githubusercontent.com/38570621/95429774-20a7d800-094b-11eb-9f26-e3804854e44c.png)

Best regards

**Comment by lonvia** [comment]
Can you please post the lines with FINISHED from one update run? Something like `grep FINISHED update.log` should do the trick.

**Comment by renaudk** [comment]
I've not all ranks because it was running in a screen. Rank 30 is chatty so I couldn't get rank 22-26 logs.
But here is what I could get from last import:

Day 2020/10/07 indexing
```
WARNING: Done 0/0 in 0 @ 0.000 per second - FINISHED rank 0
WARNING: Done 0/0 in 0 @ 0.000 per second - FINISHED rank 1
WARNING: Done 2/2 in 0 @ 4.496 per second - FINISHED rank 2
WARNING: Done 0/0 in 0 @ 0.000 per second - FINISHED rank 3
WARNING: Done 7/7 in 4 @ 1.528 per second - FINISHED rank 4
WARNING: Done 0/0 in 0 @ 0.000 per second - FINISHED rank 5
WARNING: Done 1/1 in 2 @ 0.420 per second - FINISHED rank 6
WARNING: Done 0/0 in 0 @ 0.000 per second - FINISHED rank 7
WARNING: Done 54/54 in 460 @ 0.117 per second - FINISHED rank 8
WARNING: Done 0/0 in 0 @ 0.000 per second - FINISHED rank 9
WARNING: Done 32/32 in 843 @ 0.038 per second - FINISHED rank 10
WARNING: Done 0/0 in 0 @ 0.000 per second - FINISHED rank 11
WARNING: Done 86/86 in 2515 @ 0.034 per second - FINISHED rank 12
WARNING: Done 0/0 in 0 @ 0.000 per second - FINISHED rank 13
WARNING: Done 41/41 in 840 @ 0.049 per second - FINISHED rank 14
WARNING: Done 3/3 in 0 @ 9.776 per second - FINISHED rank 15
WARNING: Done 480/480 in 6041 @ 0.079 per second - FINISHED rank 16
WARNING: Done 7746/7746 in 11 @ 647.826 per second - FINISHED rank 17
WARNING: Done 742/742 in 1275 @ 0.582 per second - FINISHED rank 18
WARNING: Done 2843/2843 in 1289 @ 2.205 per second - FINISHED rank 19
WARNING: Done 3187/3187 in 2154 @ 1.479 per second - FINISHED rank 20
WARNING: Done 2466/2466 in 557 @ 4.423 per second - FINISHED rank 21
...
WARNING: Done 12252/12252 in 106 @ 115.370 per second - FINISHED rank 27
WARNING: Done 10/10 in 0 @ 36.433 per second - FINISHED rank 28
WARNING: Done 1/1 in 0 @ 1.094 per second - FINISHED rank 29
WARNING: Done 1530/1530 in 20 @ 74.799 per second - FINISHED interpolation lines (location_property_osmline)
WARNING: Done 224215/224215 in 858 @ 261.137 per second - FINISHED rank 30
```

If needed, I'll be able to get all ranks on next run, results in few hours...

**Comment by lonvia** [comment]
That's fine. I was just curious which ranks are affected. Looks like really all ranks <26 are slow with the curious exception of 17. Probably a missing index somewhere. Please check first if running `ANALYSE` fixes anything. If not, then we'd need a trace of a single update execution. To obtain one, do the following:
* Stop the update process while it is indexing the ranks < 26. (Don't worry, that's safe. It will pick up correctly afterwards.)
* Add the following lines to your postgresql.conf file:
  ````
      session_preload_libraries = 'auto_explain'
      auto_explain.log_min_duration = '0'
      auto_explain.log_analyze = 'true'
      auto_explain.log_nested_statements = 'true'
  ````
* Reload postgresql.
* Run the following SQL command: `update placex set indexed_status = 0 where place_id = (select place_id from placex where rank_search between 18 and 25 and indexed_status > 0 limit 1)` You should see `UPDATE 1`.
* Remove the lines from the config file and reload postgres.

Your postgresql logfile should now contain a lot of tracing messages. Please provide those.

**Comment by renaudk** [comment]
I confirm, all ranks < 26 are affected, speed increase on rank 26. I'm running ANALYSE, I keep you up :)

**Comment by renaudk** [comment]
ANALYSE doesn't seem to change anything.

Here is the log as you requested.
[log_nominatim_psql.txt](https://github.com/osm-search/Nominatim/files/5354930/log_nominatim_psql.txt)

**Comment by lonvia** [comment]
Thank you. Those logs show that the problem is with the `INSERT` statements. That suggests that your issue have nothing to do with the Nominatim update but that there is indeed an issue with writing to your disks. Check your system logs for errors. Have you changed anything else during the update, for example the postgresql config? It might also be that a table or index is corrupted. The `search_name` table shows up as being especially slow. You can try recreating the indexes there.

**Comment by renaudk** [comment]
There were no change other than upgrading Nominatim.
I try to run `REINDEX TABLE search_name;` and let you know.

**Comment by renaudk** [comment]
REINDEX on search_name did not change anything.

Also by logging slow queries, I see the following issue:
```
2020-10-10 06:14:08.752 UTC [32737-1] nominatim@nominatim LOG:  duration: 410343.914 ms  statement: UPDATE placex SET indexed_status = 0 WHERE place_id IN (220149225)
2020-10-10 06:14:08.753 UTC [32738-1] nominatim@nominatim LOG:  duration: 409939.331 ms  statement: UPDATE placex SET indexed_status = 0 WHERE place_id IN (220064490)
2020-10-10 06:14:08.753 UTC [32735-1] nominatim@nominatim LOG:  duration: 409939.397 ms  statement: UPDATE placex SET indexed_status = 0 WHERE place_id IN (220086097)
2020-10-10 06:14:08.753 UTC [32733-1] nominatim@nominatim LOG:  duration: 409958.764 ms  statement: UPDATE placex SET indexed_status = 0 WHERE place_id IN (220086094)
2020-10-10 06:14:08.753 UTC [32739-1] nominatim@nominatim LOG:  duration: 409955.884 ms  statement: UPDATE placex SET indexed_status = 0 WHERE place_id IN (220099960)
2020-10-10 06:14:08.753 UTC [32731-1] nominatim@nominatim LOG:  duration: 409939.557 ms  statement: UPDATE placex SET indexed_status = 0 WHERE place_id IN (220064485)
2020-10-10 06:14:08.753 UTC [32734-1] nominatim@nominatim LOG:  duration: 409950.184 ms  statement: UPDATE placex SET indexed_status = 0 WHERE place_id IN (220073929)
2020-10-10 06:14:08.753 UTC [32736-1] nominatim@nominatim LOG:  duration: 409967.423 ms  statement: UPDATE placex SET indexed_status = 0 WHERE place_id IN (220086091)
```

I tried to reindex placex table but it has no effect, any idea?

**Comment by lonvia** [comment]
This is exactly the query you were sending the log for above. You can try and create a log for one of  the especially slow ones by downloading the script from #2002 and running it with `./analyse_indexing.py  -d nominatim --place-id 220149225`.

**Comment by renaudk** [comment]
I've tried to `REINDEX DATABASE nominatim` => no change.

Here is the output of `./analyse_indexing.py -d nominatim --place-id 220149225`:
[log_nominatim_analyse.txt](https://github.com/osm-search/Nominatim/files/5359260/log_nominatim_analyse.txt)

Indexes of placex table:
```
                             Table "public.placex"
     Column      |            Type             | Collation | Nullable | Default
-----------------+-----------------------------+-----------+----------+---------
 place_id        | bigint                      |           | not null |
 parent_place_id | bigint                      |           |          |
 linked_place_id | bigint                      |           |          |
 importance      | double precision            |           |          |
 indexed_date    | timestamp without time zone |           |          |
 geometry_sector | integer                     |           |          |
 rank_address    | smallint                    |           |          |
 rank_search     | smallint                    |           |          |
 partition       | smallint                    |           |          |
 indexed_status  | smallint                    |           |          |
 osm_id          | bigint                      |           | not null |
 osm_type        | character(1)                |           | not null |
 class           | text                        |           | not null |
 type            | text                        |           | not null |
 name            | hstore                      |           |          |
 admin_level     | smallint                    |           |          |
 address         | hstore                      |           |          |
 extratags       | hstore                      |           |          |
 geometry        | geometry(Geometry,4326)     |           | not null |
 wikipedia       | text                        |           |          |
 country_code    | character varying(2)        |           |          |
 housenumber     | text                        |           |          |
 postcode        | text                        |           |          |
 centroid        | geometry(Geometry,4326)     |           |          |
Indexes:
    "idx_place_id" UNIQUE, btree (place_id)
    "idx_placex_adminname" btree (make_standard_name(name -> 'name'::text), rank_search) WHERE osm_type = 'N'::bpchar AND rank_search < 26
    "idx_placex_geometry" gist (geometry)
    "idx_placex_geometry_reverse_lookuppoint" gist (geometry) WHERE (name IS NOT NULL OR housenumber IS NOT NULL OR rank_address >= 26 AND rank_address <= 27) AND (class <> ALL (ARRAY['railway'::text, 'tunnel'::text, 'bridge'::text, 'man_made'::text])) AND rank_address >= 26 AND indexed_status = 0 AND linked_place_id IS NULL
    "idx_placex_geometry_reverse_lookuppolygon" gist (geometry) WHERE (st_geometrytype(geometry) = ANY (ARRAY['ST_Polygon'::text, 'ST_MultiPolygon'::text])) AND rank_address >= 4 AND rank_address <= 25 AND type <> 'postcode'::text AND name IS NOT NULL AND indexed_status = 0 AND linked_place_id IS NULL
    "idx_placex_geometry_reverse_placenode" gist (geometry) WHERE osm_type = 'N'::bpchar AND rank_search >= 5 AND rank_search <= 25 AND class = 'place'::text AND type <> 'postcode'::text AND name IS NOT NULL AND indexed_status = 0 AND linked_place_id IS NULL
    "idx_placex_linked_place_id" btree (linked_place_id) WHERE linked_place_id IS NOT NULL
    "idx_placex_osmid" btree (osm_type, osm_id)
    "idx_placex_parent_place_id" btree (parent_place_id) WHERE parent_place_id IS NOT NULL
    "idx_placex_pendingsector" btree (rank_search, geometry_sector) WHERE indexed_status > 0
    "idx_placex_rank_address" btree (rank_address)
    "idx_placex_rank_search" btree (rank_search)
Triggers:
    placex_before_delete AFTER DELETE ON placex FOR EACH ROW EXECUTE PROCEDURE placex_delete()
    placex_before_insert BEFORE INSERT ON placex FOR EACH ROW EXECUTE PROCEDURE placex_insert()
    placex_before_update BEFORE UPDATE ON placex FOR EACH ROW EXECUTE PROCEDURE placex_update()

```

**Comment by lonvia** [comment]
The wikidata index is missing:

```
CREATE INDEX idx_placex_wikidata on placex USING BTREE ((extratags -> 'wikidata')) WHERE extratags ? 'wikidata' and class = 'place' and osm_type = 'N' and rank_search < 26;
```

I'll add that to the migration guide.

**Comment by renaudk** [comment]
Thank you! I'm running the index creation, I'll keep you up. Are there other indexes added in 3.5.0 to check?

**Comment by renaudk** [comment]
Index creation has fixed indexing speed, thank you very much @lonvia .
If you need to check other indexes, just ask me.

**Comment by lonvia** [comment]
We usually try to note all necessary index changes in the migration guide. This one just got lost somehow.

**Comment by renaudk** [comment]
Also note that the DROP FUNCTION must be done before recreating them.

The right step order for Migrating to 3.5.0 is:

- download the new Wikipedia tables as described in the import section
- reimport the tables: `./utils/setup.php --import-wikipedia-articles`
- Drop create_country function with `DROP FUNCTION create_country(hstore,character varying);`
- update the functions: `./utils/setup.php --create-functions --enable-diff-updates --create-partition-functions`
- create index : `CREATE INDEX idx_placex_wikidata on placex USING BTREE ((extratags -> 'wikidata')) WHERE extratags ? 'wikidata' and class = 'place' and osm_type = 'N' and rank_search < 26;`
- compute importance: `./utils/update.php --recompute-importance`
