### ISSUE TITLE
House number

### ISSUE THREAD

**Issue by mtnskb** [osm-search/Nominatim#1999]
Hello,

I have installed Nominatim 3.5.2 over Ubuntu and works fine. 
The problem is a lot of house number aren't in OSM map... In case of USA, Nominatim allow import data from TIGER.

¿some way to import house number data for others countries (Portugal, Spain...)?

thanks!

**Comment by lonvia** [comment]
No, we don't support any other external datasets at the moment. There is a request for OpenAddresses (#246) but no interest in providing an implementation so far.
