### ISSUE TITLE
India administrative levels: incorrect classification of some administrative boundaries as "state"

### ISSUE THREAD

**Issue by patelmm79** [osm-search/Nominatim#2005]
For India, I have found a few examples of boundaries that are not state-level in reality or in the OSM data itself, but are indicated as such in Nominatim.

Example 1: Bhuj (https://www.openstreetmap.org/node/567903581); within OSM, seems to be indicating state correctly as Gujarat.

However, in Nominatim API: 

https://nominatim.openstreetmap.org/search/?format=json&addressdetails=1&limit=2&polygon_geojson=0&city=bhuj&country_code=in

the API outputs state as "Kachchh"

In the UI, 

https://nominatim.openstreetmap.org/ui/details.html?osmtype=N&osmid=567903581

In the address section, "Kachchh" is marked "boundary:administrative (state)"

That is likely because "Kachchh" has a rank of "state"; it is not a state.  : 

 https://nominatim.openstreetmap.org/ui/details.html?osmtype=R&osmid=8269590&class=boundary

Example 2: Khanvel

Nominatim:
https://nominatim.openstreetmap.org/ui/details.html?osmtype=N&osmid=2870078962

The correct state is "Dadra and Nagar Haveli and Daman and Diu", however the marked state is "Dadra and Nagar Haveli" which is not the state, for similar reasons as above.

**Comment by mtmail** [comment]
I think https://wiki.openstreetmap.org/w/index.php?title=Tag:boundary%3Dadministrative&uselang=en-US and https://en.wikipedia.org/wiki/Administrative_divisions_of_India agrees with you. "Dadra and Nagar Haveli" (https://www.openstreetmap.org/relation/1952531, admin_level=5) should be a district or a place type between state and county.

**Comment by lonvia** [comment]
This is a data issue. Kachchh is marked as state here: https://www.openstreetmap.org/node/316417062 and Dadra and Nagar Haveli here: https://www.openstreetmap.org/node/4569991190

On a general note: if the address list in the details view has a specific designation (like state, or city or village), then this is always because somebody has classified it explicitly as such in OSM. To find out where it comes from, follow the details link of the address part in question. You'll find either a 'place' in the extratags section. Then the object itself has a place tag. Or you'll find a 'Linked place', a node that has the place tag.

**Comment by patelmm79** [comment]
@lonvia , thanks for the information. I figured that there was a data field that needed to be changed, but it wasn't clear as to where that was!

Is Nominatim the only way to find out what the "Linked Place" is for an administrative boundary? in the case of Kutch, from the OSM edit screen, I see no tag for boundary w/ ID 8269590 that links to place 316417062 .  Where is that relationship established exactly?

**Comment by mtmail** [comment]
@patelmm79 In the past you would look for relationship member of role `admin_centre` pointing to a node by the same name. E.g. https://www.openstreetmap.org/relation/1798824 and https://www.openstreetmap.org/node/245737900

![image](https://user-images.githubusercontent.com/3727288/95666830-fc701500-0b5d-11eb-9955-ab3c6bfc0466.png)

Newer versions of Nominatim also check name and wikidata ids (and if the node is really inside the relation) to link places. The link is only stored in the Nominatim database. There is a section "linked places" on the detail pages, e.g. https://nominatim.openstreetmap.org/ui/details.html?osmtype=R&osmid=8269590

**Comment by lonvia** [comment]
To add to that: the notation of 'linked places' is an internal one of Nominatim which we need to compute meaningful address terms. These days, linked places are searched by:

* A relation member with role `label`. (Not `admin_center` anymore as this is might be a contained city like the capital.)
* If the relation has a `place` tag, a place node with the same name and the same `place` tag.
* A place node with the same wikidata tag.
* A place node with the same name and the same [address rank](https://nominatim.org/release-docs/develop/develop/Ranking/#address-rank).

The latter is the "desperate fallback". If you want to express in the OSM data that a place node and an admin relation are the same, either use the label member or the wikidata tag. In the case of the Indian states above, it was the wikidata tag that caused the connection to be made.
