### ISSUE TITLE
File Storage mount to Docker Image

### ISSUE THREAD

**Issue by ctchetan** [osm-search/Nominatim#2010]
The Docker Image: peterevans/nominatim-k8s:latest reads the env variable NOMINATIM_PBF_URL which contains the URL of the pbf file (like: http://download.geofabrik.de/asia/maldives-latest.osm.pbf). 
Is there a way to specify the location of the pbf which is present on the file system directly (like: /mnt/maldives-latest.osm.pbf).

**Comment by lonvia** [comment]
Please report/ask this in the repo of the docker image. We are not affiliated with that.
