### ISSUE TITLE
Changes to English special phrases

### ISSUE THREAD

**Issue by Simon-Will** [osm-search/Nominatim#2014]
I made quite a lot of changes to the [English special phrases list](https://wiki.openstreetmap.org/wiki/Nominatim/Special_Phrases/EN). Have a look at the [wiki comparison](https://wiki.openstreetmap.org/w/index.php?title=Nominatim%2FSpecial_Phrases%2FEN&type=revision&diff=2049252&oldid=1871092) to previous version.

I removed some unused tags, e.g. `place=house`.

I added some that I consider fairly important, e.g.
`building=mosque`, `building=synagogue`, `amenity=public_bookcase`, crafts like `craft=tailor`, etc.

I added new names for some, e.g.
“nursery” for `amenity=kindergarten`

I renamed some, e.g.
`amenity=emergency_phone` to `emergency=phone`

I added some that you may object to for various reasons, e.g.
`amenity=kneipp_water_cure`, `bridge=*`, `building=greenhouse`

I readded `shop=cosmetics`, which was removed in the context of issue #103. It has 20k tags and I consider it relevant.

I also moved some lines from the bottom to where they belong alphabetically.

All these changes I made because I need such a type of list for my own purposes and used the special phrases list as a starting point. If you want me to revert some of the changes, I can do so.

By the way: You probably already know this, but searching for churches selects every `amenity=place_of_worship`, i.e. also mosques, etc. The problem is that we would need to specify two tags (`religion=christian`) for the proper selection of Christian places of worship. This also makes it hard to search for mosques in places like Germany, where many of them are not in actual mosque buildings and are therefore not tagged as `building=mosque`.

**Comment by lonvia** [comment]
Well, this has broken the Nominatim special phrases import now. Would have been nice to discuss this beforehand.

There is two things in particular wrong with this list: a) the use of '*' b) the inclusion of secondary tags like memorial:type. I'll revert those changes. If you need terms for secondary tags you need to create your own list. Nominatim cannot process them and at the moment these cause even more stress for a mechanism that is already brittle enough as it is.

Note on the side: we really need to get this stuff out of the wiki and into some better curated format.

**Comment by Simon-Will** [comment]
I’m sorry that my edits broke the import. In the future, I will discuss things first.

**Comment by lonvia** [comment]
Closing in favour of #2180.
