### ISSUE TITLE
Search sometimes fails when including state NSW, Australia

### ISSUE THREAD

**Issue by andrew-cormick-dockery** [osm-search/Nominatim#2017]
There are a substantial number of addresses in New South Wales (NSW) Australia, which fail to return a result when the state is included in the search term.  It appears that the reason is that Nominatim is failing to recognise that a substantial number of addresses in NSW are actually in NSW.

For example, the search term `145 Majors Bay Road CONCORD NSW 2137` returns no results, but by dropping "NSW" from the search term, the correct result is returned: `145 Majors Bay Road CONCORD 2137`.

Looking at the details in the search result, it's clear that NSW doesn't appear as a derived administrative boundary (state) - see image.
![image](https://user-images.githubusercontent.com/17037045/96412007-264bca80-1235-11eb-8cfd-9ea6d38c9010.png)

Other examples of searches failing in the same way:

* 3 Belshaw Place BATEAU BAY NSW 2261
* 14 Merinda Avenue CHARMHAVEN NSW 2263
* 6 Mathews Street NORAH HEAD NSW 2263

Lots of NSW addresses work just fine, but a large number of them do not.  The failures do appear to be grouped in particular areas.

**Comment by lonvia** [comment]
I vaguely remember that the boundary of NSW was broken for a while. Any data that has been indexed while the boundary was broken would miss the state. Just to confirm that I've reindexed all of the Concord suburb and Major Bay Road now correctly shows up as being in NSW. I can't really reindex all of NSW. It's too expensive to do. We do plan a complete reimport of the database before the end of the year though. Everything should fix itself with that.

**Comment by andrew-cormick-dockery** [comment]
Success!  Thank you so much @lonvia !

We've been having a lot of trouble with the Central Coast area too - postcodes 2261, 2262, 2263 - if you could just do those ones as well that would be so helpful.

**Comment by andrew-cormick-dockery** [comment]
Oh and I just got another request for Parramatta - it would be so awesome to have these out of the way prior to the reimportation you mentioned.

**Comment by lonvia** [comment]
I've updated the Central Coast Council and Parramatta. Everything else has to wait until after the reimport, I'm afraid.

**Comment by andrew-cormick-dockery** [comment]
Thanks @lonvia I really appreciate it.
