### ISSUE TITLE
better house number match

### ISSUE THREAD

**Issue by freyfogle** [osm-search/Nominatim#2021]
A search for "Jana i Marii Prüfferów 7, Toruń, Poland"

https://nominatim.openstreetmap.org/ui/search.html?q=Jana+i+Marii+Pr%C3%BCffer%C3%B3w+7%2C+Toru%C5%84%2C+Poland

matches the street, but not the building because in OSM there is no building with that address. But there is a building with 4 nodes tagged with addr:housenumber = 7a (or 7b, 7c, 7d)
https://www.openstreetmap.org/node/2755205631#map=19/52.99363/18.60056

Perhaps that building could be found for this search?

**Comment by lonvia** [comment]
That falls under the general heading of 'fuzzy search'. We also have trouble with space, hyphens etc. in the housenumbers.

**Comment by fxedel** [comment]
Agree. Housenumbers with suffix are sometimes entered without space (like [Fuchsweg 53a](https://www.openstreetmap.org/way/1017327866)) or with a space (like [Fuchsweg 52 a](https://www.openstreetmap.org/way/944576481)). As you don't know whether it's stored in OSM with or without space, you have to search for both variants.

A possible fix in Nominatim could be to store housenumbers always without space and stripping spaces from search input. I don't think spaces would ever be used to distinguish different addresses, so it'll probably always be fine to remove spaces.

**Comment by lonvia** [comment]
Fixed with #2621.
