### ISSUE TITLE
The Country Serbia is not returned 

### ISSUE THREAD

**Issue by LeCoupa** [osm-search/Nominatim#2023]
Just to notify you that it seems like the Serbia country should be returned as the first position for the query below? :)

https://nominatim.openstreetmap.org/search/?q=Serbia&accept-language=en&addressdetails=1&email=julien.le.coupanec@gmail.com&format=json&limit=1

**Comment by mtmail** [comment]
https://nominatim.openstreetmap.org/search/?q=Serbia&accept-language=en&addressdetails=1&pretty=1&format=jsonv2&limit=1 returns https://www.openstreetmap.org/relation/9088937 (https://www.wikidata.org/wiki/Q403) which seems to be best result.

**Comment by lonvia** [comment]
The `boundary=claimed_administrative` confuses Nominatim. https://www.openstreetmap.org/relation/1741311 should come first.
