### ISSUE TITLE
Can I import data more than one time?

### ISSUE THREAD

**Issue by shinyke** [osm-search/Nominatim#2026]
As document in [nominatim doc](https://nominatim.org/release-docs/develop/admin/Import/), import data and setup database is merge in one command.

I import data of contry A when setup database, and then I try to import country B's data.  But finally it do not work, I can only search country B in nominatim API after that.

My operation:
1. import and setup database:
./src/build/utils/setup.php --osm-file /data/gcc-states-latest.osm.pbf --import-data --setup-db --create-functions --create-tables --create-partition-tables --create-partition-functions --import-wikipedia-articles --load-data  --index --create-search-indices  --create-country-names --threads 4
(same as --all, but I create database myself.)
2. import another contry's data:
./src/build/utils/setup.php --osm-file /data/afghanistan-latest.osm.pbf --import-data --setup-db --create-functions --create-tables --create-partition-tables --create-partition-functions --import-wikipedia-articles --load-data  --index   --threads 4
3. test in API. Found that it can only search afghanistan's data.

Can you have any suggestion for this problem? Whether the operation is not allowed by Nominatim?

**Comment by lonvia** [comment]
utils/setup.php always deletes the existing data. Please see https://nominatim.org/release-docs/latest/admin/Advanced-Installations/#importing-multiple-regions  for importing multiple extracts. Note that it is still strongly recommended to merge the pb files _before_  importing them into Nominatim.
