### ISSUE TITLE
Different result in local nominatim instance and official instance

### ISSUE THREAD

**Issue by bartoliniii** [osm-search/Nominatim#2028]
Whenever we build a database for Poland based on pbf file downloaded from https://download.geofabrik.de/ we get different result for villages - in local nominatim instance and the official instance.

I marked the address entry on an attached screenshot that is problematic one - it is present on the official site but not in our local instance. The problem occurs for many villages (in Poland).

We tried 3.4.2 and "master" version - with the same result.
We didn't use any special configuration to build database.

Here are the screenshots:
![nominatim_official](https://user-images.githubusercontent.com/14015142/97275843-bd68e180-1836-11eb-801d-f480248b4bf9.png)
![nominatim_local](https://user-images.githubusercontent.com/14015142/97275850-be9a0e80-1836-11eb-9267-30ef8a245f77.png)

What can be the cause of the problem?
Is there any known issue?
Ca be a problem with pbf data source?
Where can I find what version of nominatim is deployed to official site? Master looks differently so I guess it is oldest version. Am I wrong?

Thanks for any help or idea what can we check!

**Comment by lonvia** [comment]
I've answered the question on the mailing list now. As a general hint, it is not a good idea to ask questions on many communication channels. It puts the brains of the maintainers into a dead lock trying to decide where to answer. ;)

**Comment by bartoliniii** [comment]
Hi Ionvia,
thanks for reply and sorry for problems!

I asked at the mailing list at first, but after posting question here I had canceled my question (I cannot enter and I have a message that I cannot cancel it again).
What should I do to see your reply on mailing list in that case :)?
Maybe finally we could move the discussion to this topic - your advice can be useful for other users?
