### ISSUE TITLE
There is something wrong in import and update multiple regions solution.

### ISSUE THREAD

**Issue by shinyke** [osm-search/Nominatim#2031]
Refer to document [Advanced-Installations](https://nominatim.org/release-docs/latest/admin/Advanced-Installations/#importing-multiple-regions), I found that:

1. For add more countries, the document said: 
![image](https://user-images.githubusercontent.com/5669026/97522550-f80b7f00-19da-11eb-84e4-34016cbda671.png)
But, run these command `${UPDATEFILE} --import-file ${UPDATEDIR}/tmp/combined.osm.pbf 2>&1`  will lead to lack of index for the import regions. Of cause if user execute `update_database.sh` after that, may reindex the data, but I think this shell `utils/import_multiple_regions.sh` need to work individually.
I have read the source code and maybe this command need to add `--index` option like that:
 `${UPDATEFILE} --import-file ${UPDATEDIR}/tmp/combined.osm.pbf  --index 2>&1`
It work for me.

2. The update_database.sh can only execute once
In these document [Update](https://nominatim.org/release-docs/latest/admin/Update/), we have a complete solution about one region continue update. For multiple regions, we need to execute `update_database.sh` to update.
However, I found that this shell can only work once cause it depend on `sequence.state` file. Can we have a continue update solution for multiple regions?

**Comment by lonvia** [comment]
1. yes, `--index` helps in that case.

2. The script can be executed many times. `pyosmium-get-changes` updates the sequence file, so that the next run picks up at the right position.
