### ISSUE TITLE
Reverse search returns area GB postcode instead of precise GB postcode when no house address returned

### ISSUE THREAD

**Issue by vhmoura** [osm-search/Nominatim#2040]
Hi,

I've been using nominatim for reverse geocoding and sometimes I notice that under few scenarios the result don't seem alright, it returns a "partial postcode".

For example, for this reverse 52.522990,-1.903316 zoom 17 returns a postcode B42

Searching for B42 in gb_postcodes, it does not exist. However, the correct postcode is there (B42 1ST)

Am I doing something wrong?

Many thanks
Vini

**Comment by mtmail** [comment]
[ I edited the title from "Reverser Geocoding" to make clear it's about GB postcodes ] The query: https://nominatim.openstreetmap.org/ui/reverse.html?format=html&lat=52.522990&lon=-1.903316&zoom=18

**Comment by lonvia** [comment]
This is a data issue from OSM. You need to search for 'B42' postcodes in OSM: https://overpass-turbo.eu/s/ZNH As a rule, postcodes mapped in OSM are preferred over those from the external gb_postcodes table.

**Comment by vhmoura** [comment]
> This is a data issue from OSM. You need to search for 'B42' postcodes in OSM: https://overpass-turbo.eu/s/ZNH As a rule, postcodes mapped in OSM are preferred over those from the external gb_postcodes table.

Hi Lonvia, thanks for your reply. What can I do to make sure gb_postcodes are used instead of OSM? If that is not possible or to tricky to change in the code, how can I update that  (an many others) postcodes that are not correct?

Cheers,
Vini

**Comment by lonvia** [comment]
> What can I do to make sure gb_postcodes are used instead of OSM?

If you have your own database, you can just not import postcodes from OSM. Remove the part about postcodes from the `import-*.style` that you use. Just be aware that this has an effect on all postcodes in all countries. It is not possible to selectively ignore postcodes in the UK.

> how can I update that (an many others) postcodes that are not correct?

You can fix postcodes in OSM directly. For more information see, https://www.openstreetmap.org/fixthemap The overpass-turbo tool mentioned above can help you find the OSM objects that are wrong.
