### ISSUE TITLE
Database server failed to load /srv/nominatim/build/module/nominatim.so module

### ISSUE THREAD

**Issue by toton6868** [osm-search/Nominatim#2042]
I am also getting a similar error for Ubuntu. 
```
2020-11-03 21:39:16 == module path: /srv/nominatim/build/module
2020-11-03 21:39:16 == Create DB
2020-11-03 21:39:16 == Setup DB
Postgres version found: 12
Postgis version found: 2.5
PHP Fatal error:  Uncaught Nominatim\DatabaseError: [500]: Database server failed to load /srv/nominatim/build/module/nominatim.so module

  thrown in /srv/nominatim/Nominatim-3.5.2/lib/DB.php on line 61
```
I am following [this](https://nominatim.org/release-docs/latest/appendix/Install-on-Ubuntu-18/) documentation.

I am using **Postgresql 12** and **PostGIS 2.5**. I am running the Apache server on the `8081` port.

After every prerequisite installation, I have created nominatim user. After that I have changed the user to nominatim by `sudo su - nominatim` and `make` nominatim in `/srv/nominatim` directory. The building was errorless. But when I am trying to run `./utils/setup.php --osm-file /srv/nominatim/Nominatim-3.5.2/data/map.osm.pbf --all 2>&1 | tee setup.log` command it is returning the above error. The `nominatim.so` file permission is as follows
```
-rwxrwxrwx 1 nominatim nominatim 308800 Nov  3 21:03 /srv/nominatim/build/module/nominatim.so
```
even i have tried with `chmod a+x /srv/nominatim` and `chmod a+x /srv` but there is no luck.

**Comment by mtmail** [comment]
Thanks for providing the exact version numbers.

The old github issue you found was CentOS and I think the third that went unresolved (users gave up, no longer replied or switched to use Ubuntu). We were unable to reproduce the issues either inside Vagrant or setting our own servers. There's always something different on the user's system we can't get a handle on (remote debugging). That said we only see the reports if something doesn't work, other users install it just fine on CentOS.

Does the postgresql logfiles give any more clues? E.g. that a directory can't be accessed, or file not found?

Is postgresql installed locally (not on another computer or the cloud)?

I'm no longer sure giving everybody will write permissions (`chmod a+x`) is the solution. Why would the database load a library that any users can write/overwrite? The permissions I see after a fresh installation are:

```
/srv/nominatim/Nominatim/build/module$ ls -la
drwxrwxr-x  3 nominatim nominatim   4096 Oct  2 14:18 .
drwxrwxr-x 10 nominatim nominatim   4096 Oct  3 15:43 ..
drwxrwxr-x  3 nominatim nominatim   4096 Oct  2 14:16 CMakeFiles
-rw-rw-r--  1 nominatim nominatim   1121 Oct  2 14:16 cmake_install.cmake
-rw-rw-r--  1 nominatim nominatim    281 Oct  2 14:16 CTestTestfile.cmake
-rw-rw-r--  1 nominatim nominatim   6886 Oct  2 14:16 Makefile
-rw-rw-r--  1 nominatim nominatim 476476 Oct  2 14:18 nominatim.bc
-rw-rw-r--  1 nominatim nominatim 491192 Oct  2 14:18 nominatim.o
-rwxr-xr-x  1 nominatim nominatim 308792 Oct  2 14:18 nominatim.so
```

`/srv/nominatim/Nominatim/build` is `drwxrwxr-x 10 nominatim nominatim`
`/srv/nominatim/Nominatim/` is `drwxrwxr-x 10 nominatim nominatim`
`/srv/nominatim/` is `drwxr-xr-x  9 nominatim nominatim`
`/srv/` is `drwxr-xr-x  3 root      root`

**Comment by toton6868** [comment]
Thanks for the quick reply
Here are my permissions.
`/srv/`
```
drwxr-xr-x    3 root root       4096 Nov  3 20:45 srv
```
`/srv/nominatim/`
```
drwxr-xr-x 5 nominatim nominatim 4096 Nov  3 21:41 nominatim
```
In the `/srv/nominatim` folder I have `build` folder and `Nominatim-3.5.2` folder separately. 
```
drwxrwxr-x 10 nominatim nominatim     4096 Nov  3 21:16 build
drwxr-xr-x 17 nominatim nominatim     4096 Sep 25 09:03 Nominatim-3.5.2
-rwxrwxr-x  1 nominatim nominatim 49286001 Sep 25 09:13 Nominatim-3.5.2.tar.bz2
```
In the `/srv/nominatiom/build` folder
```
-rwxrwxr-x  1 nominatim nominatim 26203 Nov  3 20:58 CMakeCache.txt
drwxrwxr-x 33 nominatim nominatim  4096 Nov  3 21:03 CMakeFiles
-rwxrwxr-x  1 nominatim nominatim  1777 Nov  3 20:58 cmake_install.cmake
-rwxrwxr-x  1 nominatim nominatim 30153 Nov  3 20:58 compile_commands.json
-rwxrwxr-x  1 nominatim nominatim  1828 Nov  3 20:58 CTestTestfile.cmake
-rwxr-xr-x  1 nominatim nominatim  2540 Nov  3 20:58 DartConfiguration.tcl
drwxrwxr-x  5 nominatim nominatim  4096 Nov  3 20:58 docs
-rwxrwxr-x  1 nominatim nominatim 21117 Nov  3 20:58 Makefile
-rwxr-xr-x  1 nominatim nominatim  1920 Nov  3 20:58 mkdocs.yml
drwxrwxr-x  3 nominatim nominatim  4096 Nov  3 21:03 module
drwxrwxr-x  4 nominatim nominatim  4096 Nov  3 21:03 osm2pgsql
drwxrwxr-x  2 nominatim nominatim  4096 Nov  3 21:33 settings
-rwxrwxr-x  1 nominatim nominatim   387 Nov  3 21:39 setup.log
drwxrwxr-x  3 nominatim nominatim  4096 Nov  3 20:58 Testing
drwxrwxr-x  2 nominatim nominatim  4096 Nov  3 20:58 utils
drwxrwxr-x  2 nominatim nominatim  4096 Nov  3 20:58 website
```
In the `/srv/nominatiom/build/module` folder
```
drwxrwxr-x 3 nominatim nominatim   4096 Nov  3 20:58 CMakeFiles
-rwxrwxr-x 1 nominatim nominatim   1127 Nov  3 20:58 cmake_install.cmake
-rwxrwxr-x 1 nominatim nominatim    277 Nov  3 20:58 CTestTestfile.cmake
-rwxrwxr-x 1 nominatim nominatim   6762 Nov  3 20:58 Makefile
-rwxrwxr-x 1 nominatim nominatim 434188 Nov  3 21:03 nominatim.bc
-rwxrwxr-x 1 nominatim nominatim 491200 Nov  3 21:03 nominatim.o
-rwxrwxrwx 1 nominatim nominatim 308800 Nov  3 21:03 nominatim.so
```
In the /srv/nominatim/Nominatim-3.5.2` folder
```
-rwxr-xr-x 1 nominatim nominatim   248 Sep 25 09:02 AUTHORS
-rwxr-xr-x 1 nominatim nominatim 10679 Sep 25 09:03 ChangeLog
drwxr-xr-x 2 nominatim nominatim  4096 Sep 25 09:03 cmake
-rwxr-xr-x 1 nominatim nominatim  6286 Sep 25 09:03 CMakeLists.txt
-rwxr-xr-x 1 nominatim nominatim  3991 Sep 25 09:02 CONTRIBUTING.md
-rwxr-xr-x 1 nominatim nominatim 18092 Sep 25 09:02 COPYING
drwxr-xr-x 2 nominatim nominatim  4096 Nov  3 21:13 data
drwxr-xr-x 6 nominatim nominatim  4096 Sep 25 09:03 data-sources
drwxr-xr-x 6 nominatim nominatim  4096 Sep 25 09:03 docs
drwxr-xr-x 4 nominatim nominatim  4096 Nov  3 21:41 lib
drwxr-xr-x 2 nominatim nominatim  4096 Sep 25 09:02 module
drwxr-xr-x 2 nominatim nominatim  4096 Sep 25 09:02 munin
drwxr-xr-x 3 nominatim nominatim  4096 Sep 25 09:03 nominatim
drwxr-xr-x 8 nominatim nominatim  4096 Sep 25 09:03 osm2pgsql
-rwxr-xr-x 1 nominatim nominatim  5356 Sep 25 09:02 phpcs.xml
-rwxr-xr-x 1 nominatim nominatim  2407 Sep 25 09:02 README.md
drwxr-xr-x 2 nominatim nominatim  4096 Sep 25 09:03 settings
drwxr-xr-x 3 nominatim nominatim  4096 Sep 25 09:03 sql
drwxr-xr-x 6 nominatim nominatim  4096 Sep 25 09:03 test
drwxr-xr-x 2 nominatim nominatim  4096 Sep 25 09:03 utils
drwxr-xr-x 2 nominatim nominatim  4096 Sep 25 09:03 vagrant
-rwxr-xr-x 1 nominatim nominatim  2568 Sep 25 09:03 Vagrantfile
-rwxr-xr-x 1 nominatim nominatim  5970 Sep 25 09:03 VAGRANT.md
drwxr-xr-x 5 nominatim nominatim  4096 Sep 25 09:02 website
```
I think the problem is in postgres version conflict. Thanks for postgresql log tips. I found
```
2020-11-04 05:59:43.014 UTC [3470187] nominatim@nominatim FATAL:  database "nominatim" does not exist
2020-11-04 05:59:44.918 UTC [3470191] nominatim@nominatim ERROR:  incompatible library "/srv/nominatim/build/module/nominatim.so": **version mismatch**
2020-11-04 05:59:44.918 UTC [3470191] nominatim@nominatim DETAIL:  Server is version 12, library is version 13.
2020-11-04 05:59:44.918 UTC [3470191] nominatim@nominatim STATEMENT:  CREATE FUNCTION nominatim_test_import_func(text) RETURNS text AS '/srv/nominatim/build/module/nominatim.so', 'transliteration' LANGUAGE c IMMUTABLE STRICT;DROP FUNCTION nominatim_test_import_func(text);
```
Then I tried to rebuild again from scratch. after `cmake` I got the following output. but I am using Postgrsql 12 engine. I think the problem was the installing `postgresql-contrib-13` mistakenly at the first time. After that I have `sudo apt-get --purge remove postgresql-contrib-13` and installed postgresql-contrib-12.. But still it is showing
``` 
-- Found PostgreSQL: /usr/lib/x86_64-linux-gnu/libpq.so **(found version "13.0")** 
```
I know it is not related to nominatim but it would be a great help if you can help.
Thanks again for the quick reply.

**Comment by lonvia** [comment]
It's the package `postgresql-server-dev-*` which is causing issues here. Make sure you have installed the one matching your Postgresql server version and only that. If you are on a fresh server and still have a choice, I strongly suggest to switch everything to Postgresql 13.

**Comment by lonvia** [comment]
I've tried with the latest Ubuntu-20.04 now and it looks like there is still only Postgresql 12 present. So these problems should only show up when the extra Postgresql apt repositories are enabled. Please correct me if I'm wrong.
