### ISSUE TITLE
Cannot get png-s for Openlayers-ext widget

### ISSUE THREAD

**Issue by gregordavid** [osm-search/Nominatim#2043]
'https://nominatim.openstreetmap.org/ui/images.html'  is missing

**Comment by lonvia** [comment]
Shouldn't you rather be opening a report with openlayers-ext if pngs are missing in their widgets?

**Comment by gregordavid** [comment]
I tought these links to the icons are in your database, and also this db contains these png-s. 
Sorry if this is not your case.
example:
feature.icon = https://nominatim.openstreetmap.org/images/mapicons/poi_boundary_administrative.p.20.png

**Comment by lonvia** [comment]
The icons have moved to https://nominatim.openstreetmap.org/ui/mapicons/. This is correctly reported by our API, e.g. see the icon field in https://nominatim.openstreetmap.org/search.php?q=london&format=json.

If there is an API response that returns an invalid link, please provide an example. If openlayers-ext uses hardcoded links to these icons, then you should indeed report this to them.

**Comment by lonvia** [comment]
For reference, @gregordavid  has opened with ol-ext: https://github.com/Viglino/ol-ext/issues/528 Thanks for that. Lets see what they say.
