### ISSUE TITLE
Why the word "Brucehaven" is changed to "Bruceaven" in search_name table?

### ISSUE THREAD

**Issue by johnnyzhangzhao** [osm-search/Nominatim#2048]
Hi guys, 

Seems like the word_tokens of address "Brucehaven Drive, Riverview, FL, 33569" are changed in search_name table,  the name_vector is "bruceaven", " bruceaven dr" and "bruceaven dr",  but why it's not  "brucehaven", " brucehaven dr" and "brucehaven dr", I searched "_Nominatim/module/tokenstringreplacements.inc_" file and was thinking that if there is any replacement there, but no, not included, anybody knows the reason?  

Ps: I tracked the debug output at https://nominatim.openstreetmap.org/search.php, seems the change takes place between "Final query phrases" and "Tokenization".

Thanks,
Johnny

**Comment by mtmail** [comment]
I think it's `str_replace(buffer, &len, &changes, "eh", 2, "e", 1, 0);` in https://github.com/osm-search/Nominatim/blob/master/module/nominatim.c#L275

**Comment by johnnyzhangzhao** [comment]
Thanks, mtmail, I didn't notice this before, I will check it out later.
