### ISSUE TITLE
Reverse vs Search

### ISSUE THREAD

**Issue by vhmoura** [osm-search/Nominatim#2050]
Hi there,

I am primarily running GB and Ireland maps where the focus is on getting the address details from a particular latitude and longitude. 
My requests where done like this:
"reverse.php?format=json&lat=51.486513&lon=-0.150921&addressdetails=1&extratags=1&zoom=17"

The majority of the requests are sub 50ms. This particular request sits around 200ms (and so many others).  
Now, when I change this to a search, I get some very fast results (around 100ms and below)
"search.php?format=json&addressdetails=1&extratags=1&q=51.486513 -0.150921"

So, what is the main difference between the two? Bear in mind the database is updated overnight and ANALYSE is run to compute statistics. 

Many thanks in advance for any response.

Cheers,
Vini

**Comment by lonvia** [comment]
These two requests end up exactly in the same code path, with the tiny exception that the search request sets the zoom level to 18.

When doing your timing tests, have you usually run the reverse first, found it slow and then tried the same with search? In that case reverse would have been running on cold caches while the subsequent search request found all the data it needed already in RAM. That certainly would explain the difference.

**Comment by lonvia** [comment]
I stand corrected. There is a difference. `reverse` also looks into the interpolation table while `search` does not. Try to change `true` to `false` in https://github.com/osm-search/Nominatim/blob/f89e71a861e1c447de63658a334383640cb831ea/lib/ReverseGeocode.php#L234 and see if that resolves your performance differences.

**Comment by vhmoura** [comment]
Hi Sarah,

Thanks for your input.

Allow me to detail a bit more what I am trying to achieve.

So my app is primarily interested in particular details of a street based on lat/lon.


The reverse call will always run with the same set of parameters: "reverse.php?format=json&lat=51.486513&lon=-0.150921&addressdetails=1&extratags=1&zoom=17"
Only thing that changes is lat/lon. This gives me the most accurate position where a speed data is available.

Running this request at high level volumes, at some point it reaches a "pick" where the whole postgres/apache struggles with 100% cpu, then it goes down a bit and up again and so on after 5-8 minutes of heavy load. I've done extensive tests and optimization on my server (32gb memory) and I can't think of what else to change (it is apache-prefork). The queries at this point are taking anywhere from 2-10 seconds to respond (although the majority responds just fine). However, when running only search (literally just changing the queries), search runs always around 50ms average and the load to postgres/apache is about 30% during heavy load.

Search also only changes lat/lon and doesn't do reverse query: "search.php?format=json&addressdetails=1&extratags=1&q=51.486513 -0.150921"

The issue with search is that not always it will return extra tag for road speed. Any reason for that?

Please see example below:

search.php?format=json&addressdetails=1&extratags=1&q=51.503596 -3.192717
reverse.php?format=json&addressdetails=1&extratags=1&zoom=17&lat=51.503596&lon=-3.192717

Another interesting fact is search returns a correct postcode while reverse doesn't. 

Regarding interpolation, I don't think that will get executed because zoom is set to 17, correct?

Any help appreciated.

Many thanks
Vini

**Comment by lonvia** [comment]
When you have a high volume of requests, you should switch to nginx/php-fpm for serving the API. I've seen a similar behaviour as you describe on our production machines and eventually narrowed it down to apache not able to handle the load.

**Comment by vhmoura** [comment]
Thanks Sarah, that is what I initially considered. I tried to follow the documentation to use nginx but couldn't get it to work. I will give it another try and let you know. Many thanks for all your help and support. It is amazing what you guys are doing.

**Comment by vhmoura** [comment]
Hi Sarah,

Just a heads up. I ended up installing everything from scratch this time using nginx and indeed the difference is gigantic. 

Many thanks for your help. Closing this query.

Cheers,
Vini
