### ISSUE TITLE
forward search shouldnt fail when name of neighbourhood is added to query

### ISSUE THREAD

**Issue by freyfogle** [osm-search/Nominatim#2052]
Hi,

A search for "The Barbary, 16 Neal's Yard, London, United Kingdom" works perfectly, returning only the single correct result
https://nominatim.openstreetmap.org/ui/search.html?q=The+Barbary%2C+16+Neal%27s+Yard%2C+London%2C+United+Kingdom

the correct answer is this node:
https://www.openstreetmap.org/node/4348379097

A search for "The Barbary, 16 Neal's Yard, Seven Dials, London, United Kingdom"  however fails, returning no result at all.
"Seven Dials" is the name of the neighbourhood

There is a node with admin_level 15 (suburb) and the name "Seven Dials" about 100m from "The Barbary"
https://nominatim.openstreetmap.org/ui/details.html?osmtype=N&osmid=344093927&class=place

Is this a tagging issue (ie Seven Dials also needs to be defined as a relation) or a search algorithm issue?

thanks for your help

Ed

**Comment by lonvia** [comment]
Seven Dials is not mapped as a neighbourhood but as a `place=locality`. From what I read from the linked wikipedia article, that sounds about right. It is basically a named roundabout or square.

**Comment by freyfogle** [comment]
yes, you are correct, it is a roundabout. Having had an office in that area for many years, It is also how people refer to that area of London. It is not any sort of "official" neighbourhood, more like a landmark that describes the surrounding space. What would be the way to tag it so a search like that works?

https://en.wikipedia.org/wiki/Seven_Dials,_London
`"The term also refers informally to the area immediately surrounding."`

**Comment by lonvia** [comment]
Then possibly use `place=neighbourhood`. At least that's the one that would fit best imo. But eventually that is something you should make sure is agreed on within the local community.

Nominatim's stance with this is:
 * `place=locality` is not included in the search terms/address unless explicitly referred to in addr:place. That is because it is defined as an 'uninhabited place'.
 * place=town/borough/suburb/quarter/neighbourhood are applied in a fuzzy fashion when mapped as a place node: all that are close enough will be included in the search terms, so you'll find it when adding them to the search address. Only the closest one of each group is used in the displayed address.

**Comment by freyfogle** [comment]
thanks for clarifying, now I understand.

I worked there for 10+ years, feel quite confident this is inline with the local community (and indeed the question comes from a customer wondering why this search doesn't work). I guess the question is if there should be a node for the actual roundabout and then a relation for the neighbourhood. I will experiment. 

thanks again, closing

**Comment by freyfogle** [comment]
Just as an additional point - I guess we could consider this and example of the "landmark" way of referring to a location, that is quite common in many parts of the world. India for example. People frequently add local landmarks to a query on the assumption that the more information the better, and because that is the local way of referring to the area. It's then frustrating when the query fails, especially if the landmark itself actually exists in OSM. We see many searches like this. Just food for thought.

**Comment by lonvia** [comment]
A place node is probably not so bad here. It basically says: everything around the node is definitely part of this neighbourhood. The farther away we go, the more fuzzy the definition becomes if something belongs to it.

Searching by landmark is a completely different cattle of fish and I think it cannot be done without at least some support from the mappers to mark the places that are locally well-known and used as reference points. Famous examples here are reference points like 'the corner where the fireworks factory was that blew up in 1965'. In any case, we are still miles away from being able to do something like that in Nominatim. More simple stuff like fuzzy searching and leaving out unknown terms needs implementing first.
