### ISSUE TITLE
place:county node errors for Dane County, Wisconsin, United States

### ISSUE THREAD

**Issue by mikeglee** [osm-search/Nominatim#2053]
Potentially thousands of addresses in Dane County, Wisconsin https://www.openstreetmap.org/node/317007182 are misidentified as Walworth County https://www.openstreetmap.org/node/317007212

I first observed this error with this query: 
https://nominatim.openstreetmap.org/ui/reverse.html?format=html&lat=42.9341346999983&lon=-89.2380796999528&zoom=18

The county node error appears to be restricted to the southeast corner of Dane County, comprising several hundred square miles.

![Dane_County_not_Walworth_County](https://user-images.githubusercontent.com/74513342/99198725-1e157b00-2760-11eb-87f6-b0a81c3a0a4f.PNG)

**Comment by mtmail** [comment]
The Dane County relation (https://www.openstreetmap.org/relation/1799444) was unconnected in several places. All members (way) were there, but not ordered. There is also a duplicate it seems: https://www.openstreetmap.org/way/842213599 and https://www.openstreetmap.org/way/842213582 I removed one of them. One can't easily see such a problem on a map, as I said each member way existed, no gaps.

![image](https://user-images.githubusercontent.com/3727288/99199538-31e0d180-27a0-11eb-8360-e9b79ff6f301.png)

**Comment by lonvia** [comment]
The duplicated way was indeed the problem here. The ways don't need to be ordered, although it helps enormously to spot connection issues.

Closing as data error.
