### ISSUE TITLE
Lose boundary:administrative(state) Sankt-Peterburg and place:city Saint Petersburg after last update

### ISSUE THREAD

**Issue by EvgenyEK** [osm-search/Nominatim#2057]
Before update:
![outdated](https://user-images.githubusercontent.com/43876596/99401050-8b184480-2909-11eb-91bd-1ed708bb3191.jpg)

After update:
![updated](https://user-images.githubusercontent.com/43876596/99401097-9a978d80-2909-11eb-9100-3fdb5e32574f.jpg)

after 2020/11/13 18:01 GMT  update where lose boundary:administrative
after 2020/11/14 11:51 GMT we lose city at all
now we using old version and disable updates
call format: osmtype=W&osmid=364509520&class=amenity
how to fix it ?

WBR, Evgeny Kuleshov.

**Comment by lonvia** [comment]
Please add the following information:

* is this the osm.org server or your own? If it is your own, what version of Nominatim does it run?
* What did you update, only the data or also the software? If the software, from what version to which version?
* What does the details page for the two St. Peterburg relations say (osmtype=R&osmid=337422&class=boundary and osmtype=R&osmid=421007&class=place)?

**Comment by EvgenyEK** [comment]
1. This is my own server with Nominatim version 3.5.2
2. Update only data, this is fresh version of Nominatim 3.5.2 servers, CentOS 8 and PostgreSQL 12

3. osmtype=R&osmid=337422&class=boundary
![Clipboard01](https://user-images.githubusercontent.com/43876596/99657835-7c07d280-2a80-11eb-800c-0c2e8de4febb.jpg)
osmtype=R&osmid=421007&class=place
![Clipboard02](https://user-images.githubusercontent.com/43876596/99657889-8de97580-2a80-11eb-987c-17b7bda1aa68.jpg)

**Comment by lonvia** [comment]
These relations are present on all our servers. So its unlikely to be a software bug. It might be a data issue that has been fixed in the meantime but that it hard to tell after the fact. More likely is that something went wrong with the updates on your server. Please check your system logs. Possible causes to look out for: You missed an osc and therefore miss now data. You use a flatnode file and that is corrupted.

**Comment by EvgenyEK** [comment]
May be you right, but this trouble manifested on two **independent** servers in **absolutely same** situation
Ok, i just re-import world again
But i suspect that something be wrong with updates.
