### ISSUE TITLE
Indexing status fails after import

### ISSUE THREAD

**Issue by msullenb** [osm-search/Nominatim#2062]
Just performed a fresh install of Nominatim 3.5.2 on Ubuntu 20.04 with PostgreSQL 12 and did a full planet import. The import completed without any warnings. However, when I verified the import with check_import_finished script I received the following:
```
./utils/check_import_finished.php
Checking database got created ... OK
Checking nominatim.so module installed ... OK
Checking place table ... OK
Checking indexing status ... Failed
    The indexing didn't finish. There is still 30 places. See the
    question 'Can a stopped/killed import process be resumed?' in the
    troubleshooting guide.
```
I verified this in postgresql:
```
SELECT count(*) from placex where indexed_status=1;
 count 
-------
    30
(1 row)
```
I ran the index step again using:

`./utils/setup.php --index --index-noanalyse`

Now the check_import_finished script reports 18 places still need indexed and no matter how many times I run the index step, the same 18 places never get indexed. These 18 places are scattered between Rank 26, 27 and 30. I ran the index step directly:
 
`'/srv/nominatim/Nominatim-3.5.2/nominatim/nominatim.py' --database nominatim --port 5432 -t 1 -r 26 -R 30`
 
And received the following output:
```
WARNING: Starting indexing rank (26 to 30) using 1 threads
WARNING: Starting rank 26
WARNING: Done 8/8 in 0 @ 1598.402 per second - FINISHED rank 26
 
WARNING: Starting rank 27
WARNING: Done 1/1 in 0 @ 1926.782 per second - FINISHED rank 27
 
WARNING: Starting rank 28
WARNING: Done 0/0 in 0 @ 0.000 per second - FINISHED rank 28
 
WARNING: Starting rank 29
WARNING: Done 0/0 in 0 @ 0.000 per second - FINISHED rank 29
 
WARNING: Starting interpolation lines (location_property_osmline)
WARNING: Done 0/0 in 0 @ 0.000 per second - FINISHED interpolation lines (location_property_osmline)
 
WARNING: Starting rank 30
WARNING: Done 9/9 in 0 @ 5917.160 per second - FINISHED rank 30
```
Since there was only one place in Rank 27, I ran this again doing only Rank 27 to capture the postgresql log data:
```
statement:  UPDATE pg_settings SET setting = -1 WHERE name = 'jit_above_cost';
                        UPDATE pg_settings SET setting = 0
                           WHERE name = 'max_parallel_workers_per_gather';
statement: BEGIN
statement: SELECT count(*) FROM placex
                          WHERE rank_search = 27 and indexed_status > 0
 
statement: DECLARE "places" CURSOR WITHOUT HOLD FOR SELECT place_id FROM placex
                          WHERE indexed_status > 0 and rank_search = 27
                          ORDER BY geometry_sector
statement: FETCH FORWARD 20 FROM "places"
statement: FETCH FORWARD 20 FROM "places"
statement: CLOSE "places"
statement: UPDATE placex SET indexed_status = 0 WHERE place_id IN (204869206)
```
So, no errors, per se, but the indexing isn't occurring…or if it is occurring it isn't able to update placex with the indexed_status. I ran the last statement myself in postgresql and it simply returns UPDATE 0.
 
When I run the query:
```
SELECT place_id
FROM placex
WHERE indexed_status > 0 and rank_search = 27;
```
I am returned 204869206, but when I run:
```
SELECT *
FROM placex
WHERE place_id = 204869206;
```
I do not get any rows returned. The same goes for any of the other place_ids that didn't get indexed.
 
Not sure what the next step is from here. Hoping there might be a simple fix short of re-importing the entire planet and crossing my fingers.

**Comment by lonvia** [comment]
This sounds like a corrupted index. Can you run `REINDEX INDEX idx_placex_pendingsector` and if that doesn't help `REINDEX INDEX idx_place_id`.

**Comment by msullenb** [comment]
That did the trick. I had to REINDEX both indices.

**Comment by lonvia** [comment]
Glad it worked. Unfortunately it also means that there is a real chance that more parts of your database are corrupted. Check your disks and RAM to make sure you don't have faulty hardware. Then you might want to do a `REINDEX` on the entire DB to make sure that any other broken indexes get fixed. It will take a couple of hours to rebuild them all but might still be worth it because, as you noticed, Postgresql often won't tell you when an index is broken. You just get strange results.

In any case, closing here, as this is more of a system administration problem than a problem with Nominatim.
