### ISSUE TITLE
Lookup endpoint unable to find osm_id returned by reverse endpoint

### ISSUE THREAD

**Issue by cprates** [osm-search/Nominatim#2063]
Hi,

I recently came across this issue where if I use the /reverse endpoint to resolve lat/lon and then use the returned osm_id with the /lookup endpoint, it fails to find it. But, if I use the /details endpoint Nominatim can find it, but shows a different osm_id in the results.
I would expect that if /reverse returns an osm_id, /lookup would be able to resolve it.

As an example, resolving lat/lon:
https://nominatim.openstreetmap.org/reverse?lat=36.7420284&lon=-3.8850681&format=jsonv2
Returns the following details with osm_id `37081567`:
```json
{
  "place_id": 4091153,
  "licence": "Data © OpenStreetMap contributors, ODbL 1.0. https://osm.org/copyright",
  "osm_type": "way",
  "osm_id": 37081567,
  "lat": "36.7419922",
  "lon": "-3.8854769",
  "place_rank": 30,
  "category": "place",
  "type": "house",
  "importance": -0.1,
  "addresstype": "place",
  "name": null,
  "display_name": "20, Calle Mérida, Urbanización Casa Blanca, Maro, Nerja, La Axarquía, Malaga, Andalusia, NERJA, Spain",
  "address": {
    "house_number": "20",
    "road": "Calle Mérida",
    "neighbourhood": "Urbanización Casa Blanca",
    "suburb": "Maro",
    "town": "Nerja",
    "county": "La Axarquía",
    "state": "Andalusia",
    "postcode": "NERJA",
    "country": "Spain",
    "country_code": "es"
  },
  "boundingbox": [
    "36.7419422",
    "36.7420422",
    "-3.8855269",
    "-3.8854269"
  ]
}
```

Now if I take the returned osm_id and use the /lookup endpoint, no results are returned
https://nominatim.openstreetmap.org/lookup?osm_ids=W37081567&format=jsonv2

The same happens if I use /reverse with the osm_id
https://nominatim.openstreetmap.org/reverse?osm_type=W&osm_id=37081567&format=jsonv2

But when using /detail Nominatim returns details but with a different osm_id `27735892`.
https://nominatim.openstreetmap.org/details?osmtype=W&osmid=37081567&format=json
```json
{
  "place_id": 93153274,
  "parent_place_id": 10909533,
  "osm_type": "W",
  "osm_id": 27735892,
  "category": "highway",
  "type": "residential",
  "admin_level": 15,
  "localname": "Calle Mérida",
  "names": {
    "name": "Calle Mérida"
  },
  "addresstags": [],
  "housenumber": null,
  "calculated_postcode": "NERJA",
  "country_code": "es",
  "indexed_date": "2020-01-11T08:39:34+00:00",
  "importance": 0,
  "calculated_importance": 0.09999999999999998,
  "extratags": {
    "lit": "yes",
    "oneway": "yes",
    "surface": "paved"
  },
  "calculated_wikipedia": null,
  "rank_address": 26,
  "rank_search": 26,
  "isarea": false,
  "centroid": {
    "type": "Point",
    "coordinates": [
      -3.8850681,
      36.7420284
    ]
  },
  "geometry": {
    "type": "Point",
    "coordinates": [
      -3.8850681,
      36.7420284
    ]
  }
}
```

I few more osm ids I found with the same behaviour
* W37081567
* W335425307
* W309949426
* W40942080
* W513891536
* W468510369

Any thoughts?

**Comment by lonvia** [comment]
That's address interpolations which aren't supported by the `/lookup` endpoint.

Side question: why would you put a reverse result into the lookup endpoint? They return exactly the same information.

**Comment by cprates** [comment]
> That's address interpolations which aren't supported by the `/lookup` endpoint.
Does this mean that the /lookup is expected to not be able to resolve all osm_ids?



> Side question: why would you put a reverse result into the lookup endpoint? They return exactly the same information.
I need this flow for backwards compatibility reasons. But in this case that doesn't seem to happen, /reverse return details, but /lookup doesn't:
https://nominatim.openstreetmap.org/reverse?lat=36.7420284&lon=-3.8850681&format=jsonv2
https://nominatim.openstreetmap.org/lookup?osm_ids=W37081567&format=jsonv2

**Comment by lonvia** [comment]
`/lookup` only ever gets you a result for OSM object that are indexed by Nominatim. A lot of objects are dropped because they are not interesting for search.

There will never be a guarantee that `/reverse` and `/lookup` will worked together in the way you want it. In the same way there is no guarantee that the `display_name` response given by any endpoint can be fed back directly into `/search`.

**Comment by cprates** [comment]
@lonvia thanks for the reply.

Would I be able to use the place_id instead in that same way? I mean query /lookup with the place_id returned by /reverse (I'm aware that the place_id is generated every time the data is loaded)? Or are these details documented somewhere?
