### ISSUE TITLE
Make search less strict about Polish rank title "generał"

### ISSUE THREAD

**Issue by rmilecki** [osm-search/Nominatim#2066]
I noticed this problem while searching for the phase `Osiedle generała Władysława Sikorskiego 7, 32-650 Kęty`. In Polish language "generał" is an army rank title. Word "generała" is just one of declension forms.

People often skip that word when searching for an address.

Could you make search engine less restrictive so it can return then same address for the `Osiedle generała Władysława Sikorskiego 7, 32-650 Kęty` query?

**Comment by rmilecki** [comment]
One more related request. A common abbreviation for "generał" and "generała" is "gen.".

Could you make search engine also deal with:

- `Osiedle gen Władysława Sikorskiego 7, 32-650 Kęty`
- `Osiedle gen. Władysława Sikorskiego 7, 32-650 Kęty`

**Comment by lonvia** [comment]
Please add abbreviations like that to https://wiki.openstreetmap.org/wiki/Name_finder:Abbreviations. Nominatim needs some fundamental redesign to improve the abbreviation handling for cases like this. But once this is done, the wiki page will really come in handy.
