### ISSUE TITLE
Error importing data

### ISSUE THREAD

**Issue by vhmoura** [osm-search/Nominatim#2067]
Hi,

Just run ./utils/setup.php --osm-file ../Nominatim/data/britain-and-ireland-latest.osm.pbf --all --reverse-only --osm2pgsql-cache 12000 2>&1 | tee setup.log

but got the following error with latest git pull

WARNING: Done 158843/158843 in 243 @ 651.843 per second - FINISHED rank 27

WARNING: Starting rank 28 (using batch size 1)
WARNING: Done 0/0 in 0 @ 0.000 per second - FINISHED rank 28

WARNING: Starting rank 29 (using batch size 1)
WARNING: Done 0/0 in 0 @ 0.000 per second - FINISHED rank 29

WARNING: Starting rank 0 (using batch size 1)
INFO: Done 100 in 6 @ 15.730 per second - rank 0 ETA (seconds): 35445.68
Traceback (most recent call last):
  File "/srv/nominatim/Nominatim/nominatim/nominatim.py", line 270, in <module>
    Indexer(options).index_by_rank()
  File "/srv/nominatim/Nominatim/nominatim/nominatim.py", line 139, in index_by_rank
    self.index(RankRunner(0))
  File "/srv/nominatim/Nominatim/nominatim/nominatim.py", line 173, in index
    thread = next(next_thread)
  File "/srv/nominatim/Nominatim/nominatim/nominatim.py", line 194, in find_free_thread
    if thread.is_done():
  File "/srv/nominatim/Nominatim/nominatim/indexer/db.py", line 99, in is_done
    if self.conn.poll() == psycopg2.extensions.POLL_OK:
psycopg2.errors.UndefinedTable: relation "search_name" does not exist
LINE 2: ...                                             FROM search_nam...
                                                             ^
QUERY:  SELECT s.name_vector, s.nameaddress_vector
                                                       FROM search_name s
    WHERE s.place_id = parent_place_id
CONTEXT:  PL/pgSQL function create_poi_search_terms(bigint,smallint,bigint,hstore,text,text,integer[],geometry) line 13 at SQL statement
SQL statement "SELECT *                                                FROM create_poi_search_terms(NEW.place_id,
                                       NEW.partition, NEW.parent_place_id,
                                       inherited_address || NEW.address,
                                       NEW.country_code, NEW.housenumber,
                                       name_vector, NEW.centroid)"
PL/pgSQL function placex_update() line 316 at SQL statement

ERROR: error status 1 running nominatim!
string(33) "error status 1 running nominatim!"

Anything wrong with the way it was imported?

Thanks
Vini

**Comment by lonvia** [comment]
Accidental break with the latest changes. I'm going to add the reverse-only mode to CI to avoid these kind of issues in the future.
