### ISSUE TITLE
Non functional, but enabled, "details" button

### ISSUE THREAD

**Issue by simonpoole** [osm-search/Nominatim#2072]
Searching for NR20 5NF on nominatim.openstreetmap.org will show a result with a "details" button that can be clicked, but doesn't do anything.

**Comment by otbutz** [comment]
Looks like this doesn't work for any postecodes

**Comment by lonvia** [comment]
Indeed. And there is even an issue for that marked with 'Help wanted'.

Duplicate of #1671.
