### ISSUE TITLE
Wrong geocoding result, also no other results for geopy. 

### ISSUE THREAD

**Issue by Arattel** [osm-search/Nominatim#2081]
When I search for "Austin, TX", I get the right geolocation, but when I search for "Austin, TX, USA", I get Austin street not even in the same county. 
![image](https://user-images.githubusercontent.com/26382913/100614858-71bac380-331f-11eb-98f2-6ac8a4afd9e4.png)
When I click on the button "Search for more results", I get the right result for web interface. But for this Python code
```
from geopy.exc import GeocoderTimedOut
from geopy.geocoders import Nominatim, GoogleV3
locator = Nominatim(user_agent='counties-in-circle')
location = locator.geocode("Austin, TX, USA", exactly_one=False, limit=200)
```
I get only one location:
`[Location(Austin, Bastrop Beach, Brazoria County, Texas, United States of America, (29.083823, -95.366077, 0.0))]`

Geopy version:
geopy~=2.0.0

**Comment by lonvia** [comment]
That's a bug introduced with #2073. Will be fixed with #2084.
