### ISSUE TITLE
Supporting multilingual address information

### ISSUE THREAD

**Issue by jochenhebbrecht** [osm-search/Nominatim#2083]
Hi,

We are currently loading a PBF file into Nominatim in which certain _nodes_ contain address information in multiple languages. These _multilingual addresses_ have been modelled according to the OpenStreetMap guidelines being described over here: https://wiki.openstreetmap.org/wiki/Key:addr#Multilingual_Addresses

Example:
```
        <node id="..." changeset="..." version="..." timestamp="..." lat="..." lon="...">
            <tag k="addr:street:en" v="Village street"/>
            <tag k="addr:street:es" v="Calle del pueblo"/>
            ...
         </node>
```

Unfortunately, Nominatim doesn't seem to add this address information into the `place` table. If we use the webviewer and we fill in the address information the search field, it's also not queryable.

**My questions:**
* Are multilingual addresses supported by default? We do know that the ` addr:` tags are just recently being taken into account (ref: https://nominatim.org/2020/10/07/about-addr-tags.html). Is there a possibility the multilingual address information is something that is not taken up yet? Or is there currently development work going on to support this?
* If it would be supported by default -> looking at the configuration of Nominatim, do we need to tweak the https://github.com/osm-search/Nominatim/blob/master/settings/import-street.style file for example to also support `addr:street:*` tags?

Thanks for your feedback!
Jochen

**Comment by lonvia** [comment]
Nominatim doesn't support multilingual address information and probably never will. The simple reason is that it is not worth the trouble. OpenStreetMap usually has the translations on the street and Nominatim already has a generic mechanism to pick up the translations from there (and from the city place, and the country, and...)

Nominatim does save the multi-lingual tags in the address field though, see for example [this street in Südtirol](https://nominatim.openstreetmap.org/ui/details.html?osmtype=N&osmid=2755810008&class=place). With the recent changes to handle extra addr:* tags, it should be fairly easy to hack the code to add the terms to the search names (so it is found) and later merge them back into the display result.

You should be careful with loading separate node information though. Nominatim is designed around the premise that every element of the address is also present as a separate entity. Streets as `highway=*` ways, cities as `place=*` nodes etc. It cannot process addresses well when they only appear in the form of addr:* tags.

**Comment by jochenhebbrecht** [comment]
Thanks for your quick feedback! Much appreciated :-)!

We are currently using Nominatim version `3.5.2`, but whent trying to load OSM node information with multilingual address information (such as example in my first post), the complete node cannot be found in the `place` table. We'll probably need to build Nominatim from `master` to get this kind of functionality?

Thanks for sharing the concern to be careful with loading separate node information. We have taken it into account.

**Comment by lonvia** [comment]
If you have address nodes, then you need to use the `import-address.style` or `import-full.style`. `import-street.style` only imports data down to street level but not house numbers.

**Comment by jochenhebbrecht** [comment]
Hmm, sorry, that also doesn't work I'm afraid :-( ... I tried `import-address.style` and `import-full.style`, but the multi-lingual tags are still not being recognized. Actually, the whole node is even not available in the `place` table.

I changed the import style by adapting the `local.php` file to:
```php
 @define('CONST_Import_Style', '/srv/nominatim/settings/import-full.style');
```
Should I do something else as well?

**Comment by jochenhebbrecht** [comment]
Ok, sorry, I figured out what was going wrong when looking into the source code. Adatepd the PBF file to:
```
        <node id="..." changeset="..." version="..." timestamp="..." lat="..." lon="...">
            <tag k="addr:street:en" v="Village street"/>
            <tag k="addr:street:es" v="Calle del pueblo"/>
            **<tag k="addr:street" v="Village street - Calle del pueblo"/>**
            ...
         </node>
```
After adding the line in bold, everything was imported correctly. After that, we noticed that quering indeed doesn't work. But that's normal based on your feedback:
>  it should be fairly easy to hack the code to add the terms to the search names (so it is found) and later merge them back into the display result.

**Comment by lonvia** [comment]
The additional `addr:street` tag wouldn't make a difference. What other tags do you have on the node? There needs to be at least one that is recognised as a main tag or Nominatim drops the entire node.

**Comment by jochenhebbrecht** [comment]
Well, if I leave out `addr:street`, it just simply doesn't seem to work anymore ... :-(.

The other tags that I have on the node are, but that's basically it.
```
* addr:housenumber
* addr:postcode
* addr:city
```

**Comment by lonvia** [comment]
There must be something else that's wrong in your file. I just tried with:
```
<?xml version="1.0" encoding="UTF-8"?>
<osm version="0.6" >
 <node id="704166152" visible="true" version="2" changeset="95175857" timestamp="2020-12-02T20:20:27Z" user="Iváns_import" uid="10907973" lat="43.3593539" lon="-8.4488861">
  <tag k="addr:city" v="A Coruña"/>
  <tag k="addr:housenumber" v="53"/>
  <tag k="addr:street:en" v="Lugar de Bens"/>
  <tag k="addr:postcode" v="15010"/>
 </node>
</osm>
```

and Nominatim happily creates a record for it in the placex table on master and version 3.5.2.

**Comment by jochenhebbrecht** [comment]
Sorry, I see that I wasn't 100% clear in my previous reply.

I tested your example and it works fine. Then I updated your file to make it in line with what we have, and after doing that, it stopped working:

```xml
<?xml version="1.0" encoding="UTF-8"?>
<osm version="0.6" >
      <node id="704166152" visible="true" version="2" changeset="95175857" timestamp="2020-12-02T20:20:27Z" user="Iváns_import" uid="10907973" lat="43.3593539" lon="-8.4488861">
         <tag k="addr:city:en" v="A Coruña" />
         <tag k="addr:housenumber:en" v="53" />
         <tag k="addr:street:en" v="Lugar de Bens" />
         <tag k="addr:postcode:en" v="15010" />
      </node>
</osm>
```
So adding the language identifier to all of the `addr:` tags makes the node be skipped during analyzing.
Now, you'll probably going to ask: _why do you want to add a language tag on the housenumber?_ I guess that would be very good question :-D ...

**Comment by lonvia** [comment]
Indeed, that would explain it. The style only accepts `addr:housenumber` as main tag. All other `addr:` tags it finds go into address field.

Purely theoretically speaking, you could add `addr:housenumber:en` as a main tag to the the style. It just wouldn't do much because the address processing code is then hardcoded to look only for `addr:housenumber`. If you really wanted housenumbers localized, you'd have to do some hacking there too.

**Comment by jochenhebbrecht** [comment]
Thanks, you are right. I do have 1 little question. Maybe you can explain me the following scenario.

I wanted to pick on this reply:
> You should be careful with loading separate node information though. Nominatim is designed around the premise that every element of the address is also present as a separate entity. Streets as highway=* ways, cities as place=* nodes etc. It cannot process addresses well when they only appear in the form of addr:* tags.

So, if you would go to https://nominatim.openstreetmap.org/ui/search.html and search for `644 Rizal Avenue, Santa Cruz`, you'll get the following result:

![Screenshot from 2020-12-03 23-01-53](https://user-images.githubusercontent.com/2405227/101093923-dbef9480-35bb-11eb-909e-4bfcba2ab338.png)

Now, when take the Philippines from Geofabrik and add the following node information:

```xml
<?xml version="1.0" encoding="UTF-8"?>
<osm version="0.6" >
            <node id="100258899" changeset="123456" version="1" timestamp="2020-09-20T20:20:20Z" lat="14.6018374" lon="120.98194529999999">
                <tag k="addr:street" v="Rizal Avenue"/>
                <tag k="addr:housenumber" v="644"/>
                <tag k="addr:postcode" v="1003"/>
                <tag k="addr:city" v="Manila"/>
            </node>
</osm>
```
Next, we load the 'custom' PBF into our own Nominatim instance. We try to search for the same address, we're getting following result:

![Screenshot from 2020-12-03 23-02-08](https://user-images.githubusercontent.com/2405227/101094051-15280480-35bc-11eb-918b-f739aa5b833e.png)

So the conclusion for me is that the geocoding improves after adding the extra address tags. However, coming back to the reply where you said: _ It cannot process addresses well when they only appear in the form of addr:* tags._, I was actually not expecting the geocoding experience to be improved. 

Could you explain this scenario to me?

( sorry, a little hijacking the topic over here, because this has nothing to do anymore with multilingual addresses )

**Comment by lonvia** [comment]
In your example you enhance OSM data with address data. That works fine. I meant something different: say you have an address database and convert it into an OSM file with lots of nodes with only addr:* tags. Then you load only this file into Nominatim. This won't work well.

Address points are not a full data point on its own in Nominatim. An address point looks up the street or place) the house number belongs to and then uses most of the address information from there. That allows us to save a significant amount of storage. The assumption always was that mappers would add the streets first to OSM and then only gradually put in the house numbers. So it didn't seem to be a big issue to optimise this way. That changes of course with imports. The case above with address only data is a bit extreme, but we run into the same problems when somebody imports addresses in an area that isn't well mapped. Norway and Denmark have this issue at the moment.

**Comment by jochenhebbrecht** [comment]
Thanks, that makes it much clearer :-).
Closing this ticket, thanks for your help!
