### ISSUE TITLE
Question on peterevans/nominatim, docker: It Always re-download OSM data and re-import into postgres when restart the container

### ISSUE THREAD

**Issue by sj132** [osm-search/Nominatim#2089]
I am a newcomer of nominatim. I use the docker images named peterevans/nominatim. 
The question is that every time I restart this docker contrainer, it seems that it will re-download OSM and re-import into postgres. If I kill the download process, it will be error to access database like this:

Internal Server Error
Nominatim has encountered an internal error while accessing the database. This may happen because the database is broken or because of a bug in the software.

Details
Database query failed
If you feel this error is incorrect feel file an issue on Github. Please include the error message above and the URL you used.

**Comment by mtmail** [comment]
I think https://github.com/peter-evans/nominatim-docker/issues/22 covers this already. Their docker setup is not persistent and will recreate/reimport the data each time. The documentation at https://github.com/peter-evans/nominatim-docker#persistent-storage points to another project. You should raise the issue with peter-evans.

I'd say of course there's errors if a process gets killed. The Apache webserver error log might show a more detailed error message. Running `./build/utils/check_import_finished.php` (I can't tell where that script is located is inside their docker setup) might also point to specific errors.

**Comment by lonvia** [comment]
This is the wrong place to ask questions about the docker image. We are not affiliated with that.

**Comment by sj132** [comment]
> I think [peter-evans/nominatim-docker#22](https://github.com/peter-evans/nominatim-docker/issues/22) covers this already. Their docker setup is not persistent and will recreate/reimport the data each time. The documentation at https://github.com/peter-evans/nominatim-docker#persistent-storage points to another project. You should raise the issue with peter-evans.
> 
> I'd say of course there's errors if a process gets killed. The Apache webserver error log might show a more detailed error message. Running `./build/utils/check_import_finished.php` (I can't tell where that script is located is inside their docker setup) might also point to specific errors.

Oh, I see. Thanks a lot.

**Comment by sj132** [comment]
> This is the wrong place to ask questions about the docker image. We are not affiliated with that.

I'm so sorry for not knowing the rules. I will be careful next time. Sorry again!
