### ISSUE TITLE
Problems when searching for special characters

### ISSUE THREAD

**Issue by marlarius** [osm-search/Nominatim#2091]
## What did you search for?

Rømø, an island in Denmark

https://nominatim.openstreetmap.org/ui/search.html?q=r%C3%B8m%C3%B8

## What result did you get?

Rome, Italy. The first result in the list.

## What result did you expect?

Rømø, the second result.

**Is the result in the right place and just named wrongly?** 

No

Please tell us the display name you expected.

n/a

**Is the result missing completely?**

It is ordered incorrectly. The perfect match comes as item 2.

Rømø is here: https://www.openstreetmap.org/relation/5178496

## Further details

I looked at the debug output. Apparently the Danish special characters are being latinized so the actual query sent to Nominatim is "romo" which is then interpreted as Rome.

Nominatim should first try with the original characters and only proceed with a latinized version in case of no match.

**Comment by lonvia** [comment]
Diacratics are now taken into account to weigh now well a search matches.
