### ISSUE TITLE
Failing to find very simple city searches for cities located in Ohio

### ISSUE THREAD

**Issue by ebzimny01** [osm-search/Nominatim#2093]
## What did you search for?
Cincinnati, OH, USA
Cincinnati, Ohio, USA

I have also tried other cities in Ohio that are not working:
Cleveland, OH, USA
Akron, OH, USA
Toledo, OH, USA
Columbus, OH, USA

Please try to provide a link to your search. You  can go to https://nominatim.openstreetmap.org and repeat your search there. If you originally found the issue somewhere else, please tell us what software/website you were using.

https://nominatim.openstreetmap.org/ui/search.html?city=Cincinnati&state=Ohio&country=USA

Debug output:
https://nominatim.openstreetmap.org/search.php?city=Cincinnati&state=Ohio&country=USA&polygon_geojson=1&format=jsonv2&debug=1

## What result did you get?
No search results found

## What result did you expect?
Expected to see results for Cincinnati, Ohio appear in the results.

**Is the result in the right place and just named wrongly?** 

Please tell us the display name you expected.

**Is the result missing completely?**
YES.

Please note that if you simply search for "Cincinnati" alone without state and country, you will get a list of search results including the main one which is Cincinnati, Ohio.
https://nominatim.openstreetmap.org/ui/search.html?city=Cincinnati

Make sure that the data you are looking for is in OpenStreetMap. Provide a link to the OpenStreetMap object or if you cannot get it, a link to the map on https://openstreetmap.org where you expect the result to be.

https://nominatim.openstreetmap.org/ui/details.html?osmtype=R&osmid=183453&class=boundary

To get the link to the OSM object, you can try the following:

 * Go to [https://openstreetmap.org](https://openstreetmap.org).
 * Move to the area of the map where you expect the result and then zoom in as much as possible.
 * Click on the question mark on the right side of the map. You get a question cursor. Use it to click on the map where your object is located.
 * Find the object of interest in the list that appears on the left side.
 * Click on the object and report back the URL that the browser shows.

## Further details

Anything else we should know about the search. Particularities with addresses in the area etc.

**Comment by lonvia** [comment]
Bad luck. The Ohio boundary was broken exactly on the day where we did the reimport of the database. I'll see what I can do.

**Comment by lonvia** [comment]
All fixed.

**Comment by ebzimny01** [comment]
Indeed, thank you!
