### ISSUE TITLE
"Could not lookup place"  error in search api

### ISSUE THREAD

**Issue by nashJG** [osm-search/Nominatim#2100]
**_I got a error in search and detail api._** 
I have installed my own nominatim service, and imported data successed. 

The search query was "/search.php?q=Washington%20DC&polygon_geojson=1&format=jsonv2"
and responsed:

> {"error":{"code":500,"message":"Could not lookup place"}}

The detail query  was "/details.php?osmtype=R&osmid=5396194&class=boundary&addressdetails=1&hierarchy=0&group_hierarchy=1&polygon_geojson=1&format=json"
and responsed:

> {"error":{"code":500,"message":"Database query failed"}}

My postgres version is  psql (PostgreSQL) 10.15 (Ubuntu 10.15-0ubuntu0.18.04.1)
The Nominatim is clone from master at  7889509856a99c90bf5b3f52c86f39a3265281c4
`commit 7889509856a99c90bf5b3f52c86f39a3265281c4 (grafted, HEAD -> master, origin/master, origin/HEAD)`

The data is imported from all planet osm pbf and checked import success.

**Comment by mtmail** [comment]
Can you check the webserver logfile, on Ubuntu that could be `/var/log/apache2/error.log` for the full error message. It should contain the exact line and database query that failed. Does `/status.php?format=json` print any errors?

**Comment by nashJG** [comment]
/status.php?format=json   response success:

> {"status":0,"message":"OK","data_updated":"2020-11-30T00:56:40+00:00"}

I have checked the webserver logfile,  there is no output in error.log. 

I print the sql executed in "/search.php?q=Washington%20DC&polygon_geojson=1&format=jsonv2",  the psql error was caused by this sql:

>`SELECT     osm_type,    osm_id,    class,    type,    admin_level,    rank_search,    rank_address,    min(place_id) AS place_id,    min(parent_place_id) AS parent_place_id,    -1 as housenumber,    country_code,get_address_by_language(place_id,-1,ARRAY['name:zh-CN','name:zh','name','brand','official_name:zh-CN','short_name:zh-CN','official_name:zh','short_name:zh','official_name','short_name','ref','type']) AS langaddress,    get_name_by_language(name,ARRAY['name:zh-CN','name:zh','name','brand','official_name:zh-CN','short_name:zh-CN','official_name:zh','short_name:zh','official_name','short_name','ref','type']) AS placename,    get_name_by_language(name, ARRAY['ref']) AS ref,    avg(ST_X(centroid)) AS lon,     avg(ST_Y(centroid)) AS lat,     COALESCE(importance,0.75-(rank_search::float/40)) AS importance, (SELECT max(ai_p.importance * (ai_p.rank_address + 2))   FROM place_addressline ai_s, placex ai_p   WHERE ai_s.place_id = min(CASE WHEN placex.rank_search < 28 THEN placex.place_id ELSE placex.parent_place_id END)     AND ai_p.place_id = ai_s.address_place_id      AND ai_s.isaddress      AND ai_p.importance is not null) AS addressimportance,    COALESCE(extratags->'place', extratags->'linked_place') AS extra_place  FROM placex WHERE place_id in (14278148)    AND (        placex.rank_address between 0 and 30     OR (extratags->'place') = 'city'       )     AND linked_place_id is null  GROUP BY      osm_type,      osm_id,      class,      type,      admin_level,      rank_search,      rank_address,      housenumber,     country_code,      importance, langaddress,      placename,      ref,      extra_place ;`


I executed this sql in postgresql client,  it responsed error:

> ERROR:  record "place" is not assigned yet
> DETAIL:  The tuple structure of a not-yet-assigned record is indeterminate.
> CONTEXT:  SQL statement "SELECT place IS NULL"
> PL/pgSQL function get_addressdata(bigint,integer) line 53 at IF
> PL/pgSQL function get_address_by_language(bigint,integer,text[]) line 12 at FOR over SELECT rows

So i think there was something wrong with create function or index data when i imported data.

I compare the dictionary "Nominatim/sql/functions/" in commit 7889509856a99c90bf5b3f52c86f39a3265281c4 with the earlier commit 1f07d63dc5a043c44faa478f418c38455cc6dd75 .  I found some comitted codes in address_lookup.sql and placex_triggers.sql .   Is this problem caused by these commits?

**Comment by nashJG** [comment]
> This works on our servers, so I suspect that this is an issue with older Postgresql versions. Let me see if I can reproduce it.

**Comment by nashJG** [comment]
I upgraded my Postgresql to version 12, and reinstalled by the same nominatim source code.  I imported the /europe/monaco-latest.osm.pbf for test.  The search api and detail api works well.  So I think it is an issue with Postgresql version 10.
