### ISSUE TITLE
Searching for cities in Pennsylvania is not working very well...

### ISSUE THREAD

**Issue by ebzimny01** [osm-search/Nominatim#2103]
## What did you search for?
Searching for cities in Pennsylvania is not working very well.

Reading, PA - https://nominatim.openstreetmap.org/ui/search.html?city=Reading&state=Pennsylvania&country=USA&dedupe=0
Pittsburgh, PA - https://nominatim.openstreetmap.org/ui/search.html?city=Pittsburgh&state=Pennsylvania&country=USA&dedupe=0
West Chester, PA - https://nominatim.openstreetmap.org/ui/search.html?city=West+Chester&state=Pennsylvania&country=USA&dedupe=
- *Note that this search result comes back with "Chester, PA" which is not the same location as "West Chester, PA"*
Pottstown, PA - https://nominatim.openstreetmap.org/ui/search.html?city=Pottstown&state=Pennsylvania&country=USA&dedupe=0
Altoona, PA - https://nominatim.openstreetmap.org/ui/search.html?city=Altoona&state=Pennsylvania&country=USA

Philadelphia, PA - https://nominatim.openstreetmap.org/ui/search.html?city=Philadelphia&state=Pennsylvania&country=USA&dedupe=0
- *This is the only one in this list that returns an expected result.*

Please try to provide a link to your search. You  can go to https://nominatim.openstreetmap.org and repeat your search there. If you originally found the issue somewhere else, please tell us what software/website you were using.

## What result did you get?
Reading, PA - no result
Pittsburgh, PA - no result
West Chester, PA - search returns "Chester, PA" which is not the correct location
Pottstown, PA - no result
Altoona, PA - no result
Philadelphia, PA - returns correct result

## What result did you expect?
Should have been able to return the correct search results for these locations in PA.

**Is the result in the right place and just named wrongly?** 

Please tell us the display name you expected.

**Is the result missing completely?**

Make sure that the data you are looking for is in OpenStreetMap. Provide a link to the OpenStreetMap object or if you cannot get it, a link to the map on https://openstreetmap.org where you expect the result to be.

Reading, PA - https://www.openstreetmap.org/relation/188481#map=14/40.3339/-75.9256
Pittsburgh, PA - https://www.openstreetmap.org/relation/188553#map=14/40.4362/-79.9866
West Chester, PA - https://www.openstreetmap.org/relation/187665#map=11/39.9602/-75.6057
Pottstown, PA - https://www.openstreetmap.org/relation/187801
Altoona, PA - https://www.openstreetmap.org/relation/188252

## Further details

Anything else we should know about the search. Particularities with addresses in the area etc.

**Comment by lonvia** [comment]
Same as #2093. Pennsylvania was broken when we reimported the database. Should be fixed now.

**Comment by ebzimny01** [comment]
Figured that might be the case. Thank for you for resolving!
