### ISSUE TITLE
There is confusion about the address rank. The rank is different from those on  `nominatim.openstreetmap.org`

### ISSUE THREAD

**Issue by shinyke** [osm-search/Nominatim#2107]
## background
I imported complete global dataset to my local nominatim service. 

## What did you search for?
query a building like this:
http://ip:8080/details.php?osmtype=W&osmid=363576780&class=building

A same search in `nominatim.openstreetmap.org` is :
https://nominatim.openstreetmap.org/ui/details.html?osmtype=W&osmid=363576780&class=building

## What result did you get?
my search result:
![image](https://user-images.githubusercontent.com/5669026/102167775-0b5ea500-3eca-11eb-9c87-eda655afcad5.png)
All the entities in china have the same mistake:  the rank of city/district/subdistrict  in chaos.

I found the address rank is quite different from `nominatim.openstreetmap.org`.  And latter one  is correct.
![image](https://user-images.githubusercontent.com/5669026/102168030-7dcf8500-3eca-11eb-92e8-47128215691b.png)

## What result did you expect?
I expect that my local search results can be same as `nominatim.openstreetmap.org`. 
In my imaginatiom, I import the complete global data [(https://planet.openstreetmap.org/)](https://planet.openstreetmap.org/)  to build my local service, I expect a same search results as in the open API. It can be a subset of it, but the existing parts should not be different.

## Further details
I checked the OSM data of the locale with an exception address rank. If you import according to the default configuration, you will get the wrong data I have shown above.

default address rank configure:
```json
{ "tags" : {
      "place" : {
          "sea" : [2, 0],
          "island" : [17, 0],
          "islet" : [20, 0],
          "continent" : [2, 0],
          "country" : [4, 0],
          "state" : [8, 0],
          "province" : [8, 0],
          "region" : [18, 0],
          "county" : 12,
          "district" : 12,
          "municipality" : 14,
          **"city" : 16,**
          "town" : [18, 16],
          "borough" : 18,
          "village" : [19, 16],
          "suburb" : [19, 20],
          "hamlet" : 20,
          "croft" : 20,
          "subdivision" : 22,
          "allotments" : 22,
          "neighbourhood" : [20, 22],
          "quarter" : [20, 22],
          "isolated_dwelling" : [22, 20],
          "farm" : [22, 20],
          "city_block" : 25,
          "mountain_pass" : 25,
          "square" : 25,
          "locality" : 25,
          "houses" : [28, 0],
          "house" : 30,
          "" : [22, 0]
      },
      "boundary" : {
          "administrative2" : 4,
          "administrative3" : 6,
          "administrative4" : 8,
          "administrative5" : 10,
          **"administrative6" : 12,**
          "administrative7" : 14,
          **"administrative8" : 16,**
          "administrative9" : 18,
          "administrative10" : 20,
          "administrative11" : 22,
          "administrative12" : 24,
          "" : [25, 0]
      },
```

relation 广州 -> place= 'city' -> address rank=16
```json
12683640:  <relation id="3287346" version="50" timestamp="2020-11-26T20:20:09Z">
12683641-    <member type="node" ref="244080443" role="admin_centre"/>
12683710-    <tag k="admin_level" v="5"/>
12683714-    <tag k="boundary" v="administrative"/>
12683717-    <tag k="name" v="广州市"/>
12683851-    <tag k="place" v="city"/>
12683852-    <tag k="type" v="boundary"/>
12683855-  </relation>
```

relation 越秀区 ->boundary:administrative  + admin_level=6 -> Address rank=12
```json
12789569:  <relation id="3987394" version="16" timestamp="2020-08-13T17:44:22Z">
12789570-    <member type="node" ref="5113242584" role="admin_centre"/>
12789619-    <tag k="name" v="越秀区"/>
12789620-    <tag k="type" v="boundary"/>
12789639-    <tag k="boundary" v="administrative"/>
12789648-    <tag k="admin_level" v="6"/>
12789649-    <tag k="china_class" v="county"/>
12789651-  </relation>
````

relation 光塔街道 -> boundary:administrative + admin_level=8 -> Address rank = 16
```json
12797530:  <relation id="4069906" version="3" timestamp="2020-08-24T15:49:55Z">
12797531-    <member type="node" ref="3098740409" role="admin_centre"/>
12797542-    <tag k="admin_level" v="8"/>
12797543-    <tag k="boundary" v="administrative"/>
12797544-    <tag k="name" v="光塔街道"/>
12797545-    <tag k="type" v="boundary"/>
12797547-  </relation>
```

**Comment by lonvia** [comment]
What version of Nominatim do you use with your own installation?

**Comment by shinyke** [comment]
> What version of Nominatim do you use with your own installation?

@lonvia  I'm now using v3.5.2.

**Comment by lonvia** [comment]
nominatim.openstreetmap.org is on 3.6.0. That explains the difference. Rank assignment has changed massively in the last version, see also https://nominatim.org/2020/11/11/places-and-boundaries.html. You need a reimport to profit from the changes.

**Comment by shinyke** [comment]
> nominatim.openstreetmap.org is on 3.6.0. That explains the difference. Rank assignment has changed massively in the last version, see also https://nominatim.org/2020/11/11/places-and-boundaries.html. You need a reimport to profit from the changes.

I read the material you gave, and check the address-levels.json's  diffs between v3.5.2 and v3.6.0. But still found that cannot fix this issue.

In version 3.6.0, the address rank of city GuangZhou(广州 id=3287346) still will be calculated to 16 and the YueXiu district（越秀区 id=3987394）will be calculated to 12 cause `boundary:administrative` and `admin_level=6`. So it still not match to the result in nominatim.openstreetmap.org.

**Comment by lonvia** [comment]
All I can say that nominatim.openstreetmap.org runs pretty much exactly 3.6.0 even data-wise. If you tell me that what you see there is correct, then I can only conclude there is no problem.
