### ISSUE TITLE
Street Number No Longer Show on Reverse Lat Long Lookup

### ISSUE THREAD

**Issue by sunilw123** [osm-search/Nominatim#2109]
## What did you search for? I looked up the lat long for an address.  Last month when I did it, it showed the street address of 10704 but now when I run the same lat long reverse lookup it doesn't show the street address.  Why is that and how can I consistently get the street address to be returned from the reverse lat long lookup? I submitted both screenshots. The first one was from November which showed the street address and the second from today which no longer shows it.  i need to know how can I make sure i consistently receive the street number from my lat long reverse lookup? Every lookup I do doesn't show the house number. Please help. Thanks.

Please try to provide a link to your search. You  can go to https://nominatim.openstreetmap.org and repeat your search there. If you originally found the issue somewhere else, please tell us what software/website you were using.  Link: -88.000340
<img width="1792" alt="Screen Shot 2020-11-23 at 4 27 03 PM" src="https://user-images.githubusercontent.com/35516853/102316713-0c301f00-3f3c-11eb-8411-32611ec491e7.png">
<img width="1792" alt="Screen Shot 2020-12-16 at 1 04 40 AM" src="https://user-images.githubusercontent.com/35516853/102316759-2538d000-3f3c-11eb-8be6-01e330b6bcca.png">

## What result did you expect? I expected the december/current results to show the same as what I got when I ran the search in November.

**Is the result in the right place and just named wrongly?** 

Please tell us the display name you expected.

**Is the result missing completely?** No

Make sure that the data you are looking for is in OpenStreetMap. Provide a link to the OpenStreetMap object or if you cannot get it, a link to the map on https://openstreetmap.org where you expect the result to be.

To get the link to the OSM object, you can try the following:

 * Go to [https://openstreetmap.org](https://openstreetmap.org).
 * Move to the area of the map where you expect the result and then zoom in as much as possible.
 * Click on the question mark on the right side of the map. You get a question cursor. Use it to click on the map where your object is located.
 * Find the object of interest in the list that appears on the left side.
 * Click on the object and report back the URL that the browser shows.

## Further details

Anything else we should know about the search. Particularities with addresses in the area etc.

**Comment by lonvia** [comment]
Can you please provide the link to the reverse lookup in question in a form that it can be copied.

**Comment by sunilw123** [comment]
Sure.  Here it is: https://nominatim.openstreetmap.org/ui/details.html?osmtype=W&osmid=21543861&class=highway
The Lat is: 43.2136210822436 and the Long is: -88.0005844038327. 
So I would like to know 1) why this is no longer showing the street address and 2) how do we make sure we always get the street address using reverse lat long API?  Thank you.

**Comment by lonvia** [comment]
That was a sysadmin error. I forgot to enable the additional US Tiger housenumber data after the reimport. Fixed now.
