### ISSUE TITLE
Cannot get details for the relation of Tampa, Florida

### ISSUE THREAD

**Issue by rcarroll0452** [osm-search/Nominatim#2110]
## What did you search for?
https://nominatim.openstreetmap.org/ui/details.html?osmtype=R&osmid=1216849

Yields `Error fetching results from /details.php?osmtype=R&osmid=1216849&addressdetails=1&hierarchy=0&group_hierarchy=1&polygon_geojson=1&format=json`

[Here's the OSM link for the relation Tampa Florida](https://www.openstreetmap.org/relation/1216849)

**Comment by lonvia** [comment]
This is a data issue. Somebody has removed `type=boundary` and `boundary=administrative` from that relation [12 days ago](https://www.openstreetmap.org/changeset/95316784). Revert it and Nominatim picks up the change.
