### ISSUE TITLE
Pin point GPS position picking up another street

### ISSUE THREAD

**Issue by vhmoura** [osm-search/Nominatim#2111]
## What did you search for?

https://nominatim.openstreetmap.org/ui/reverse.html?format=html&lat=51.433217&lon=-1.077398&zoom=17

## What result did you get?
Station yard street. Please see below in red where it was searched and the result it returned

## What result did you expect?
Station road, exactly where the gps position is.

**Is the result in the right place and just named wrongly?** 
result is pin pointing a different road

**Is the result missing completely?**
No

## Further details

![image](https://user-images.githubusercontent.com/20772905/102384175-54931f80-3fc4-11eb-89ef-fa6878a35ec3.png)

is it because the map street seems broken? Way: 4478539 If that is the case, how can that get fixed? I've tried to adjust the way line but didn't work.

![image](https://user-images.githubusercontent.com/20772905/102386757-6924e700-3fc7-11eb-9370-6607c585d987.png)

**Comment by mtmail** [comment]
This is a data issue. https://www.openstreetmap.org/way/4478539 doesn't have a `name` tag.

**Comment by mtmail** [comment]
I see you edited the OSM way and the search returns Station Rd now. https://nominatim.openstreetmap.org/ui/reverse.html?format=html&lat=51.433217&lon=-1.077398&zoom=17
