### ISSUE TITLE
Import data too slow when i use nominatim:3.6.0

### ISSUE THREAD

**Issue by k1tCooler** [osm-search/Nominatim#2114]
Import data is slower than previous versions at local environment.

Data:
         https://download.geofabrik.de/asia/gcc-states-latest.osm.pbf

Cost time at v3.5.2:
         about 20 mins

Cost time at v3.6.0:
         more than 2 hours

**Comment by lonvia** [comment]
This is not enough information to even start analysing the problem. I'm closing this. Please open another issue using the 'Report problems with the software' template and make sure to answer all the questions in there.
