### ISSUE TITLE
Livno Tušnica no results

### ISSUE THREAD

**Issue by programmin1** [osm-search/Nominatim#2121]
## What did you search for?

https://nominatim.openstreetmap.org/search/Livno%20Tu%C5%A1nica?format=jsonv2

## What result did you get?

No results

## What result did you expect?

I would expect the nominatim result I see here: https://nominatim.openstreetmap.org/ui/search.html?q=Livno+Tu%C5%A1nica

**Is the result missing completely?**

Yes, only on json api call.

**Comment by mtmail** [comment]
You need to replace ' ' with ' '
https://nominatim.openstreetmap.org/search/Livno/Tu%C5%A1nica?format=jsonv2

Documented on https://nominatim.org/release-docs/3.5.2/api/Search/
"This format only accepts a free-form query string where the parts of the query are separated by slashes."

That query format is getting phased out in the next years. It's no longer documented in version 3.6
https://nominatim.org/release-docs/3.6.0/api/Search/
so it's better to use the 
https://nominatim.openstreetmap.org/search?q=Livno+Tu%C5%A1nica&format=jsonv2
format.

**Comment by programmin1** [comment]
Thanks. It does work for other queries such as
https://nominatim.openstreetmap.org/search/Bend%20OR?format=jsonv2

**Comment by lonvia** [comment]
That just works accidentally because it puts terms in different order.

Please switch to `q=` parameter query format.
