### ISSUE TITLE
Nominatim API does not return house number with CURL request but returns when requested via browser

### ISSUE THREAD

**Issue by br4v0** [osm-search/Nominatim#2122]
I am using OSM Nominatim API to reverse geocode address from lat lng. But i am facing this weird problem, when i hit api via CURL reuquest it does not return any house number.

```
function getAddressFromNominatim($lat,$lon){
  $client = new Client();
  $nominatimUrl = env('NOMINATIM_URL', 'https://nominatim.openstreetmap.org/reverse?');
  $nominatimUrl .= "lat={$lat}&lon={$lon}&format=json&accept-language=en";
  $headers['json'] = [];
  $headers['User-Agent'] = 'Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:74.0) Gecko/20100101 Firefox/74.0';
  
  $request = $client->request('GET', $nominatimUrl,[
          'headers' => $headers
      ]);
  $response = collect(json_decode((string) $request->getBody(), true));
  if (!isset($response['display_name'])) {
      return 'Unable to geocode';
  }
  return $response['display_name'];}
```
Postman Response
<img src=https://i.gyazo.com/f32eff099adffb69aa6efb60f5f8f578.png>

But when i hit the same url in browser, it returns house number

Browser Response
<img src=https://i.gyazo.com/051070f949b4f04bbb51b2269e09ab0b.png>

I am using Guzzle HTTP in Laravel 5.8 to make CURL requests.

Nominatim URL for Reference: [Click Here](https://nominatim.openstreetmap.org/reverse?lat=43.213753025087726&lon=-88.00024470322579&format=json&accept-language=en)

Can anyone guide me with this ?

**Comment by lonvia** [comment]
That's not a problem with Nominatim. It is a problem with your script on the client side. Probably an off-by-one error somewhere in the in the json decoder.

Side note: please don't fake user agents to pretend to be a browser. Set a custom user agent that identifies your script.

**Comment by br4v0** [comment]
> That's not a problem with Nominatim. It is a problem with your script on the client side. Probably an off-by-one error somewhere in the in the json decoder.
> 
> Side note: please don't fake user agents to pretend to be a browser. Set a custom user agent that identifies your script.

I have tried using different methods in PHP, including CURL and file_get_contents 
And yes i also tried using custom agent, nothing worked.

And how it is a problem with script when it's behavior is to fetch data from url ?

**Comment by lonvia** [comment]
Well, I can see the housenumber with the web browser and also `curl -A 'Custom Curl' 'https://nominatim.openstreetmap.org/reverse?lat=43.213753025087726&lon=-88.00024470322579&format=json` returns the house number as expected. So at the moment the behaviour you describe is not reproducible for me. Please create a complete but minimalist script that I can execute locally and that shows the behaviour you describe. The code snippet above is not sufficient.
