### ISSUE TITLE
The wrong result from the search

### ISSUE THREAD

**Issue by solty2212** [osm-search/Nominatim#2128]
I'm tested API and expected an empty array, but in response, I have 2 objects.
URL for request:
https://nominatim.openstreetmap.org/search?q=Ukraine%2CNoName%23%23&format=json

Country: Ukraine
City: NoName(we don't have this city)
I've added a snapshot where I'm lighted what is wrong. 
![NoName_nominatim](https://user-images.githubusercontent.com/16225617/103765846-85480100-5026-11eb-81aa-2968dbea9f4d.PNG)

**Comment by mtmail** [comment]
Some cafes and restaurant use funny names. In the OpenStreetMap data the's a cafe in the Ukraine called 'NoName' https://www.openstreetmap.org/way/701944513 For the search terms you provided it's the best results.

**Comment by lonvia** [comment]
Closing as data issue.
