### ISSUE TITLE
Nominatim webserver build error

### ISSUE THREAD

**Issue by raviteja-karri** [osm-search/Nominatim#2130]
After compiling the latest Nominatim with the following steps
mkdir build
 cd build
 cmake ..
 make
 ./build/utils/setup.php --osm-file ../data/map.osm.pbf --all

Last steps results in the following error log

PHP Warning:  require(Symfony/Component/Dotenv/autoload.php): failed to open stream: No such file or directory in /home/ubuntu/Nominatim/lib/lib.php on line 3
PHP Fatal error:  require(): Failed opening required 'Symfony/Component/Dotenv/autoload.php' (include_path='.:/usr/share/php') in /home/ubuntuNominatim/lib/lib.php on line 3

**Comment by lonvia** [comment]
You need [Symphony Dotenv](https://symfony.com/doc/4.3/components/dotenv.html) now. On Debian/Ubuntu install it with `apt install php-symfony-dotenv`.

The [Ubuntu installation instructions](https://nominatim.org/release-docs/develop/appendix/Install-on-Ubuntu-18/) already had it. I've now also [added it to the prerequisites list](https://github.com/osm-search/Nominatim/commit/aaabb46f20bd6189caebf02c1f1a925cbd08a263).

**Comment by raviteja-karri** [comment]
I have ubuntu 16 now it is not allowing me to install php-symfony-dotenv

**Comment by lonvia** [comment]
We no longer officially support Ubuntu16. I recommend that you go back to the recent release 3.6.0. That should still do.
