### ISSUE TITLE
Wrong search result, Blora Central Java Indonesia

### ISSUE THREAD

**Issue by Zandut** [osm-search/Nominatim#2131]
I was try to search this location, https://nominatim.openstreetmap.org/ui/reverse.html?format=html&lat=-6.9260850&lon=111.5392733. And I got result, Blora Tuban East Java Indonesia. 
![Screen Shot 2021-01-09 at 19 14 33](https://user-images.githubusercontent.com/5546437/104091266-f994d580-52ae-11eb-9aa2-3100d29c3541.png)
And Blora should be Central Java. Please fix it. Thank You

**Comment by mtmail** [comment]
Rewording the issue: https://www.openstreetmap.org/way/646861111 crosses state lines. West of the state line, like in the provided coordinates, the address should show state 'Central Java' (https://www.openstreetmap.org/relation/2388357), not 'East Java'.
I split the long highway at the state border now but that doesn't seem to fix it yet

**Comment by Zandut** [comment]
Thank you @mtmail for fixing.

**Comment by lonvia** [comment]
Eventually needs to be fixed via #1518. Closing as duplicate.

**Comment by Zandut** [comment]
Thank You @lonvia , I hope to be fixed soon
