### ISSUE TITLE
Bedfordshire should be in 'East of England', not 'East Midland'

### ISSUE THREAD

**Issue by EdwardBetts** [osm-search/Nominatim#2137]
## What did you search for?

Bedfordshire

https://nominatim.openstreetmap.org/ui/search.html?q=Bedfordshire

## What result did you get?

Bedfordshire, East Midlands

https://nominatim.openstreetmap.org/ui/details.html?osmtype=R&osmid=88082&class=boundary

## What result did you expect?

Bedfordshire, East of England

**Comment by lonvia** [comment]
There is a rounding issue here. East Middlands gets split up into grids for faster lookup. That then gets compared against the original Bedfordshire and there is a tiny overlap. Not easy to fix without making indexing much more expensive.

**Comment by lonvia** [comment]
So it turns out that splitting the geometries into smaller pieces in #1926 has made the rounding error a real issue. I've reverted this now. This won't immediately fix the objects already in the database though. It is going to take a bit until all the errors have corrected themselves
