### ISSUE TITLE
I have updated the Latest Databse for Nepal, In reverse Geocode I only get country name in Display name

### ISSUE THREAD

**Issue by bhasingagan** [osm-search/Nominatim#2141]
## What did you search for?

https://nominatim.openstreetmap.org/reverse?format=jsonv2&lat=27.69871614261352&lon=85.34800250085284

http://<Private IP >/nominatim/reverse.php?format=jsonv2&lat=27.69871614261352&lon=85.34800250085284

## What result did you get?

{"place_id":4766077,"licence":"Data © OpenStreetMap contributors, ODbL 1.0. https://osm.org/copyright","osm_type":"relation","osm_id":184633,"place_rank":4,"category":"boundary","type":"administrative","importance":0.65,"addresstype":"boundary","name":"Nepal","display_name":"Nepal","address":{"country":"Nepal","country_code":"np"},"boundingbox":["26.3477581","30.446945","80.0586226","88.2015257"]}

## What result did you expect?

{"place_id":145352592,"licence":"Data © OpenStreetMap contributors, ODbL 1.0. https://osm.org/copyright","osm_type":"way","osm_id":220704533,"lat":"27.6989098","lon":"85.34797357000171","place_rank":30,"category":"amenity","type":"school","importance":0,"addresstype":"amenity","name":"Nepal Everest Montessori School","display_name":"Nepal Everest Montessori School, Tilaganga B Marg, Turning, Sinamangal, Kathmandu, Bagmati Pradesh, 44703, Nepal","address":{"amenity":"Nepal Everest Montessori School","road":"Tilaganga B Marg","neighbourhood":"Turning","suburb":"Sinamangal","city":"Kathmandu","county":"Kathmandu","region":"Bagmati Pradesh","postcode":"44703","country":"Nepal","country_code":"np"},"boundingbox":["27.6988004","27.6990377","85.3478135","85.3481369"]}
**Is the result in the right place and just named wrongly?** 

"Nepal Everest Montessori School, Tilaganga B Marg, Turning, Sinamangal, Kathmandu, Bagmati Pradesh, 44703, Nepal"

**Is the result missing completely?**

## Further details

/nominatim/details.php?osmtype=R&osmid=184633&class=boundary

Internal Server Error

Nominatim has encountered an error with your request.
Details
DateTime::__construct(): Failed to parse time string (@) at position 0 (@): Unexpected character

**Comment by lonvia** [comment]
Please provide details about your installation. What OS and what version of Nominatim do you use? What data have you imported? Was the import successful? Does `./utils/check_import_finished.php` report any errors?

**Comment by lonvia** [comment]
Closing, as no further detail was provided.

**Comment by 942u3895hjf** [comment]
I have this problem too. Just installed 3.7.2 on Ubuntu 20.04 and imported some OSM files i recently got from Overpass exports and a file from Geofabrik, the Australia.osm. It took a little while but it went fine.

Calls to details.php fail, such as:
http://localhost/nominatim/details.php?osmtype=W&osmid=6397441&addressdetails=1&hierarchy=0&group_hierarchy=1&format=json

Giving:
{"error":{"code":0,"message":"DateTime::__construct(): Failed to parse time string (@) at position 0 (@): Unexpected character"}}

I wouldexpect is the output as seen here:
https://nominatim.openstreetmap.org/details.php?osmtype=W&osmid=6397441&addressdetails=1&hierarchy=0&group_hierarchy=1&format=json

I do get errors when calling: ./utils/check_import_finished.php
PHP Warning:  require(Symfony/Component/Dotenv/autoload.php): failed to open stream: No such file or directory in /srv/nominatim/Nominatim-3.7.2/lib-php/dotenv_loader.php on line 3
PHP Fatal error:  require(): Failed opening required 'Symfony/Component/Dotenv/autoload.php' (include_path='.:/usr/share/php') in /srv/nominatim/Nominatim-3.7.2/lib-php/dotenv_loader.php on line 3

Any ideas?

**Comment by lonvia** [comment]
Please don't post on closed issue that might not even be related to your problem. Use the 'Discussion' feature if you need help with your installation.
