### ISSUE TITLE
Searching for texts in inscription key

### ISSUE THREAD

**Issue by urbalazs** [osm-search/Nominatim#2148]
From the [OpenStreetMap wiki](https://wiki.openstreetmap.org/wiki/Key:inscription):

> The key `inscription=*` is used for the text of inscriptions on buildings, memorials, advertising signs and other objects.

There are many useful information in key `inscription` and Nominatim should use this key as data source. Please add `inscription` to the sources of searches.

**Comment by lonvia** [comment]
This is out of scope for Nominatim for the moment. The goal is to search for places, not to find arbitrary OSM content.
