### ISSUE TITLE
When searching for an address, seemingly minor variations return unexpected results

### ISSUE THREAD

**Issue by tguen** [osm-search/Nominatim#2149]
## What result did you get?

`6300 North Lombard Street Portland Oregon` -> 6300 North Lombard Street, Portland, Oregon
`6300 N Lombard St Portland OR` -> 6300 North Lombard Street, Portland, Oregon
`6300 Lombard Portland OR` -> 6300 North Lombard Street, Portland, Oregon
`6300 North Lombard Portland Oregon` -> **5651** North Lombard Street, Portland, Oregon
`6300 North Lombard Portland OR` -> **no results**
`6300 Lombard Street Portland OR` -> Lombard Street, Portland, **Maine**
`6300 Lombard Street Portland Oregon` -> **no results**

## What result did you expect?

6300 North Lombard Street, Portland, Oregon

## Further details

This seems like a major issue. If I search for the terms that gave no results, I'd assume it hasn't been mapped unless I know otherwise. The 5651 result is close enough to the expected location that I might not notice it's the wrong address. Regarding the result in Maine, it seems that exact matches for the street name are considered more important than the city name. This might make sense within a short distance, but certainly not when the other city is thousands of miles away.

Related to #535

**Comment by lonvia** [comment]
Nominatim is not particular good on partial matches. That is a long standing and often reported issue.

Closing in favour of #94.
