### ISSUE TITLE
Error for searching South Jakarta (5802438)

### ISSUE THREAD

**Issue by gyurmalin** [osm-search/Nominatim#2150]
Hi All,

I was searching for admin_level==5 administrative boundaries for Jakarta. Out of the 5 districts 4 can be found properly in Nominatim, however, there is no record for South Jakarta (osm_id==R5802438).

https://www.openstreetmap.org/relation/5802438

Searching for URL and OSM ID I got the following error message: 
_Error fetching results from /details.php?osmtype=R&osmid=5802438&addressdetails=1&hierarchy=0&group_hierarchy=1&polygon_geojson=1&format=json__

So the problem is the related place seems to be missing completely from Nominatim.

Is there a chance to add the missing record?

Thanks a lot!

**Comment by lonvia** [comment]
If Nominatim can't find it by ID, then the relation is broken. The [relation analyser](http://ra.osmsurround.org/analyzeRelation?relationId=5802438&_noCache=on) gives the error [here](https://www.openstreetmap.org/relation/5802438#map=17/-6.23580/106.74824).

Closing as data error.

**Comment by gyurmalin** [comment]
Thanks, relation analyser is a good suggestion, will help a lot!
