### ISSUE TITLE
Searching coworking only returns results with name

### ISSUE THREAD

**Issue by ViolaineDo** [osm-search/Nominatim#2151]
## What did you search for?

Search for coworking space in Papeete, city in french polynesia, where there is a coworking space
Nominatim search link :
https://nominatim.openstreetmap.org/ui/search.html?q=coworking%2C+papeete

## What result did you get?
nothing found

## What result did you expect?
Showing coworking space Fakatere that I just added. 
If I search for name Fakatere, coworking space is found. But I would like to find it if I do not know the name, with the OSM tags : office=coworking

https://nominatim.openstreetmap.org/ui/details.html?osmtype=N&osmid=8350163117&class=office

**Is the result in the right place and just named wrongly?** 

No

**Is the result missing completely?**

Yes, here is osm data : 
https://www.openstreetmap.org/node/8350163117

**Comment by lonvia** [comment]
This is a so-called 'special phrase search', a search by POI type. You need to add coworking spaces to the [list of special phrases in the wiki](https://wiki.openstreetmap.org/wiki/Nominatim/Special_Phrases). Note however that the special phrases on the server only get updated on the reimport of the database. It might be a while until the next reimport. This is a known issue, see #1362.

**Comment by ViolaineDo** [comment]
sorry didn't know about this special phrases, thanks!
