### ISSUE TITLE
High volume of requests per second

### ISSUE THREAD

**Issue by dmitrymaslov99** [osm-search/Nominatim#2152]
Hello. Can your service be used for a large number of requests per day? No limit on requests per second?
I understand that the IP is banned

**Comment by mtmail** [comment]
Please don't. https://operations.osmfoundation.org/policies/nominatim/ has a section on third-party providers and how to install your own instance of Nominatim.

**Comment by dmitrymaslov99** [comment]
If I install mine instance of Nominatim, will I be able to access my server in unlimited quantities?

**Comment by mtmail** [comment]
Yes, with your own hardware you can "throw" as many requests per second at your instance of Nominatim as you want.
