### ISSUE TITLE
Missing some relations after importing India extract.

### ISSUE THREAD

**Issue by Suraj-Yadav** [osm-search/Nominatim#2154]
**Describe the bug**
I am running a Nominatim server in a ubuntu machine which i setup following these [instructions](https://nominatim.org/release-docs/latest/admin/Installation/).
Since I only needed data for India, i imported [extract](https://download.geofabrik.de/asia/india-latest.osm.pbf) from geofabrik using these [steps](https://nominatim.org/release-docs/latest/admin/Import/#initial-import-of-the-data).
`./utils/setup.php --osm-file india-latest.osm.pbf --all 2>&1 | tee setup.log`. 

<details>
  <summary>Result of check_import_finished. Click to expand.</summary>
  
```
➜  ./utils/check_import_finished.php
Checking database got created ... OK
Checking nominatim.so module installed ... OK
Checking place table ... OK
Checking indexing status ... OK
Search index creation
Checking index idx_word_word_id ... OK
Checking index idx_place_addressline_address_place_id ... OK
Checking index idx_placex_rank_search ... OK
Checking index idx_placex_rank_address ... OK
Checking index idx_placex_pendingsector ... OK
Checking index idx_placex_parent_place_id ... OK
Checking index idx_placex_geometry_reverse_lookuppoint ... OK
Checking index idx_placex_geometry_reverse_lookuppolygon ... OK
Checking index idx_placex_geometry_reverse_placenode ... OK
Checking index idx_location_area_country_place_id ... OK
Checking index idx_osmline_parent_place_id ... OK
Checking index idx_osmline_parent_osm_id ... OK
Checking index idx_place_osm_unique ... OK
Checking index idx_postcode_id ... OK
Checking index idx_postcode_postcode ... OK
Checking index idx_search_name_nameaddress_vector ... OK
Checking index idx_search_name_name_vector ... OK
Checking index idx_search_name_centroid ... OK
Checking search indices are valid ... OK
```
</details>

Later I found that some data is missing from my server. Like if I search for `Uttarakhand` the relation with osm_id `9987086` doesn't show up.

<details>
  <summary><code>http 'http://my-server.internal/nominatim/search.php?q=Uttarakhand&polygon_geojson=1&format=jsonv2'</code></summary>
  
```json
[
    {
        "boundingbox": [
            "27.4417376",
            "32.6417376",
            "76.489691",
            "81.689691"
        ],
        "category": "place",
        "display_name": "Uttarakhand, India",
        "geojson": {
            "coordinates": [
                79.089691,
                30.0417376
            ],
            "type": "Point"
        },
        "importance": 0.66,
        "lat": "30.0417376",
        "licence": "Data © OpenStreetMap contributors, ODbL 1.0. https://osm.org/copyright",
        "lon": "79.089691",
        "osm_id": 2240945388,
        "osm_type": "node",
        "place_id": 170033,
        "place_rank": 8,
        "type": "state"
    }
]
```
</details>

Response from Official Server (I removed some elements from coordinates array manually to reduce output)
<details>
  <summary><code>http 'https://nominatim.openstreetmap.org/search.php?q=Uttarakhand&polygon_geojson=1&format=jsonv2'</code></summary>
  
```json
[
    {
        "boundingbox": [
            "28.7243243",
            "31.459016",
            "77.57133",
            "81.044789"
        ],
        "category": "boundary",
        "display_name": "Uttarakhand, India",
        "geojson": {
            "coordinates": [
                [
                    [
                        77.57133,
                        30.4092517
                    ],
                    [
                        77.57133,
                        30.4092517
                    ]
                ]
            ],
            "type": "Polygon"
        },
        "icon": "https://nominatim.openstreetmap.org/ui/mapicons//poi_boundary_administrative.p.20.png",
        "importance": 0.7484312119661475,
        "lat": "30.091993549999998",
        "licence": "Data © OpenStreetMap contributors, ODbL 1.0. https://osm.org/copyright",
        "lon": "79.32176659343018",
        "osm_id": 9987086,
        "osm_type": "relation",
        "place_id": 259569642,
        "place_rank": 8,
        "type": "administrative"
    },
    {
        "boundingbox": [
            "27.4417376",
            "32.6417376",
            "76.489691",
            "81.689691"
        ],
        "category": "place",
        "display_name": "Uttarakhand, India",
        "geojson": {
            "coordinates": [
                79.089691,
                30.0417376
            ],
            "type": "Point"
        },
        "importance": 0.66,
        "lat": "30.0417376",
        "licence": "Data © OpenStreetMap contributors, ODbL 1.0. https://osm.org/copyright",
        "lon": "79.089691",
        "osm_id": 2240945388,
        "osm_type": "node",
        "place_id": 21215155,
        "place_rank": 8,
        "type": "state"
    }
]
```
</details>

This is one instance which i know of, it might be possible that other places are missing too. I have tried running the update command, but it doesn't seem to help. 

Is there any way to get these missing details?

**Software Environment (please complete the following information):**
- Nominatim version: `3.5.2`
- Postgresql version: `postgres (PostgreSQL) 10.15 (Ubuntu 10.15-0ubuntu0.18.04.1)`
- Postgis version:  `POSTGIS="2.4.3 r16312" PGSQL="100" GEOS="3.6.2-CAPI-1.10.2 4d2925d6" PROJ="Rel. 4.9.3, 15 August 2016" GDAL="GDAL 2.2.3, released 2017/11/20" LIBXML="2.9.4" LIBJSON="0.12.1" LIBPROTOBUF="1.2.1" RASTER`
- OS: Ubuntu 18.04.5 LTS

**Hardware Configuration (please complete the following information):**
- RAM: 32GB
- number of CPUs: 8

**Postgresql Configuration:**
Nothing

**Comment by mtmail** [comment]
Nominatim didn't link the relation (https://www.openstreetmap.org/relation/9987086) and node (https://www.openstreetmap.org/node/2240945388) of the state. Link means Nominatim should treat both as being the same place and merge data from both. I linked them together now by setting the `label` role on the relation and adding `wikipedia` and `wikidata` tags to the node (same values as the relation obviously).

Now https://nominatim.openstreetmap.org/ui/search.html?q=Uttarakhand shows the relation as first result. That server does minutely updates, with extracts from geofabrik you need to wait until tomorrow (if you setup daily updates).

If that doesn't resolve the issue:

https://www.openstreetmap.org/relation/9987086 is at the border of the country. Sometimes the boundaries geofabrik used to extracts the country from the world data overlap, causing a small section of the relation to be outside, thus breaking the relation. They use a *.poly file, see https://download.geofabrik.de/asia/india.html On your server check if the relation shows up on `http://my-server.internal/nominatim/polygons.php?format=html`

**Comment by Suraj-Yadav** [comment]
@mtmail  Thanks a lot 👍 .
After running the update it shows up correctly on my server.
