### ISSUE TITLE
make issue

### ISSUE THREAD

**Issue by raviteja-karri** [osm-search/Nominatim#2156]
We are upgrading our platforms from Ubuntu 16 x86 architecture to ubuntu 20.04 arm architecture.
After pulling the latest codebase and running step 1 in readme file I am unable to find ./build/website directory

**Comment by lonvia** [comment]
There are 3 steps in that readme. The website directory is only available after step 2 to has run.

**Comment by raviteja-karri** [comment]
I ran all the steps and cant find ./build/website directory

**Comment by raviteja-karri** [comment]
cmake command results the following log
`
-- Configuring done
-- Generating done
-- Build files have been written to: <path to build folder>

`
still I cant see website in it
I ran all the three commands
