### ISSUE TITLE
Make issue

### ISSUE THREAD

**Issue by raviteja-karri** [osm-search/Nominatim#2158]
We have a working Nominatim setup with Ubuntu 16 x_86 now we want to migrate it to Ubuntu 20 arm architecture.
In the process of installing nominating I have following all the 3 steps from readme but I cant find the website folder in the build folder. Given below are the list of folders in the build at the end.

CMakeCache.txt       compile_commands.json  docs        module     Testing
CMakeFiles           CTestTestfile.cmake    Makefile    nominatim     utils
cmake_install.cmake  DartConfiguration.tcl  mkdocs.yml  osm2pgsql 

I dont have any issue with the pdf file while extracting the data. I have ended up the same way thrice.

**Comment by mtmail** [comment]
Can you post the URL of the README you're following?  And the commands you ran? Which Nominatim version are you installing? Is it an update of an existing Nominatim installation (if so: which version) or a new installation?

**Comment by raviteja-karri** [comment]
This is a new installation.
I am pulling the latest version in this current project. 
https://github.com/osm-search/Nominatim

**Comment by mtmail** [comment]
Please try installing the stable version, currently 3.6.0, from http://nominatim.org/ and the full installation instructions http://nominatim.org/release-docs/latest/admin/Installation/

In the Readme on https://github.com/osm-search/Nominatim please note the paragraph in **bold** that explains how and where to report installation issues.
