### ISSUE TITLE
Search by name not working

### ISSUE THREAD

**Issue by MartinStokelj** [osm-search/Nominatim#2165]
## What did you search for?
I am using search
url = "https://nominatim.openstreetmap.org/search?q=ljubljana&format=xml"
I also can't ping address
https://nominatim.openstreetmap.org

## What result did you get?
we = {"The remote name could not be resolved: 'nominatim.openstreetmap.org'"}

## What result did you expect?
To get response for searh location.

**Comment by lonvia** [comment]
This is not an issue with the software. It's an operational issue. Given that resolving nominatim.openstreetmap.org works fine here, it is likely an operational issue on your side.
