### ISSUE TITLE
CMake Error while building

### ISSUE THREAD

**Issue by sggts04** [osm-search/Nominatim#2170]
**Describe the bug**
When building Nominatim, cmake throws an error

```
      CMake Error at CMakeLists.txt:241 (install):
      install TARGETS given target "osm2pgsql" which does not exist in this
      directory.
```

**To Reproduce**
`cmake $USERHOME/Nominatim`

**Software Environment (please complete the following information):**
- Nominatim version: Latest
- Postgresql version: 10
- Postgis version: 2.4
- OS: Ubuntu 18.04

**Comment by lonvia** [comment]
This works on my Debian stable, so I suspect that the older cmake version in 18.04 does something differently. I'll have a look. In the meantime, if you can switch to Ubuntu 20.04 then that is a safer bet for current master.
