### ISSUE TITLE
Wrong district on Brazil

### ISSUE THREAD

**Issue by leontino** [osm-search/Nominatim#2179]
## What did you search for?

District Centro in Fortaleza, Ceara, Brazil.

## What result did you get?
Centro, Pacoti, Ceara, Brazil (this is a other city)

https://nominatim.openstreetmap.org/ui/details.html?osmtype=N&osmid=2752343510&class=natural

## What result did you expect?

https://nominatim.openstreetmap.org/ui/details.html?osmtype=R&osmid=5522105&class=boundary

**Is the result in the right place and just named wrongly?** 

It's a wrong place

Centro from Fortaleza, Ceara, Brazil

**Is the result missing completely?**

No

**Comment by mtmail** [comment]
Can you add the full URL of the search? When I search for `District Centro in Fortaleza, Ceara, Brazil` (https://nominatim.openstreetmap.org/ui/search.html?q=District+Centro+in+Fortaleza%2C+Ceara%2C+Brazil), with or withou the `in`, I get no result.

**Comment by leontino** [comment]
I don't found without In, but show correctly reply in the 7º position.

Em dom., 21 de fev. de 2021 22:24, mtmail <notifications@github.com>
escreveu:

**Comment by mtmail** [comment]
Did you search for 'District Centro' when the map was showing 'Fortaleza, Ceara, Brazil'? Or did you search for 'District Centro, Fortaleza, Ceara, Brazil'? I can't see any results. We might need a screenshot of the URL or the full URL.

**Comment by leontino** [comment]
I've search for District Centro, Fortaleza, Ceara, Brazil and results don't
show in Fortaleza City, but show in another city in same state.
[image: image.png]

Em seg., 22 de fev. de 2021 às 07:11, mtmail <notifications@github.com>
escreveu:

**Comment by lonvia** [comment]
There is at least one tagging error here that needs fixing: https://www.openstreetmap.org/node/2752343510 doesn't look like there is a mountain peak called Centro.

The remainder is a question of reordering results that we can probably do something about.

**Comment by lonvia** [comment]
Closing in favour f underlying issue #2268.
