### ISSUE TITLE
Use closest street as parent for associatedStreet relations with multiple street members

### ISSUE THREAD

**Issue by Damarisse** [osm-search/Nominatim#2183]
Hello,

I have searched for the address '142 avenue Ledru-Rollin Paris' in OpenStreetMap:
https://www.openstreetmap.org/search?query=142%20avenue%20ledru-rollin%20paris#map=19/48.85490/2.37839

The result is in the right place.

But the district for this address is not correct. It should be 'Quartier de la Roquette Paris 11e arrondissement', instead of 'quartier des Quinze-Vingts Paris 12e arrondissement'.

Best regards,

Damarisse

**Comment by lonvia** [comment]
That's the curse of associatedStreet relations. The housenumber is part of [this relation](https://www.openstreetmap.org/relation/6949986) which goes through two different Quartiers. When looking for the parent street, we just take the first street in the relation that can be found which then might be in the wrong Quartier. We'd need to look for the closest street instead when there are multiple streets in the relation.

I'm updating the issue title to reflect the underlying issue.
