### ISSUE TITLE
GB railway station refs

### ISSUE THREAD

**Issue by boothym** [osm-search/Nominatim#2184]
Railway stations in Great Britain have have a three letter code, e.g. EDB for Edinburgh which is mapped in OSM as **ref:crs** https://www.openstreetmap.org/node/7149998196

It would be great if could Nominatim include this tag so that users can search for the three letter codes - similar to how iata and icao are included for airports.

**Comment by lonvia** [comment]
We are unlikely to include such special interest refs in the near future. Short references tend to cause a lot of mixups thus degrading other search results. Until Nominatim has a solution for this, I'd rather see less refs indexed than more.

**Comment by boothym** [comment]
So what's the solution to this so that these can be used for searching? Because they are very useful for jumping straight to a railway station as Nominatim doesn't always find the correct location first time, for example: https://nominatim.openstreetmap.org/ui/search.html?q=edinburgh+railway+station goes to a bus stop miles away.

Should the ref:crs be changed back to just **ref** or one of the following refs? 

 ["ref", "int_ref", "nat_ref", "reg_ref", "loc_ref", "old_ref", "iata", "icao", "pcode"],

**Comment by mtmail** [comment]
You can use 'railway station in edinburgh' https://nominatim.openstreetmap.org/ui/search.html?q=railway+station+in+edinburgh

'railway station in' is a special phrase (https://wiki.openstreetmap.org/wiki/Nominatim/Special_Phrases/EN) and then Nominatim looks at the type of place rather than a name match.

**Comment by lonvia** [comment]
Please don't start tagging for the search engine. Just leave the tagging as is. If at some later point Nominatim becomes better at handling short references, we might want to include selected special refs again. It's just not possible at the moment.

That said, given the number of people on the planet who know the CRS references of British railway stations versus the number of people who don't, I'd say that improving the results for 'Edinburgh railway station' has the priority.

**Comment by boothym** [comment]
@mtmail thanks - but to me saying "railway station in XYZ" makes it seem like I'm doing a search to find all the stations in a certain place. And even when doing that search, it only show two railway stations, when there are 12 in the Edinburgh council area.

@lonvia I understand not tagging for the search engine, but I do wonder whether ref:crs is needlessly specific, when ref would suffice? I mean other OSM objects don't create their own ref:xyz tag when ref works fine. 

I added some ref tags to stations, but another user came along and moved them to ref:crs for all stations. 

Though these probably aren't as obscure as you might think - if you search on a British train times/ticket website it will show them alongside the station name and they are used in urls etc
![natr](https://user-images.githubusercontent.com/16965772/114790474-bbf78b00-9d7c-11eb-91e5-979544d3aa40.jpg)
