### ISSUE TITLE
Import Tiger data directly from tarball

### ISSUE THREAD

**Issue by lonvia** [osm-search/Nominatim#2187]
The [function for importing TIGER data](https://github.com/osm-search/Nominatim/blob/204fe20b4b660bdf34953b87763f9f7d06525a28/lib-php/setup/SetupClass.php#L430) still needs porting to Python. While doing this, we should add support to import the data directly from the tarball, so that the user no longer needs to have the unpacked version on the disk.

Some helpful pointers where to look for code examples:

* porting a PHP setup function to Python, see for example [load-data](https://github.com/osm-search/Nominatim/commit/57db5819efb1eac7497aca2dbdb2493a67bd33f9)
* [Python tarfile support](https://docs.python.org/3.8/library/tarfile.html)
* [running asynchronous SQL commands](https://github.com/osm-search/Nominatim/blob/e14e7c6235a40dbec451146bcb3aaec013d659c9/nominatim/tools/database_import.py#L222) for parallel execution

**Comment by darkshredder** [comment]
I would like to work on this issue if it's still open.Moreover I have some doubts.

- Do I need to add these changes in add-data or transitions subcommand?
- While using tarfile support. Do I need to extract it ,use it and then delete it or just read files and run those sql files?

**Comment by lonvia** [comment]
Welcome, @darkshredder. This issue is still waiting for an interested taker.

> Do I need to add these changes in add-data or transitions subcommand?

Both, actually. I would suggest you create your own python file for this task under `nominatim/tools/tiger_data.py` with a public function `add_tiger_data()`. Then you can replace the calls to `run_legacy_script()` in these two places with your new function.

> While using tarfile support. Do I need to extract it ,use it and then delete it or just read files and run those sql files?

The idea was to extract the content of the tarfile one-by-one into memory and run the resulting "SQL memory blob" against one of the asynchronous SQL connections. tarfile's `extractfile()` should do the trick.

NB: ideally the function can handle packed and unpacked content in the end, i.e. if the given Tiger data path is a directory, read all the files it contains, if it is a file handle it like a tarball.
