### ISSUE TITLE
Compile Nominatim without cloning osm2pgsql cloned and without PHP installed

### ISSUE THREAD

**Issue by Yamakasi** [osm-search/Nominatim#2190]
Hi,

I want to offload PHP to other PHP servers so I like to compile Nominatim without PHP installed.

Is this possible ?

Also I like to not download osm2pgsql when cloning, I want to have only Nominatim to be compiled.

I assume that sharing the nominatim PHP files between my PHP backends and the Nominatim server(s) is enought to make this work ? Without having ngxin/apache local might be impossible ?

I run into these:

```
Cloning into 'Nominatim'...
Submodule 'osm2pgsql' (https://github.com/openstreetmap/osm2pgsql.git) registered for path 'osm2pgsql'
Cloning into '/opt/src/Nominatim/osm2pgsql'...
```

and:

```
CMake Warning at CMakeLists.txt:69 (message):
  pyosmium-get-changes not found (required for updates)


CMake Error at CMakeLists.txt:88 (message):
  PHP binary not found.  Install php or provide location with
  -DPHP_BIN=/path/php
```

Hoping that someone can clear this out.

Thanks!

**Comment by mtmail** [comment]
converting the issue to a discussion
