### ISSUE TITLE
Create a man page for nominatim tool

### ISSUE THREAD

**Issue by lonvia** [osm-search/Nominatim#2201]
Distributions like Debian require that any installed binary comes with a man page, so we need one for the new [nominatim tool](https://nominatim.org/2021/02/25/nominatim-tool.html). For osm2pgsql we've successfully used [argparse-manpage](https://github.com/praiskup/argparse-manpage) to generate a manpage from the docstrings that also create the help text shown with `--help`. The output looks good in general but still needs some tweaking in parts possibly by running a couple of seds over it.

The man page should be checked in and just recreated occasionally by developers when needed. So we'd need a new `make manpage` command that recreates the man page on demand.

The mn page also needs to be properly installed on `make install`.

**Comment by darkshredder** [comment]
I would like to work on this issue if it is available to work on.
