### ISSUE TITLE
Port country name setup to Python

### ISSUE THREAD

**Issue by lonvia** [osm-search/Nominatim#2202]
The function for [adding country names to the word index](https://github.com/osm-search/Nominatim/blob/35f4695b67b50a41caf69378ea13044ea91f1d2c/lib-php/setup/SetupClass.php#L203) still needs porting from PHP to Python. The task is fairly straightforward as only a couple of SQL commands need to be executed. The ported function then also needs some tests.

Some helpful pointers where to look for code examples:
* porting a PHP setup function to Python, see for example [load-data](https://github.com/osm-search/Nominatim/commit/57db5819efb1eac7497aca2dbdb2493a67bd33f9)
* [tests for ported setup functions](https://github.com/osm-search/Nominatim/blob/master/test/python/test_tools_database_import.py)

**Comment by darkshredder** [comment]
I would like to work on this if no one is working on it
