### ISSUE TITLE
Import of special phrases needs porting to Python

### ISSUE THREAD

**Issue by lonvia** [osm-search/Nominatim#2203]
The function to [import special phrases from the OSM wiki](https://github.com/osm-search/Nominatim/blob/master/lib-php/admin/specialphrases.php) still needs porting from PHP to Python. The ported function then needs some testing.

Some helpful pointers where to look for code examples:
* porting a admin functions to Python, see for example [port of check_database functions](https://github.com/osm-search/Nominatim/commit/b169e4c88cd99075c7e932aeb6587c97f51e7ed1)
* [tests for ported setup functions](https://github.com/osm-search/Nominatim/blob/master/test/python/test_tools_database_import.py)

**Comment by AntoJvlt** [comment]
Hello!

I was a casual user of OSM and I am new to Nominatim. I started last week to dive deeper in the OSM world and started with some mapping. I also started to tackle Nominatim and got a local instance running.

I would like to work on this issue as it seems doable for me, as I begin I might ask for help if I am in trouble, if it is ok for you.

Thanks!

**Comment by lonvia** [comment]
Please see https://wiki.openstreetmap.org/wiki/User:Lonvia/GSoC_2021_Nominatim_Projects for recommendations where to ask for help.
