### ISSUE TITLE
Apache config in docs does not work for root level

### ISSUE THREAD

**Issue by otbutz** [osm-search/Nominatim#2207]
Following the documentation at https://nominatim.org/release-docs/3.6.0/admin/Deployment/#configuring-apache and https://nominatim.org/release-docs/3.6.0/admin/Setup-Nominatim-UI/#setting-up-forwarding-in-apache i tried to adapt the config to mirror the behavior of https://nominatim.openstreetmap.org

My first attempt was to simply switch from `RewriteBase "/nominatim/"` to `RewriteBase "/"`:

```
<Directory "/opt/nominatim-ui/dist">
  DirectoryIndex search.html
  Require all granted
</Directory>
Alias /ui /opt/nominatim-ui/dist

<Directory "/opt/nominatim/build/website">
  Options FollowSymLinks MultiViews
  AddType text/html   .php
  Require all granted

  RewriteEngine On

  # This must correspond to the URL where nominatim can be found.
  RewriteBase "/"

  # If no endpoint is given, then use search.
  RewriteRule ^(/|$)   "search.php"

  # If format-html is explicity requested, forward to the UI.
  RewriteCond %{QUERY_STRING} "format=html"
  RewriteRule ^([^/]+).php ui/$1.html [R,END]
  # Same but .php suffix is missing.
  RewriteCond %{QUERY_STRING} "format=html"
  RewriteRule ^([^/]+) ui/$1.html [R,END]

  # If no format parameter is there then forward anything
  # but /reverse and /lookup to the UI.
  RewriteCond %{QUERY_STRING} "!format="
  RewriteCond %{REQUEST_URI}  "!/lookup"
  RewriteCond %{REQUEST_URI}  "!/reverse"
  RewriteRule ^([^/]+).php ui/$1.html [R,END]
  # Same but .php suffix is missing.
  RewriteCond %{QUERY_STRING} "!format="
  RewriteCond %{REQUEST_URI}  "!/lookup"
  RewriteCond %{REQUEST_URI}  "!/reverse"
  RewriteRule ^([^/]+) ui/$1.html [R,END]
</Directory>
Alias / /opt/nominatim/build/website
```

But this caused apache to drop the trailing slash when trying to access the files: `/opt/nominatim/build/websitestatus.php`

I was able to fix this by adding a trailing slash to `Directory` and `Alias` paths:

```
<Directory "/opt/nominatim-ui/dist/">
...
Alias /ui /opt/nominatim-ui/dist/

<Directory "/opt/nominatim/build/website">
...
Alias / /opt/nominatim/build/website/
```

**Comment by otbutz** [comment]
We could also simplify the rules handling `.php`

```
   RewriteRule ^([^/\.]+)(?:.php)? ui/$1.html [R,END]
```

**Comment by lonvia** [comment]
I remember that `Alias` in Apache is tricky. The trailing slashes for source and destination need to be the same. So my guess would be that you only need to fix the line `Alias / /opt/nominatim/build/website/` to make it work. I've usually also made sure the Directory line matches.

We've switched to nginx on osm.org, so I don't really have a working example from production to offer here.

**Comment by otbutz** [comment]
I also think that an exclusion for `status.php` is missing

**Comment by otbutz** [comment]
> I remember that `Alias` in Apache is tricky. The trailing slashes for source and destination need to be the same. So my guess would be that you only need to fix the line `Alias / /opt/nominatim/build/website/` to make it work. I've usually also made sure the Directory line matches.

I tried only editing the Alias but that caused the path resolution to go completely haywire.

**Comment by lonvia** [comment]
`status.php?format=html` is an invalid URL. So you'd end up with a 404, which is a correct response. (Although I do like the idea of a status page in nominatim-ui. Let me open a ticket for that.)

> I tried only editing the Alias but that caused the path resolution to go completely haywire.

Hmm, I'm not completely surprised. A consistent version that always includes the slashes is probably better anyway. Do you have a test setup to confirm that that also works with the `/nominatim` in the example setup? Then I'd be happy to change the documentation to include the slashes as well. I really don't remember if I excluded them accidentally or on purpose at the time.

**Comment by otbutz** [comment]
> `status.php?format=html` is an invalid URL. So you'd end up with a 404, which is a correct response. (Although I do like the idea of a status page in nominatim-ui. Let me open a ticket for that.)

```
  # If no format parameter is there then forward anything
  # but /reverse and /lookup to the UI.
  RewriteCond %{QUERY_STRING} "!format="
  RewriteCond %{REQUEST_URI}  "!/lookup"
  RewriteCond %{REQUEST_URI}  "!/reverse"
  RewriteRule ^([^/]+).php ui/$1.html [R,END]
```

Wouldn't that rule cause `/status.php` to be rewritten to `ui/status.html` ?

> Hmm, I'm not completely surprised. A consistent version that always includes the slashes is probably better anyway. Do you have a test setup to confirm that that also works with the `/nominatim` in the example setup? Then I'd be happy to change the documentation to include the slashes as well. I really don't remember if I excluded them accidentally or on purpose at the time.

I got it set up in a docker container. I will add my proposed changes and test for `/` and `/nominatim` and report back.

**Comment by lonvia** [comment]
> Wouldn't that rule cause /status.php to be rewritten to ui/status.html ?

Ah, yes. And it looks like I forgot that in the nginx config, too.

> `Alias /nominatim /opt/nominatim/build/website/`

No slash after `/nominatim`?

**Comment by otbutz** [comment]
We don't have one for `/nominatim/ui` either?

PS: Updated my post because i forgot the `/nominatim` prefix in the ui alias

**Comment by lonvia** [comment]
> Edit: Alias /nominatim/ breaks the page as only localhost:8080/nominatim/ with a trailing slash is recognized.

Aha, that means the documentation is written like that on purpose. Actually, in your case, when you run Nominatim from the root URL, you shouldn't be using `Alias` for the website at all. Just set `DocumentRoot` to `/opt/nominatim/build/website/` and all should work as expected.

**Comment by lonvia** [comment]
Did this work in the end without any Alias at all?
