### ISSUE TITLE
Cannot reach result when searching with param Country = China

### ISSUE THREAD

**Issue by minhthienlk** [osm-search/Nominatim#2208]
With this searching url: https://nominatim.openstreetmap.org/ui/search.html?country=china
-> it returns no data

With this search url: https://nominatim.openstreetmap.org/ui/search.html?state=china
-> it returns China country correctly.

**Comment by lonvia** [comment]
This is a data problem in OSM. Somebody has demoted China from country to state by changing adminLevel from 2 to 4 in https://www.openstreetmap.org/changeset/100474447. Looks like the entire changeset is bogus on should be reverted.
