### ISSUE TITLE
Adding Pull Request template

### ISSUE THREAD

**Issue by darkshredder** [osm-search/Nominatim#2209]
**Is your feature request related to a problem? Please describe.**
Currently when a person wants to create a pull request there is not standard template to write it's description.

**Describe the solution you'd like**
We should use a pull request template. Moreover this would also ease the work of project maintainers.

**Additional context**
I would like to work on this issue if it is approved.

**Comment by lonvia** [comment]
From a maintainer point of view, I am quite content with the free-form descriptions of PRs so far. We have some hints in CONTRIBUTING.md and CI runs check for the formal correctness of the PRs.

That doesn't mean PR template couldn't be helpful as a guidance for new contributors. Could you elaborate a bit what kind of information you were expecting in a template?

**Comment by darkshredder** [comment]
Actually when I was making my first PR I was expecting something like this 

> 
> 
> ## Description
> 
> 
> ## Related Issue
> 
> 
> 
> 
> 
> ## Motivation and Context
> 
> 
> ## Reviewers
> 
> 
> ## How Has This Been Tested?
> 
> 
> 
> 
> ## Screenshots (if appropriate):
> 
> 
> ## Types of changes
> 
> - [ ] Bug fix (non-breaking change which fixes an issue)
> - [ ] New feature (non-breaking change which adds functionality)
> - [ ] Breaking change (fix or feature that would cause existing functionality to change)
> - [ ] Other
> 
> ### Checklist:
> 
> 
> - [ ] My code follows the code style (modified PEP8) of this project.
> - [ ] My change requires a change to the documentation.
> - [ ] I have updated the documentation accordingly.

But I didn't get something like this and thus was confused what to write in PR description and in what manner so I created an issue for this

**Comment by lonvia** [comment]
We have been discussing this among the maintainers and we think that the guidelines in CONTRIBUTING.md are sufficient.
