### ISSUE TITLE
Small hamlet instead of large suburb returned as top search result

### ISSUE THREAD

**Issue by boothym** [osm-search/Nominatim#2215]
I searched for Leith: https://nominatim.openstreetmap.org/ui/search.html?q=leith

I expected to get Leith, Edinburgh, Scotland - which is tagged as a suburb with a population of 50,000 on OSM.

Instead I got Leith, North Dakota, USA - which is an admin boundary with a population of 25 and also tagged as a hamlet node, 

However the latter also has a city boundary: https://www.openstreetmap.org/relation/181515 - is that the reason for it appearing higher in the search results?

**Comment by mtmail** [comment]
Having a wikipedia URL, wikidata id is also a ranking factor. https://nominatim.org/release-docs/latest/develop/Ranking/#search-rank

You can probably add https://en.wikipedia.org/wiki/Leith to the place in OpenStreetMap data. You find the wikidata id ("Q<number>") in the left navigation "Wikidata item"

**Comment by lonvia** [comment]
Adding a wikipedia or Wikidata tag to Leith, Edinburgh will fix this.
