### ISSUE TITLE
Search for street+housenumber returns address node of different street

### ISSUE THREAD

**Issue by hungerburg** [osm-search/Nominatim#2224]
## What did you search for?

https://www.openstreetmap.org/search?query=Ing.-Etzel-Stra%C3%9Fe%2055%2C%20Innsbruck
https://nominatim.openstreetmap.org/search?format=json&street=Ing.-Etzel-Stra%C3%9Fe%2055&city=Innsbruck

## What result did you get?

In order of result set:
1) Viaduktbogen 55 - https://www.openstreetmap.org/node/4917537700
2) Ing Etzel Straße 55 - https://www.openstreetmap.org/way/93787370

## What result did you expect?

Result set either sorted 2) 1), or even only showing 2)

## Further details

From the displayed name it looks like the street name "Viaduktbogen" is stripped from place 1) As a matter of fact, there is no such street anywhere around, but this is still a valid postal address; it is the name of the railway viaduct.

No idea how widely such mismatches occur. But I cannot close the OSM-note there, before this has been diligently processed :)

**Comment by lonvia** [comment]
This is a tagging issue. The node is tagged with `addr:street=Viaduktbogen` but no such street exists, so the `addr:street` tag is ignored and the house number assigned to the closest street.  Use `addr:place=Viaduktbogen` instead to indicate that the house number is not attached to a street and all will be well.

**Comment by hungerburg** [comment]
Reading what the wiki says, there must exist a  "place=Viaduktbogen" for this to work out, such a place does not exist either and making one up is not considered good pratice, I suppose.

Maybe there is another way: A little more to the east, part of the street recently got a "name:left" key. Looks like nominatim can reference `name:left|right` in its search for associated street - c.f. https://nominatim.openstreetmap.org/ui/details.html?osmtype=W&osmid=524863068&class=building - it doesn't even have to know, where left|right is.

**Comment by lonvia** [comment]
No, you don't need to have a place node anymore.

**Comment by hungerburg** [comment]
Thank you Lonvia, name: looks to me quite true to the ground, and it is less intrusive, fewer things need change. Looking at where a section of the street has `name:left`, https://nominatim.openstreetmap.org/ui/details.html?osmtype=N&osmid=4917537689&class=place - nominatim does not use it.

**Comment by lonvia** [comment]
name:left/right is for cases where a street itself has two names. I don't see how this is relevant here. I doubt anybody would refer to the street as 'Viaduktbogen'. The case is pretty clear here imo. The address does not refer to a street, so don't use addr:street. 

Closing as data issue.

**Comment by hungerburg** [comment]
True, nobody calls the street that name; Can now go to work on the addresses.
