### ISSUE TITLE
Also search in artwork_subject

### ISSUE THREAD

**Issue by richlv** [osm-search/Nominatim#2232]
**Is your feature request related to a problem? Please describe.**
tourism=artwork sometimes have artwork_subject tagged that is different from name=*.
It would be very helpful to find objects by the artwork_subject tag.
Specific example: https://www.openstreetmap.org/node/8068046961 .

**Describe the solution you'd like**
Finding objects by artwork_subject.

**Describe alternatives you've considered**
Tagging artwork subject in the name like "Artwork name (Artwork subject)".

**Additional context**
Example object: https://www.openstreetmap.org/node/8068046961 .

**Comment by lonvia** [comment]
The wiki is very vague on what this tag actually means but it looks to be a categorical tag. So it would fall under the category of finding objects by tag type rather than by name. This is currently out of scope for Nominatim for subtags.

**Comment by richlv** [comment]
Thank you, it indeed is not super-consistent. Sometimes it's a specific subject, sometimes it's used as a category. That would be great to split up. Maybe in 10 years :)
