### ISSUE TITLE
XML format: more_url points to localhost, not base URL

### ISSUE THREAD

**Issue by mtmail** [osm-search/Nominatim#2236]
## What did you search for?

https://nominatim.openstreetmap.org/search.php?format=xml&city=berlin

## What result did you get?

XML includes `more_url="https://localhost/search.php/?city=berlin&exclude_place_ids=566...`

## What result did you expect?

`more_url="https://nominatim.openstreetmap.org/search.php?city=berlin&exclude_place_ids=566...`

or relative URL

`more_url="/search.php?city=berlin&exclude_place_ids=566...`

`more_url="?city=berlin&exclude_place_ids=566...`

**Comment by darkshredder** [comment]
I think we can easily fix this issue by removing this if statement.
https://github.com/osm-search/Nominatim/blob/28b4fb12b684a5c76ca24002ba1ae19ce2e22c87/lib-php/website/search.php#L69

**Comment by darkshredder** [comment]
I think we can fix this issue by changing this absolute URL with a relative URL.
https://github.com/osm-search/Nominatim/blob/28b4fb12b684a5c76ca24002ba1ae19ce2e22c87/lib-php/website/search.php#L74

I would like to work on this issue if I m correct.

**Comment by lonvia** [comment]
The absolute URL is needed here, so that the caller can use the URL directly to send further requests. I think we should be using HTTP_HOST instead of SERVER_NAME. This will be forwarded correctly through PHP-fpm.
