### ISSUE TITLE
No result for object with building:part=university

### ISSUE THREAD

**Issue by istefanos** [osm-search/Nominatim#2237]
## What did you search for?
teaching center wien

https://nominatim.openstreetmap.org/ui/search.html?q=teaching+center+wien

First I found the issue here: https://www.openstreetmap.org/search?query=teaching%20center%20wien#map=19/48.22193/16.36053

## What result did you get?
https://nominatim.openstreetmap.org/ui/details.html?osmtype=N&osmid=1466988216&class=amenity
https://nominatim.openstreetmap.org/ui/details.html?osmtype=W&osmid=247495121&class=building

## What result did you expect?
https://www.openstreetmap.org/way/452432519

**Is the result in the right place and just named wrongly?** 
It is correct.

Teaching Center

**Is the result missing completely?**
Yes

 https://www.openstreetmap.org/way/452432519

**Comment by lonvia** [comment]
This looks rather like a mistagging. building:part is a tag for 3D mapping and used to describe architectural features of a part of a building. It's usually not named. The "Teaching Center" seems to be a part of a university (a department?). You should find a better tag to describe it.

**Comment by istefanos** [comment]
Thanks, department could be wright.

Adding 'department=teaching_center' would be the solution?
https://wiki.openstreetmap.org/wiki/Tag:amenity%3Duniversity#Faculties_and_departments

**Comment by lonvia** [comment]
These kind of tagging discussions are out of scope for this issue tracker. You could try the [tagging mailinglist](https://lists.openstreetmap.org/listinfo/tagging) or ask your local community.
