### ISSUE TITLE
Addresses exist but not found

### ISSUE THREAD

**Issue by astricus** [osm-search/Nominatim#2238]
## What did you search for?
Arnulfstraße 60
https://nominatim.openstreetmap.org/ui/search.html?q=Arnulfstra%C3%9Fe+60

## What result did you get?
Only **one** place in Rosenheim

## What result did you expect?
Several results in different cities in München, Berlin, Trier, Rosenheim.

**Is the result in the right place and just named wrongly?** 
No

**Is the result missing completely?**
No

Here are the missing addresses:
https://nominatim.openstreetmap.org/ui/search.html?q=Arnulfstra%C3%9Fe+60+M%C3%BCnchen
https://nominatim.openstreetmap.org/ui/search.html?q=Arnulfstra%C3%9Fe+60+Berlin
https://nominatim.openstreetmap.org/ui/search.html?q=Arnulfstra%C3%9Fe+60+Trier
Maybe there are some others

## Further details

The right address can only be found if the city is added in the query. Without the city the result is unexpected.

**Comment by lonvia** [comment]
There is a [comment in the code](https://github.com/osm-search/Nominatim/blob/28b4fb12b684a5c76ca24002ba1ae19ce2e22c87/lib-php/SearchDescription.php#L613) that narrowing down search to housenumbers gets too expensive with the current way of querying. Although looking at it now, I wonder if a clever index can't help here.
