### ISSUE TITLE
historical administrative boundaries should not be used for reverse geocoding

### ISSUE THREAD

**Issue by donalhunt** [osm-search/Nominatim#2239]
The algorithm that nominatim uses to determine the structured address, includes historical administrative boundaries. While these are no longer used directly in day-to-day life (e.g. for addresses), there is value in having them mapped.

Example geocoding: https://www.openstreetmap.org/search?whereami=1&query=54.34657%2C-7.65026#map=17/54.34657/-7.65026
Current address returned: Windmill Heights, Windmill Hill, **_Enniskillen South ED,_** Enniskillen, County Fermanagh, Northern Ireland, BT74 5HD, United Kingdom
Expected address: Windmill Heights, Windmill Hill, Enniskillen, County Fermanagh, Northern Ireland, BT74 5HD, United Kingdom

My understanding is that could be dealt with by tuning the ranks but suspect that may be problematic since Northern Ireland (where we have observed this) is part of the UK.

Upon reviewing some of the codebase, it may make sense to adjust the isAdminBoundary function ([link](https://github.com/osm-search/nominatim-ui/blob/21bcfb32a13839ff8c69a452d09e294da800a15a/src/lib/helpers.js#L70)) to ignore historical boundaries (i.e. relations with historic=yes).

Opening this issue to track the discussion and identify potential solutions. If this is better filed in the osm-search/Nominatim repository please let me know! :)

**Comment by lonvia** [comment]
That's unusual tagging for a historical boundary and one that I'd rather not see supported. An auxiliary tag should never invalidate a main tag. I'm sure there is some boundary=historical tagging schema around for this.
