### ISSUE TITLE
Problem with nomination in Friuli Venezia

### ISSUE THREAD

**Issue by cicciobenza** [osm-search/Nominatim#2240]
Hi, we have found that all the municipalities of the Friuli Venezia Giulia region (Italy) do not have the denomination of the province of reference.

For example R179163 (Palmanova) should have UDINE (UD) as its province. This happens for all municipalities.

**Comment by mtmail** [comment]
https://www.openstreetmap.org/relation/179296 relation was broken. Some members near the Italian-Slovenian border were is the wrong order. I fixed the relation.

**Comment by lonvia** [comment]
[Wikipedia](https://en.wikipedia.org/wiki/Province_of_udine) tells me that the province of Udine no longer exists. That would explain its absence.

**Comment by cicciobenza** [comment]
This is correct for all the provinces of friuli venezia giulia that have lost their functions as local authorities but instead remain unchanged as constituencies of state administrations in the territory. Consequently they should always have their "province abbreviation" according to ISTAT administrative unit file "
CLASSIFICAZIONE
CODICI STATISTICI DELLE UNITÀ AMMINISTRATIVE TERRITORIALI: COMUNI, CITTÀ METROPOLITANE, PROVINCE E REGIONI"

**Comment by lonvia** [comment]
That is something that needs to be sorted out with the Italian OpenStreetMap community. Nominatim can just show what is in the OSM data.
