### ISSUE TITLE
Nominatim assumes wrong street, as result address not found at all

### ISSUE THREAD

**Issue by szydzio** [osm-search/Nominatim#2241]
## What did you search for?

Poland, Leszno, Osiedle Józefa Sułkowskiego 4

## What result did you get?
No address found at all

## What result did you expect?
Find [this node](https://www.openstreetmap.org/node/2385637754)

**Is the result missing completely?**

[Details for this address](https://nominatim.openstreetmap.org/ui/details.html?osmtype=N&osmid=2385637754) reveals it's assigned to a wrong street (Parkowa instead of Osiedle Józefa Sułkowskiego). As result the address is not found, searching for it returns [only nearby highways](https://www.openstreetmap.org/search?query=Poland%2C%20Leszno%2C%20Osiedle%20J%C3%B3zefa%20Su%C5%82kowskiego%204#map=19/51.83873/16.59160).

## Further details

Further nodes are affected as well: 2385637775, 2385637782, 2385637695, 2385637698, 2385637701, 2385637704, 2385637709, 2385637712, 2385637715, 2385637718, 2385637721, 2385637724 and 2385637734.

**Comment by lonvia** [comment]
The housenumber nodes haven't picked up the name change. I've updated the server and opened a separate issue for the underlying cause (#2242).
