### ISSUE TITLE
Adding Code Coverage to the Project

### ISSUE THREAD

**Issue by darkshredder** [osm-search/Nominatim#2245]
**Is your feature request related to a problem? Please describe.**
Currently, we don't have the actual statistics about how much code is being tested through various tests we have implemented.

**Describe the solution you'd like**
To solve this issue, we can use [codecov](https://about.codecov.io/) which supports different languages, provides a badge to show the percentage of Code Coverage, can be integrated easily with Github-Actions and can also act as a bot to give comments in pull requests showing changes in code coverage due to pull request shown [here](https://docs.codecov.io/docs/pull-request-comments#branches)

**Additional context**
I have tried implementing it for Nominatim results can be found by clicking on the badge below.

[![codecov](https://codecov.io/gh/darkshredder/Nominatim/branch/code-coverage/graph/badge.svg?token=7UX4CNKAFB)](https://codecov.io/gh/darkshredder/Nominatim)

**Comment by lonvia** [comment]
I've used a local installation of SonarQube for looking at coverage numbers as I found it much more useful to have the numbers while developing. But I don't mind setting up codecov, if somebody provides a PR. ;)

The main issue in the example you show is that it doesn't include the numbers for the BDD API tests, which provide most of the coverage for the PHP code. There is some info about setting up BDD code coverage [in the documentation](https://nominatim.org/release-docs/develop/develop/Testing/#code-coverage). Maybe you can see if you can get it included into the codecov numbers? Feel free to ask if the instructions turn out to be outdated.

**Comment by darkshredder** [comment]
Sure, I will be creating a PR soon.
