### ISSUE TITLE
Street in Forney, Texas not assigned to Forney

### ISSUE THREAD

**Issue by Tiree2021** [osm-search/Nominatim#2249]
## What did you search for?

https://nominatim.openstreetmap.org/ui/search.html?street=15936+Wiser+Rd&city=Forney&county=Kaufman&state=Texas&country=USA&postalcode=75126

## What result did you get?
The result came up as not found

## What result did you expect?
I expected to see my home address

**Is the result in the right place and just named wrongly?** 
Not even found

15936 Wiser Rd, Forney, TX 75126

**Is the result missing completely?**
YES

## Further details

The address is as I wrote,   The side closest to I-20 is Mesquite and where I live is still Forney, Texas.  Can look up on google maps

**Comment by mtmail** [comment]
OpenStreetMap has Wiser Rd https://www.openstreetmap.org/way/21052546 (https://nominatim.openstreetmap.org/ui/details.html?osmtype=W&osmid=21052546&class=highway) but not assigned to a city.

The city of Forney has smaller boundaries https://www.openstreetmap.org/relation/115451 Those are the exact ones from government sources and in the United States sometimes don't reflect what residents think their location is. I think related to https://github.com/osm-search/Nominatim/issues/1120

**Comment by lonvia** [comment]
The address is missing in OpenStreetMap. Just add addr:housenumber + addr:city to the house in question and all will be well. See also [Fix the map](https://www.openstreetmap.org/fixthemap) and [Address mapping](https://wiki.openstreetmap.org/wiki/Addresses).

Closing as data issue.
