### ISSUE TITLE
Search error houses with cyrillic letter in number

### ISSUE THREAD

**Issue by 7171bel** [osm-search/Nominatim#2254]
## What did you search for?
60А, улица Нефтяников, Речица, Речицкий район, Беларусь

## What result did you get?
улица Нефтяников, Речица, Речицкий район, Беларусь
## What result did you expect?
Don't search houses with cyrillic letter in number, for example 60А
Не ищет дома с кириллической буквой в номере дома, например, 60А
**Is the result in the right place and just named wrongly?** 

**Is the result missing completely?**

**Comment by lonvia** [comment]
Could you please link to the house on OSM. I can't find a 60A.

That said. Searching for cyrillic housenumbers is presently not possible while we are running an update on the database. Should be back in a couple of hours.

**Comment by 7171bel** [comment]
https://www.openstreetmap.org/#map=19/52.37013/30.34183
it is problem of last day with all houses with cyrillic letter in number of
houses

ср, 7 апр. 2021 г. в 18:08, Sarah Hoffmann ***@***.***>:

**Comment by 7171bel** [comment]
No problems yet, thank you.

**Comment by 7171bel** [comment]
It's all right! Thanx! 👍

**Comment by lonvia** [comment]
Jep, last of the servers just finished the updates. It took a bit longer than anticipated. Sorry for the inconvenience.
