### ISSUE TITLE
bad postcode when searching for address

### ISSUE THREAD

**Issue by ChazyTheBest** [osm-search/Nominatim#2255]
## What did you search for?

I searched for `Eduardo Ferrandez Garcia, 66, Elche`.

Link: https://nominatim.openstreetmap.org/?addressdetails=1&q=Eduardo%20Ferrandez%20Garcia%2C%2066%2C%20Elche&format=jsonv2

## What result did you get?

I got a bad `postcode`: `0323`.

## What result did you expect?

The postal code for that area should be: `03203`.

**Comment by mtmail** [comment]
I followed the steps in https://nominatim.org/release-docs/latest/develop/Postcodes/ and see https://www.openstreetmap.org/node/6176058485 is the source of the 4 digit postal code.

**Comment by lonvia** [comment]
Please fix this in the OSM data.

**Comment by ChazyTheBest** [comment]
@lonvia Can I have a link for that? I don't know where nor how to fix this.

**Comment by mtmail** [comment]
@ChazyTheBest On https://www.openstreetmap.org/node/6176058485 near the top left you will see an 'Edit' button, similar to wikipedia. That opens the editor https://www.openstreetmap.org/edit?node=6176058485#map=19/38.26644/-0.69365

**Comment by ChazyTheBest** [comment]
@mtmail Do i need to do this for every address that's affected? Isn't there another way to fix this?

**Comment by mtmail** [comment]
Only for https://www.openstreetmap.org/node/6176058485 Every night the remaining will get recalculated, so it should work after 24-48 hours.
