### ISSUE TITLE
emergency=yes tag regarded as a feature instead of an access tag

### ISSUE THREAD

**Issue by 501Ghost** [osm-search/Nominatim#2257]
Hello. When querying features on osm.org, I noticed that Nominatim regards features tagged with emergency=yes as emergency features instead of other features that simply have access for emergency services. I request a change to ignore emergency=yes when describing the feature, and instead focus on other main tags such as highway=*. 

A good example is the Hoogstraat in Wageningen, which is a pedestrian highway:

With emergency=yes: https://www.openstreetmap.org/way/297710230
![image](https://user-images.githubusercontent.com/61314579/114187596-771cc000-9948-11eb-816c-4c2dfbd55680.png)

Without emergency=yes: https://www.openstreetmap.org/way/6921808
![image](https://user-images.githubusercontent.com/61314579/114187937-dc70b100-9948-11eb-8504-ebdfb6fe383d.png)

Kind regards,
Casper

**Comment by mtmail** [comment]
The nearby features and enclosing features are queries from [Overpass](https://wiki.openstreetmap.org/wiki/Overpass_API) API, not Nominatim.

![image](https://user-images.githubusercontent.com/3727288/114191411-ab927b00-994c-11eb-8137-ab9c6d4dcfea.png)

**Comment by mtmail** [comment]
Nominatim doesn't seem to return the emergency tag, e.g. https://nominatim.openstreetmap.org/lookup.php?osm_ids=W297710230&format=jsonv2&extratags=1

**Comment by lonvia** [comment]
Indeed. Nominatim does process the `emergency` key as a primary key but explicitly [skips `yes` and `no`](https://github.com/osm-search/Nominatim/blob/master/settings/import-extratags.style#L39).
