### ISSUE TITLE
No results with some minor variations

### ISSUE THREAD

**Issue by calbasi** [osm-search/Nominatim#2259]
## What did you search for?

For example: 

> Avinguda d'Eduard Corbella, 182, Cardedeu, Espanya

Right query: https://nominatim.openstreetmap.org/ui/search.html?q=Avinguda+d%27Eduard+Corbella%2C+182%2C+Cardedeu%2C+Espanya&accept-language=ca

But, when I try minor variations, like:

> Avinguda d'Eduard Corbella, 184, Cardedeu, Espanya
> Avinguda Eduard Corbella, 182, Cardedeu, Espanya
> Eduard Corbella, 182, Cardedeu, Espanya

## What result did you get?

I get no results on the last 2 queries and an error about the number on the first. 

## What result did you expect?

The same result on all 4 queries.

## The issue

Geocoding is not useful for me if every minimal variation get an empty result or a mistake: without "avenue" word, next door/street number, a number which is not the corner house number, forgetting an article "the, 's" or, in Catalan/Spanish "de, la, d'"

We can expect users to write the "exact" address, like OSM has on his database: some minor variations should be accepted and processed. In fact, that's what Google Maps do.

**Comment by lonvia** [comment]
Nominatim is not particular good on partial matches. That is a long standing and offen reported issue.

Closing in favour of #94.
