### ISSUE TITLE
Disable search API when database was imported with --reverse-only

### ISSUE THREAD

**Issue by lonvia** [osm-search/Nominatim#2267]
When the database is a reverse-only database (i.e. the table search_name) is missing, then the refresh-website commend should create a dummy script for the endpoint `search.php` that just returns a 404 with the explanation that the installation does not support forward searching.

Also: the [documentation](https://nominatim.org/release-docs/develop/admin/Import/#testing-the-installation) recommends the `query.php` endpoint for testing. There should be a hint there to use `reverse.php` when importing with `--reverse-only`.

**Comment by darkshredder** [comment]
I would like to take up this issue if it is available to work on.

**Comment by lonvia** [comment]
The website scripts are always [(re)created as the last step of the import process](https://github.com/osm-search/Nominatim/blob/40cb17d2995baaba6bec299d4e6dc65b25dbdc28/nominatim/clicmd/setup.py#L142). So as long as you make the change in the `setup_website` function in `refresh.py`, the order does not matter.

I'd like to avoid runtime checks because the reverse script needs to be really fast.
