### ISSUE TITLE
Include importance of address parts into general importance

### ISSUE THREAD

**Issue by lonvia** [osm-search/Nominatim#2268]
the importance of address parts can be important to correctly rank searches for places like streets that usually don't get a specific importance assigned because they have no Wikipedia article linked. The address importance is currently used when reordering the results but that is too late as important results might already have been discarded because of the LIMIT parameter in the SQL query. The importance of the address should instead be included into the importance of the placex object. Now that the address parts can be assigned specific functions (country, state, county, city), it should be possible to obtain a consistent formula. I've done some experiments with photon on 9this branch](https://github.com/lonvia/photon/tree/address-importance).

**Comment by revolution909** [comment]
Was the issue solved or acknowledged somehow? I'm facing the same problem described in #1916 for the city of Cagliari (Cagliari is also the province name, so I am not able to get consistent results for the streets with common names in the area)
