### ISSUE TITLE
Searching for part of a university name

### ISSUE THREAD

**Issue by boothym** [osm-search/Nominatim#2271]
Came across this note: https://www.openstreetmap.org/note/2384794

https://nominatim.openstreetmap.org/ui/search.html?q=University+of+the+West+of+Scotland

Like the person who opened the note, I would have expected Nominatim to find the university (and others containing the search term): https://www.openstreetmap.org/way/4543895

But it seems like Nomination is looking for an exact match of the search term, rather than finding universities in OSM which begin with or contain the search term? 

I also searched for other universities and colleges which had "- XYZ Campus" in their name e.g. "ABC College - XYZ campus" and got similar results like a bus stop named "ABC College" but not the campus.

Is there anything that can or should be done with the OSM tagging? Or is this a Nominatim issue?

**Comment by mtmail** [comment]
converting the question to a github discussion
