### ISSUE TITLE
website folder not created during build process

### ISSUE THREAD

**Issue by Vrumfondel** [osm-search/Nominatim#2290]
The setup guide for Nominatim 3.7 explaines how to make the /website folder and content to be accessible, but this folder (and expected content) is not created for me during build process.

How can this be fixed?

**Comment by Vrumfondel** [comment]
OK, I answer this myselfe: The installation guide is not really clear. It should be mentioned that running "nominatim refresh --website" is needed .....

**Comment by lonvia** [comment]
It's not needed. The `website` directory should be available in the project directory after `nominatim import` is finished.
