### ISSUE TITLE
Documentation: update /advanced-installations to use Nominatim 3.7 script names

### ISSUE THREAD

**Issue by ombogdan** [osm-search/Nominatim#2304]
https://nominatim.org/release-docs/latest/admin/Update/#updating-the-database
at the bottom of the page there is a link to update multiple maps: https://nominatim.org/release-docs/latest/admin/Advanced-Installations/

but in version 3.7.1. there is no file setup.php, update.php so I get an error
please write normal documentation.
Write about nominatim replication --init or nominatim replication  or nominatim add-data

**Comment by lonvia** [comment]
There was an issue with the tar.bz2 file for the Nominatim 3.7.1 which is fixed now. Please download and install again. The setup and update scripts to make those multi-site scripts work should be back.

**Comment by ombogdan** [comment]
now i download tar.bz2 file with command: wget https://nominatim.org/release/Nominatim-3.7.1.tar.bz2.
But i  do not see file setup.php or update.php in utils directory: http://joxi.ru/E2pw1xoiGLWO3m why? This is what I need for Updating multiple regions in file update_database.sh.

**Comment by lonvia** [comment]
They are installed in `build/utils`. For using the multi-country scripts you still need the old-style installation method with running from the build directory as described in https://nominatim.org/release-docs/3.6.0/admin/Installation/. We'll probably switch the method completely for the 4.0.0 release but for now it is as it is.
