### ISSUE TITLE
Nominatim returns (node) suburb names ahead of (node) town or city names when the search location is nearer to the town or city than the nearest suburb.

### ISSUE THREAD

**Issue by SomeoneElseOSM** [osm-search/Nominatim#231]
The discussion was initially prompted by this anonymous note:

http://www.openstreetmap.org/note/310989

When you do a Nominatim search of that location the result is currently "Forest Town, Mansfield, Nottinghamshire, East Midlands, England, United Kingdom" or more specifically

http://nominatim.openstreetmap.org/details.php?place_id=66041028

Lansdowne Avenue (Type: highway:residential, way 41437217, 15, 0 GOTO)
Forest Town (Type: place:suburb, node 1587152579, 15, 0.0392499283515287 GOTO)
Mansfield Woodhouse (Type: place:suburb, node 1587155714, 15, 0.0449261591459793 GOTO)
Mansfield (Type: place:town, relation 154006, 8, 0.0484990562893802 GOTO)
Ravenshead (Type: place:village, node 322809684, 15, 0.0415295987995344 GOTO)
Nottinghamshire (Type: place:county, relation 181040, 6, 0.175419560568802 GOTO)
Nottinghamshire (Type: place:county, node 302323934, 15, 0.186689544474509 GOTO)
East Midlands (Type: boundary:administrative, relation 151279, 5, 0.43241986583943 GOTO)
England (Type: boundary:administrative, relation 58447, 4, 0.826522671450268 GOTO)
United Kingdom (Type: place:country, relation 62149, 2, 2.70048608918807 GOTO)
gb (Type: place:country_code, 0 GOTO)

According to Overpass, the nearest places are as follows:

http://overpass-turbo.eu/s/7uD

Interestingly the relation:

http://www.openstreetmap.org/relation/154006

doesn't have place=town on it but the node (not mentioned by Nominatim above) does:

http://www.openstreetmap.org/node/26984579

It'd be nice of Nominatim could somehow reason "because Forest Town is defined as a node, and because it's further away from the search location than the place=town node for Mansfield, Forest Town should be omitted from the returned address"

Although a valid question, this is a slightly artificial situation in Mansfield because:

You could argue that "Berry Hill" ought to be a suburb much closer to the search location.
You could argue that "Forest Town" ought to be a village rather than a suburb.

However, a similar situation appears in Sheffield here:

http://www.openstreetmap.org/way/103865627

which apparently is "Sheffield Town Hall, Cheney Row, Moorhead, Little Kelham, Sheffield, Yorkshire and the Humber, England, S1 2LG, United Kingdom"

http://nominatim.openstreetmap.org/details.php?place_id=77543699

Sheffield Town Hall (Type: amenity:townhall, 0 GOTO)
Cheney Row (Type: highway:pedestrian, way 103917574, 15, 0 GOTO)
Moorhead (Type: place:neighbourhood, node 1210567152, 15, 0.00340211079478811 GOTO)
Little Kelham (Type: place:suburb, node 1230601700, 15, 0.00838123021101319 GOTO)
Wicker (Type: place:suburb, node 266155305, 15, 0.0102748834591939 GOTO)
Saint George's (Type: place:suburb, node 266154763, 15, 0.0117031658708233 GOTO)
Saint Vincent's (Type: place:suburb, node 266154414, 15, 0.00929232098024799 GOTO)
Sheffield (Type: place:city, relation 106956, 8, 0.0845535473528197 GOTO)
Moscar Cottages (Type: place:hamlet, node 1451971656, 15, 0.0393070225762539 GOTO)
Sheffield (Type: place:city, node 266155142, 15, 0.00090448951348269 GOTO)
Derbyshire (Type: place:county, node 302323945, 15, 0.241943294202922 GOTO)
Yorkshire and the Humber (Type: boundary:administrative, relation 151012, 5, 0.634915564095151 GOTO)
England (Type: boundary:administrative, relation 58447, 4, 0.969669553988156 GOTO)
S1 2LG (Type: place:postcode, 0.000753603124673094 GOTO)
S1 1XX (Type: place:postcode, 0.00112682213011335 GOTO)
United Kingdom (Type: place:country, relation 62149, 2, 2.31644935526428 GOTO)
gb (Type: place:country_code, 0 GOTO)

The nearby place nodes are:

http://overpass-turbo.eu/s/7uE

Of which the nearest place node is:

http://www.openstreetmap.org/node/266155142

(place=city)

When thing was discussed on IRC, it was suggested that a way to solve this would be by defining areas for suburbs.  In the case of Forest Town, it'd be easy to define an area that didn't include the search location, but less easy to define one that all the locals consider accurate for that suburb.

**Comment by HolgerJeromin** [comment]
Another problem with a town and its suburb:
http://www.openstreetmap.org/search?query=51.8832,8.5099
It links to the suburb http://www.openstreetmap.org/node/290921164 but not the nearer (and better fitting) town http://www.openstreetmap.org/node/240129345

**Comment by lonvia** [comment]
I have given this some considerable thought and come to the conclusion that this is not something that Nominatim can decide or even guess with more help from the mappers. The mapping is very inconsistent in OSM. Sometimes there is an additional node for the city center 'suburb', sometimes there isn't. Some cities do have a city center where the town node may apply some don't. There is just too much guessing involved. I even don't have a good suggestion what could be done on the tagging side to describe the situation better. 

So I'm closing this as 'won't fix'.
