### ISSUE TITLE
Add CSV import for special phrases

### ISSUE THREAD

**Issue by lonvia** [osm-search/Nominatim#2311]
We currently only have the ability to import special phrases from the wiki. It would be nice if the user could supply a simple CSV instead with their own custom phrases. For the moment these CSV should follow the wiki structure and expect the following columns: phrase, key, value, operator. The reader should simply ignore any other columns, so that we can require additional optional data in the future.

This CSV importer would also be needed [for the BDD tests](https://github.com/osm-search/Nominatim/blob/3c67bae86884bdd4b7f053b553fe697066b5c887/test/bdd/steps/nominatim_environment.py#L195). Now that the task of importing the special phrases into the word table has been outsourced to the tokenizer, the simple approach of having an SQL file does not work anymore.

@AntoJvlt Is that a task I could interest you in?

**Comment by AntoJvlt** [comment]
Yes this is nice and it comes at the right time for me, I will work on it, thanks for the notification.

For the [BDD tests](https://github.com/osm-search/Nominatim/blob/3c67bae86884bdd4b7f053b553fe697066b5c887/test/bdd/steps/nominatim_environment.py#L195) can we imagine to call the CSV importer with a custom CSV file created for tests purpose?

**Comment by lonvia** [comment]
Yes. The [current test data](https://github.com/osm-search/Nominatim/blob/3c67bae86884bdd4b7f053b553fe697066b5c887/test/testdb/specialphrases_testdb.sql) is still in the old SQL format. This would need to be converted into CSV and imported where we currently execute the SQL. In an upcoming change I simply [call import-from-wiki](https://github.com/lonvia/Nominatim/blob/icu-tokenizer/test/bdd/steps/nominatim_environment.py#L206) but the BDD tests really shouldn't rely on the wiki always having the necessary data.
