### ISSUE TITLE
API returns empty array instead of empty hash when place has no keywords

### ISSUE THREAD

**Issue by mtmail** [osm-search/Nominatim#2329]
Related to https://github.com/osm-search/nominatim-ui/issues/152

The details API result of a place with keywords includes
```js
{
    'keywords': {
       'name': [ ... ],
       'address': [ ... ]
    }
}
```
and both keys `name` or `address` might be missing.

If both are missing, e.g. a place like a house number without any keywords, then the API result includes
```js
{
    'keywords': []
}
```

I'd argue either an empty hash `{}`, `null` or hash with both `name` and `address` present (pointing to empty arrays) should be returned instead to be consistent.

**Comment by lonvia** [comment]
Tricky. PHP' s json_encode only has an option to globally force empty arrays to objects. That might break other things. How about:

```
{
    'keywords': {
       'name': [],
       'address': []
    }
}
```

For the case where `name` and/or `address` are empty?

**Comment by mtmail** [comment]
@lonvia Sounds good
