### ISSUE TITLE
Search for incomplete name plus country fails and gives lots of results from other countries

### ISSUE THREAD

**Issue by AxelBoldt** [osm-search/Nominatim#2344]
I was trying to find the Isla Madre de Dios in Chile, https://www.openstreetmap.org/relation/2715606 .

I searched Nominatim for "Madre de Dios, Chile" https://nominatim.openstreetmap.org/ui/search.html?q=Madre+de+Dios%2C+Chile

The top two results were roads in Chile, and the remaining results were about roads or other structures in other countries. The island did not appear in the result list.

Searches for "Isla Madre de Dios" https://nominatim.openstreetmap.org/ui/search.html?q=Isla+Madre+de+Dios or "Isla Madre de Dios, Chile" https://nominatim.openstreetmap.org/ui/search.html?q=Isla+Madre+de+Dios%2C+Chile yield the correct top result. Search for "Madre de Dios" https://nominatim.openstreetmap.org/ui/search.html?q=Madre+de+Dios gives the Chilean island at position 41 in the result list, which is acceptable since the name is so common.

**Comment by lonvia** [comment]
The problem with the the country here is that we have 'chile' still as a potential housenumber due to a mapping error that long since has been fixed. There is definitely room for improvement. I've opened #2351 for the underlying issue to be resolved. Closing here.
