### ISSUE TITLE
Result reports wrong street address, apparently deduced from proximity

### ISSUE THREAD

**Issue by AxelBoldt** [osm-search/Nominatim#2345]
A search for "Red's Savoy Pizza, Saint Paul" https://nominatim.openstreetmap.org/ui/search.html?q=Red%27s+Savoy+Pizza%2C+Saint+Paul yields the correct result,
https://www.openstreetmap.org/node/7688578431, however it reports the wrong street address "143 Hague Avenue". The correct address is "143 Snelling Avenue North", which is listed in the restaurant's entry. Hague Avenue is the cross street; apparently Nominatim guesses the street from proximity, but still uses the house number from the restaurant's entry.

**Comment by lonvia** [comment]
The name in addr:street and the name of the street it references must correspond for Nominatim to get the address correct. At the moment 'North' is used inconsistently.

Closing as data issue.
