### ISSUE TITLE
Error while installing nominatim - FATAL: Cannot initialize tokenizer.

### ISSUE THREAD

**Issue by mdawood1991** [osm-search/Nominatim#2347]
**Describe the bug**

I am trying to install the latest version of Nominatim on a new VM running Ubuntu.
First I ran the script [`Install-on-Ubuntu-20.sh`](https://github.com/osm-search/Nominatim/blob/v3.7.1/vagrant/Install-on-Ubuntu-20.sh)  with the following changes only:

```
    useradd -d /srv/nominatim -s /bin/bash -m nominatim
    export USERNAME=nominatim        #DOCS:    export USERNAME=nominatim
    export USERHOME=/srv/nominatim  #DOCS:    export USERHOME=/srv/nominatim
```

The script runs to this step `nominatim refresh --website`. On this line it displays an error:

```
-- Up-to-date: /usr/local/share/man/man1/nominatim.1
mkdir: cannot create directory ‘/srv/nominatim/nominatim-project’: File exists
2021-05-24 21:51:17: Using project directory: /srv/nominatim/nominatim-project
2021-05-24 21:51:17: Cannot find tokenizer data in '/srv/nominatim/nominatim-project/tokenizer'.
2021-05-24 21:51:17: FATAL: Cannot initialize tokenizer.
```
Full installation log: [Link](https://1drv.ms/t/s!ArJHgD_ehpS3g5YgkApF6ijckPzhBg?e=xbPqMU) 

So I checked out `tag/v3.7.1` from github and run the same script again, but still the same error. I also tried running the commands for installation one-by-one manually - but still the same issue.

Am I missing something? 

I have tried the steps [here ](https://nominatim.org/release-docs/latest/appendix/Install-on-Ubuntu-20/) about 3 times 

**To Reproduce**

Just run the installation comands or script on a newly installed Ubuntu VM  Ubuntu 20.04.2.

**Software Environment (please complete the following information):**
- Nominatim version: v3.7.1
- Postgresql version: 12.6
- Postgis version: 
- OS:  Ubuntu 20.04.2

**Hardware Configuration (please complete the following information):**
- RAM: 30GB
- number of CPUs: 2
- type and size of disks: sda = 50GB ext4, sdb = 250 GB ext4
- bare metal/AWS/other cloud service: Oracle Cloud VM

**Postgresql Configuration:**

Default congifuration, haven't got to this step yet.

**Additional context**

**Comment by AntoJvlt** [comment]
A new Tokenizer system has been introduced recently (see #2305). You are trying to execute a command that needs the tokenizer to work `Cannot find tokenizer data in '/srv/nominatim/nominatim-project/tokenizer'`, so you are getting this error.

You need to import the database first for the Tokenizer to be created, follow the [import section](https://nominatim.org/release-docs/latest/admin/Import/) and then get back to the [webserver setup](https://nominatim.org/release-docs/latest/appendix/Install-on-Ubuntu-20/#setting-up-a-webserver). During the import, the folder "tokenizer" will be created under your project directory and it will contains the right Tokenizer code.

The documentation needs some update regarding this change.

**Comment by lonvia** [comment]
That was an unintended side effect of the tokenizer introduction. The setup-website command should be able to work without the tokenizer. Maybe we can change `nominatim/clicmd/refresh.py` so that the tokenizer is not initialised for the `refresh --website` command.

**Comment by mdawood1991** [comment]
Hi, 
Thanks for the response, based on @AntoJvlt 's suggestion I tried to import the data, but again there is some error on the tokenizer.

![image](https://user-images.githubusercontent.com/9995855/119487634-8c5f7980-bd51-11eb-8934-72571cd38168.png)


The script I ran:
# Import database script
# ----------------------
export USERHOME= /srv/nominatim 
export DATAHOME= $USERHOME/nominatim-data
export BUILDHOME= $USERHOME/build

cd $USERHOME
mkdir nominatim-data

#IMPORTING THE DATA
# This script only imports the data for Saudi Arabia
# Download data
cd $DATAHOME
wget http://download.openstreetmap.fr/extracts/asia/saudi_arabia-latest.osm.pbf

# Import the data
cd $BUILDHOME
nominatim import --osm-file $DATAHOME/saudi_arabia-latest.osm.pbf 2>&1 | tee setup.log
nominatim admin --check-database

**Comment by AntoJvlt** [comment]
You have a permission denied error, the tokenizer folder cannot be created. Make sure to execute the import command from a user with write access on the directory you are in.

**Comment by lonvia** [comment]
To add to that: do not run the import from the build directory anymore. Create a separate project directory.
