### ISSUE TITLE
House numbers in word table should be cleaned regularly

### ISSUE THREAD

**Issue by lonvia** [osm-search/Nominatim#2351]
When a buggy house number is entered in OSM, its import creates an entry in the word table. Even when the house number is later corrected, the entry remains. That often leads to odd search errors because house numbers are optional parts of the query and can practically change the search into a partial one.

We should have a task to clean out house numbers from the word table that no longer appear in the `placex` table. As the main issue here is with "words as house numbers", the task could be restricted to house numbers without any digits in them.

Implementation details: The `housenumber` column of the placex table contains the transliterated version of a housenumber. This is the same term that appears in the column `word_token` in the word table. Housenumber terms in the word table are recognisable from `class=place` and `type=house`. The task would involve removing all those rows in the word table that whose `word_token` is nowhere to the found in the `housenumber` column of the placex table. This would be a refresh task, i.e. implemented as a command `nominatim refresh --housenumbers`.

**Comment by rocka0** [comment]
@lonvia, this would be the first time I'm contributing to an open source project but I'd like to give this issue a shot. Since it has been about 4 months since this issue was opened, is there anything you think I should know before giving this a go?
