### ISSUE TITLE
wrong place=farm nodes in address (hierarchy)

### ISSUE THREAD

**Issue by geoneutrino** [osm-search/Nominatim#2352]
## What did you search for?

e.g.
https://nominatim.openstreetmap.org/ui/search.html?q=Schroffenbergallee+83471+Berchtesgaden
or 
https://nominatim.openstreetmap.org/ui/search.html?q=+M%C3%BChlenstra%C3%9Fe+6%2C+40885+Ratingen

## What result did you expect?
got correct street/buildings but address hierarchy of those have associated place=farm nodes with distance 0 not belonging to the objects

Ratingen example
https://nominatim.openstreetmap.org/ui/details.html?osmtype=W&osmid=197403694&class=building
has Frielingsrath associated with distance 0 but this is on the other side of the highway (500-600 meters away)

Bertechsgaden example
https://nominatim.openstreetmap.org/ui/details.html?osmtype=W&osmid=51518401&class=highway
hast Nagllehen associated with distance 0 (but is ~ 350 meters away)

The problem is that this farm information ist not only in details hierarchy but also in Api response
https://nominatim.openstreetmap.org/search.php?q=+M%C3%BChlenstra%C3%9Fe+6%2C+40885+Ratingen&format=xml&addressdetails=1
marking the result to be a farm

**Comment by lonvia** [comment]
It's tricky to distinguish "stand-alone" farms from simple farmyards in OSM. This is relevant to know for Geocoding because the former usually lend their name to the area they are in, while the latter just really are a name for the farm itself.

**Comment by lonvia** [comment]
I'm closing this as a data issue. You should be using `place=farm` only, when the farm lends its name to the surrounding area (i.e. when there really is a place of that name, not just a house), otherwise use [landuse=farmyard](https://wiki.openstreetmap.org/wiki/Tag:landuse%3Dfarmyard) with the appropriate name tag.
