### ISSUE TITLE
differences in importance between village and town

### ISSUE THREAD

**Issue by christophlingg** [osm-search/Nominatim#236]
While debugging some [photon](github.com/komoot/photon) results I came across these two nominatim entries:

[Bailleul](http://nominatim.openstreetmap.org/details.php?place_id=127679278), importance: 0.39 place=town
[Bailleul-Sir-Berthould](http://nominatim.openstreetmap.org/details.php?place_id=127809443) importance: 0.59 place=village

Both of them have an calculated wikipedia assignment, so I do not understand why a village has an significant higher importance than town. Could it be a bug?

**Comment by christophlingg** [comment]
let me guess: the impact of the calculated wikipedia assignment is based on how similar wikipedia title and the name tag is. And as `Bailleul_(Nord)` does not match exactely on `Bailleul` is getting downgraded?

**Comment by mtmail** [comment]
My hunch is that the Wikipedia count is from the english Wikipedia only and Bailleu (town) has a disambiguation page. Also data might be old. Good news is that I will go through all that logic and document any flaws in preparation for the FOSSGIS talk in March (which is exactly about this part of the ranking logic). I'd like to keep this issue open until I can give you a correct answer.

**Comment by christophlingg** [comment]
Cool that you are going to put your hands on it!

I just find another example that might help you too:

[Sandkrug village](http://nominatim.openstreetmap.org/details.php?place_id=12137352) importance: 0.25
[Sandkrug town](http://nominatim.openstreetmap.org/details.php?place_id=300028) importance: 0.21

interestingly the town has even a calculated wiki page. And probably you are right: it is yet another case of a disambiguation page: `de:Sandkrug_(Hatten)`

**Comment by christophlingg** [comment]
I found another example, maybe related to the same:

[Village](http://nominatim.openstreetmap.org/details.php?place_id=127986272), population=259, with wiki, importance = **0.54**
[Town](http://nominatim.openstreetmap.org/details.php?place_id=127738784), population= 19281, with wiki, importance = **0.51**

**Comment by lonvia** [comment]
The links have long gone stale. It is impossible to check if the issue is still relevant after the recomputation of wikipedia importances. I'll close this issue.

**Comment by eginhard** [comment]
I see this as well. Searching for [Martigny](https://nominatim.openstreetmap.org/ui/search.html?q=Martigny) returns 3 French villages ranked higher than the much larger Swiss town.
- [Martigny (Aisne)](https://nominatim.openstreetmap.org/ui/details.html?osmtype=R&osmid=153341&class=boundary), importance: 0.59
- [Martigny (Seine-Maritime)](https://nominatim.openstreetmap.org/ui/details.html?osmtype=R&osmid=164923&class=boundary), importance: 0.59
- [Martigny (Manche)](https://nominatim.openstreetmap.org/ui/details.html?osmtype=R&osmid=1003301&class=boundary), importance: 0.57
- [Martigny](https://nominatim.openstreetmap.org/ui/details.html?osmtype=R&osmid=1685332&class=boundary), importance: 0.53

If I understand https://github.com/osm-search/wikipedia-wikidata correctly, importance is calculated based on the number of links to the Wikipedia page, but as far as I can tell the Swiss town has the most links: https://linkcount.toolforge.org/?project=fr.wikipedia.org&page=Martigny
