### ISSUE TITLE
Wildcards

### ISSUE THREAD

**Issue by probonopd** [osm-search/Nominatim#2361]
**Is your feature request related to a problem? Please describe.**
I would like to find all streets that thave "Unix" as part of their name.

**Describe the solution you'd like**
https://nominatim.geocoding.ai/search.php?street=unix*&format=jsonv2 should return, among others,

```
[
   {
      "place_id":264521793,
      "licence":"Data © OpenStreetMap contributors, ODbL 1.0. https://osm.org/copyright",
      "osm_type":"way",
      "osm_id":907002287,
      "boundingbox":[
         "47.988125",
         "47.9883357",
         "9.7777096",
         "9.7785522"
      ],
      "lat":"47.988234",
      "lon":"9.7781935",
      "display_name":"Unixstraße, Lindenhof, Haldenhof, Oberessendorf, Eberhardzell, Verwaltungsgemeinschaft Biberach an der Riß, Landkreis Biberach, Baden-Württemberg, 88436, Deutschland",
      "place_rank":26,
      "category":"highway",
      "type":"residential",
      "importance":0.19999999999999998
   }
]
```

but it doesn't. The result above is _only_ found when searching for https://nominatim.geocoding.ai/search.php?street=unixstra%C3%9Fe&format=jsonv2

**Comment by mtmail** [comment]
https://photon.komoot.io/ software is optimized for type-ahead searching if that's what you're looking for. It uses data generated by Nominatim.

**Comment by probonopd** [comment]
Only that https://photon.komoot.io/api/?q=Unix* doesn't find Unixstraße either.

**Comment by mtmail** [comment]
https://photon.komoot.io/api/?q=Unix&limit=100 returns it. The street in Eberhardzell is arguably not the most relevant result if no other parameters like the focus point, language etc are set. (Photon doesn't have a street= parameter like Nominatim). I'd expect a user to type in `Unixs` or `Unixst`. How Photon ranks results is a questions for https://github.com/komoot/photon/discussions

**Comment by probonopd** [comment]
Thank you very much, that seems to do the job indeed.

**Comment by Smig0l** [comment]
Anything changed in 2 years?

**Comment by mtmail** [comment]
Same open wishlist item for 10 years.  https://photon.komoot.io/ uses Nominatim data and can do type-ahead/autocomplete/autosuggest.
