### ISSUE TITLE
Cannot get the postcode with a georeverse, similar error that issue #2301

### ISSUE THREAD

**Issue by shishamo** [osm-search/Nominatim#2362]
## What did you search for?
try to get the adress with postcode
the following search didn't send me unexpected result, need the postcode
https://nominatim.openstreetmap.org/reverse?lat=35.69&lon=135.69&format=geojson&accept-language=en

## What result did you get?
```
{
    "type": "FeatureCollection",
    "licence": "Data © OpenStreetMap contributors, ODbL 1.0. https://osm.org/copyright",
    "features": [
        {
            "type": "Feature",
            "properties": {
                "place_id": 258675332,
                "osm_type": "relation",
                "osm_id": 4799812,
                "place_rank": 14,
                "category": "boundary",
                "type": "administrative",
                "importance": 0.40078255314528716,
                "addresstype": "city",
                "name": "Wakasa",
                "display_name": "Wakasa, Mikatakaminaka County, Fukui Prefecture, Japan",
                "address": {
                    "town": "Wakasa",
                    "county": "Mikatakaminaka County",
                    "province": "Fukui Prefecture",
                    "country": "Japan",
                    "country_code": "jp"
                }
            },
            "bbox": [
                135.6320225,
                35.3944,
                135.954278,
                35.8693841
            ],
            "geometry": {
                "type": "Point",
                "coordinates": [
                    135.9051269,
                    35.5432385
                ]
            }
        }
    ]
}
```

## What result did you expect?
Same result as that search below
https://nominatim.openstreetmap.org/reverse?lat=35.69&lon=139.65&format=geojson
```
{
  "type": "FeatureCollection",
  "licence": "Data © OpenStreetMap contributors, ODbL 1.0. https://osm.org/copyright",
  "features": [
    {
      "type": "Feature",
      "properties": {
        "place_id": 113280088,
        "osm_type": "way",
        "osm_id": 101852597,
        "place_rank": 26,
        "category": "highway",
        "type": "residential",
        "importance": 0.09999999999999998,
        "addresstype": "road",
        "name": null,
        "display_name": "Horinouchi 2-chome, Suginami, 166-0013, Japon",
        "address": {
          "neighbourhood": "Horinouchi 2-chome",
          "city": "Suginami",
          "postcode": "166-0013",
          "country": "Japon",
          "country_code": "jp"
        }
      },
      "bbox": [139.6500074, 35.6895341, 139.6523638, 35.6900829],
      "geometry": {
        "type": "Point",
        "coordinates": [139.6500096305503, 35.69000025993963]
      }
    }
  ]
}
```

**Is the result in the right place and just named wrongly?** 
I was expects to receive the postcode

**Is the result missing completely?**

To get the link to the OSM object, you can try the following:

 * Go to [https://openstreetmap.org](https://openstreetmap.org).
 * Move to the area of the map where you expect the result and then zoom in as much as possible.
 * Click on the question mark on the right side of the map. You get a question cursor. Use it to click on the map where your object is located.
 * Find the object of interest in the list that appears on the left side.
 * Click on the object and report back the URL that the browser shows.
-->

**Comment by lonvia** [comment]
The coordinate you are looking for is in the middle of the sea and therefore resolves only to the city, not to an address point. Cities usually don't have a postcode. This is intentional.

**Comment by shishamo** [comment]
Thank you for your answer, I haven't checked properly...
Concerning the issue #2301, I get that coordinates from the device and doesn't look like it is in the sea.
I think that the issue was fixed but the same problem came back, could you confirm me please?

**Comment by lonvia** [comment]
#2301 is still fixed but you'll see the effects only gradually when the underlying data gets updated. There was no global reimport to fix all missing postcodes.
