### ISSUE TITLE
Error on "nominatim refresh --website":  cannot import name 'Transliterator'

### ISSUE THREAD

**Issue by GKurt** [osm-search/Nominatim#2370]
On following instructions at: https://nominatim.org/release-docs/latest/appendix/Install-on-Centos-8/

I encountered a reproducible error at:

mkdir $USERHOME/nominatim-project
cd $USERHOME/nominatim-project
nominatim refresh --website

as follows:

[nominatim@web3b website]$ pwd
/home/nominatim/nominatim-project/website
[nominatim@web3b nominatim-project]$ nominatim refresh --website
Traceback (most recent call last):
  File "/usr/local/bin/nominatim", line 9, in <module>
    from nominatim import cli
  File "/usr/local/lib64/nominatim/lib-python/nominatim/cli.py", line 14, in <module>
    from . import clicmd
  File "/usr/local/lib64/nominatim/lib-python/nominatim/clicmd/__init__.py", line 13, in <module>
    from .special_phrases import ImportSpecialPhrases
  File "/usr/local/lib64/nominatim/lib-python/nominatim/clicmd/special_phrases.py", line 5, in <module>
    from nominatim.tools.special_phrases import SpecialPhrasesImporter
  File "/usr/local/lib64/nominatim/lib-python/nominatim/tools/special_phrases.py", line 11, in <module>
    from icu import Transliterator
ImportError: cannot import name 'Transliterator'
[nominatim@web3b nominatim-project]$

After nothing else I tried worked I commented out line 11 in

/usr/local/lib64/nominatim/lib-python/nominatim/tools/special_phrases.py

and the "nominatim refresh --website" command ran to completion, and created some scripts:

[nominatim@web3b nominatim-project]$ ls -l website
total 28
-rw-rw-r--. 1 nominatim nominatim 965 Jun 18 17:04 deletable.php
-rw-rw-r--. 1 nominatim nominatim 963 Jun 18 17:04 details.php
-rw-rw-r--. 1 nominatim nominatim 962 Jun 18 17:04 lookup.php
-rw-rw-r--. 1 nominatim nominatim 964 Jun 18 17:04 polygons.php
-rw-rw-r--. 1 nominatim nominatim 963 Jun 18 17:04 reverse.php
-rw-rw-r--. 1 nominatim nominatim 962 Jun 18 17:04 search.php
-rw-rw-r--. 1 nominatim nominatim 962 Jun 18 17:04 status.php
[nominatim@web3b nominatim-project]$ 

I'll see how they work.

**Comment by lonvia** [comment]
The libicu dependency is called `libicu-devel` not `libicu-dev`. I'll try to get the installation instructions updated but I'm currently running into some other issues with the vagrant scripts.

**Comment by GKurt** [comment]
Hello lonvia,
     It seems as though the package is named libicu-dev on debian/ubunu distributions, and libicu-devel on redhat-derived distributions. I just installed "libicu-dev" on my Ubuntu 30.04.2 LTS Laptop, and apt-get is unable to find a "libicu-devel" package. OTOH I do have "libicu-devel" installed on the Rehdat 8.4 server where I'm trying to build Nominatim, and dnf cannot find any "libicu-dev" to install.

**Comment by GKurt** [comment]
But this seems irrelevant to the problem I am encountering. I haven't yet tried to build Nominatim 3.7.2 on Ubuntu, but on both platforms (redhat 8.4 and ubuntu 20.04.2), when I run python3 and the command line and enter the first eleven lines of "special_phrases.py", they fail identically with the error:

>>> from icu import Transliterator
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ImportError: cannot import name 'Transliterator'

**Comment by lonvia** [comment]
Please follow https://nominatim.org/release-docs/latest/appendix/Install-on-Ubuntu-20/#installing-the-required-software for Ubuntu 20.04 and https://nominatim.org/release-docs/latest/appendix/Install-on-Centos-8/#installing-the-required-software for CentOS 8, which lists all required software prerequisites.

**Comment by dguymon** [comment]
I'm also running into this same error, but not during the website refresh step.  I see it later on when I'm trying to import a Geofabrik OSM dataset.  I've listed which python icu package and icu yum packages I have installed currently:

[root@ip-10-99-223-124 build]# sudo -u nominatim /usr/local/bin/nominatim import --osm-file /srv/nominatim/build/north-america-latest.osm.bz2 2>&1 | tee setup.log
Traceback (most recent call last):
  File "/usr/local/bin/nominatim", line 9, in <module>
    from nominatim import cli
  File "/usr/local/lib64/nominatim/lib-python/nominatim/cli.py", line 14, in <module>
    from . import clicmd
  File "/usr/local/lib64/nominatim/lib-python/nominatim/clicmd/__init__.py", line 13, in <module>
    from .special_phrases import ImportSpecialPhrases
  File "/usr/local/lib64/nominatim/lib-python/nominatim/clicmd/special_phrases.py", line 5, in <module>
    from nominatim.tools.special_phrases import SpecialPhrasesImporter
  File "/usr/local/lib64/nominatim/lib-python/nominatim/tools/special_phrases.py", line 11, in <module>
    from icu import Transliterator
ImportError: cannot import name 'Transliterator'

[root@ip-10-99-223-124 build]# pip3 list | grep icu
DEPRECATION: The default format will switch to columns in the future. You can use --format=(legacy|columns) (or define a format=(legacy|columns) in your pip.conf under the [list] section) to disable this warning.
icu (0.0.1)

[root@ip-10-99-223-124 build]# yum list installed | grep icu
libicu.x86_64                         50.2-4.el7_7               @base
libicu-devel.x86_64                   50.2-4.el7_7               @base
libicu65.x86_64                       65.1-1.el7.remi            @remi-safe

**Comment by lonvia** [comment]
As per installation instructions, you need the PyICU Python package, not icuL `pip3 install PyICU`.

**Comment by dguymon** [comment]
Thanks, yeah I ended up doing a new clean install on a Centos 8 EC2 instance last night and noticed that I had made that mistake in my previous installation attempt.  I’m good now :)

- Danny

**Comment by lonvia** [comment]
Okay, thanks for the feedback. I'll assume that this was also the issue with the original report. Let me check if we can add a test in the CMakeFile, so that you get a meaningful error when installing the wrong library. It's an easy enough mistake to make.

**Comment by GKurt** [comment]
This is a case where the shotgun approach causes problems:

==========
[root@web3b ~]# dnf list installed | grep -i icu
harfbuzz-icu.x86_64                                1.7.5-3.el8                                    @rhel-8-for-x86_64-appstream-rpms        
icu.x86_64                                         60.3-2.el8_1                                   @rhel-8-for-x86_64-baseos-rpms           
libicu.x86_64                                      60.3-2.el8_1                                   @rhel-8-for-x86_64-baseos-rpms           
libicu-devel.x86_64                                60.3-2.el8_1                                   @rhel-8-for-x86_64-baseos-rpms           
libicu-doc.noarch                                  60.3-2.el8_1                                   @rhel-8-for-x86_64-baseos-rpms           
[root@web3b ~]# 
.     .     .     .     .     .
[nominatim@web3b ~]$ pip3 list installed | grep -i icu
DEPRECATION: The default format will switch to columns in the future. You can use --format=(legacy|columns) (or define a format=(legacy|columns) in your pip.conf under the [list] section) to disable this warning.
icu (0.0.1)
PyICU (2.7.4)
[nominatim@web3b ~]$
==========

     I guess the (0.0.1) python package messes things up even if you also have PyICU. After "pip3 uninstall icu" I was able to complete the "nominatim refresh --website" step.

     I think I am closing this issue by clicking [Close with comment] ?
