### ISSUE TITLE
Sevastopl edited as city that belong to Russia which is not.

### ISSUE THREAD

**Issue by Ar4isteR** [osm-search/Nominatim#2386]
I was on instagram and location tag said Sevastopol is in Russia but it is incorrect edit that someone did i took couple of screenshots as proof. Please fix 

![Screenshot_20210708-170104_Chrome](https://user-images.githubusercontent.com/20827610/124992371-dace8c00-e010-11eb-9d57-2f055b4026f2.jpg)
![Screenshot_20210708-170122_Chrome](https://user-images.githubusercontent.com/20827610/124992379-dbffb900-e010-11eb-9c56-e2556954c68f.jpg)
![Screenshot_20210708-170648_Chrome](https://user-images.githubusercontent.com/20827610/124992380-dd30e600-e010-11eb-92b3-6830e459db68.jpg)

**Comment by mtmail** [comment]
This issue tracker is for the search software Nominatim, not OpenStreetMap data issues. Contact the user who made the edit first. The second screenshot shows "Edited 2 months ago by <username>". You can also find local OpenStreetMap community groups and contact links for the area on https://openstreetmap.community/

**Comment by Ar4isteR** [comment]
Thanks for your prompt response.
