### ISSUE TITLE
The search does not work after installation

### ISSUE THREAD

**Issue by dmitrymaslov99** [osm-search/Nominatim#2388]
**Describe the bug**
Installed according to your documentation for the country of Russia. We use the reverse everything is fine, when using the search returns an error - Reverse-only import does not support forward searching.

**To Reproduce**
http://109.95.212.124/reverse.php?lat=55.824637&lon=37.655149&format=json - working
http://109.95.212.124/search.php - dont working

**Software Environment (please complete the following information):**
- Nominatim version: last
- Postgresql version: psql (PostgreSQL) 12.7 (Ubuntu 12.7-0ubuntu0.20.04.1)
- Postgis version: 
- OS: Ubuntu 20.04

**Hardware Configuration (please complete the following information):**
- RAM: 64 GB
- number of CPUs: 12
- type and size of disks: 250GB SSD
- bare metal/AWS/other cloud service: 

**Postgresql Configuration:**
shared_buffers = 2GB
maintenance_work_mem = (10GB)
autovacuum_work_mem = 2GB
work_mem = (50MB)
effective_cache_size = (24GB)
synchronous_commit = off
checkpoint_segments = 100 # only for postgresql <= 9.4
max_wal_size = 1GB # postgresql > 9.4
checkpoint_timeout = 10min
checkpoint_completion_target = 0.9

**Additional context**
We acted according to the instructions in full - https://nominatim.org/release-docs/latest/admin/Installation/
![telegram-cloud-photo-size-2-5422744520619045535-y](https://user-images.githubusercontent.com/36110676/125043585-c2f41800-e0a3-11eb-83ad-5f0d00bcde02.jpg)

**Comment by lonvia** [comment]
The search on the linked site looks to be working fine. I tried: http://109.95.212.124/search.php?q=s

**Comment by dmitrymaslov99** [comment]
Because we reinstalled exactly the same way and everything worked)
