### ISSUE TITLE
Wrong address Zaandam

### ISSUE THREAD

**Issue by alexbyldakov** [osm-search/Nominatim#2402]
## What did you search for?

https://nominatim.openstreetmap.org/ui/search.html?q=Zaandam+Westzijde+17B+

https://nominatim.openstreetmap.org/search?format=json&q=%20NL%20Zaandam%20Westzijde%2017B

Country: Netherlands
City: Zaandam
Street: Westzijde 
Street number: 17B  

## What result did you get?
![image](https://user-images.githubusercontent.com/50888479/126992842-b7350dff-501a-4ad0-80fd-e01f3a820d53.png)

## What result did you expect?
![image](https://user-images.githubusercontent.com/50888479/126992953-f6878f5d-5f11-4e5f-a123-9bf4f8f37629.png)

Can you clarify this data?

**Comment by mtmail** [comment]
In the OpenStreetMap data the clothing store is mapped as house number 17A, not 17B https://www.openstreetmap.org/node/2893584875

**Comment by lonvia** [comment]
Data issue.
