### ISSUE TITLE
Is it possible to give the country_code in Upper case?

### ISSUE THREAD

**Issue by jacobrajesh** [osm-search/Nominatim#2403]
## What did you search for?

https://nominatim.openstreetmap.org/reverse?format=jsonv2&lat=37.1357&lon=-121.6502

## What result did you get?
{
    "place_id": 95735168,
    "licence": "Data © OpenStreetMap contributors, ODbL 1.0. https://osm.org/copyright",
    "osm_type": "way",
    "osm_id": 27590902,
    "lat": "37.1357412",
    "lon": "-121.65025016900907",
    "place_rank": 30,
    "category": "amenity",
    "type": "school",
    "importance": 0,
    "addresstype": "amenity",
    "name": "El Toro Elementary School",
    "display_name": "El Toro Elementary School, Calle Buena Vista, Viento, Morgan Hill, Santa Clara County, California, 95037-3197, United States",
    "address": {
        "amenity": "El Toro Elementary School",
        "road": "Calle Buena Vista",
        "residential": "Viento",
        "town": "Morgan Hill",
        "county": "Santa Clara County",
        "state": "California",
        "postcode": "95037-3197",
        "country": "United States",
        "country_code": "us"
    },
    "boundingbox": [
        "37.1343067",
        "37.1369333",
        "-121.6520877",
        "-121.6484094"
    ]
}
## What result did you expect?
I expected  "country_code": "US"  instead of "us"  because the receiver application does not provide case insensitive matching. 

**Is the result in the right place and just named wrongly?** 

**Is the result missing completely?**

**Comment by lonvia** [comment]
Certainly not possible. What about all the other receiver applications that are used to getting the country code in lower case because that's what we have always done? You will have to fix your client to not make assumptions about case.
