### ISSUE TITLE
Update Zip Code Info

### ISSUE THREAD

**Issue by navercm418** [osm-search/Nominatim#2407]
Hello, just a little contribution..
I noticed for the coordinates below the postcode is "02046" but the actual postcode is "02370".  Everything else seems ok.
Thank you for all your hard work👍

location:
{'place_id': 109245240, 'licence': 'Data © OpenStreetMap contributors, ODbL 1.0. https://osm.org/copyright', 'osm_type': 'way', 'osm_id': 78363433, 'lat': '42.1646324', 'lon': '-70.89461701945069', 'display_name': 'The Home Depot, 1149, Hingham Street, Rockland, Plymouth County, Massachusetts, 02046, United States', 'address': {'shop': 'The Home Depot', 'house_number': '1149', 'road': 'Hingham Street', 'town': 'Rockland', 'county': 'Plymouth County', 'state': 'Massachusetts', 'postcode': '**02046**', 'country': 'United States', 'country_code': 'us'}, 'boundingbox': ['42.1639291', '42.165354', '-70.8955608', '-70.8939334']}

Reference:
https://www.google.com/maps/place/42%C2%B009'52.7%22N+70%C2%B053'40.6%22W/@42.1676595,-70.9234471,13.25z/data=!4m5!3m4!1s0x0:0x0!8m2!3d42.1646324!4d-70.894617

**Comment by mtmail** [comment]
The 02046 postcode is taken from this shop https://www.openstreetmap.org/node/4331452389 There aren't many other building with postcodes in OpenStreetMap data nearby. The school next door https://www.ssec.org/ has 02043 so I'd say the shop's postcode looks reasonable.

For the Home Depot store you can click "edit" on https://www.openstreetmap.org/way/78363433 which will open and editor and form where you can enter the correct postcode. Adding postcodes helps Nominatim calculate the center point better https://nominatim.org/release-docs/latest/develop/Postcodes/

I get an "access denied" error when I visit the homedepot.com website, maybe you can double-check there what they say their own postcode for their store is. Copying data from other licensed maps like Google into OpenStreetMap isn't allowed.

**Comment by mtmail** [comment]
Corrected the postcode of https://www.openstreetmap.org/node/4331452389 to 02043, so now no address in OpenStreetMap is 02046. It will need 24-48h before that's reflected in the Nominatim database.

I still can't access Home Depot, maybe they block users from outside the United States.

**Comment by navercm418** [comment]
Thank you for the quick reply.  Here is the info from Home Depot website:

**Comment by mtmail** [comment]
Should be fine now https://nominatim.openstreetmap.org/reverse.php?lat=42.16463&lon=-70.894&format=jsonv2&pretty=1

**Comment by navercm418** [comment]
Thank you very much for your hard work 👍
