### ISSUE TITLE
Several Canadian postal codes have no results , inconsistent behavior sometimes hyphen accepted only, other times works with or without or space instead of hyphen

### ISSUE THREAD

**Issue by joejoseph00** [osm-search/Nominatim#2410]
## What did you search for?
g0n2j0, g1s3e5, g9n0a3, g0g1j0 and j0w1r0
g0n-2j0, g1s-3e5, g9n-0a3, g0g-1j0 and j0w-1r0
g0n 2j0, g1s 3e5, g9n 0a3, g0g 1j0 and j0w 1r0
G0N-2J0, G1S-3E5, G9N-0A3, G0G-1J0 and J0W-1R0
also
Montreal postal codes also problematic, see H2Y-1B5, h2y-1b5, h2y 1b5, h2y1b5

https://nominatim.openstreetmap.org/search?q=H2Y-1B5%2C+quebec%2C+canada&format=xml&addressdetails=1&limit=5

## What result did you get?
no result

## What result did you expect?
expect something like a working postal code
https://nominatim.openstreetmap.org/search?q=j9h-6y3%2C+quebec%2C+canada&format=xml&addressdetails=1&limit=5

some work with dash/hyphen, others do not work in any combination of space upper/lower case and with or without hyphen or space

**Is the result missing completely?**
YES, missing completely

To to the OSM object:

https://nominatim.openstreetmap.org/search?q=H2Y-1B5%2C+quebec%2C+canada&format=xml&addressdetails=1&limit=5

**Comment by lonvia** [comment]
We have the postcodes as they are mapped in OpenStreetMap. If you can't find them, then they are likely missing there. If you can't find a postcode despite there being data in OSM with the same postcode, please point out the relevant OSM object.

Regarding the spelling, this is the same issue. The postcodes can only be found in the way they have been enterd in OSM. being more lenient with respect to hypthens/spaces is already covered in #927.

**Comment by joejoseph00** [comment]
I'm not sure what you mean by an OSM object?

there are several postal codes missing with no results, others have results.

**Comment by joejoseph00** [comment]
related issues:

https://github.com/osm-search/Nominatim/issues/1452

https://github.com/osm-search/Nominatim/pull/1302

would like to know how to add the missing postal codes?

**Comment by joejoseph00** [comment]
![Uploading image.png…]()

**Comment by joejoseph00** [comment]
testing again:
https://nominatim.openstreetmap.org/ui/search.html?q=Montreal+Quebec+H2Y-2B5

no results in OSM 

however in postal code monde there's info about it: 
https://www.codepostalmonde.com/canada/street-place-d-youville-montreal-0600-h2y-2b5/

**Comment by mtmail** [comment]
There is a OpenStreetMap object with postcode `H2Y2B5` https://www.openstreetmap.org/way/339862099 and searching for "H2Y2B5, Canada" works. Nominatim can't handle searching for `H2Y 2B5` or `H2Y-2B5` yet for Canadian postcodes. And vice versa when the OSM object's postcode has spaces and somebody searches without spaces. That's an open feature request in https://github.com/osm-search/Nominatim/issues/927

https://www.nominatim.org/release-docs/develop/develop/Postcodes/ has background on postcode handling and the Overpass query I ran to find the OpenStreetMap object.

It's unclear where zip-code.com or codepotalmode.com their data from. If in doubt we need to assume it's a licensed dataset incompatible with OpenStreetMap's license. It's a good indication such a postcode exists but it's data or position can't be copied into OpenStreetMap's database.

If you have knowledge of a postcode you'd add it to an address or building, e.g. https://www.openstreetmap.org/node/3080858171 and click the 'edit' button on the top of the page. https://www.openstreetmap.org/fixthemap

> how do we confirm if this is missing data or a query issue?

Try all combinations `AAA BBB, Canada`, `AAA-BBB, Canada`, `AAABBB, Canada` in case the postcode is in the database in a different spelling. It's clearly a query issue that Nominatim doesn't do this automatically yet.

> how do we get more postal code data entered in OSM?

Users with local knowledge add those to addresses or buildings. Sometimes a datasource can be imported in bulk https://wiki.openstreetmap.org/wiki/Import That's outside the scope of the Nominatim search engine.

**Comment by olstjos** [comment]
ok I've dug down a bit and found out a bit what was happening, this is a crowdsourced dataset due to Canada Post behaving in a very anti-democratic anti-competitive way.  http://geocoder.ca/?sued=1

I'm in the process of elaborating a complaint to the open data canada organisation and if I have to will write to some Members of Parliament.

**Comment by mtmail** [comment]
Check with the OpenStreetMap Canada community https://lists.openstreetmap.org/listinfo/talk-ca what the current status is. E.g. a previous discussion in 2019 https://lists.openstreetmap.org/pipermail/talk-ca/2019-October/thread.html
