### ISSUE TITLE
SSL handshake error connecting to nominatim.openstreetmap.org

### ISSUE THREAD

**Issue by notsectr** [osm-search/Nominatim#2419]
I created a reverse geocode task with a tasker to use it in my car's android 4.4.4 headunit. But I am getting Http error like this. I can connect with Locaioniq without such an error, but it is limited.

javax.net.ssl.SSL.HandshakeException:javax.net.SSL.ProtocolException:SSL handshake aborted.ssl=0x6a565d60 Failure in SSL library,usually a protocol error
error:14077410:SSLroutines.SSL_23_GET_SERVER_HELLO sslv3 alert handshake failure (external/open.ssl/ssl/s23_clnt.c:741 0x5a613d74:0x00000000

Is there a solution to the problem?

**Comment by mtmail** [comment]
*.openstreetmap.org servers no longer support SSL protocols versions below TLS 1.2. That's a security best practice https://www.securityweek.com/major-browsers-kill-tls-10-11

Some older operating systems don't support TLS 1.2, for example Windows 7. I see there's a couple of web tutorials to add/enable TLS 1.2 on Android 4.4, so you might have luck.

**Comment by lonvia** [comment]
This is a wontfix then.
