### ISSUE TITLE
Jakarta not found for this query

### ISSUE THREAD

**Issue by LeCoupa** [osm-search/Nominatim#2426]
Just to let you know, Jakarta is not returned for this query:

```
jakarta, jakarta raya, indonesia
```

https://nominatim.openstreetmap.org/search/?q=jakarta,%20jakarta%20raya,%20indonesia&accept-language=en&addressdetails=1&format=json&limit=3

**Comment by lonvia** [comment]
Thanks for letting us know but it's completely unclear if you expect us to do about something about it. Please use the [issue template](https://github.com/osm-search/Nominatim/issues/new?assignees=&labels=&template=report-issues-with-search-results.md&title=) to create a full bug report if you think you have found an issue with the **software** Nominiatim.
