### ISSUE TITLE
Wrong CORRS headers

### ISSUE THREAD

**Issue by mauricio-rp** [osm-search/Nominatim#2430]
## What did you search for?
https://nominatim.openstreetmap.org/search?format=json&limit=1&street=135%2011%20DE%20SEPTIEMBRE&city=PERGAMINO

## What result did you get?
has been blocked by CORS policy: The 'Access-Control-Allow-Origin' header contains multiple values '*, *', but only one is allowed.

## What result did you expect?
The gps position

The server is returning double "access-control-allow-origin" headers

![ErrorCORRS](https://user-images.githubusercontent.com/89310670/130327085-dc490a88-98c3-4887-bcd5-be2d61a0b261.png)

**Comment by lonvia** [comment]
Sorry, operational error. Fixed.

**Comment by mauricio-rp** [comment]
Thank you, that was fast! :)
