### ISSUE TITLE
Lincoln School node N358769365 is no longer a school

### ISSUE THREAD

**Issue by purp** [osm-search/Nominatim#2431]
## What did you search for?

Lincoln School, Alameda CA

## What result did you get?

I got [N358769365](https://nominatim.openstreetmap.org/ui/details.html?osmtype=N&osmid=358769365&class=amenity)

## What result did you expect?

I got what I expected: a node for a place that no longer exists. In the late 1980s, the new Lincoln Middle School opened, at which point the old school was demolished and turned into housing. This node was imported [12 years ago](https://www.openstreetmap.org/changeset/781903#map=4/33.67/-102.22) as part of a known-inaccurate GNIS import.

**Is the result in the right place and just named wrongly?** 

Maybe? I don't know how y'all treat historical locations. Maybe "Site of former Lincoln School"?

**Is the result missing completely?**

No. The result is erroneous or incomplete.

## Further details

This was Lincoln Middle School in the late 1980s, at which time it moved to [this location (W199894417)](https://nominatim.openstreetmap.org/ui/details.html?osmtype=W&osmid=199894417&class=amenity)

p.s. as someone not involved with the project, it was really hard to figure out how to contribute this information. No combination of the FAQ, wiki, or Github gave me any confidence of how to submit a simple data correction. Hope this is a decent way, and it might be helpful to provide a more obvious path. Would have preferred to be able to enter a correction somewhere, have someone review the correction and approve or give notes. Instead, I did a fair amount of work seeking and maybe understanding so I could make work for someone else. =\

**Comment by lonvia** [comment]
This is a data issue, which needs to be fixed in the data source, [OpenStreetMap](https://openstreetmap.org). You can either get an account an fix the school yourself or leave a note and hope that another member of the community fixes the data. See https://www.openstreetmap.org/fixthemap for more information. I'll add a link to fixthemap in the issue template.
