### ISSUE TITLE
Searching for a term that is substring of a place doesn't get this place as result (not even on "more results")

### ISSUE THREAD

**Issue by jase88** [osm-search/Nominatim#244]
Hey,

If I'm searching for a term that is part of a name of a place, this place doesn't show up in this results. I scrolled to serveral pages for the two examples. These results should be considered as possible results.

Examples:
**a)**
Search term: [Halle](https://nominatim.openstreetmap.org/search.php?q=Halle)
Looking for: [Halle (Saale)](https://nominatim.openstreetmap.org/details.php?place_id=16954397) 
Results like Hayle, Hälle are found on "more results", but the city "Halle" near the river "Saale" with a population around 230.000 is not suggested.

**b)**
Search term: [Audorf](https://nominatim.openstreetmap.org/search.php?q=Audorf)
Looking for: [Schacht-Audorf](https://nominatim.openstreetmap.org/details.php?place_id=127836278) 
Streets like "Au" or "Dorf" are suggested, but not "Schacht-Audorf", which matches better then most other results.

In other cases this works better e.g. New York -> New York City
Maybe this is caused because of special character in the name.

There might be better examples. These two were just some I came across.

Thanks for your attention ;)

**Comment by lonvia** [comment]
Both terms have the problem that they are simply to common to work well with a partial search. It might be possible to give the first one a boost by adding the assumption that the part outside the brackets is a full word but there is little that can be done for the second. If it is common among locals to abbreviate this village as 'Audorf', add it as short_name or local_name.

**Comment by kerosin** [comment]
Thanks for your reply. Yes the second example isn't that important. I added loc_name="Audorf" to it and hopefully this will do the job. 

But the first example is pretty common in Germany. To differentiate from cities with the same name there is often put a suffix - mostly in brackets.
Frankfurt am Main - Frankfurt (Oder)
Neustadt in Sachsen - Neustadt in Holstein - Neustadt (Dosse) - Neustadt (Hessen) (there are about 10 or more of them)
There are a lot more examples...

**Comment by gagarine** [comment]
This bug make it stupidly hard to find places on OSM (I have to use Google Map to find it on OSM). It's also linked with the fact that Nominatim doesn't seem to take into account the user context (where the user is right now on the map).

Searching for `Grand Théâtre de Genève` works but not any other combination like `Grand Théâtre`  or `Grand Théâtre Genève` even if I'm actually in Geneva.

**Comment by scaidermern** [comment]
> Examples:
> **a)**
> Search term: [Halle](https://nominatim.openstreetmap.org/search.php?q=Halle)
> Looking for: [Halle (Saale)](https://nominatim.openstreetmap.org/details.php?place_id=16954397)
> Results like Hayle, Hälle are found on "more results", but the city "Halle" near the river "Saale" with a population around 230.000 is not suggested.

Meanwhile searching for "Halle" returns the correct result. However that's probably because someone added `alt_name=Halle`.

The same problem persists for [Kempten](https://nominatim.openstreetmap.org/search.php?q=Kempten) which fails to find [Kempten (Allgäu)](https://nominatim.openstreetmap.org/details.php?place_id=618053). Adding `alt_name=Kempten` is a possible workaround, however this doesn't scale.
