### ISSUE TITLE
Неверно отображается регион Крым для России

### ISSUE THREAD

**Issue by Nuftiev** [osm-search/Nominatim#2443]
## What did you search for?

Добрый день, я искал города в респулблике Крым, указав при этом страну Россия, большинство из них привязаны к Украине
## What result did you get? 
вместо России, указана Украина

## What result did you expect?
у городов Республики Крым страна должна быть Россия

**Comment by lonvia** [comment]
The Crimea is currently mapped as being part of Ukraine and Russia in OpenStreetMap. Nominatim isn't designed to handle places in two countries, so the actual assignment to a country is essentially random. There is already an issue for this: #202. So closing this issue as a duplicate.

Note: the current tagging of the Crimea peninsula in OSM is a result of a community agreement and **must not** be changed.
