### ISSUE TITLE
Nominatim should regularly clean deleted relations

### ISSUE THREAD

**Issue by ztzthu** [osm-search/Nominatim#2444]
Example: 
https://www.openstreetmap.org/search?whereami=1&query=38.8288%2C119.7811#map=9/38.8290/119.7839

Nominatim returns a deleted relation (deleted 3 months ago).

And also I wonder what is the frequency of the sync process with OSM database? 

Thanks.

**Comment by ztzthu** [comment]
I see the problem duplicated with #500. Nvm :)

**Comment by ztzthu** [comment]
And could you please look into this issue:
https://www.openstreetmap.org/search?whereami=1&query=25.7452%2C123.4723#map=12/25.7452/123.4723

The reverse geocoding returns a relation that does not enclose the query point.

**Comment by lonvia** [comment]
I've clean up all deleted relations older than 1 month now. This is really something that should be automated.

This is the query for removing all older deleted objects:
```
select place_force_delete(p.place_id) from import_polygon_delete d, placex p
where p.osm_type = d.osm_type and p.osm_id = d.osm_id and age(p.indexed_date) > '1 month'::interval
```

We should add a subcommand to `nominatim admin` for convenience.

**Comment by ztzthu** [comment]
Thanks for the reply Ionvia:) Also do you have any comments regarding the third comment in this issue, i.e.

https://github.com/osm-search/Nominatim/issues/2444#issuecomment-915912898

Is that also a result of some unsynchronization with the OSM data ?

**Comment by lonvia** [comment]
@ztzthu I've deliberate ignored the question: please don't mix different topics in one Github issue.

**Comment by ztzthu** [comment]
I see. I thought the two issues were the same. Will open another ticket for this one.

**Comment by jcob-sikorski** [comment]
Which files correspond to the proposed changes?

**Comment by lonvia** [comment]
First you need to add a new command `--clean-deleted` to the nominatim tool in the [module for the admin subcommand](https://github.com/osm-search/Nominatim/blob/master/nominatim/clicmd/admin.py). Then you need a new function `clean_deleted_relations` in the [admin module](https://github.com/osm-search/Nominatim/blob/master/nominatim/tools/admin.py).

The command needs a mandatory parameter that defines how old relations are that should be deleted. I suggest to simply define that the parameter must be a [Postgresql time interval](https://www.postgresql.org/docs/current/datatype-datetime.html#DATATYPE-INTERVAL-INPUT) and hand this directly in into SQL.

That means a command `nominatim admin --clean-deleted "3 months"` would translate into `select place_force_delete(p.place_id) from import_polygon_delete d, placex p
where p.osm_type = d.osm_type and p.osm_id = d.osm_id and age(p.indexed_date) > '3 months'::interval`.

Finally, unit tests for both changes need to be added in https://github.com/osm-search/Nominatim/blob/master/test/python/cli/test_cmd_admin.py and https://github.com/osm-search/Nominatim/blob/master/test/python/tools/test_admin.py respectively.

**Comment by lujoh** [comment]
Hi, I would like to work on this issue if nobody else is working on it.

**Comment by mtmail** [comment]
@lujoh Go ahead. Nominatim is in a big migration from a PHP to Python framework (https://nominatim.org/blog/). The files mentioned in lonvia's last comment point to the Python implementation already so that's good. You no longer need to worry about any PHP.
