### ISSUE TITLE
In Slovakia, district is incorrectly returned instead of city

### ISSUE THREAD

**Issue by MSlivone** [osm-search/Nominatim#2453]
## What did you search for?

https://nominatim.openstreetmap.org/search?q=48.332037222+18.2675750009&format=jsonv2&addressdetails=1&accept-language=en
https://nominatim.openstreetmap.org/search?q=48.332037222+18.2675750009&format=jsonv2&addressdetails=1&accept-language=sk

The problem seems to be generic to the whole country. In neighbouring countries (e.g. CZ) the mapping is correct.

## What result did you get?

in English: "address":{ ..., "city_district":"Beladice","city":"District of Zlaté Moravce", ...}
in Slovak "address":{ ..., "city_district":"Beladice","city":"okres Zlaté Moravce", ...}

The "city" value corresponds to the district, i.e. subdivision of country LAU 1 (former NUTS 4). This is wrong.

## What result did you expect?

The "city" should be filled with real city / municipality. In the above example probably as "Beladice". Alternatively, the attribute "village" may be used instead of city.

**Comment by lonvia** [comment]
So where should the districts go instead? Would a designation of 'county' be about right as an equivalent?

**Comment by MSlivone** [comment]
Hi, in my opinion the county is a good fit for the district. (I have checked that in the neighbouring Czech Republic, the district is usually referred to as county.)

**Comment by MSlivone** [comment]
Excellent, thanks for the quick fix Ionvia
