### ISSUE TITLE
Searches in Cabrales (Spain) return results from Valparaiso (Chile)

### ISSUE THREAD

**Issue by Juanjo-MC** [osm-search/Nominatim#2464]
## What did you search for?

[farmacias en cabrales](https://nominatim.openstreetmap.org/ui/search.html?q=farmacias+en+cabrales) [1]
[farmacias en Cabrales](https://nominatim.openstreetmap.org/ui/search.html?q=farmacias+en+Cabrales) [2]
[pharmacies in cabrales](https://nominatim.openstreetmap.org/ui/search.html?q=pharmacies+in+cabrales) [3]
[gasolineras en cabrales](https://nominatim.openstreetmap.org/ui/search.html?q=gasolineras+en+cabrales) [4]
[gasolineras en Cabrales](https://nominatim.openstreetmap.org/ui/search.html?q=gasolineras+en+Cabrales) [5]
[fuel stations in cabrales](https://nominatim.openstreetmap.org/ui/search.html?q=fuel+stations+in+cabrales) [6]

## What result did you get?

Searching for amenities in Cabrales (a Spanish municipality) using special phrases is returning results from Valparaiso (Chile) along those within Cabrales.
Using special phases in Spanish, when the municipality name is not correctly capitalized, [1] and [4], results from Cabrales are not at the top.  Position 6 for [1] and 18 for [4]
When the municipality name is properly capitalized, [2] and [5], results within Cabrales are at the top of the list.
Using special phrases in English, [3] and [6] the results from Cabrales arrives at the top, no matter if it is capitalized or not.

## What result did you expect?

I expected nominatim to return results within Cabrales, the Spanish municipality, at the top. There is a neighborhood, and several streets within it, called Cabrales in Valparaiso (Chile) but nominatim is returning results located several kilometers away from it.

**Comment by lonvia** [comment]
This seems to have fixed itself with the tweaks to special searches, possibly in #3290.
