### ISSUE TITLE
Searches for city, name of street in Cyrillic

### ISSUE THREAD

**Issue by mtk11** [osm-search/Nominatim#2468]
## What did you search for?

Русе славянска

## What result did you get?

Results from OpenStreetMap Nominatim https://nominatim.openstreetmap.org/ui/search.html?q=Русе+славянска
Residential Road Slavyanska, Golyamo Vranovo, Slivo Pole, Ruse, 7065, Bulgaria
Residential Road Slavyanska, Sandrovo, Ruse, 7059, Bulgaria
- now a click on "more results" is required -
Secondary Road Bul. Slavyanski, Old Center, Ruse, 7000, Bulgaria
Secondary Road bul. Slavyanski, Old Center, Ruse, 7000, Bulgaria
Secondary Road bul. Slavyasnki, Old Center, Ruse, 7000, Bulgaria
Residential Road Slavyanska 2-ra, Marten, Ruse, 7058, Bulgaria
Residential Road Slavyanska 1-va, Marten, Ruse, 7058, Bulgaria
Residential Road Slavyanska 3-ta, Marten, Ruse, 7058, Bulgaria

## What result did you expect?

Secondary Road Bul. Slavyanski, Old Center, Ruse, 7000, Bulgaria
Secondary Road bul. Slavyanski, Old Center, Ruse, 7000, Bulgaria
Secondary Road bul. Slavyasnki, Old Center, Ruse, 7000, Bulgaria
Residential Road Slavyanska 2-ra, Marten, Ruse, 7058, Bulgaria
Residential Road Slavyanska 1-va, Marten, Ruse, 7058, Bulgaria
Residential Road Slavyanska 3-ta, Marten, Ruse, 7058, Bulgaria
Residential Road Slavyanska, Sandrovo, Ruse, 7059, Bulgaria
Residential Road Slavyanska, Golyamo Vranovo, Slivo Pole, Ruse, 7065, Bulgaria

## Further details

Searched for city, street. The results were sorted by the street name, also in English. Ruse is a region.

**Comment by mtk11** [comment]
@mtmail, Yes. There is also question with districts. For example. if try city. suburb search: Ruse, Rodina, the results are:

Results from OpenStreetMap Nominatim
Residential Road Rodina, жк. Родина 3, Ruse, 7012, Bulgaria
Residential Road Rodina, кв. Родина 4, Ruse, 7012, Bulgaria
Tertiary Road Rodina, Borisovo, Slivo Pole, Ruse, 7064, Bulgaria
Residential Road Rodina, Senovo, Vetovo, Ruse, 7038, Bulgaria
Stadium Stadium "Danube" Ruse, Ticha, в.з. "Кръста", жк. Родина 1, Ruse, 7006, Bulgaria
Stadium City Stadium, Mehomia, кв.Ялта, Ruse, 7002, Bulgaria
University University of Ruse "Angel Kanchev", 8, Studentska, жк. Здравец-север 1, Студентски град, Ruse, 7017, Bulgaria
Suburb жк. Родина 2, Ruse, 7006, Bulgaria
Suburb кв. Родина 4, Ruse, 7001, Bulgaria
Suburb жк. Родина 3, Ruse, 7018, Bulgaria
Suburb жк. Родина 1, Ruse, 7006, Bulgaria

But the following results suppose to be ranked higher:

Suburb жк. Родина 2, Ruse, 7006, Bulgaria
Suburb кв. Родина 4, Ruse, 7001, Bulgaria
Suburb жк. Родина 3, Ruse, 7018, Bulgaria
Suburb жк. Родина 1, Ruse, 7006, Bulgaria

**Comment by lonvia** [comment]
Known issue, needs #2268 to be solved. Closing here.
