### ISSUE TITLE
update mechanism broken after aborted update

### ISSUE THREAD

**Issue by MichaelKorn** [osm-search/Nominatim#2503]
**Describe the bug**
After an aborted incremental update (`nominatim replication`) the update mechanism is broken due to `duplicate key value violates unique constraint "idx_place_osm_unique"`.
The update was aborted because the connection between my notebook and the server was interrupted.
Current output if I start the replication process:
```
nominatim@hostname:/app$ nominatim replication --project-dir /nominatim
2021-10-29 14:16:56: Using project directory: /nominatim
2021-10-29 14:17:26  osm2pgsql version 1.4.1
2021-10-29 14:17:26  Database version: 12.8 (Ubuntu 12.8-0ubuntu0.20.04.1)
2021-10-29 14:17:26  PostGIS version: 3.0
2021-10-29 14:17:26  Node-cache: cache=2000MB, maxblocks=32000*65536, allocation method=11
2021-10-29 14:17:26  Parsing gazetteer style file '/usr/local/etc/nominatim/import-full.style'.
Processing: Node(2134k 237.1k/s) Way(16k 0.42k/s) Relation(0 0.0/s)2021-10-29 14:18:13  ERROR: DB copy thread failed: Ending COPY mode for 'place' failed: ERROR:  duplicate key value violates unique constraint "idx_place_osm_unique"
DETAIL:  Key (osm_id, osm_type, class, type)=(9133372933, N, place, locality) already exists.
CONTEXT:  COPY place, line 1: "9133372933       N       place   locality        "name"=>"La Tuileire"   15      \N      \N      0101000020E6100000D6952AACAFE11940E55BC41..."
.
Traceback (most recent call last):
  File "/usr/local/bin/nominatim", line 11, in <module>
    exit(cli.nominatim(module_dir='/usr/local/lib/nominatim/module',
  File "/usr/local/lib/nominatim/lib-python/nominatim/cli.py", line 288, in nominatim
    return parser.run(**kwargs)
  File "/usr/local/lib/nominatim/lib-python/nominatim/cli.py", line 92, in run
    return args.command.run(args)
  File "/usr/local/lib/nominatim/lib-python/nominatim/clicmd/replication.py", line 154, in run
    UpdateReplication._update(args)
  File "/usr/local/lib/nominatim/lib-python/nominatim/clicmd/replication.py", line 113, in _update
    state = replication.update(conn, params)
  File "/usr/local/lib/nominatim/lib-python/nominatim/tools/replication.py", line 119, in update
    run_osm2pgsql(options)
  File "/usr/local/lib/nominatim/lib-python/nominatim/tools/exec_utils.py", line 131, in run_osm2pgsql
    subprocess.run(cmd, cwd=options.get('cwd', '.'), env=env, check=True)
  File "/usr/lib/python3.8/subprocess.py", line 516, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['/usr/local/lib/nominatim/osm2pgsql', '--hstore', '--latlon', '--slim', '--with-forward-dependencies', 'false', '--log-progress', 'true', '--number-processes', '1', '--cache', '2000', '--output', 'gazetteer', '--style', '/usr/local/etc/nominatim/import-full.style', '--append', '--flat-nodes', '/nominatim/flatnode/flatnode.file', '/nominatim/osmosischange.osc']' returned non-zero exit status 2.
```
Maybe related to https://github.com/osm-search/Nominatim/issues/1695

**To Reproduce**
I suppose to interrupt a `nominatim replication` in the wrong moment should reproduce the situation. Unfortunately, I can not find out when the interruption occurred, but I know that a few (daily) updates were successfully applied beforehand.

**Expectations**
In the short term, I would be happy if I could get my installation back into a consistent state.
In addition, the update process should become more robust, because an update takes a relatively long time and is carried out very regularly. It is therefore relatively likely that problems will arise.

**Software Environment:**
- Nominatim version: 3.7 (Docker image: mediagis/nominatim:3.7)
- Postgresql version: 12.8
- Postgis version: 3.0
- OS: Container-Optimized OS (cos-89)

**Hardware Configuration (for the imported a bigger machine was used):**
- RAM: 32 Gib
- number of CPUs: 4 vCPUs
- type and size of disks: 740GB standard HHD (+HDD OS, with swap)

**Postgresql Configuration:**
```
fsync = off
full_page_writes = off

shared_buffers = 2GB
maintenance_work_mem = 10GB
autovacuum_work_mem = 2GB
work_mem = 50MB
effective_cache_size = 24GB
synchronous_commit = off
max_wal_size = 1GB
checkpoint_timeout = 10min
checkpoint_completion_target = 0.9
```

**Additional context**
Europe is imported.
Faltnode storage is activated.
The import of a daily update takes about 40 minutes.

**Comment by lonvia** [comment]
Can you please put the change file `/nominatim/osmosischange.osc` somewhere (feel free to gzip it first, if it is too large).

Also can you please log into the database with psql and get the output of the following commands: `\d+ place`, `SELECT * FROM place WHERE osm_type = 'N' and osm_id = 9133372933` and `SELECT * FROM placex WHERE osm_type = 'N' and osm_id = 9133372933`.

**Comment by MichaelKorn** [comment]
Hello Sarah,
Thank you very much for your help.
When I ran the Selects, the results were empty and I noticed that the problem had probably resolved itself overnight.
Now the updates are working again and I think it will be too time-consuming to find out what state the update process was in. I close the ticket again.

**Comment by lonvia** [comment]
Just for context: update are save to be interrupted at pretty much any time. If you run into trouble then it is likely either because your database is corrupted or the diffs are broken. There is a known issue with pyosmium < 3.2.0 when merging extract update files. Maybe you have run into this.
