### ISSUE TITLE
Not search results for certain STATEs 

### ISSUE THREAD

**Issue by dcormace** [osm-search/Nominatim#2508]
I am not getting results when running queries including STATE parameter for Buenos Aires (STATE), Argentina (but OK for other states, see examples):

## What did you search for?

1. https://nominatim.openstreetmap.org/ui/search.html?street=750+Emilio+Mitre&city=Martinez&county=Partido+de+San+Isidro&state=Buenos+Aires&country=Argentina
2. https://nominatim.openstreetmap.org/ui/search.html?street=750+Bartolome+Mitre&city=Lujan&state=Buenos+Aires&country=Argentina

## What result did you get?

1. Nothing 
2. Nothing 

## What result did you expect?
1. https://nominatim.openstreetmap.org/ui/search.html?street=750+Emilio+Mitre&city=Martinez&county=Partido+de+San+Isidro&country=Argentina
2. https://nominatim.openstreetmap.org/ui/search.html?street=750+Bartolome+Mitre&city=Lujan&country=Argentina

## Further details

For other STATES in Argentina I'm getting the correct result, for example:
a. https://nominatim.openstreetmap.org/ui/search.html?street=1202+Autonomista&city=Santa+Rosa&state=La+Pampa&country=Argentina
b. https://nominatim.openstreetmap.org/ui/search.html?street=750+Bartolom%C3%A9+Mitre&city=San+Carlos+de+Bariloche&state=Rio+Negro&country=Argentina
c. https://nominatim.openstreetmap.org/ui/search.html?street=750+Avenida+Colon&city=Cordoba&state=Cordoba&country=Argentina

**Comment by lonvia** [comment]
Thanks to a beginner's mistake in [this changeset](https://www.openstreetmap.org/changeset/111842107) there was no state of Buenos Aires when we did the reimport last week. Somebody has fixed the mistake by now but we'd have to reindex the entire state. That's an awfully large area.

**Comment by dcormace** [comment]
Yes. It's working now. THANKS AGAIN!!!!!!!
