### ISSUE TITLE
9148 W Church St, Des Plaines, IL, USA 60016 shows incorrectly. Google maps shows correctly.

### ISSUE THREAD

**Issue by galleyfairs** [osm-search/Nominatim#2512]
## What result did you expect?

**When the result in the right place and just named wrongly:** 

**When the result missing completely:**

**Comment by mtmail** [comment]
This might be the street in OpenStreetMap data, no 'W' in the name https://nominatim.openstreetmap.org/ui/details.html?osmtype=W&osmid=646258498&class=highway

It's against OpenStreetMap licence to copy data from licensed sources like Google Maps. If you have local first hand knowledge of the street you can use the 'Edit' button on https://www.openstreetmap.org/way/646258498 (or relevant street name) and make changes. Or alternatively leave a note for local mappers https://www.openstreetmap.org/fixthemap

**Comment by lonvia** [comment]
The house number is not in OSM data. The prefix issue is already covered in  #535.

Also, the issue templates are there for a reason.
