### ISSUE TITLE
Error when run replication - UnboundLocalError: local variable 'indexer' referenced before assignment

### ISSUE THREAD

**Issue by NormandoHall** [osm-search/Nominatim#2518]
**Describe the bug**

After initial import, I set the update `nominatim replication --init` for future updates from inside project folder. Then run `nominatim replication` for the first update, and runs ok. After 1600 seconds aprox. trigger the second update, and get this error:

**To Reproduce**

```
$ nominatim replication
2021-11-13 19:20:15: Using project directory: /opt/nominatim/project
Traceback (most recent call last):
  File "/usr/local/bin/nominatim", line 17, in <module>
    phpcgi_path='/bin/php-cgi'))
  File "/usr/local/lib64/nominatim/lib-python/nominatim/cli.py", line 235, in nominatim
    return parser.run(**kwargs)
  File "/usr/local/lib64/nominatim/lib-python/nominatim/cli.py", line 96, in run
    return args.command.run(args)
  File "/usr/local/lib64/nominatim/lib-python/nominatim/clicmd/replication.py", line 188, in run
    UpdateReplication._update(args)
  File "/usr/local/lib64/nominatim/lib-python/nominatim/clicmd/replication.py", line 164, in _update
    while indexer.has_pending():
UnboundLocalError: local variable 'indexer' referenced before assignment
```

**Software Environment (please complete the following information):**
- Nominatim version: 4.0.0
- Postgresql version: 14
- Postgis version: 3.2
- OS: centos 7

**Hardware Configuration (please complete the following information):**
- RAM: 16Gb
- number of CPUs: 4
- type and size of disks: SSD 500Gb
- bare metal/AWS/other cloud service: cloud

**Postgresql Configuration:**

Same as sugets installs docs

**Additional context**

Using geofabrick because initial import comes from geofabrick extract (Argentina)

`NOMINATIM_REPLICATION_URL="http://download.geofabrik.de/south-america/argentina-updates"`

If check for updates, get that is up to date:

```
$ nominatim replication --check-for-updates
2021-11-13 20:40:02: Using project directory: /opt/nominatim/project
2021-11-13 20:40:03: Database is up to date.
```

**Comment by NormandoHall** [comment]
News. After I checked again for new data, `nominatim replication` runs ok.

```
$ nominatim replication --check-for-updates
2021-11-14 03:51:32: Using project directory: /opt/nominatim/project
2021-11-14 03:51:33: New data available (3153 => 3154).
```

Seams that error occurs when there is no new data available for update

**Comment by NormandoHall** [comment]
So does it happen to someone else?

**Comment by lonvia** [comment]
There is now a fix for this on master. It would be nice if you could give it a try. master is 100% compatible with 4.0 at the moment, so you can simply install the master version and keep your existing DB. If that works for you, then I'll do a 4.0.1 release.

**Comment by NormandoHall** [comment]
@lonvia . Today I will test it and back with results. Thanks!

**Comment by NormandoHall** [comment]
Confirmed, runs like a charm. Thanks!

**Comment by lonvia** [comment]
4.0.1 is now out which should fix this error.
