### ISSUE TITLE
Does not search in name tags on assiciatedStreet relations

### ISSUE THREAD

**Issue by skfd** [osm-search/Nominatim#2519]
## What did you search for?

I [searched](https://nominatim.openstreetmap.org/ui/search.html?q=%D0%A6%D1%83%D0%BB%D1%83%D0%BA%D1%96%D0%B4%D0%B7%D0%B5+%D0%B2%D1%83%D0%BB%D0%B8%D1%86%D1%8F+%D0%BA%D0%B8%D0%B5%D0%B2&exclude_place_ids=133579039) for old name of the street. Old name has beein moved to `old_name:1955-2021` tag on `associatedStreet`. No result found.

Just in case, here is a proof query generaly works [Here is a proof it works with a general old_name](https://nominatim.openstreetmap.org/ui/search.html?q=%D0%B0%D1%80%D1%82%D0%B5%D0%BC%D0%B0+%D0%BA%D0%B8%D0%B5%D0%B2).

## What result did you get?

It did not find the street by old name in Киев.

## What result did you expect?

It should have found [renamed street](https://www.openstreetmap.org/relation/9500199).

## Further details

I think Nominatim should search in `old_name` of `associatedStreet`. It should respect language and date postfixes, but bias to more recent or general  `old_name` values.

Thank you!

**Comment by mtmail** [comment]
Adding the OSM wiki page for reference: https://wiki.openstreetmap.org/wiki/Key:old_name

**Comment by lonvia** [comment]
Nominatim does index old_name:* tags. It just does not index any names from `associatedStreet` relations. There are no plans to change this.

**Comment by skfd** [comment]
Why? This is a natural place to store meta-information about the streets.
