### ISSUE TITLE
Localized display_name result -- always only NUMBER, STREET, ....

### ISSUE THREAD

**Issue by rotdrop** [osm-search/Nominatim#2522]
## What did you search for?

https://nominatim.openstreetmap.org/search/Graf-Ulrich-Str.%201%2C%2071229%20Leonberg?format=json&addressdetails=1&extratags=1&namedetails=1&limit=8&accept-language=de

## What result did you get?

```
...
display_name: "1, Graf-Ulrich-Straße, Leonberg, Landkreis Böblingen, Baden-Württemberg, 71229, Deutschland"
...
```

## What result did you expect?

A German address-format because of accept-language=de (the accept-language header was de,en-US;q=0.7,en;q=0.3), in detail:

```
...
display_name: "Graf-Ulrich-Straße 1, 71229 Leonberg, Landkreis Böblingen, Baden-Württemberg, Deutschland"
...
```

**When the result in the right place and just named wrongly:** 

**When the result missing completely:**

## Further details

Of course, I can construct a suitable display-name from the particular fields which are present in the JSON response. But then: what is the purpose of the display_name property?

Thanks for all this work!

**Comment by mtmail** [comment]
Tracked in https://github.com/osm-search/Nominatim/issues/213 with the address-formatting library as work-around.
