### ISSUE TITLE
Postalcodelookup response  city: "null" with postcode: 95134

### ISSUE THREAD

**Issue by hcurtis810101** [osm-search/Nominatim#2523]
1. Request:
curl --location --request GET 'https://nominatim.openstreetmap.org/?format=json&addressdetails=1&postalcode=95134'

2. Response:
[
    {
        "place_id": 286336516,
        "licence": "Data © OpenStreetMap contributors, ODbL 1.0. https://osm.org/copyright",
        "boundingbox": [
            "37.248361597738",
            "37.568361597738",
            "-122.09886089308",
            "-121.77886089308"
        ],
        "lat": "37.40836159773795",
        "lon": "-121.93886089308147",
        "display_name": "Santa Clara County, California, 95134, United States",
        "class": "place",
        "type": "postcode",
        "importance": 0.33499999999999996,
        "address": {
            "county": "Santa Clara County",
            "state": "California",
            "postcode": "95134",
            "country": "United States",
            "country_code": "us"
        }
    },
    {
        "place_id": 286261243,
        "licence": "Data © OpenStreetMap contributors, ODbL 1.0. https://osm.org/copyright",
        "boundingbox": [
            "48.151845175",
            "48.471845175",
            "17.706723629033",
            "18.026723629033"
        ],
        "lat": "48.311845175",
        "lon": "17.866723629033046",
        "display_name": "Malý Báb, Báb, okres Nitra, Nitriansky kraj, Západné Slovensko, 95134, Slovensko",
        "class": "place",
        "type": "postcode",
        "importance": 0.33499999999999996,
        "address": {
            "city_district": "Malý Báb",
            "city": "Báb",
            "county": "okres Nitra",
            "state": "Nitriansky kraj",
            "region": "Západné Slovensko",
            "postcode": "95134",
            "country": "Slovensko",
            "country_code": "sk"
        }
    },
    {
        "place_id": 285658715,
        "licence": "Data © OpenStreetMap contributors, ODbL 1.0. https://osm.org/copyright",
        "boundingbox": [
            "55.510765383333",
            "55.830765383333",
            "21.024318721625",
            "21.344318721625"
        ],
        "lat": "55.67076538333333",
        "lon": "21.1843187216249",
        "display_name": "Klaipėda, Klaipėdos miesto savivaldybė, Klaipėdos apskritis, 95134, Lietuva",
        "class": "place",
        "type": "postcode",
        "importance": 0.33499999999999996,
        "address": {
            "city": "Klaipėda",
            "state_district": "Klaipėdos miesto savivaldybė",
            "state": "Klaipėdos apskritis",
            "postcode": "95134",
            "country": "Lietuva",
            "country_code": "lt"
        }
    }
]

For US, city was not provided in the content of address

**Comment by lonvia** [comment]
The boundary of San Jose was broken when the postcode was indexed. I've updated the servers. That said there is no guarantee that the result for the postcode contains a city element, especially in the US with its rather odd postal cities.
