### ISSUE TITLE
Problem with tokenizer in 4.0

### ISSUE THREAD

**Issue by Vrumfondel** [osm-search/Nominatim#2524]
I did an upgrade from 3.7 zu 4.0.

When I now want to access via nominatim-ui, I seem to get a lot of trouble with tokenizer used in Status.php

1. CONST_TokenizerDir seems not be be defined correctly (or the define included).

2. When I set the full path in Status.php directly, this results in an error "Call to a member function checkStatus() on null).

Any hints how to fix this?

**Comment by Vrumfondel** [comment]
... not beeing an php expert, but from what I see all these declarations are done in warm.php - which seems not to be used.

**Comment by Vrumfondel** [comment]
OK,
 my mistake. If you recreate the website you really need to make sure the newly generated files .....

**Comment by mausch** [comment]
I seem to be having issues with this too. Can you explain a bit how you fixed it?
