### ISSUE TITLE
Address search in error if "bis" in number

### ISSUE THREAD

**Issue by sylvain-m** [osm-search/Nominatim#2527]
Even if the addresses are present in OSM, searches with a `bis` in the number are unsuccessful.
Here is an example: `9 bis Rue Georges Brassens 61250 Valframbert` ([OSM Node](https://www.openstreetmap.org/node/3670794379))

-  with `bis` = no result
    https://nominatim.openstreetmap.org/ui/search.html?q=9+bis+Rue+Georges+Brassens+61250+Valframbert

-  without `bis` = result ok
    https://nominatim.openstreetmap.org/ui/search.html?q=9+Rue+Georges+Brassens+61250+Valframbert

[Same search with Photon](https://photon.komoot.io/api/?q=9%20bis%20Rue%20Georges%20Brassens%2061250%20Valframbert) is successful

(I originally [posted this request on their repository](https://github.com/komoot/photon/issues/614), but the problem was with the date the data was updated. In this case, the address node is several years old.)

**Comment by lonvia** [comment]
Fallout of #2437. Now the penalty for house numbers with a letter in them is getting so large that 'bis' numbers are effectively dropped.
