### ISSUE TITLE
incorrect packet name in centos7 install script

### ISSUE THREAD

**Issue by boooch** [osm-search/Nominatim#2531]
**libicu-dev**  must **be libicu-devel**

**Comment by lonvia** [comment]
I know that this is not exactly the answer you are looking for but I think we should remove the Centos7 instructions completely. They are not tested or kept up to date and CentOS8 has been out long enough to reasonably expect that people have switched by now.

**Comment by lonvia** [comment]
The package name is now fixed in the release documentation. For current master, #2540 removes the installation instructions for CentOS7 completely.
