### ISSUE TITLE
Some of the data about boroughs in Kharkiv Ukraine has disappeared

### ISSUE THREAD

**Issue by kharkovtourist** [osm-search/Nominatim#2537]
I am trying to get data about https://nominatim.openstreetmap.org/search?q=старицкого 9, Харьков&addressdetails=1&format=json&limit=1

And i get
[{"place_id":122869332,"licence":"Data © OpenStreetMap contributors, ODbL 1.0. https://osm.org/copyright","osm_type":"way","osm_id":94826383,"boundingbox":["50.0332635","50.0343247","36.2373837","36.2386649"],"lat":"50.03383895","lon":"36.23809418296452","display_name":"9, Старицкого улица, Микрорайон 6, Павлово Поле, Харьков, Харківська міська громада, Харьковский район, Харьковская область, 61103, Украина","class":"building","type":"apartments","importance":0.22100000000000003,"address":{"house_number":"9","road":"Старицкого улица","residential":"Микрорайон 6","suburb":"Павлово Поле","city":"Харьков","municipality":"Харківська міська громада","district":"Харьковский район","state":"Харьковская область","postcode":"61103","country":"Украина","country_code":"ua"}}]

this data does not contain **borough": "Шевченковский район"**
https://www.openstreetmap.org/relation/3796255

This relation are broken for all streets and buildings. Also lost Новобаварский and Холодногорский boroughs.

**Comment by mtmail** [comment]
https://nominatim.openstreetmap.org/ui/details.html?osmtype=W&osmid=94826383 works again I think.

For other broken relations or data please contact local mappers https://openstreetmap.community/ (or the last person who edited the relation). This issue tracker is about Nominatim software, not general OpenStreetMap data issues.
