### ISSUE TITLE
state is missing in address property

### ISSUE THREAD

**Issue by bart** [osm-search/Nominatim#2538]
It looks like the current version running in production doesn't return a `state` as part of the `address property` anymore. Example: https://nominatim.openstreetmap.org/search/Unter%20den%20Linden%201%20Berlin?format=json&addressdetails=1&limit=1

```
...
"address": {
  "road": "Unter den Linden",
  "suburb": "Mitte",
  "borough": "Mitte",
  "city": "Berlin",
  "postcode": "10117",
  "country": "Deutschland",
  "country_code": "de"
}
...
```

**Comment by lonvia** [comment]
Same issue as #1817. Berlin is a city state, so Nominatim only returns the city.

**Comment by bart** [comment]
But it worked at least until yesterday @lonvia and also makes sense to always show both. State and city might be the same value but are logically two different geographic fields.

**Comment by bart** [comment]
Btw. in your official documentation Berlin is state is also described as part of the address property (as I said, like we got it back until yesterday): https://nominatim.org/release-docs/develop/api/Search/#json-with-svg-polygon
