### ISSUE TITLE
Service is down

### ISSUE THREAD

**Issue by faustoct** [osm-search/Nominatim#2541]
https://nominatim.openstreetmap.org is it down ? What happened and how often does it happen ?

**Comment by otbutz** [comment]
It works for me ™

> how often does it happen ?

Reading between the lines: don't rely on the public Nominatim instance for any kind of service. Host your own instead.

**Comment by faustoct** [comment]
What you mean by my own domain? I am working on this nominatim under openstreet is it reliable? It is working again .

**Comment by faustoct** [comment]
looks down again

**Comment by otbutz** [comment]
Maybe you're hitting the ratelimit.

> No heavy uses (an absolute maximum of **1 request per second**).

> As a general rule, bulk geocoding of larger amounts of data is **not** encouraged. 

https://operations.osmfoundation.org/policies/nominatim/

**Comment by faustoct** [comment]
what you mean ? I doing by web browser
<img width="1440" alt="Screen Shot 2021-12-07 at 08 56 00" src="https://user-images.githubusercontent.com/3135444/145024850-090a4080-d291-4df9-8ede-50f9c31d157f.png">

**Comment by faustoct** [comment]
> Results must be cached on your side. Clients sending repeatedly the same query may be classified as faulty and blocked.
It is unblocked after rate limit reached ? We are caching on backend BUT it can be multiple requests from same server. Can it be go against the policy?

**Comment by faustoct** [comment]
@otbutz it probably blocked the ip of my home. So what next ? It is my dev environment!

**Comment by otbutz** [comment]
The block is only temporary AFAIK but i don't know how long. If it's business critical, you should always consider to run your own server.

https://nominatim.org/release-docs/latest/admin/Installation/

**Comment by faustoct** [comment]
@otbutz yes, it's business critical but it restrict the development environment. So is it bad ideia use [nominatim](https://nominatim.openstreetmap.org/ui/search.html) in production/business purpose?

**Comment by otbutz** [comment]
I wouldn't rely on it. Hosting your own Nominatim instance isn't witchcraft :)

**Comment by mtmail** [comment]
https://operations.osmfoundation.org/policies/nominatim/ explains the policy and alternatives.
