### ISSUE TITLE
nominatim: command not found

### ISSUE THREAD

**Issue by alansenairj** [osm-search/Nominatim#2543]
**Describe the bug**

nominatim command not found 

**To Reproduce**

I followed this instructions from here: 
https://nominatim.org/release-docs/develop/appendix/Install-on-Ubuntu-20/

root@instance-20211208-1836:/srv/nominatim/nominatim-project# history 
    1  sudo apt update -qq
    2  sudo apt install -y php-cgi
    3  sudo useradd -d /srv/nominatim -s /bin/bash -m nominatim
    4  export USERNAME=nominatim
    5  export USERHOME=/srv/nominatim
    6  chmod a+x $USERHOME
    7  cd /

    9  apt install mlocate
   10  updatedb

   15  sudo apt install -y build-essential cmake g++ libboost-dev libboost-system-dev                     libboost-filesystem-dev libexpat1-dev zlib1g-dev                     libbz2-dev libpq-dev libproj-dev                     postgresql-server-dev-12 postgresql-12-postgis-3                     postgresql-contrib-12 postgresql-12-postgis-3-scripts                     php php-pgsql php-intl libicu-dev python3-dotenv                     python3-psycopg2 python3-psutil python3-jinja2                     python3-icu python3-datrie git
   16  vi /etc/postgresql/12/main/postgresql.conf
   17  sudo systemctl restart postgresql
   18  sudo -u postgres createuser -s $USERNAME
   19  sudo -u postgres createuser www-data
   20  cd $USERHOME
   21  git clone --recursive git://github.com/openstreetmap/Nominatim.git
   22  cd Nominatim
   23  touch mapabr.sh
   24  vi mapabr.sh 
   25  wget -O data/country_osm_grid.sql.gz https://www.nominatim.org/data/country_grid.sql.gz
   26  mkdir $USERHOME/build
   27  cd $USERHOME/build
   28  cmake $USERHOME/Nominatim
   29  make
   30  mkdir $USERHOME/nominatim-project
   31  mkdir $USERHOME/nominatim-project/website
   32  sudo apt install -y apache2 libapache2-mod-php
   33  sudo tee /etc/apache2/conf-available/nominatim.conf << EOFAPACHECONF
<Directory "$USERHOME/nominatim-project/website">
  Options FollowSymLinks MultiViews
  AddType text/html   .php
  DirectoryIndex search.php
  Require all granted
</Directory>

Alias /nominatim $USERHOME/nominatim-project/website
EOFAPACHECONF

   34  sudo a2enconf nominatim
   35  sudo systemctl restart apache2
   36  ls

   41  locate mapabr
   42  cd nominatim-project/
   43  ls
   44  cd ..
   45  cd Nominatim/
   46  ls
   47  chmod a+x mapabr.sh 
   48  ./mapabr.sh 
   49  ls

   52  nominatim import --osm-file brazil-latest.osm.pbf 2>&1 | tee setup.log
   53  nominatim --help
   54  cd nominatim/
   55  ls
   56  cd ..
   57  ls
   58  cd build/
   59  ls
   60  cd ..
   61  ls
   62  cd nominatim-project/
   63  nominatim import --osm-file /srv/nominatim/Nominatim/brazil-latest.osm.pbf 

**Software Environment (please complete the following information):**
- Nominatim version: latest
- Postgresql version: 
- Postgis version:
- OS: Ubuntu 20.04

**Hardware Configuration (please complete the following information):**
- RAM: 16
- number of CPUs: 4
- type and size of disks:
- bare metal/AWS/other cloud service: oracle cloud

**Postgresql Configuration:**

**Additional context**

**Comment by mtmail** [comment]
I see `29 make` but not the `make install`. `mapabr.sh` is not part of the instructions, I can't tell what it does.

It's great you want to try the latest development version (https://nominatim.org/release-docs/develop/) but for production usage you might want to try the latest stable version (https://nominatim.org/release-docs/latest/)
