### ISSUE TITLE
Restore ability to run nominatim refresh --website without an active DB

### ISSUE THREAD

**Issue by victorhaggqvist** [osm-search/Nominatim#2544]
This is probably working as intended, but is a breaking change to previous behavior.

**Describe the bug**
Prior to 
https://github.com/osm-search/Nominatim/commit/e5ffc59cd5727237e52b0dc250f38acb3ede01f7 it was possible to run `nominatim refresh --website` without a DB connected, however that introduced a hard dependency of a DB.

This makes it, maybe not problematic, but at least a bit more annoying to generate the website at build time in an isolated environment, for eg. a container image.

**To Reproduce**
Attempt to run `nominatim refresh --website` in a env without a database.

**Proposed solution**
Either add an additional flag that would let me as operator acknowledge that at runtime the table will be present (or not).
Or, on when failure to connect to DB just log that as an warning and assume the presence of the table, which would restore the previous behavior.

**Comment by lonvia** [comment]
I don't understand your use-case. There is absolutely no need to have the website directory, even in a container environment, until you have imported the database. The import will create the website directory automatically.

Please also see the discussion in #2515.

**Comment by lonvia** [comment]
I assume the issue has resolved itself.
