### ISSUE TITLE
reverse geocoding not returning expected building number

### ISSUE THREAD

**Issue by freyfogle** [osm-search/Nominatim#2547]
## What did you search for?

59.33433, 18.07645

https://nominatim.openstreetmap.org/ui/reverse.html?lat=59.33433&lon=18.07645&zoom=18 

## What result did you get?

Hotel Riddargatan (node 1383446156)

Specifically I see "Hotel Riddargatan - ProfilHotels, Riddargatan, Östermalm, Östermalms stadsdelsområde, Stockholm, Stockholms kommun, Stockholm County, 114 51, Sweden"

## What result did you expect?

I expected the hotel name, but also the building number

## Further details

If I modify the coordinates very slightly to 59.33440, 18.07652
https://nominatim.openstreetmap.org/ui/reverse.html?lat=59.33440&lon=18.07652&zoom=18

I get the correct building number, though not the hotel. 
"14, Riddargatan, Östermalm, Östermalms stadsdelsområde, Stockholm, Stockholms kommun, Stockholm County, 114 35, Sweden "

You can see on osm.org both building number and hotel name are displayed

<img width="433" alt="Screenshot 2021-12-09 at 15 55 42" src="https://user-images.githubusercontent.com/351074/145419600-b21b8603-8f04-4734-b774-11bbbe6caab1.png">

is there any way to get both the hotel name and the building number?
Is this a data issue? 

Just trying to understand what is happening here.

Thanks

**Comment by freyfogle** [comment]
sorry, forgot to add one more question - assuming it is not possible to get both hotel name and building number, is there any way to specify that building number is preferred?

**Comment by lonvia** [comment]
The hotel itself doesn't have a house number and there is no way for Nominatim to determine the house number except through guessing. The building to which it belongs has multiple housenumbers. So it would have to do something along the lines of: use the closest housenumber that is in or on the same buidling outline. It's not impossible but rather expensive. At the moment Nominatim inherits only housenumbers that are on the building outline itself.

As for always returning an address, that's an open feature request already covered in #1469.

**Comment by lonvia** [comment]
Closing as duplicate.
