### ISSUE TITLE
categorical/special search returns unexpected result

### ISSUE THREAD

**Issue by xinyuluo** [osm-search/Nominatim#2550]
## What did you search for?

hospitals singapore

https://nominatim.openstreetmap.org/ui/search.html?q=hospitals+singapore

## What result did you get?

A hospital in India (I wonder how did search process "singapore" in the query? )

## What result did you expect?

Some hospitals options in singapore, such as Singapore General Hospital, National University Hospital, etc.
similar to the list you'll get when searching "hospitals in singapore" (https://nominatim.openstreetmap.org/ui/search.html?q=hospitals+in+singapore&limit=50)

**Comment by lonvia** [comment]
If you don't specify 'in' you get a name search, not a search for POIs. This cannot be changed because it would lead to a lot of bad results for regular searches.

Please note that Nominatim is primarily a geocoder, not a POI search engine. Use Overpass API for that.
