### ISSUE TITLE
Is replication working?

### ISSUE THREAD

**Issue by Tri0L** [osm-search/Nominatim#2555]
I'm using nominatim helm installation.
Init already successfully done.

**Describe the bug**
I use next env variables for updater:
NOMINATIM_DATABASE_MODULE_PATH: /bitnami
NOMINATIM_IMPORT_STYLE: full
NOMINATIM_REPLICATION_URL: https://ftpmirror.your.org/pub/openstreetmap/replication/day/

In logs I see messages that no new updates:
```
2021-12-15 21:04:20: No new changes. Sleeping for 900 sec.
2021-12-15 21:19:20: Update completed. Import: 0:00:00. Total: 0:00:00. Remaining backlog: 9 days, 23:20:35.
2021-12-15 21:19:20: No new changes. Sleeping for 900 sec.
2021-12-15 21:34:20: Update completed. Import: 0:00:00. Total: 0:00:00. Remaining backlog: 9 days, 23:35:35.
2021-12-15 21:34:20: No new changes. Sleeping for 900 sec.
2021-12-15 21:49:20: Update completed. Import: 0:00:00. Total: 0:00:00. Remaining backlog: 9 days, 23:50:35.
2021-12-15 21:49:20: No new changes. Sleeping for 900 sec.
2021-12-15 22:04:20: Update completed. Import: 0:00:00. Total: 0:00:00. Remaining backlog: 10 days, 0:05:35.
2021-12-15 22:04:20: No new changes. Sleeping for 900 sec.
2021-12-15 22:19:21: Update completed. Import: 0:00:00. Total: 0:00:00. Remaining backlog: 10 days, 0:20:36.
2021-12-15 22:19:21: No new changes. Sleeping for 900 sec.
2021-12-15 22:34:21: Update completed. Import: 0:00:00. Total: 0:00:00. Remaining backlog: 10 days, 0:35:36.
2021-12-15 22:34:21: No new changes. Sleeping for 900 sec.
2021-12-15 22:49:21: Update completed. Import: 0:00:00. Total: 0:00:00. Remaining backlog: 10 days, 0:50:36.
```

Manually check:
```
# nominatim replication --check-for-updates
2021-12-16 22:34:28: Using project directory: /nominatim
2021-12-16 22:34:28: Database is up to date.
```

But I am alarmed by the growing backlog days. Is it ok?
If I go to the replication url, I see that every day we have new file. Why updater not use it?

**Software Environment (please complete the following information):**
- Nominatim version: 3.7
- Postgresql version: postgresql-nominatim:latest
- OS: Ubuntu 20.04.3 LTS (image: mediagis/nominatim:3.7)

**Comment by mtmail** [comment]
We have no experience with helm and only little with the mediagis/nominatim docker environment, those are separate projects. But hopefully it's something rather easy.

Did updates work before the 10 days or did no update work after the initial import?

What is the output of `SELECT * FROM import_status;` database query?

What is the exact version of Nominatim? Check `ChangeLog` file. The Docker image `media/nominatim:3.7` updated the version multiple times https://github.com/mediagis/nominatim-docker/commits/master/3.7/Dockerfile

Inside the container does `wget https://ftpmirror.your.org/pub/openstreetmap/replication/day/000/003/382.osc.gz` work (or `curl` or similar)? Can the file be extracted? Here we want to make sure there's no network issue, firewall block or SSL issue.

**Comment by Tri0L** [comment]
> Did updates work before the 10 days or did no update work after the initial import?

Nope. The update has not worked even once since the init import.

> What is the output of SELECT * FROM import_status; database query?
```
# SELECT * FROM import_status;
     lastimportdate     | sequence_id | indexed 
------------------------+-------------+---------
 2021-12-05 21:58:45+00 |     4831666 | t
(1 row)
```

> What is the exact version of Nominatim? Check ChangeLog file. The Docker image media/nominatim:3.7 updated the version multiple times https://github.com/mediagis/nominatim-docker/commits/master/3.7/Dockerfile

3.7.2

> Inside the container does wget https://ftpmirror.your.org/pub/openstreetmap/replication/day/000/003/382.osc.gz work (or curl or similar)?

```
# curl https://ftpmirror.your.org/pub/openstreetmap/replication/day/000/003/382.osc.gz -o 382.osc.gz 
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100 90.7M  100 90.7M    0     0  67.5M      0  0:00:01  0:00:01 --:--:-- 67.4M

# ls
382.osc.gz

# gunzip 382.osc.gz 

# ls -latr
total 1028132
drwxr-xr-x 1 root root       4096 Dec 15 18:34 ..
-rw-r--r-- 1 root root 1052791321 Dec 17 09:36 382.osc
drwxrwxrwt 1 root root       4096 Dec 17 09:39 .

# tail 382.osc 
    </relation>
    <relation id="13555604" version="1" timestamp="2021-12-15T23:58:16Z" uid="11601527" user="BlueButterfly" changeset="114982900">
      <member type="way" ref="159115515" role="from"/>
      <member type="way" ref="492853619" role="via"/>
      <member type="way" ref="492853617" role="to"/>
      <tag k="restriction" v="no_u_turn"/>
      <tag k="type" v="restriction"/>
    </relation>
  </create>
</osmChange>
```

Looks good.

**Comment by lonvia** [comment]
The sequence ID is bogus. I suspect you have changed the replication source at some point and forgotten to rerun `nominatim replication --init` afterwards. Run the init command and all should be fine afterwards.

**Comment by Tri0L** [comment]
For the initial download I used this url https://ftpmirror.your.org/pub/openstreetmap/pbf/planet-latest.osm.pbf
Maybe replication url wrong for this initial import?

**Comment by lonvia** [comment]
The replication source looks okay. If you "just followed the docker instruction" to set up updates, then there is a bug in their setup. Please open an issue with https://github.com/mediagis/nominatim-docker.

**Comment by Tri0L** [comment]
@lonvia `nominatim replication --init` will import full pbf again?

Can we somehow find out from the database where this sequence_id came from?

And last question, if I set sequence_id manually to right sequence_id(~10-12 days before), is it will continue updating?

**Comment by lonvia** [comment]
No, `nominatim replication --init` does not an import, it initialises updates. Please read the [documentation about updates](https://nominatim.org/release-docs/latest/admin/Update/).

The sequence ID is obviously from a minutely replication service, i.e the default replication service used when no other service is explicitly configured.

No, you should not set anything manually but simply run the command I told you about to fix it.

I'm closing this here. It's either user error or a docker issue.

**Comment by Tri0L** [comment]
@lonvia thank a lot.
You are absolutely right.

`nominatim replication --init` helped me.
