### ISSUE TITLE
Code 500 : Could not get places for search terms.

### ISSUE THREAD

**Issue by benjaminbusselet** [osm-search/Nominatim#2556]
Hello, when i  use your API search (https://nominatim.openstreetmap.org/search?), i have this message.

I think it's provisional. But I would like to be sure because I often use it in my API.

Regards,

**Comment by lonvia** [comment]
The API is provided on a best-effort base without any guarantees. If that is not sufficient for you, please have a look at the commercial alternatives listed in [the OSM wiki](https://wiki.openstreetmap.org/wiki/Nominatim#Alternatives.2FThird-party_providers). You should also read the [usage policy](https://operations.osmfoundation.org/policies/nominatim/) to decide if nominatim.openstreetmap.org is for you.

If you have queries that consistently return an 5xx error, please provide the full URL.

**Comment by benjaminbusselet** [comment]
I try with the example url that Nominatim gives in the tutorial 🤷

https://nominatim.openstreetmap.org/search?q=135+pilkington+avenue,+birmingham&format=xml&polygon_geojson=1&addressdetails=1

**Comment by lonvia** [comment]
There was a configuration error on one of our machines. Should be fixed now. Thank you for reporting.
