### ISSUE TITLE
Sudden performance degradation

### ISSUE THREAD

**Issue by Stefanic** [osm-search/Nominatim#2557]
**Describe the bug**
Sudden performance degradation in reverse geocoding on a full planet OSM instance, after a few days/weeks.
CPU usage in postgres suddenly spikes without any disk IO or IO wait and this dramatically decreases reverse geocode performance.

**To Reproduce**
Install full planet instance and keep server running (with continuous updates).
We followed https://nominatim.org/release-docs/latest/admin/Installation/
Update run using `nominatim replication` as systemd service

**Software Environment (please complete the following information):**
- Nominatim version: 3.7.2
- Postgresql version: 12.9
- Postgis version: 3.0
- OS: Ubuntu 20.04.3 LTS

**Hardware Configuration (please complete the following information):**
- RAM: 64GB
- number of CPUs: 1 CPU (AMD Ryzen 7 3700X), 8 cores 16 threads
- type and size of disks: 2x NVMe SSD 1TB in RAID0
- bare metal/AWS/other cloud service: bare metal

**Postgresql Configuration:**
None

**Additional context**
We created a postgres function based on the reverse.php logic. We call that function to do the reverse geocoding.
After clean install we reach around 400 rev. geocodes per second, when the 'bug' occurs we only get around 50 per second.

**Comment by lonvia** [comment]
If you use some custom hacks around Nominatim, then that's where you should start looking. You can use [auto-explain](https://www.postgresql.org/docs/current/auto-explain.html) to measure performance in your reverse functions.

Note that there was a minor reorganisation of indexes in 3.7 (See [this migration](https://github.com/osm-search/Nominatim/blob/master/nominatim/tools/migration.py#L160), which might affect you if you haven't adapted your scripts.

**Comment by Stefanic** [comment]
Sorry for the confusion, the custom function is simply a 1 on 1 clone of the reverse.php logic.
So there is no custom scripting/hacking except for porting the PHP code to a postgres function.
That function executes the exact same queries as the PHP does.

The auto-explain seems like a good starting point.

**Comment by Stefanic** [comment]
With auto-explain enabled I used both the reverse HTTP endpoint as the postgres function, both give the same explain:
`2021-12-21 16:11:17.558 CET [1282509] LOG:  duration: 445.962 ms  plan:
        Query Text: select place_id,parent_place_id,rank_address,country_code, ST_distance(ST_SetSRID(ST_Point(4.449287,51.771998),4326), geometry) as distance FROM  placex   WHERE ST_DWithin(ST_SetSRID(ST_Point(
4.449287,51.771998),4326), geometry, 0.006)   AND rank_address between 26 and 30 and (name is not null or housenumber is not null or rank_address between 26 and 27) and (rank_address between 26 and 27      or ST_
GeometryType(geometry) != 'ST_LineString') and class not in ('boundary') and indexed_status = 0 and linked_place_id is null and (ST_GeometryType(geometry) not in ('ST_Polygon','ST_MultiPolygon')  OR ST_DWithin(ST
_SetSRID(ST_Point(4.449287,51.771998),4326), centroid, 0.006)) ORDER BY distance ASC limit 1
        Limit  (cost=506567.76..506567.77 rows=1 width=29)
          ->  Sort  (cost=506567.76..506617.17 rows=19763 width=29)
                Sort Key: (st_distance('0101000020E610000062122EE411CC1140E94999D4D0E24940'::geometry, geometry))
                ->  Index Scan using idx_placex_geometry on placex  (cost=0.80..506468.95 rows=19763 width=29)
                      Index Cond: (geometry && st_expand('0101000020E610000062122EE411CC1140E94999D4D0E24940'::geometry, '0.006'::double precision))
                      Filter: ((linked_place_id IS NULL) AND (rank_address >= 26) AND (rank_address <= 30) AND (class <> 'boundary'::text) AND (indexed_status = 0) AND ((name IS NOT NULL) OR (housenumber IS NOT N
ULL) OR ((rank_address >= 26) AND (rank_address <= 27))) AND (((rank_address >= 26) AND (rank_address <= 27)) OR (st_geometrytype(geometry) <> 'ST_LineString'::text)) AND st_dwithin('0101000020E610000062122EE411C
C1140E94999D4D0E24940'::geometry, geometry, '0.006'::double precision) AND ((st_geometrytype(geometry) <> ALL ('{ST_Polygon,ST_MultiPolygon}'::text[])) OR st_dwithin('0101000020E610000062122EE411CC1140E94999D4D0E
24940'::geometry, centroid, '0.006'::double precision)))
        JIT:
          Functions: 8
          Options: Inlining true, Optimization true, Expressions true, Deforming true
2021-12-21 16:11:18.383 CET [1282507] LOG:  duration: 264.822 ms  plan:
        Query Text: select place_id,parent_place_id,rank_address,country_code, ST_distance(ST_SetSRID(ST_Point(5.126427,51.192803),4326), geometry) as distance FROM  placex   WHERE ST_DWithin(ST_SetSRID(ST_Point(
5.126427,51.192803),4326), geometry, 0.006)   AND rank_address between 26 and 30 and (name is not null or housenumber is not null or rank_address between 26 and 27) and (rank_address between 26 and 27      or ST_
GeometryType(geometry) != 'ST_LineString') and class not in ('boundary') and indexed_status = 0 and linked_place_id is null and (ST_GeometryType(geometry) not in ('ST_Polygon','ST_MultiPolygon')  OR ST_DWithin(ST
_SetSRID(ST_Point(5.126427,51.192803),4326), centroid, 0.006)) ORDER BY distance ASC limit 1
        Limit  (cost=506567.76..506567.77 rows=1 width=29)
          ->  Sort  (cost=506567.76..506617.17 rows=19763 width=29)
                Sort Key: (st_distance('0101000020E610000058535914768114400CC9C9C4AD984940'::geometry, geometry))
                ->  Index Scan using idx_placex_geometry on placex  (cost=0.80..506468.95 rows=19763 width=29)
                      Index Cond: (geometry && st_expand('0101000020E610000058535914768114400CC9C9C4AD984940'::geometry, '0.006'::double precision))
                      Filter: ((linked_place_id IS NULL) AND (rank_address >= 26) AND (rank_address <= 30) AND (class <> 'boundary'::text) AND (indexed_status = 0) AND ((name IS NOT NULL) OR (housenumber IS NOT NULL) OR ((rank_address >= 26) AND (rank_address <= 27))) AND (((rank_address >= 26) AND (rank_address <= 27)) OR (st_geometrytype(geometry) <> 'ST_LineString'::text)) AND st_dwithin('0101000020E610000058535914768114400CC9C9C4AD984940'::geometry, geometry, '0.006'::double precision) AND ((st_geometrytype(geometry) <> ALL ('{ST_Polygon,ST_MultiPolygon}'::text[])) OR st_dwithin('0101000020E610000058535914768114400CC9C9C4AD984940'::geometry, centroid, '0.006'::double precision)))
        JIT:
          Functions: 8
          Options: Inlining true, Optimization true, Expressions true, Deforming true`

As you can see this is about the `idx_placex_geometry` and not the one created in the 3.7 migration.
An online query explain tool (https://explain.dalibo.com/) says the cost of this index is high, but I don't know what can be done about that.

A fresh install is in the making and I'll try to explain the same query on that machine to see if there's a difference.

**Comment by lonvia** [comment]
Disable JIT and parallel workers and you are probably fine.

For the future: this is not the right place to discuss code that is not actually maintained in this repository. You are welcome to discuss custom adaptions in the discussion section but only if you provide the code under discussion in full.

**Comment by Stefanic** [comment]
I have the feeling the emphasis lies way too much on the custom part, what I tried to report is that the performance of the database changes (negatively) over time.
This performance drop cannot have anything to do with the custom query as it reads data just like the supplied website..

My guess is the update process might be 'breaking' the performance of the `idx_placex_geometry` index.
I'll look into this further.

**Comment by lonvia** [comment]
... or you could just follow the suggestion about JIT and parallel workers in Postgres.

**Comment by Stefanic** [comment]
> ... or you could just follow the suggestion about JIT and parallel workers in Postgres.

I have and that is what was causing the slowdown, thanks!
