### ISSUE TITLE
Unable to find address

### ISSUE THREAD

**Issue by otbutz** [osm-search/Nominatim#2558]
## What did you search for?

Haimelkofen 68 84082

## What result did you get?

Unstructured:

https://nominatim.openstreetmap.org/ui/search.html?q=Haimelkofen+68+84082 (center of the village)

Structured:

https://nominatim.openstreetmap.org/ui/search.html?street=Haimelkofen+68&postalcode=84082 (no result)

## What result did you expect?

https://www.openstreetmap.org/way/817469014

## Further details

Not sure if this is caused by the `addr:street` tag being used instead of `addr:place` which seems to be more appropriate here.

**Comment by lonvia** [comment]
> Not sure if this is caused by the addr:street tag being used instead of addr:place which seems to be more appropriate here.

Yes, it is. You need to fix the data here.

**Comment by otbutz** [comment]
Thanks
