### ISSUE TITLE
АПТЕКА not Аптека

### ISSUE THREAD

**Issue by 7171bel** [osm-search/Nominatim#2560]
## What did you search for?
АПТЕКА [highway=bus_stop], Речица, РЕЧИЦКИЙ РАЙОН, ГОМЕЛЬСКАЯ ОБЛАСТЬ
аптека [highway=bus_stop], Речица, РЕЧИЦКИЙ РАЙОН, ГОМЕЛЬСКАЯ ОБЛАСТЬ
Аптека [highway=bus_stop], Речица, РЕЧИЦКИЙ РАЙОН, ГОМЕЛЬСКАЯ ОБЛАСТЬ

## What result did you get?
https://nominatim.openstreetmap.org/ui/details.html?osmtype=N&osmid=2699797401&class=highway

## What result did you expect?
https://nominatim.openstreetmap.org/ui/details.html?osmtype=N&osmid=2666420490&class=highway
**When the result in the right place and just named wrongly:** 

**When the result missing completely:**

**Comment by lonvia** [comment]
This is in line with how the '[]' notation is defined at the moment. It gets you results with bus stops named 'Аптека' and results with bus stops near places named 'Аптека'. There is no facility explicit way to restrict the search to named places of a type.
