### ISSUE TITLE
"St. John's, Canada" does not match anything.

### ISSUE THREAD

**Issue by endlisnis** [osm-search/Nominatim#2561]
## What did you search for?
"St. John's, Canada"
https://nominatim.openstreetmap.org/ui/search.html?q=St.+John%27s%2C+Canada

## What result did you get?
"No search results found"

## What result did you expect?
I expected it to be the same as when I search for "St. John's, Newfoundland".  It seems that if I put ", Canada" at the end of my search, then it finds nothing.  

"St. John's, Newfoundland": works (https://nominatim.openstreetmap.org/ui/search.html?q=St.+John%27s%2C+Newfoundland)
"St. John's, Canada": fails
"St. John's, Newfoundland, Canada": fails

I'm pretty sure this used to work several weeks ago.  I caught this while using the Python API.  I was running a script that used to work, but now fails when trying to find "St. John's, Canada"

**Comment by lonvia** [comment]
Fixed for now by #2565.

**Comment by endlisnis** [comment]
That resolves the problem with "St. John's, Canada" but it creates a few other problems:

Now "Toronto Pearson Airport, Canada" no longer works but "Toronto Pearson Airport" works.

**Comment by lonvia** [comment]
Well, neither of the two works. The second just gives you a random hotel close to the airport. The full name "Toronto Pearson International Airport" will do the trick. That's unrelated to the tweak that made St John's work. It behaved exactly the same before the change.

**Comment by endlisnis** [comment]
OK, my mistake.  What used to work was "Toronto-Pearson, Canada".  That no longer gives any results.

**Comment by endlisnis** [comment]
But "Toronto-Pearson" still works.
