### ISSUE TITLE
Ways and relations are not updated when nodes are moved

### ISSUE THREAD

**Issue by Mashin6** [osm-search/Nominatim#2563]
This seems to be related to #1539. 

There is a report that Nominatim does not update ways when nodes are moved, but the way itself is not modified ([Slack link](https://osmus.slack.com/archives/C029HV955/p1628175951016300)). 
And from my experience this seems to be true also for relations. This causes that the geometry polygon returned by Nominatim is not identical to the current state in osm and thus causes problems when those geometries are used for spatial subsetting.

**Comment by jleedev** [comment]
Attaching screenshot:

![image-1](https://user-images.githubusercontent.com/23022/147972177-1b588faa-bfed-4390-8cef-63839922dad5.png)

There is a mismatch between the highlighted building (outdated) and the tiles (up to date).

**Comment by lonvia** [comment]
Yes, that's the case. It's intentional because those updates can be quite expensive but have rarely any significant influence on search.

**Comment by Mashin6** [comment]
Hmm maybe showing a warning message in the API output could help in those cases when someone wants to rely on Nominatim geometries.
