### ISSUE TITLE
Collation of German umlauts ue => ü for city searches

### ISSUE THREAD

**Issue by mtmail** [osm-search/Nominatim#2572]
Or rather ue => u which comes with all kinds of side-effects.

## What did you search for?

https://nominatim.openstreetmap.org/ui/search.html?q=muenster%2C+germany

## What result did you get?

Addresses containing 'muenster'

## What result did you expect?

Addresses containing 'münster', basically same as https://nominatim.openstreetmap.org/ui/search.html?q=m%C3%BCnster%2C+germany

## Further details

https://en.wikipedia.org/wiki/Diaeresis_(diacritic)#HTML

ue => ü, oe => ö, ae => ä used to work. It's natural to me to use the a-z version because my keyboard doesn't have umlaut keys but I don't know how common that is for the average user.

**Comment by otbutz** [comment]
Any plans for the next release which includes this fix?
