### ISSUE TITLE
Bnei Brak, Il, polygon not found

### ISSUE THREAD

**Issue by YissacharB** [osm-search/Nominatim#2576]
## What did you search for?

I was trying to pull the polygon for the city of Bnei Brak and no matter what I did, it seems like I couldn't find it in the database.
(https://nominatim.openstreetmap.org/search?city=Bnei%20Brak&countrycodes=IL&format=json&polygon_geojson=true&limit=5) also try at https://nominatim.openstreetmap.org/ui/search.html?q=Bnei+Brak%2C+IL

## What result did you get?
A point coordinate
`["32.0473899","32.1273899","34.7924376","34.8724376"],"lat":"32.0873899","lon":"34.8324376","display_name":"Bnei Brak, Tel Aviv Subdistrict, Tel Aviv District, 5158103, Israel","class":"place","type":"town","importance":0.3,"icon":"https://nominatim.openstreetmap.org/ui/mapicons//poi_place_town.p.20.png","geojson":{"type":"Point","coordinates":[34.8324376,32.0873899]}}]`

## What result did you expect?
To get a geojson of type Polygon or MultiPolygon of the entire city, 

**When the result missing completely:**

and it seems like there is a polygon for the city at OpenStreetMap - https://www.openstreetmap.org/relation/1382817

**Comment by lonvia** [comment]
The polygon is broken. See the long line sticking out in the north east.

**Comment by YissacharB** [comment]
Thank you @lonvia 
I fixed it the polygon there remove the extra there, Do you know how long it takes to see the result?
