### ISSUE TITLE
Scotland relation missing in downloaded scotland.pbf file

### ISSUE THREAD

**Issue by december1990** [osm-search/Nominatim#2590]
I installed the local version of Nominatim by following the installation instructions for ubuntu 20.04 and it's working fine, but I faced some subtale differences which are as following : 

search for ML6 6DE using public API retuns ** North Lanarkshire, Scotland, ML6 6DE, United Kingdom ** as label, 
but searching for the same postcode on my local returns ** North Lanarkshire, ML6 6DE, United Kingdom "" ,
the scotland word in local version is missing. the API seems to be accurate somehow, what could be the problem ? I used .pbf file for scotland, country_osm_grid.sql.gz, country_grid.sql.gz, wikimedia-importance.sql.gz and gb_postcodes.csv.gz as well. 

thanks in advance

**Comment by mtmail** [comment]
The Scotland file on http://download.geofabrik.de/europe/great-britain.html doesn't contain the full https://www.openstreetmap.org/relation/58446 relation. The relation references some OSM ways that are not the data file. Nominatim doesn't import incomplete relations.

I checked using `osmium getid scotland-latest.osm.pbf r58446 --add-referenced -o scotland-r58446.osm` (https://osmcode.org/osmium-tool/manual.html#getting-osm-objects-by-id) and then opened `scotland-r58446.osm` in JOSM (https://josm.openstreetmap.de/)

Geofabrik cuts data from larger files using *.poly files. You see that as red area on their preview map. It can happen that the *.poly file isn't large enough or OSM data changed and the country itself (here: Scotland) becomes incomplete.

cc Geofabrik's @woodpeck but I think you need to email them.

The easiest work-around is trying to import a larger country like great-britain. (I checked with osmium tool and JSOM the relation looks complete in that file).

![image](https://user-images.githubusercontent.com/3727288/150648314-d64f9655-4630-4a8f-8261-eb5b5979e348.png)
