### ISSUE TITLE
reverse geocoding settings

### ISSUE THREAD

**Issue by dieterdreist** [osm-search/Nominatim#2600]
## What did you search for?

https://www.openstreetmap.org/search?whereami=1&query=41.85824%2C12.46374#map=16/41.8582/12.4637

https://www.openstreetmap.org/search?whereami=1&query=41.85824%2C12.46374#map=18/41.85824/12.46375

## What result did you get?
in zoom 16 no housenumber 
## What result did you expect?
same address as it is defined by a polygon 
**When the result in the right place and just named wrongly:** 

**When the result missing completely:**

## Further details
maybe it’s the wrong place here to report and should be reported to the website?

**Comment by lonvia** [comment]
That's intentional. "Where am I" shows you what you see on the map. At zoom level 16 you don't see any housenumbers yet but only streets.

**Comment by dieterdreist** [comment]
I can see where it is coming from, but I think it is confusing (at least in some instances, in particular when a bigger area has a single address), because I did not type "where am I", I clicked on "show address" (context click menu on osm.org). Imagine an area of several football pitches with a single address, you would not expect you had to zoom to z18 in order to get a housenumber.

**Comment by lonvia** [comment]
That's rather an issue with naming then on the OSM website. Nothing that can be fixed here.
