### ISSUE TITLE
healthcare=* seem not indexed

### ISSUE THREAD

**Issue by pyrog** [osm-search/Nominatim#2609]
## What did you search for?

"Infirmières Lindecker et Montaut, La Réunion" 

## What result did you get?

"No results found"

## What result did you expect?

get nurses https://www.openstreetmap.org/node/5169779756

**Comment by lonvia** [comment]
That's a slightly tricky tag because 80% of objects that are tagged with `healthcare=*` have the meaning duplicated with `amenity=*`.

**Comment by lonvia** [comment]
Included 'healthcare' as a fallback in the style, i.e. it will be used only if there is no other interesting main tag. In practice that means that these objects will be found by name but searching by type will usually fail.

Also note that the database won't be reimported, so the objects will show up only gradually.
