### ISSUE TITLE
Invalid response for "donetsk people's republic"

### ISSUE THREAD

**Issue by Monstrofil** [osm-search/Nominatim#2610]
## What did you search for?

donetsk people's republic

## What result did you get?

Ukraine

## What result did you expect?

Nothing, nominatim should not display any results for that request.

## Further details

Please drop cache or whatever still makes nominatim to respond with "ukraine" for given request.

**Comment by SomeoneElseOSM** [comment]
Links from https://www.openstreetmap.org/changeset/117716012 may offer some context here.

**Comment by lonvia** [comment]
Closing as data issue.
