### ISSUE TITLE
Wrong country name - Ukraine

### ISSUE THREAD

**Issue by seus-ua** [osm-search/Nominatim#2611]
## What did you search for?
https://nominatim.openstreetmap.org/reverse?lat=50.4654&lon=30.4709

## What result did you get?
country Донецька область
country Dontsk People Republic
...etc

## What result did you expect?
country Україна
country Ukraine

**When the result in the right place and just named wrongly:** 
The name of the country has been changed throughout the database
All geolocation requests give the wrong name to Ukraine

**When the result missing completely:**

**Comment by otbutz** [comment]
@lonvia can we have a sticky post regarding disputed territories which explains that this is a data issue? I fear that a lot more of these issues might pop up...

**Comment by mishamyte** [comment]
Seems like this change is a act of vandalism.

From general perspective is there a rule to provide a data, according to international law?

**Comment by otbutz** [comment]
https://wiki.osmfoundation.org/w/images/d/d8/DisputedTerritoriesInformation.pdf

**Comment by VandJ** [comment]
@otbutz I will repeat once again for the inattentive (I hope). Disputed territories have nothing to do with this case! There is talk of information sabotage in OSM

**Comment by lonvia** [comment]
There is some difficult editing going on in OSM. The problem here is that Nominatim currently doesn't delete country names anymore once they are in the database.

I have now manually removed the entries in the databases of the servers on nominatim.openstreetmap.org and temporarily disabled changes to countries names to avoid further problems.

I'm working on appropriate functions to clean a database.

**Comment by lonvia** [comment]
The changes to country name handling are more involved and not really well backportable.

If you need to clean country names in your own database, you can temporarily remove the old names:

```
UPDATE country_name SET name = ''::hstore WHERE country_code = 'ua';
-- use this with legacy tokenizer or Nominatim <= 3.7
DELETE FROM word WHERE country_code = 'ua';
-- use this with the ICU tokenizer
DELETE FROM word WHERE type = 'C' and word = 'ua';
UPDATE placex SET indexed_status = 2 WHERE rank_search = 4 and country_code = 'ua';
```
(This works of course with any country, just change the country code.)

Then reindex your database:

```
nominatim index
```
If you want to restrict updating country names afterwards, please have a look at [this change](https://git.openstreetmap.org/nominatim.git/commitdiff/dbaf215feacb6ca82ec8c1bf3821ba5ebf218778) on how to do it.
