### ISSUE TITLE
Mon in search = no results

### ISSUE THREAD

**Issue by adamttaylor** [osm-search/Nominatim#2613]
## What did you search for?
"mon" in US

## What result did you get?
[ ]

## What result did you expect?
Montana at least plus additional  relevant results

## Further details

When searching for "mon" as the search string and with the countycode US
There are no results, however searches for  "mo" and "mont" DO return results.

no results
https://nominatim.openstreetmap.org/search?format=json&q=mon&countrycodes=us&limit=10

results
https://nominatim.openstreetmap.org/search?format=json&q=mont&countrycodes=us&limit=10
https://nominatim.openstreetmap.org/search?format=json&q=mont&countrycodes=us&limit=10

**Comment by mtmail** [comment]
Nominatim can only search for data that is in OpenStreetMap. https://www.openstreetmap.org/relation/162115 doesn't show any value with 'mon', it's neither a name or official abbreviation there.

**Comment by adamttaylor** [comment]
Oh, yes I think I was expecting the search string to be a "contains" in a string sort of thing
I'll check out Photon thanks!
