### ISSUE TITLE
Add `--version` function to nominatim CLI tool

### ISSUE THREAD

**Issue by lonvia** [osm-search/Nominatim#2615]
The nominatim CLI tool has no --version parameter, which is really something every tool should have. `nominatim/version.py` has the version of the software. A verbose version of the command (`--version -v`) should also print the version of the database if it can connect to a database.

TODO:

* [x] implement `--version` command
* [ ] output database version when run with `--version -v`)
* [x] output commit, when being built from a git clone

**Comment by anubhav06** [comment]
Hey. Can I work on this ?

> A verbose version of the command (--version -v) should also print the version of the database if it can connect to a database. 

Also, the version of database to be printed is the postgresql version which a user has installed ?

**Comment by lonvia** [comment]
The database version refers to the Nominatim version the current database was imported with or migrated to. It is saved in the `nominatim_properties` table. See [the migration code](https://github.com/osm-search/Nominatim/blob/2723553593f2c52ebf981d958942cc473f3db7e3/nominatim/tools/migration.py#L29) for an example where the version is read from the database.

**Comment by anubhav06** [comment]
Where does the version parameter need to be included ?
Should it be under the `optional arguments` section or under the `available commands` section ?

![0](https://user-images.githubusercontent.com/43821031/159067108-dc9f27a4-58b7-4abd-a9d2-f24bf19075c9.png)

**Comment by lonvia** [comment]
@anubhav06 Have you actually tried an implementation? Then the question will answer itself.

**Comment by lonvia** [comment]
Thinking some more about it, the database version is better implemented in some separate command probably under the admin subcommand. Closing here for now as completed.
