### ISSUE TITLE
Cannot retrieve county from address

### ISSUE THREAD

**Issue by mguignes** [osm-search/Nominatim#2617]
Hello,

I searched for (reverse geocoding) 44.81314, -0.63696 which is the coordinates in France, in the county of Gironde.
But I get an address without the county (undefined).
This actually works for any other county in France (and any country), but just not in the county of Gironde (south west of France, near Bordeaux).

Here is the example XHR : 
https://nominatim.openstreetmap.org/reverse?format=jsonv2&lat=44.81314&lon=-0.63696

Thanks !

![Capture](https://user-images.githubusercontent.com/33217296/155958589-a5b32cb7-8634-43a8-9b52-0a709bc4c811.PNG)

**Comment by mtmail** [comment]
Adding relevant links (this is not an answer)

https://nominatim.openstreetmap.org/ui/details.html?osmtype=W&osmid=27775419&class=highway list does not contain Gironde https://nominatim.openstreetmap.org/ui/details.html?osmtype=R&osmid=7405&class=boundary

**Comment by lonvia** [comment]
I guess the boundary was broken when the planet was imported last time. I've reindexed the entire county. Should be fixed now. Reopen if you still see missing counties somewhere.

**Comment by mguignes** [comment]
It's fixed ! 
Thank you so much !
