### ISSUE TITLE
Update Date

### ISSUE THREAD

**Issue by maxsnts** [osm-search/Nominatim#2622]
Hello

Updating a multiregion install using the script update_database.sh does not update the "lastimportdate" field of "import_status".

While a minor issue, that field us used in "Nominatim UI" as the "Last Update Date".

Thank you
Best regards

**Comment by lonvia** [comment]
I'll leave that to a user contribution to enhance.

**Comment by d-e-v-esh** [comment]
I would like to work on this issue 👍

**Comment by d-e-v-esh** [comment]
@lonvia Will adding this line in the `update_database.sh`  solve the problem?
```sh
psql -U postgres -d nominatim -c "UPDATE import_status SET lastimportdate = NOW()"

```

**Comment by maxsnts** [comment]
That is what i did on my instance, but i don't know if that will help on single region updates that are not done with this file.
(I also don't know if this affects single region updates as i only use multiple)

**Comment by lonvia** [comment]
No. The date needed is the date of the data imported. That is not necessarily NOW(). You can get it from the diff files.

**Comment by maxsnts** [comment]
I see. 
I did it only so that my users would not complaint about an out of date data. :)

Just out out of curiosity, do you know if the diff XML files guaranteed to be ordered with the most recent updates at the end?

**Comment by lonvia** [comment]
They are ordered by OSM type/ID. You'd need to scan the whole file and find the maximum date.

**Comment by sudeersharma** [comment]
To solve this issue, you will need to modify the update_database.sh script to update the lastimportdate field in the import_status table.

To do this, you can add a line of SQL code at the end of the script to update the lastimportdate field with the current date and time. Here's an example of how you could modify the script:
#!/bin/bash
set -e

# Update the database
cd /path/to/nominatim
./utils/update.php --import-osmosis-all

# Update the lastimportdate field
echo "UPDATE import_status SET lastimportdate=NOW();" | sudo -u postgres psql nominatim
This modified script will update the lastimportdate field in the import_status table to the current date and time each time the script is run. This should ensure that the "Last Update Date" displayed in the Nominatim UI is always up-to-date.

Note that you will need to replace /path/to/nominatim with the actual path to your Nominatim installation, and you may need to adjust the sudo -u postgres part of the SQL command depending on your PostgreSQL configuration.

**Comment by mtmail** [comment]
@sudeersharma lonvia already explained that `NOW()` is not ideal and the date should be taken from the data files.

`./utils/update.php` is a Nominatim 3.x command, it no longer exists in Nominatim version 4.

The path should be the project path, not the path of the Nominatim installation.

It's not clear to me if you tested your instructions and why you gave yourself a thumbs-up.

![image](https://user-images.githubusercontent.com/3727288/231884098-c65a2f17-90af-469d-8fa9-d27e3056f8e8.png)
