### ISSUE TITLE
https://nominatim.openstreetmap.org down?

### ISSUE THREAD

**Issue by rider87** [osm-search/Nominatim#2624]
Hi, 

is https://nominatim.openstreetmap.org/ down?

**Comment by lonvia** [comment]
No.

**Comment by rider87** [comment]
I cannot reach the website at all???

**Comment by rider87** [comment]
<img width="932" alt="image" src="https://user-images.githubusercontent.com/9787533/157311482-42b1f432-49bd-473e-8971-6651f7daf81d.png">

https://nominatim.openstreetmap.org/status.php
-> not working

<img width="836" alt="image" src="https://user-images.githubusercontent.com/9787533/157311552-e1b6a7d1-8f58-4dca-9466-bc40b2a453f9.png">

Why you close this issue?

**Comment by otbutz** [comment]
Your DNS is probably broken. The domain resolves perfectly fine for me and [Googles DNS servers](https://dns.google/query?name=nominatim.openstreetmap.org)
