### ISSUE TITLE
Error - nominatim refresh --website "Cannot import name 'SpecialPhrasesImporter'"

### ISSUE THREAD

**Issue by gcsa99** [osm-search/Nominatim#2634]
I've been trying to install nominatim for a while, but I've been having a lot of problems until I decided to start over from the beginning.
I found this tutorial and am following it.
https://timi.eu/docs/anatella/5_15_4_1_building-your_own_nominatim_server.html
But in section 2, when I try to run the nominatim refresh --website command, it returns the error: 

sislogica@srv-sislogica:/srv/nominatim/nominatim-projects nominatim refresh -- website
Traceback (most recent call last):
File "/usr/local/bin/nominatim", line 9, in <module>
 from nominatim import cli 
File "/usr/local/lib/nominatim/lib-python/nominatim/clt.py", line 14, in <module> 
from . import climd 
File "/usr/local/lib/nominatim/lib-python/nominatim/clicmd/init_.py", line 13, in module> 
from .special_phrases import ImportSpecialPhrases 
File "/usr/local/lib/nominatim/lib-python/nominatim/clicmd/special_phrases.py", line
in <module>
from nominatim.tools.special_phrases import SpecialPhrases Importer
ImportError: cannot import name 'SpecialPhrasesImporter' from 'nominatim. tools.special_p
rases' (/usr/local/lib/nominatim/lib-python/nominatim/tools/special_phrases/init_.py)

**Comment by lonvia** [comment]
Please use the [official installation instructions](https://nominatim.org/release-docs/latest/appendix/Install-on-Ubuntu-20/). If you run into issues with them, feel free to [start a discussion](https://github.com/osm-search/Nominatim/discussions) to get help. If you have issues with external tutorials, you should contact the writers of the tutorial.
