### ISSUE TITLE
DOCS: Improve SystemConfig for Ubuntu Installation

### ISSUE THREAD

**Issue by anubhav06** [osm-search/Nominatim#2638]
**Is your feature request related to a problem? Please describe.**

I was referring to the [System Configuration](https://nominatim.org/release-docs/develop/appendix/Install-on-Ubuntu-20/#system-configuration) docs for Ubuntu 20 installation.
The docs are correct, and mention to save the variable names like this:
```
export USERNAME=nominatim
export USERHOME=/srv/nominatim
```
However, these variable names remain valid only for the active session i.e. these are lost when you close your Ubuntu session (in WSL).

**Describe the solution you'd like**

Specifying these variable names in `.bashrc` will permanently save them, preventing them from being lost when the session is closed.
I think this thing should be mentioned in the docs.
Now, I agree that someone who is already familiar with Ubuntu (WSL) might do this on their own, but personally me being a beginner in Ubuntu (WSL) faced the same issue. This could potentially save 3-4 hrs for a beginner who is trying to get started with the project but ends up in loosing the variables on every new Ubuntu (WSL) session.

**Comment by lonvia** [comment]
I'm sorry but I have to reject that. A certain level of knowledge in terms of Linux system administration is required. It is enough work to maintain the documentation for Nominatim itself. There are other resources that can teach you the basics. Same for questions about Postgresql administration. Please refer to the documentation if things are unclear.
