### ISSUE TITLE
Inconsistent results between IPs…

### ISSUE THREAD

**Issue by zedrdave** [osm-search/Nominatim#2647]
The same exact query (with a set language) seems to return a different ordering of result (and therefore a different result with `limit=1`) when run from a different location. This seems tied to load balancing and whatever server gets to handle the call:

Location 1 (Europe):
```
curl -v -A nom_test "https://nominatim.openstreetmap.org/search?q=Zurich%2CFrance&format=json&limit=1&language=en" 
*   Trying 130.117.76.9:443...
* Connected to nominatim.openstreetmap.org (130.117.76.9) port 443 (#0)
[...]
[{"place_id":52519400,"licence":"Data © OpenStreetMap contributors, ODbL 1.0. https://osm.org/copyright","osm_type":"node","osm_id":4524285167,"boundingbox":["49.4489339","49.4490339","1.1284994","1.1285994"],"lat":"49.4489839","lon":"1.1285494","display_name":"Zurich, Rue de Zürich, Vallon Suisse, Quartier Grieu / Vallon Suisse / Saint-Hilaire, Rouen, Seine-Maritime, Normandie, France métropolitaine, 76000, France","class":"highway","type":"bus_stop","importance":0.22100000000000003,"icon":"https://nominatim.openstreetmap.org/ui/mapicons//transport_bus_stop2.p.20.png"}]%
```

From location 2 (US):
```
curl -v --ipv4 -A nom_test "https://nominatim.openstreetmap.org/search?q=Zurich%2CFrance&format=json&limit=1&language=en"
[...]
*   Trying 184.104.226.109...
[...]
[{"place_id":13541552,"licence":"Data © OpenStreetMap contributors, ODbL 1.0. https://osm.org/copyright","osm_type":"node","osm_id":1395173997,"boundingbox":["48.8717868","48.8718868","2.1833321","2.1834321"],"lat":"48.8718368","lon":"2.1833821","display_name":"Zurich, Boulevard Richelieu, Village du Plateau, Rueil-Malmaison, Arrondissement de Nanterre, Hauts-de-Seine, Île-de-France, France métropolitaine, 92500, France","class":"highway","type":"bus_stop","importance":0.22100000000000003,"icon":"https://nominatim.openstreetmap.org/ui/mapicons//transport_bus_stop2.p.20.png"}]
```

I cannot find any mention of server/IP specificity in the docs… Is there a way to guarantee consistency, regardless of the server running these queries?

**Comment by lonvia** [comment]
We have mutliple servers which are assigned by GeoIP. So you usually should get the same server when calling from a the same IP but there is no way to choose a server. It shouldn't usually be necessary. The servers have the same data (minus smaller but usually insignificant differences for technical reasons) . What you see is rather that there are two results with exactly equal relevance available for your request. With `limit=1` you get a random result. Can also happen when sending the same query twice to the same server.

**Comment by zedrdave** [comment]
I did not realise that the sorting (and therefore the value returned by `limit=1`) was random on purpose.
That would explain the inconsistency between calls (I seemed to be getting the same order based on each originating IP, but that might have been a fluke).

Is there any reason not to use a deterministic sort ?

**Comment by lonvia** [comment]
There is no particular reason to have a sort that goes beyond "the result is more relevant". Maybe you can explain a bit more what you are trying to achieve and why the different results are an issue.

**Comment by zedrdave** [comment]
@lonvia Hello and sorry for the delay in replying.

Our particular use-case is simply a unit test in our platform. The fact that the API behaves non-deterministically makes it a bit complicated to test that our script behaves as expected. We solved it for ourselves by finding a query that only returns a single match.

**Comment by lonvia** [comment]
Okay, not a use case we would actively want to support. Unit tests and volatile web APIs are never a good match. Results change over time and the service may be down.
