### ISSUE TITLE
Lookup API doesn't return any result for certain osm_ids

### ISSUE THREAD

**Issue by ACOJO5920** [osm-search/Nominatim#2648]
There is not much of a pattern that I can deduce. 

Even an osm_id used on the documentation returns an empty result:
https://nominatim.openstreetmap.org/lookup?osm_ids=W104393803&format=json

The osm_id used on the documentation can be found here:
https://nominatim.org/release-docs/latest/api/Lookup/ 

Here are a few more ids that return an empty result:
W153590272
N6592395214
W1008785948

**Comment by mtmail** [comment]
https://www.openstreetmap.org/way/153590272 https://www.openstreetmap.org/node/6592395214 https://www.openstreetmap.org/way/1008785948 are buildings without house numbers or names. Nominatim imports only features (node,way,relation) with names. When you do reverse search for example on the coordinates then Nominatim will try to find the nearest features with a name.

https://www.openstreetmap.org/way/104393803 got deleted 6 years ago.
