### ISSUE TITLE
Search failing to locate New York municipalities.

### ISSUE THREAD

**Issue by kennykb** [osm-search/Nominatim#2662]
## What did you search for?

"Lansing, New York"  https://nominatim.openstreetmap.org/ui/search.html?q=lansing%2C+new+york

## What result did you get?

Search returns a hamlet named 'Lansing' in Town of Scriba, Oswego County, New York, and a building named 'Lansing' in City of Geneva, Ontario County, New York.  Borders of the town and village of Lansing do not show up until "Search for More Results is selected, and even then the place node for the town and village does not appear.

## What result did you expect?

Expected the primary search results to include the place node for Town and Village of Lansing, Delaware County, New York. https://www.openstreetmap.org/node/158346576 - which is a considerably more prominent place than the "Lansing" in Oswego County.

## Further details

I've been working for the last few months on a project to check and correct the administrative civil divisions in New York State against the state's GIS, which is considerably more reliable and precise than the several inconsistent TIGER imports that brought these boundaries into OSM originally.  I've been regularizing tagging, making sure that divisions have labels, and adding admin centers where I can find them.  If there's anything wrong with the tagging or relation structure here, it's also wrong systemically with a couple of thousand other places. I've kept good records, so I almost certainly can correct any gaffe with a mechanical edit, but at the moment I can't quite see what's gone wrong.

**Comment by 1ec5** [comment]
If I click “Search for more results” – which excludes the aforementioned features from the results:

* South Lansing, Town of Lansing, Tompkins County
* Town of Lansing, Tompkins County
* Village of Lansing, Town of Lansing, Tompkins County
* Lansing Station, Town of Lansing, Tompkins County
* North Lansing, Town of Lansing, Tompkins County
* East Lansing, Town of Lansing, Tompkins County
* …

but not the Town of Lansing itself.

I also see no sign of the Lansing in Delaware County, even when searching for “Lansing, Delaware County, New York”. [The debug page for this Lansing](https://nominatim.openstreetmap.org/ui/details.html?osmtype=N&osmid=158346576) shows that it’s associated with both the Town of Lansing and the Village of Lansing. Perhaps its “diamond inheritance” in the administrative hierarchy is confusing Nominatim?

**Comment by lonvia** [comment]
Another case of different names on place node and administrative boundary which was fixed recently in #2637. I've forced an update. Nodes and administrative boundary get merged when they describe the same entity, so there won't be an explicit result for the node.

I have no idea why you expect the node should be in [Delaware County](https://www.openstreetmap.org/relation/1838017), when it clearly is located in [Tompkins County](https://www.openstreetmap.org/relation/1838025).

A node functioning as label member for multiple administrative boundaries is bad mapping. A place node should describe exactly one place. If it is linked to two different administrative boundaries, it obviously describes two. It should either be the place node for 'Village of Lansing' or 'Town of Lansing'. That said, Nominatim seems to handle the case half-way reasonable.

**Comment by 1ec5** [comment]
> A node functioning as label member for multiple administrative boundaries is bad mapping. A place node should describe exactly one place. If it is linked to two different administrative boundaries, it obviously describes two.

For what it’s worth, I recently discovered that the place node for [Texarkana](https://www.openstreetmap.org/node/151470692) was doing double duty, since in reality it’s a single place split between two distinct administrative areas of the same name. The settlement predates the state line running through town, so its unofficial identity as a single town is locally important (and pretty well known nationally). OSM is consistent with most other maps in labeling just a single “Texarkana” on the state line, but Nominatim’s behavior of returning [two results](https://nominatim.openstreetmap.org/ui/search.html?polygon=1&q=Texarkana) is not uncommon among geocoders either. There might be other cases like this among [border towns](https://en.wikipedia.org/wiki/Border_town).

**Comment by lonvia** [comment]
> For what it’s worth, I recently discovered that the place node for [Texarkana](https://www.openstreetmap.org/node/151470692) was doing double duty, since in reality it’s a single place split between two distinct administrative areas of the same name.

Fair enough. That's a difficult case. I would argue that in such a case, there are in fact three different entities here: the settlement of Texarkana (represented by the place node), the administrative entity of Texarkana, Arkansas and the administrative entity of Texarkana, Texas. Best if Nominatim returns three distinct results when searching for Texarkana. I see that the three objects already have different wikidata items, which is a good indicator of the situation. I'd be in favour of removing the label membership, too.

But we are getting far away from the original report. Feel free to open a new issue about split towns. Closing here, as the original issue is solved.
