### ISSUE TITLE
"Address Rank"100 for a village. Missing address municipality admin_level 8.

### ISSUE THREAD

**Issue by AllroadsNL** [osm-search/Nominatim#2664]
## What did you search for?
Vlieland admin_level 10

OSM forum:
https://forum.openstreetmap.org/viewtopic.php?id=75341
This problem **first** mentioned to the community.

https://nominatim.openstreetmap.org/ui/details.html?osmtype=R&osmid=296985&class=boundary
## What result did you get?
![image](https://user-images.githubusercontent.com/8817345/162759850-1d60d080-1ce4-432d-81b5-4ec7afd984e8.png)
## What result did you expect?
For the boundary of the village Address Rank 16
At the arrow a line with the municipality Vlieland with Adress Rank 14

This line municipality with Address Rank 14
![image](https://user-images.githubusercontent.com/8817345/162760395-78b93c8b-115c-4730-a860-88cc266d768f.png)
https://nominatim.openstreetmap.org/ui/details.html?osmtype=R&osmid=47609&class=boundary

There more places in the Netherlands with the same problem.
Enkuizen
https://nominatim.openstreetmap.org/ui/details.html?osmtype=R&osmid=296470&class=boundary
Urk
https://nominatim.openstreetmap.org/ui/details.html?osmtype=R&osmid=295078&class=boundary
more
Schiermonnikoog, Zeewolde, Lelystad, Almere en Arnhem.

All:
<html><body>

Address Rank | 0 (other)
-- | --

</body>
</html>

Places: with the same name for the village/city and the municipality admin_level=8

How to change to the right Address Rank for admin_level=10?

**Comment by lonvia** [comment]
That's Nominatim's duplicate detection doing its work as expected. If there are two relations with exactly the same area it is assumed that it is a single administrative entity that spans multiple admin_level. All but the one with the highest level are dropped because otherwise the address would have duplicates that don't exist in real life.

Please explain the tagging you are using and the situation on the ground.

**Comment by AllroadsNL** [comment]
The situation on the ground.
Boundary are almost never visible on the ground. (signed)

The boundary lines are official Government data.
admin_level=10 De "woonplaats", dutch , Residence, the village/town/city, where people live, the residence have a name.
admin_level=8 "Gemeente", dutch, Municipality, The municipalities are governed by both a board of mayor and aldermen and a municipal council. This boundary could  include 1 or more "woonplaats", residence. These residence have a administrative boundary, decided by the governed municipality.

In the Netherlands we have the situation that we can have a municipality and a residence with the same name and boundary line. We do not draw this line twice.

When we write a letter and post it.
Name people/company
addr:street addr:housenumber
addr:postcode "Woonplaats" residence (addr:city)
from abroad addr:country is enough.

We never use municipality or province on a addressed envelop for a letter.

Vlieland:
A building address", mostly on a node in the Netherlands.
https://www.openstreetmap.org/node/2756835816
![image](https://user-images.githubusercontent.com/8817345/162831705-00d0ae60-629d-4482-8b63-f091db05f863.png)
A tag, "place" on a node.
https://www.openstreetmap.org/node/237681211

![image](https://user-images.githubusercontent.com/8817345/162832138-0f7cb930-fb7d-4303-a3eb-2e3c5c84f3a1.png)

"Woonplaats", residence, Vlieland, admin_level 10
https://www.openstreetmap.org/relation/296985
Not everywhere in the Netherlands the "place" node is used as a relation role "label" in a "Woonplaats", residence, adm_level=8.
In this case, Vlieland, it is not used.
![image](https://user-images.githubusercontent.com/8817345/162835656-a393c22a-6d07-4ca1-80d2-dec887b9ebe4.png)

"Gemeente", Municipality, Vlieland, admin_level=8.
https://www.openstreetmap.org/relation/47609
The "place" node is used as a admin_centre.
![image](https://user-images.githubusercontent.com/8817345/162836239-3a589437-d424-4bd5-a3e5-ecf6c32cba86.png)

I hope this explains enough.

When people do a search, they expect both "Woonplaats" residence and "Gemeente", municipality in the list, and that some are not left out for the Netherlands.

**Comment by lonvia** [comment]
> When people do a search, they expect a complete list structure, if this is both "Woonplaats" residence and "Gemeente", municipality in the list, and that some are not left out for the Netherlands.

I'm confused, which list structure this might be. The details page you are quoting is an internal debug tool.

**Comment by AllroadsNL** [comment]
In the [link](https://forum.openstreetmap.org/viewtopic.php?id=75341) OSM forum above.
Someone is searching for ......... 

Dutch:

> Hoi Frank
> Ik ben weer aan het klooien met OSM. Nu kom ik er achter dat de plaats Vlieland (296985), niet onder de gemeente Vlieland (47609) valt. Zie https://nominatim.openstreetmap.org/details?osmtype=R&osmid=296985&format=json&addressdetails=1
> Dat geld volgens mij ook voor Schiermonnikoog, Zeewolde, Lelystad, Almere, Urk en Arnhem.
> 
> Bij Tilburg wordt wel netjes de gemeente vermeld:
> https://nominatim.openstreetmap.org/details?osmtype=R&osmid=1411514&format=json&addressdetails=1
> 
> Weet jij hoe ik die gegevens kan toevoegen?

Translated: 
> Hi Frank
> I'm messing around with OSM again. Now I find out that the place Vlieland (296985), does not fall under the municipality of Vlieland (47609). See https://nominatim.openstreetmap.org/details?osmtype=R&osmid=296985&format=json&addressdetails=1
> I think that also applies to Schiermonnikoog, Zeewolde, Lelystad, Almere, Urk and Arnhem.
>
> At Tilburg, the municipality is neatly stated:
> https://nominatim.openstreetmap.org/details?osmtype=R&osmid=1411514&format=json&addressdetails=1
>
> Do you know how I can add that data?

He expect to find, the structure, that in the Netherlands, he can find  all places inside a municipality. Even with the same boundary.

He think data is missing, how to add data.

**Comment by lonvia** [comment]
Unfortunately, this still doesn't answer my question at all. "I was messing with OSM" is not a description of what they are trying to do that is helpful in an issue report. I don't see much point in further back and forth as you are not the actual user with the problem and obviously have not enough information to get to the bottom of it.

The original user is welcome to open a new discussion in the [discussion section](https://github.com/osm-search/Nominatim/discussions/) and describe what he was doing and why it was a problem.
