### ISSUE TITLE
"Wrong" town

### ISSUE THREAD

**Issue by Xevib** [osm-search/Nominatim#2674]
## What did you search for?

"Carrer ponent, Banyoles" [ link ](https://nominatim.openstreetmap.org/ui/search.html?q=Carrer+ponent+%2C+banyoles)

## What result did you get?
I have two results, one is [this](https://nominatim.openstreetmap.org/ui/details.html?osmtype=W&osmid=153470581&class=highway)
In this case the result sais that the town is "Banyoles" but most of the street is in "Porqueres"

## What result did you expect?

From my point of view I expect that the town must be "Porqueres" because most of the street is in "Porqueres"

## Further details

The street is inside two towns and I supose that is causing the problem

**Comment by mtmail** [comment]
Yes, the street crossing administrative boundaries is like the issue. Thanks for the example, https://github.com/osm-search/Nominatim/issues/2658 covers this more broadly.

**Comment by lonvia** [comment]
We currently use the distance to the centroid of the administrative area as sorting criteria. That may not be the best choice. A better idea would be the distance of the administrative area to the centroid of the feature. That guarantees that the area that contains the centroid will be chosen as the 'display address'. It's still a heuristics and there will be corner cases that come out wrong but it's the best we can do. Computing which area contains the larger part of a road is too expensive.
