### ISSUE TITLE
Germany Zip Code(s) missing or wrong

### ISSUE THREAD

**Issue by JPustkuchen** [osm-search/Nominatim#2677]
## What did you search for?
In Drupal 9 with [Geocoder](https://www.drupal.org/project/geocoder) module and Root URL https://nominatim.openstreetmap.org I searched for the German Zip Code: "49078" on https://www.cube-dental.com/de/labore/mitglieder

The search returns two results without city name:
![grafik](https://user-images.githubusercontent.com/637807/164702736-578e5ab4-ae8c-4c44-8a8c-f1001b89063e.png)

## What result did you get?
Clicking a result seems to return a place close to "Düsseldorf", while there are Places in Osnabrück.

## What result did you expect?
Place in Osnabrück. When entering "Osnabrück" as name instead of 49078 as zip code, the search returns the following:
![grafik](https://user-images.githubusercontent.com/637807/164703280-d0c32ab2-4e8a-41bd-8c97-bcc2b686002f.png)

Clicking "49074 Osnabrück" returns a place which is indeed in Osnabrück, as it would be expected for 49078 

## Further details
https://nominatim.openstreetmap.org/ui/search.html?q=49078 returns the expected and correct results. So it might also be a Drupal Module issue? Confused by the autocomplete results.

**Comment by lonvia** [comment]
This is a display problem with Drupal. Please report the issue there.
