### ISSUE TITLE
Batch Queries fail when using PHP 8.X

### ISSUE THREAD

**Issue by troyberte** [osm-search/Nominatim#2679]
## What did you search for?

Within a standalone instance using Nominatim 4.0.1 with NOMINATIM_SEARCH_BATCH_MODE=yes running on a server with PHP 8.0, searching "/search.php?batch=<json>&format=json" with any json to do a batch query.

## What result did you get?

The result: {"error":{"code":0,"message":"Unsupported operand types: array | int"}}

In Nominatim 4.0.1, the details of the log indicate it's an error in ./lib-php/lib.php at line 128.

## What result did you expect?

Results from the query without any errors.

## Further details

The error looks like it's the result of ./lib-php/template/search-batch-json.php, line 75 that calls the javascript_renderData function with an iOptions parameter of "array('geojson')".  This results in the error indicated above when running with PHP 8.X.  The error goes away if we we revert back to PHP 7.X.

**Comment by lonvia** [comment]
As the docs say "This feature is currently undocumented and potentially broken." There is a good chance it will go away completely when the API gets rewritten in Python. This is just to say that there is very little chance this gets fixed.

**Comment by lonvia** [comment]
I'm closing this as a won't fix. The new Python frontend drops batch processing in favour of using Nominatim as a library.
