### ISSUE TITLE
State/region missing in Denmark

### ISSUE THREAD

**Issue by WonderingDane** [osm-search/Nominatim#2701]
## What did you search for?
I searched for "Region Hovedstaden".
https://nominatim.openstreetmap.org/ui/search.html?q=%22Region+Hovedstaden%22

## What result did you get?
It shows a café and two other government buildings.

## What result did you expect?
I expected the boundaries of the state/region "Region Hovedstaden". All other regions in Denmark can be found. Fx: "Region Syddanmark" and "Region Nordjylland".

**When the result missing completely:**
https://www.openstreetmap.org/relation/1320608#map=8/55.600/13.420

**Comment by mtmail** [comment]
Only adding link for further analysis:

The server doesn't seem to have the relation in its database https://nominatim.openstreetmap.org/ui/details.html?osmtype=R&osmid=1320608

The polygon isn't broken http://ra.osmsurround.org/analyzeRelation?relationId=1320608&noCache=true&_noCache=on

**Comment by lonvia** [comment]
Was probably broken at the time of import.
