### ISSUE TITLE
Wrong calculated postal code

### ISSUE THREAD

**Issue by livioavalle** [osm-search/Nominatim#2703]
## What did you search for?
I searched for Quargnento, this is the [link ](https://nominatim.openstreetmap.org/ui/search.html?q=Quargnento)to the site.

## What result did you get?
The village result with a calculated postcode wrong, 15029, and not with the correct code. The wrong code (15029) is of the nearby village.
## What result did you expect?
The correct postal code for Quargnento is 15044, and there are some node in the village with the right postcode, like this [one ](https://www.openstreetmap.org/way/313894169)

Also, the search link of nominatim, give me an Administrative result that doesn't have a post code calculated and i don't know why

**Comment by mtmail** [comment]
Checking
https://nominatim.openstreetmap.org/ui/search.html?q=15044%2C+italy
https://nominatim.openstreetmap.org/ui/search.html?q=15029%2C+italy
will show where Nominatim calculated the center points.

https://nominatim.org/release-docs/3.5.2/develop/Postcodes/ is an older documentation (current Nominatim version is 4.0) how to check for postcodes in the area using Overpass API.

![image](https://user-images.githubusercontent.com/3727288/167492681-718ae9f5-e6b2-4b1f-8d55-36a2b111b5b4.png)

There's only 4 places in Quargento mapped with a postcode. It's probably easiest to add a `postal_code=15044` to the village place node or relation. https://wiki.openstreetmap.org/wiki/Key:postal_code Example of a nearby village San Savatore Monferrato https://www.openstreetmap.org/node/63622366

**Comment by lonvia** [comment]
Postcodes for town are mostly interpolated by Nominatim from OSM data. As such they may or may not be precise. It just comes with the data. Not fixable in the general case.
