### ISSUE TITLE
 some addresses when i use the api output undefined

### ISSUE THREAD

**Issue by wolfevening** [osm-search/Nominatim#2712]
When I send the location to the Popayán and Monteria api in the geocoding json in the "admin" section, the "level6" section does not appear. someone could organize it would be very helpful, thanks

**Comment by mtmail** [comment]
What is the "Popayán and Monteria api"?

Please use the "Report issues with search results" template on https://github.com/osm-search/Nominatim/issues/new/choose and list the full API request (URL) and ideally response. "some addresses" is not detailed enough, list at least one specific address, which part of the API response is unexpected and what a better API response could be.

**Comment by wolfevening** [comment]
I'm sorry, I was trying to say that when I consume the location Popayán(Colombia) and Monteria(Colombia) in Nominatim, in the json that gives me a geocoding response in the "admin" section, the "level6" section does not appear. thanks

**Comment by wolfevening** [comment]
this is the url i use https://nominatim.openstreetmap.org/reverse?format=geocodejson&lat=latitude&lon=longitude
this returns the following json with the location information
![respuesta](https://user-images.githubusercontent.com/91489427/169059329-b0311f60-1572-49e5-9fbe-56f1889e20e5.png)

**Comment by wolfevening** [comment]
look here, I leave you an example with a location with the level6 section.
![respuesta](https://user-images.githubusercontent.com/91489427/169060933-3fdfeb07-772b-42d4-ae6b-6c93af37a49b.png)

**Comment by mtmail** [comment]
What in your opinion should the values for the levels be for this place? https://nominatim.openstreetmap.org/ui/details.html?osmtype=W&osmid=635308793

**Comment by wolfevening** [comment]
In my opinion, for these two locations Popayán (Colombia) and Montería (Colombia), the level6 section would be the same name as the city, in the case of Popayán it would be Popayán and for Montería it would be Montería.
Thank you so much

**Comment by mtmail** [comment]
The `format=geocodejson` of Nominatim is quite strict and will return the levels in the OSM data. The OSM data would need to change which is outside the scope of the Nominatim software. A work-around is too look at higher levels, e.g. level7 and use that value is level6 is not set. There is no guarantee that any of the levels are set, not even level2 (country).

Looking at https://wiki.openstreetmap.org/wiki/Tag:boundary%253Dadministrative the mappers in Columbia use different levels in cities/urban vs rural. Many countries have such exceptions (Sweden for example uses level7 a lot and leaves level8 empty, while in Austria it's the opposite).

Nominatim tries to normalize that a bit with so called address levels (https://nominatim.org/release-docs/latest/customize/Ranking/#rank-configuration) to map the numeric numbers to labels, e.g. 'city' or 'county'. The output goes to `format=jsonv2`. Maybe that format is better suited.

You can reach the Columbian OpenStreetMap community via various channels listed at https://openstreetmap.community/?map=5.96354,-73.74665&zoom=5.58
