### ISSUE TITLE
Icon URL contains duplicate path separator

### ISSUE THREAD

**Issue by otbutz** [osm-search/Nominatim#2717]
e.g querying https://nominatim.osm.org/search.php?q=regensburg&format=jsonv2 yields:

`icon: https://nominatim.openstreetmap.org/ui/mapicons//poi_boundary_administrative.p.20.png`

Expected:

https://nominatim.openstreetmap.org/ui/mapicons/poi_boundary_administrative.p.20.png

**Comment by lonvia** [comment]
Should be right now on all the OSMF servers.
