### ISSUE TITLE
Allow creating postgresql database ahead of time

### ISSUE THREAD

**Issue by Xiretza** [osm-search/Nominatim#2719]
**Is your feature request related to a problem? Please describe.**
The current installation instructions require creating a postgresql superuser just for nominatim: https://nominatim.org/release-docs/latest/appendix/Install-on-Ubuntu-20/#setting-up-postgresql

While those permissions can probably be removed once the database is created, that step is easily forgotten, causing a possible security issue for all other users of the postgresql cluster in case the nominatim user is compromised.

Trying to create the database before running `nominatim import` immediately errors with `permission denied to create database`, even if the database already exists.

**Describe the solution you'd like**
The administrator should be able to set up nominatim's database structure without giving superuser permissions to nominatim.

**Comment by lonvia** [comment]
There probably will be a non-supervisor import mode at some point but it's not exactly high on the priority list at the moment.

**Comment by lonvia** [comment]
Here is how this could work:

* add a new import mode `nominatim import --prepare-database`, which executes all commands that need privileged mode (create database, create extensions, anything else?)
* add a new import node `nominatim import --no-superuser` which executes the import as usual except for the priviledged commands. This mode should still fail when it detects that Nominatim is already installed in the database (e.g. look if table `place` exists).

The new modes should be tested by changing the [CI import runs](https://github.com/osm-search/Nominatim/blob/5751686fdce33f6b69a93dd1641ceacb2239791f/.github/workflows/ci-tests.yml#L189) to run first `--prepare-database` and then `--no-superuser` import.

**Comment by contiyo** [comment]
Hello. 

Is this being worked by someone ? 
It seems like a really good first issue and I would like to contribute.

**Comment by lonvia** [comment]
Please go ahead.

**Comment by lonvia** [comment]
This is now implemented on master since #3204.
