### ISSUE TITLE
Searching for an address will sometimes set "class=place", causing the link to the details page to be invalid

### ISSUE THREAD

**Issue by jerryplin** [osm-search/Nominatim#2733]
[5327 darnell street, houston, tx](https://nominatim.openstreetmap.org/ui/search.html?q=5327+darnell+street%2C+houston%2C+tx)

## What result did you get?

https://nominatim.openstreetmap.org/ui/details.html?osmtype=W&osmid=15439385&class=place

Note that clicking on that link takes you to [this page](https://nominatim.openstreetmap.org/ui/details.html?osmtype=W&osmid=15439385&class=place) which states "No place with that OSM ID found."

## What result did you expect?

https://nominatim.openstreetmap.org/ui/details.html?osmtype=W&osmid=15439385

That link has the expected information.

## Further details

Line 318 of PlaceLookup.php forces the "class" to be "place" even though the corresponding OSM ID (15439385) is considered a "highway," causing nominatim-ui to append "&class=place" which in turn causes the OSM ID to not be found.

**Comment by lonvia** [comment]
The result is a TIGER housenumber, i.e. external data, while the OSM link goes to the underlying street. We don't have a details page for TIGER data yet. This is already covered in #1671, so closing here.
