### ISSUE TITLE
Can't find way ID in Nominatim while present in Openstreepmaps

### ISSUE THREAD

**Issue by StanPipple** [osm-search/Nominatim#2734]
## What did you search for?

Way 331344737 - https://nominatim.openstreetmap.org/ui/details.html?osmtype=W&osmid=331344737

## What result did you get?

No place with that OSM ID found.

## What result did you expect?

The result I get when searching via https://www.openstreetmap.org/way/331344737

**Comment by lonvia** [comment]
Unnamed link roads are not imported in Nominatim by default. You can change this in your own installation by [adopting the import style](https://nominatim.org/release-docs/latest/customize/Import-Styles/). For this specific case you would need to remove 'with_name' in this line: https://github.com/osm-search/Nominatim/blob/8a0e3e2f3d9bce87725a6e08dcc90a072a17995c/settings/import-extratags.style#L92
