### ISSUE TITLE
Search results missing - Partizanska bolnica Franja, Slovenia

### ISSUE THREAD

**Issue by tzugen** [osm-search/Nominatim#2741]
## What did you search for?

The Partisan hospital Franja, while being the Map was centered on Slovenia
https://nominatim.openstreetmap.org/ui/search.html?q=Franja

## What result did you get?

Two conpletely unrelated results, in Kroatia and US.

## What result did you expect?

This object:
https://www.openstreetmap.org/search?query=Partizanska%20bolnica%20Franja#map=19/46.15403/14.02821&layers=Y

## Further details

If I search for the specific name ("Partizanska bolnica Franja") it shows. But people might not know the exact name and just look for Franja....

**Comment by mtmail** [comment]
You can add for example `loc_name` or `short_name` tag to the hospital. https://wiki.openstreetmap.org/wiki/Key:name

For the Berlin https://www.openstreetmap.org/way/583306346 hospital there's also an official (longer) `name` with shorter names in other languages.

**Comment by lonvia** [comment]
Closing this as 'won't fix'. Automatically figuring out that 'Franja' is the short version will be very, very difficult without additional information. Use `short_name` to help search out.
