### ISSUE TITLE
No search result with dutch zip codes without space

### ISSUE THREAD

**Issue by Peetzer** [osm-search/Nominatim#2762]
When using a suggestion/ auto completion based on the input without space in the zip code, no results are shown,

Examples zip code with '2741JV' and '2741 JV'

    A12, Waddinxveen, 2741JV => not found (https://nominatim.openstreetmap.org/search.php?q=A12%2C+Waddinxveen%2C+2741JV&format=jsonv2)

    A12, Waddinxveen, 2741 JV => found (https://nominatim.openstreetmap.org/search.php?q=A12%2C+Waddinxveen%2C+2741+JV&format=jsonv2)

**Comment by lonvia** [comment]
Already fixed in #2757. Will be available after the next full database import.

NB: Please read the section of our [usage policy](https://operations.osmfoundation.org/policies/nominatim/) about auto-complete being unacceptable use of the API.
