### ISSUE TITLE
New GB postcode July 2022 files

### ISSUE THREAD

**Issue by mtmail** [osm-search/Nominatim#2765]
A new CODEPO file got released on https://osdatahub.os.uk/downloads/open/CodePointOpen

I converted it using https://github.com/osm-search/gb-postcode-data/ and placed it on
https://downloads.opencagedata.com/public/gb_postcodes.202207.csv.gz (13MB)
https://downloads.opencagedata.com/public/gb_and_ni_postcodes.202207.csv.gz (13MB)

Please review and upload to https://www.nominatim.org/downloads/

```
$ ./compare.py gb_postcodes.202205.csv gb_postcodes.csv
Read 1725632 postcodes from old file gb_postcodes.202205.csv
Read 1727727 postcodes from new file gb_postcodes.csv
Added: 4683 (0.271%)
Deleted: 2588 (0.150%)
Position moved: 60590 (3.507%)
Position moved more than 100 meters: 10478 (0.606%)
Position moved more than 1000 meters: 625 (0.036%)
Position moved more than 10000 meters: 7 (0.000%)
Average distance difference of all updates: 90.92 meters
```

**Comment by lonvia** [comment]
Done.
