### ISSUE TITLE
Field address->county in osm database for france-latest is messed up for 2 search (city=Paris & city=Lion)

### ISSUE THREAD

**Issue by nmateo** [osm-search/Nominatim#2766]
## What did you search for?
search 1: https://nominatim.openstreetmap.org/search?city=Lion&format=json&limit=1&accept-language=fr&addressdetails=1&extratags=1

search 2: https://nominatim.openstreetmap.org/search?city=Paris&format=json&limit=1&accept-language=fr&addressdetails=1&extratags=1

## What result did you get?
search 1(Lion): address->county but equals "Metropole de Lion"

search 2(Paris): address->county isn't a field

## What result did you expect?
Address->county equals department for most of research (france-latest.osm.pbf) but not for those city.
**When the result in the right place and just named wrongly:** 
search 1(Lion): address->county need to equals "Rhone"
search 2(Paris): address->county need to be present and equals "Paris"

I except thethe field address->county to be always present and with de department name, in case of Paris, it's Paris and for Lion it's Rhone.

Like for Marseille: https://nominatim.openstreetmap.org/search?city=Marseille&format=json&limit=1&accept-language=fr&addressdetails=1&extratags=1

address->county equals  Bouches-du-Rhône

or for Rennes https://nominatim.openstreetmap.org/search?city=Rennes&format=json&limit=1&accept-language=fr&addressdetails=1&extratags=1

address->county equals Ille-et-Vilaine

**When the result missing completely:**

**Comment by lonvia** [comment]
Lyon is not part of the [Rhone department](https://www.openstreetmap.org/relation/4850451) in OSM. According to [Wikipedia](https://en.wikipedia.org/wiki/Lyon) Lyon hasn't been part of the department since 2015, so this is correct.

Paris is special because it is a city and department at the same time. Nominatim only outputs one of the two in such a case (usually the city).

**Comment by lonvia** [comment]
The status of Lyon is something you have to discuss with the [French community](https://forum.openstreetmap.fr/). Nominatim will show what is mapped.

Regarding Paris, if you are explicitly looking for departments in the administrative sense, use [geocodejson output with address details](https://nominatim.openstreetmap.org/search?city=Paris&format=geocodejson&limit=1&accept-language=fr&addressdetails=1&extratags=1) and use the `admin->level6` field.

Closing here as data issue.
