### ISSUE TITLE
Coordinate search didn't support degree symbol

### ISSUE THREAD

**Issue by c933103** [osm-search/Nominatim#2776]
I tried to search the string "22.92°N 118.95°E" on OSM website, but Nominatim returned no result.

Instead, when I search  "22.92N 118.95E" on OSM website, Nominatim returned the result of  22.92°N 118.95°E.

Users should be able to type in coordinate in the format of  "22.92°N 118.95°E" and expect to be able to get result of 22.92°N 118.95°E from Nominatim.

**Comment by lonvia** [comment]
This has nothing to do with the Nominatim software. Parsing of the various formats for coordinates is done on the [OSM website](https://github.com/openstreetmap/openstreetmap-website) before the request is sent, somewhere around [here](https://github.com/openstreetmap/openstreetmap-website/blob/8aa6d483603137c9c6993dd9452f8be5828bfa28/app/controllers/geocoder_controller.rb#L289).
