### ISSUE TITLE
Wrong location returned for City+State search

### ISSUE THREAD

**Issue by yelskiy** [osm-search/Nominatim#2790]
## What did you search for?

Searched for `Norwood, MA` via https://nominatim.openstreetmap.org/search?city=Norwood&state=MA&format=json&limit=1

## What result did you get?

```json
[
	{
		"place_id": 297984071,
		"licence": "Data © OpenStreetMap contributors, ODbL 1.0. https://osm.org/copyright",
		"osm_type": "relation",
		"osm_id": 126010,
		"boundingbox": [
			"40.70314",
			"40.711032",
			"-89.706821",
			"-89.694728"
		],
		"lat": "40.7055931",
		"lon": "-89.6987129",
		"display_name": "Norwood, Peoria County, Illinois, United States",
		"class": "boundary",
		"type": "administrative",
		"importance": 0.535679868885482,
		"icon": "https://nominatim.openstreetmap.org/ui/mapicons/poi_boundary_administrative.p.20.png"
	}
]
```

Note the `Peoria County, Illinois` bit

## What result did you expect?

```json
[
	{
		"place_id": 298434856,
		"licence": "Data © OpenStreetMap contributors, ODbL 1.0. https://osm.org/copyright",
		"osm_type": "relation",
		"osm_id": 2389803,
		"boundingbox": [
			"42.1499166",
			"42.2138843",
			"-71.2383432",
			"-71.1548528"
		],
		"lat": "42.194543",
		"lon": "-71.1994976",
		"display_name": "Norwood, Norfolk County, Massachusetts, 02062, United States",
		"class": "boundary",
		"type": "administrative",
		"importance": 0.6006627616878826,
		"icon": "https://nominatim.openstreetmap.org/ui/mapicons/poi_boundary_administrative.p.20.png"
	}
]
```
## Further details

I have discovered that when I change `limit` to 3 or greater, i.e. `https://nominatim.openstreetmap.org/search?city=Norwood&state=MA&format=json&limit=3`, correct location is returned as the first item in the list; however, when `limit` is 1 or 2, "MA" location is not in the list of results.

**Comment by mtmail** [comment]
Can you add &country=US (or "United States") as a workaround?

**Comment by lonvia** [comment]
Same issue as #882. The workaround is to not use the limit parameter. Have multiple results returned and ignore everything but the first.

Closing as duplicate here.

**Comment by lonvia** [comment]
#2793 fixed this particular example.
