### ISSUE TITLE
Add Support for Open Location Code (aka "Plus Code")

### ISSUE THREAD

**Issue by martinum4** [osm-search/Nominatim#2802]
**Is your feature request related to a problem? Please describe.**

Entering an OLC (e.g. `9F4MG972+R2`) into a Nomatim-Search filed yields no results.

**Describe the solution you'd like**

Solve a valid OLC to coordinates.

**Describe alternatives you've considered**

Using another service.

**Additional context**

There are a lot of code examples at https://github.com/google/open-location-code so this should be reasonably easy to implement.

**Comment by mtmail** [comment]
Previously discussed in https://github.com/osm-search/Nominatim/issues/914 (Nominatim), https://github.com/openstreetmap/openstreetmap-website/pull/1818 (OSM website), OSM mailing lists and https://wiki.openstreetmap.org/wiki/Proposal_Open_Location_Code Consensus from the project maintainers is not to implement it.

**Comment by lonvia** [comment]
Closing as duplicate.
