### ISSUE TITLE
Too few results shown in some circumstances

### ISSUE THREAD

**Issue by karlvr** [osm-search/Nominatim#2813]
## What did you search for?

All of these searches were done in an NZ only dataset using only https://download.geofabrik.de/australia-oceania/new-zealand-latest.osm.pbf

You can reproduce some of these results on https://nominatim.openstreetmap.org by limiting the country code to "nz".

The context of my testing is in developing an autocomplete search and _generally expecting_ the number of results to reduce as the search becomes more specific. Seeing an early result with one result incorrectly suggests that there's no more to find. I know the search isn't specifically _intended_ to be an autocomplete, but it mostly works! :-)

1. ["28 Arnold"](https://nominatim.openstreetmap.org/ui/search.html?q=28+Arnold&countrycodes=nz)

This results in a single result "28, Maori Gully Road, Grey District, West Coast, New Zealand" where as ["28 Arnold St"](https://nominatim.openstreetmap.org/ui/search.html?q=28+Arnold+St&countrycodes=nz) has multiple results.

The reason the first result appears (I believe) is because it is in a hamlet named "Arnold Valley", which doesn't appear for the road it is on, so that house gets an entry in `search_name` which is found by the search algorithm and the search is stopped with one result.

I would like to see the search continue to include the other search groups so we see more results (up to the limit on the number of results) so the result shows that there are more results available.

2. ["48 High"](https://nominatim.openstreetmap.org/ui/search.html?q=48+High&countrycodes=nz)

This also results in a single result "48, High Street, Island Bay, Wellington, Wellington City, Wellington, 6023, New Zealand" whereas there are, as you'd expect, many High Streets in NZ, with many 48s.

Here the searches with High as the street name and 48 as the house number are pruned because there are too many results for them. I think the counts for this are different with the world data set, but the behaviour looks similar.

I would like to see the search return either no results, indicating that there are too many results to present and more input is required, or to show up to the maximum number of results, again indicating that more input is required.

I have successfully increased `NOMINATIM_SEARCH_NAME_ONLY_THRESHOLD` to resolve this, but I expect there will always be a limit / threshold that we'll meet and get this odd situation where we return one result where there are actually potentially hundreds.

## Attempted solutions

1. I've made the following patches to `lib-php/Geocode.php` to keep the search going after the first search group that produces results, and adds some sort order weight to those found earlier, in case they are valid name matches and deserve to be first:

```diff
@@ -773,7 +773,13 @@
                 }
 
+                foreach ($aResults as $iIdx => $aResult) {
+                    if (!isset($aResult->group)) {
+                        $aResult->group = $iGroupLoop;
+                    }
+                }
+                $aNextResults = $aResults;
-                if (!empty($aResults) || $iGroupLoop > 4 || $iQueryLoop > 30) {
+                if ($iGroupLoop > 4 || $iQueryLoop > 30) {
                     break;
                 }
             }
         } else {
@@ -860,6 +865,8 @@
                 }
                 // - number of exact matches from the query
                 $aResult['foundorder'] -= $aResults[$aResult['place_id']]->iExactMatches;
+                // - sort by the group in which we found the result
+                $aResult['foundorder'] += $aResults[$aResult['place_id']]->group;
                 // - importance of the class/type
                 $iClassImportance = ClassTypes\getImportance($aResult);
                 if (isset($iClassImportance)) {
```

I think the core of the problem is that houses get a name containing the street number when they go into `search_name`, whereas that isn't their "name" and makes them seem as significant as a named venue?

2. I've tried adding a heuristic to the group pruning so that if we've pruned away a search group that looks really promising (has a house number) and haven't left any other promising ones (have house numbers) then we reject the whole search.

Again in `lib-php/Geocode.php`:

```diff
@@ -429,10 +429,16 @@
             }
         }
 
+        $acceptedHouseNumberSearches = 0;
+        $rejectedHouseNumberSearches = 0;
+
         // Revisit searches, drop bad searches and give penalty to unlikely combinations.
         $aGroupedSearches = array();
         foreach ($aSearches as $oSearch) {
             if (!$oSearch->isValidSearch()) {
+            if ($oSearch->hasHousenumber()) {
+                $rejectedHouseNumberSearches ++;
+            }
                 continue;
             }
 
@@ -441,9 +447,18 @@
                 $aGroupedSearches[$iRank] = array();
             }
             $aGroupedSearches[$iRank][] = $oSearch;
+
+            if ($oSearch->hasHousenumber()) {
+                $acceptedHouseNumberSearches ++;
+            }
         }
         ksort($aGroupedSearches);
 
+        // Heuristic to reject all search groups if there are possible house number specific searches that are too broad
+        if ($rejectedHouseNumberSearches > 0 && $acceptedHouseNumberSearches == 0) {
+            return array();
+        }
+
         return $aGroupedSearches;
     }
 
```

As above, maybe it would be better to just grab some results from the big set to show that there are lots of results, if returning no results is more odd.

**Comment by lonvia** [comment]
The problem with the house-number-as-name search entries is that we currently can't properly express what the dependent name is which must appear together with the housenumber in the search query. There are some other problems with the house-number-as-name solution to the [extra-search-terms-for-an-address issue](https://github.com/osm-search/Nominatim/pull/1965). Maybe we need a completely different approach here.

**Comment by lonvia** [comment]
So I've looked a bit into alternative ways to handle addresses with extra search terms but they come all with their own problems. The house-number-as-name solution isn't so bad after all. It just needs a post filter that removes these 'false results' where the housenumber is present but the dependent street/place is missing. Such a filter requires some reorganisation of the search front end, which in turn is a bit of a bigger undertaking.

NB: the root problem here seems to be that you are trying something that Nominatim explicitly doesn't have an API for: suggestions. The search API is not made for that use case and will produce garbage regularly when presented with partial input.

**Comment by karlvr** [comment]
@lonvia thank you very much for your consideration here. I've found this quite fascinating to delve into.

I recognise that this isn't the intention of the API, and that some things might require restructuring. As above, I've modified the API to be more suitable for our use. Got to love open source. Thank you very much for your ongoing efforts on it.

Do you think the way the search algorithm returns the results from the first group that presents results could be improved? It doesn't seem to be a valid assumption that something in an earlier group is significantly better than in later groups (given the way house numbers sometimes appear in names).

**Comment by lonvia** [comment]
> Do you think the way the search algorithm returns the results from the first group that presents results could be improved?

I want to get away from the concept of search groups altogether and switch to a more conventional ranking based on floating-point scores. This allows to have a scoring which mixes the likelihood of the SearchDescription matching the search query and the results matching the SearchDescription. Then it will be possible that a very well matching result from a lower-scored SearchDescription overtake results from a better-scored SearchDescription.

**Comment by karlvr** [comment]
@lonvia thank you, yes, I think that's what I've simulated by continuing to look at results from all groups. I will watch with interest!

**Comment by lonvia** [comment]
The new ranking is now implemented in the Python frontend.

The results for '28 Arnold' look quite correct to me. The situation with '48 high' is a bit different. Nominatim refuses to look that up as a partial search as a measure of self protection because there are too many results expected. Going through 110.000 instances of places containing 'high' to find the few streets with a house number '48' takes too long. This is an inherent restriction on how the search index works.
