### ISSUE TITLE
Replication Error

### ISSUE THREAD

**Issue by xlofhappy** [osm-search/Nominatim#2815]
My docker-nominatim run with no errors. But, when I do [nominatim replication] from planet.openstreemmap.org,
it runs well until the error appear：

ERROR: DB copy thread failed: Ending COPY mode for 'planet_osm_rels' failed: ERROR:  value "218678" is out of range for type smallint
CONTEXT:  COPY planet_osm_rels, line 1101, column way_off: "218678"

I just run the command : nominatim replication

- Nominatim version: 4.0.1
- Postgresql version: 12.9 (Ubuntu 12.9-0ubuntu0.20.04.1)
- Postgis version: 3.0
- OS: Ubuntu 12.9-0ubuntu0.20.04.1 

**Hardware Configuration (please complete the following information):**
- RAM: 
- number of CPUs: 12
- type and size of disks: 1TB
- bare metal/AWS/other cloud service: 

REPLICATION_URL=https://planet.openstreetmap.org/replication/minute/
Data date: 2022-01-14T06:35:27+00:00

**Comment by lonvia** [comment]
Known issue, see https://github.com/openstreetmap/osm2pgsql/issues/1607 for recommended workaround. Already fixed in Nominatim 4.1.

You should not be updating a half-year old planet. Reimport instead.
