### ISSUE TITLE
addr:street tag ignored (assumed based on nearby way)

### ISSUE THREAD

**Issue by blackboxlogic** [osm-search/Nominatim#2826]
## What did you search for?
[37 Market Square, South Paris, Maine](
https://www.openstreetmap.org/search?query=37%20Market%20Square%2C%20South%20Paris%2C%20Maine#map=19/44.22333/-70.51443)

## What result did you get?
No results

## What result did you expect?
https://www.openstreetmap.org/node/7176251197

## Further details
[Searching for this element by name](https://www.openstreetmap.org/search?query=Paris%20Public%20Library#map=19/44.22333/-70.51443) finds it, but reveals that Nominatim thinks this element is on "Church Street"
![image](https://user-images.githubusercontent.com/31355456/191989983-0f009479-a01b-4e5b-9476-8508456c7b73.png)
Even though the `addr:street=Market Square`
![image](https://user-images.githubusercontent.com/31355456/191990168-6838eb49-9e50-43b9-9e6e-d4c6582be9c7.png)
There is a "Church street" near by, and maybe nominatim pre-processing assumes `addr:street` is wrong because there's no element with `highway=*` nearby with that name. I realize I could probably fix this by adding an element with `name=Market Square`, and I probably will, but I shouldn't need to do that for Nominatim to find the correct element which is correctly tagged by searching for the correct address.

The address is correct as tagged, confirmed on [the website](http://www.paris.lib.me.us/).

**Comment by mtmail** [comment]
Your assessment is correct. Nominatim looks for "Market Square" but can't find a nearby road by that name. Somebody needs to add the road.

There are way too many mapping errors, typos and inconsistencies in `addr:street` values to have Nominatim create places for each in its database. https://nominatim.org/qa/#map=2.18/0.00/0.00&layer=addr_street_wrong_name

**Comment by lonvia** [comment]
This looks like a case where you want to use addr:place instead of addr:street. Looks like there is no real street or place with that name anymore because there are now state road crossroads in the place of the former square.

**Comment by blackboxlogic** [comment]
@mtmail I'm glad it's by design instead of a mistake. Did you consider any other options, maybe index the location as _both_ the tagged and inferred addresses?

@lonvia Thanks for suggesting `addr:place`. I just found where [addr:street~".*square"](http://overpass-turbo.eu/s/1m8K) and I'll probably review/fix all those.

**Comment by blackboxlogic** [comment]
This did end up being a missing road, which I've fixed. You're detecting when addr:street doesn't match a nearby road and assuming the addr:street is wrong. For the record, in Maine USA, the address data is more reliable than the road data.

**Comment by lonvia** [comment]
Closing as data issue.
