### ISSUE TITLE
Hauptstraße 77, 76534 Baden-Baden not found

### ISSUE THREAD

**Issue by GitOsmar** [osm-search/Nominatim#2828]
## What did you search for?
Hauptstraße 77, 76534 Baden-Baden

https://www.openstreetmap.org/note/3371087#map=18/48.74493/8.25862

## What result did you get?
Hauptstraße 77, Hauptstraße, Warmbronn, Leonberg, Landkreis Böblingen, Baden-Württemberg, 71229, Deutschland Bus stop
https://nominatim.openstreetmap.org/ui/search.html?q=Hauptstra%C3%9Fe+77%2C+76534+Baden-Baden

## What result did you expect?
Hauptstraße 77, 76534 Baden-Baden
https://www.openstreetmap.org/note/3371087#map=18/48.74493/8.25862

**When the result in the right place and just named wrongly:** 

Baden-Baden! The city "Baden-Baden" is specified correctly, but an incorrect location is displayed.

**When the result missing completely:**

https://www.openstreetmap.org/note/3371087#map=18/48.74493/8.25862

## Further details

Street and place "Hauptstraße 77, Baden-Baden" are correctly specified as a search. Therefore, no other city should be displayed as a result. "Hauptstrasse 77, Baden-Baden" is also correctly defined in OSM.

**Comment by lonvia** [comment]
Tricky problem. 'Baden-Baden' essentially matches against 'Baden-Würtemberg' because we loose along the way the information that the token 'Baden' appears twice.

**Comment by lonvia** [comment]
Added full-text matches for address parts, which also handles double names like this correctly now.
