### ISSUE TITLE
Should place=state, admin_level=4 be in country_names table?

### ISSUE THREAD

**Issue by mtmail** [osm-search/Nominatim#2830]
Specifically I note this search https://nominatim.openstreetmap.org/ui/search.html?q=San+Juan%2C+Puerto+Rico creates a dozen search candiates that include country_code=pr (https://nominatim.openstreetmap.org/search.php?q=San+Juan%2C+Puerto+Rico&format=jsonv2&debug=1)

All places in Puerto Rico in the the `placex` table have country_code=us set. I assume Nominatim checks the `country_names` table where Puerto Rico has an entry, likely because the state has an ISO country code set https://www.openstreetmap.org/relation/4422604

I say 'state' because that's how it's mapped in OSM data. Of course in this case it's a [unincorporated territory](https://en.wikipedia.org/wiki/Unincorporated_territories_of_the_United_States). Similar situation with Macao and Hongkong.

Should the `country_names` table perhaps not contain entries which aren't mapped as admin_level=2 ?

**Comment by lonvia** [comment]
I have [a change on a private branch](https://github.com/osm-search/Nominatim/commit/1be741aa5f53b6138a12fd15d9315f78debda619) that removes all countries that are not admin_level=2. Never quite got around to merging it because I'm not entirely sure what the consequences would be.
