### ISSUE TITLE
Road name only available on zoom=18

### ISSUE THREAD

**Issue by marcioaguiar** [osm-search/Nominatim#2845]
## What did you search for?

-5.4433716,-47.4716666

https://nominatim.openstreetmap.org/reverse?lat=-5.4433716&lon=-47.4716666&zoom=17&extratags=1

## What result did you get?

```
/address/road: undefined
```

## What result did you expect?

```
/address/road: BR-010
```

When i make the same query using zoom=18, I get the correct road. Is that expected behavior? Zoom 18 is not suitable for me.

On old data, when the unclassified way (https://www.openstreetmap.org/way/772044541#map=18/-5.44414/-47.46918) did not exist, the road name is BR-010 in zoom=17 also.

**Comment by lonvia** [comment]
The result is exactly as excepted. Your point is exactly on way 772044541, so that is what you get in return.

I do admit that it is a bit confusing that the main object is missing in the address listing. Maybe we should just return an empty string for the unnamed road.

**Comment by marcioaguiar** [comment]
Thanks for the reply, @lonvia! Can you elaborate on why the road is informed as expected on zoom=18?

**Comment by lonvia** [comment]
z=18 returns [River Refrigerantes](River Refrigerantes) as being the nearest POI/house. This happens to have the trunk highway as part of its address.

**Comment by marcioaguiar** [comment]
Got it, @lonvia ! Thank you for your attention!
