### ISSUE TITLE
Chester, VA as input incorrectly returning Chester, WV coordinates

### ISSUE THREAD

**Issue by niklas-ax** [osm-search/Nominatim#2847]
Attempting to generate coordinate for Chester, VA, instead, got coordinates for Chester, WV (input=Chester, VA).

Also Searched for Chester, _VA_ in openstreetmap. First results returned was Chester, _WV_. Even when zipcode was added, Chester WV was the first result/coordinate returned when Chester, VA was used as input.

Here is link to search: https://nominatim.openstreetmap.org/ui/search.html?q=chester%2C+virginia

## What result did you get?
Returned results/coordinates for Chester, WV

## What result did you expect?
Expected results/coordinates for Chester, VA

**Comment by lonvia** [comment]
Mixed up with the short_name `w.va.`.

**Comment by IbrahimAshqar** [comment]
Can you elaborate please @lonvia

**Comment by lonvia** [comment]
Fixed with the new weighing mechanism.
