### ISSUE TITLE
Parent ID not assigned to a few interpolation data rows

### ISSUE THREAD

**Issue by rocainunwired** [osm-search/Nominatim#2850]
Hello

Just noticed that a few rows in the `location_property_osmline` table has `parent_place_id` set to `0`, resulting in addresses that contain just the house_number & postal_code (Ex: `"display_name":"245, 30114"`)

Did a count check across the planet in the table `location_property_osmline`, and there are 480 such rows worldwide.

Here's 2 such reverse query links:
Ex 1: https://nominatim.openstreetmap.org/ui/reverse.html?lat=34.21359&lon=-84.51620&zoom=18
Ex 2: https://nominatim.openstreetmap.org/ui/reverse.html?lat=51.16829&lon=0.17600&zoom=18

**Comment by lonvia** [comment]
These most likely come from bad interpolation lines. They are a candidate for [Nominatim QA](https://nominatim.org/qa/). Best to exclude them from reverse searches. They cannot be found in forward search.
