### ISSUE TITLE
2 Ulmenweg, Hildesheim not found

### ISSUE THREAD

**Issue by mtmail** [osm-search/Nominatim#2855]
## What did you search for?

2, ulmenweg, hildesheim, 31139, deutschland
https://nominatim.openstreetmap.org/ui/search.html?q=2%2C+ulmenweg%2C+hildesheim%2C+31139%2C+deutschland

## What result did you get?

none

## What result did you expect?

https://nominatim.openstreetmap.org/ui/details.html?osmtype=N&osmid=5833924449&class=place

## Further details

All other house numbers in that street work. Removing 'Deutschland' or the postcode works.

Street is completely in the postcode relation (https://www.openstreetmap.org/relation/1162960)

On my private planet installation house numbers 2,4,6,8,12 don't work, the others work fine. I did various local reindexing of course.

The query plan https://nominatim.openstreetmap.org/search.php?q=2%2C+ulmenweg%2C+hildesheim%2C+31139%2C+deutschland&format=jsonv2&debug=1
has many steps with postcodes '31-139' and '311 39'. I couldn't find where those variations are created (checked `PostcodeTokenAnalysis` and `MutationVariantGenerator`). I'd expect that if Germany or country=de is recognized it could only check for '31139' because that's the format specificied in `country_settings.yaml`.

```
$ nominatim --version
Nominatim version 4.1.0-0 (d8be8a72)
```

**Comment by lonvia** [comment]
Ah, now the housenumber variants come back to bite. Two solutions come to mind: a) grouping of postcodes that normalize to the same term or b) penalize non-exact matches. Penalizing by country format is an option, too, but only works for half the query plan.

**Comment by spixi** [comment]
German house numbers can be very complicated. There is also a house with the address "Straße der Einheit 24 A-3" in 06632 Gleina. Interestingly, there is also "Straße der Einheit 24 A", but not "24 A-1" or "24 A-2".

**Comment by lonvia** [comment]
Housenumber variants are now combined in a single query.
