### ISSUE TITLE
Update statement - Nominatim 4.1.0 on read only database

### ISSUE THREAD

**Issue by t-tomek** [osm-search/Nominatim#2857]
**Describe the bug**

I have multipled Postgres databases (1 main - rw; 2 replicas ro). With version 4.1.0 I'm unable to query read only replicas anymore becouse of: https://github.com/osm-search/Nominatim/blob/master/lib-php/DB.php#L50-L51

You should change those setting via 'SET' queries as it's done on https://github.com/osm-search/Nominatim/blob/master/lib-php/DB.php#L47-L48

**Software Environment (please complete the following information):**
- Nominatim version: 4.1.0
- Postgresql version: 14.5
- Postgis version: 3.3.1
- OS: Linux

**Hardware Configuration (please complete the following information):**
- RAM: 120 GB
- number of CPUs: 24
- type and size of disks:
- bare metal/AWS/other cloud service: cloud

**Comment by t-tomek** [comment]
I've just made PR https://github.com/osm-search/Nominatim/pull/2856

**Comment by lonvia** [comment]
Fixed in #2856. The new Python frontend (#2937) will do this properly right from the beginning.
