### ISSUE TITLE
"svm" object has no attribute "cached" in file "database_import.py" at line 110

### ISSUE THREAD

**Issue by eHorn96** [osm-search/Nominatim#2872]
**Describe the bug**
When executing command "nominatim import --osm-file <data file> 2>&1 | tee setup.log" I get following error:

At line 110, file "database_import.py":

"svm" object has no attribute "cached"

This is the culprit code-snippet:

`if not options['flatnode_file'] and options['osm2pgsql_cache'] == 0:`
 `    mem = psutil.virtual_memory()`
 `fsize = 0`
 `   if isinstance(osm_files, list):`
            `for fname in osm_files:`
                `fsize += os.stat(str(fname)).st_size`
        `else:`
            `fsize = os.stat(str(osm_files)).st_size`
        `options['osm2pgsql_cache'] = int(min((mem.available + mem.cached) * 0.75,`
                                             `fsize * 2) / 1024 / 1024) + 1`

It seemed that psutil didn't recognise the OS?

**To Reproduce**
macOS Venture, Nominatim 4.1, all prerequisites installe as per the documentation, executed the above import command with Germany-latest.osm.pbf from Geofabrik.

**Software Environment (please complete the following information):**
- Nominatim version: 4.1
- Postgresql version: 14.5 (Homebrew)
- Postgis version: 3.3
- OS: macOS Ventura 13.0

**Hardware Configuration (please complete the following information):**
- RAM: 8GB
- number of CPUs: 8
- type and size of disks: 1TB
- bare metal/AWS/other cloud service: External SSD

**Postgresql Configuration:**
shared_buffers= 3GB
work_mem = 100 MB
maintenance_work_mem = 4GB
auto vacuum_work_mem = 2GB
max_worker_processes = 8
max_parallel_workers = 8
checkpoint_timeout = 10min
checkpoint_completion_target = 0.9
fsync = off

**Comment by mtmail** [comment]
I can't see `svm` anywhere, I assume you refer to `mem`. `psutil` doesn't fill that value on MacOS https://psutil.readthedocs.io/en/latest/#memory Not sure what a good replacement would be here.

We haven't tested Nominatim on MacOS. Maybe just patching the line locally will make the import work but we don't know if there's other MacOS specifics later in the import or replication. It's best to test with a small country (Luxembourg, Lichternstein, Monaco) first.

**Comment by eHorn96** [comment]
Hi,

sorry, mem is the svm object returned by psutil.virtual_memory(). Weird that documentation doesn't include macOS, since in VSCode it specifically mentions macOS for the cached attribute. I removed mem.cached and it is importing now. You are right with the small country, maybe next time :D

**Comment by mtmail** [comment]
Importing Germany with 8GB RAM is tight and can easily take 12-24h, while consuming 100% CPU majority of the time. Monaco runs in 20 minutes and then you're at least sure all the tools run without error.

**Comment by eHorn96** [comment]
Yea you're right. Took more than 24 hours. Fortunately though, it worked and it's successfully serving requests now. The discrepancy between the documentation and the VSCode description of the virtual_memory() function is still confusing.

<img width="727" alt="Screenshot 2022-11-10 at 14 55 04" src="https://user-images.githubusercontent.com/75582081/201110921-311fd648-3f11-49af-a6ba-cbabe1a95c0a.png">
