### ISSUE TITLE
search error

### ISSUE THREAD

**Issue by HAPKOMAHcer** [osm-search/Nominatim#2876]
What did you search for?

РЕСТОРАН БЕЛЫЙ АИСТ РЕЧИЦА
https://nominatim.openstreetmap.org/ui/search.html?q=%D0%A0%D0%95%D0%A1%D0%A2%D0%9E%D0%A0%D0%90%D0%9D+%D0%91%D0%95%D0%9B%D0%AB%D0%99+%D0%90%D0%98%D0%A1%D0%A2+%D0%A0%D0%95%D0%A7%D0%98%D0%A6%D0%90

What result did you expect?

https://nominatim.openstreetmap.org/ui/search.html?q=%D1%80%D0%B5%D1%81%D1%82%D0%BE%D1%80%D0%B0%D0%BD+%D0%B1%D0%B5%D0%BB%D1%8B%D0%B9+%D0%B0%D0%B8%D1%81%D1%82+%D1%80%D0%B5%D1%87%D0%B8%D1%86%D0%B0

What did you search for?
КАФЕ ШЕФ РЕЧИЦА
https://nominatim.openstreetmap.org/ui/search.html?q=%D0%9A%D0%90%D0%A4%D0%95+%D0%A8%D0%95%D0%A4+%D0%A0%D0%95%D0%A7%D0%98%D0%A6%D0%90

What result did you expect?

https://nominatim.openstreetmap.org/ui/search.html?q=%D1%88%D0%B5%D1%84+%D0%BA%D0%B0%D1%84%D0%B5+%D1%80%D0%B5%D1%87%D0%B8%D1%86%D0%B0

**Comment by mtmail** [comment]
In the 'what result did you expect' you're listing another search. Can you instead list the exact object you were expecting?

> Make sure that the data you are looking for is in OpenStreetMap. Provide a link to the OpenStreetMap object or if you cannot get it, a link to the map on https://openstreetmap.org where you expect the result to be.
>
> To get the link to the OSM object, you can try the following:
>
> * Go to [https://openstreetmap.org](https://openstreetmap.org).
> * Move to the area of the map where you expect the result and then zoom in as much as possible.
> * Click on the question mark on the right side of the map. You get a question cursor. Use it to click on the map where your object is located.
> * Find the object of interest in the list that appears on the left side.
> * Click on the object and report back the URL that the browser shows.

**Comment by lonvia** [comment]
There is something wrong with the special operators. The search ends up as "restaurant near БЕЛЫЙ АИСТ РЕЧИЦА".

**Comment by 7171bel** [comment]
What did you search for?

https://nominatim.openstreetmap.org/ui/search.html?q=%D0%A0%D0%95%D0%A1%D0%A2%D0%9E%D0%A0%D0%90%D0%9D+%D0%91%D0%95%D0%9B%D0%AB%D0%99+%D0%90%D0%98%D0%A1%D0%A2%2C+%D0%A0%D0%95%D0%A7%D0%98%D0%A6%D0%90

What result did you get?

https://nominatim.openstreetmap.org/ui/details.html?osmtype=N&osmid=306064371&class=amenity

What result did you expect?

https://nominatim.openstreetmap.org/ui/details.html?osmtype=W&osmid=239848644&class=amenity

Further details

Wrong result in upper case.

When I search in lower case, I expect that I need:

https://nominatim.openstreetmap.org/ui/search.html?q=%D0%A0%D0%B5%D1%81%D1%82%D0%BE%D1%80%D0%B0%D0%BD+%D0%91%D0%B5%D0%BB%D1%8B%D0%B9+%D0%90%D0%B8%D1%81%D1%82%2C+%D0%A0%D0%B5%D1%87%D0%B8%D1%86%D0%B0

Thus, the search result is radically different from the case of the entered query, which does not change the essence of the query, but produces different (wrong) results.

**Comment by 7171bel** [comment]
Why the same request in different CASE (case) returns different results?

**Comment by lonvia** [comment]
I can't see any difference in the results. If you have a query where case matters, please open a new issue and provide working examples.

**Comment by 7171bel** [comment]
What did you search for?

https://nominatim.openstreetmap.org/ui/search.html?q=%5Bamenity%3Drestaurant%5D+%D0%91%D0%95%D0%9B%D0%AB%D0%99+%D0%90%D0%98%D0%A1%D0%A2%2C+%D0%A0%D0%95%D0%A7%D0%98%D0%A6%D0%90%2C+%D0%91%D0%95%D0%9B%D0%90%D0%A0%D0%A3%D0%A1%D0%AC

What result did you get?

https://nominatim.openstreetmap.org/ui/details.html?osmtype=N&osmid=306064371&class=amenity

What result did you expect?

https://nominatim.openstreetmap.org/ui/details.html?osmtype=W&osmid=239848644&class=amenity
