### ISSUE TITLE
Search problem using viewbox

### ISSUE THREAD

**Issue by MatsGej** [osm-search/Nominatim#2877]
## What did you search for?
All the restaurants within a viewbox in Sweden

https://nominatim.openstreetmap.org/search?q=restaurant&format=json&debug=0&viewbox=56.876117312824135,14.80401225330986,56.8817615578279,14.814320969994824&bounded=1&extratags=1addressdetails=1&namedetails=1&limit=15

## What result did you get?
No results
## What result did you expect?
A number of restaurants

If I do a similar search but using around in overpass turbo, I get a number of restaurants
node(around:800.00,56.876944,14.809167)["amenity"="restaurant"];

Or if I do this in overpass turbo (setting the polygon to the corners of the viewbox) I get 6 restaurants
node(poly:"56.8817615578279 14.81432174669014 56.876117312824135 14.814320969994824 56.876117312824135 14.804013030005176 56.8817615578279 14.80401225330986");

**When the result in the right place and just named wrongly:** 
??

??
**When the result missing completely:**
Every time

## Further details
I have attached  the viewbox image

![Viewbox](https://user-images.githubusercontent.com/46919059/201543810-26e4ae58-5966-4288-861c-9e3c198a6271.png)

**Comment by MatsGej** [comment]
Had the long lat in the wrong order

**Comment by mtmail** [comment]
If anybody else has similar issues: replace format=json with format=html in the URL and look for the green box on the map (it's tiny though).
![image](https://user-images.githubusercontent.com/3727288/201546196-a844e3cc-5d25-41c4-975f-6d782baf25f1.png)
