### ISSUE TITLE
InvalidTextRepresentation error when updating

### ISSUE THREAD

**Issue by JehtJanich** [osm-search/Nominatim#2897]
**Describe the bug**
When running `nominatim replication` I see an error in the log file:

`2022-11-22 11:18:12: Starting interpolation lines (location_property_osmline) (using batch size 20)
Traceback (most recent call last):
  File "/usr/local/bin/nominatim", line 14, in <module>
    exit(cli.nominatim(module_dir='/usr/local/lib/nominatim/module',
  File "/usr/local/lib/nominatim/lib-python/nominatim/cli.py", line 264, in nominatim
    return parser.run(**kwargs)
  File "/usr/local/lib/nominatim/lib-python/nominatim/cli.py", line 126, in run
    return args.command.run(args)
  File "/usr/local/lib/nominatim/lib-python/nominatim/clicmd/replication.py", line 196, in run
    self._update(args)
  File "/usr/local/lib/nominatim/lib-python/nominatim/clicmd/replication.py", line 161, in _update
    indexer.index_full(analyse=False)
  File "/usr/local/lib/nominatim/lib-python/nominatim/indexer/indexer.py", line 140, in index_full
    if self.index_by_rank(26, 30) > 1000:
  File "/usr/local/lib/nominatim/lib-python/nominatim/indexer/indexer.py", line 178, in index_by_rank
    total += self._index(runners.InterpolationRunner(analyzer), 20)
  File "/usr/local/lib/nominatim/lib-python/nominatim/indexer/indexer.py", line 234, in _index
    runner.index_places(pool.next_free_worker(), part)
  File "/usr/local/lib/nominatim/lib-python/nominatim/db/async_connection.py", line 201, in next_free_worker
    return next(self.free_workers)
  File "/usr/local/lib/nominatim/lib-python/nominatim/db/async_connection.py", line 209, in _yield_free_worker
    if thread.is_done():
  File "/usr/local/lib/nominatim/lib-python/nominatim/db/async_connection.py", line 159, in is_done
    if self.conn.poll() == psycopg2.extensions.POLL_OK:
psycopg2.errors.InvalidTextRepresentation: invalid input syntax for type smallint: "12-2"
CONTEXT:  PL/pgSQL function osmline_update() line 42 at assignment`

After that the import of this chunk seems to start over again.

**To Reproduce**

- Install nominatim 4.1.99
- import Europe from [geofabrik](https://download.geofabrik.de/europe.html)
- nominatim http://download.geofabrik.de/europe-updates/
- Update maps using `nominatim replication --init` AND `nominatim replication`

**Software Environment (please complete the following information):**
- Nominatim version: 4.1.99-0
- Postgresql version: 14.5
- Postgis version: 3.2.0
- OS: Ubuntu 22.04.1 LTS

**Hardware Configuration (please complete the following information):**
- RAM: 16GB
- number of CPUs: 4 VCPUs
- type and size of disks: 20GB local + 1000GB mounted Volume (DB Storage; EXT4)
- bare metal/AWS/other cloud service: Hetzner Cloud Services

**Postgresql Configuration:**
According to the documentation:
shared_buffers = 512MB
maintenance_work_mem = 4GB
autovacuum_work_mem = 512MB
work_mem = 12MB
effective_cache_size = 6GB
synchronous_commit = off
max_wal_size = 1GB
checkpoint_timeout = 10min
checkpoint_completion_target = 0.9

**Comment by mtmail** [comment]
This has been fixed in https://github.com/osm-search/Nominatim/pull/2889, part of Nominatim 4.1.1 release
https://github.com/osm-search/Nominatim/releases/tag/v4.1.1
https://github.com/osm-search/Nominatim/blob/4.1.x/ChangeLog

**Comment by lonvia** [comment]
(as per the instructions from https://nominatim.org/2022/11/20/release-411.html)

### Fixing a potential failure during updates

Please note that this release also fixes a potential crash of the update
process when handling `addr:interpolation` updates with an illegal value. If
you see an error message like this while running updates:

``` sh
psycopg2.errors.InvalidTextRepresentation: invalid input syntax for type smallint: "12-2"
```

then some illegal data has found its way into your database. You need to first
remove the bad data by running the following SQL command (using psql):

``` sql
DELETE FROM location_property_osmline
  WHERE address->'interpolation' not in ('odd', 'even', 'all')
        and not address->'interpolation' similar to '[1-9]'
```

Then update Nominatim to the latest 4.1.1 version and restart updates.

**Comment by JehtJanich** [comment]
Thanks a lot!
When googling i couldn't find a solution. So this was of great help!
