### ISSUE TITLE
Index issue/missing on update 4.1 => 4.1.1

### ISSUE THREAD

**Issue by geoneutrino** [osm-search/Nominatim#2900]
Last week i installed a system with release 4.1 and complete planet import. Now i saw 4.1.1 release and wanted to update but after compile migrate says everything ok
(edit: used the release download on https://nominatim.org/ )

nominatim admin --migrate
2022-11-22 14:02:51: Using project directory: <cut>
2022-11-22 14:02:51: Checking for necessary database migrations
2022-11-22 14:02:51: Database already at latest version (4.1.99-0)

but check database misses indexes
nominatim admin --check-database
2022-11-22 14:07:14: Using project directory: <cut>
2022-11-22 14:07:14: Checking database
Checking database connection ... OK
Checking for placex table ... OK
Checking for placex content ... OK
Checking that tokenizer works ... OK
Checking for wikipedia/wikidata data ... OK
Checking indexing status ... OK
Checking that database indexes are complete ... Failed
           The following indexes are missing:
             idx_placex_rank_address_sector
idx_placex_rank_boundaries_sector

           Rerun the index creation with:   nominatim import --continue db-postprocess

When i run "nominatim import --continue db-postprocess" this takes a lot of time but after finishing the check-database has same issue
It seems that something is missing in the update script / db check ? 

System seems to work normal on search/reverse calls

nominatim --version
Nominatim version 4.1.99-0 ()

**Comment by mtmail** [comment]
I see the index creation was added two months ago, sometime between 4.1.0 and 4.1.1 and indeed isn't part of `nominatim admin --migrate` yet. Also `idx_placex_rank_search` index is no longer needed. 

https://github.com/osm-search/Nominatim/commit/f4d3ae6f70e5f0e86475d75c79dd3cbe1c07e103

> System seems to work normal on search/reverse calls

As far as I see it'll only affect performance of applying data updates.

**Comment by lonvia** [comment]
Your database reports that you have been using a development version from master. You should not update to a released version from there. This is not supported because release versions are created from a separate branch.

**Comment by lonvia** [comment]
Argh, turns out I've packaged the wrong branch in the tar ball. This is bad. I will need to do a 4.2. release with the current master to fix things for people running releases.

**Comment by lonvia** [comment]
The 4.2 release with a fix is in the making. In the meantime you can safely ignore the error report. The existing indexes are just fine.
