### ISSUE TITLE
different results depend on CASE of request

### ISSUE THREAD

**Issue by 7171bel** [osm-search/Nominatim#2904]
What did you search for?

https://nominatim.openstreetmap.org/ui/search.html?q=%5Bamenity%3Drestaurant%5D+%D0%91%D0%95%D0%9B%D0%AB%D0%99+%D0%90%D0%98%D0%A1%D0%A2%2C+%D0%A0%D0%95%D0%A7%D0%98%D0%A6%D0%90%2C+%D0%91%D0%95%D0%9B%D0%90%D0%A0%D0%A3%D0%A1%D0%AC

What result did you get?

https://nominatim.openstreetmap.org/ui/details.html?osmtype=N&osmid=306064371&class=amenity

What result did you expect?

https://nominatim.openstreetmap.org/ui/details.html?osmtype=W&osmid=239848644&class=amenity

Further details:

When I search in lower case, result differs (correct) :

search:
https://nominatim.openstreetmap.org/ui/search.html?q=%5Bamenity%3Drestaurant%5D+%D0%91%D0%B5%D0%BB%D1%8B%D0%B9+%D0%B0%D0%B8%D1%81%D1%82%2C+%D0%A0%D0%95%D0%A7%D0%98%D0%A6%D0%90%2C+%D0%91%D0%95%D0%9B%D0%90%D0%A0%D0%A3%D0%A1%D0%AC

correct result:
https://nominatim.openstreetmap.org/ui/details.html?osmtype=W&osmid=239848644&class=amenity

When I change place of amenity, results also differents and also depend on case of request:
1) https://nominatim.openstreetmap.org/ui/search.html?q=%D0%91%D0%95%D0%9B%D0%AB%D0%99+%D0%90%D0%98%D0%A1%D0%A2+%5Bamenity%3Drestaurant%5D%2C+%D0%A0%D0%95%D0%A7%D0%98%D0%A6%D0%90%2C+%D0%91%D0%95%D0%9B%D0%90%D0%A0%D0%A3%D0%A1%D0%AC

2) https://nominatim.openstreetmap.org/ui/search.html?q=%D0%91%D0%B5%D0%BB%D1%8B%D0%B9+%D0%B0%D0%B8%D1%81%D1%82+%5Bamenity%3Drestaurant%5D%2C+%D0%A0%D0%95%D0%A7%D0%98%D0%A6%D0%90%2C+%D0%91%D0%95%D0%9B%D0%90%D0%A0%D0%A3%D0%A1%D0%AC

**Comment by lonvia** [comment]
PHP's stripos doesn't do case-insensitive UTF-8 comparison, only ASCII. This won't work for Cyrillic letters. So the reranking gives different results depending on if query and result match case-sensitively or not.

**Comment by 7171bel** [comment]
Для этих целей в своей работе в php я использую mb_stripos с указанием UTF-8. Например, результатом mb_stripos('АБВГД', 'в', 0, 'UTF-8') = 2
