### ISSUE TITLE
Unnecessary postcode returned on long rivers

### ISSUE THREAD

**Issue by ZeLonewolf** [osm-search/Nominatim#2915]
When retrieving results for rivers, Nominatim returns a result which includes a post code.  For example, searches:

https://nominatim.openstreetmap.org/ui/search.html?q=Mississippi+River
https://nominatim.openstreetmap.org/ui/search.html?q=Nile+River

Return the results:

![image](https://user-images.githubusercontent.com/3254090/206048411-39c558fd-9a3f-4372-961d-a2c17e251126.png)
![image](https://user-images.githubusercontent.com/3254090/206048460-61d89393-2648-401c-9706-0410604eae4d.png)

Since rivers can be long (10s to thousands of kilometers in length), it does not make sense to return a postcode in the results of river searches.  For these two examples, I would expect (ideally) something like:

* **Mississippi River, United States** (river)
* **Nile River** (river)

While the issue of a river crossing one or more international boundaries is a tangential issue to this (since the Nile spans Egypt and Sudan), it's rarely correct to attribute a postcode, which is an extremely specific location, to a river.

**Comment by lonvia** [comment]
Fix is now live. Please be aware that you see the effects only gradually as data gets edited.

**Comment by ZeLonewolf** [comment]
Looks great, thanks!
https://www.openstreetmap.org/search?query=Missouri%20River
