### ISSUE TITLE
Exclude name:etymology:* from indexing

### ISSUE THREAD

**Issue by spixi** [osm-search/Nominatim#2933]
## What did you search for?
Düsseldorf

## What result did you get?
Way Faunastraße (369241294)

## What result did you expect?
This way should not appear when searching for Düsseldorf.

The way [Faunastraße (369241294)](https://www.openstreetmap.org/way/369241294) contains the string "Tierschutzverein Fauna, Düsseldorf" (Animal Welfare Association Fauna, Düsseldorf) in the attribute name:etymology:wikidata:missing
The attribute name:etymology:* is for name etymology, but not for names and should not be indexed.

**Comment by spixi** [comment]
Here is the [search result](https://nominatim.openstreetmap.org/ui/details.html?osmtype=W&osmid=42218997&class=highway). In the output _Tierschutzverein Fauna, Düsseldorf_ is considered to be a name, because of the attribute name:etymology:wikidata:missing

**Comment by mtmail** [comment]
Adding relevant documentation:

https://wiki.openstreetmap.org/wiki/Key:name:etymology

https://taginfo.openstreetmap.org/keys/name%3Aetymology

https://www.openstreetmap.org/way/149904315#map=18/51.23339/6.77593

**Comment by lonvia** [comment]
`name:etymology`, `name:etymology:wikipedia` and `name:etymology:wikidata` are [already excluded](https://github.com/osm-search/Nominatim/blob/master/settings/import-extratags.style#L10). `name:etymology:wikidata:missing` is simply non-sensical. I'd consider it a data error.

**Comment by spixi** [comment]
@lonvia
The attribute name:etymology:wikidata:missing is used [1566 times](https://taginfo.openstreetmap.org/keys/name:etymology:wikidata:missing) , so I doubt that this is a data error.

**Comment by lonvia** [comment]
1k world-wide usage is nothing and there is no description in the wiki what it even means.

Closing as mostly solved.

**Comment by spixi** [comment]
119 users using that key is significant. Also, it is very odd, that `name:etymology:wikidata` is excluded, but `name:etymology:wikidata:missing` not.

**Comment by spixi** [comment]
There is also another key often used in combination with `name:etymology:wikidata:missing`, called `name:etymology:description`. @hholzgra You are the developer of hholzgra/Mapnik-gaslight-overlay and it seems that `name:etymology:wikidata:missing` has a strong correlation with the key `lit_by_gaslight`. Do you know anything about the `name:etymology:wikidata:missing` key and its purpose?
