### ISSUE TITLE
name should take precedence over name:*

### ISSUE THREAD

**Issue by SLMapper** [osm-search/Nominatim#2934]
## What did you search for?
https://www.openstreetmap.org/search?query=Entringen#map=13/49.4146/6.1135

(with German browser locale I guess; logged in with user settings:
Bevorzugte Sprachen de-DE de en-US en) 

## What result did you get?
1. village [Entrange](https://www.openstreetmap.org/relation/1553189) (name:de=Entringen) 
2. village [Entringen](https://www.openstreetmap.org/relation/4557331) 

## What result did you expect?
Resultat with "name" to appear first over "name:de" from France. 

(On the other hand ordering still needs to consider foreign names of a city higher than the local name of a village, which I assume is already implemented like this)

**Comment by lonvia** [comment]
Certainly not, unless you like to see ''北京市" when searching for Beijing.

This is simply ad data issue. The tagging must be done in a way that Nominatim can distinguish if the name is being used. If a name is not in active use, use `old_name` and its variants when tagging. Before changing anything discuss with the local community what names they consider not to be in active use.

**Comment by SLMapper** [comment]
Was my request misunderstood or did't I understand your answer? 
This request is not about in which locale the result is displayed, but about result ordering. 

So my request is to show results for "name" before results for "name:*". 

Exception: cities with "name:*" should get higher rank than villages with "name"

So yes, when searching for "Peking" I want to find the city of Beijing (北京市) as first result.

**Comment by lonvia** [comment]
The French village is first simply because it's a lot bigger than the German hamlet. This kind of ordering is a good thing. Keeping with the 'Peking' example, you wouldn't want [the ship Peking](https://www.openstreetmap.org/way/845145391) appear higher in the result list than the city of Beijing simply because the former matches the name and the latter doesn't.

**Comment by SLMapper** [comment]
Thanks for giving the example. Yes this is true. However it seems that Nominatim / Openstreetmap also considers proximity.
So when I do two consecutive searches:
- Hamburg: https://www.openstreetmap.org/search?query=hamburg#map=2/40.9/104.1
- Peking: https://www.openstreetmap.org/search?query=peking#map=9/53.7126/9.2149
I end up with the ship.

How is the "a lot bigger" calculated?
- boundaries are bigger for German Entringen
- population is not given for German Entringen (but knowingly it is around a similar value)
- only admin_level I can see 1 level above for French Entrange

[French Entrange](https://www.openstreetmap.org/relation/1553189#map=14/49.4146/6.1136) 
[German Entringen](https://www.openstreetmap.org/relation/4557331#map=14/48.5570/8.9828)
