### ISSUE TITLE
Unable to find nearest lighthouse by partial match

### ISSUE THREAD

**Issue by fgnievinski** [osm-search/Nominatim#2935]
## What did you search for?
I was browsing OSM near -30.91215,-51.50066:
https://www.openstreetmap.org/#map=18/-30.91215/-51.50066&layers=Y

I've searched for "lighthouse" and also for the corresponding translation in the local language ("farol", in Portuguese); here's an attempt at replicating the search in Nominatim, with a similar view box:
https://nominatim.openstreetmap.org/ui/search.html?q=farol&viewbox=-51.16607%2C-31.06281%2C-51.16417%2C-31.06419

## What result did you get?
the main results are about administrative units named similarly ("farol"), much farther away than the nearest lighthouse.

## What result did you expect?
**When the result missing completely:**
https://nominatim.openstreetmap.org/ui/details.html?osmtype=W&osmid=546142204&class=man_made

## Further details
Searching by the feature full name returns the correct result, for example (I'm not sure this is the nearest one):
https://nominatim.openstreetmap.org/ui/search.html?q=farol+da+solid%C3%A3o&viewbox=-52.87857%2C-23.93605%2C-52.39380%2C-24.31206

The problem is the user normally doesn't know the full name of features they see outdoors, only the type of feature (lighthouse, in this case) can be recognized.

**Comment by lonvia** [comment]
Descriptive terms for Nominatim are known as 'Special Phrases' and can be added via https://wiki.openstreetmap.org/wiki/Nominatim/Special_Phrases/ Neither lighthouse nor farol are currently in that list. So that's the place to start.

When you add them, please be aware that the database pulls these special terms only infrequently.

**Comment by fgnievinski** [comment]
done:
https://wiki.openstreetmap.org/w/index.php?title=Nominatim/Special_Phrases/EN&diff=2458998&oldid=2319986
thanks for the pointer

**Comment by fgnievinski** [comment]
question: in addition to the descriptive term (related to type tag), couldn't Nominatim find the feature by its name ("Farol...")?
