### ISSUE TITLE
Update Taginfo Projects

### ISSUE THREAD

**Issue by danieldegroot2** [osm-search/Nominatim#2938]
Show the OpenStreetMap community what [data](https://wiki.openstreetmap.org/wiki/Tags) you are using. Update your project on the [list](https://taginfo.openstreetmap.org/projects) of [Taginfo Projects](https://github.com/taginfo/taginfo-projects).

**Comment by lonvia** [comment]
Somebody would have to write a converter from the [lua import style](https://nominatim.org/release-docs/develop/customize/Import-Styles/) to a taginfo project description. The original one is not up to date any longer.

**Comment by biswajit-k** [comment]
I would like to work on this issue if it's available. 
I had gone through the above lua import style guide and the format required for the project description. Also, could you please provide the source of the old converter? I searched for it but couldn't find it. It would be quite helpful for reference.

**Comment by mtmail** [comment]
The output file should be https://nominatim.openstreetmap.org/taginfo.json I'm not aware that the file was created from a script previously, I think it was manual.

**Comment by lonvia** [comment]
Indeed. This file was generate by hand from the old [import styles](https://github.com/osm-search/Nominatim/blob/4.2.x/settings/import-extratags.style).

My idea here was to write a small lua script, that imports a Nominatim lua style and then outputs the taginfo json file by just printing to stdout. There is a dirt trick, how to make that work. Write your own flex-base.lua, which implements their own variant of the convenience functions described [here](https://nominatim.org/release-docs/develop/customize/Import-Styles/#changing-the-recognized-tags). The parameters for these functions have all the relevant tags in handy lists, so they can be easily collected and afterwards printed.

**Comment by biswajit-k** [comment]
Thanks, @mtmail, @lonvia for the information and suggestion. I had gone for [this issue](https://github.com/osm-search/Nominatim/issues/2953) and would come to this one when its done.

**Comment by lonvia** [comment]
The taginfo.json generated by @biswajit-k's code is now live on https://nominatim.openstreetmap.org/taginfo.json.
