### ISSUE TITLE
Update OSM Wiki

### ISSUE THREAD

**Issue by danieldegroot2** [osm-search/Nominatim#2939]
Was: #2938 

A similar file which [is linked on the wiki](https://wiki.openstreetmap.org/wiki/Nominatim/Development_overview#Tags_processed) has since [changed file name](https://github.com/osm-search/Nominatim/blob/master/settings/import-extratags.lua).

**Comment by lonvia** [comment]
How about you do some research yourself instead of just opening issues everywhere?

I've deleted the page. It's no longer relevant.
