### ISSUE TITLE
Nominatim refresh importance data doesn't work

### ISSUE THREAD

**Issue by santifa** [osm-search/Nominatim#2948]
Hey folks,

it seems the function triggered by python has changed in the latest version of nominatim.
See the [line](https://github.com/osm-search/Nominatim/blob/5f4e98e0d9b5e89c81bc09a53cfdba1bdb45351b/nominatim/tools/refresh.py#L179) which uses the old parameters while the new [`compute_importance`](https://github.com/osm-search/Nominatim/blob/5f4e98e0d9b5e89c81bc09a53cfdba1bdb45351b/lib-sql/functions/importance.sql#L101) uses only `rank_search` and not `osm_type` or `osm_id`.

**Comment by lonvia** [comment]
Thanks for the report.
