### ISSUE TITLE
Searching categories

### ISSUE THREAD

**Issue by GitFredo0** [osm-search/Nominatim#2965]
## What did you search for?

Search N5393502035

## What result did you get?
I got a dermatologist on Italy.

## What result did you expect?
I expected maps to show me the Dermatologist on my last search zone (Zacatecas, Mexico) on this case.
You should  create search tags so when you search this type of places or medic, urologist, nutriologist, food, or any other thing the map show you the options near you, not that it shows always a specific place on the other side of the world just because it was called "Dermatologo".

**When the result in the right place and just named wrongly:** 

**When the result missing completely:**

**Comment by mtmail** [comment]
@GitFredo0 You looked at a map of Zacatecas https://www.openstreetmap.org/relation/5606652#map=12/22.7294/-102.6945

What did you type into the search field? What did you search for (in your language)?

**Comment by GitFredo0** [comment]
I did searched "Dermatologo"

Enviado desde Proton Mail móvil

-------- Mensaje original --------

**Comment by mtmail** [comment]
Searching categories has been a long time feature request. It partly works with so called 'special phrases', see https://nominatim.org/release-docs/latest/api/Search/ and https://wiki.openstreetmap.org/wiki/Nominatim/Special_Phrases/ES

There are no dermatologist, urogist, etc places in OpenStreetMap data in that city https://overpass-turbo.eu/s/1qMO If you know any the first step would be to add them to the OpenStreetMap data https://www.openstreetmap.org/fixthemap

The issue template for reporting issues with results also has a section "When the result missing completely" https://github.com/osm-search/Nominatim/issues/new?template=report-issues-with-search-results.md

**Comment by GitFredo0** [comment]
If there's no data about the search on the zone I'm looking for it should show an advertising saying something like "There are not places with your description, please zoom out or search on other place" instead of sending you to another country. It is quite annoying.

Enviado desde Proton Mail móvil

-------- Mensaje original --------

**Comment by GitFredo0** [comment]
Also I think that in order to get more searches, it definitely has to have this feature because for example if I search "Comida" in "Zacatecas" it gives me a specific place instead of showing all the results related with this. (Attached are the screenshots of the search)
In this case could you for example add a tag of "Comida" to all the "restaurantes" and "gorditas" and all the places related to food, doing it by code?. Because if I try to add that tag one by one is gonna be so hard.

Enviado desde Proton Mail móvil

-------- Mensaje original --------

**Comment by mtmail** [comment]
If you need the search to be only within the bounds of the current map view you can set `bounded=1` ("When a viewbox is given, restrict the result to items contained within that viewbox") https://nominatim.org/release-docs/latest/api/Search/ 

I can only explain how the Nominatim search software works. How websites, e.g. www.openstreetmap.org, integrate the search is up to them.

**Comment by GitFredo0** [comment]
Wait, I thought you could improve openstreetmap.org coding because they sent me to you guys.
Is that wrong?

Enviado desde Proton Mail móvil

-------- Mensaje original --------

**Comment by lonvia** [comment]
I think @mtmail has said everything there is to say about this issue.
