### ISSUE TITLE
County not found but exists in openstreetmap.org

### ISSUE THREAD

**Issue by xlofhappy** [osm-search/Nominatim#2966]
When I search a city named [万载县](a county in China) via  https://nominatim.openstreetmap.org/ui/search.html, I can't find administration boundary result
I want was https://www.openstreetmap.org/relation/3182919
I use R3182919 to search the Object via https://nominatim.openstreetmap.org/ui/details.html, got nothing.
What is

**Comment by lonvia** [comment]
That was an update glitch where a geometry fix was not picked up. Should all be good now.
