### ISSUE TITLE
First search result for "Columbia, TN" returns a county in Washington

### ISSUE THREAD

**Issue by jeph36** [osm-search/Nominatim#2967]
## What did you search for?

Search text is "Columbia, TN".
https://nominatim.openstreetmap.org/ui/search.html?q=Columbia%2C+TN

## What result did you get?

First search result is Columbia County, WA, near Walla Walla, WA.

## What result did you expect?

The correct result of Columbia, TN, south of Nashville, is listed 2nd on the list.

## Further details

Searching for "Columbia, Tennessee" returns the expected result.

**Comment by lonvia** [comment]
Thai is causing trouble here. The Washington name of 'รัฐวอชิงตัน ' gets transliterated to 'rth wx chng tn'.

**Comment by lonvia** [comment]
We are now tracing scripts, so that matches of Latin input against non-Latin script is heavily penalized.
