### ISSUE TITLE
Broken documentation relative links

### ISSUE THREAD

**Issue by kevinlin1** [osm-search/Nominatim#2968]
**Describe the bug**

Several links in the nominatim.org/release-docs are broken due to differences between relative links hard-coded in the documentation and the permalinks for pages generated by MkDocs. For example, I was able to find the following two pages where links are broken:

- [`docs/api/Output.md`](https://nominatim.org/release-docs/latest/api/Output/). The "search rank" and "address rank" links are broken. The link includes an extra `api` subdirectory in the URL path, which leads to a 404 error.
- [`docs/customize/Importance.md`](https://nominatim.org/release-docs/latest/customize/Importance/). The "search rank" link is broken. The link includes an extra `customize` subdirectory in the URL path, which leads to a 404 error.

The problem is most likely due to differences between how MkDocs treats links. For example, the relative link `../customize/Ranking#search-rank` will be literally copied into the HTML whereas the relative link `../customize/Ranking.md` will be picked-up by the MkDocs system and generate a correct permalink.

I have not examined whether `../customize/Ranking.md#search-rank` will correct this issue.

**To Reproduce**

This issue is occurring on the live, public deployment of the Nominatim documentation; I have not tried to reproduce the issue locally yet.

**Comment by lonvia** [comment]
That's indeed a problem of missing `.md` suffixes. Mkdocs won't rewrite the URLs when the link names don't correspond to a real file name. I thought I'd caught all suffix-less links by now but apparently not.
