### ISSUE TITLE
Wrong adress

### ISSUE THREAD

**Issue by RmVTA** [osm-search/Nominatim#2971]
Hello,

There is an error on the address of Villa Thuret in France, it is not Grasse but only Antibes!
Very important, because when you put the location on an event on Telabotanica, the event is located in Grasse, instead of Antibes. Can you make the change? Thanks!

Here is the current wrong address, you just need to just remove Grasse! We don't need to mention Grasse arrondissement in a french address. 

That's the wrong address : 

Villa Thuret, 90, Chemin Gustave Raymond, Cap d'Antibes, Antibes, Grasse, Alpes-Maritimes, Provence-Alpes-Côte d'Azur, France métropolitaine, 06160, France

New one : 

Villa Thuret, 90, Chemin Gustave Raymond, Cap d'Antibes, Antibes, Alpes-Maritimes, Provence-Alpes-Côte d'Azur, France métropolitaine, 06160, France

**Describe the bug**

**To Reproduce**

**Software Environment (please complete the following information):**
- Nominatim version: 
- Postgresql version: 
- Postgis version:
- OS: 

**Hardware Configuration (please complete the following information):**
- RAM: 
- number of CPUs:
- type and size of disks:
- bare metal/AWS/other cloud service: 

**Postgresql Configuration:**

**Additional context**

**Comment by mtmail** [comment]
This is the building: https://nominatim.openstreetmap.org/ui/details.html?osmtype=W&osmid=68063027&class=building

Nominatim returns
https://nominatim.openstreetmap.org/search.php?q=Villa+Thuret%2C+90%2C+antibes&format=jsonv2&addressdetails=1&pretty=1
```json
      "address": {
            "building": "Villa Thuret",
            "house_number": "90",
            "road": "Chemin Gustave Raymond",
            "suburb": "Cap d'Antibes",
            "town": "Antibes",
            "municipality": "Grasse",
            "county": "Maritime Alps",
            "state": "Provence-Alpes-Côte d'Azur",
            "region": "Metropolitan France",
            "postcode": "06160",
            "ISO3166-2-lvl4": "FR-PAC",
            "ISO3166-2-lvl6": "FR-06",
            "country": "France",
            "country_code": "fr"
        }
        "display_name": "Villa Thuret, 90, Chemin Gustave Raymond, Cap d'Antibes, Antibes, Grasse, Maritime Alps, Provence-Alpes-Côte d'Azur, Metropolitan France, 06160, France",
```

> when you put the location on an event on Telabotanica, the event is located in Grasse, instead of Antibes. Can you make the change?

We can't make that change. The location is both in Antibes and Grasse. The Telabotanica software/website needs to take the Nominatim data and use `municipality` instead of `town` in this case if that's preferred.
