### ISSUE TITLE
New GB postcode Feb 2023 files

### ISSUE THREAD

**Issue by mtmail** [osm-search/Nominatim#2976]
A new CODEPO file got released on https://osdatahub.os.uk/downloads/open/CodePointOpen

I converted it with https://github.com/osm-search/gb-postcode-data/ and placed it on
https://downloads.opencagedata.com/public/gb_postcodes.202302.csv.gz (13MB)
https://downloads.opencagedata.com/public/gb_and_ni_postcodes.202302.csv.gz (13MB)

Please review and upload to https://www.nominatim.org/downloads/

$ ./compare.py gb_postcodes.202211.csv gb_postcodes.csv
Read 1730303 postcodes from old file gb_postcodes.202211.csv
Read 1731989 postcodes from new file gb_postcodes.csv
Added: 4705 (0.272%)
Deleted: 3019 (0.174%)
Position moved: 60753 (3.508%)
Position moved more than 100 meters: 10493 (0.606%)
Position moved more than 1000 meters: 520 (0.030%)
Position moved more than 10000 meters: 3 (0.000%)
Average distance difference of all updates: 84.02 meters

**Comment by lonvia** [comment]
Done.
