### ISSUE TITLE
Add Latvia (LV) to special phrases wiki import script's list

### ISSUE THREAD

**Issue by HellMapGoesCoding** [osm-search/Nominatim#2982]
In short, please add newly-created https://wiki.openstreetmap.org/wiki/Nominatim/Special_Phrases/LV to https://github.com/osm-search/Nominatim/blob/master/nominatim/tools/special_phrases/sp_wiki_loader.py, i.e. and `lv` entry

The code calls `self.config.get_str_list('LANGUAGES')`, so I'm not exactly sure if the language list is somehow automated or what this means exactly, but there's an explicit list given, so I'm assuming it needs to be added still?

Thanks.

P. S. I should also note that these two are missing from the list:
* https://wiki.openstreetmap.org/wiki/Nominatim/Special_Phrases/DE_AT
* https://wiki.openstreetmap.org/wiki/Nominatim/Special_Phrases/TR

I cannot say anything about whether they should be added or not at this point.

**Comment by mtmail** [comment]
I created https://github.com/osm-search/Nominatim/pull/2986 to add them.

`self.config.get_str_list('LANGUAGES')`: this reads the configuration value `NOMINATIM_LANGUAGES` (https://nominatim.org/release-docs/latest/customize/Settings/#nominatim_languages), which is usually empty/unset.

**Comment by danieldegroot2** [comment]
The PR has since been merged.

cc: @lonvia This issue seems to have been resolved.

**Comment by lonvia** [comment]
There will be a reimport of the databases in the comming weeks. That should eventually include the new list.
