### ISSUE TITLE
[Feature Request]: Nearest distance to country etc.

### ISSUE THREAD

**Issue by MarketingPip** [osm-search/Nominatim#2995]
In relation to my previous issue opened #2994 - it would be an enhancement to return the nearest country, city etc if the longitude & latitude provided are over water / ocean etc.

**Comment by lonvia** [comment]
Nominatim does get you country information up until the usual country boundaries. Beyond that the definition of 'nearest country' becomes so fuzzy that it doesn't make sense to add. If you do want geocoding to go further out, simply provide your own `country_osm_grid.sql.gz` with sea boundaries that go much further out into the ocean.

I thought we had discussed nautical applications at some point but can't find it anymore. The gist of it was that it needs to work differently than what we do on land and therefore #510 will pretty much be all that Nominatim might support. And even that has a low priority.

Closing this as 'not planned'.

**Comment by MarketingPip** [comment]
In terms of "fuzzy" matching. Are you saying it is to hard to calculate the distance to a location? As I don't think the math / calculation / algorithmic implementation needed would be that hard. 

Tho if the project / team doesn't see a need for it - that's your call! 👌 

Thanks for prompt response and hope you have an awesome weekend! 😇

**Comment by lonvia** [comment]
I mean 'fuzzy' in the sense of 'not very meaningful'. If you are in the middle of the Atlantic Ocean, the information that Spain is at 345km the closest country somewhat looses its meaning or at least it very much depends on the application which information exactly you want.

In any case, you don't need a full geocoder to get that information if it is useful to you. A simple SpatialLite loaded with country boundaries should do the trick. If you need more than country information, use it to compute the closest point on land and reverse geocode that.

**Comment by MarketingPip** [comment]
Thank you! Tho I was figuring just a good idea for this project 🙈 

Was thinking we would use a pre-existing algorithm that calculates based on something like this
```
[X, X, X]
[X, Y, X,]
[X, Y, X]
```
with X representing any nearest country point from Y (being the long & lat provided). Tho again - if not needed & not a fit. No hard feelings at all!
