### ISSUE TITLE
New York City Metropolitan Area does not return any results

### ISSUE THREAD

**Issue by baditaflorin** [osm-search/Nominatim#3002]
## What did you search for?
New York City Metropolitan Area
https://nominatim.openstreetmap.org/ui/search.html?q=New+York+City+Metropolitan+Area

## What result did you get?
Nothing

## What result did you expect?
To get at least New York City or to get at least something. 

In Debug, it can be seen that there were some candidates that could have been added

<pre style="position: relative;"><h3>Search candidates</h3><div class="open_grepper_editor" title="Edit &amp; Save To Grepper" style="display: block !important; height: 20px !important; width: 20px !important; position: absolute !important; top: 0px !important; right: 0px !important; background-size: 20px 20px !important; cursor: pointer !important; background-color: rgb(0, 0, 0) !important; background-image: url(&quot;data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAABQAAAAUCAYAAACNiR0NAAAABmJLR0QA8gBBAEG7NC6zAAAACXBIWXMAAA7EAAAOxAGVKw4bAAAAB3RJTUUH4wwNFQsGe+TrNQAAADxpVFh0Q29tbWVudAAAAAAAUHJvY2Vzc2VkIEJ5IGVCYXkgd2l0aCBJbWFnZU1hZ2ljaywgejEuMS4wLiB8fEIyejRLlgAAA0RJREFUOMuNlE0odG8Yxn/nOc+c+TCimCkUGYUmjLJgUtgqKQt2srC1sLextbak9EqyHktfO1G+lZIkGVOiTseMMfPMjOe/0IzXy9/7/pbn1NV1X/d9Pcbw8LDmG7TW5PN5DMPANE0MwwDAMAyUUry9vSGlREqJ1h8S4k8BgLe3NwzDYHR0lLGxsdI3gEwmQyQSYWpqimAwiFLqkxFZUhYCv9+P4zgIIZBS0tTUhGmauN1uXl9fUUpRX1/P+Pg4Qggsy/rkruQwm81SV1fH9PQ0ra2t5PN5UqkUu7u7pFIpMpkMQgjy+Ty9vb04jsPc3BzxeBzLsr4KGoZBJpPB7/fT29tLoVBACMHLywvPz8+k02kKhQKNjY2Ew2Hm5+eJx+OYpvklewFgWRb39/fs7OwQCoUIBAIopfB6vdi2XcpwaGiI1dVVbNvG5/N9t8sPh263m1gsRiKRIBqNks1mqaio4PHxkXw+T39/Pzc3N5yfn+N2u/k/hGmaaK3JZDJorfn16xft7e1UVVXh8/l4fHykpaWFcDjMxsYGXq/3yyJ+x5yZmZmdmJggmUySzWZ5enqivLycjo4O3G43tm0TjUbZ3t7Gtm2klPyEMTk5qTs7O2lubqasrIx0Oo3L5aK6uhqtNVJKtra2iMViSCkpFApIKT8d+yeHNTU1s5eXl+zv77O3t4fP56OtrQ2lFLlcDpfLVTr4wcFBAHK5HI7joJTCMAyEEAjx3hFZrE+xUicnJ/T09ODxePB6vVxcXLC+vo5SCq01oVCI7u5uDMPg4eGB6+tr4vE4juO81/H36mmt8Xg8SCmxLIuLiwsWFxdLDg4PDzk+PkZKSUNDA5FIhJGRESorK3Ech7W1NcyWlpbZomgulyMYDDIwMMDt7S1LS0vFMUp1NE0TIQS2bXN0dMTZ2RmBQICmpqZ3M3+GWlNTw/PzMwsLCyilvt2q1hohBOXl5SSTSZaXlzk9PeX+/v5DsBhuV1cXKysrJJNJPB4Pf8PlcgFwcHDwPknxh1KKcDiMbducnp7+2IbvsCzrPeviCAB9fX1sbm7i8/m+vbF/QQAUCgVqa2u5uroikUh8+4r8K7KYw8PDA3d3d3g8nh+7+jf+A6kWbVI0BmDOAAAAAElFTkSuQmCC&quot;) !important;"></div></pre><table border="1"><tbody><tr><th>rank</th><th>Name Tokens</th><th>Name Not</th><th>Address Tokens</th><th>Address Not</th><th>country</th><th>operator</th><th>class</th><th>type</th><th>postcode</th><th>housenumber</th></tr><tr><td>3</td><td>#new york city(W 165427)#</td><td></td><td>#metropolitan(w 59749)#, #area(w 125319)#</td><td></td><td></td><td></td><td></td><td></td><td></td><td></td></tr><tr><td>3</td><td>#area(W 1968696)#</td><td></td><td>#metropolitan(w 59749)#, #new york city(W 165427)#</td><td></td><td></td><td></td><td></td><td></td><td></td><td></td></tr><tr><td>3</td><td>#area(W 8386582)#</td><td></td><td>#metropolitan(w 59749)#, #new york city(W 165427)#</td><td></td><td></td><td></td><td></td><td></td><td></td><td></td></tr><tr><td>3</td><td>#area(W 41295977)#</td><td></td><td>#metropolitan(w 59749)#, #new york city(W 165427)#</td><td></td><td></td><td></td><td></td><td></td><td></td><td></td></tr><tr><td style="color: rgb(0, 0, 0); font-family: Times; font-size: medium; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;">4</td><td style="color: rgb(0, 0, 0); font-family: Times; font-size: medium; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;">#new york(W 68964)#</td><td style="color: rgb(0, 0, 0); font-family: Times; font-size: medium; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;"></td><td style="color: rgb(0, 0, 0); font-family: Times; font-size: medium; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;">#city(w 33117)#, #metropolitan(w 59749)#, #area(w 125319)#</td><td style="color: rgb(0, 0, 0); font-family: Times; font-size: medium; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;"></td><td style="color: rgb(0, 0, 0); font-family: Times; font-size: medium; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;"></td><td style="color: rgb(0, 0, 0); font-family: Times; font-size: medium; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;"></td><br class="Apple-interchange-newline">

**When the result in the right place and just named wrongly:** 

New York City Metropolitan Area
**When the result missing completely:**

**Comment by mtmail** [comment]
> it can be seen that there were some candidates 

The numbers starting with `W` in the table are word token ids internal to the Nominatim database.

Which OSM object should be returned in your opinion? I can't find anything matching https://en.wikipedia.org/wiki/New_York_metropolitan_area in OpenStreetMap data. It looks like a statistical boundary unrelated to addresses.

**Comment by baditaflorin** [comment]
I believe returning something is better than nothing. In this specific case Relation 175905
More generic, it should return the city boundary if there is no metropolitan area. 

From what I see for metropolitan areas there are around 10 countries in OSM that specify what admin_level means metropolitan areas (usually 7) based on the wiki
https://wiki.openstreetmap.org/w/index.php?title=Tag:boundary%3Dadministrative&uselang=en

There are a lot of Metropolitan areas in the world and there are valid use cases where the user would search the city name and include Metropolitan area. 

As of February 28, 2013, the [United States](https://en.wikipedia.org/wiki/United_States) [Office of Management and Budget](https://en.wikipedia.org/wiki/Office_of_Management_and_Budget) (OMB) defined 1,098 [statistical areas](https://en.wikipedia.org/wiki/Statistical_area) for the metropolitan areas of the United States and [Puerto Rico](https://en.wikipedia.org/wiki/Puerto_Rico).[[14]](https://en.wikipedia.org/wiki/Metropolitan_area#cite_note-OMB_13-01-14)
As of 2018, there are 74 zonas metropolitanas in Mexico. 75.1 million people, 62.8% of the country population, live within a metropolitan area.[[13]](https://en.wikipedia.org/wiki/Metropolitan_area#cite_note-conapo2015-13)
[Pakistan](https://en.wikipedia.org/wiki/Pakistan) has nine metropolitan areas with populations greater than a million
There are 30 officially defined "metropolitan municipalities" in Turkey.
https://en.wikipedia.org/wiki/Metropolitan_area

In the end, I will provide some examples of how other companies are returning data for the following search. New York City Metropolitan Area
1. ✅ Here
```
curl 'https://geocoder.ls.hereapi.com/6.2/geocode.json?apiKey=$API_KEY&searchtext=New%20York%20City%20Metropolitan%20Area'
{"Response":{"MetaInfo":{"Timestamp":"2023-03-10T00:20:23.754+0000"},"View":[{"_type":"SearchResultsViewType","ViewId":0,"Result":[{"Relevance":1.0,"MatchLevel":"street","MatchQuality":{"City":1.0,"Street":[0.85]},"Location":{"LocationId":"NT_Ww9Q.27G21bpO1B9Vbd0rB","LocationType":"point","DisplayPosition":{"Latitude":40.60584,"Longitude":-74.11999},"NavigationPosition":[{"Latitude":40.60584,"Longitude":-74.11999}],"MapView":{"TopLeft":{"Latitude":40.60644,"Longitude":-74.12003},"BottomRight":{"Latitude":40.60456,"Longitude":-74.11955}},"Address":{"Label":"Area Pl, Staten Island, NY 10314, United States","Country":"USA","State":"NY","County":"Richmond","City":"Staten Island","District":"Emerson Hill","Street":"Area Pl","PostalCode":"10314","AdditionalData":[{"value":"United States","key":"CountryName"},{"value":"New York","key":"StateName"},{"value":"Richmond","key":"CountyName"},{"value":"N","key":"PostalCodeType"}]}}}]}]}}%                         
```
2. ✅ Apple Maps suggests the City
<img width="380" alt="image" src="https://user-images.githubusercontent.com/2330999/224191480-4b4c731c-4278-4ab2-b7c7-168c7b35710c.png">
3. ❌ OpenCage suggests a city in Italy for the search
<img width="946" alt="image" src="https://user-images.githubusercontent.com/2330999/224191811-f01b3ec0-c2bd-4d1e-9736-da2e8c4c9d26.png">
4. ✅ Google Maps suggests a pin in the middle of New York City
<img width="855" alt="image" src="https://user-images.githubusercontent.com/2330999/224192259-c359bd1e-bf04-4ee3-bdf1-4754ccb7338b.png">
5. ✅ Bing Maps suggest a centroid in the middle of the metropolitan area, probably the most accurate. 
<img width="1485" alt="image" src="https://user-images.githubusercontent.com/2330999/224192666-3de47f39-f11a-49f9-8f47-2da5574423fd.png">
6. ❌ openrouteservice show a lot of locations all over the world
<img width="1510" alt="image" src="https://user-images.githubusercontent.com/2330999/224193316-d1242639-51ff-4098-9634-8330ec4faceb.png">
From the Open Source Geocoder almost all of them fail to give relevant results
7. Photon shows a wrong first result https://photon.komoot.io/
<img width="889" alt="image" src="https://user-images.githubusercontent.com/2330999/224193754-ffdece1b-5180-4462-94aa-4403a613fc46.png">
8. ❌ Geocode Earth
<img width="1187" alt="image" src="https://user-images.githubusercontent.com/2330999/224194115-4d18b65f-05e2-46e3-bbb3-61d7b530deb9.png">
9. ✅https://www.oscar-web.de/ Mostly by luck it shows a point in Jersey City
<img width="816" alt="image" src="https://user-images.githubusercontent.com/2330999/224194256-81308cab-636f-4ee7-84b0-4e8cbcbe1a18.png">
10 ❌ [Gisgraphy](https://github.com/gisgraphy/gisgraphy) ([demo](https://services.gisgraphy.com/public/geocoding.html))
<img width="725" alt="image" src="https://user-images.githubusercontent.com/2330999/224194650-055488f6-3f72-4618-9fa3-d4cef6cee05c.png">
## Other Geocoders
11. ✅ OsmNames https://osmnames.org/#q=new%20york%20city%20administrative%20area
<img width="1009" alt="image" src="https://user-images.githubusercontent.com/2330999/224195071-11ca565c-1761-457b-ad27-3d6f7f64ec5c.png">
12. ✅ [LocationIQ](https://locationiq.com/)
<img width="1156" alt="image" src="https://user-images.githubusercontent.com/2330999/224195349-2b3b8ca5-c66d-4738-a4cd-5cca889f09fe.png">

**Comment by baditaflorin** [comment]
Also, it is possible to get the search terms used for people that are searching in nominatim? 
This would allow us to learn what people are searching for, with a focus on the searches that appear a lot of times and nominatim returns 0 results.
