### ISSUE TITLE
Wildcard support

### ISSUE THREAD

**Issue by Smig0l** [osm-search/Nominatim#3012]
## What did you search for?

I am using nominatim to search for cities/towns in a specific state.
I tried with:

`https://nominatim.openstreetmap.org/search?format=json&accept-language=it&countrycodes=it&state=Lombardy&city=vare`

Tried also with `&q=`.

I know that they should return at least `varedo` and `varese`.

Does Nominatim supports wildcard or is there a way to search for cities in a specific state?

## What result did you get?

But they didn’t return anything.
`{}`
## What result did you expect?
`varedo{}` and `varese{}`
**When the result in the right place and just named wrongly:** 

**When the result missing completely:**

## Further details
Same issue as #2361 (hoping that in 2 years has changed)

**Comment by mtmail** [comment]
As you already discovered it's a duplicate request https://github.com/osm-search/Nominatim/issues/2361
