### ISSUE TITLE
Problem with city name: undefined

### ISSUE THREAD

**Issue by kamilsobik** [osm-search/Nominatim#3018]
## What did you search for?

 For cords: 49.8026196 19.0702093 API does not return the name of the town, although it is in the logs

## What result did you get?

city: undefined

## What result did you expect?

city: Bielsko-Biała

Link to this place in OpenStreetMap
https://www.openstreetmap.org/search?query=49.8026196%2019.0702093#map=19/49.80262/19.07021

## Further details

Link do screen shot from console:
https://i.ibb.co/fnWjcBC/Screenshot-2023-03-28-at-11-51-56.png

**Comment by lonvia** [comment]
Works fine here: https://nominatim.openstreetmap.org/reverse.php?lat=49.8026196&lon=19.0702093&zoom=18&format=json
