### ISSUE TITLE
No geojson data with postalcode 91550

### ISSUE THREAD

**Issue by blankse** [osm-search/Nominatim#3025]
## What did you search for?

https://nominatim.openstreetmap.org/search?format=jsonv2&polygon_geojson=1&postalcode=91550&countrycodes=de

## What result did you get?

No geojson data

## What result did you expect?

geojson data like in other postal code searches

## Further details

The data is available in osm. See https://www.openstreetmap.org/relation/1143749

With other postal code it works.
For example:
https://nominatim.openstreetmap.org/search?format=jsonv2&polygon_geojson=1&postalcode=86633&countrycodes=de

So why not there?

**Comment by lonvia** [comment]
Has already been fixed in #3021.

**Comment by blankse** [comment]
@lonvia Oh nice 👍🏼 Thank you :) Can you say when this is live at the server?

**Comment by lonvia** [comment]
It is live.

**Comment by blankse** [comment]
Thank you very much 👍🏼
