### ISSUE TITLE
Similar places

### ISSUE THREAD

**Issue by davidgutierrez** [osm-search/Nominatim#3027]
What did you search for?

Search text is "Unicento".
https://nominatim.openstreetmap.org/ui/search.html?q=Unicento+Bogota+Colombia

What result did you get?
None

What result did you expect?
https://nominatim.openstreetmap.org/ui/search.html?q=Unicentro+Bogota+Colombia

Further details

It is a common mistake for users to search the name of a place forgetting some letters or having a bad spelling, so having the possibility to search with similar places will helps a lot.

**Comment by mtmail** [comment]
Spelling correction is covered in https://github.com/osm-search/Nominatim/issues/759
