### ISSUE TITLE
Incoherent postal codes results on different times of the day

### ISSUE THREAD

**Issue by bxl-forever** [osm-search/Nominatim#3031]
I live in a city where most postal codes are obtained through boundary=postal_code areas.

We recently found an issue (https://community.openstreetmap.org/t/inconsistent-results-for-searches-on-postal-code-areas-data-problem-or-nominatim-issue/97618) that was solved by importing those areas even when they do not have a name (https://github.com/osm-search/Nominatim/pull/3021).

Here is another issue: When doing reverse geocoding through osm.org, the result will sometimes give the correct postcode and sometimes give another postcode.  Here is an example for a location: the correct postal code is 1050 (obtained through the postal_code relation).  One query gives a wrong answer (https://i.imgur.com/xTpFPlz.png) and later that day the answer is correct (https://i.imgur.com/n63tYet.png).  The next day, postal code is incorrect again, and so on, despite OSM data was untouched.

I also reproduced the problem by querying the same address through openstreetmap.org and through nominatim.openstreetmap.org at the same time, and obtained different results. (https://i.imgur.com/4H7Puyk.png)  This suggests that osm.org is querying different—some possibly outdated—Nominatim servers.

What can we do here?

**Comment by mtmail** [comment]
To add more detail:

https://nominatim.openstreetmap.org/ui/reverse.html?lat=50.83958&lon=4.37305&zoom=18
"9, Place du Luxembourg - Luxemburgplein, Leopold Quarter, Ixelles - Elsene, Brussels-Capital, 1047, Belgium"

openstreetmap.org currently uses 4 Nominatim servers. Server `dulcy` returns 1050, the other 3 return 1047.

**Comment by lonvia** [comment]
I've only reinstated the postcode boundaries after the import fix, I haven't reindexed the full data affected by the missing postcodes. That will take too long.

So, sorry, this is a won't fix.

**Comment by bxl-forever** [comment]
Okay, I understand the problem.  I suppose it will solve itself naturally after some time, right.
