### ISSUE TITLE
`Община Стара Загора` does not return boundary relation

### ISSUE THREAD

**Issue by Dimitar5555** [osm-search/Nominatim#3039]
## What did you search for?
`Община Стара Загора`
https://www.openstreetmap.org/search?query=Община+Стара+Загора

## What result did you get?
Mostly townhalls in that region
## What result did you expect?
The municipality's boundary relation.

**When the result missing completely:**
https://www.openstreetmap.org/relation/1947830

## Further details

The municipality's relation has `name:prefix` for the word `Община`.

**Comment by lonvia** [comment]
That's basically a category search. See #2944 for plans on how to do that.

Closing here as duplicate.
