### ISSUE TITLE
319 Irwin Pl, Erie, CO 80516 is labeled as 319 Irwin court

### ISSUE THREAD

**Issue by mikehancoski** [osm-search/Nominatim#3051]
the data of this address is incorrect 319 Irwin court, Erie, CO 80516 does not exist

https://www.google.com/maps/@40.0378525,-105.0802505,3a,75y,5.17h,85.92t/data=!3m7!1e1!3m5!1scZlaueRhAOg-qoo9Nx_zqQ!2e0!6shttps:%2F%2Fstreetviewpixels-pa.googleapis.com%2Fv1%2Fthumbnail%3Fpanoid%3DcZlaueRhAOg-qoo9Nx_zqQ%26cb_client%3Dmaps_sv.tactile.gps%26w%3D203%26h%3D100%26yaw%3D179.07622%26pitch%3D0%26thumbfov%3D100!7i13312!8i6656
## What did you search for?

https://nominatim.openstreetmap.org/search?format=json&q=319%20Irwin%20Pl+CO+80516&viewbox=37,41,25,32

Results in a new york address 

https://nominatim.openstreetmap.org/search?format=json&q=319%20Irwin%20court+CO+80516&viewbox=37,41,25,32

results is the correct address except irwin place does not exist

## What result did you get?
[{"place_id":319587166,"licence":"Data © OpenStreetMap contributors, ODbL 1.0. https://osm.org/copyright","osm_type":"way","osm_id":12287079,"boundingbox":["43.025901528736","43.026001528736","-78.819468494253","-78.819368494253"],"lat":"43.02595152873563","lon":"-78.81941849425287","display_name":"319, Irwin Place, Town of Amherst, Erie County, New York, 14228, United States","class":"place","type":"house","importance":0.1225}]

## What result did you expect?
[{"place_id":312745731,"licence":"Data © OpenStreetMap contributors, ODbL 1.0. https://osm.org/copyright","osm_type":"way","osm_id":17017211,"boundingbox":["40.038557547049","40.038657547049","-105.07978441407","-105.07968441407"],"lat":"40.03860754704923","lon":"-105.07973441406958","display_name":"319, Irwin Court, Erie, Boulder County, Colorado, 80516, United States","class":"place","type":"house","importance":0.23249999999999993},{"place_id":333211530,"licence":"Data © OpenStreetMap contributors, ODbL 1.0. https://osm.org/copyright","osm_type":"way","osm_id":15993287,"boundingbox":["40.76160870443","40.76170870443","-95.369676836562","-95.369576836562"],"lat":"40.76165870443048","lon":"-95.36962683656184","display_name":"319, Irwin Court, Shenandoah, Page County, Iowa, 51601, United States","class":"place","type":"house","importance":0.1225}]

that is the correct location but "court" does not exist

**When the result in the right place and just named wrongly:** 

319 Irwin Pl, Erie, CO 80516 = CORRECT NAME
319 Irwin Court, Erie, CO 80516 = Name on map

## Further details

please update  Irwin Court to  Irwin place

If you google t you can see the street view it is in fact Place

**Comment by mtmail** [comment]
It's not allowed to copy data from licensed sources (like Google Maps) into OpenStreetMap.
You seem to have local knowledge of that area though. You can go to https://www.openstreetmap.org/way/17017211 and click the 'Edit' button to make the change. It will be reflected in the Nominatim results after a couple of minutes. Thanks a lot. Happy mapping.
