### ISSUE TITLE
Adding "NASA" in search term results in no results found

### ISSUE THREAD

**Issue by Caseyb87** [osm-search/Nominatim#3059]
## What did you search for?

NASA Goddard Space Flight Centre

https://nominatim.openstreetmap.org/ui/search.html?q=NASA+Goddard+Space+Flight+Centre

## What result did you get?

No search results found

## What result did you expect?

**When the result missing completely:**

https://www.openstreetmap.org/relation/4237285
https://nominatim.openstreetmap.org/ui/details.html?osmtype=R&osmid=4237285&class=amenity

## Further details

The relation is actually named "Goddard Space Flight Centre" in OSM. When searching nominatim just for this, it unsurprisingly [finds it](https://nominatim.openstreetmap.org/ui/search.html?q=Goddard+Space+Flight+Center). 

It seems like the addition of "NASA" to the search term prevents nominatim from finding the object in OSM - which seems a bit odd. NASA is in the operator value (although it is slightly oddly tagged as ``operator=United States NASA``).

Edit to add: it doesn't matter where in the search string "NASA" is added, or whether it's uppercase or lowercase. The presence at all ends up with no results.

**Comment by lonvia** [comment]
Nominatim does require that all words in the search query appear in the search term, see #145. As you noted, the term 'NASA' is missing in the OSM data in the names.

There are no plans to use the operator, mostly because it's use in OSM is rather varied and it is hard to predict if it is useful for search or not. We used to have it indexed and it caused more harm than good.

So closing as data issue/duplicate/not planned.

**Comment by Caseyb87** [comment]
Oof. I didn't realise this was such a major limitation of nominatim. 

If I add some term that includes "NASA" in the alt_name field (e.g. NASA GSFC) would that then result in a successful search? Or does it have to be an exact match in every "name" field?

**Comment by otbutz** [comment]
Only if the tags make sense. [Tagging for the renderer](https://wiki.openstreetmap.org/wiki/Tagging_for_the_renderer) or any other specific software is frowned upon by the OSM community.

**Comment by Caseyb87** [comment]
> Only if the tags make sense. [Tagging for the renderer](https://wiki.openstreetmap.org/wiki/Tagging_for_the_renderer) or any other specific software is frowned upon by the OSM community.

Yep, of course. Yes, it would make sense in this example. The place is often referred to as NASA Goddard and GSFC is a widely used acronym for it.
