### ISSUE TITLE
Partial search with 3 characters is not working with bound box

### ISSUE THREAD

**Issue by sarojsh1** [osm-search/Nominatim#3060]
## What did you search for?
Searched for "min" with bound box. URL is below

https://nominatim.openstreetmap.org/ui/search.html?q=min&viewbox=-105.22727%2C50.07920%2C-74.02610%2C40.61503&bounded=1

## What result did you get?

No search results found

## What result did you expect?
Minnesota, Minneapolis etc. which matches the three characters searched.

**Comment by mtmail** [comment]
Nominatim doesn’t support partial matches. Adding bounding box makes no difference here.

For a type-ahead / search-as-you-type / partial match geocoding solution have a look at https://github.com/komoot/photon

**Comment by sarojsh1** [comment]
Thank you **mtmail**. I will look into your suggestion.
