### ISSUE TITLE
Missing State Information for Cities in the Province of Tokyo

### ISSUE THREAD

**Issue by rocainunwired** [osm-search/Nominatim#3061]
I've noticed an issue with the address section of the results, specifically regarding the handling of state information for cities located within the province of Tokyo.

According to the OpenStreetMap, the relation ID [1543125](https://www.openstreetmap.org/relation/1543125) for Tokyo is tagged as `place:province`. However, addresses within Tokyo, the state/province information is omitted from the address section of the response, because Nominatim considers Tokyo as a City and there is already a city in the response.

For example,
https://nominatim.openstreetmap.org/reverse.php?lat=35.72518&lon=139.85444&zoom=10&format=json&accept-language=en

The response only includes "Katsushika" as the city, while leaving out "Tokyo" as the state.
Here's the link for the Details API: https://nominatim.openstreetmap.org/ui/details.html?osmtype=R&osmid=1761718&class=boundary

Considering Tokyo's administrative hierarchy and the classification provided by OpenStreetMap, it would be beneficial to include the state information for cities within the province of Tokyo in the Nominatim responses. This would provide more accurate and comprehensive location information.

**Comment by lonvia** [comment]
This is a well-known data issue. If place=city are nested then Nominatim has to make a choice for the addressdetails format in the json(v2) response. Use `geocodejson` format to get more mingled address information that works around this data issue.

**Comment by rocainunwired** [comment]
Thank you for your response and suggesting workarounds on this issue.

However, I was wondering if you could kindly provide some additional clarification. Given that Tokyo is tagged as `place:province` in OpenStreetMap, I'm curious to understand the reasoning behind Nominatim considering Tokyo as a city instead of a state/province.

**Comment by lonvia** [comment]
This is not a workaround. geocodejson is the way to go if you want address details that are globally consistent. If you need admin level information instead of address level information, then geocodejson gives you that as well.

For background, please see https://nominatim.org/2020/11/11/places-and-boundaries.html and https://www.youtube.com/watch?v=NAzljx1ewZ0
