### ISSUE TITLE
debug script which shows all OS,Postgres,Nominatim parameters

### ISSUE THREAD

**Issue by mtmail** [osm-search/Nominatim#307]
[enhancement]
It's bothersome asking users for their Nominatim version, paths, PostGIS version. It would be cool to have a script, e.g. `utils/collect_os_info.sh` which prints all information we usually need in one go and make it a requirement for bug reports to include the report. Other projects do that (I can't remember one on top of my head.)
It might print sensitive information, e.g. the postgres connection string might include a password. We need to either remove that or make the user aware.

**Comment by lonvia** [comment]
Can I bump this issue a bit? It would be really helpful to have more consistent reports from people.

**Comment by lonvia** [comment]
This is half-way done now in #2552. Help would still be welcome to integrate the code into the nominatim CLI tool. See PR for details.

**Comment by lonvia** [comment]
Implemented in #2739.
