### ISSUE TITLE
Nominatim installation 4.0.2 failed due to psycopg2.errors.UndefinedObject: data type geometry has no default operator class for access method "spgist"

### ISSUE THREAD

**Issue by MALKARAJ** [osm-search/Nominatim#3071]
Creating nominatim ... done
Attaching to nominatim
nominatim    | + trap stopServices TERM
nominatim    | + /app/config.sh
nominatim    | + id nominatim
nominatim    | + useradd -m -p very_secure_password nominatim
nominatim    | + IMPORT_FINISHED=/var/lib/postgresql/12/main/import-finished
nominatim    | + TOKENIZER_DIR=/nominatim/tokenizer
nominatim    | + '[' '!' -f /var/lib/postgresql/12/main/import-finished ']'
nominatim    | + /app/init.sh
nominatim    | + OSMFILE=/nominatim/data.osm.pbf
nominatim    | + '[' '' = true ']'
nominatim    | + '[' -f '' ']'
nominatim    | + echo 'Skipping optional Wikipedia importance import'
nominatim    | Skipping optional Wikipedia importance import
nominatim    | + '[' '' = true ']'
nominatim    | + '[' -f '' ']'
nominatim    | + echo 'Skipping optional GB postcode import'
nominatim    | Skipping optional GB postcode import
nominatim    | + '[' '' = true ']'
nominatim    | + '[' -f '' ']'
nominatim    | + echo 'Skipping optional US postcode import'
nominatim    | Skipping optional US postcode import
nominatim    | + '[' '' = true ']'
nominatim    | + '[' -f '' ']'
nominatim    | + echo 'Skipping optional Tiger addresses import'
nominatim    | Skipping optional Tiger addresses import
nominatim    | + '[' https://download.geofabrik.de/europe/monaco-latest.osm.pbf '!=' '' ']'
nominatim    | + echo Downloading OSM extract from https://download.geofabrik.de/europe/monaco-latest.osm.pbf
nominatim    | Downloading OSM extract from https://download.geofabrik.de/europe/monaco-latest.osm.pbf
nominatim    | + curl -L https://download.geofabrik.de/europe/monaco-latest.osm.pbf -C - --create-dirs -o /nominatim/data.osm.pbf
nominatim    |   % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
nominatim    |                                  Dload  Upload   Total   Spent    Left  Speed
100  484k  100  484k    0     0   349k      0  0:00:01  0:00:01 --:--:--  349k
nominatim    | + '[' '' '!=' '' ']'
nominatim    | + '[' '!' -f /var/lib/postgresql/12/main/PG_VERSION ']'
nominatim    | + sudo service postgresql start
nominatim    |  * Starting PostgreSQL 12 database server
nominatim    |    ...done.
nominatim    | + sudo -E -u postgres psql postgres -tAc 'SELECT 1 FROM pg_roles WHERE rolname='\''nominatim'\'''
nominatim    | + grep -q 1
nominatim    | + sudo -E -u postgres psql postgres -tAc 'SELECT 1 FROM pg_roles WHERE rolname='\''www-data'\'''
nominatim    | + grep -q 1
nominatim    | + sudo -E -u postgres psql postgres -tAc 'ALTER USER nominatim WITH ENCRYPTED PASSWORD '\''very_secure_password'\'''
nominatim    | ALTER ROLE
nominatim    | + sudo -E -u postgres psql postgres -tAc 'ALTER USER "www-data" WITH ENCRYPTED PASSWORD '\''very_secure_password'\'''
nominatim    | ALTER ROLE
nominatim    | + sudo -E -u postgres psql postgres -c 'DROP DATABASE IF EXISTS nominatim'
nominatim    | DROP DATABASE
nominatim    | + chown -R nominatim:nominatim /nominatim
nominatim    | + cd /nominatim
nominatim    | + sudo -E -u nominatim nominatim import --osm-file /nominatim/data.osm.pbf --threads 16
nominatim    | 2023-05-25 13:09:55: Using project directory: /nominatim
nominatim    | 2023-05-25 13:09:55: Creating database
nominatim    | 2023-05-25 13:09:56: Setting up country tables
nominatim    | 2023-05-25 13:09:59: Importing OSM data file
nominatim    | 2023-05-25 13:09:59  osm2pgsql version 1.5.1
nominatim    | 2023-05-25 13:09:59  Database version: 10.3
nominatim    | 2023-05-25 13:09:59  PostGIS version: 3.2
nominatim    | 2023-05-25 13:09:59  Parsing gazetteer style file '/usr/local/etc/nominatim/import-full.style'.
nominatim    | NOTICE:  table "place" does not exist, skipping
2023-05-25 13:10:00  Reading input files done in 1s.                                      
nominatim    | 2023-05-25 13:10:00    Processed 28254 nodes in 0s - 28k/s
nominatim    | 2023-05-25 13:10:00    Processed 4555 ways in 0s - 5k/s
nominatim    | 2023-05-25 13:10:00    Processed 276 relations in 1s - 276/s
nominatim    | 2023-05-25 13:10:00  Done postprocessing on table 'planet_osm_nodes' in 0s
nominatim    | 2023-05-25 13:10:00  Done postprocessing on table 'planet_osm_ways' in 0s
nominatim    | 2023-05-25 13:10:00  Done postprocessing on table 'planet_osm_rels' in 0s
nominatim    | 2023-05-25 13:10:00  osm2pgsql took 1s overall.
nominatim    | 2023-05-25 13:10:00: Create functions (1st pass)
nominatim    | 2023-05-25 13:10:00: Create tables
nominatim    | Traceback (most recent call last):
nominatim    |   File "/usr/local/bin/nominatim", line 11, in <module>
nominatim    |     exit(cli.nominatim(module_dir='/usr/local/lib/nominatim/module',
nominatim    |   File "/usr/local/lib/nominatim/lib-python/nominatim/cli.py", line 235, in nominatim
nominatim    |     return parser.run(**kwargs)
nominatim    |   File "/usr/local/lib/nominatim/lib-python/nominatim/cli.py", line 96, in run
nominatim    |     return args.command.run(args)
nominatim    |   File "/usr/local/lib/nominatim/lib-python/nominatim/clicmd/setup.py", line 82, in run
nominatim    |     SetupAll._setup_tables(args.config, args.reverse_only)
nominatim    |   File "/usr/local/lib/nominatim/lib-python/nominatim/clicmd/setup.py", line 151, in _setup_tables
nominatim    |     database_import.create_tables(conn, config, reverse_only=reverse_only)
nominatim    |   File "/usr/local/lib/nominatim/lib-python/nominatim/tools/database_import.py", line 122, in create_tables
nominatim    |     sql.run_sql_file(conn, 'tables.sql')
nominatim    |   File "/usr/local/lib/nominatim/lib-python/nominatim/db/sql_preprocessor.py", line 88, in run_sql_file
nominatim    |     cur.execute(sql)
nominatim    |   File "/usr/local/lib/nominatim/lib-python/nominatim/db/connection.py", line 27, in execute
nominatim    |     super().execute(query, args)
nominatim    |   File "/usr/lib/python3/dist-packages/psycopg2/extras.py", line 142, in execute
nominatim    |     return super(DictCursor, self).execute(query, vars)
nominatim    | psycopg2.errors.UndefinedObject: data type geometry has no default operator class for access method "spgist"
nominatim    | HINT:  You must specify an operator class for the index or define a default operator class for the data type.
nominatim    | 

kindly let us know why it is failing

**Comment by MALKARAJ** [comment]
NOMINATIM VERSION 4.0.2
POSTGIS VERION 3.2.0
POSTGRES VERSION 10.3

**Comment by mtmail** [comment]
> nominatim | * Starting PostgreSQL 12 database server

then later Nominatim during installation checks the database version:

>  nominatim | 2023-05-25 13:09:59 Database version: 10.3

I'd say Nominatim got compiles against postgresql 12 libraries but you connect to an older postgresql database version.

There is no Nominatim version 4.0.2 (https://github.com/osm-search/Nominatim/releases) Do you mean a different version?

**Comment by MALKARAJ** [comment]
i am using nominatim docker version  so in that they are internally using nominatim 4.0.2

**Comment by mtmail** [comment]
Try the lastest Docker image. If it’s still installing the old 4.0.2 Nomination version then contact the maintainer of that Docker image.

**Comment by mtmail** [comment]
Postgis 2.4.

Note that current versions of Nominatim don't work well with Postgresql 10/PostGIS 2.4

https://nominatim.org/release-docs/develop/admin/Installation/ "For larger installations you must have PostgreSQL 11+ and PostGIS 3+ otherwise import and queries will be slow to the point of being unusable. Query performance has marked improvements with PostgreSQL 13+ and PostGIS 3.2+."
