### ISSUE TITLE
Local instance requires hard format of search queries

### ISSUE THREAD

**Issue by nikitenich** [osm-search/Nominatim#3074]
## What did you search for?
`Смоленск Кирова 32`
`Смоленск, Кирова 32`

https://nominatim.openstreetmap.org/ui/search.html?q=%D0%A1%D0%BC%D0%BE%D0%BB%D0%B5%D0%BD%D1%81%D0%BA+%D0%9A%D0%B8%D1%80%D0%BE%D0%B2%D0%B0+32%D0%B0

## What result did you get?
http://localhost:8100/search?format=json&q=Смоленск Кирова 32 - got empty array, while https://nominatim.openstreetmap.org/search?format=json&q=Смоленск Кирова 32 return result.

But if add comma between city and street (`Смоленск` and `Кирова`), local instance return result! The presence of a space does not affect the results at nominatim.openstreetmap.org.

## What result did you expect?
Expected same result as nominatim.openstreetmap.org provides.

## Further details
I'm using [nominatim-docker](https://github.com/mediagis/nominatim-docker/tree/master/4.2) image with [russia-latest.osm.pbf](https://download.geofabrik.de/russia.html) OSM data.
`IMPORT_STYLE` is set to `address`.

Debug logs:
* For a local `Смоленск Кирова 32` query (empty result): https://pastebin.com/Zhi72BbB
* For a local `Смоленск, Кирова 32` query (have result): https://pastebin.com/gbtbLAU4
* https://nominatim.openstreetmap.org/search?format=json&q=%D0%A1%D0%BC%D0%BE%D0%BB%D0%B5%D0%BD%D1%81%D0%BA%20%D0%9A%D0%B8%D1%80%D0%BE%D0%B2%D0%B0%2032%D0%B0&debug=1
* https://nominatim.openstreetmap.org/search?format=json&q=%D0%A1%D0%BC%D0%BE%D0%BB%D0%B5%D0%BD%D1%81%D0%BA,%20%D0%9A%D0%B8%D1%80%D0%BE%D0%B2%D0%B0%2032&debug=1

If its a configuration problem could you help with it? Thanks.

**Comment by mtmail** [comment]
nominatim.openstreetmap.org uses unreleased software (github master branch). You can try installing the unreleased software or wait for the next version of Nominatim to be released (there's no timeline yet).

**Comment by nikitenich** [comment]
@mtmail Okay, I'll try it. Thanks for answer!

**Comment by nikitenich** [comment]
I've build [docker image with master sources](https://github.com/mediagis/nominatim-docker/compare/master...nikitenich:nominatim-docker:master) and this didn't affect the results of geocoding.
Maybe required re-import geodata related actions?

**Comment by mtmail** [comment]
Most likely.
I forgot that this PR https://github.com/osm-search/Nominatim/pull/3067 is not live yet on nominatim.osm.org

**Comment by nikitenich** [comment]
So the problem is that on nominatim.osm.org everything works as expected for the addresses I wrote when opening the issue. That said, there is a problem with both the docker image 4.2 and the image with master branch.  It is indicated that the pull request you specified is already in the master and generally does not affect the described problem

**Comment by lonvia** [comment]
Problem of search for partial street names. This is essentially fixed in #3067. So closing here. Note that there is no ETA yet, when the new Python code will go live on osm.org or when there will be a release.

The fact that the example works on osm.org is accidental. It is not possible to run a local version that always returns exactly the same results due to the way we update data and software for our production servers.
