### ISSUE TITLE
Cannot find District 5, HCMC

### ISSUE THREAD

**Issue by fextivity** [osm-search/Nominatim#3077]
## What did you search for?

District 5, Ho Chi Minh City, Vietnam
https://nominatim.openstreetmap.org/ui/search.html?county=District+5&state=Ho+Chi+Minh+City&country=Vietnam

## What result did you get?

No search results found.

## What result did you expect?

A boundary box and information for District 5. 

**When the result missing completely:**

https://www.openstreetmap.org/relation/3820432

**Comment by mtmail** [comment]
That works again. The relation had type=boundary but was missing boundary=administrative
