### ISSUE TITLE
Address contains two suburbs

### ISSUE THREAD

**Issue by paganella31** [osm-search/Nominatim#3078]
When looking up for an address in the old town part of Trento ("centro storico" in italian), two suburbs are returned ("bolghera" and "centro storico"). For some reason, "bolghera" is placed in the first place, despite its distance from the old town streets.

## What did you search for?

This is the output for Via Malpaga in Trento: https://nominatim.openstreetmap.org/ui/details.html?osmtype=W&osmid=23763869&class=highway
The street is the closest to the "Centro storico" suburb node

## What result did you get?

The returned address is "Via Malpaga, Bolghera, Centro storico, Trento"

## What result did you expect?

I would expect just one suburb to be returned, so the correct address should be "Via Malpaga, Centro storico, Trento"

## Further details

Both suburbs are mapped as nodes. I see that "Bolghera" has a wikidata tag, while "Centro storico" doesn't.

Another difference is that the first suburb is part of an administrative boundary of level 10 (but it doesn't play any role in the relation), while the second is only contained within the city boundary. This is actually something that would need to be improved in the map, since those level 10 boundaries are currently present only in the southern half of the city. Maybe this is the issue: could it be that nodes inside an administrative boundaries are given an higher ranking than others?

**Comment by mtmail** [comment]
Having all suburbs as relations would be best.

If all are nodes, then Nominatim uses the closest (by distance). Here Bolghera and Centro storico have different address ranks though.

> since those level 10 boundaries are currently present only in the southern half of the city. Maybe this is the issue: could it be that nodes inside an administrative boundaries are given an higher ranking than others?

Map: https://overpass-turbo.eu/s/1vXd

I think that's why Bolgera has address rank 22, it's inside a admin_level=10 boundary (Oltrefersina, https://www.openstreetmap.org/relation/11889360) while the other have address rank 20.

**Comment by lonvia** [comment]
The problem is indeed the missing level 10 boundaries. I'd prefer to file this under 'data issue'. It is rather unusual to have such incomplete coverage of boundaries of the same level and taking it into account would come at a relatively high cost on the import side.

**Comment by paganella31** [comment]
Thanks for the explanation, I will get in contact with the community so to add the missing boundaries.
As it is indeed a map issue, I would consider the issue solved.
