### ISSUE TITLE
psycopg2.OperationalError: terminating connection due to idle-in-transaction timeout

### ISSUE THREAD

**Issue by MALKARAJ** [osm-search/Nominatim#3082]
Hi team getting this error continuously kindly check and let us know please

![error in nominatim](https://github.com/osm-search/Nominatim/assets/62066377/41bb47a2-f3e7-41c7-90aa-69a920b21e43)

Nominatim version 4.2.3
postgres 10.3
postgis: 2.5.9

**Comment by lonvia** [comment]
This report is missing a lot of information. Please use the issue template for reporting problems with the software and fill in the required information. Closing for now.

**Comment by MALKARAJ** [comment]
sorry for less information
