### ISSUE TITLE
ValueError: unexpected '{' in field name

### ISSUE THREAD

**Issue by ErwanTouba** [osm-search/Nominatim#3084]
**Describe the bug**
During execution of `init.sh` script, the following nominatim command is run

```bash
sudo -E -u nominatim nominatim import --osm-file $OSMFILE --threads $THREADS
```

after some work, i get an error `ValueError: unexpected '{' in field name` with the following stacktrace
```bash
# last logs frmo nominatim before the error
2023-06-18 12:20:01: Recompute word counts
2023-06-18 12:20:04: Setup website at /nominatim/website
.......................................................................................................

Traceback (most recent call last):
  File "/usr/local/bin/nominatim", line 14, in <module>
    exit(cli.nominatim(module_dir='/usr/local/lib/nominatim/module',
  File "/usr/local/lib/nominatim/lib-python/nominatim/cli.py", line 264, in nominatim
    return parser.run(**kwargs)
  File "/usr/local/lib/nominatim/lib-python/nominatim/cli.py", line 126, in run
    return args.command.run(args)
  File "/usr/local/lib/nominatim/lib-python/nominatim/clicmd/setup.py", line 154, in run
    refresh.setup_website(webdir, args.config, conn)
  File "/usr/local/lib/nominatim/lib-python/nominatim/tools/refresh.py", line 242, in setup_website
    (basedir / script).write_text(template.format(script), 'utf-8')
ValueError: unexpected '{' in field name
```

**To Reproduce**
i Believe the error is occured because the `password` field of the `NOMINATIM_DATABASE_DSN` value contained the character `{`
when i changed the password in `NOMINATIM_DATABASE_DSN` string without `{` the error was gone.

**Software Environment (please complete the following information):**
- Nominatim version: 4.2.3
- Postgresql version: 14
- Postgis version: 3.3
- OS: Ubuntu 22.04.2 LTS

**Hardware Configuration (please complete the following information):**
- RAM: 2
- number of CPUs: 2
- type and size of disks: 20Go virtual

**Postgresql Configuration:**

**Nominatim Configuration:**

**Additional context**

I'm working with a custom built docker image based on mediagis/nominatim-docker/

**Comment by lonvia** [comment]
Your assessment is correct. There is a bug when a curly brace is present in the password. Fix is on its way but I won't make a new release for that as there is a fairly simple workaround for the problem.
