### ISSUE TITLE
502 Bad Gateway response

### ISSUE THREAD

**Issue by gboeing** [osm-search/Nominatim#3098]
## What did you search for?

Searching for anything via the API is generating `502 Bad Gateway` on every request over the past 5 hours. The same error can be seen here: https://nominatim.openstreetmap.org/ui/status.html

> Error fetching data from /status.php?format=json (Bad Gateway)

## What result did you get?

502 Bad Gateway

## What result did you expect?

HTTP 200 OK response codes

## Further details

I have tried from different machines and IP addresses, just to be safe. Same result everywhere.

**Comment by mtmail** [comment]
nominatim.openstreetmap.org is using 4 servers, I see 1 (stormfly-04) is affected since 6 hours.

![image](https://github.com/osm-search/Nominatim/assets/3727288/367482b6-036c-43ae-9bbd-cbaa951448b1)

**Comment by gboeing** [comment]
Thanks for checking @mtmail. [OSMnx](https://github.com/gboeing/osmnx/) makes requests to nominatim.openstreetmap.org and our CI has been failing for several hours. Same thing when I run the CI test suite locally on different machines. Perhaps that means all of our requests to nominatim.openstreetmap.org are resolving to only the stormfly-04 server? But this seems odd to be happening uniformly across the various different machines.

**Comment by gboeing** [comment]
If I explicitly use https://dulcy.openstreetmap.org/ it is working. It does appear to be a stormfly-04 server problem, but it seems that my local machines and the Github CI all keep resolving to that one server when requesting nominatim.openstreetmap.org today.

**Comment by mtmail** [comment]
I can only observe myself, I don't have any admin access to the configuration. I think https://github.com/openstreetmap/operations (https://operations.osmfoundation.org/) can change the load balancing.

**Comment by gboeing** [comment]
Appears to be up and working again normally, so I shall close this.
