### ISSUE TITLE
Lat / Long Points Return Incorrect City Name 

### ISSUE THREAD

**Issue by cdroulias** [osm-search/Nominatim#3113]
## What did you search for?  
lat / long points: 34.00897, -84.028329
https://nominatim.openstreetmap.org/ui/search.html?q=34.00897%2C+-84.028329

## What result did you get? 
Cove Ridge Court, Deerwood, Georgia 30024
## What result did you expect? 
2107 Cove Ridge Ct. in Suwanee, GA 30024
**When the result in the right place and just named wrongly:** 

**When the result missing completely:**

**Comment by lonvia** [comment]
This is a general problem of US postal cities which do not coincide with administrative boundaries, already covered in #1120. Closing here.
