### ISSUE TITLE
Lat / Long Points Return Incorrect Address #2

### ISSUE THREAD

**Issue by cdroulias** [osm-search/Nominatim#3114]
## What did you search for?
 lat / long 34.169949, -83.984448
 https://nominatim.openstreetmap.org/ui/search.html?q=34.169949%2C+-83.984448

## What result did you get?
Yacht Club Rd, Johnson, GA

## What result did you expect?
Yacht Club Rd. in Flowery Branch, GA

**When the result in the right place and just named wrongly:** 

Yacht Club Rd. in Flowery Branch, GA

**Comment by mtmail** [comment]
Flowery Branch has precise borders in OpenStreetMap data. Too precise, or rather not what people living in the area would see as the expected borders

https://www.openstreetmap.org/relation/119735
![image](https://github.com/osm-search/Nominatim/assets/3727288/64edfa26-b8a6-42c9-9f65-faa2a67ce902)

**Comment by cdroulias** [comment]
Hello, thank you for this response. When using the Nominatim OSRM for these lat / long points we are still not sure how the name "Johnson" is being provided. 

As there is no "Johnson" city in Georgia. There is a "Johnson County" but it is 3 hours away from this location. 
<img width="432" alt="Screenshot 2023-07-19 at 8 52 11 AM" src="https://github.com/osm-search/Nominatim/assets/138628640/2610be38-23e4-44df-b111-723525bb1975">

It seems the city name that should be provided would be one of the surrounding cities of Flowery Branch
<img width="570" alt="Screenshot 2023-07-19 at 8 56 41 AM" src="https://github.com/osm-search/Nominatim/assets/138628640/a00c9aac-0c73-4b59-9619-22669cc0779b">


Could you kindly investigate this on your end? 

Thank you

**Comment by lonvia** [comment]
Johnson is the name of the suburb: https://www.openstreetmap.org/node/154055700

This is a general problem of US postal cities which do not coincide with administrative boundaries, already covered in #1120. Closing here.
