### ISSUE TITLE
Cors error suddunly came.

### ISSUE THREAD

**Issue by CoderAravind** [osm-search/Nominatim#3129]
## What did you search for?

Access to XMLHttpRequest at 'https://nominatim.openstreetmap.org/reverse?lat=11.039843&lon=77.0028459&format=json' from origin 'http://localhost' has been blocked by CORS policy: Response to preflight request doesn't pass access control check: It does not have HTTP ok status.

It was working fine suddenly this error occurred???

Access to XMLHttpRequest at 'https://nominatim.openstreetmap.org/reverse?lat=11.039843&lon=77.0028459&format=json' from origin 'http://localhost' has been blocked by CORS policy: Response to preflight request doesn't pass access control check: It does not have HTTP ok status.

It was working fine suddenly this error occurred???

## What result did you expect?

need normal working as before

**When the result missing completely:**

**Comment by mtmail** [comment]
You're probably automatically blocked, try again in 24 hours. https://operations.osmfoundation.org/policies/nominatim/

**Comment by lonvia** [comment]
Or maybe not. Still looking, what is going wrong.

**Comment by lonvia** [comment]
It should be sending enough headers now to get the preflight through. Let me know if this fixes things for you.
