### ISSUE TITLE
Problem with endpoint for reverse geocoding

### ISSUE THREAD

**Issue by Kalihackz** [osm-search/Nominatim#3131]
## What did you search for?

https://nominatim.openstreetmap.org/reverse?format=json&addressdetails=1&extratags=1&osm_id=165473&osm_type=R&polygon_geojson=1&namedetails=1

## What result did you get?

Internal Server Error

## What result did you expect?

Previously, providing osm_id and osm_type , it used to give response which contained all details like boundingbox, geojsondata and other important data.

The country I am trying to find is in openstreetmap : https://www.openstreetmap.org/relation/165473#map=7/38.574/-116.971

## Further details

I know the reverse way of searching is now only with lat and lon instead of osm_id and osm_type. But even if I use the /lookup endpoint to get lat and lon using the osm_id and osm_type , that lat and lon that is coming points to a specific county or city instead of a state or country as the display_name contains county name specifically not the general state name

**Comment by lonvia** [comment]
The `osm_type` and `osm_id` parameters have been deprecated for a very long time now and have now been removed on the public instance following the switch to the Python frontend. Please use the [lookup endpoint](https://nominatim.org/release-docs/develop/api/Lookup/).
