### ISSUE TITLE
/search/?q=query URL format no longer supported (should be /search?q=query)

### ISSUE THREAD

**Issue by scbhooshan** [osm-search/Nominatim#3134]
## What did you search for?

bangalore

https://nominatim.openstreetmap.org/search/?q=banga&format=json&addressdetails=1&limit=3&countrycodes=in%2Cus&accept-language=en

## What result did you get?

<error>
<title>404 Not Found</title>
</error>

## What result did you expect?

**When the result in the right place and just named wrongly:** 

[
{
"place_id": 297963002,
"licence": "Data © OpenStreetMap contributors, ODbL 1.0. http://osm.org/copyright",
"osm_type": "relation",
"osm_id": 1960177,
"lat": "22.9964948",
"lon": "87.6855882",
"class": "boundary",
"type": "administrative",
"place_rank": 8,
"importance": 0.6474964049356986,
"addresstype": "state",
"name": "West Bengal",
"display_name": "West Bengal, India",
"address": {
"state": "West Bengal",
"ISO3166-2-lvl4": "IN-WB",
"country": "India",
"country_code": "in"
},
"boundingbox": [
"21.5473014",
"27.2212039",
"85.8200883",
"89.8725414"
]
}
]
// 20230802132021
// https://nominatim.openstreetmap.org/search?q=banga&format=json&addressdetails=1&limit=3&countrycodes=in%2Cus&accept-language=en
​
[
  {
    "place_id": 297963002,
    "licence": "Data © OpenStreetMap contributors, ODbL 1.0. http://osm.org/copyright",
    "osm_type": "relation",
    "osm_id": 1960177,
    "lat": "22.9964948",
    "lon": "87.6855882",
    "class": "boundary",
    "type": "administrative",
    "place_rank": 8,
    "importance": 0.6474964049356986,
    "addresstype": "state",
    "name": "West Bengal",
    "display_name": "West Bengal, India",
    "address": {
      "state": "West Bengal",
      "ISO3166-2-lvl4": "IN-WB",
      "country": "India",
      "country_code": "in"
    },
    "boundingbox": [
      "21.5473014",
      "27.2212039",
      "85.8200883",
      "89.8725414"
    ]
  }
]

**When the result missing completely:**

**Comment by lonvia** [comment]
I see that we have the old slash syntax still in the docs: https://nominatim.org/release-docs/develop/api/Search/#json-with-svg-polygon That definitely needs to go away.

**Comment by lonvia** [comment]
Lovely. Opened an issue [there](https://github.com/jonataswalker/ol-geocoder/issues/267) but this project looks to be mostly dead.

**Comment by lonvia** [comment]
The new implementation is only live on one of our servers right now. Depending on the location of your server you get the new or old behaviour. I see how this can be annoying when the test environment happily keeps working. Sorry about that. I'll see to it that we quickly disable the URL pattern on all servers.

I've decided against monkey-patching to support the old style URL because eventually it would only move the problem two years down the road for everybody.

**Comment by deryckchan** [comment]
I've encountered the same issue today, and after some debugging I landed on the "API no longer accessible via this URL" error page that links to this thread, thank you. As @lonvia pointed out above, the "incorrect" `search/` syntax was used in documentation examples, so I think this breaking change has widespread impact.

**Comment by rbyjoswald** [comment]
> As @lonvia pointed out above, the "incorrect" `search/` syntax was used in documentation examples, so I think this breaking change has widespread impact.

Encountered the same today. Any chance for a rollback with another grace-period (say 30 days?!)?

**Comment by lorello** [comment]
we are in the same conditions: haundred of websites to patch because we are using the wrong but well documented way to call your API. @Ionvia A backward compatible solution would be very appreciated, even for just a couple of weeks.

**Comment by richterb** [comment]
Same here, a month-long grace period would be enough to properly update all our code to the new proper URL and would be greatly appreciated. The summer period doesn't help with updates and deployments either.

**Comment by mtmail** [comment]
> The new implementation is only live on one of our servers right now.

That server was temporarily taken down by OpenStreetMap operations team 24h ago so the new implementions isn't live any more.

**Comment by misibacsi** [comment]
I still encounter this bug today and I do not know how long I should wait until someone notices this and correct the code. 
Or what can I do as a simple OSM user?
I receive no error message just no result from Nominatim search.
I reported this 5 days ago [https://github.com/facebook/Rapid/issues/1006](url)

**Comment by mtmail** [comment]
@misibacsi Looks like the Rapideditor team didn’t implement a change yet. You need to contact them again.

**Comment by alexdezi** [comment]
Is there any way at all to have the compatibility with the /? Some third party solutions basically stopped worked, because the use the well documented (but wrong) way of calling the API.

**Comment by mtmail** [comment]
@alexdezi Can you list or link those third party solutions which are not working for you?

**Comment by alexdezi** [comment]
I am for example currently working with a Wordpress theme that has integrated that API query using the /. Funny enough it's a few sites with the same purpose, on some I managed to get the location query done on time, and on some it suddenly stopped working. After a lot of debugging I realized that the query is implemented incorrectly despite the documentations showing it like that.

**Comment by MuhammadNaeem42** [comment]
please anyone guide me how i change old URL to New URL i am running OSRM in docker 

![image](https://github.com/osm-search/Nominatim/assets/106573678/8c1be9b6-d54f-484a-a40b-9f03302451aa)

**Comment by mtmail** [comment]
@MuhammadNaeem42 You need to update the `leaflet-control-geocoder` dependency. See https://github.com/Project-OSRM/osrm-frontend/pull/370 For follow-up questions contact the osrm-frontend repository maintainers.

**Comment by Eolia** [comment]
The good url is:
https://nominatim.openstreetmap.org/search.php?q=banga&format=json&addressdetails=1&limit=3&countrycodes=in%2Cus&accept-language=en

Result:

**Comment by mtmail** [comment]
@Eolia That legacy URL works, but `/search` is the official URL. See the documentation at https://nominatim.org/release-docs/latest/api/Overview/
