### ISSUE TITLE
Postal code search not working

### ISSUE THREAD

**Issue by AlbertoCortina** [osm-search/Nominatim#3135]
## What did you search for?

Searching for a specific postal code for a country with the following URL:

https://nominatim.openstreetmap.org/?postalcode=1217&country=ch&format=json&limit=1

## What result did you get?

Currently, I am getting an empty response

```
[ ]
```

## What result did you expect?

I was expecting to get information about the postal code. Before, executing the same call, we were getting the following:
```
[
   {
      "place_id":299666817,
      "licence":"Data © OpenStreetMap contributors, ODbL 1.0. https://osm.org/copyright",
      "boundingbox":[
         "46.069503798157",
         "46.389503798157",
         "5.9134538552995",
         "6.2334538552995"
      ],
      "lat":"46.229503798156685",
      "lon":"6.073453855299539",
      "display_name":"Meyrin, Geneva, 1217, Switzerland",
      "class":"place",
      "type":"postcode",
      "importance":0.33499999999999996
   }
]
```

**Comment by lonvia** [comment]
Turns out that the lambda functions introduced in #3110 have some issues with caching value lists for IN expression correctly. 

Fixed in https://github.com/osm-search/Nominatim/commit/2c7e1db5f63bb1157c26764ed134986bfe74b5d3.
