### ISSUE TITLE
Return administrative relation for London, not ceremonial

### ISSUE THREAD

**Issue by RedAuburn** [osm-search/Nominatim#3140]
## What did you search for?
https://nominatim.openstreetmap.org/ui/search.html?q=london

## What result did you get?
Greater London (ceremonial bounds not including the City of London) https://www.openstreetmap.org/relation/65606
![image](https://github.com/osm-search/Nominatim/assets/26939824/d28ba0d3-e5b2-4734-950e-510e002ad126)

## What result did you expect?
Greater London (administrative bounds including City of London) https://www.openstreetmap.org/relation/175342
![image](https://github.com/osm-search/Nominatim/assets/26939824/3f73f2da-b13c-40dc-9d27-d74497e8dd24)

## Further details
related overpass turbo issue: https://github.com/tyrasd/overpass-turbo/issues/631

**Comment by mtmail** [comment]
I'd see that as duplicate or comment on https://github.com/osm-search/Nominatim/issues/2911 where a different discussion is linked. There wouldn't be a change for one city, it would need to be country-wide setting.

**Comment by lonvia** [comment]
Sorry, but this is an unsolvable data problem. Everything in the OSM data tells Nominatim that relation 65606 is meant when searching for 'London'. It has the place=city tag, the link to the London wikipedia page and the exact name you were searching for. Short of adding extra handling precisely for those two relations, there is nothing to be done on the Nominatim side to fix the problem.

You need to get in touch with the British community and have a discussion with them what 'London' means and if the tagging can be changed to conventionally include the City of London under that term.
