### ISSUE TITLE
Issues with Venice - Italy results

### ISSUE THREAD

**Issue by dimalif** [osm-search/Nominatim#3142]
Basilica di Santa Maria Gloriosa dei Frari, Venice
But actually everything is wrong for the City of Venice, half of the results show 30170 as code and that is MESTRE.

## What result did you get?

Basilica di Santa Maria Gloriosa dei Frari, Calle dei Albanesi, San Polo, Venezia-Murano-Burano, Mestre, Venice, Venezia, Veneto, **30170**, Italy

## What result did you expect?

30170 is Mestre and that is wrong.

and other example:

 ,"suburb":"Venezia-Murano-Burano","city":"Mestre","county":"Venezia","ISO3166-2-lvl6":"IT-VE","state":"Veneto","ISO3166-2-lvl4":"IT-34","postcode":"30135","country":"Italy"

Venezia-Murano-Burano are not Suburbs of Mestre. Rather Burano, Murano, and Mestre are suburbs of Venezia (Venice).

There are no counties in Italy, rather there are provinces and indeed Venezia is a Province as well. There are no States in Italy, rather there are Regions and Veneto is the correct region.

**When the result in the right place and just named wrongly:** 

**When the result missing completely:**

## Further details

Please see the Note and the reply

https://www.openstreetmap.org/note/3822083

**Comment by eurobank** [comment]
An other example:

Search for "Ca' Rezzonico, venice, italy".

OpenStreetMaps:

"Pier [Ca' Rezzonico, Fondamenta del Tragheto, Dorsoduro, Venezia-Murano-Burano, Mestre, Venice, Venezia, Veneto, 30170, Italy]

(https://www.openstreetmap.org/way/138843293)"

30170 is wrong and it is MESTRE not Venice city.

GoogleMaps:

https://www.google.com/maps/place/Ca'+Rezzonico/@45.4335404,12.3219549,17z/data=!3m1!4b1!4m6!3m5!1s0x477eb1ce51c54ad7:0xbf7bf91f51cdfd5d!8m2!3d45.4335405!4d12.3268258!16zL20vMDN5enY2?entry=ttu

Sestiere Dorsoduro, 3136, 30123 Venezia VE, Italy

Google maps correctly reports 30123

**Comment by lonvia** [comment]
The postcode comes from [the Maestre city node](https://www.openstreetmap.org/node/29997772). That gets included because it is the same level as [Venice city node](https://www.openstreetmap.org/node/64778090) within the [city relation of Venice](https://www.openstreetmap.org/relation/44741).

Or to put it differently: Nominatim is getting mixed messages of the size of Venice and weather or not it includes Maestre. The result is the bad postcode.

**Comment by dimalif** [comment]
@lonvia I'm not familiar at all with all this. I tried to find a solution for this issue since i can't use properly Openstreetmaps api within Wordpress directory plugin.

And it is not only a badcode. As i posted 

****,"suburb":"Venezia-Murano-Burano","city":"Mestre","county":"Venezia","ISO3166-2-lvl6":"IT-VE","state":"Veneto","ISO3166-2-lvl4":"IT-34","postcode":"30135","country":"Italy"

Venezia-Murano-Burano are not Suburbs of Mestre. Rather Burano, Murano, and Mestre are suburbs of Venezia (Venice).

There are no counties in Italy, rather there are provinces and indeed Venezia is a Province as well. There are no States in Italy, rather there are Regions and Veneto is the correct region.**

Who designed all that so wrong?

So is that an expected behavior? is it a bug? What shall i do next?

**Comment by dimalif** [comment]
@mtmail I apologize if my tone was not appropriate. By "who designed all that so wrong" was probably wrong worded by me (not beeing english speaking). What i ment was a so popular city like Venice how it can have such a big issue and nobody saw it by now.

Thanks for the reply.

**Comment by lonvia** [comment]
Looks like this is a general mapping issue in Italy, as it is similar to #3162.

As with the other, I'm closing in favour of #2606 which discusses a possible solution to the problem.
