### ISSUE TITLE
500 status code on lookup with polygon_geojson=1 query param

### ISSUE THREAD

**Issue by Muha113** [osm-search/Nominatim#3147]
[https://nominatim.openstreetmap.org/lookup?format=json&osm_ids=R59195&polygon_threshold=0.005&polygon_geojson=1](https://nominatim.openstreetmap.org/lookup?format=json&osm_ids=R59195&polygon_threshold=0.005&polygon_geojson=1)
returns 500 status code while
[https://nominatim.openstreetmap.org/lookup?format=json&osm_ids=R59195&polygon_threshold=0.005](https://nominatim.openstreetmap.org/lookup?format=json&osm_ids=R59195&polygon_threshold=0.005)
responds with normal data (without polygons)

may be smth changed in query params spec but everything was ok just a day ago

**Comment by lonvia** [comment]
Fix is now live.
