### ISSUE TITLE
Search fails for small Irish village

### ISSUE THREAD

**Issue by danieldegroot2** [osm-search/Nominatim#3148]
## What did you search for?

Originally on openstreetmap.org, reproduced with nominatim.openstreetmap.org

EN https://nominatim.openstreetmap.org/ui/search.html?q=Athea
GA https://nominatim.openstreetmap.org/ui/search.html?q=%C3%81th+an+tSl%C3%A9ibhe

## What result did you get?

Only the nearby mountain top is returned with the Irish Gaelic search as it's a partial match. The English search just returns the surrounding boundary and some house elsewhere.

## What result did you expect?

The result is missing completely;

For "Athea"/"Áth an tSléibhe", I expect the search results to possibly include
https://www.openstreetmap.org/node/52263467 (EN: "Athea", GA: "Áth an tSléibhe"); which as far as I can see is an exact match.

## Further details

None. Maybe because it's also a GNS node. Or maybe it just dropped out of priority.

**Comment by lonvia** [comment]
This had already been fixed in #3100. I've refreshed Athea now.
