### ISSUE TITLE
Boundingbox represented as a 'Point'

### ISSUE THREAD

**Issue by Andrzej-Krawiec** [osm-search/Nominatim#3149]
## What did you search for?

Any country ex. https://nominatim.openstreetmap.org/search.php?country=poland&format=jsonv2

## What result did you get?

```json
[{"place_id":307669234,"licence":"Data © OpenStreetMap contributors, ODbL 1.0. http://osm.org/copyright","osm_type":"relation","osm_id":49715,"lat":"52.215933","lon":"19.134422","category":"boundary","type":"administrative","place_rank":4,"importance":0.8525855477196589,"addresstype":"country","name":"Poland","display_name":"Poland","boundingbox":["52.2158830","52.2159830","19.1343720","19.1344720"]}]
```

## What result did you expect?

Correct `boundingbox` array

## Further details

`boundingbox` array should contain four distinct values, but the API response contains duplicated values (2x 52.2158830, 2x 19.1343720).

**Comment by lonvia** [comment]
The box was a real box, just rather small. In any case, it is now back to returning a box of the full country when available.
