### ISSUE TITLE
Wrong(?) result for country=ru

### ISSUE THREAD

**Issue by EduardoOliveira** [osm-search/Nominatim#3151]
## What did you search for?
https://nominatim.openstreetmap.org/search?format=json&country=ru

## What result did you get?
A list with United Kingdom as first element and Russia in second place

```
[
  {
    "place_id": 297365518,
    "licence": "Data © OpenStreetMap contributors, ODbL 1.0. http://osm.org/copyright",
    "osm_type": "relation",
    "osm_id": 62149,
    "lat": "54.7023545",
    "lon": "-3.2765753",
    "class": "boundary",
    "type": "administrative",
    "place_rank": 4,
    "importance": 0.8723780132837334,
    "addresstype": "country",
    "name": "United Kingdom",
    "display_name": "United Kingdom",
    "boundingbox": [
      "54.7023045",
      "54.7024045",
      "-3.2766253",
      "-3.2765253"
    ]
  },
  {
    "place_id": 297746125,
    "licence": "Data © OpenStreetMap contributors, ODbL 1.0. http://osm.org/copyright",
    "osm_type": "relation",
    "osm_id": 60189,
    "lat": "64.6863136",
    "lon": "97.7453061",
    "class": "boundary",
    "type": "administrative",
    "place_rank": 4,
    "importance": 0.852192362078589,
    "addresstype": "country",
    "name": "Russia",
    "display_name": "Russia",
    "boundingbox": [
      "64.6862636",
      "64.6863636",
      "97.7452561",
      "97.7453561"
    ]
  }
]
```

## What result did you expect?
A list with one element of Russia, or at least Russia as first element

**When the result in the right place and just named wrongly:** 

**When the result missing completely:**

**Comment by mtmail** [comment]
Both are returned because the French short name of United Kingdom is RU (Royaume-Uni). Are you setting any language? E.g. https://nominatim.openstreetmap.org/search?format=json&country=ru&limit=1&accept-language=en returns United Kingdom. I think without language the result ranking is random.

**Comment by lonvia** [comment]
The result ranking is per importance.

I think we need to add a special case here assuming that a two-letter country always represents a country code.

**Comment by EduardoOliveira** [comment]
The result could still be a list but that case should bump the ranking of the result.

I think that could be a nice solution

You could also create a country code specific endpoint or flag

**Comment by lonvia** [comment]
#3206 is somewhat helping with that in putting the results in a better order.

However, it presents exactly the case where it would be better to rerank against all name tags defined in the locale. This way, a french user would get both results and everybody else just Russia.
