### ISSUE TITLE
Blocked by CORS after operating for a year

### ISSUE THREAD

**Issue by sabina-brvar** [osm-search/Nominatim#3153]
## What did you search for?
https://nominatim.openstreetmap.org/reverse?format=json&lon=145.10742188&lat=-38.03078569 

Posted within my web app, it used to work with no issues, and still works when i post it in web browser. But on the app I get the error (see below)

## What result did you get?

Access to XMLHttpRequest at 'https://nominatim.openstreetmap.org/reverse?format=json&lon=145.10742188&lat=-38.03078569&zoom=5' from origin 'https://riders.bloodbikesaustralia.com.au' has been blocked by CORS policy: Request header field content-type is not allowed by Access-Control-Allow-Headers in preflight response.
main.js?v=2.1:2598  ........readyState:4  status:0
main.js?v=2.1:302     GET https://nominatim.openstreetmap.org/reverse?format=json&lon=145.10742188&lat=-38.03078569&zoom=5 net::ERR_FAILED

## What result did you expect?

**When the result in the right place and just named wrongly:** 

**When the result missing completely:**

## Further details

The web app is for volunteer organisation Bloodbikes Australia (www.bloodbikesaustralia.com.au) - without this working, we are back to using manual methods. Have we reached some kind of usage limit? Referrer would be riders.bloodbikesaustralia.com.au - if that is so, how can we get unbanned? We have no funding, we all volunteer our time and resources, to transport urgent blood and medical supplies to and from different healthare providers. But if there is some licence that I need to pay, to continue using a service, please let me know and I'll see, depending on how much it is, what i can do about it.

**Comment by lonvia** [comment]
Back to allowing all kinds of headers. Will be gradually rolled out in the next half hour or so.
