### ISSUE TITLE
Photo Apps Reverse Geocoding

### ISSUE THREAD

**Issue by clickburr** [osm-search/Nominatim#3157]
Hello,

I'm a photographer who uses 3 different apps for doing reverse geocoding from photos with GPS data. There is an issue in my home town of Chertsey, UK, which none of the app developers say they can help with, so am hoping someone here knows what's going on and if it can be fixed (and ideally fix it!).

I have to say first that I don't understand any of this so won't be able to answer any techy questions!

In the apps the data returned doesn't give the correct City, State or Country (that returns UK not England, which is debatable I guess).

Here's an example - the GPS Geodata is:

N 51° 23' 29.390" , W 0° 30' 15.600"

In the Nominatim search dialogue this returns the correct place (Guildford Street in Chertsey):

https://nominatim.openstreetmap.org/ui/details.html?osmtype=W&osmid=446907652&class=amenity

But the data pulled by the apps shows the City to be Borough Of Runnymede, and the State to be England.

Here's a couple of screen grabs of what two of the apps return (hopefully you can see them):

![Screenshot 2023-08-18 at 12 00 41](https://github.com/osm-search/Nominatim/assets/142589479/e7e2242e-a3a1-4bef-8bd6-ee1f6d0316a8)
![Screenshot 2023-08-18 at 12 00 03](https://github.com/osm-search/Nominatim/assets/142589479/27d70c74-fe0d-476e-bb3b-67c1b06a1090)

So is there anything that can be done to correct this? 

Obviously I am more than happy to test any corrections made or do other testing to help identify the issues.

Many thanks,
:DK

**Comment by clickburr** [comment]
The street name should read Guildford Street, not London street (I changed the picture for the example!).

**Comment by clickburr** [comment]
I'm sorry again, I've the wrong link in for the Nominatim search - it should be this one:

https://nominatim.openstreetmap.org/ui/details.html?osmtype=W&osmid=446907652&class=amenity

**Comment by otbutz** [comment]
The API returns `Chertsey` as the town:

![image](https://github.com/osm-search/Nominatim/assets/22315436/0e444bac-e697-4d72-b195-d7cf78a65b14)

If that is the correct location, than the app developer is most likely interpreting the result in an unexpected way.

**Comment by lonvia** [comment]
That's essentially another example of #2490. The OSM data in the UK is simply not suitable to create usable address information.

Closing here. Further discussions should go into #2490.

**Comment by mtmail** [comment]
I was on the wrong track with my assessment, it's not the coordinate format. I forgot to add the - after the conversion to decimal and the result was way off. After I added the - I didn't realize the result is only off by less than 500 meters. So the conversion and thus the apps can't be the culprit.
