### ISSUE TITLE
Reverse issue - Erice, Sicily, Italy

### ISSUE THREAD

**Issue by GianlucaRizzo92** [osm-search/Nominatim#3162]
Hello everyone,

I am writing to report an issue I have encountered with the reverse geocoding functionality in a specific area of the Sicily region in Italy. To be more precise, the issue revolves around the town of Erice. I'll do my best to provide comprehensive details, and I apologize in advance for any shortcomings in my English.

In a nutshell, I've noticed a discrepancy when using the reverse geocode feature for the coordinates corresponding to the town of Erice. When performing a search and setting the zoom level to 12, the result consistently points to the outskirts of Casa Santa. Casa Santa, with a population of over 10,000, is classified as a town. Strikingly, this behavior occurs across many points along the border of the Erice municipality.

I have verified that the municipal boundaries are accurate, and Erice is correctly labeled as a town. Additionally, the population figure for Erice surpasses that of Casa Santa. Notably, Erice is designated as an "admin_centre" within the municipality relation, implying a higher level of importance. Therefore, it should rightfully take precedence in this context.

I believe this inconsistency is affecting the accuracy of the reverse geocoding results in this area, particularly for the town of Erice. The data seems to be correctly structured, but the priority appears to be misaligned.

Thank you very much for your attention to this matter. Your support and expertise are greatly appreciated in resolving this issue and ensuring the accuracy of the reverse geocoding service in the mentioned area.

This is the link: https://nominatim.openstreetmap.org/ui/reverse.html?lat=38.03718&lon=12.58784&zoom=12

This is the link whit the XML where there isn't Erice as Town: https://nominatim.openstreetmap.org/reverse?lat=38.03718&lon=12.58784&&zoom=12

thank you kindly for the help. Best regards

**Comment by lonvia** [comment]
Essentially the same as #2606 with 'Erice' and 'Casa Santa' are both mapped as town.

Closing here as duplicate.
