### ISSUE TITLE
"Grefrath Dorfstraße" not found (highway)

### ISSUE THREAD

**Issue by pathmapper** [osm-search/Nominatim#3163]
## What did you search for?

https://nominatim.openstreetmap.org/ui/search.html?q=Grefrath+Dorfstra%C3%9Fe (Grefrath Dorfstraße)

## What result did you get?

no result

## What result did you expect?

Grefrath Dorfstraße

**When the result missing completely:**

https://www.openstreetmap.org/way/37258402

## Further details

https://nominatim.openstreetmap.org/ui/search.html?q=Grefrath returns results

**Comment by otbutz** [comment]
https://nominatim.openstreetmap.org/ui/search.html?q=Vinkrath+Dorfstra%C3%9Fe

![image](https://github.com/osm-search/Nominatim/assets/22315436/06c5c4ad-10bf-41ad-8adc-af013405efe3)

Looks correct to me.

**Comment by pathmapper** [comment]
> https://nominatim.openstreetmap.org/ui/search.html?q=Vinkrath+Dorfstra%C3%9Fe

This delivers only the bus stop, not the street intself.

Also "Vinkrath" is only a point, the administrative boundary where "Dorfstraße" is located is "Grefrath".

![grafik](https://github.com/osm-search/Nominatim/assets/20856381/8ea5489d-1de2-4072-8681-8466a5c29f77)

**Comment by pathmapper** [comment]
Thanks a lot for the fix ! 🎉
