### ISSUE TITLE
Missed updates of some addresses

### ISSUE THREAD

**Issue by mstock** [osm-search/Nominatim#3168]
The Nominatim-Data-Analyser reports errors for a few buildings in Waengi, e.g. [Chüechligasse 23a][1], saying that the parent "Chüechligasse" doesn't match the street "Chüechligass". Originally, this actually was the case, however, [I then changed the `addr:street` to "Chüechligasse"][2], but that didn't have an effect (at least on some buildings), so about two days later, I made another change to the building, but still no effect.

When searching for the address with the default settings, a ['combined' building with multiple house numbers is found][3], [when searching with disabled deduplication][4], two results are found, both pointing to the same details page, but one of them contains only one house number in the search result list. The 'Address Tags' line on the details page still mentions 'Chüechligass', but the 'Address' section doesn't. So it seems my change didn't completely make it into the Nominatim database, neither did the change from a [changeset a couple days before mine][5] where the building with an original `addr:housenumber` of `23a;23b;23c` was split into three buildings with separate house numbers.

[1]: https://www.openstreetmap.org/way/274163557
[2]: https://www.openstreetmap.org/changeset/137712091
[3]: https://nominatim.osm.org/ui/search.html?q=Ch%C3%BCechligasse+23a%2C+W%C3%A4ngi
[4]: https://nominatim.osm.org/ui/search.html?q=Ch%C3%BCechligasse+23a%2C+W%C3%A4ngi&dedupe=0
[5]: https://www.openstreetmap.org/changeset/137425715

**Comment by lonvia** [comment]
There seems to be an issue with updates when the type of object changes. There are now two entries in the database for the way. One with `building=house`, one with `building=terrace`. This should not happen.

**Comment by lonvia** [comment]
There are about 1.3M duplicates in the database. I'll do a reimport on all machines soonish to fix those.
