### ISSUE TITLE
house_number missing in reverse lookup (when 'amenity' is set)

### ISSUE THREAD

**Issue by mrAceT** [osm-search/Nominatim#3173]
## What did you search for?
lat: 52.9660819
lon: 5.9177899

## What result did you get?
    "address": {
        "amenity": "De Tjongerschans",
        "road": "Van Helomalaan",
        "town": "Heerenveen",
        "municipality": "Heerenveen",
        "state": "Frisia",
        "ISO3166-2-lvl4": "NL-FR",
        "country": "Netherlands",
        "postcode": "8441 BZ",
        "country_code": "nl"
    },

## What result did you expect?
also the 'house_number':
    "address": {
        "amenity": "De Tjongerschans",
        "house_number": "44",
        "road": "Van Helomalaan",
        "town": "Heerenveen",
        "municipality": "Heerenveen",
        "state": "Frisia",
        "ISO3166-2-lvl4": "NL-FR",
        "country": "Netherlands",
        "postcode": "8441 BZ",
        "country_code": "nl"
    },

## Further details
I get the distinct impression that when there is a value for 'amenity' the field 'house_number' is left out. I have tested it with several.. This does not happen when there is an 'office' field set.

When I look in OpenStreetMap I do see the house number, so the data is there!

PS: can anyone tell me why the state is 'Frisia' ? It should officially be 'Fryslân' (or at least "Friesland") The name Frisia refers much more to the Frisian country hundreds of years ago.. (https://en.wikipedia.org/wiki/Frisia)

**Comment by lonvia** [comment]
Closing as duplicate.
