### ISSUE TITLE
XML Response is not valid

### ISSUE THREAD

**Issue by DmytroMelnyk** [osm-search/Nominatim#3175]
Expected result is here:
https://nominatim.org/release-docs/develop/api/Search/#xml-with-kml-polygon
```
more_url=https://nominatim.openstreetmap.org/search?q=135+pilkington+avenue%2C+birmingham&amp;polygon_kml=1&amp;addressdetails=1&amp;limit=20&amp;exclude_place_ids=125279639&amp;format=xml
```
Actual result -> https://nominatim.openstreetmap.org/search?q=135+pilkington+avenue,+birmingham&format=xml&polygon_kml=1&addressdetails=1
```
more_url="https://nominatim.openstreetmap.org/search?q=135+pilkington+avenue%2C+birmingham&polygon_kml=1&addressdetails=1&limit=20&exclude_place_ids=125070285&format=xml"
```
Problem is `&` symbol is invalid for xml and should be changed to `&amp;`

**Comment by mtmail** [comment]
Can you show how to reproduce the issue? I'm using `curl` and the output looks fine. Are you looking at a different server (your own server?) or different version? Is the tool you're viewing the XML with maybe translation &amp; back to & ?

![image](https://github.com/osm-search/Nominatim/assets/3727288/1b376d61-7717-410e-ab9e-716d557fc768)

**Comment by DmytroMelnyk** [comment]
Sorry, problem was on my side. closing issue.
Thanks!
