### ISSUE TITLE
Vandalism with Russian titles

### ISSUE THREAD

**Issue by sunbromarko** [osm-search/Nominatim#3176]
## What did you search for?
https://nominatim.openstreetmap.org/ui/reverse.html?lat=55.79952&lon=37.92566&zoom=18

## What result did you get?
National insults embedded in search results

## What result did you expect?
Just normal search results

Thanks !

**Comment by sunbromarko** [comment]
<img width="980" alt="image" src="https://github.com/osm-search/Nominatim/assets/115900728/22fa20c9-3013-46a3-b321-3a8b12f34d59">

**Comment by mtmail** [comment]
We're aware of the current vandalism. There's several dicussion threads on https://community.openstreetmap.org/ (e.g. "
Horrors are written on the maps of Russia") and members of the OpenStreetMap data working group (https://wiki.osmfoundation.org/wiki/Data_Working_Group) are actively reverting changes and deleting user accounts.

The change at your reported coordinates have been reverted several hours ago. We're waiting for the Nominatim search index to be updates at this point.

In OpenStreetMap we call it vandalism. People can create user accounts and edit the map (database) in the browser. Like wikipedia we want to make editing for easy for everybody. Hacking I think would mean somebody used a backdoor into the database. I know the wording doesn't matter much when looking at the data on your screenshot.

**Comment by sunbromarko** [comment]
Thank you for the explanation, and the immediate response ! I have a lot of respect for the work you do !

**Comment by lonvia** [comment]
Our servers are having trouble catching up with the latest changes in the OSM database. Please give it a few more hours and the reverts should be visible.

**Comment by lonvia** [comment]
The servers are back up to date. Please note that further vandalism is possible and there may be some further delays with updates in the next days.. The DWG is watching to the situation and doing their best to stop this at the source. Not much that can be done on the Nominatim side, I'm afraid. So closing here.
