### ISSUE TITLE
Diffrent results depending on whether a particular city is in the bbox

### ISSUE THREAD

**Issue by Dimitar5555** [osm-search/Nominatim#3177]
## What did you search for?

`град Приморско` when `Банкя` (https://www.openstreetmap.org/node/273488684) is in the bbox.
https://www.openstreetmap.org/search?query=град%20Приморско#map=13/42.7102/23.1465

## What result did you get?
The first result returns the city of Bankya, clicking on "More results" returns HTTP 500 error.

## What result did you expect?

**When the result missing completely:**
The first result should be `Приморско` (https://www.openstreetmap.org/node/273488895).

## Further details

Using the same terms in other location yields the correct result (https://www.openstreetmap.org/search?query=град%20Приморско#map=15/43.1329/24.7152). The problem occurs only when `Банкя` (https://www.openstreetmap.org/node/273488684) is in the bbox.

**Comment by mtmail** [comment]
www.openstreetmap.org website uses Nominatim API in the background. It's not always easy to see what exact request and response happens between the systems.

But I think I can replicate it.
1. go to https://nominatim.openstreetmap.org/
2. search for "Maksim Gorki, 9300, Bulgaria"
3. zoom out the map a bit, click 'advanced options', click 'apply viewbox'. Then search for "град Приморско"
4. Result page shows https://nominatim.openstreetmap.org/ui/search.html?q=%D0%B3%D1%80%D0%B0%D0%B4+%D0%9F%D1%80%D0%B8%D0%BC%D0%BE%D1%80%D1%81%D0%BA%D0%BE&viewbox=27.66461%2C43.67756%2C28.02922%2C43.39208
5. click "Search for more results"
6. Now there's an error: Error fetching data from /search.php?q=%D0%B3%D1%80%D0%B0%D0%B4%20%D0%9F%D1%80%D0%B8%D0%BC%D0%BE%D1%80%D1%81%D0%BA%D0%BE&polygon_geojson=1&viewbox=27.66461%2C43.67756%2C28.02922%2C43.39208&exclude_place_ids=516701%2C550453%2C497232&format=jsonv2 (Internal Server Error)
