### ISSUE TITLE
Wrong address resolution for position 0.0, 0.0

### ISSUE THREAD

**Issue by AMDFX60** [osm-search/Nominatim#3179]
The lat. and long. position 0.0, 0.0 should return "Null Island" or "Soul Buoy".
Since some days it returns "Bioladen Schlanders", which is (I guess) in Italy and makes no sense as result.

**Comment by mtmail** [comment]
Null Island is fictional. Some geocoders return it as a joke (e.g. opencage) but it shouldn’t be in OSM data.

**Comment by lonvia** [comment]
This is a data issue, not a Nominatim problem.

When fixed the [Soul Buoy](https://www.openstreetmap.org/node/3815077900), which is not exactly at 0/0 in OSM, will reappear.
