### ISSUE TITLE
500 Internal Server Error - exclude_place_ids & Incorrect listing of search results regarding postal code

### ISSUE THREAD

**Issue by StudySteve** [osm-search/Nominatim#3184]
1. An error occurs when something is searched for and it contains "exclude_place_ids." In this case, an error message is always displayed: "Error fetching data from /search.php?q=Bakery%20in%2010115%2C%20Berlin%2C%20Deutschland&polygon_geojson=1&exclude_place_ids=12638719%2C7401858%2C58963332%2C12651684%2C5102217%2C14168603%2C14075238%2C59396706%2C8779249%2C7399704&format=jsonv2 ()".

2. When searching for a postal code in a country, for example, "Bakery in 10115 Berlin Deutschland," the results are not properly filtered by postal code (The result: 10115, 10115, 10115, 13355, 13347, 10115, 10115, 10115, 10115, 13347,...). Instead, other similar postal codes keep appearing in between. As a result, some results with the correct postal code are not displayed. 

Thank you very much.

**Comment by lonvia** [comment]
This was already fixed in  15e09f2b247d1286a9e43e46d6ab9476eca0bb82, just wasn't rolled out on some of the servers. Should be fine now.

Please also not that the use of `/search.php` is deprecated. Please change your URL to `/search`.

**Comment by StudySteve** [comment]
Thank you for your time and your help. That helped me alot.
