### ISSUE TITLE
500 Internal Server - Failure by searching api with excluded

### ISSUE THREAD

**Issue by StudySteve** [osm-search/Nominatim#3185]
Please excuse me for contacting you again. But unfortunately the "500 Internal Server" error still occurs sometimes when I'm working with excluded ids. What could be the reason? Or how can I fix the error.
However, the error does not always occur, only sometimes. You have to call up the link several times and then you get the error message again and again and sometimes it works.

Thank you for your time, help and understanding.

This is a link for example:
[https://nominatim.openstreetmap.org/?addressdetails=1&q=Bakery+in+88048%2C+Friedrichshafen%2C+Deutschland&exclude_place_ids=92245516%2C92125346%2C91727841%2C93001088%2C91818690%2C92126331%2C91799319%2C91989542%2C91824016%2C92071501%2C91828239%2C92025666%2C93031070%2C92023834%2C91850050%2C91695145%2C92075766%2C91965002%2C92290493%2C91885009%2C91819476%2C92446155%2C91893382%2C92077128%2C91812802%2C91760956%2C91892928%2C91823585%2C92261889%2C91825833%2C92206387%2C92078522%2C91803825%2C92293066%2C92229670%2C92171445%2C91823378%2C91758904%2C92122829%2C91851943%2C91800520%2C91942355%2C91700034%2C92383105%2C91785270%2C91873677%2C92333968%2C92188249%2C91678059%2C91891042%2C92247836%2C92004175%2C91824067%2C91841799%2C91852633%2C92175573%2C91962286%2C91701816&format=json&limit=50](https://nominatim.openstreetmap.org/?addressdetails=1&q=Bakery+in+88048%2C+Friedrichshafen%2C+Deutschland&exclude_place_ids=92245516%2C92125346%2C91727841%2C93001088%2C91818690%2C92126331%2C91799319%2C91989542%2C91824016%2C92071501%2C91828239%2C92025666%2C93031070%2C92023834%2C91850050%2C91695145%2C92075766%2C91965002%2C92290493%2C91885009%2C91819476%2C92446155%2C91893382%2C92077128%2C91812802%2C91760956%2C91892928%2C91823585%2C92261889%2C91825833%2C92206387%2C92078522%2C91803825%2C92293066%2C92229670%2C92171445%2C91823378%2C91758904%2C92122829%2C91851943%2C91800520%2C91942355%2C91700034%2C92383105%2C91785270%2C91873677%2C92333968%2C92188249%2C91678059%2C91891042%2C92247836%2C92004175%2C91824067%2C91841799%2C91852633%2C92175573%2C91962286%2C91701816&format=json&limit=50)

This is the error message for example

This XML file does not appear to have any style information associated with it. The document tree is shown below.
`<error>
<title>500 Internal Server Error</title>
</error>`

**Comment by StudySteve** [comment]
This the error message of the XML:

This XML file does not appear to have any style information associated with it. The document tree is shown below.
<error>
<title>500 Internal Server Error</title>
</error>

**Comment by mtmail** [comment]
Unrelated (still same error) but you should use /search? instead of /? (deprecated)

Also unrelated, Overpass API is a good alternative they're looking for all hospitals/pubs/restaurants in a defined area. For example the "all supermarkets in London" https://dev.overpass-api.de/overpass-doc/en/full_data/area.html where "London" can be any address because it will do geocoding in the background. Or one can geocode first and then use a bounding box search.

**Comment by mtmail** [comment]
This URL is shorter (more readable) and has the same issue https://nominatim.openstreetmap.org/search?addressdetails=1&q=Bakery+in+Hannover&exclude_place_ids=123&format=jsonv2

**Comment by lonvia** [comment]
Still wasn't properly deployed. I hope I got it right this time.
