### ISSUE TITLE
 Error in build  because of missing dependecy in guide: nlohmann

### ISSUE THREAD

**Issue by gsg-git** [osm-search/Nominatim#3192]
Hello!
 I got an error: 
"NLOHMANN_INCLUDE_DIR-NOTFOUND"
In the guide is the missing application not mentioned:
nlohmann-json3-dev

Thank you!

**Comment by mtmail** [comment]
Just to clarify, which page are you looking at? Is that https://nominatim.org/release-docs/4.3/admin/Installation/ ?

**Comment by lonvia** [comment]
Duplicate of #3191.
