### ISSUE TITLE
Cities don't come in the results anymore

### ISSUE THREAD

**Issue by tiagomn** [osm-search/Nominatim#3196]
Hi Guys, It's been around 2 months since some cities in Brazil are not coming in the results. I'll give one example which the result is not correct as we expected:

https://nominatim.openstreetmap.org/search?q=sao%20jose%20dos%20campos&addressdetails=1&accept-language=pt-BR&format=jsonv2

It was supposed to return Sao Jose dos Campo, SP, Brazil but it's not returning anymore, and this is city is quite famous here in Brazil.

Do you guys know if there was an update in the Nominatim Database? As other cities don't come in the result either.

**Comment by mtmail** [comment]
So the expected top result is either
São José dos Campos
https://nominatim.openstreetmap.org/ui/details.html?osmtype=R&osmid=298019&class=boundary (place=municipality)
or
São José dos Campos 
https://nominatim.openstreetmap.org/ui/details.html?osmtype=R&osmid=5349757&class=boundary (admin_level=9 (district))

**Comment by tiagomn** [comment]
Hi mate.

Should be the first one. Many cities like this was shown in the past, but around 2 months they haven't been shown in the results. I also realized the the result are coming with few or may one result of cities we type. For example: Sao Paulo, SP, there are other cities in Brazil called Sao Paulo, but in different states, but nominatim are showing only Sao Paulo, SP

**Comment by mtmail** [comment]
Please list the exact search (URL) you're doing and which result (link to OSM object) that you'd expect to be the first result. This will help us avoid misunderstandings, especially in case one issue gets solved to see if the next is still open. We have instructions how to find the URLs on https://raw.githubusercontent.com/osm-search/Nominatim/master/.github/ISSUE_TEMPLATE/report-issues-with-search-results.md

(You can find that template by clicking "Get Started" next to "Report issues with search results" on https://github.com/osm-search/Nominatim/issues/new/choose)

**Comment by tiagomn** [comment]
https://nominatim.openstreetmap.org/search?q=sao%20bernardo%20do%20campo&addressdetails=1&accept-language=pt-BR&format=jsonv2&limit=20

We expected to see something like this for those issues using São Paulo as example:

![image](https://github.com/osm-search/Nominatim/assets/4093380/1867e816-610c-4851-8b23-5cc3520a78c2)

**Comment by mtmail** [comment]
Please open a new issue and use the report template "Report issues with search results" https://github.com/osm-search/Nominatim/issues/new/choose
