### ISSUE TITLE
nominatim search timeout

### ISSUE THREAD

**Issue by denen99** [osm-search/Nominatim#3197]
## What did you search for?
Berlin

nominatim search --query Berlin

## What result did you get?

Nothing, it hangs

## What result did you expect?

Some sort of result

Berlin results 

https://www.openstreetmap.org/query?lat=49.7675&lon=13.3610

## Further details

Getting timeouts to the DB and unsure how to troubleshoot the issue?  CPU seems fine

**Comment by danieldegroot2** [comment]
Have you tried debugging with https://nominatim.openstreetmap.org/ ?
Just a quick sidenote, could you also try "Berlin, DE", if possible? This should have a higher chance of success.
(with recent versions of Nominatim it is a bit stricter about some of these queries)

**Comment by denen99** [comment]
Berline, DE gives the same issue. 

Looking at postgres, it seems to be stuck on the query, is it possible there is an indexing issue? 

SELECT place_id, address_rank,  (  SELECT count(*) FROM (   SELECT unnest(ARRAY[69445,69451,69454,69455,69459,69477,69484,69516,69522,69542,69543])    INTERSECT   SELECT unnest(nameaddress_vector) ) s) as exactmatch FROM search_name WHERE name_vector @> ARRAY[69516] ORDER BY (CASE WHEN importance = 0 OR importance IS NULL THEN 0.75001-(search_rank::float/40) ELSE importance END) DESC, exactmatch DESC LIMIT 20

**Comment by mtmail** [comment]
Can you post your Postgresql and PostGIS versions? And the output of the same query with „EXPLAIN“ in front? That might give a clue which database index is affected. The pg_top tool might also indicate what other process is blocking.

**Comment by denen99** [comment]
Ugh sorry, i am an idiot.  Looks like the import process did not complete fully , running import with --continue indexing fixed it

**Comment by mtmail** [comment]
I assumed Nominatim had been in use already. In that case running `nominatim--check-database` would've shown a warning that not all places are indexed yet and that indexes are missing.
