### ISSUE TITLE
Short town name Vic not found when searched for the name alone

### ISSUE THREAD

**Issue by polarbearing** [osm-search/Nominatim#3198]
## What did you search for?

place=town Vic in Catalonia, Spain
Using only the name:
https://nominatim.openstreetmap.org/ui/search.html?q=Vic

## What result did you get?
Not the town. Only Victoria, Australia 

## What result did you expect?
Vic place node:
https://www.openstreetmap.org/node/1470839536

This town works:
https://nominatim.openstreetmap.org/ui/search.html?q=radebeul
place=town, name=Radebeul https://www.openstreetmap.org/node/84710033

## Further details
Together with a street, it works:
Street only:
https://nominatim.openstreetmap.org/ui/search.html?q=Carrer+Nou
==> first 10 results elsewhere

With town name:
https://nominatim.openstreetmap.org/ui/search.html?q=Carrer+Nou%2C+Vic
==> Carrer Nou, Barri dels Caputxins, Vic, Osona, Barcelona, Catalonia, 08500, Spain Living street

With Catalonia, it also works:
https://nominatim.openstreetmap.org/ui/search.html?q=Vic%2C+Catalonia
==> Vic, Osona, Barcelona, Catalonia, 08500, Spain Administrative

**Comment by lonvia** [comment]
Fixed with #3206.

Victoria, AU will still appear in the second place, which looks correct to me because 'VIC' is a common enough abbreviation for the state.
