### ISSUE TITLE
not finding Salò, Italy

### ISSUE THREAD

**Issue by dieterdreist** [osm-search/Nominatim#3200]
## What did you search for?
Salò
and also 
Salò, Italia (but after the map already had jumped to Chile)

osm.org

## What result did you get?
the map jumped to Latin America and showed "Chile" as only initial result. Clicking on "more results" yielded a lot of places in Chile (none of them actually written exactly the same "Salò", but were written "Salo").

## What result did you expect?
Salò, town in Italy

**result missing completely:**
https://www.openstreetmap.org/relation/45412
https://it.wikipedia.org/wiki/it:Sal%C3%B2

## Further details

interestingly, I found Salò when I searched for "Salò, Italien" (despite having set English as preferred OSM language and having my browser set to English as well).

**Comment by lonvia** [comment]
Fixed with #3206.

"Chile" will still appear relatively early, when searching for more results because 'Salo' matches against the transliteration of the non-latin versions of Chile. To properly fix this, we need token rematching against country names. I'll open a separate issue for that.
