### ISSUE TITLE
Strange order of results with addr:place

### ISSUE THREAD

**Issue by osmuser63783** [osm-search/Nominatim#3208]
## What did you search for?

[1 Royal Terrace Gardens](https://nominatim.openstreetmap.org/ui/search.html?q=1+royal+terrace+gardens)

## What result did you get?

The top result is a house in New Zealand with address 1 Royal Terrace. "Gardens" does not appear anywhere in its address.

## What result did you expect?

I expected either node [10853538418](https://nominatim.openstreetmap.org/ui/details.html?osmtype=N&osmid=10853538418&class=amenity) or node [3287615132](https://nominatim.openstreetmap.org/ui/details.html?osmtype=N&osmid=3287615132&class=place) in Edinburgh, both of which have the address 1 Royal Terrace Gardens.

## Further details

There isn't a corresponding street called "Royal Terrace Gardens", so the address tagging uses `addr:place` instead. 

Since the value in `addr:place` is an exact match for the search query I would expect it to be ranked higher than the address in New Zealand.

In my experiments, I have found that I am more likely to get the expected results for addresses with an `addr:place` tag when there is a node / way / relation with a `place` tag nearby e.g. `place=village` or `place=city_block`. Creating such a `place` object sometimes makes sense e.g. when the value in `addr:place` refers to a clearly defined area such as a village or city block. In this case, this doesn't really make sense: the building is in a [park](https://www.openstreetmap.org/way/22415647) that used to be called Royal Terrace Gardens but is now called something else. Royal Terrace Gardens is already tagged as the `alt_name` of the park and adding an artificial `place` on top of that would not be faithful to the situation on the ground.

**Comment by lonvia** [comment]
Unlisted addr:place are currently not added as a full name due to some previous optimisations. That means they don't get the accuracy boost.
