### ISSUE TITLE
Missing names in relations from the linked place nodes after update

### ISSUE THREAD

**Issue by rcarroll0452** [osm-search/Nominatim#3209]
**Describe the bug**
Has anyone noticed in their setup where relations that are getting updated has missing names that were original imported from the linked place nodes?

In my setup, the import happened on Oct-2022 and continuous updates has been running since then.
Since last few weeks, relations that are getting updated seems to be dropping the names that were originally included from the linked place nodes.

For example: I found the below difference for [Jerusalem](https://www.openstreetmap.org/relation/1381350), which got updated on 13-09-2023:

On 12-09-2023, the `namedetails` contained the following in the list of names:
```
{
    ...
    "name:es": "Jerusalén",
    "name:sv": "Jerusalem",
    "name:id": "Yerusalem",
    "name:no": "Jerusalem",
    "name:pl": "Jerozolima",
    ...
}
```
On 13-09-2023 after the update to this relation, I could only obtain the names that are directly tagged in the relation (name:es, sv, id, no, pl are missing).
```
{
    "name": "ירושלים | القدس",
    "name:ar": "القدس",
    "name:cs": "Jeruzalém",
    "name:de": "Jerusalem",
    "name:el": "Ιερουσαλήμ",
    "name:en": "Jerusalem",
    "name:fi": "Jerusalem",
    "name:fr": "Jérusalem",
    "name:fy": "Jeruzalim",
    "name:he": "ירושלים",
    "name:hu": "Jeruzsálem",
    "name:it": "Gerusalemme",
    "name:ko": "예루살렘",
    "name:mi": "Hiruhārama",
    "name:nl": "Jeruzalem",
    "name:ro": "Ierusalim",
    "name:ru": "Иерусалим",
    "name:sk": "Jeruzalem",
    "name:ur": "یروشلم",
    "int_name": "Jerusalem",
    "name:ckb": "قودس",
    "name:szl": "Jeruzalym",
    "name:tzl": "Ierusalem",
    "alt_name:ur": "بیت المقدس",
    "official_name": "القدس",
    "short_name:ur": "القدس"
}
```

**Software Environment (please complete the following information):**
- Nominatim version: 4.1.0-0 (b64207e0)
- Postgres version: 12.12
- Postgis version: psql (PostgreSQL) 12.7 
- OS: Ubuntu 20.04.2 LTS
- OSM initial import date: Oct-2022

**Hardware Configuration (please complete the following information):**
- number of CPUs: 16 cores/32 threads
- RAM : 128GB
- Disk type: SSD
- Disk size: 1.8TB

**Nominatim Configuration:**

- NOMINATIM_LIMIT_REINDEXING=no
- NOMINATIM_FLATNODE_FILE=....
- NOMINATIM_REPLICATION_URL="http://planet.openstreetmap.org/replication/day"
- NOMINATIM_REPLICATION_MAX_DIFF=30
- NOMINATIM_REPLICATION_UPDATE_INTERVAL=86400

**Additional context**

All of these missing names are from the linked place nodes since the actual relation did not have any of these missing names (checked relation history as well) and they are getting deleted only when the relation gets updated. Any relation that was not updated in the recent times still has all the names from the linked place nodes.

**Comment by lonvia** [comment]
Is the Jerusalem relation still linked to the Jerusalem place node?

**Comment by rcarroll0452** [comment]
Thanks for taking a look.

> Is the Jerusalem relation still linked to the Jerusalem place node?

Yes. From the list of members for [Jerusalem relation](https://www.openstreetmap.org/relation/1381350), I could see "Node [Jerusalem (29090735)](https://www.openstreetmap.org/node/29090735) as admin_centre"

**Comment by lonvia** [comment]
That's not what I meant. I mean, are node and relation still linked in your instance of Nominatim. You can see this in the details view. For example the public instance: https://nominatim.openstreetmap.org/ui/details.html?osmtype=R&osmid=1381350 has the node under the heading of 'Linked Places'.

**Comment by rcarroll0452** [comment]
No, they do not appear linked in my DB instance. 
Checked from details page and did not get any info about 'Linked Places'

So, I checked the `placex` table in Nominatim DB on my local instance and the `linked_place_id` is empty for this relation. I noticed the problem with [Brussels](https://www.openstreetmap.org/relation/58274) as well, and even for that relation the `linked_place_id` is null.


```
nominatim=> SELECT osm_id, osm_type, linked_place_id FROM placex WHERE osm_type = 'R' AND osm_id IN (1381350, 58274);
 osm_id  | osm_type | linked_place_id 
---------+----------+-----------------
   58274 | R        |                
 1381350 | R        |                
(2 rows)
```

Then i tried to check if these place nodes are present in my DB. They are present and I also noticed that the the place node [Jerusalem node](https://www.openstreetmap.org/node/29090735) did not have any `parent_place_id` and the `linked_place_id` points to [Jerusalem, a different relation](https://www.openstreetmap.org/relation/6502363). (Can a node have a linked_place_id?)

```
nominatim=> SELECT osm_id, osm_type, parent_place_id, linked_place_id FROM placex WHERE osm_type = 'N' AND osm_id IN (29090735, 1635651356);
   osm_id   | osm_type | parent_place_id | linked_place_id 
------------+----------+-----------------+-----------------
   29090735 | N        |                 |       344821403
 1635651356 | N        |       303624891 |                
(2 rows)

nominatim=> SELECT osm_id, osm_type FROM placex WHERE place_id = 344821403;
 osm_id  | osm_type 
---------+----------
 6502363 | R
(1 row)
```

**Comment by lonvia** [comment]
This is a data issue then. Both relations pretend to be `place=city` polygons for Jerusalem. It will be essentially random which one Nominatim will link to.

**Comment by rcarroll0452** [comment]
Thank you so much for helping me understand this. I could confirm that I'm seeing all the names from the place node on the different Jerusalem relation's details.

I'm unsure of the reason for [Brussels](https://www.openstreetmap.org/node/1635651356) node to not be linked with any relation in my instance

**Comment by lonvia** [comment]
There are at least four boundary relations named Brussels, all having the node as 'admin_center', none with a matching wikidata or wikipedia tag. The data seems to indicate that it is correct to match the node with node of the boundaries.

Closing as data issue.
