### ISSUE TITLE
Wrong sort China the country ranked after a small town named with China in MX

### ISSUE THREAD

**Issue by LaoshuBaby** [osm-search/Nominatim#3215]
## What did you search for?

China

https://nominatim.openstreetmap.org/ui/search.html?q=China

## What result did you get?

![图片](https://github.com/osm-search/Nominatim/assets/42690037/bed38f7a-b498-4068-add4-60936f8ab6e4)

The first result is https://www.openstreetmap.org/relation/5605656 

## What result did you expect?

**When the result missing completely:**

openstreetmap.org/relation/270056

## Further details

HAR file for the request (I capture in F12 debug terminal)

[nominatim.openstreetmap.org_Archive [23-09-28 22-37-26].har.zip](https://github.com/osm-search/Nominatim/files/12750823/nominatim.openstreetmap.org_Archive.23-09-28.22-37-26.zip)

**Comment by lonvia** [comment]
As per comment in #3206:

> It's possible that this leads to artifacts when the script used in the query is different from the script in the result (say when you have set your browser to Japanese but search for 'New York' in latin letters).

You are mixing a Chinese locale with an English-language request here.

**Comment by mtmail** [comment]
Adding a reproducable API call by setting the same browser language as in the HAR file.

`curl -s 'https://nominatim.openstreetmap.org/search?q=China&format=jsonv2&limit=1&accept-language=zh-CN,zh;q=0.8,zh-TW;q=0.7,zh-HK;q=0.5,en-US;q=0.3,en;q=0.2' | jq`

```json
[
  {
    "place_id": 304004633,
    "licence": "Data © OpenStreetMap contributors, ODbL 1.0. http://osm.org/copyright",
    "osm_type": "relation",
    "osm_id": 5605656,
    "lat": "25.491579899999998",
    "lon": "-98.98111150455688",
    "category": "boundary",
    "type": "administrative",
    "place_rank": 12,
    "importance": 0.45000999999999997,
    "addresstype": "county",
    "name": "China",
    "display_name": "China, 新莱昂州, 墨西哥",
    "boundingbox": [
      "25.0671341",
      "25.9161824",
      "-99.4612273",
      "-98.4215760"
    ]
  }
]
```

**Comment by LaoshuBaby** [comment]
I don't think it's a browser UA problem, because my UA has not changed for years, but I tested it again today and found that this problem has been fixed, so I closed this issue until a similar problem occurs again. Thank you for your recurrence.
