### ISSUE TITLE
Strange results with the new version of Nominatim

### ISSUE THREAD

**Issue by pyrog** [osm-search/Nominatim#3232]
## What did you search for?

[hospital in Annecy](https://www.openstreetmap.org/search?query=hospital%20in%20annecy#map=19/45.93234/6.11311)

## What result did you get?
The city hospital first and 4 hospitals nearby 😄 
But also 5 american hospitals 🤪

## What result did you expect?
Only hospitals nearby.

## Further details
Tests done after [Nominatim 4.3 released](https://nominatim.org/2023/10/07/release-43.html).

Some similar search:
- [hospital near annecy](https://www.openstreetmap.org/search?query=hospital%20near%20annecy#map=17/45.93224/6.11754) return in second position an hospital in Bonneville, far from Annecy.
- [hospital annecy](https://www.openstreetmap.org/search?query=hospital%20annecy#map=15/45.9356/6.1321) seem fine 😎 
- [hôpital d'annecy](https://www.openstreetmap.org/search?query=hôpital%20d%27annecy#map=17/45.93224/6.11754) give results in Bonnville too 😞 
- [hôpital annecy](https://www.openstreetmap.org/search?query=hôpital%20annecy%20#map=17/45.93224/6.11754) give good results (not limited to hospitals: bus stop, parking…)

**Comment by lucca-oliveira** [comment]
I'm having the same issue here, searching for cities in Brasil. Some cities seems like just don't exist in their database or something like that, even worse with small cities. Example: Searching for Novo Cruzeiro, Minas Gerais, Brasil (https://nominatim.openstreetmap.org/search?q=Novo+cruzeiro&addressdetails=1&accept-language=pt-BR&format=jsonv2&limit=20), it don't return the City itself. IDK if its a bug but hope it get fixed.

**Comment by mtmail** [comment]
@lucca-oliveira Please open a new separate issue. Use the "report issue with search results template" on https://github.com/osm-search/Nominatim/issues/new/choose
