### ISSUE TITLE
Failure (http 500) when creating address details for name-less aerodome

### ISSUE THREAD

**Issue by dlubom** [osm-search/Nominatim#3237]
This query give 500 error:

https://nominatim.openstreetmap.org/details.php?osmtype=N&osmid=9051953583&addressdetails=1&hierarchy=0&group_hierarchy=1&format=json

For Overpass query:

```
node(id:9051953583);
out body;
```

It give correct results:

```
<?xml version="1.0" encoding="UTF-8"?>
<osm version="0.6" generator="Overpass API 0.7.61.5 4133829e">
<note>The data included in this document is from www.openstreetmap.org. The data is made available under ODbL.</note>
<meta osm_base="2023-10-31T14:32:15Z"/>

  <node id="9051953583" lat="9.3252684" lon="-70.9306634">
    <tag k="aeroway" v="aerodrome"/>
  </node>
</osm>

```

**Comment by mtmail** [comment]
I'm adding more information that will help debugging.

https://www.openstreetmap.org/node/9051953583 has no name or reference. Unclear why Nominatim has it in its database.

Disabling `addressdetails` works https://nominatim.openstreetmap.org/details.php?osmtype=N&osmid=9051953583&addressdetails=0&format=json

I can't reproduce the issue in an older Nominatim version 4.2, so might be 4.3 related.

**Comment by mtmail** [comment]
On a fresh installation I imported a fresh Venezula and can't reproduce the issue. Neither with Python implementation nor PHP:

```
nominatim --version
Nominatim version 4.3.0-0 (afb439b0)

nominatim details --node 9051953583 --addressdetails
{
    "place_id": 265197,
    "parent_place_id": 270188,
    "osm_type": "N",
    "osm_id": 9051953583,
...

curl 'http://localhost/nominatim/details.php?osmtype=N&osmid=9051953583&addressdetails=1&format=json' | jq
{
  "place_id": 265197,
  "parent_place_id": 270188,
  "osm_type": "N",
  "osm_id": 9051953583,
...
```

**Comment by lonvia** [comment]
You need to have assertions enabled in Python to reproduce the error.

**Comment by dlubom** [comment]
Thank you for quick fix
