### ISSUE TITLE
Multiple wrong street names on openstreetmap.org

### ISSUE THREAD

**Issue by colson-louis** [osm-search/Nominatim#3239]
## What result did you expect?

The latitude and longitude of both streets since they do exist but there is a grammar mistake in both street names.
openstreetmap: Voie de Meuniers               <=> real name: Voie des Meuniers
openstreetmap: Rue Tiges des Marchands  <=> real name: Rue Tige des Marchands

There is many more wrong names this is just a small sample.

**Comment by mtmail** [comment]
Nominatim uses the data from OpenStreetMap. If you know of a data error in OpenStreetMap you can use the 'Edit' button on https://openstreetmap.org (https://www.openstreetmap.org/fixthemap). Nominatim updates very fast, usually after a couple of minutes.
