### ISSUE TITLE
searching for name of river currently invisible

### ISSUE THREAD

**Issue by fgnievinski** [osm-search/Nominatim#3242]
## What did you search for?

term "arroio do salso":
https://nominatim.openstreetmap.org/ui/search.html?q=arroio+do+salso

when browsing near the city of Porto Alegre, at street level zoom (default for OSM's "show my location" feature)
https://www.openstreetmap.org/#map=16/-30.0978/-51.2455

## What result did you get?
lots of other rivers named similarly but located far away. the nearest one was actually the ninth hit in the search results.

## What result did you expect?
the closest hit among similarly named features of the same kind should be the first hit:
https://www.openstreetmap.org/way/356395708#map=14/-30.1740/-51.2145&layers=T

## Further details
after knowing where the feature was, reducing the zoom level so as to include the feature of interest improved the search ranking
https://www.openstreetmap.org/#map=14/-30.1681/-51.1700&layers=T

I've checked the FAQ and this issue might be related to the first question though I'm not sure about it:
https://nominatim.org/api/Faq/

I've also checked the search ranking settings but it didn't seem to say anything specific about rivers or ways:
https://nominatim.org/customize/Ranking/#search-rank

**Comment by lonvia** [comment]
The viewbox parameter means you get a preference for what is in the viewbox (as well as its close proximity). It does not cause ordering of results by distance. So the results are as expected. 

The best way to improve search with rivers like this is to create waterway relations. This will drastically reduce the result list.

I've added a comment to the general viewbox-improvement ticket #824 regarding your feature request to keep the topic a bit together. Closing here.

**Comment by fgnievinski** [comment]
> The best way to improve search with rivers like this is to create waterway relations. This will drastically reduce the result list.

done, thanks for the suggestion!
https://www.openstreetmap.org/relation/16694516

**Comment by fgnievinski** [comment]
> > The best way to improve search with rivers like this is to create waterway relations. This will drastically reduce the result list.
> 
> done, thanks for the suggestion! https://www.openstreetmap.org/relation/16694516

however, the other rivers with the same name showing in the search results are independent rivers, distant (unconnected) hundreds of kilometers. admittedly, the river name is quite common, it's not unlike "Mill Creek".
