### ISSUE TITLE
osm2pgslq cmake fails

### ISSUE THREAD

**Issue by iaguerri** [osm-search/Nominatim#3251]
**Describe the bug**
When doing the cmake of the nominatim

**To Reproduce**
1. The part of the dockerfile is:

```
`` # Nominatim install.
ENV NOMINATIM_VERSION=4.3.2
ARG USER_AGENT=mediagis/nominatim-docker:${NOMINATIM_VERSION}
RUN true \
    && curl -A $USER_AGENT https://nominatim.org/release/Nominatim-$NOMINATIM_VERSION.tar.bz2 -o nominatim.tar.bz2 \
    && tar xf nominatim.tar.bz2 \
    && mkdir build \
    && cd build \
    && cmake ../Nominatim-$NOMINATIM_VERSION \
    && make -j`nproc` \
    && make install 
``
```

**Expected behavior**
To compile Nominatim

**Screenshots & Logs**
[ 30%] Building CXX object osm2pgsql/src/CMakeFiles/osm2pgsql_lib.dir/node-locations.cpp.o
09:36:23  c++: fatal error: Killed signal terminated program cc1plus
09:36:23  compilation terminated.
09:36:23  make[2]: *** [osm2pgsql/src/CMakeFiles/osm2pgsql_lib.dir/build.make:132: osm2pgsql/src/CMakeFiles/osm2pgsql_lib.dir/expire-tiles.cpp.o] Error 1
09:36:23  make[2]: *** Waiting for unfinished jobs....
09:36:23  In file included from /usr/include/boost/bind.hpp:30,
09:36:23                   from /usr/include/boost/property_tree/json_parser/detail/parser.hpp:7,
09:36:23                   from /usr/include/boost/property_tree/json_parser/detail/read.hpp:13,
09:36:23                   from /usr/include/boost/property_tree/json_parser.hpp:16,
09:36:23                   from /home/jenkins/agent/workspace/_feature_test-rvalseca-contanier/Nominatim-4.3.2/osm2pgsql/src/gazetteer-style.cpp:15:
09:36:23  /usr/include/boost/bind.hpp:36:1: note: ‘#pragma message: The practice of declaring the Bind placeholders (_1, _2, ...) in the global namespace is deprecated. Please use <boost/bind/bind.hpp> + using namespace boost::placeholders, or define BOOST_BIND_GLOBAL_PLACEHOLDERS to retain the current behavior.’
09:36:23     36 | BOOST_PRAGMA_MESSAGE(
09:36:23        | ^~~~~~~~~~~~~~~~~~~~
09:37:31  c++: fatal error: Killed signal terminated program cc1plus
09:37:31  compilation terminated.
09:37:31  make[2]: *** [osm2pgsql/src/CMakeFiles/osm2pgsql_lib.dir/build.make:202: osm2pgsql/src/CMakeFiles/osm2pgsql_lib.dir/geom-from-osm.cpp.o] Error 1
09:41:07  c++: fatal error: Killed signal terminated program cc1plus
09:41:07  compilation terminated.
09:41:07  make[2]: *** [osm2pgsql/src/CMakeFiles/osm2pgsql_lib.dir/build.make:286: osm2pgsql/src/CMakeFiles/osm2pgsql_lib.dir/middle-pgsql.cpp.o] Error 1

**Desktop / Server (please complete the following information):**
 - OS & Version: Kubernetes 
 - Docker Version: Docker version 24.0.7, build afdd53b
 - Nominatim Version: 4.3.2

**Additional context**
How could avoid this?

**Comment by lonvia** [comment]
Please report docker-related issues with https://github.com/mediagis/nominatim-docker/issues

That said, you don't have enough RAM available to compile osm2pgsql.
