### ISSUE TITLE
New US TIGER 2023 data

### ISSUE THREAD

**Issue by mtmail** [osm-search/Nominatim#3258]
US Census published new data this week https://www2.census.gov/geo/tiger/TIGER2023/

I used https://github.com/osm-search/TIGER-data/ to convert it.

Output is uploaded to https://downloads.opencagedata.com/public/
* [tiger2023-nominatim-preprocessed.csv.tar.gz](https://downloads.opencagedata.com/public/tiger2023-nominatim-preprocessed.csv.tar.gz)
* [us_postcodes_from_tiger2023.csv.gz](https://downloads.opencagedata.com/public/us_postcodes_from_tiger2023.csv.gz)

Number of files/counties remained the same. Number of lines (street segments) went from 33,900,561 to 34,011,617 (+111056, +0.33%)

Few counties have changes over 10%. The largest changes in number of lines (street segments) are
```
31025.csv	9954	8041	-1913	23.79%
36061.csv	10005	11391	1386	-12.17%
36081.csv	3716	3276	-440	13.43%
38043.csv	7033	6154	-879	14.28%
38055.csv	11406	10095	-1311	12.99%
```

```
./compare.py us_postcodes_from_tiger2022.csv us_postcodes_from_tiger2023.csv
Read 36661 postcodes from old file us_postcodes_from_tiger2022.csv
Read 36623 postcodes from new file us_postcodes_from_tiger2023.csv
Added: 45 (0.123%)
Deleted: 83 (0.227%)
Position moved: 24912 (68.023%)
Position moved more than 100 meters: 1015 (2.771%)
Position moved more than 1000 meters: 102 (0.279%)
Position moved more than 10000 meters: 7 (0.019%)
Average distance difference of all updates: 39.38 meters
```

**Comment by mtmail** [comment]
[TIGER2022vs2023.ods](https://github.com/osm-search/Nominatim/files/13459610/TIGER2022vs2023.ods)

**Comment by lonvia** [comment]
Copied to nominatim.org.
