### ISSUE TITLE
FATAL: Wikipedia importance dump file not found

### ISSUE THREAD

**Issue by KodornaRocks** [osm-search/Nominatim#3267]
**Describe the bug**

The file exists, but got the _FATAL: Wikipedia importance dump file not found_ when trying to refresh wiki data.

**To Reproduce**

Create a project, import data and them refresh wiki importance data.
```
nominatim@geodatabase:~/nominatim-brazil$ nominatim refresh --wiki-data --importance --project-dir /srv/nominatim/nominatim-brazil
2023-12-05 22:06:31: Using project directory: /srv/nominatim/nominatim-brazil
2023-12-05 22:06:31: Import wikipdia article importance from /srv/nominatim/nominatim-brazil/wikimedia-importance.sql.gz
2023-12-05 22:06:31: FATAL: Wikipedia importance dump file not found
nominatim@geodatabase:~/nominatim-brazil$ nominatim refresh --wiki-data --importance
2023-12-05 22:06:36: Using project directory: /srv/nominatim/nominatim-brazil
2023-12-05 22:06:36: Import wikipdia article importance from /srv/nominatim/nominatim-brazil/wikimedia-importance.sql.gz
2023-12-05 22:06:36: FATAL: Wikipedia importance dump file not found
```

As I coldn't import it the right way I did a manual import which fooled the db check, but doesn't seems to be improving the queries.
```

> psql -d nominatimbrazil -f wikimedia-importance.sql
> nominatim index
> nominatim admin --warm

> nominatim admin --check-database
2023-12-05 22:16:47: Using project directory: /srv/nominatim/nominatim-brazil
2023-12-05 22:16:47: Checking database
Checking database connection ... OK
Checking for placex table ... OK
Checking for placex content ... OK
Checking that tokenizer works ... OK
Checking for wikipedia/wikidata data ... OK
Checking indexing status ... OK
Checking that database indexes are complete ... OK
Checking that all database indexes are valid ... OK
Checking TIGER external data table. ... not applicable
```

**Software Environment (please complete the following information):**
- Nominatim version: 4.3.2-0 ()
- Postgresql version: 14.9
- Postgis version:  3.2.0 c3e3cc0
- OS: Ubuntu 22.04.3 LTS x86_64

**Hardware Configuration (please complete the following information):**
- RAM: 64G
- number of CPUs: (24) @ 2.499GHz
- type and size of disks: 489G SSD 

**Postgresql Configuration:**

```
shared_buffers = 2GB
work_mem = 50MB
maintenance_work_mem = 10GB
autovacuum_work_mem = 2GB
dynamic_shared_memory_type = posix
synchronous_commit = off
checkpoint_timeout = 10min
checkpoint_completion_target = 0.9
max_wal_size = 1GB
min_wal_size = 80MB
effective_cache_size = 24GB
```

**Nominatim Configuration:**
```
NOMINATIM_DATABASE_DSN=pgsql:dbname=nominatimbrazil
NOMINATIM_FLATNODE_FILE=/srv/nominatim/flatnodes/brazil.file
NOMINATIM_WIKIPEDIA_DATA_PATH=/srv/nominatim/nominatim-brazil/wikimedia-importance.sql.gz
```

**Additional context**

```
nominatim@geodatabase:~/nominatim-brazil$ ls -la
total 3726984
drwxrwxr-x  5 nominatim nominatim       4096 Dec  4 23:28 .
drwxr-x--x 12 nominatim nominatim       4096 Dec  5 21:34 ..
-rw-rw-r--  1 nominatim nominatim        203 Dec  1 02:33 .env
-rw-rw-r--  1 nominatim nominatim 1743207217 Nov 30 20:28 brazil-latest.osm.pbf
-rw-rw-r--  1 nominatim nominatim     463070 Dec  1 11:09 continue_setup.log
-rw-rw-r--  1 nominatim nominatim     274588 Dec  1 03:38 setup.log
drwxrwxr-x  2 nominatim nominatim       4096 Dec  1 03:05 tokenizer
drwxrwxr-x  5 nominatim nominatim       4096 Dec  1 11:28 venv
drwxrwxr-x  2 nominatim nominatim       4096 Dec  5 21:27 website
-rw-r--r--  1 nominatim nominatim 1678855233 Nov 17  2019 wikimedia-importance.sql <<< just in case
-rw-r--r--  1 nominatim nominatim  393574858 Nov 17  2019 wikimedia-importance.sql.gz
```

**Comment by KodornaRocks** [comment]
That was really dumb.

FROM:
```
NOMINATIM_WIKIPEDIA_DATA_PATH=/srv/nominatim/nominatim-brazil/wikimedia-importance.sql.gz
```

TO:
```
NOMINATIM_WIKIPEDIA_DATA_PATH=/srv/nominatim/nominatim-brazil
```

**Comment by mtmail** [comment]
Setting `NOMINATIM_WIKIPEDIA_DATA_PATH` is probably not needed.

I see in `~/nominatim-brazil` you have an `.env` file and a `tokenizer` subdirectory, so `~/nominatim-brazil` is your project directory.

But you ran `nominatim refresh --wiki-data --importance --project-dir /srv/nominatim/nominatim-brazil` which points to the wrong directory.

**Comment by KodornaRocks** [comment]
> Setting `NOMINATIM_WIKIPEDIA_DATA_PATH` is probably not needed.
> 
> I see in `~/nominatim-brazil` you have an `.env` file and a `tokenizer` subdirectory, so `~/nominatim-brazil` is your project directory.
> 
> But you ran `nominatim refresh --wiki-data --importance --project-dir /srv/nominatim/nominatim-brazil` which points to the wrong directory.

Actually it worked when I fixed the `NOMINATIM_WIKIPEDIA_DATA_PATH`.
That config were there because initially the file was in a NFS, so I was pointing there. The problem was that I was pointing to the **filepath** instead of pointing to the **folderpath**.

~/nominatim-brazil is indeed the project folder, and the nominatim home is /srv/nominatim
So `~/nominatim-brazil` is the same of `/srv/nominatim/nominatim-brazil`
