### ISSUE TITLE
Unable to geocode

### ISSUE THREAD

**Issue by ressec** [osm-search/Nominatim#3272]
## What did you search for?

I was using the reverse geocoding API searching for a specific lat, lon:

https://nominatim.openstreetmap.org/reverse?format=json&addressdetails=1&lat=60.11448569290558&lon=20.018432900632526&zoom=18&accept-language=en 

## What result did you get?

An error message: `Unable to geocode` 

## What result did you expect?

**When the result missing completely:**

I was guessing to get at least a continent or sea information.

## Further details

Thanks in advance.

**Comment by mtmail** [comment]
I see a result in Finland when I search for those coordinates https://nominatim.openstreetmap.org/ui/reverse.html?lat=60.11448569290558&lon=20.018432900632526&zoom=18 Did you mix up latitude,longitude and expect a result east of Oman?

International waters is still low on the wishlist and OpenStreetMap data has no boundaries for oceans, request is tracked at https://github.com/osm-search/Nominatim/issues/510

**Comment by lonvia** [comment]
I presume it was a lat/lon mixup.

**Comment by ressec** [comment]
It was not a mixup of lat/lon as described in the ticket. As @mtmail commented it seems OpenStreetMap seems to not being able to geocode coordinates located in ocean/sea!
