### ISSUE TITLE
No results found when zoomed in?

### ISSUE THREAD

**Issue by sfkeller** [osm-search/Nominatim#3274]
## What did you search for?

Search Text: Bahnhofstrasse 104, 8001 Zürich
Node: https://www.openstreetmap.org/node/2954594730
Query: https://www.openstreetmap.org/search?query=Bahnhofstrasse%20104%2C%208001%20Z%C3%BCrich#map=19/51.22190/4.39806

## What result did you get?

"No results found."

When zooming out covering Zurich, the adresses are found, e.g.
https://www.openstreetmap.org/search?query=Bahnhofstrasse%20104%2C%208001%20Z%C3%BCrich#map=6/47.535/8.240

## What result did you expect?

List of all addresses matching "Bahnhofstrasse 104, 8001 Zürich"

**Comment by lonvia** [comment]
Link in Nominatim: https://nominatim.openstreetmap.org/ui/search.html?q=Bahnhofstrasse+104%2C+8001+Z%C3%BCrich&viewbox=4.38241%2C51.22374%2C4.42313%2C51.21031
