### ISSUE TITLE
proximity could get more weight

### ISSUE THREAD

**Issue by fgnievinski** [osm-search/Nominatim#3277]
the nearest feature should appear first among similarly named features or at least before dissimilarly named features.

## What did you search for?
"rio grande" when browsing nearby
https://openstreetmap.org/#map=11/-30.04354/-51.20994
https://nominatim.openstreetmap.org/search.php?q=rio+grande&viewbox=-51.47095%2C-29.95196%2C-50.82550%2C-30.13028&format=jsonv2&debug=1

## What result did you get?
a long list of similar and dissimilar named features:
![image](https://github.com/osm-search/Nominatim/assets/5018500/2104c294-0cda-48a3-abba-464336547953)

## What result did you expect?
this is desired result:
https://www.openstreetmap.org/relation/242762
it appeared in 7th place in search results.

## Further details
even enclosing the search expression in quotes didn't prevent randomly named features from appearing before the intended one in the search results, e.g.:
https://www.openstreetmap.org/way/33859167

**Comment by lonvia** [comment]
@mtmail is right, viewbox does not do a nearest search. It only slightly favours results in or near the viewbox.

That said, the 'Agno' and 'Bille' definitely should not show up in the results. This needs fixing.
