### ISSUE TITLE
POIs should estimate on-the-fly what parts of the address to use from their parent

### ISSUE THREAD

**Issue by PhilHa** [osm-search/Nominatim#328]
There are problems finding this address: Aegidienberger Straße 2, 53639, Königswinter
but the address is correctly and completely mapped at 50.6791744, 7.2708271

If I search for "Aegidienberger Straße 2, 53639, Honnef" instead (which is wrong as Honnef is the neighbor admin area) the correct address is found.
The corresponding way "Aegidienberger Straße" (141225144) stretches across two administrative areas (Ittenbach and Honnef). 
It seems that Nominatim somehow matches the whole street and all corresponding addresses to the area where the street is located for the most part instead of splitting the street at the boundary.

Is this a known issue?
Or is this even due to wrong mapping of the way 141225144 and it should be split at the boundary? (because in this case, the problem would not occur I guess)

**Comment by lonvia** [comment]
It is a known issue. The address is always taken from the street for optimization reasons. Splitting the road at the boundary will help as a workaround. However, be aware that doing so is frowned upon by some people as 'tagging for nominatim'.

**Comment by PhilHa** [comment]
wouldn't it be possible to split the way during parsing of the osm file?

**Comment by lonvia** [comment]
Searching of these addresses is possible by now. The address is still displayed wrongly, though.

**Comment by lonvia** [comment]
We can't really compute the addresses of every single place in the database on import. That would likely double the size of `place_addressline`, which is at a critical size already. And in any case it wouldn't solve the issue for random reverse points as it came up in #1094. So the address of the attached street must somehow do. The address computation already makes sure that for streets that go through multiple administrative boundaries all those boundaries get included. Have a look at the details page for your [Albertville example](https://nominatim.openstreetmap.org/details.php?osmtype=W&osmid=7836175&class=highway). You see that Albertville is there, just grayed out, which means that it is searchable but does not show up in the displayed address. The corresponding field in `place_addressline` is the `isaddress` column.

It might work out to change the `get_addressdata()` to compute isaddress field on the fly if (and only if) there are multiple rows with the same `rank_address` and `isarea = true` (i.e. do this for polygons only). This would mean that there are no additional is-in-polygon for the majority of cases, where the boundary affiliation is clear but a better address for the other case. The function would need to get the coordinates in question as additional  parameter to make this work.

If you want to try to implement something like this and do performance measurements to find out what the impact is, such a contribution would be very welcome. 

Note that photon is doing its own address computations based on `place_addressline` and the `isaddress` field. If the implementation does not break photon, that would really be a plus.

**Comment by gopi-ar** [comment]
>We can't really compute the addresses of every single place in the database on import. That would likely double the size of place_addressline, which is at a critical size already

I meant we could do this like photon does (from what I understand from a quick glance at its importer) by first taking a row from placex, matching all related elements from place_addressline and then storing it someplace else (say in the same placex row). I'm not sure whether this breaks forward geocoding though. This way though, we will no longer need other tables if all address lines are computed & stored at import. You're right that this doesn't solve the random lat/lons issue though, that will need realtime validation.

> It might work out to change the get_addressdata() to compute isaddress field on the fly if (and only if) there are multiple rows with the same rank_address and isarea = true (i.e. do this for polygons only). This would mean that there are no additional is-in-polygon for the majority of cases, where the boundary affiliation is clear but a better address for the other case. The function would need to get the coordinates in question as additional parameter to make this work.

That's an interesting way to attack this; will try this over the weekend.

**Comment by lonvia** [comment]
The address can be found now. Remains to take addr:* tags into account when computing the final address. That's addressed in (the still open) issue #148. Closing here.

**Comment by lonvia** [comment]
Hmm, no, not really closed. Should be doing the on-the-fly computation of what is and address and what not.
