### ISSUE TITLE
Random result when any of the polygon_output options is set to '1'

### ISSUE THREAD

**Issue by NickBevers** [osm-search/Nominatim#3282]
## What did you search for?
I used the reverse search to try and get a country (in my case I tried it with Belgium)
I used latitude 50.64028 and longitude 4.66671, which should be Belgium

This is the query I'm using: https://nominatim.openstreetmap.org/reverse?lat=50.64028&lon=4.66671&zoom=3&addressdetails=0&polygon_geojson=1&accept-language=en&polygon_threshold=0.001

## What result did you get?
Above query gives a random result each time. However if you don't specify a polygon output (eg. polygon_geojson, kml, svg or text) it returns the correct response which should be Belgium

## Further details
I tried dropping other parameters in the query but keeping the polygon_output, but that didn't give the result I desired.

**Comment by mtmail** [comment]
Adding `&debug=1` to the URL I can see the country code changing in the SQL query.

![image](https://github.com/osm-search/Nominatim/assets/3727288/b7a7174c-9134-4802-bd25-e56b1663b558)

But locally I wasn't able to replicate the issue yet which makes me wonder if this is caching or multi-threading related.

```
nominatim reverse --lat 50.6402 --lon 4.66671 --zoom 3 --polygon-output geojson --accept-language en --polygon-threshold 0.001 --format debug
```

**Comment by lonvia** [comment]
Thanks for reporting. This caused quite a few odd results. The fix is now live on all servers.

**Comment by NickBevers** [comment]
Awesome, thank you so much for the quick responses and implementation 👍
