### ISSUE TITLE
No result for 'KIoosplantsoen 749, Ridderkerk'

### ISSUE THREAD

**Issue by ALPHATROTS** [osm-search/Nominatim#3285]
## What did you search for?

KIoosplantsoen 749, Ridderkerk

https://nominatim.openstreetmap.org/ui/search.html?q=KIoosplantsoen+749+RIDDERKERK

## What result did you get?

no results

## What result did you expect?

correct gecoding.

on: https://www.openstreetmap.org/search?query=KLOOSPLANTSOEN%20749%20RIDDERKERK

I do get the address returned. Object id= 2729561796

**When the result in the right place and just named wrongly:** 

**When the result missing completely:**

**Comment by mtmail** [comment]
It's a hard-to-see typo in search query: The second character in `KIoosplantsoen 749, Ridderkerk` is upper i (`I`), not lowercase L (`l`). So Nominatim searches for `kioosplantsoen 749 ridderkerk`

**Comment by lonvia** [comment]
Closing as typing error. For the more general issue of spelling correction, we already have #759.
