### ISSUE TITLE
bbox bounded generic search doesn't work anymore

### ISSUE THREAD

**Issue by Juanjo-MC** [osm-search/Nominatim#3298]
Hi,

until recently, it was possible to perform generic searches (ie q=restaurants) when the query was bounded to a view box. It seems that it is not the case anymore.

Is this on purpose or is it a bug?

Cheers

**Comment by mtmail** [comment]
Likely related to https://github.com/osm-search/Nominatim/pull/3290 from last week. You can still run queries "restaurants near $latitude,$longitude" plus the bounded view filter. For example
https://nominatim.openstreetmap.org/ui/search.html?q=restaurants+near+54.32270%2C10.13547

Nominatim isn't the best tool to extract data from OSM. If you want to list every restaurant in a geographic area something like Overpass API will return all.

**Comment by lonvia** [comment]
That was not intentional. I'll do a fix but it will be a couple of days.
