### ISSUE TITLE
/reverse response missing ZIP code in Des Moines

### ISSUE THREAD

**Issue by kerrickstaley** [osm-search/Nominatim#3304]
## What did you search for?

https://nominatim.openstreetmap.org/reverse?lat=41.58512155948215&lon=-93.63531744348033

## What result did you get?

The returned address is
```Western Gateway, Des Moines, Polk County, Iowa, United States```

## What result did you expect?

I expected the result to contain the zipcode 50309.

## Further details

This lat/lon is in the middle of a public park. If I choose a coordinate pair in the neighborhood just south of this lat/lon it works:

 https://nominatim.openstreetmap.org/reverse?lat=41.58405278404359&lon=-93.63554607323444

I tried the instructions to "Make sure that the data you are looking for is in OpenStreetMap" in this issue template, but regardless of where I clicked on the map I couldn't find any ZIP code objects.

**Comment by mtmail** [comment]
Not a direct answer, I'm adding a map with nearby objects having postcode set

https://overpass-turbo.eu/s/1Gef

![image](https://github.com/osm-search/Nominatim/assets/3727288/54075754-82fe-4383-95ce-19bb7d7c8c42)
