### ISSUE TITLE
Wrong ZIP code returned for southwest Berkeley

### ISSUE THREAD

**Issue by kerrickstaley** [osm-search/Nominatim#3305]
## What did you search for?
https://nominatim.openstreetmap.org/reverse?lat=37.85353813271663&lon=-122.29008828881683

## What result did you get?
The ZIP code in the response is 94608.

## What result did you expect?
The ZIP code should be 94710. You can see this ZIP code on the [website of the business located at this site](https://www.berkeleybowl.com/). Also, various sites show the boundary of the 94608 ZIP code as being a few blocks south of this lat/lon.

## Further details
I think this is a mapping data issue in OSM, but I spent a while digging into the OSM data and I was not able to find where this bad ZIP code comes from.

**Comment by mtmail** [comment]
Nominatim doesn't use boundaries like other websites.

The HTML view https://nominatim.openstreetmap.org/ui/details.html?osmtype=W&osmid=52769190&class=shop has a link to documentation how Nominatim calculates postcodes. `Computed Postcode: 94703 (how?)` It also lists an Overpass API query to find nearby postcodes.

Specifically for that business you can add the postcode to OSM of course.

**Comment by mtmail** [comment]
This `addr:postcode=94608` entry seems off https://www.openstreetmap.org/way/105058255 Several miles away from other postcodes of the same value

**Comment by lonvia** [comment]
ZIP codes are a guess in Nominatim unless they are mapped in OSM as an area. This is not the case for the US. The point is close to a ZIP boundary, so will always be a hit and miss.

Adding `addr:postcode` to the addresses of the businesses in the area will fix at least the displayed ZIP for them.

Closing as won't fix.

**Comment by mtmail** [comment]
> Adding addr:postcode to the addresses of the businesses in the area will fix at least the displayed ZIP for them.

I added the postcode to the supermarket now. The reverse search returned the (named) parking lot though, not the supermarket. https://www.openstreetmap.org/way/52769273

> This addr:postcode=94608 entry seems off https://www.openstreetmap.org/way/105058255 Several miles away from other postcodes of the same value

I corrected that, too. Possible that after the next nightly update the parking lot shows the correct postcode then.
