### ISSUE TITLE
DeadLock while running whole planet build

### ISSUE THREAD

**Issue by MALKARAJ** [osm-search/Nominatim#3307]
**Software Environment (please complete the following information):**
- Nominatim version: v4.2.3
- Postgresql version: 15
- Postgis version: 3.3.3

**Hardware Configuration (please complete the following information):**
- RAM: 64GB
- number of CPUs: 32CORE
- type and size of disks: nvme and 1.5TB

getting deadlock for some queries while running process

will it cause data lose issue or is there any handling in the nominatim system itself for the deadlock

how to check whether data is imported properly( without missing any data)?

**Comment by otbutz** [comment]
Logs?

**Comment by MALKARAJ** [comment]
> Logs?

There is no discrepancy in the log

Our internal system detected the deadlock

**Comment by otbutz** [comment]
Well, there should at least be PostgreSQL logs when a deadlock is detected.

**Comment by MALKARAJ** [comment]
**log1**

> 024-01-21 19:36:30 GMT::@:[980199]:LOG: checkpoint starting: wal
> 2024-01-21 19:36:33 GMT:172.30.247.5(52154):nominat@nominatim:[597145]:ERROR: deadlock detected
> 2024-01-21 19:36:33 GMT:172.30.247.5(52154):nominatim@nominatim:[597145]:DETAIL: Process 597145 waits for ShareLock on transaction 188237230; blocked by process 597142.
> Process 597142 waits for ShareLock on transaction 188237231; blocked by process 597145.
> Process 597145: UPDATE placex
> SET indexed_status = 0, address = v.addr, token_info = v.ti,
> name = v.name, linked_place_id = v.linked_place_id
> FROM (VALUES (335701108, hstore(ARRAY[name], ARRAY[Río Boliche])::hstore, NULL::hstore, NULL::int, {"names": "{62612287,931034,98028}"}::jsonb)) as v(id, name, addr, linked_place_id, ti)
> WHERE place_id = v.id
> 
> Process 597142: UPDATE placex
> SET indexed_status = 0, address = v.addr, token_info = v.ti,
> name = v.name, linked_place_id = v.linked_place_id
> FROM (VALUES (335695588, hstore(ARRAY[name], ARRAY[Río Taura])::hstore, NULL::hstore, NULL::int, {"names": "{62482393,412578,98028}"}::jsonb)) as v(id, name, addr, linked_place_id, ti)
> WHERE place_id = v.id
> 
> 2024-01-21 19:36:33 GMT:172.30.247.5(52154):nominatim@nominatim:[597145]:HINT: See server log for query details.
> 2024-01-21 19:36:33 GMT:172.30.247.5(52154):nominatim@nominatim:[597145]:CONTEXT: while locking tuple (183244,1) in relation "placex"
> SQL statement "UPDATE placex SET linked_place_id = NEW.place_id WHERE place_id = linked_node_id"
> PL/pgSQL function placex_update() line 234 at SQL statement
> 2024-01-21 19:36:33 GMT:172.30.247.5(52154):nominatim@nominatim:[597145]:STATEMENT: UPDATE placex
> SET indexed_status = 0, address = v.addr, token_info = v.ti,
> name = v.name, linked_place_id = v.linked_place_id
> FROM (VALUES (335701108, hstore(ARRAY[name], ARRAY[Río Boliche])::hstore, NULL::hstore, NULL::int, {"names": "{62612287,931034,98028}"}::jsonb)) as v(id, name, addr, linked_place_id, ti)
> WHERE place_id = v.id

**log2**

```
2024-01-21 19:40:25 GMT::@:[980199]:LOG: checkpoint starting: wal
2024-01-21 19:40:33 GMT:172.30.247.5(52318):nominatim@nominatim:[600732]:ERROR: deadlock detected
2024-01-21 19:40:33 GMT:172.30.247.5(52318):nominatim@nominatim:[600732]:DETAIL: Process 600732 waits for ShareLock on transaction 188535767; blocked by process 600736.
Process 600736 waits for ShareLock on transaction 188535763; blocked by process 600732.
Process 600732: UPDATE placex
SET indexed_status = 0, address = v.addr, token_info = v.ti,
name = v.name, linked_place_id = v.linked_place_id
FROM (VALUES (336106130, hstore(ARRAY[name,alt_name], ARRAY[Velike Gredine I,Velike Gredine 1])::hstore, NULL::hstore, NULL::int, {"names": "{62703173,62703174,60945,2191044,5228,103}"}::jsonb)) as v(id, name, addr, linked_place_id, ti)
WHERE place_id = v.id

Process 600736: UPDATE placex
SET indexed_status = 0, address = v.addr, token_info = v.ti,
name = v.name, linked_place_id = v.linked_place_id
FROM (VALUES (336132649, hstore(ARRAY[name,alt_name], ARRAY[Velike Gredine II,Velike Gredine 2])::hstore, NULL::hstore, NULL::int, {"names": "{62703170,62703171,10259,60860,2191044,5228}"}::jsonb)) as v(id, name, addr, linked_place_id, ti)
WHERE place_id = v.id

2024-01-21 19:40:33 GMT:172.30.247.5(52318):nominatim@nominatim:[600732]:HINT: See server log for query details.
2024-01-21 19:40:33 GMT:172.30.247.5(52318):nominatim@nominatim:[600732]:CONTEXT: while locking tuple (11669327,8) in relation "placex"
SQL statement "UPDATE placex SET linked_place_id = NEW.place_id WHERE place_id = linked_node_id"
PL/pgSQL function placex_update() line 234 at SQL statement
2024-01-21 19:40:33 GMT:172.30.247.5(52318):nominatim@nominatim:[600732]:STATEMENT: UPDATE placex
SET indexed_status = 0, address = v.addr, token_info = v.ti,
name = v.name, linked_place_id = v.linked_place_id
FROM (VALUES (336106130, hstore(ARRAY[name,alt_name], ARRAY[Velike Gredine I,Velike Gredine 1])::hstore, NULL::hstore, NULL::int, {"names": "{62703173,62703174,60945,2191044,5228,103}"}::jsonb)) as v(id, name, addr, linked_place_id, ti)
WHERE place_id = v.id




```


@otbutz  sorry for the late reply here is the log file

**Comment by lonvia** [comment]
Does this have an impact in Nominatim in some way or did you just see the log messages from Postgres?

**Comment by MALKARAJ** [comment]
> Does this have an impact in Nominatim in some way or did you just see the log messages from Postgres?

nominatim doesn't show any error, internal monitoring tool detected this deadlock while running planet data

**Comment by lonvia** [comment]
Then this is nothing to worry about. The indexing process runs into deadlocks occasionally between the parallel threads. This is detected and corrected.

**Comment by MALKARAJ** [comment]
> Then this is nothing to worry about. The indexing process runs into deadlocks occasionally between the parallel threads. This is detected and corrected.

may i know how nominatim will resolve the deadlock ?
