### ISSUE TITLE
amenity=university should be handled like a landuse (campus) instead of a POI

### ISSUE THREAD

**Issue by jeeprisk** [osm-search/Nominatim#3308]
## What did you search for?

https://nominatim.openstreetmap.org/ui/details.html?osmtype=N&osmid=4216906302&class=highway
https://nominatim.openstreetmap.org/ui/details.html?osmtype=W&osmid=194552384&class=amenity
## What result did you get?
Search works, shows correct location and map and buildging.
Reverse does not work, as it changes the street name to a wrong location.

## What result did you expect?
show the correct street and building on the map

N/A

**Comment by mtmail** [comment]
Please add the URL of "reverse does not work". Also list explicitly the street name you're expecting.

**Comment by jeeprisk** [comment]
https://nominatim.openstreetmap.org/ui/details.html?osmtype=W&osmid=194552384&class=amenity
Loop Road

**Comment by mtmail** [comment]
You said you did reverse search, so which reverse search URL did you use? Which coordinates?

Why is Loop Road a better street result for a huge campus? On their official website https://www.kent.edu/ I see "800 E. Summit St." listed

**Comment by mtmail** [comment]
Sorry. You might need to explain everything again, in great detail, with full URLs for every action. I still don't understand and I want to avoid any confusion what to look for.

Is this the coordinates and URL you're looking at? https://nominatim.openstreetmap.org/ui/reverse.html?lat=41.1460482&lon=-81.3346588&zoom=18

**Comment by jeeprisk** [comment]
how about a teams call and i'll show you

**Comment by jeeprisk** [comment]
the 41.1460482,-81.3346588 are from a standard search of 635 Loop Rd., Kent, Ohio 44243, from the details page.
however when you plug those coordinates into a "reverse" search it fails and brings up the "cline road" info

**Comment by mtmail** [comment]
User didn't provide full URLs, closing as not reproducible.

**Comment by jeeprisk** [comment]
I did give you the coordinates in my responses
I also gave you the steps to recreate the issue.
I will record a browser steps video to show you the issue since you can't seem to get it.
Can someone else look at this ticket?
b

**Comment by jeeprisk** [comment]
41.1460482,-81.3346588 from Nominatim site shows 635 Loop Rd, Kent, Ohio 44243 in both google maps and bing maps correctly.
It returns 635 Loop Rd, Kent, Ohio 44243, which is Heer Hall on the Kent Campus.

But when you plug these coordinates into Nominatim "reverse search" it shows Cline Road.

**Comment by mtmail** [comment]
I think I understand now. Thank you for your patience and persistence.

https://nominatim.openstreetmap.org/ui/reverse.html?lat=41.1460482&lon=-81.3346588&zoom=18
![image](https://github.com/osm-search/Nominatim/assets/3727288/4540fc27-684e-43a6-a750-8bc5de120c67)

Question is why Nominatim, when given the coordinates direct on a building (41.1460482,-81.3346588 https://www.openstreetmap.org/way/201660634) tagged `university:building` (https://wiki.openstreetmap.org/wiki/Tag:building=university?uselang=en) returns the university campus (https://www.openstreetmap.org/way/194552384), not the university building.

When I do the searches I get different coordinates and street name (I get Summit Road, not Cline Road). This might be tiny data differences between the Nominatim servers installed in the US vs Europe.

I checked the same on (older) Nominatim version 4.3.2 I get the building as result (635 Loop Road). So it look like a recent software change.

**Comment by lonvia** [comment]
This got actually fixed by #3390.
