### ISSUE TITLE
Strange issue in Wildschönau

### ISSUE THREAD

**Issue by hungerburg** [osm-search/Nominatim#3318]
Preface: Wildschönau is a strange place, when it comes to addressing, so strange results excpected :) The local community is currently talking about revisiting tagging there, this gem surfaced:

* https://nominatim.openstreetmap.org/ui/search.html?q=Niederau+122
* https://nominatim.openstreetmap.org/ui/search.html?q=Oberau+122

Notes/observations
* Both searches yield same result on top
* official "street" names in Wildschönau contain a comma indeed!
* First returns exact match, second returns exact match in third position and non-match apart from number in top.
* Niederau node uses addr:place (unlisted), Oberau node uses addr:street.
* Is Oberau node missing a named place=suburb close by?

Should Oberau return on top even today when searched for? Can tagging be improved?

Thank You in advance!

PS: Please excuse troll post below

**Comment by Luzandro** [comment]
> * official "street" names in Wildschönau contain a comma indeed!

The street / place names don't contain a comma. The addresses do, although that's also only a workaround to prevent ambiguities. Pension Enzian at your given location uses the following address:
Wildschönauerstr. 122
A-6314 Wildschönau-Niederau

https://www.enzian.com/

See here for the mentioned community discussion: https://community.openstreetmap.org/t/strassen-welche-neben-dem-wirklichen-namen-auch-ortsteilbezeichnungen-im-name-haben/108473

**Comment by hungerburg** [comment]
I created the issue for the "gem". Sure, there are more ways to write down addresses and get mail delivered successfully. The canonical form of the "street" field in administrative address database has a comma in the value. I never talked about the value of highway name.

**Comment by hungerburg** [comment]
Will try another issue that attracts less nitpicking on details of no relevance.

**Comment by 987654321000123456789** [comment]
@osmhomeblog Johann, hol dir bitte Hilfe und achte darauf nicht irgendwann mal eine Vorladung wegen § 111 StGB zu bekommen.
