### ISSUE TITLE
Curious issue in Wildschönau

### ISSUE THREAD

**Issue by hungerburg** [osm-search/Nominatim#3319]
Wildschönau is a strange place, when it comes to addressing. During community talk a curious nominatim search result surfaced.

* https://nominatim.openstreetmap.org/ui/search.html?q=Niederau+122
* https://nominatim.openstreetmap.org/ui/search.html?q=Oberau+122

Search for Oberau yields hit for Niederau on top. How that? 

Notes/observations
* Official "street" part in Wildschönau addresses contains a comma indeed!
* Niederau node uses addr:place (unlisted), Oberau node uses addr:street (existing).
* Is place=suburb actually considered?

Thank you in advance!

**Comment by lonvia** [comment]
Until two days ago the [place node of Oberau](https://www.openstreetmap.org/node/29170980/history) had the same wikidata tag as [Gemeinde Wildschönau](https://www.openstreetmap.org/relation/1016861). This caused the two entities to be merged including their names. Hence, everything in Wildschönau was findable via 'Oberau'. I've now kicked the server to refresh all addresses and everything should be fine.

The lack of update of addresses when place nodes associations change is already captured in #1539.
