### ISSUE TITLE
实际返回地址的经纬度与查询时的经纬度不一致

### ISSUE THREAD

**Issue by cwy1996** [osm-search/Nominatim#3322]
/reverse?lat=28.664308&lon=121.411646

但实际结果却是如下的
![image](https://github.com/osm-search/Nominatim/assets/76695859/39bdeb8b-ae29-4786-bb03-fd75e93904b3)

**Comment by lonvia** [comment]
The returned position is that of the object. It is close to the position you have requested. All is as expected.

Please use the issue templates when reporting a bug and carefully read the instructions in there. Can I also kindly request to use a translation tool and do the request in English. The issue will be read by many people, so it is more efficient to do the Chinese -> English translation once while writing, than to do it many times while reading.

**Comment by cwy1996** [comment]
> 返回的位置是对象的位置。它接近您所要求的位置。一切都如预期。
> 
> 报告错误时请使用问题模板并仔细阅读其中的说明。我还可以请求使用翻译工具并用英语提出请求吗？该期刊会被很多人阅读，因此在写作时进行一次中文->英文翻译比在阅读时进行多次翻译效率更高。

Thanks
