### ISSUE TITLE
"nominatim refresh --word-counts" breaks the database after recent commit

### ISSUE THREAD

**Issue by pawel-wroniszewski** [osm-search/Nominatim#3330]
I compiled code from master (f523c01571f2aacd9314f67216e408a5abd8327f) and run Python frontend in Ubuntu 22.04 docker image 

I run "nominatim refresh --word-counts" as a nominatim user on the database which was imported with a previous Nominatim version (4.3.2). Afterwards, all requests fail with the error:

2024-02-06 15:27:54.921 UTC [101] www-data@nominatim ERROR:  must be owner of table word    
2024-02-06 15:27:54.921 UTC [101] www-data@nominatim STATEMENT:  DROP TABLE IF EXISTS "word"
 
**Software Environment (please complete the following information):**
- Nominatim version: f523c01571f2aacd9314f67216e408a5abd8327f
- Postgresql version: 14
- Postgis version: 3.2.0
- OS: Ubuntu 22.04 

**Hardware Configuration (please complete the following information):**
- RAM: 128 GB
- number of CPUs: 16
- type and size of disks: SSD 2TB

**Postgresql Configuration:**
shared_buffers = 32GB
maintenance_work_mem = 6GB
autovacuum_work_mem = 2GB
work_mem = 160MB
effective_cache_size = 96GB
synchronous_commit = off
max_wal_size = 8GB
checkpoint_timeout = 10min
checkpoint_completion_target = 0.9
max_connections = 200
random_page_cost = 1.1
effective_io_concurrency = 200

**Nominatim Configuration:**

**Additional context**
This seems to be related to the recent commit: https://github.com/osm-search/Nominatim/commit/81eed0680cd2a8b5c53217ab2996a43ab17f5056

It works with no issues with the version compiled from master before that commit (version 33c0f249b1a9bc716bcb89078c4a766766cbe94f)

**Comment by lonvia** [comment]
As a quick fix do `GRANT SELECT ON word TO "www-data"`.
