### ISSUE TITLE
Update location information

### ISSUE THREAD

**Issue by DeveloperMarius** [osm-search/Nominatim#3334]
Hello,

I hope I'm asking in the right place.
We are a startup that manages location information for restaurants. We currently support Google, Apple and Bing and want to extend the support for openstreetmap. 
I wanted to ask where we can contribute up to date data linke opening hours etc.
Alternativ where do you get your location information from?

I am looking forward to your feedback,
Marius Karstedt

**Comment by mtmail** [comment]
The Nominatim software gets its data from OpenStreetMap.

I see you're based in Germany so I'd contact the German community first. https://openstreetmap.de/community/ (which points to https://community.openstreetmap.org/)

They'll be able to point you to relevant documentation or other communication channels.

This discussion thread looks similar to what you're planning https://community.openstreetmap.org/t/organised-editing-teleclinic-gmbh-apothekendaten/6262

**Comment by DeveloperMarius** [comment]
Thank you!
