### ISSUE TITLE
does not include region, level=4 administrative boundary in "Zakarpattia Oblast"

### ISSUE THREAD

**Issue by bezdna** [osm-search/Nominatim#3343]
does not include the region, the administrative border of level=4 is the "Zakarpattia Oblast"

## What did you search for?

https://nominatim.openstreetmap.org/ui/details.html?osmtype=N&osmid=4700347179&class=place

## What result did you get?
like: Мукачівська міська громада(7) >Мукачівський район(6) >Україна(2)
>>>>

## What result did you expect?
https://nominatim.openstreetmap.org/ui/details.html?osmtype=N&osmid=4118676009&class=office
like: Вінницька міська громада(7) >Вінницький район(6) >Вінницька область(4)>Україна(2)

**Comment by bezdna** [comment]
the same thing happens with the neighboring region "Ivano-Frankivsk Oblast " https://nominatim.openstreetmap.org/ui/details.html?osmtype=N&osmid=337580758&class=place

**Comment by lonvia** [comment]
Looks like the relations for the two oblasts were broken and had been repaired only recently. I've started a reindexing of the regions. Should be fixed on all servers in a couple of minutes.

**Comment by bezdna** [comment]
sorry but not work yet
maybe there is another problem?

**Comment by bezdna** [comment]
> Looks like the relations for the two oblasts were broken and had been repaired only recently. I've started a reindexing of the regions. Should be fixed on all servers in a couple of minutes.

sorry but not work yet
maybe there is another problem?

**Comment by lonvia** [comment]
The relation is broken again. There is a huge hole here now: https://www.openstreetmap.org/relation/72488#map=14/48.2091/24.5389

**Comment by bezdna** [comment]
> The relation is broken again. There is a huge hole here now: https://www.openstreetmap.org/relation/72488#map=14/48.2091/24.5389

I fixed it
How long does it take for the cache to be updated for the region(oblast) and the community(gromada)?
