### ISSUE TITLE
No polygon data with postalcode

### ISSUE THREAD

**Issue by blankse** [osm-search/Nominatim#3361]
## What did you search for?

https://nominatim.openstreetmap.org/search?format=jsonv2&polygon_geojson=1&postalcode=91550&countrycodes=de

## What result did you get?

No geojson data

## What result did you expect?

geojson data like in other postal code searches

## Further details

The error was already fixed in April 2023. But now it's back again. Seems to affect many more or all postcodes now.

See: https://github.com/osm-search/Nominatim/issues/3025

**Comment by lonvia** [comment]
The Python frontend has a preference for the postcode centroids over the postcode areas. That is in principle a good thing because it reduces false positive results. We just need a fast way to find potential postcode areas in placex to complete the data.

**Comment by lonvia** [comment]
Fixed in #3362.
