### ISSUE TITLE
Support for key "lock_name"

### ISSUE THREAD

**Issue by philippelatulippe** [osm-search/Nominatim#3365]
### Problem
Locks are tagged as regular waterways with an additional tag `lock=yes`. This means that their `name` tag is often simply the name of the river or canal, while the name of the lock itself is tagged in `lock_name`, as recommended in [Key:lock](https://wiki.openstreetmap.org/wiki/Key:lock). Nominatim doesn't see this tag, so these locks cannot be searched for by name. 

### Solution
Add the key `lock_name` to the list of tags that are considered names.

### Alternatives
Couldn't think of any. Hopefully this is a straightforward solution.

### Additional context
Searching for the name of a lock is useful not just for boaters, but also for regular folks who live in cities that have many of them, where they are often gathering places. The name of locks are also mentioned in the news and blogs posts, for instance the [Weerdsluis](https://www.openstreetmap.org/way/107194897) which is often talked about internationally due to its 'fish doorbell'.

**Comment by lonvia** [comment]
If only the tag name was `lock:name`, then it could be easily handled in the same way as `bridge:name` but it looks like the tag vastly predates the introduction of the colon notation.

I'm tempted to just internally rewrite the tag to `lock:name`. The drawback is that it would then also show up like this in the details and people might wonder where the tag comes from.
