### ISSUE TITLE
Town 'Buja' not returned in Italy address search

### ISSUE THREAD

**Issue by st4vrogin** [osm-search/Nominatim#3371]
## What did you search for?

via sottocolle 66, buja

https://nominatim.openstreetmap.org/search?q=66 via sottocolle, buja&format=json&addressdetails=1

## What result did you get?

JSON format reports city incorrectly (Tonzolano as village) while the key (addr:city) in OSM XML format is right (Buja)

JSON Format

```json
   "address": {
            "house_number": "66",
            "road": "Via Sottocolle",
            "hamlet": "Ursinins Piccolo",
            "village": "Tonzolano",
            "county": "Udine",
            "ISO3166-2-lvl6": "IT-UD",
            "state": "Friuli-Venezia Giulia",
            "ISO3166-2-lvl4": "IT-36",
            "postcode": "33030",
            "country": "Italia",
            "country_code": "it"
        },
```

## What result did you expect?

```json
   "address": {
            "house_number": "66",
            "road": "Via Sottocolle",
            "hamlet": "Ursinins Piccolo",
            "town": "Buja",
            "county": "Udine",
            "ISO3166-2-lvl6": "IT-UD",
            "state": "Friuli-Venezia Giulia",
            "ISO3166-2-lvl4": "IT-36",
            "postcode": "33030",
            "country": "Italia",
            "country_code": "it"
        },
```

Tonzolano is just another hamlet in Buja, different from Ursinins Piccolo.

**Output of OSM XML**

https://www.openstreetmap.org/api/0.6/node/3624918345

```xml
<osm version="0.6" generator="CGImap 0.9.0 (1949097 spike-07.openstreetmap.org)" copyright="OpenStreetMap and contributors" attribution="http://www.openstreetmap.org/copyright" license="http://opendatacommons.org/licenses/odbl/1-0/">
<node id="3624918345" visible="true" version="1" changeset="32281650" timestamp="2015-06-29T10:32:52Z" user="RAFVG import" uid="2658983" lat="46.2075060" lon="13.1117967">
<tag k="addr:city" v="Buja"/>
<tag k="addr:housenumber" v="66"/>
<tag k="addr:postcode" v="33030"/>
<tag k="addr:street" v="Via Sottocolle"/>
</node>
</osm>
```

**Comment by mtmail** [comment]
https://nominatim.openstreetmap.org/ui/details.html?osmtype=N&osmid=3624918345&class=place

Nominatim merges two map features when they represent the same (relation https://www.openstreetmap.org/relation/179194 and node https://www.openstreetmap.org/node/66503091). The node is tagged as `place=village`. Try reviewing and changing that.

**Comment by st4vrogin** [comment]
Degraded Tonzolano to hamlet (which is in fact part of Buja) in OSM so that Buja will be the only village in its administrative boundaries
