### ISSUE TITLE
Auckland returns wrong centre point

### ISSUE THREAD

**Issue by d-meehan** [osm-search/Nominatim#3372]
## What did you search for?
Auckland - https://nominatim.openstreetmap.org/ui/search.html?q=auckland

## What result did you get?
The search correctly returns R17000522, but the centre point is -36.5412811,174.5506104914412
## What result did you expect?
For R17000522 OSM correctly has a centre point of -36.5359, 174.8998 https://www.openstreetmap.org/relation/17000522

**Comment by lonvia** [comment]
The [Auckland place node](https://www.openstreetmap.org/node/292806332) and the [Auckland admin boundary](https://www.openstreetmap.org/relation/17000522) do not describe the same object according to their wikidata tags. The former is [the city of Auckland](https://www.wikidata.org/wiki/Q37100) while the latter is linked to the [Auckland region](https://www.wikidata.org/wiki/Q726917). To add to the confusion, both objects have wikipedia tags that indeed point to the city of Auckland, i.e. they contradict the wikidata tags.

Then there is [another Auckland relation](https://www.openstreetmap.org/relation/2094141) which also points to the wikidata page for Auckland region and the wikipedia page for Auckland, has the same area as relation 17000522 but a different admin_level. I presume that this is the actual 'Auckland region' relation.

If you fix wikipedia and wikidata tags for these three objects, linking between them should work between them, which in turn will mean that the result gets the center point where the node is.

Closing as data issue.

**Comment by d-meehan** [comment]
Thank you for the quick clarification, I'll try and fix those tags.
