### ISSUE TITLE
I cant write down "utca" for hungarian street name 

### ISSUE THREAD

**Issue by Daniel2001777** [osm-search/Nominatim#3379]
So when I search hungarian street name that ends with "utca" it is the hungarian name for street, there is an error: Error fetching data from /search.php?q=Ispot%C3%A1ly%20utca&polygon_geojson=1&format=jsonv2 ().

For example: https://nominatim.openstreetmap.org/ui/search.html?q=Ispot%C3%A1ly+utca .

And the problem occours every hungarian street name ends with "utca", but it should provide a result for the searching for example Ispotály utca.

Thanks for the support.

**Comment by lonvia** [comment]
Fixed in 78c19bc006d5957f183968d086226be4b2b65fe3.
