### ISSUE TITLE
geocodejson format can contain duplicate admin level keys

### ISSUE THREAD

**Issue by mtmail** [osm-search/Nominatim#3382]
https://nominatim.openstreetmap.org/reverse?accept-language=en&addressdetails=1&format=geocodejson&lat=41.00488&lon=28.98016

returns level4 twice

```
  "label": "Agora Guesthouse, 10, Amiral Tafdil Sokağı, Cankurtaran Mahallesi, Istanbul, Fatih, Istanbul, Marmara Region, 34122, Turkey",
  "admin": {
    "level8": "Cankurtaran Mahallesi",
    "level4": "Istanbul",
    "level6": "Fatih",
    "level4": "Istanbul",
    "level3": "Marmara Region"
  }
```

It's not obvious because tools like JSON browser plugin, [jq](https://jqlang.github.io/jq/) or some parsers ignore the second occurance silently. In fact duplicate keys seem to be allowed https://stackoverflow.com/questions/21832701/does-json-syntax-allow-duplicate-keys-in-an-object . The parser I'm using fails when it encounters a duplicate key.

I'll provide a PR for the output formatting but I wonder if the issue is deeper or if it's possible the values for the same level could also be different.

**Comment by lonvia** [comment]
Place nodes with `admin_level` again. They tend to be set for capitals and then refer to admin level of the administration they are the capital for. The geocodejson formatter should ignore everything that isn't a `boundary=administrative`.
