### ISSUE TITLE
Timeouts on nominatim.osm.org service

### ISSUE THREAD

**Issue by JaimeSistemas** [osm-search/Nominatim#3405]
I am trying to consume the webservices to get directions but it returns this error message
I hope you can help me
Error en la descarga del recurso solicitado.

**Comment by mtmail** [comment]
Without any details people can't help.

**Comment by JaimeSistemas** [comment]
> Without any details people can't help.

The message that the webservice returns to me is, "Error downloading the requested resource"
Everything was working fine it just stopped responding

![nominatib](https://github.com/osm-search/Nominatim/assets/168585107/766e0bb3-4205-43b4-9959-5140f412f4f2)

**Comment by mtmail** [comment]
Thanks, the URL and code is helpful. Most likely your IP address got blocked. See https://operations.osmfoundation.org/policies/nominatim/ for instructions. For example you need to set a user agent string. It will unblock automatically but it can take up to 24 hours.

**Comment by Tuxrug** [comment]
I started getting intermittent HTTP 500 errors in a powershell script I was using despite a user agent string set and (admittedly short-lived) result cacheing. I checked some queries from https://nominatim.openstreetmap.org/ and am getting slow responses with intermittent errors there as well on two machines on different networks. I'm trying to get screenshots but it seems to be clearing up now.

**Comment by mtmail** [comment]
@Tuxrug Good observation. nominatim.openstreetmap.org usage graphs show a lot of slow queries today. That might be something for https://github.com/openstreetmap/operations/issues (I don't have any admin access to those servers) 
![image](https://github.com/osm-search/Nominatim/assets/3727288/acba1e94-a28d-429a-b0dc-8f3a44dbb6fe)

**Comment by JaimeSistemas** [comment]
Very good information to keep in mind if this happens again. Case closed, thanks for the help!!


> @Tuxrug Good observation. nominatim.openstreetmap.org usage graphs show a lot of slow queries today. That might be something for https://github.com/openstreetmap/operations/issues (I don't have any admin access to those servers) ![image](https://private-user-images.githubusercontent.com/3727288/326963226-acba1e94-a28d-429a-b0dc-8f3a44dbb6fe.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTQ1MTM0NjQsIm5iZiI6MTcxNDUxMzE2NCwicGF0aCI6Ii8zNzI3Mjg4LzMyNjk2MzIyNi1hY2JhMWU5NC1hMjhkLTQyOWEtYjBkYy04ZjNhNDRkYmI2ZmUucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDQzMCUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA0MzBUMjEzOTI0WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9MDNlMjBiODczYmFkZjcxZDkwNjk4ZTBhYTAzZmUwMmQ1YTU2ODg1OGE2ZmRjYTI5NjE1ZWYwM2MyNTJhYmY3MSZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.hL-kwNZ-ztnL2-N7PFyYBafgzWlCuwYIaPyCcLujmq8)

**Comment by lonvia** [comment]
Operational issue which resolved itself in the meantime.
