### ISSUE TITLE
San Bernadino, California only finds county, but not the city

### ISSUE THREAD

**Issue by wgds60** [osm-search/Nominatim#3442]
## What did you search for?

Search: San Bernadino, California

https://nominatim.osm.org/ui/search.html?q=san+bernadino%2C+california

## What result did you get?

Only the San Bernadino County but not San Bernadino City.

## What result did you expect?

San Bernadino City

OSM Node: https://www.openstreetmap.org/node/150958886
preferably with the city relation attached: https://www.openstreetmap.org/relation/253639 to get a polygon of San Bernadino (City)

**When the result in the right place and just named wrongly:** 

**When the result missing completely:**

## Further details

Even trying a San Bernadino, San Bernadino, California    (that is: City, County, State) does not help. E.g. this helps with Matera, Matera, California  (where Matera, California retuns the county, not the city, but Matera, Matera, California returns the city)

In general, I think it would be nice if the importance of a city is higher than a county if both share a name.

**Comment by mtmail** [comment]
https://www.openstreetmap.org/relation/396509 and https://www.openstreetmap.org/node/316944822 both represent the county. The node has a shorter name though. I'd say rename the node to match the relation.

**Comment by wgds60** [comment]
So that is about the county, but why does the city not turn up at all?

Is the county relation duped as a duplicate (in regard to the label node) and with this kills the admin_centre that is also the admin_centre of the city from being processed?

**Comment by wgds60** [comment]
Oh my, the problem exists here at keyboard as the typo (San Bernadino instead of San Bernardino) did not help at all. With San Bernardino the city is found.

**Comment by lonvia** [comment]
That actually means you found a typo in the OSM data. The county relation has `official_name=County of San Bernadino`. Let me fix that..

**Comment by wgds60** [comment]
Yes, San Bernardino seems to be prone for a typo, so at least it's not only me. I also found that typo at the San Bernardino County DA bulding ( https://www.openstreetmap.org/way/338720949 ) but missed the one in the official_name of the county.

**Comment by lonvia** [comment]
Makes you wonder how many of the dozen [other roads named San Bernadino](https://nominatim.openstreetmap.org/ui/search.html?q=san+bernadino&countrycodes=us&limit=100) in the US are typos. We'll never know without a survey. At least the one in [Auckland, New Zealand](https://www.openstreetmap.org/way/40670572) seems correct without the 'r'.
