### ISSUE TITLE
Place returned by Overpass not found with Nominatim `Search By ID`

### ISSUE THREAD

**Issue by GniLudio** [osm-search/Nominatim#3452]
## What did you search for?
When I use the following query in Overpass for the german state `Schleswig-Holstein`  ([Link](https://overpass-turbo.eu/s/1NbC))
```
[out:csv(::id)];
relation['de:amtlicher_gemeindeschluessel'='01'];
out;
```
it returns two relations which represent roughly the same area ([51529](https://www.openstreetmap.org/relation/51529), [62775](https://www.openstreetmap.org/relation/62775))
```csv
@id
51529
62775
```

If I use the second ID for `Search By ID` in Nominatim ([Link](https://nominatim.openstreetmap.org/ui/details.html?osmtype=R&osmid=62775)), I get an error:
```
No place with that OSM ID found. 
```

## What result did you get?
`No place with that OSM ID found.`

## What result did you expect?
The details of the relation with ID `62775`: [Relation 62775 on OpenStreetMap](https://www.openstreetmap.org/relation/62775)

## Further details
> None.

**Comment by mtmail** [comment]
Nominatim by default doesn't import `boundary=land_area` (https://github.com/osm-search/Nominatim/blob/master/settings/import-extratags.lua near line 85). As you've seen it often leads to duplicates with `boundary-administrative` of the same name.

What did you hope to be able to do with the result data?

**Comment by GniLudio** [comment]
> Nominatim by default doesn't import `boundary=land_area` (https://github.com/osm-search/Nominatim/blob/master/settings/import-extratags.lua near line 85). As you've seen it often leads to duplicates with `boundary-administrative` of the same name.
> 
> What did you hope to be able to do with the result data?

I want to get the GeoJSON of places in germany by their `'de:amtlicher_gemeindeschluessel'` and `'de:regionalschluessel'`.
So I get the IDs from Overpass and then tried to get the GeoJSON from Nominatim, but that didn't work for this one.

But now I know that I should just ignore `land_area`s.

**Comment by mtmail** [comment]
https://github.com/tyrasd/osmtogeojson can convert Overpass output to geojson. There are many (https://github.com/tmcw/awesome-geojson), some even have the same name, but this one worked for me on a similar project.
