### ISSUE TITLE
"Off license" is not understood in en_US

### ISSUE THREAD

**Issue by ZeLonewolf** [osm-search/Nominatim#3473]
I searched for liquor stores, and I was confused that the results returned "off license" instead of "liquor store".  I discovered that this is a British term.  Is it possible to localize this to "liquor store" in en_US? 

![image](https://github.com/osm-search/Nominatim/assets/3254090/f8e11cb8-3b44-4032-aea7-194f511e56b9)

**Comment by mtmail** [comment]
This is configured at https://wiki.openstreetmap.org/wiki/Nominatim/Special_Phrases Look for language 'en' and shop=alcohol. There's no distinction between US English vs British English. OpenStreetMap has it roots in Britain so a lot of defaults are British English.

The output "Off License" you see on the OSM Website can be translated, too. See 'Nominatim prefixes' at https://github.com/openstreetmap/openstreetmap-website/blob/master/CONTRIBUTING.md#i18n I'm not familiar enough with Translatewiki tool. There's two English files but I can't find shop/alcohol in them. You might need to ask over in that repository.

**Comment by lonvia** [comment]
Closing here in favour of https://github.com/openstreetmap/openstreetmap-website/issues/4975.
