### ISSUE TITLE
Searching for adits

### ISSUE THREAD

**Issue by hungerburg** [osm-search/Nominatim#3474]
## What did you search for?

I searched for the name of a (disused) adit.

## What result did you get?

I got an empty result.

## What result did you expect?

I expected to find the node where it is mapped.

**When the result missing completely:**

Here a sample, https://www.openstreetmap.org/node/7443433162 rsp. https://www.openstreetmap.org/search?query=Erzherzogsbergstollen#map=19/47.32524/11.47636

## Further details

I am aware that adits can be hazards for people not knowledgeable in subject matter. I am aware the people not knowledgeable in subject matter may spoil adits. There may be extra considerations needed to just show them point-blank.

**Comment by mtmail** [comment]
We started limiting importing `man_made` features to a positive list of values. I've added adits now (https://github.com/osm-search/Nominatim/pull/3480) but it will need a reimport of the database and that's usually only done after a big software version update. Effectively it will take weeks to possibly months before you can search for it on openstreetmap.org.
