### ISSUE TITLE
Private waste disposals should be ranked lower than residential buildings

### ISSUE THREAD

**Issue by matkoniecz** [osm-search/Nominatim#3475]
## What did you search for?

https://nominatim.openstreetmap.org/ui/search.html?q=Na+B%C5%82onie+9%2C+Krak%C3%B3w

## What result did you get?

waste disposal, then apartment buildings

![screen01](https://github.com/user-attachments/assets/8686bb93-de84-4fc1-86e6-1249a40291f8)

## What result did you expect?

apartment building, then nothing or its waste disposal

## Further details

Maybe private waste disposals should not be treated as POI at all?

Yes, I know it is micromapping

**Comment by lonvia** [comment]
This is essentially a duplicate of the very, very old issue #280. 9 years on I still don't have a good idea for a metric to classify the importance of different POI types.

That said, I shall "solve" this particular issue by removing `amenity=waste_disposal` from the list of objects interesting for Nominatim. Wiki says they are _not primarily for use by passing pedestrians_, so not really a general interest POI and not something you'd search by name. (On the side: there are 3000+ with a name and they look all suspicious.)
