### ISSUE TITLE
Search Suggestions

### ISSUE THREAD

**Issue by akshayg147** [osm-search/Nominatim#3495]
Problem:
I'm always frustrated when I use the search functionality on OpenStreetMap and do not receive any suggestions as I type. This lack of search suggestions makes it difficult and time-consuming to find specific locations, especially when compared to other mapping services that provide real-time suggestions and autocomplete features.

Solution I'd like:
I would like to see the implementation of search suggestions for city, road, and other geographical queries on OpenStreetMap. This feature should provide real-time suggestions as users type in the search bar, helping them to quickly and accurately find their desired locations. The suggestions should be relevant and prioritize popular or nearby locations. Additionally, an autocomplete functionality would further enhance the user experience by allowing users to quickly complete their search queries.

Alternative Solution:
An alternative solution could be to integrate with existing search APIs that already offer suggestion features, but this might not align with the open-source nature of OpenStreetMap. Developing an in-house solution tailored to OpenStreetMap's unique data and user base seems like the most effective approach.

**Additional context**
For example, when a user types "New Y" in the search bar, the system could provide suggestions such as "New York, USA," "New York Avenue, Washington, D.C.," etc. Implementing this feature would greatly enhance the usability of OpenStreetMap, making it more user-friendly and efficient.

https://github.com/user-attachments/assets/f91e1047-2aaa-4b3d-a728-fba4e985a56a

**Comment by otbutz** [comment]
I think this is the wrong place to discuss missing features of the openstreetmap.org website. Technically this is already solved by [Photon](https://github.com/komoot/photon).

**Comment by mtmail** [comment]
I'll close it here. It's not on the road map for Nominatim (yet). It's a feature requests as old as Nominatim itself (together with typo tolerance) and we have a good-enough alternative with Photon to point users and server administrators to at the moment.
