### ISSUE TITLE
prefer matching to both city name and administrative area name over matching to only administrative boundary

### ISSUE THREAD

**Issue by matkoniecz** [osm-search/Nominatim#3496]
## What did you search for?

https://nominatim.openstreetmap.org/ui/search.html?q=%C5%81%C3%B3d%C5%BA%2C+Wr%C3%B3blewskiego+31

## What result did you get?

https://nominatim.openstreetmap.org/ui/details.html?osmtype=N&osmid=7299640257&class=place

https://www.openstreetmap.org/node/7299640257

## What result did you expect?

https://nominatim.openstreetmap.org/ui/details.html?osmtype=W&osmid=42835103&class=shop

https://www.openstreetmap.org/way/42835103

## Further details

I am honestly confused why the correct match is preferred. Yes, https://www.openstreetmap.org/node/7299640257 technically is in Łódź Voivodeship. Both https://www.openstreetmap.org/way/42835103 is also there and also in city Łódź!

In addition, at least in Poland, matching city name is much stronger indicator of being good match than matching to administrative area name.

I thought that there may be some confusion with `name:en` tags - but also https://nominatim.openstreetmap.org/ui/search.html?q=%C5%81%C3%B3d%C5%BA%2C+Wr%C3%B3blewskiego+31&accept-language=pl gives the same results.

**Comment by mtmail** [comment]
Query "Łódź, Wróblewskiego 31"

The second result is in the street "Generała Walerego Wróblewskiego".  Is that street locally known as "Wróblewskiego"?
https://nominatim.openstreetmap.org/ui/details.html?osmtype=W&osmid=42835103&class=shop

**Comment by matkoniecz** [comment]
that would explain things, I opened https://www.openstreetmap.org/note/4364379
