### ISSUE TITLE
idx_placex_geometry_reverse_lookupPlaceNode index not checked with check_db cmd

### ISSUE THREAD

**Issue by oOHenry** [osm-search/Nominatim#3501]
**Describe the bug**
the index idx_placex_geometry_reverse_lookupPlaceNode doesn't get checked from: `nominatim admin --check-database`

https://github.com/osm-search/Nominatim/blob/master/src/nominatim_db/tools/check_database.py#L102

**Software Environment:**
- Nominatim version: 4.4.0

**Comment by mtmail** [comment]
Did you see https://nominatim.org/release-docs/latest/admin/Migration/#420-430 on how to create the index in case it's missing?

**Comment by oOHenry** [comment]
yes I did, but thanks for the hint :)
