### ISSUE TITLE
Searching for Ogrodowa street from Łódź city returns all Ogrodowa streets from the entire Łódź Province

### ISSUE THREAD

**Issue by Jrk-Ldz** [osm-search/Nominatim#3507]
## What did you search for?

[Ogrodowa 15, Łódź](https://nominatim.openstreetmap.org/search?q=Ogrodowa%2015,%20%C5%81%C3%B3d%C5%BA&format=json&addressdetails=1) – where _Ogrodowa_ is the name of the street, _15_ is the house number (it's common in Poland to put the house number after the street name), and _Łódź_ is the name of the city.

## What result did you get?

* [15, Ogrodowa, Konstantynów Łódzki, powiat pabianicki, województwo łódzkie, 95-050, Polska](https://openstreetmap.org/way/135175526)
* [15, Ogrodowa, Starowa Góra, gmina Rzgów, powiat łódzki wschodni, województwo łódzkie, 95-030, Polska](https://openstreetmap.org/node/3682981083)
* [15, Ogrodowa, Samotnik, Łagiewniki Nowe, gmina Zgierz, powiat zgierski, województwo łódzkie, 95-002, Polska](https://openstreetmap.org/way/897060803)
* [15, Ogrodowa, Grocholice, Bełchatów, powiat bełchatowski, województwo łódzkie, 97-400, Polska](https://openstreetmap.org/node/2586606316)
* [15, Ogrodowa, Pabianice, powiat pabianicki, województwo łódzkie, 95-200, Polska](https://openstreetmap.org/node/3180364572)
* [15, Ogrodowa, Wania, Warta, gmina Warta, powiat sieradzki, województwo łódzkie, 98-290, Polska](https://openstreetmap.org/node/2478024029)
* [15, Ogrodowa, Krzeczów, gmina Wierzchlas, powiat wieluński, województwo łódzkie, 98-324, Polska](https://openstreetmap.org/node/2583613088)
* [15, Ogrodowa, Piaski, Maluszyn, gmina Żytno, powiat radomszczański, województwo łódzkie, 97-532, Polska](https://openstreetmap.org/node/3878839354)
* [15, Ogrodowa, Dąbrówka-Sowice, gmina Zgierz, powiat zgierski, województwo łódzkie, 95-100, Polska](https://openstreetmap.org/node/4362500275)
* [15, Ogrodowa, Wrząca-Parcela, Wrząca, gmina Lutomiersk, powiat pabianicki, województwo łódzkie, 95-083, Polska](https://openstreetmap.org/node/3161798301)

## What result did you expect?

* [Muzeum Miasta Łodzi, 15, Ogrodowa, Bałuty-Centrum, Stare Miasto, Łódź-Bałuty, Łódź, województwo łódzkie, 91-065, Polska ](https://openstreetmap.org/node/432504799)
* [Pałac Izraela Poznańskiego w Łodzi, 15, Ogrodowa, Bałuty-Centrum, Stare Miasto, Łódź-Bałuty, Łódź, województwo łódzkie, 91-065, Polska](https://openstreetmap.org/way/37550695)

## Further details

[Łódź](https://www.openstreetmap.org/relation/2907537) (or Lodz if using ASCII characters without diacritics) is the capital of the [Łódź Province](https://www.openstreetmap.org/relation/224458) in Poland. The name _Łódź_ appears both in the name of the city and the province. And this may be the cause of the problem. I think someone is more likely to search for an address in a given city, not in the entire province.

**Comment by mtmail** [comment]
Strange indeed. Debug output suggests Nominatim first finds the museum

https://nominatim.openstreetmap.org/search.php?q=Ogrodowa+15%2C+%C5%81%C3%B3d%C5%BA&format=jsonv2&debug=1

```
Results

[0.700]
    PLACEX(Muzeum Miasta Łodzi, type=(tourism,museum), rank=30, osm=[N432504799](https://www.openstreetmap.org/node/432504799), cc=pl, importance=0.29350)
[0.700]
    PLACEX(Pałac Izraela Poznańskiego w Łodzi, type=(historic,palace), rank=30, osm=[W37550695](https://www.openstreetmap.org/way/37550695), cc=pl, importance=0.28683)
[0.700]
    PLACEX(Pałac Izraela Poznańskiego w Łodzi, type=(tourism,attraction), rank=30, osm=[W37550695](https://www.openstreetmap.org/way/37550695), cc=pl, importance=0.28683)

TOTAL: 3
```

and then during "Query address details" step returns a new set of results.

**Comment by lonvia** [comment]
It's a bit tricky to find but the Islandic name for https://www.openstreetmap.org/node/505043292 has the raw `Łódź`, which provides a perfect match. Change this to the islandic equivalent of 'Lodz province' (hérað Łódź apparently) and the results should sort themselves out.

This issue will also see an improvement with the use of secondary importance but servers need a full reimport to take complete advantage of this. This is unlikely to happen before October.
