### ISSUE TITLE
Nominatim Connection Timeout

### ISSUE THREAD

**Issue by shriyashfinov8** [osm-search/Nominatim#3529]
We have hosted a data collection and standardization service on aws lambda instances
There are in total 3 instances dev, sandbox and prod
As of now, the dev instance works perfectly fine, but the other two instances get following error when requested any of the nominatim urls
Example Url : https://nominatim.openstreetmap.org/search?q=Lisle,%20Ill&format=json&addressdetails=1

## What result did you get?
requests.exceptions.ConnectTimeout: HTTPSConnectionPool(host='nominatim.openstreetmap.org', port=443): Max retries exceeded with url: /search?q=Lisle,%20Ill&format=json&addressdetails=1 (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x7faaa768fd40>, 'Connection to nominatim.openstreetmap.org timed out. (connect timeout=None)'))

## What result did you expect?
Result expected : JSON data with lat, long, state, country name

**Comment by mtmail** [comment]
nominatim.openstreetmap.org makes no uptime guarantees. You shouldn't use it in production system https://operations.osmfoundation.org/policies/nominatim/
