### ISSUE TITLE
Poor quality results for neighborhood queries (zoom level 14)

### ISSUE THREAD

**Issue by mod3330** [osm-search/Nominatim#3538]
While queries at zoom level 13 generally work pretty well, I have noticed several inconsistent results for queries at zoom 14. This affects different countries. I have gathered some representative examples here.

## Lahti, Finland

https://nominatim.openstreetmap.org/ui/reverse.html?lat=60.95791&lon=25.67280&zoom=14

This matches a place=neighborhood that is almost 2 km away from the original location. The same query at zoom level 13 matches the expected place=suburb (Liipola). It seems that Liipola "loses" just because it is not a place=neighborhood.

## Milan, Italy

https://nominatim.openstreetmap.org/ui/reverse.html?lat=45.48304&lon=9.21327&zoom=14

This returns only the admin level 10 boundary (Municipio 3). Meanwhile at zoom level 13 we get a place=suburb (Loreto), which is finer-grained and the expected result. Shouldn't the zoom 14 query give a finer result than the zoom 13 one?

## Trentino, Italy

https://nominatim.openstreetmap.org/ui/reverse.html?lat=46.16211&lon=11.10783&zoom=14

This returns a place=isolated_dwelling. According to the [docs](https://nominatim.org/release-docs/develop/api/Reverse/#result-restriction) at zoom level 14 we should be getting "neighborhood", not "any settlement". The isolated dwelling would make sense at zoom level 15. Actually the result to zoom 15 is far worse; it is in a completely different village.

## Darmstadt, Germany

https://nominatim.openstreetmap.org/ui/reverse.html?lat=49.84965&lon=8.63038&zoom=14

This returns a postal code. Ditto for zoom 15. The same query at zoom 16 matches the nearest street and contains the expected place=quarter (Heimstätten-Siedlung).

**Comment by lonvia** [comment]
The only actionable item here is the part about postcodes. Might be worth pushing them into their own layer. They are currently part of the `address` layer but that might indeed not make particular sense.

**Comment by mod3330** [comment]
Sorry, but could you please elaborate why the other cases are not "actionable"? Are you saying these are tagging errors or...?

**Comment by mod3330** [comment]
OK, I can understand that it is challenging to improve upon the first case since the areas are not well-defined.

But what about the two other cases in Italy? Why is zoom=14 returning coarser-grained results than zoom=13? I assume it is trying to find a place=neighborhood there, but there isn't any. But then why not return the ok-ish result of place=suburb (like the zoom=13 query does)?

And, since you are referencing the documentation, why is it that in Trentino we get a place=isolated_dwelling at zoom level 14? OSM Wiki defines those as "the smallest kind of human settlement." Hence that should only ever appear at zoom level 15, "any settlement", nothing above that.
