### ISSUE TITLE
Potentially missing data in the nominatim api?

### ISSUE THREAD

**Issue by GuardsmanPanda** [osm-search/Nominatim#3540]
## What did you search for?
I used the /lookup endpoint in the API in an attempt to get the geojson for the province.
https://nominatim.openstreetmap.org/lookup?format=jsonv2&osm_ids=R1902947

## What result did you get?
Empty response

## What result did you expect?
The data that is available here.
https://www.openstreetmap.org/relation/1902947

## Further details
This lookup method has reliably worked for hundreds of similar relations, and the last change on this one is 6 months ago, it does not appear to be deleted, I might be missing something obvious but I am not sure what.

Here is an example of a working query 
https://nominatim.openstreetmap.org/lookup?format=jsonv2&osm_ids=R1898961

**Comment by mtmail** [comment]
Is a data issue. The relation isn't closed. It has two missing ways. http://ra.osmsurround.org/analyzeMap?relationId=1902947 (zoom in on the blue map markers).

**Comment by mtmail** [comment]
I see somebody (you?) have fixed the relation in the OSM data. Thank you. Nominatim finds it now.
