### ISSUE TITLE
Wrong Postal Code

### ISSUE THREAD

**Issue by LittleB0b** [osm-search/Nominatim#3545]
## What did you search for?
https://nominatim.openstreetmap.org/reverse?format=json&lat=44.602689342612571&lon=5.01183457883026584

## What result did you get?

"address": {
    "shop": "La marge",
    "house_number": "60",
    "road": "Rue du Commandant Chaix",
    "village": "Pont-de-Barret",
    "municipality": "Nyons",
    "county": "Drôme",
    "ISO3166-2-lvl6": "FR-26",
    "state": "Auvergne-Rhône-Alpes",
    "ISO3166-2-lvl4": "FR-ARA",
    "region": "France métropolitaine",
    "postcode": "16160",
    "country": "France",
    "country_code": "fr"
  }

## What result did you expect?
Wrong Postal Code :
"address": {
    "shop": "La marge",
    "house_number": "60",
    "road": "Rue du Commandant Chaix",
    "village": "Pont-de-Barret",
    "municipality": "Nyons",
    "county": "Drôme",
    "ISO3166-2-lvl6": "FR-26",
    "state": "Auvergne-Rhône-Alpes",
    "ISO3166-2-lvl4": "FR-ARA",
    "region": "France métropolitaine",
    "postcode": "16160", => 26160
    "country": "France",
    "country_code": "fr"
  }

**Comment by mtmail** [comment]
@LittleB0b Only the postcode for the one address (the bookstore) is affected. https://overpass-turbo.eu/s/1RLp You can edit it on OpenStreetMap's website https://www.openstreetmap.org/node/10712459923 It's pretty clear from the other addresses nearby that the first digit is wrong.
