### ISSUE TITLE
Asignment error to large areas place:country, admin_level:15

### ISSUE THREAD

**Issue by makis** [osm-search/Nominatim#355]
Original Search: "Heliconias Lodge, Bijagua"
Returns: 

Puentes Colgantes de Heliconias Lodge   highway:path    way 141500490   15  0   details >
Bijagua     place:village   node 859538130  15  0   details >
**El Jardín    place:hamlet    node 2526134719     15  0   details >
Toro Amarillo   place:county    node 3840893700     15  0   details** >
Alajuela    place:state     relation 3222933    4   0   details 

Notes:
1. Heliconias is correct on the map, but does not lie within El Jardin in Bijagua.
2. Toro Amarillo is a river and a neighbourhood of Guapiles but not a county.  Neither Heliconias nor Bijagua lie within Toro Amarillo. In fact, Toro Amarillo is probably 200X300m at over 100km from Bijagua. It's also not where Nominatim shows it on the map.

I only mention this because small data errors apparently cause broad systematic asignment errors in Nominatim. I didn't want to remove the data related to Toro Amarillo and with it the trigger to the erroneous asighnment.

Cheers,

Mark

**Comment by lonvia** [comment]
It might be worth to restrict the radius of county and state nodes a fair bit, given that counties and states are mostly mapped as relations these days. The large radius is from the days where we only had nodes for counties and it simply chose the closest one, which was a good heuristic then.

The issue with town vs. hamlet vs. suburb is more complicated as mappers use these tags very inconsistently. We are goign to have to find a different approach to figure out what lies within what.

I see that somebody has added a [county boundary](http://www.openstreetmap.org/relation/5657078) for Toro Amarillo but there seems to be a dispute if it is level 8 or 10. In any case, as the county node has now been added as a label, there should be no more misassignments in newly added data.

**Comment by lonvia** [comment]
This is really old and the address assignment algorithm has changed significantly lately. Closing.
