### ISSUE TITLE
/reverse unusual http status code returned on error

### ISSUE THREAD

**Issue by Martin-happy** [osm-search/Nominatim#3556]
**Describe the bug**
I wonder whether the status-code returned for an error case is intended?
This also applies for nominatim running on nominatim.openstreetmap.org.

In my case, I'm running the REST-api of nominatim (in docker) using the standard apache service.

**To Reproduce**
This can also be reproduced on the public API:

```bash
curl -v https://nominatim.openstreetmap.org/reverse\?format\=jsonv2\&lat\=-2.45662302001619\&lon\=%208.562215996347591
```

result (shortened) showing the error with status **200**:
```bash
... 
< HTTP/2 200
< server: nginx
< date: Mon, 07 Oct 2024 08:09:31 GMT
< content-type: application/json; charset=utf-8
< content-length: 29
<
* Connection #0 to host nominatim.openstreetmap.org left intact
{"error":"Unable to geocode"}%
```

**Software Environment (please complete the following information):**

- Nominatim version: **4.5.0** (I expect that to be deployed under nominatim.openstreetmap.org)

As a developer using the API I'd like to be able to interpret the response based on the http-status code.
The current implementation (returning 200 also for error cases) puts the burden, of interpreting onto the client.

As the error is caused by the user's input, I'd expect a **400** in my case.

**Comment by mtmail** [comment]
There is no data in OpenStreetMap around those coordinates, it's off the coast of Africa in the middle of an ocean. You should interpret the response as "no results found".

A user error looks like this: `{"error":{"code":400,"message":"Parameter 'lon' missing."}}`

The Nominatim project is very old (oldest git commit about 14 years) and changing the error behavior now would break the API for too many users. We collect some ideas for a version 2 of the API (https://github.com/osm-search/Nominatim/milestone/1) but there's no timeline.

At https://nominatim.org/release-docs/latest/customize/Result-Formatting/ you can see the latest refactoring in Nominatim version 4.5 already put the existing output routines into 'v1' directory/namespace in preparation for future versions. If you feel strongly about the HTTP codes you could experiment with the customization in your location installation.

**Comment by Martin-happy** [comment]
Thanks for your response @mtmail.
I understand that changing the API conflicts in backwards compatibility.

It still feels non-standard, to me returning fundamentally different json schemas with the same 200 status code.
So I will try to tackle this on my end.
