### ISSUE TITLE
Toeplerstraße 3, 13627 Berlin not found while it exists in OSM

### ISSUE THREAD

**Issue by mrflix** [osm-search/Nominatim#3559]
## What did you search for?

Toeplerstraße 3, 13627 Berlin
https://openstreetmap.org/ui/search.html?street=Toeplerstraße+3&city=Berlin&county=Germany&postalcode=13627

## What result did you get?

"No search results found"

## What result did you expect?

I was expecting to find the address. If I search for the street on openstreetmap.org and right click "show address" on the house number, it returns Toeplerstraße 3, 13627 Berlin
![CleanShot 2024-10-10 at 09 24 42](https://github.com/user-attachments/assets/d73edbdb-6a19-4805-8fce-119223595180)
https://www.openstreetmap.org/search?lat=52.538037&lon=13.285199#map=19/52.538037/13.285200

**Comment by mtmail** [comment]
I think it's a tiny mistake in the URL. It says "county=Germany", it should be "country=Germany"

https://nominatim.openstreetmap.org/ui/search.html?street=Toeplerstra%C3%9Fe+3&city=Berlin&country=Germany&postalcode=13627
