### ISSUE TITLE
Translation into Italian language

### ISSUE THREAD

**Issue by gpsaliola** [osm-search/Nominatim#3567]
By entering this command, the results are shown in the local language (Greek) instead of Italian:

`https://nominatim.openstreetmap.org/reverse.php?format=xml&lat=38.2660322&lon=20.5373903&accept-language=it-IT`

I get:

`<reversegeocode timestamp="Tue, 22 Oct 2024 08:44:46 +00:00" attribution="Data © OpenStreetMap contributors, ODbL 1.0. http://osm.org/copyright" querystring="lat=38.2660322&lon=20.5373903&format=xml">
<result place_id="48024760" osm_type="relation" osm_id="13241359" ref="Δημοτική Ενότητα Πυλαρέων" lat="38.3062329" lon="20.5575979" boundingbox="38.2522602,38.4357787,20.5048468,21.1075571" place_rank="16" address_rank="16">Δημοτική Ενότητα Πυλαρέων, Δήμος Σάμης, Περιφερειακή Ενότητα Κεφαλληνίας, Περιφέρεια Ιονίων Νήσων, Αποκεντρωμένη Διοίκηση Πελοποννήσου, Δυτικής Ελλάδας και Ιονίου, 280 81, Grecia</result>
<addressparts>
<city>Δημοτική Ενότητα Πυλαρέων</city>
<municipality>Δήμος Σάμης</municipality>
<county>Περιφερειακή Ενότητα Κεφαλληνίας</county>
<state_district>Περιφέρεια Ιονίων Νήσων</state_district>
<ISO3166-2-lvl5>GR-F</ISO3166-2-lvl5>
<state>Αποκεντρωμένη Διοίκηση Πελοποννήσου, Δυτικής Ελλάδας και Ιονίου</state>
<postcode>280 81</postcode>
<country>Grecia</country>
<country_code>gr</country_code>
</addressparts>
</reversegeocode>`

In English it works correctly:

`https://nominatim.openstreetmap.org/reverse.php?format=xml&lat=38.2660322&lon=20.5373903&accept-language=en-US`

`<reversegeocode timestamp="Tue, 22 Oct 2024 08:51:24 +00:00" attribution="Data © OpenStreetMap contributors, ODbL 1.0. http://osm.org/copyright" querystring="lat=38.2660322&lon=20.5373903&format=xml">
<result place_id="47645549" osm_type="relation" osm_id="13241359" ref="Pylaros Municipal Unit" lat="38.3062329" lon="20.5575979" boundingbox="38.2522602,38.4357787,20.5048468,21.1075571" place_rank="16" address_rank="16">Pylaros Municipal Unit, Sami Municipality, Kefallonia Regional Unit, Ioanian Islands, Peloponnese, Western Greece and the Ionian, 280 81, Greece</result>
<addressparts>
<city>Pylaros Municipal Unit</city>
<municipality>Sami Municipality</municipality>
<county>Kefallonia Regional Unit</county>
<state_district>Ioanian Islands</state_district>
<ISO3166-2-lvl5>GR-F</ISO3166-2-lvl5>
<state>Peloponnese, Western Greece and the Ionian</state>
<postcode>280 81</postcode>
<country>Greece</country>
<country_code>gr</country_code>
</addressparts>
</reversegeocode>`

Am I missing something?
Thanks

**Comment by mtmail** [comment]
The issue is missing data. Somebody needs to add the Italian names to all address components. For example the `<county>` is https://www.openstreetmap.org/relation/957829 and there's only names in 6 languages. English got translated more often than Italian. If the Italian translation is missing then Nominatim returns the `name`, which is Greek.

**Comment by mtmail** [comment]
You can set multiple languages: https://nominatim.openstreetmap.org/reverse.php?format=xml&lat=38.2660322&lon=20.5373903&accept-language=it-IT,en-US Then Nominatim looks for Italian first, then English. But that means that `<country>` is Italian and most other fields are English, you'd have a mix of languages.

**Comment by gpsaliola** [comment]
Great suggestion. 
Many thanks.
