### ISSUE TITLE
County Waterford search returning Waterford City results only

### ISSUE THREAD

**Issue by cpalmerhfl** [osm-search/Nominatim#3569]
I'm using Apify with the Google Maps Scraper to webscrape Ireland county by county. 

I've worked through each of the 26 counties, and have successfully pulled 25 datasets without issue based on keywords and the geolocation "County {name}".

I'm trying to pull data for County Waterford in Ireland however, and the geographic region is purely pulling from the city boundary (I've tried different location fields, enclosing the search term in " "). 

When I look at the Nominatim for County Waterford, there are two entries and the first is the city - that's not what happens for other counties. https://nominatim.openstreetmap.org/ui/search.html?q=County+Waterford

Is there an underlying issue with the data here?

**Comment by lonvia** [comment]
The [place node of Waterford](https://www.openstreetmap.org/node/52263292) had a translation of the city name with 'County' in it. [Fixed that](https://www.openstreetmap.org/changeset/158490050).

> I'm using Apify with the Google Maps Scraper to webscrape Ireland county by county.

You are aware that OpenStreetMap offers free and legally usable geodata for Ireland?
