### ISSUE TITLE
Selwyn Street, Eastwood returns S65 1QW postcode in new installation, should be S65 1QN

### ISSUE THREAD

**Issue by mtmail** [osm-search/Nominatim#3572]
### Discussed in https://github.com/osm-search/Nominatim/discussions/3570

<div type='discussions-op-text'>

<sup>Originally posted by **patway211** October 29, 2024</sup>
We are getting different UK postcode for many  Lat,Long pair as compared to nominatim.opentreetmap in a server with fresh installation of nominatim full planet. Updated Database and GB postcode.

[...]

Here is an example :
Lat : 53.4367566
Long -1.3470283

In nominatim.openstreetmap 
https://nominatim.openstreetmap.org/ui/reverse.html?lat=53.4367566&lon=-1.3470283&zoom=18
Selwyn Street, Eastwood, Rawmarsh, Rotherham, South Yorkshire, England, 
S65 1QN, 
United Kingdom 

In Self hosted : 
Selwyn Street, Eastwood, Rawmarsh, Rotherham, South Yorkshire, England, 
S65 1QW,
United Kingdom

The post code expected : S65 1QN
[...]
</div>

**Comment by lonvia** [comment]
The centroid of the street is bad. I could swear that ST_PointOnSurface() had changed at some point to return sane defaults for lines but apparently not.

The difference between nominatim.org and your instance simply comes from using different versions of the UK postcode files. Both instances have the centroid issue as far as I can see.

**Comment by lonvia** [comment]
Turns out that ST_PointOnSurface() always returns an existing point for lines. For most streets that behaviour is perfectly fine (and the most efficient way to do it). Only when the road consists of a linestring with only two points do we end up with a badly placed centroid. Solution is to use ST_LineInterpolatePoint for linestrings.

**Comment by mtmail** [comment]
>  from using different versions of the UK postcode files.

I checked the last 13 Royalmail data releases back to 2022-02, but the coordinates for those two postcodes haven't changed.

**Comment by mtmail** [comment]
I did a test import of South Yorkshire area and see it fixed

```
nominatim reverse --lat 53.4367566 --lon -1.3470283 --zoom 18 --addressdetails | grep postcode
        "postcode": "S65 1QN",
```
