### ISSUE TITLE
"Perth" (29277817) can't be found, but works with older extract

### ISSUE THREAD

**Issue by gineika** [osm-search/Nominatim#3573]
I guess, it's because of this change: https://www.openstreetmap.org/relation/11343564/history/12

"Perth" now has no parent place ID.

# Older extract

```
nominatim import --osm-file australia-240801.osm.pbf
nominatim search --query "Perth"
```

"Perth" (29277817) is listed. Matches: https://nominatim.openstreetmap.org/search?format=jsonv2&q=Perth

Parent place is set:

```sql
select parent_place_id, linked_place_id from placex where osm_id = 29277817;
-- parent_place_id: ID of "City of Perth" (11343564)
-- linked_place_id: null
```

# Latest extract

```
nominatim import --osm-file australia-latest.osm.pbf
nominatim search --query "Perth"
```

"Perth" (29277817) is not listed.

Parent place is null, but linked place is set:

```sql
select parent_place_id, linked_place_id from placex where osm_id = 29277817;
-- parent_place_id: null
-- linked_place_id: ID of "City of Perth" (11343564)
```

**Comment by mtmail** [comment]
nominatim.openstreetmap.org seem to show the old behaviour right now. Which Nominatim version are you using (`nominatim --version`)? The extracts are from https://download.geofabrik.de/ ?

**Comment by mtmail** [comment]
I did a local import and can confirm what you see.

```
$ nominatim search --query "Perth" | jq -c '.[] | [.osm_type, .osm_id, .category, .type, .display_name]'
["relation",11343564,"boundary","administrative","City of Perth, Western Australia, Australia"]
["relation",11689210,"boundary","administrative","Perth, City of Perth, Western Australia, Australia"]
["relation",10604247,"boundary","administrative","Perth, Northern Midlands, Tasmania, 7300, Australia"]

$ nominatim details --relation 11343564
{
    "place_id": 131511,
    "parent_place_id": 130079,
    "osm_type": "R",
    "osm_id": 11343564,
    "category": "boundary",
    "type": "administrative",
    "admin_level": 6,
    "localname": "City of Perth",
    "names": {
        "name": "City of Perth",
        "name:en": "City of Perth",
        "_place_name": "Perth",
        "name:ar": "بيرث",
        "name:bn": "পার্থ",
        "name:de": "Perth",
        "_place_name:en": "Perth",
        "name:eo": "Perto",
        "name:es": "Perth",
        "name:fr": "Perth",
[...]
    },
    "addresstags": {},
    "country_code": "au",
    "indexed_date": "2024-11-02T22:51:51.886260+00:00",
    "importance": 0.24000999999999997,
    "calculated_importance": 0.24000999999999997,
    "extratags": {
        "capital": "4",
        "wikidata": "Q1855330",
        "wikipedia": "en:City of Perth",
        "linked_place": "city"
    },
    "rank_address": 16,
    "rank_search": 12,
    "isarea": true,
[...]
```

nominatim.openstreetmap.org currently runs Nominatim 4.5 but hasn't done a full import in months, it probably didn't pick up the change you mentioned yet but a new import would.

Nominatim merges two places when they represent the same. That's usually a node and relation of the same name and wikidata id (node inside the relation) but hints like setting an `admin_centre` or `label` role on a relation pointing to a node also work. One of the places can no longer be found by osm_type&osm_id, it simply doesn't have a database entry (`nominatim lookup` fails etc).

In this case Nominatim merged City of Perth (`admin_level=6`, https://www.openstreetmap.org/relation/11343564) and Perth (`place=city`, https://www.openstreetmap.org/node/29277817). The `nominatim details` command above shows the merged data, in `extratags->linked_place` it recorded the `place_type` of the node.

There's a mismatch, one say it's a county (admin_level=4), the other a city. Such a mismatch is common, especially with large cities which often can be both at the same time or have a special legal status or are neither (in Germany we have a "county-less-city" concept for example). There's never one good solution, some users (use-cases) want the city as first result, some the county.

I think ideally in OSM data we'd have a relation for county and one for city, I can imagine the boundaries both would overlap. Next best I think is to undo the https://www.openstreetmap.org/relation/11343564/history/12 change. Was the goal to remove "City of Perth" from map rendering, or to move the "Perth" label to a different location on the map maybe?

**Comment by gineika** [comment]
"City of Perth" is a small area (centre) of Perth.

Perth (https://www.google.com/maps/place/Perth+WA,+Australia/) should have a boundary. Then https://www.openstreetmap.org/node/29277817 could be linked to it.

Something like Sydney. Boundary - https://www.openstreetmap.org/relation/5750005. Linked place - https://www.openstreetmap.org/node/13766899.

But I'm not familiar with OSM to add these changes.

**Comment by gineika** [comment]
```sql
select
  *
from
  placex a
join
  placex b
on
  a.linked_place_id = b.place_id
where
  a.name->'name' != b.name->'name'
and
  a.extratags->'wikidata' != b.extratags->'wikidata'
```

| osm_id | name | wikidata | osm_id  | name | wikidata |
| --- | --- | --- | --- | --- | --- |
| 113724008 | "Wagga Wagga" | "Q459600" | 6247060 | "Wagga Wagga City Council" | "Q820153" |
| 20920968 | "Wollongong" | "Q187861" | 6303077 | "Wollongong City Council" | "Q56477626" |
| 21477953 | "Ipswich" | "Q1009253" | 11675604 | "Ipswich City" | "Q1631867" |
| 1546628274 | "Brisbane" | "Q34932" | 11677792 | "Brisbane City" | "Q917682" |
| 145620822 | "Gold Coast" | "Q140075" | 11675459 | "Gold Coast City" | "Q1069385" |
| 29277817 | "Perth" | "Q3183" | 11343564 | "City of Perth" | "Q1855330" |
| 32566858 | "Mandurah" | "Q595542" | 11690490 | "City of Mandurah" | "Q1664472" |

All should appear in the search results.

The code could probably be improved to not link/hide rows if names and Wikidata IDs don't match.

**Comment by lonvia** [comment]
The label member is indeed the problem. If the "City of Perth" and "Perth" are not the same, then this is wrong tagging. The label member is supposed to have the place node that represents exactly the same entity as the relation. Nominatim prefers the label member over any other matching method (wikidata tag or name). I've added a comment to the change and removed the label. It looks like the user was tweaking OSM data for Nominatim output.

On a more general note, it would probably be helpful to have area relations for these metropolitan areas. You can always tag them with `place=city`, if there is no real administrative entity for them. Just having a node for such a large area is bound to cause bad guesses on the side of user software.

**Comment by lonvia** [comment]
As expected, Nominatim is highly confused now in which order to put "City of Perth" and "Perth" in the address hierarchy. The admin_level=6 used by the city of Perth is usually reserved for county-like objects in the rest of the world, i.e. something above city-level.

**Comment by gineika** [comment]
@lonvia All Australian addresses are confusing. Take Sydney, for example: "Sydney, Council of the City of Sydney, New South Wales". "Council of the City of Sydney" is a small area of Sydney.

By area, the order should be:
New South Wales > Perth > City of Perth > Perth (suburb)

As far as I know, there's nothing between New South Wales and Perth.

This format could work for big cities:
https://nominatim.openstreetmap.org/search?format=jsonv2&addressdetails=1&accept-language=lt&q=senamiestis,%20vilnius

- state: Vilniaus apskritis = New South Wales
- state_district: Vilniaus miesto savivaldybė = N/A
- city: Vilnius = Perth
- suburb: Senamiesčio seniūnija = City of Perth
- suburb: Senamiestis = Perth

And for smaller places:
https://nominatim.openstreetmap.org/search?format=jsonv2&addressdetails=1&accept-language=lt&q=trakai

- state: Vilniaus apskritis
- state_district: Trakų rajono savivaldybė
- county: Trakų seniūnija
- town: Trakai

"Senamiesčio seniūnija" is smaller than the city, so it's labeled as a suburb. "Trakų seniūnija" is bigger than the town, so it's labeled as a county.

I assume it's a data issue and can't be fixed here?
