### ISSUE TITLE
Search includes vending machines

### ISSUE THREAD

**Issue by cmahnke** [osm-search/Nominatim#3574]
## What did you search for?

"Wilhelm-Weber-Straße 3, Göttingen"

## What result did you get?

https://www.openstreetmap.org/node/4331001915

## What result did you expect?

https://www.openstreetmap.org/way/125872373

**When the result in the right place and just named wrongly:** 

This is up to discussion, see:
https://www.openstreetmap.org/changeset/158641175

The contributor / maintainer referred to https://wiki.openstreetmap.org/wiki/Tagging_for_the_renderer

The change I did was reverted, there need so be a general consensus if the name needs to be unique or Nominatim need to apply a better filter. I suspect that this might be a problem in other cities as well.

**Comment by jengelh** [comment]
Observed output:

![1](https://github.com/user-attachments/assets/f1c16595-7078-40fa-b314-c6d142d6ff21)

Click more, and reveal:

![1more](https://github.com/user-attachments/assets/cee080b8-eee2-46b0-abe9-48bf28531ee0)

I am not participating in Nomatim as a developer (but I do elsewhere), and so can add  an interpretation what might be going on and why the expectations are supposedly not met.

* Priorities: The vending machine is a _direct string match_ to the search term, and might have a higher priority class than address matches.
* Asynchronous search: Sometimes, the all three results may be shown on the first search try.
* Format: As evident from the results, Nomatim's preferred text address format is hierarchial: "3, Wilhelm-Weber-Straße, Göttingen", which makes sense considering the worldwide practice of subdividing the world. "Wilhelm-Weber-Straße 3, Göttingen" is a locale-specific notation (and, from an information technology point of view, is as weird as the often-ridiculed North American M/Y/D calendar format). Searching for `3, Wilhelm-Weber-Straße, Göttingen` directly yields the expected address matches (and expectedly, none of the name matches).

**Comment by cmahnke** [comment]
@jengelh: Thanks for the extensiv analysis and description!

Anyways: I use Nominatim to GeoCode addresses, as it's tagline advertises:
> Nominatim uses OpenStreetMap data to find locations on Earth by name and address (geocoding)

That implies: 
* That (postal) addresses should have a higher priority than a numbered vending machine
* An addresse is resolved given the format usual for the locale native to the given address:

> Nominatim can power the search box on your website, allowing your users to type free-form queries (“Cafe Paris, New York”) in any language. It also offers a structured query mode (“postcode=12345”, “city=London”, “type=cafe”) that helps you to automate geocoding of extensive address lists.

All quotes taken from https://nominatim.org/

That said, the issue above needs to be sorted out. Certainly on the Nominatim side...

**Comment by mtmail** [comment]
The three results have the same address. The relevant ranking factor to look for in these results is the 'importance' score. It's based on the type of map feature. The `amenity=dentist` and `amenity=vending_machine` have the same score, it's higher than the `bulding=house`. https://nominatim.openstreetmap.org/search.php?q=Wilhelm-Weber-Stra%C3%9Fe+3%2C+G%C3%B6ttingen&format=jsonv2

Direct string match and local address format are irrelevant here. Those three simply have the exact same address (house number + street + city etc) and changing the query would affect all equally. What jengelh described as 'Asynchronous' could be possible. With 2 results having the same importance score it's kind of random which becomes the first result. 

nominatim.openstreetmap.org uses multiple servers. They should behave the same, results between them are not mixed together. I think you're both based in central europe so you likely used the same server.

@cmahnke wrote "I use Nominatim to GeoCode addresses". With the API you can set `layer=addresses` (https://nominatim.org/release-docs/latest/api/Search/#result-restriction). You can test it on https://nominatim.openstreetmap.org/ui/reverse.html (click 'advanced options'), but that's reminds me: I should add the same on the search.html page, too.

With `layer=addresses` the vending machine result is removed. I'm not sure why the dentist is still returned. Maybe it's not treated as POI. https://nominatim.openstreetmap.org/search.php?q=Wilhelm-Weber-Stra%C3%9Fe+3%2C+G%C3%B6ttingen&format=jsonv2&layer=address

In Nominatim default settings we already removed a couple of map features that should no longer be found. Traffic cameras, waste baskets, information boards. Recently I saw somebody adding a full address to a park bench or dog park even. (https://github.com/osm-search/Nominatim/commits/master/settings/import-extratags.lua) Even if they have name and address tags in OSM data it's unlikely people search for it. Maybe vending machine should be excluded, too.

**Comment by cmahnke** [comment]
@mtmail That's good news!
I haven't tried your suggestion yet, I need to figure out how to pass the layer using GeoPandas.

The vending machine is question is for selling parking tickets it (and other ones) have names assigned by the local municipality consisting for name of the street and an increasing number...
That looks exactly like an address. Please exclude them...
I guess this could be closed afterwards?

**Comment by lonvia** [comment]
I don't see any particular reason why vending machines should be excluded from being searchable. Nominatim is not just a search engine for addresses but for any OSM data.

If you absolutely require the result to be an address, use `layer=addresses` as described by @mtmail. Please note that this will also return POIs with an address. Simply igonre the name and type, if you are interested in the address part only.

If you don't know how to add additional parameters in your client, you also have the option of running your own instance with the "address" profile. This will exclude all POIs from your database to start with.

In the long term, I also have some ideas how to improve odd search results like this but implementation to this is still a long way off.

Closing this ticket as a "won't fix".

**Comment by cmahnke** [comment]
I'm sorry, but I don't get it: Why not providing sane defaults?
I've included the relevant quotes from https://nominatim.org/ above, those imply to me that finding addresses is (first class citizen) feature, while vending machines aren' mentioned at all.
This in turn implies that even while the need to set a specific layer on a short term, that shouldn't be required in general. A clear priority is needed somewhere: Either in terms of findability, that is, having results from the address always being first or by adjusting the description of features and capabilities on the https://nominatim.org/

Everything else seem to be a source of confusion for others as well or a lack of a clear project vision / common understanding of features.
