### ISSUE TITLE
Return the bigger object matching searched address

### ISSUE THREAD

**Issue by ls-1N** [osm-search/Nominatim#3589]
## What did you search for?

- [Mäe 6 Tartu](https://nominatim.openstreetmap.org/ui/search.html?q=m%C3%A4e+6+tartu&accept-language=en-US%2Cen)
- [Vaba 13 Tartu](https://nominatim.openstreetmap.org/ui/search.html?q=vaba+13+tartu&accept-language=en-US%2Cen)

## What result did you get?
Small sheds or garages.

## What result did you expect?
For both of them, I expected the bigger and more important residential buildings next to them with identical addresses.

**When the result in the right place and just named wrongly:** 
No. But FYI, this ⬆️ template subpoint should maybe have the word "is" 😛. Same for the one below it.

**When the result missing completely:**

## Further details

This is an issue I have noticed a lot when using openstreetmap.org in Tartu. I think the issue is nonexistent or less pronounced with OsmAnd~. The issue does not appear for each set of objects without a unique address - i.e. for some queries Nominatim returns the bigger object (residential building). An example being [Vaba 22](https://nominatim.openstreetmap.org/ui/search.html?q=vaba+22+tartu&accept-language=en-US%2Cen).

1. Is this an unfortunate side-effect of implementation details that cannot easily be fixed?
2. Is this something that can be improved on the Nominatim side?
    2.1 E.g. if multiple results with the same address, return the largest object first? However, this would only really help if there is access to an approximation of surface area. Sometimes the bigger (and usually more important) building has fewer nodes than the small side building. Ofc few buildings have their height or floor tags added, so can't base it off of that either. 🤔
3. Should all of these hundreds or thousands of map objects simply be edited in the OSM dataset? What should be changed?

I'm terribly sorry if this has been asked before. I searched for some issues here before being overwhelmed 😞. But I ultimately decided to attempt to contribute anyway since this has subjectively been the most glaring issue with OSM usability in the browser. 😅

**Comment by lonvia** [comment]
Somewhat related to #3444. I need to figure out why Nominatim has this obsession with taking the smallest possible object when deduplicating. I'd expect it to return the largest one just like you say.

That said, the duplication of addresses in that area is somewhat odd. Addresses are usually related to an entrance and I'd expect only the building containing the entrance to have the address tagged. But that is more a discussion for the [local community](https://community.openstreetmap.org/c/communities/fi/67) than for this issue tracker.

**Comment by ls-1N** [comment]
> That said, the duplication of addresses in that area is somewhat odd. Addresses are usually related to an entrance and I'd expect only the building containing the entrance to have the address tagged. But that is more a discussion for the [local community](https://community.openstreetmap.org/c/communities/fi/67) than for this issue tracker.

I suspect that is the result of importing a public dataset that also has an address duplicated for every building on a particular lot (unless they have their own distinct address). Whether it is a quirk of the specific data source or whether the whole legal apparatus sees the addresses this way, I cannot guess.
