### ISSUE TITLE
Reverse geocoding fails when no admin_level=2 boundary 

### ISSUE THREAD

**Issue by woodpeck** [osm-search/Nominatim#3595]
## What did you search for?

Attempted to reverse geocode a coordinate pair in Anguilla this morning, using a query that used to work earlier (and works again at the time of writing):

https://nominatim.openstreetmap.org/reverse?format=jsonv2&accept-language=en-US&lat=18.1954947&lon=-63.0750234&zoom=3

## What result did you get?

HTTP 200 OK / "Unable to Geocode"

## What result did you expect?

`{"place_id":389565794,"licence":"Data © OpenStreetMap contributors, ODbL 1.0. http://osm.org/copyright","osm_type":"relation","osm_id":2177161,"lat":"18.1954947","lon":"-63.0750234","category":"boundary","type":"administrative","place_rank":4,"importance":0.6366581903890984,"addresstype":"country","name":"Anguilla","display_name":"Anguilla","address":{"country":"Anguilla","country_code":"ai"},"boundingbox":["18.0615454","18.7951194","-63.6391992","-62.7125449"]}`

## Further details

The reason was that someone had downgraded Anguilla to `admin_level=3` in https://www.openstreetmap.org/relation/2177161/history/24 which prevented Nominatim from returning anything.

It would be good if there was some safety net that would catch such "overseas territories" cases and not return an error. (Arguably, apart from international waters there probably shouldn't be anything on the world that is not inside an `admin_level=2` but things like this *will* happen.)

**Comment by lonvia** [comment]
The fix actually falls back to the pre-set country data as a result. It's just too difficult to correctly guess the difference between a level-2 country set to level 3 and a level-2 country which has disappeared because of a broken boundary and contains a strange level-3 boundary that was never meant to be a country.
