### ISSUE TITLE
Unexpected objects in search results for a building address

### ISSUE THREAD

**Issue by rpahut** [osm-search/Nominatim#3603]
### Discussed in https://github.com/osm-search/Nominatim/discussions/3602

Searching for some building addresses with `layer=ADDRESS` in a DB imported with `NOMINATIM_IMPORT_STYLE=address` yields, on top of the building at the address, other unexpected POI-like objects.

Examples:
N5266350421, N5266417321 for [address](https://nominatim.openstreetmap.org/ui/search.html?q=%D0%9C%D0%BE%D1%81%D0%BA%D0%B2%D0%B0+%2C++%D0%BF%D1%80%D0%BE%D1%81%D0%BF%D0%B5%D0%BA%D1%82+%D0%97%D0%B0%D1%89%D0%B8%D1%82%D0%BD%D0%B8%D0%BA%D0%BE%D0%B2+%D0%9C%D0%BE%D1%81%D0%BA%D0%B2%D1%8B+%2C++1) (now removed).
N4682629046 for [address](https://nominatim.openstreetmap.org/ui/search.html?q=%D0%9C%D0%BE%D1%81%D0%BA%D0%B2%D0%B0%2C++%D0%90%D0%BA%D0%B0%D0%B4%D0%B5%D0%BC%D0%B8%D0%BA%D0%B0+%D0%90%D0%BD%D0%BE%D1%85%D0%B8%D0%BD%D0%B0+%2C+12%D0%BA3&layer=address).

The expected behavior is for POIs to be absent in a DB imported with `NOMINATIM_IMPORT_STYLE=address`, or if they has to be present, not be returned alongside the exact address match when there is one, or if they has to be returned, to be practically distinguishable from the exact address match.

**Comment by lonvia** [comment]
As already discussed in #3602: the presence of these objects when using the address import style is entirely expected. The POIs have an address mapped and therefore need to be imported. Nominatim cannot know in advance if the address will also be present on a building. The duplicates are filtered on output.

What should not happen is that the name of the POI object spills over into the address point. Without the POI type being set, the name is unrelated.

**Comment by rpahut** [comment]
I thought the name is a part of the address, it kinda makes sense.
Will removing it relieve the issue in some way?
