### ISSUE TITLE
Error Permission -  nominatim

### ISSUE THREAD

**Issue by felipesms** [osm-search/Nominatim#3607]
services:
  nominatim:
    container_name: nominatim
    image: mediagis/nominatim:4.5
    deploy:
      resources:
        limits:
          cpus: '6.0'
          memory: 16G
    restart: no
    ports:
      - "5080:8080"
    networks:
        - mynetwork
    environment:
      NOMINATIM_PASSWORD: 123456
      THREADS: 6
      PBF_URL: https://download.geofabrik.de/south-america/brazil-latest.osm.pbf
      PGDATABASE: nominatim    
    volumes:
      - /home/felipe/disco/vm_dados/nominatim:/nominatim
      - /home/felipe/disco/vm_dados/nominatim/database:/var/lib/postgresql/16/main 
      - /etc/localtime:/etc/localtime:ro          
         
    shm_size: 2gb

networks:
  mynetwork:
    driver: bridge

error

nominatim  | + sudo -E -u postgres psql postgres -c 'DROP DATABASE IF EXISTS nominatim'
nominatim  | NOTICE:  database "nominatim" does not exist, skipping
nominatim  | DROP DATABASE
nominatim  | + chown -R nominatim:nominatim /nominatim
nominatim  | + cd /nominatim
nominatim  | + '[' '' = true ']'
nominatim  | + sudo -E -u nominatim nominatim import --osm-file /nominatim/data.osm.pbf --threads 6
nominatim  | 2024-12-07 20:16:35: Using project directory: /nominatim
nominatim  | 2024-12-07 20:16:39: Creating database
nominatim  | createdb: error: connection to server on socket "/var/run/postgresql/.s.PGSQL.5432" failed: FATAL:  could not open file "global/pg_filenode.map": Permission denied
nominatim  | 2024-12-07 20:16:39: FATAL: Creating new database failed.
nominatim exited with code 1

**Comment by mtmail** [comment]
>  image: mediagis/nominatim:4.5

Please open an issue with https://github.com/mediagis/nominatim-docker/issues instead. They know more about Docker, docker-compoase, kubernetes and the permissions required from/to containers.
