### ISSUE TITLE
Stop Using gray on gray graphics - Gooooodddddddddd  FFS.

### ISSUE THREAD

**Issue by Phuxxi** [osm-search/Nominatim#3620]
I absolutely HATE Google Maps and Google - because they use gray on gray mapping - which is HARD to read without squinting and zooming in... 

![0198](https://github.com/user-attachments/assets/3b6736e1-2419-4339-8f4f-fd45fa2e0f1a)

And YOU people have chosen the exact same settings.

![0199](https://github.com/user-attachments/assets/562e1640-b74a-41b7-8596-527887f827f1)

AND nobody just stops doing this stupid shit, and no one has a setting selection - like a soft gray or similar back ground colour and plain BLACK LINES for the roads etc..

Here is a simple NATIONAL road map for Australia. It's easy to read.

![Simple Road Map](https://github.com/user-attachments/assets/257714f2-06cb-4485-8812-79f21f530ab7)

This is a bit more complex - but it's a good map.

![Uploading nebraska-road-map-free-printable-driving-maps.jpg…]()

**Comment by Phuxxi** [comment]
Just stop using soft colours that tend to be indistinct from all the other similar tones and shades of soft colours.

**Comment by mtmail** [comment]
This repository is for the software searching for addresses and places.
