### ISSUE TITLE
Adding new Special Phrases

### ISSUE THREAD

**Issue by MKergall** [osm-search/Nominatim#52]
I would like to add some (quite relevant I think) Nominatim "Special Phrases" for French language. 
I added some entries in the table here: http://wiki.openstreetmap.org/wiki/Nominatim/Special_Phrases/FR
Like: "Médecin", "Auto-école", "Mairie"
10 days later, those entries are still not effective in the openstreetmap.org service. 

What is the process to add new Special Phrases?

**Comment by Klofutar** [comment]
Could you please update it again?  I added Slovenian language (https://wiki.openstreetmap.org/wiki/Nominatim/Special_Phrases/SL).

**Comment by mtmail** [comment]
Please open a new issue. Comments on a 4 year old closed issue get lost too easy. Thanks!
