### ISSUE TITLE
isolated_dwelling or suburb wrongly included in address

### ISSUE THREAD

**Issue by boothym** [osm-search/Nominatim#575]
Came across a few situations where a distant isolated_dwelling or suburb is included in an address when it really shouldn't be. 

For example this street has a suburb in the name, which is 2.8km away: http://nominatim.openstreetmap.org/details.php?place_id=81662773. There is also a note here http://www.openstreetmap.org/note/777205 which was "near Halbeath, Kingseat, Fife..." in my RSS feed, when it should simply read "near Hill of Beath, Fife" as it is right beside the village node!

Another example is an address in this town, e.g.: http://nominatim.openstreetmap.org/details.php?place_id=91980307 - which includes an isolated_dwelling about 2.5km away from the street. Or this pub in the nearby village which is even further away from the isolated_dwelling: http://nominatim.openstreetmap.org/details.php?place_id=49079181

**Is there a problem with Nominatim or can these issue be solved by improving the OSM data in some way?**

**Comment by lonvia** [comment]
Nominatim is notoriously bad at those. For suburbs and similar it helps if you add the approximate area (tagging it with place=suburb/hamlet etc. as well or with landuse=residential, both works as long as there is a name tag with the same name as the node). For isolated_dwelling Nominatim really should reduce the search area, they are small by definition.

**Comment by boothym** [comment]
Happy to add an approx area, but is there a way to combine the two with a relation to avoid duplication?

**Comment by lonvia** [comment]
If they have the same name then Nominatim will automatically combine them.

**Comment by boothym** [comment]
Ok, I've added some areas and they've really helped with those searches 👍 The reason I mentioned relations is to help renderers (e.g. OpenCycleMap) from displaying two names, by connecting them together somehow.

I agree about the search area of isolated_dwelling - but you also need to look at suburbs. Where there is no area around a town/village, suburbs are included in search results almost 5km away - for example http://nominatim.openstreetmap.org/details.php?place_id=69652973

Surely reducing this to 1 or 2km would be much better?

**Comment by lonvia** [comment]
Areas for isolated dwellings and suburbs have been reduced in #1836.

Note that we haven't reimported the database. That means that a) hamlets and isolated dwellings will only disappear gradually as data in OSM is updated and b) there might be some odd artefacts as we change from old to new computation for small places. There will be a reimport eventually to get to a clean state but at the moment I'd like to see if the change breaks other stuff.
