### ISSUE TITLE
Choose a list of countries for update

### ISSUE THREAD

**Issue by spin0us** [osm-search/Nominatim#60]
In the installation wiki it is specified that we can limit the update source range using some local settings like

```
 @define('CONST_Replication_Url', 'http://download.geofabrik.de/europe/france-updates');
 @define('CONST_Replication_MaxInterval', '259200');     // Process up to 3 days updates in a run
 @define('CONST_Replication_Update_Interval', '86400');  // How often upstream publishes diffs
 @define('CONST_Replication_Recheck_Interval', '900');   // How long to sleep if no update found yet
```

Is there any way to specify multiple country ou region ?
In fact i only need some countries in the update process.

**Comment by mdeweerd** [comment]
This is an old closed thread, but I think that visitors can still benefit from the updated script for whic I created a gist:
https://gist.github.com/mdeweerd/9bc5f60f2d6733e907f3

**Comment by mtmail** [comment]
Thank you! Really helpful.

**Comment by anthologist** [comment]
The script by @mdeweerd doesn't work, precisely the command
/usr/bin/osmosis --rri workingDirectory=${DIR}/. --wxc ${FILENAME}.osc.gz
seems to not create any osc.gz file.
Any solution to this?

**Comment by RhinoDevel** [comment]
Thanks to @spin0us, @mdeweerd and everybody else!

[Here](https://gist.github.com/RhinoDevel/8a35ebd2a08166f328eca01ab005c6de) is an updated version that works with Nominatim 3.2.0, uses HTTPS and has some other tiny improvements (less hard-coded stuff, etc.):

https://gist.github.com/RhinoDevel/8a35ebd2a08166f328eca01ab005c6de

**Comment by ItBedna** [comment]
It can also be used to update multiple diffs of the same region and then index all together? Or I need to use update.php --index after every imported diff?

**Comment by mtmail** [comment]
The original question was from 2013. Nominatim no longer uses osmosis, but osmium, so the instructions are likely outdated. http://nominatim.org/release-docs/latest/admin/Import-and-Update/#updates

> Or I need to use update.php --index after every imported diff?

Importing marks places as unindexed (indexed_status > 1 in the placex table). The `update.php --index` then looks for those and processed them. So if you managed to import multiple countries/regions, then you only need to run `update.php --index` once. (Or rather the second time it won't any unindexed places).

**Comment by ItBedna** [comment]
Thank's, but for example: I need import 480.osc.gz, 481.osc.gz and 482.osc.gz diffs from http://download.geofabrik.de/europe-updates/000/002/. Can I import all files without indexing each file and index everything at the end once?
