### ISSUE TITLE
Reverse geocoder doesn't find housenumbers

### ISSUE THREAD

**Issue by tyrasd** [osm-search/Nominatim#66]
The reverse geocoding (address lookup) call apparently doesn't find housenumbers anymore. Instead only the nearest street is returned. The a look at the example listed on the [wiki](http://wiki.openstreetmap.org/wiki/Nominatim#Example).

**Comment by pashtika** [comment]
Please help me to know why following not pulling any data ??
http://nominatim.openstreetmap.org/?format=json&addressdetails=1&q=7584 E Big Cannon Drive,California,92808,US

**Comment by mtmail** [comment]
@pashtika: please open a new issue instead of commenting on a 2 year old closed issue.
