### ISSUE TITLE
When a name contain the word SAN does not find anything

### ISSUE THREAD

**Issue by javiermrr** [osm-search/Nominatim#702]
Hello.

When I search a School, Kindergarten and the name cotain the word SAN does not find anything.

Examples: 

School **San José de Calasanz**
https://www.openstreetmap.org/#map=18/40.02739/-3.59746

Query:
http://nominatim.openstreetmap.org/search.php?q=San+Jos%C3%A9+de+Calasanz%2C+Aranjuez%2C+Madrid&polygon_geojson=1&viewbox=

School **San Isidro**
https://www.openstreetmap.org/#map=18/40.03278/-3.59042

Query:
http://nominatim.openstreetmap.org/search.php?q=San+Isidro%2C+Aranjuez%2C+Madrid&polygon_geojson=1&viewbox=

If I active debug=1, I see that the word SAN is replace by S  ( S José de calasanz, S Isidro etc..)

**Comment by lonvia** [comment]
This should work with the new search algorithm.
