### ISSUE TITLE
Increasing zoom value reduces information in reverse geocoding

### ISSUE THREAD

**Issue by Mstriewe** [osm-search/Nominatim#704]
Consider the following two queries for reverse geocoding, which only differ in the zoom value:

Query 1: http://nominatim.openstreetmap.org/reverse.php?format=html&lat=51.484622236435&lon=8.337727189064&zoom=10
Query 2: http://nominatim.openstreetmap.org/reverse.php?format=html&lat=51.484622236435&lon=8.337727189064&zoom=14

Query 1 returns "Belecke, Warstein, Kreis Soest, Regierungsbezirk Arnsberg, Nordrhein-Westfalen, Deutschland", which is correct.
Query 2 returns "Altstadt, Belecke, Kreis Soest, Regierungsbezirk Arnsberg, Nordrhein-Westfalen, 59581, Deutschland", which is incomplete. Particularly it misses the "Warstein" bit.

Details for the result from query 2 (http://nominatim.openstreetmap.org/details.php?place_id=70478377) show an extra way of type "place:village", but as this has rank "Other: 19" it is not supposed to supress the relation for Warstein with rank "City", isn't it?

**Comment by lonvia** [comment]
Yes, [Warstein](http://www.openstreetmap.org/relation/153401) competes with [Belecke](http://www.openstreetmap.org/way/140053210) over who gets to define the city part of the address. The OSM tagging is completely right here. Unfortunately, it is very difficult for Nominatim to correctly guess if a village is part of a town or not. In that particular case we would know if we knew that we are in Germany and a Gemeinde is often a connecton of multiple smaller villages. So localized treatment will be needed. See also #213.

**Comment by Mstriewe** [comment]
Thanks for the explanation.

Given the fact that the details page mentioned above lists all potential elements of the address (with the ones considered irrelevant printed in light grey), I wonder if it is possible to add a parameter which forces Nominatim to show all these elements also in the JSON output. This would allow clients to decide on their own which city, town or village is relevant to them. This would solve the issue as well, as no data gets lost by an incorrect guess by Nominatim.

**Comment by Megachip** [comment]
@lonvia is there any way to help nominatim to guess right? E.g. setting the is_in attribute or putting the lower relation als child relation into the higher relation?

**Comment by lonvia** [comment]
The example has been fixed with the use of admin boundaries it seems. Hopefully works better in general with the new address computation.
