### ISSUE TITLE
border roads search is missing the correct town

### ISSUE THREAD

**Issue by arlas** [osm-search/Nominatim#785]
Every border way gets only one town, and the wrong one.

Possible causes:
1) tagging problem? border relation is "on top of" the street way (should the street way be part of the relation?)
2) nominatim cannot determine the correct name from name:left or name:right
3) nominatim cannot determine the correct location if way shares same point with border (or shares >= 1 point)

Example: Relation "San Giovanni la Punta" "eats" every border way (http://nominatim.openstreetmap.org/details.php?place_id=173232268)

Steps to reproduce the problem:

1a) Search "via nebrodi, viagrande" returns "Via Nebrodi/Via Maria Auxilium, San Giovanni la Punta, CT, SIC, 95029, Italia" (https://www.openstreetmap.org/way/78592609)
1b) Search "via nebrodi, san giovanni la punta" returns "Via Nebrodi/Via Maria Auxilium, San Giovanni la Punta, CT, SIC, 95029, Italia" (https://www.openstreetmap.org/way/78592609)
2) Search "via maria auxilium, viagrande" returns "Via Nebrodi/Via Maria Auxilium, San Giovanni la Punta, CT, SIC, 95029, Italia" (https://www.openstreetmap.org/way/78592609)
3) Search "via maria auxilium, viagrande" returns "Via Maria Auxilium, San Giovanni la Punta, CT, SIC, 95029, Italia" (https://www.openstreetmap.org/way/483320644)
4) Search "via maria auxilium, san giovanni la punta" returns "Via Nebrodi/Via Maria Auxilium, San Giovanni la Punta, CT, SIC, 95029, Italia" (https://www.openstreetmap.org/way/78592609)
5) Search "via maria auxilium, san giovanni la punta" returns "Via Maria Auxilium, San Giovanni la Punta, CT, SIC, 95029, Italia" (https://www.openstreetmap.org/way/483320644)

Reality:
search should (ever) give:
"Via Nebrodi, San Giovanni La Punta, CT, SIC, 95029, Italia" (using name:left)
"Via Maria Auxilium, Viagrande, CT, SIC, 95029, Italia" (using name:right)

So:
1a) should be removed, no "via nebrodi" is in "Viagrande"
1b) acceptable, but preferred name:left; no "via maria auxilium" is in "san giovanni la punta"
2) acceptable, but preferred name:right; street and town should be "Via Maria Auxilium, Viagrande"
3) totally wrong! that way is entirely in the correct border, and shares with border relation only one point! so should be "Viagrande" and not "San Giovanni la Punta"
4) should be removed
5) should be removed, totally wrong! that way is entirely in the correct border, and shares with border relation only one point! so should be "Viagrande" and not "San Giovanni la Punta"

**Comment by lonvia** [comment]
Nominatim does not support name:left, name:right. Until now I didn't even know that such a crazy situation exists. I'm tempted to call this an administrative error and tell you to go and fix your government. ;)

On a more serious note: this is very, very difficult to implement. Nominatim doesn't have any special provisions for roads along boundaries yet. Given that this case is rare globally (there are around 3000 highways with left/right name), that it is possible to find the right road with the right query and that the result contains both names, it is unlikely that this gets added any time soon.

An easier problem are addresses along such road because there the address point is clearly in one or the other administrative unit. This issue is already covered by #328. You should be careful to add appropriate addr:* tags, though.

Your example 5) is interesting. It is actually the results of making half of #328 work (being able to search by all cities a road crosses). The algorithm should indeed exclude boundaries that touch the road in only one point.

**Comment by arlas** [comment]
Sicily is full of this examples. If there is a simple solution (even with modifications on OSM) that can be followed even with some dataset changes.

1) i think that on nominatim actually a road is an element of 1 town relation (only); (it seems the one with the smallest ID number); that road should instead be part of all relations
2) yes, starting and ending point of a road shouldn't be checked and exluded from the boundary (not other points, though)
3) there are some address, but nominatim cannot easily follow them because of the corresponding roads
search "via trigona, 82" should clearly return "Trecastagni" but instead it returns "San Giovanni La Punta"
4) maybe there should be a check on distance between border way and relation border (or even better, inserting that way as part of the border relation). If the distance is 0 (overlapping ways) or way is part of the border (2 borders) there should be a check on name:left and right presence. Then we can check on 1 middle point translated of some meters left or right (90 degrees) to decide what name belongs to what relation. Tricky but possible

**Comment by lonvia** [comment]
The roads do get both relations assigned. That's why you can find it under both towns. The problem is only with displaying the address that appears in the result. There Nominatim has to decide for one or the other. That is the part that is not trivial.

**Comment by arlas** [comment]
I cannot find the road in both towns:
Example:
Via Trigona (multiple towns) should be of "Trecastagni", too
a piece of it (483320618) (http://nominatim.openstreetmap.org/details.php?place_id=171958889) has both towns but:
Trecastagni hasn't it : (http://nominatim.openstreetmap.org/details.php?place_id=172567217)
San Giovanni La Punta has it (http://nominatim.openstreetmap.org/details.php?place_id=173232268)

Nominatim gives only "San Giovanni La Punta" because only that town has that piece. It has somehow a priority (i think because of the smaller ID number)

**Comment by arlas** [comment]
for the displaying issue, i think it should give twice the same way, with two different towns.
if I search "via trigona" this way i can find (the same piece 483320618) listed twice with Trecastagni and San Giovanni La Punta and i can choose the town (seems crazy but people recognize the town more than the osm ID)
if I search "via trigona, Trecastagni" it will display only the "Trecastagni" one and not a misleading "via Trigona, San Giovanni La Punta" (noone will click that one).

**Comment by woodpeck** [comment]
Here is an example of a building where the boundary is *in between' the building and the road: https://nominatim.openstreetmap.org/ui/details.html?osmtype=W&osmid=113385216 - this results in the building being assigned the city of the road, even overriding the explicit addr:city setting. It also means that the address is *not* found when attempting forward geocoding, and an incorrect address shown when doing reverse.

**Comment by szydzio** [comment]
Hi! 
Has Nominatim started to support name:left, name:right ? 
I don't see these tags in the [list of it's searching index](https://github.com/osm-search/Nominatim/blob/master/settings/import-extratags.style), but somehow Nominatim manages to find correctly addresses such as [here](https://nominatim.openstreetmap.org/ui/details.html?osmtype=W&osmid=524862930&class=building) or [here](https://nominatim.openstreetmap.org/ui/details.html?osmtype=W&osmid=788712615).

**Comment by lonvia** [comment]
They have always been indexed (see `name:*`). Nominatim is just not able to choose the correct name when displaying the result.

**Comment by szydzio** [comment]
OK, many thanks for a quick answer :)
So - if I understand it correctly - for proper finding of addresses considering [this issue](https://github.com/osm-search/Nominatim/issues/912), in case of “border” streets, there has to be first of all a corresponding pair of name:left/right and addr:street, and the bi-name of the street itself in name=name_of_left_side / name_of_right_side plays a secondary role, right ?

**Comment by lonvia** [comment]
Most of the issues regarding roads crossing boundaries have been fixed. Moving the remaining corner cases into separate issues #2667 and #2658.
