### ISSUE TITLE
Feature request: XML and JSON-schema

### ISSUE THREAD

**Issue by Schupax** [osm-search/Nominatim#807]
It would be great to have a schema, makes the usage of this service much easier.

**Comment by lonvia** [comment]
We might do this for the next version of the API. The current one is not exactly schema-friendly.

**Comment by Misiu** [comment]
@lonvia schema would be awesome, but for now maybe You could paste response with all possible fields?
In Visual Studio we have option to generate classes based on XML or JSON.

**Comment by lonvia** [comment]
The examples on https://wiki.openstreetmap.org/wiki/Nominatim are the most complete examples you can get. The elements in the address part can have an unlimited number of keys, which is exactly the reason why I said the response is not schema-friendly.

**Comment by lonvia** [comment]
Closing in favour of #1697.
