### ISSUE TITLE
Nominatim utf-8 problems

### ISSUE THREAD

**Issue by usitnikov** [osm-search/Nominatim#86]
Hi all !
When i try to get search i have this:

Bad Request
Nominatim has encountered an error with your request.
Details: Illegal query string (not an UTF-8 string)

http://nominatim.gruzodrom.ru/search.php?q=%D0%A7%D0%B5%D0%BB%D1%8F%D0%B1%D0%B8%D0%BD%D1%81%D0%BA&viewbox=-120.06%2C49.1%2C120.06%2C-49.1

plz, help !

**Comment by ndroo** [comment]
Hey Guys, if possible can this get added to the *Wiki in a section other than the "updates" section (as i suspect that is optional), i ran into the same issue following the setup instructions and think it would be cleared if it was moved up the document.

* http://wiki.openstreetmap.org/wiki/Nominatim/Installation

**Comment by mtmail** [comment]
Hi @ndroo,
The ` ERROR: function transliteration(text) does not exist` error is rare and means an earlier steop in the installation returned an error. Adding to the instructions to repeat the step would likely return the same error.
I added the error message to the http://wiki.openstreetmap.org/wiki/Nominatim/Installation/Troubleshooting which hopefully makes it easier for future users (and Google searches) to find the solution.

Thanks!
