### ISSUE TITLE
Cyrillic "е" and "ё" should be considered the same character

### ISSUE THREAD

**Issue by Zverik** [osm-search/Nominatim#886]
Search results for e.g. "Савеловский" and "Савёловский" should produce identical results — maybe sorted differently, but with the same contents.

**Comment by tonynovi** [comment]
The problem could be solved with an adjustment to Nominatim/module/utfasciitable.h file.
Same mapping should be used for "е" "Е" "ё" "Ё" characters.
The adjustment should be made before build.

Similar problem occured with "г" and "Г" as they were mapped to different transliterations see #219

a version of utfasciitable.h file with fix for "Г" "г" "е" "Е" "ё" "Ё" is in attachment [utfasciitable.zip](https://github.com/openstreetmap/Nominatim/files/2537350/utfasciitable.zip)

**Comment by botanegg** [comment]
@tonynovi can you add mapping for "Й" "й" and "И" "и" ?
e.g "Гвардейская" and "Гвардеиская" is same

**Comment by Zverik** [comment]
But it's quite hard to mix these up. People do not write "и" instead of "й", unlike with "ё". These two words you use for an example are two different words. I'm against this.

**Comment by tonynovi** [comment]
@botanegg , in this particular case for "й" and "и" I am agree with @Zverik 
usage of "е" instead of "ё" is an acceptable option commonly used everywhere.
usage of "И" instead of "Й" is a spelling/typing error, so it's better to fix source data with "Воеикова"

p.s. @botanegg, you can modify attached file to get desired result in any text editor.

**Comment by JonathanMontane** [comment]
I'm not sure how relevant that is to this discussion, but Postgres 10 introduced some support for ICU collation which are designed to solve some of these issues.
https://wiki.postgresql.org/wiki/New_in_postgres_10#ICU_Collation_Support

**Comment by Vascom** [comment]
Any progress in solving this issue?

**Comment by lonvia** [comment]
The new ICU tokenizer solves these issues. "е"/"Е"/"ё"/"Ё" all map to "e",  "г"/"Г" correctly to "g".  "Й"/"й" and "И"/"и" are different letters. They map to "j"and "i" respectively.

Please be aware that it will still take a bit before the new tokenizer goes into production on osm.org.

**Comment by lonvia** [comment]
It's not deployed yet. Tokenizer changes require a full reimport, so it won't happen before I'm sure the code is stable.
