### ISSUE TITLE
Russian: place and admin_level=8 should not be the same address rank

### ISSUE THREAD

**Issue by freeExec** [osm-search/Nominatim#926]
https://nominatim.openstreetmap.org/details.php?place_id=165526562

now the wrong address:
```admin_level_4 -> admin_level_6 -> admin_level_8 -> street```
or
```admin_level_4 -> admin_level_6 -> place -> street```
the correct address should look like:
```admin_level_4 -> admin_level_6 -> admin_level_8 -> place -> street```

Place is always lower than admin_level 8.

**Comment by lonvia** [comment]
Analysing the Russian boundaries, this looks to be true for most of Russia except for the three federal cities. For the federal cities admin_level 8 is used for the suburbs (but only _inside_ the city boundary, not for the complete administrative area). To make things worse, the city area itself is only mapped as `place=city` and not part of the administrative hierarchy. We need to detect this situation and make and exception for those boundaries before admin_level 8 can be promoted to 'municipality level' to ensure it comes above cities/towns/villages.
