### ISSUE TITLE
Postcode search requires a space to return results

### ISSUE THREAD

**Issue by nicholasgriffinVF** [osm-search/Nominatim#927]
The postcode search functionality requires a space within the postcode in order to return results, while this is the correct, it isn't very user friendly.

Is there any way that we could make it so a postcode search with a space returns results for postcodes?

Here's an example:
https://nominatim.openstreetmap.org/search.php?q=le52el&polygon_geojson=1&viewbox=

**Comment by TLacey** [comment]
Is there any updates on supporting spaces within UK postcodes. As above, it's not very user friendly to have to use a space to return results.

**Comment by Codain** [comment]
@mtmail: Thanks for your pull request, I hope that such mechanism will be available soon on Nominatim to improve results!
