### ISSUE TITLE
Allow searching for words, not only complete titles

### ISSUE THREAD

**Issue by mardy** [osm-search/Nominatim#94]
Steps to reproduce the issue:
1) go to http://nominatim.openstreetmap.org
2) search for "Tikkurila" (a city in Finland)
3) search for "Prisma" (a supermarket in Tikkurila)
4) a lot of results are returned, but the "Prisma" supermarket in Tikkurila is not returned

The reason is that the official supermarket name is "Prisma Tikkurila", and it has been encoded in OSM by this title. However, "Prisma" is a chain of supermarkets, and users don't really know the complete name.
The same problem appies to other chains, such as "KotiPizza", whose shop in Tikkurila is called "KotiPizza Tikkurila".

So, I'd like for the search to return also those results which don't fully match the title (maybe split it by words, or just allow matching a substring).

**Comment by geekdenz** [comment]
"hala liku" gives matches on
https://nominatim.openstreetmap.org/search.php?q=hala+liku&polygon_geojson=1&viewbox=

However, "hala lik"
https://nominatim.openstreetmap.org/search.php?q=hala+lik&polygon_geojson=1&viewbox=
does not give any results at all.

Shouldn't it partially match and find the best matches for partial strings?

We have this as a requirement for one of our applications. I would be happy to contribute on this but would like to know what the status quo is on this first.

**Comment by lonvia** [comment]
That's not the kind of partial matching that this issue refers to. You are looking for search-as-you-type, I guess. Nominatim does not support that. Have a look at [photon](https://github.com/komoot/photon) instead. (For some ideas of coupling photon and Nominatim and photon more tightly to get a direct API endpoint for suggestions see [this year's GSOC topic on "Search suggestions for osm.org"](https://wiki.openstreetmap.org/wiki/Google_Summer_of_Code/2019/Project_ideas#Nominatim). That's still open.)

**Comment by johsin18** [comment]
>     2. search for "Tikkurila" (a city in Finland)
> 
>     3. search for "Prisma" (a supermarket in Tikkurila)
> 
>     4. a lot of results are returned, but the "Prisma" supermarket in Tikkurila is not returned

I am a bit confused with 2. and 3.  Do you mean that for both searches, the supermarket ist not returned?  If so, please make that very clear.

> The reason is that the official supermarket name is "Prisma Tikkurila", and it has been encoded in OSM by this title. However, "Prisma" is a chain of supermarkets, and users don't really know the complete name.

When searching for "Prisma" generally, I would not expect to find that supermarket anyways, given that generic name.  Are you suggesting this for a locally limited search?

**Comment by lonvia** [comment]
This one is also solved with the new Python frontend. Search now looks up partial and full matches at the same time giving a preference to the latter.
