### ISSUE TITLE
support tab as space delimiter

### ISSUE THREAD

**Issue by mtmail** [osm-search/Nominatim#967]
As reported in https://lists.openstreetmap.org/pipermail/geocoding/2018-March/001928.html

Test case:

1. curl -s 'https://nominatim.openstreetmap.org?q=berlin%20texas&format=json&limit=1'
2. curl -s 'https://nominatim.openstreetmap.org?q=berlin%09texas&format=json&limit=1'

The first is space separated and returns `Berlin, Washington County, Texas, 77832, United States of America`, the second is tab separated and returns no result.

**Comment by chatelao** [comment]
Thanks for the nice textcase

**Comment by chatelao** [comment]
Basically you could even include:
- LF (%10)
- HF (%11)
- FF (%12) 
- CR (%13)

**Comment by AdyanAhmed99** [comment]
Hey, I'd like to work on this issue if it is still required for Nominatim. I'm new to open source, so I might need some help getting started.
I have installed Nominatim locally but haven't imported the database yet as I think it is not required for this issue.

**Comment by lonvia** [comment]
You need to import something into your database to actually test your fix. We do not provide ready-made test databases. Ideally you end up with a test for this issue in `test/bdd/api/search/` but you still need to create the test database from https://www.nominatim.org/data/test/nominatim-api-testdata.pbf (see `test/README.md`).

On a general note, please do not comment on issues to ask for guidance. Use the mailing list instead, see also the [GSOC hint page](https://wiki.openstreetmap.org/wiki/User:Lonvia/GSoC_2020_Nominatim_Projects).

**Comment by krahulreddy** [comment]
I found out that this issue could be fixed by editing the ParameterParser class. Is this the right way of solving this issue? If yes, I'll go ahead and send a PR.

**Comment by krahulreddy** [comment]
My first attempt was by editing url-search-params.js file by editing find and replace, but this did not work. This file was not even being used(Not sure why! I commented the entire file but the search still works as earlier).

This is the fix I used for now in ParameterParser.php constructor:
`$this->aParams['q'] = str_replace('	', ' ', $this->aParams['q']);`

Also, this could be generalized over other white space characters

**Comment by mtmail** [comment]
`url-search-params.js` a [polyfill](https://github.com/inexorabletash/polyfill/) for older browsers, it only loads if the browser doesn't already support the feature. All recent browsers, with exception Internet Explorer 11, do https://caniuse.com/#search=URLSearchParams

Javascript is the wrong approach though. Not even 0.1% of Nominatim requests are via the website, it's all direct API requests like https://nominatim.openstreetmap.org/search.php?q=berlin&format=jsonv2

`ParameterParser.php` is a start. There are more parameters where a query might be submitted, like `&city=1` (https://nominatim.org/release-docs/develop/api/Search/)

The logic where a submitted query gets split into words is in `/lib/Phrase.php`, the line `        $this->aWords = explode(' ', $this->sPhrase);` Ideally you'd add your logic there, add 1-2 PHP tests in `test/php/` and a test in `test/bdd/`

`CONTRIBUTING.md` and `VAGRANT.md` have some instructions how to run tests.

If you get stuck or have further questions please use the mailing list or IRC channel (see https://wiki.openstreetmap.org/wiki/User:Lonvia/GSoC_2020_Nominatim_Projects)

**Comment by krahulreddy** [comment]
Phrase.php constructor does not receive %09-%13 
characters. They are somehow removed.

On further inspection, I found that this constructor is called by 
Geocode.php. The parameter passed itself does not have these characters. 
This line: 

`$sPhrase = $this->oDB->getOne(
                     'SELECT make_standard_name(:phrase)',
                     array(':phrase' => $sPhrase),
                     'Cannot normalize query string (is it a UTF-8 string?)'
                 );`

in Geocode.php alters the $sPhrase and removes those characters. Should 
I go ahead and look into the the implementation further, or is there any 
other way?

**Comment by lonvia** [comment]
Fixed with #1733 and 1734.
